src/cli/default-error-handler.js

merge conflict error does not provide any action to do something about it.
currently we do not handle diff/merge, so we should instruct to do it manually.

descriptive merge error

---

docs/getting-started.md

updated 'find a component' and made some grammar corrections

update and corrections

---

CHANGELOG.md
src/cli/command-registrar.js
src/scope/scope.js
src/utils/index.js
src/utils/is-numeric.js

- issue with installing deps from local cache instead of external
- exit code with only numeric values

install deps from local cache

---

docs/bit-component.md

supports this PR - https://github.com/teambit/bit/pull/149

explain @bit

---

e2e/hooks/javascript-hooks.e2e.js
e2e/typescript/typescript.e2e.js
src/consumer/component/consumer-component.js

add basic unit-tests for TypeScript

fix bug: dist file is not saved with "js" extension after commit

---

.babelrc
src/api/consumer/lib/build.js
src/cli/commands/public-cmds/build-cmd.js
src/consumer/component/consumer-component.js
src/consumer/component/sources/dist.js
src/consumer/component/sources/files.js
src/consumer/component/sources/index.js
src/jsdoc/parser.js
src/scope/models/component.js
src/scope/repositories/sources.js

changes:
1. moved file & dist representation to  vinyl
2. fixed bit create to work 
3.fixed tests

new build + create

---

src/api/consumer/lib/build.js
src/consumer/component/components-list.js
src/consumer/component/consumer-component.js
src/consumer/component/sources/dist.js

1. fixed build-all
2. removed write of map files - done by compiler

build-all feature

---

README.md

update for the readme file, to fit the new usage flow of Bit.

readme for new flow

---

CHANGELOG.md
e2e/commands/commit.e2e.js
e2e/commands/status.e2e.js
src/cli/command-registrar.js
src/cli/commands/public-cmds/add-cmd.js
src/cli/commands/public-cmds/commit-cmd.js
src/cli/commands/public-cmds/export-cmd.js
src/cli/commands/public-cmds/status-cmd.js
src/cli/templates/help.js

- imporved bit help
- improved commit, add, export and status outputs

outputs and help

---

CHANGELOG.md
src/cli/commands/public-cmds/add-cmd.js
src/cli/commands/public-cmds/build-cmd.js
src/cli/commands/public-cmds/clear-cache-cmd.js
src/cli/commands/public-cmds/commit-cmd.js
src/cli/commands/public-cmds/export-cmd.js
src/cli/commands/public-cmds/import-cmd.js
src/cli/commands/public-cmds/list-cmd.js
src/cli/commands/public-cmds/log-cmd.js
src/cli/commands/public-cmds/reset-cmd.js
src/cli/commands/public-cmds/search-cmd.js
src/cli/commands/public-cmds/show-cmd.js
src/cli/commands/public-cmds/status-cmd.js
src/cli/commands/public-cmds/test-cmd.js
src/cli/templates/help.js

adjusted descriptions to new help

Descriptions

---

src/consumer/component/components-list.js

Don't calculate nested deps when calculating modified component during bit status

Don't calculate nested deps when calculating modified component during bit status

---

e2e/commands/export.e2e.js
e2e/commands/list.e2e.js
src/cli/commands/public-cmds/list-cmd.js

adjusted list abstract output to new formats

list outputs

---

CHANGELOG.md
e2e/commands/export.e2e.js
src/cli/commands/public-cmds/list-cmd.js
src/scope/scope.js

- removed cache flag
- exception thrown on bit ls is now fixed

list issues and --cache removal

---

src/scope/repositories/sources.js

Fix a bug when you try to export a component to scope which contains one of the dependencies but with the wrong version

non-existing-version-only

---

CHANGELOG.md
src/api/consumer/lib/import.js
src/consumer/bit-map/bit-map.js

- fix bug - when you import authored component (and there is a newer version) it duplicate it in the .bit.map.json
- fix bug - when you import authored component it was added to bit.json dependencies

import authored component

---

package.json
src/api/consumer/lib/add.js

fixed issue with multiple test file written to bitmap

fix bit add for multipule files with -i

---

src/cli/templates/help.js

added deprecate and remove to bit help message

---

src/cli/commands/public-cmds/bind-cmd.js
src/cli/commands/public-cmds/commit-cmd.js

fixing some outputs to lowercase.

Lowercase outputs

---

CHANGELOG.md
e2e/commands/add.e2e.js
src/api/consumer/lib/add.js
src/cli/commands/public-cmds/add-cmd.js
src/utils/getMissingTestFiles.js
src/utils/index.js
src/utils/verifyTetsFiles.js

1.throw error msg if test file fails
2.add testfiles that are in same dir as impl

refactored bit add 

---

CHANGELOG.md
src/consumer/component/consumer-component.js

Show correct message / error when the tester has an exception during bit test

tester exception

---

src/api/consumer/lib/import.js
src/scope/models/component.js

- removed exception that caused a redundant CurrptedComponent exception to be thrown

corrupted component model and caching

---

README.md

1. Text changes
2. Added tutorials
3. Updated quick start workflow
4. Updated "why Bit" section

Extensive readme updates

---

README.md

* Fixed "BitSrc" to "bitsrc"
* Edited "why Bit"
* Fixed typos and grammar

Readme text and grammar updates

---

README.md

* updated why bit
* updated use cases
* updated languages

Updated readme texts

---

README.md

fixed getting started on readme

Fixed readme getting started

---

README.md

Description
features
use cases

Updated Readme/content fixex

---

src/api/consumer/lib/get-consumer-component.js
src/cli/commands/public-cmds/show-cmd.js

(when use show without the scope name)

fix show -v after export component 

---

README.md

- changed main text and key features

readme text changes

---

README.md

Changed and updated main content.

Update readme/main content grammar and structure

---

README.md

Updated text for a clearer message and better understanding.

update README / updated text

---

README.md

* Grammar fixes
* Spelling
* Structure
* Description
* Use cases
* Motivation

Updated readme / grammar, structure, content

---

README.md

Updated readme / minor description changes

---

README.md

Updated general description and bullets

Update readme / description and bullets

---

README.md

added twitter CTA badge to readme.md
-
-
-

readme.me/added twitter badge

---

package.json

restore old behavior of requiring package installation

---

README.md

update readme \ grammer + links + docs

---

README.md

- Fixed broken links
- Edited how it works
- Edited use cases and examples
- Edited motivation

Readme update/ extensive updates 

---

CHANGELOG.md
src/scope/network/network-lib.js
src/scope/network/ssh/ssh.js

- add entered username from prompt to context for server side hooks

add entered username from prompt to context for server side hooks

---

e2e/commands/show.e2e.js
src/cli/templates/component-template.js

fix print of show command

---

src/plugins/wix/stylable.js

added validation of mainfile

---

src/api/consumer/lib/init.js
src/cli/commands/public-cmds/init-cmd.js
src/constants.js
src/consumer/consumer.js
src/scope/scope.js
src/utils/fs/propogate-until.js

Feature/move .bit to .git

---

README.md

changed readme texts and content
-
-
-

update readme / content changes

---

e2e/commands/add.e2e.js
src/consumer/consumer-locator.js

fixed but when running bit add without bitmap and bit dir is inside .git directory

Bug/bit add with .git

---

src/cli/default-error-handler.js

as this error is what stops most developers from using bit, i'm adding a link to the docs to propose ways to resolve this issue.

add link to 'authentication issues' in docs

---

.circleci/config.yml
scripts/clone-bit-javascript.sh

add clone for bit-js in circle

---

CHANGELOG.md
src/cli/commands/public-cmds/clear-cache-cmd.js

[#729]-fix bit cc to clear module cache

---

CHANGELOG.md
src/api/consumer/lib/add.js

[#736]-Bug/gitignore block

---

src/api/consumer/lib/add.js

fixed missing flag for bitmap.getComponent

---

README.md

Minor text changes
[ci-skip]
- minor content updates
-
-

update readme / minor

---

README.md

Replaced old link with new link to https://github.com/teambit/movie-app
[ci-skip]
-
-
-

update readme / fixed outdated link

---

.circleci/config.yml
e2e/bitsrc-tester.js
e2e/commands/import.e2e.js
e2e/flows/pad-left-and-is-string.e2e.js
src/consumer/bit-map/bit-map.js
src/consumer/component/sources/dists.js

fix bug when importing version then importing another version when compiler exists

---

CHANGELOG.md
src/consumer/component/consumer-component.js

support compilers which return promises

---

.flowconfig
package-lock.json
package.json
src/consumer/component/add-components/add-components.js
src/scope/models/symlink.js
src/scope/objects/object.js
src/utils/string/get-stringify-args.js

update flow-bin package to the latest version (0.66.0)

---

src/cli/commands/public-cmds/commit-cmd.js
src/cli/commands/public-cmds/move-cmd.js
src/cli/commands/public-cmds/untag-cmd.js

align \t for outputs

---

CHANGELOG.md
src/consumer/component/consumer-component.js
src/utils/fs/create-symlink-or-copy.js
src/utils/index.js

symlink tester env in isolated envs

---

README.md

made changes to "about" section in readme
[ci-skip]
-
-
-

update readme / about

---

e2e/commands/add.e2e.js
src/consumer/component/add-components/add-components.js

exclude files when using bit add command

---

CHANGELOG.md
src/consumer/consumer-locator.js
src/consumer/consumer.js

fix bugs when running bit commands not from the workspace root

---

src/consumer/bit-map/component-map.js
src/consumer/component/add-components/add-components.js

bug fix - unable to use bit move after importing a component

---

CHANGELOG.md
e2e/flows/es6-link-files.e2e.js
package-lock.json
package.json

support link-files with "export { default as ... }"; syntax

---

e2e/commands/merge.e2e.js
e2e/commands/use.e2e.js
e2e/e2e-helper.js
e2e/flows/pad-left-and-is-string.e2e.js

Fix bit-merge and bit-use tests

---

CHANGELOG.md
e2e/commands/import.e2e.js
e2e/flows/vue.e2e.js
src/api/consumer/lib/import.js
src/cli/chalk-box.js
src/cli/commands/public-cmds/import-cmd.js
src/consumer/component/import-components.js

improve output of import command to show the imported versions

---

src/consumer/bit-map/bit-map.js

prevent duplications of same namespace+name in bitmap file

---

README.md

[ci-skip]
Fixed a broken sentence in readme.
-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/929)

udpate readme / small fix

---

src/scope/network/ssh/ssh.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/933)

fix ssh auth

---

CHANGELOG.md
e2e/commands/add.e2e.js
src/consumer/bit-map/bit-map.js
src/consumer/bit-map/component-map.js
src/consumer/component/add-components/add-components.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/932)

fix bit-add to enable marking files as tests of existing components

---

src/cli/commands/public-cmds/diff-cmd.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/938)

fix bit-diff to not show an empty line for files with no diff

---

CHANGELOG.md
e2e/e2e-helper.js
src/cli/commands/public-cmds/diff-cmd.js
src/utils/diff-files.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/942)

improve bit-diff to show the output with colors

---

src/cli/default-error-handler.js
src/scope/exceptions/resolution-exception.js
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/945)

fix ResolutionException error to show helpful data

---

package.json
src/consumer/login/login.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/943)

move login to redirect method

---

README.md

fixed typo in readme
[ci-skip]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/956)

update readme / fixed typo

---

CHANGELOG.md
e2e/commands/checkout.e2e.js
e2e/commands/diff.e2e.js
e2e/commands/import.e2e.js
e2e/commands/status.e2e.js
src/cli/commands/public-cmds/diff-cmd.js
src/cli/templates/component-template.js
src/consumer/component-ops/components-diff.js
src/consumer/component-ops/components-object-diff.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/960)

Improvement/combine bit-show-compare with bit-diff

---

README.md

replaced video link to the new video
[ci-skip]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/971)

Update readme / replace video

---

src/consumer/component-ops/components-object-diff.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/972)

bit-diff: remove "docs" property from the comparison

---

src/cli/default-error-handler.js
src/scope/component-version.js
src/scope/exceptions/hash-mismatch.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/974)

Remove abstract error from hash mismatch

---

package.json
src/cli/commands/public-cmds/login-cmd.js
src/cli/default-error-handler.js
src/consumer/login/exceptions/index.js
src/consumer/login/exceptions/path-to-npmrc-not-exist.js
src/consumer/login/exceptions/write-to-npmrc-error.js
src/consumer/login/login.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/976)

add error handling bit login

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/992)

(wip) trying to fix AppVeyor

---

src/scope/network/ssh/ssh.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1006)

improve SSH error-message when the address was not found

---

src/scope/component-ops/tag-model-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1016)

fix storing the specs results during bit tag

---

CHANGELOG.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1022)

recognize packages required from d.ts files

---

e2e/commands/import.e2e.js
e2e/commands/test.e2e.js
src/consumer/bit-json/abstract-bit-json.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1028)

write environments to bit.json in a backward compatible manner

---

CHANGELOG.md
e2e/commands/export.e2e.js
e2e/flows/envs.e2e.js
package-lock.json
package.json
src/consumer/component/sources/abstract-vinyl.js
src/scope/repositories/sources.js
src/utils/eol.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1026)

fix import of binary files

---

src/scope/models/version.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1023)

do not store envsPackageDependencies if they are empty (for backward compatibility)

---

src/cli/default-error-handler.js
src/consumer/component/consumer-component.js
src/extensions/base-extension.js
src/extensions/compiler-extension.js
src/extensions/env-extension.js
src/extensions/exceptions/extension-get-dynamic-packages-error.js
src/extensions/exceptions/extension-init-error.js
src/extensions/exceptions/extension-load-error.js
src/extensions/tester-extension.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1027)

Handle errors during loading envs

---

src/api/consumer/lib/test.js
src/cli/default-error-handler.js
src/consumer/bit-map/bit-map.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1029)

change default fork level for bit test to ONE

---

e2e/e2e-helper.js
package-lock.json
package.json
src/consumer/bit-json/abstract-bit-json.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1031)

fix bit json envs backward compatibility

---

src/specs-runner/worker.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1032)

fix bit test loaders

---

src/scope/component-ops/tag-model-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1033)

fix storing the specs results on imported environment during bit tag

---

CHANGELOG.md
e2e/flows/custom-module-resolutions.e2e.js
e2e/flows/es6-link-files.e2e.js
e2e/flows/pad-left-and-is-string.e2e.js
e2e/typescript/typescript.e2e.js
package.json
src/consumer/component/consumer-component.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js
src/consumer/component/package-json.js
src/consumer/component/templates/postinstall.default-template.js
src/environment/environment.js
src/links/link-generator.js
src/scope/models/component.js
src/scope/models/version.js
src/scope/network/ssh/ssh.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1046)

Custom module resolution npm install

---

README.md

Edited description for Readme.
Top section + second section titles.
[ci-skip]
-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1045)

Update Readme / text changes

---

CHANGELOG.md
src/consumer/component-ops/import-components.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1048)

fix bit import -e flag

---

CHANGELOG.md
src/consumer/bit-json/consumer-bit-json.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1049)

fix - init deletes resolve modules from bit.json

---

CHANGELOG.md
e2e/commands/checkout.e2e.js
src/cli/default-error-handler.js
src/cli/templates/newer-version-template.js
src/consumer/consumer.js
src/consumer/exceptions/newer-version-found.js
src/scope/component-ops/tag-model-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1050)

throw an error when auto tag components has a newer version

---

CHANGELOG.md
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1051)

fix - after auto-tagging a component with a pending update - it became modified

---

CHANGELOG.md
e2e/commands/diff.e2e.js
src/consumer/component-ops/components-object-diff.js

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1052)

fix bit-diff after tagging component

---

CHANGELOG.md
e2e/commands/import.e2e.js
specs/scope/repositories/sources.spec.js
src/scope/models/component.js
src/scope/repositories/sources.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1053)

prevent overriding local tags from remote components upon import

---

src/api/consumer/lib/checkout.js
src/cli/loader/loader-messages.js

-
-
-
[ci-skip]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1061)

added loader for bit checkout

---

src/api/consumer/lib/status.js
src/cli/loader/loader-messages.js

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1060)

added loader for bit status

---

CHANGELOG.md
package.json
src/consumer/component-ops/components-diff.js

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1055)

handle bit diff for local components without specifying  scope

---

CHANGELOG.md
src/api/consumer/lib/list-scope.js
src/consumer/bit-map/bit-map.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1056)

fix - show component on bit list even when there is duplicate entries in bitmap file

---

CHANGELOG.md
src/api/consumer/lib/get-component-logs.js

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1064)

support running bit log on local components with scope

---

CHANGELOG.md
specs/scope/models/version.spec.js
src/extensions/base-extension.js
src/extensions/compiler-extension.js
src/extensions/env-extension.js
src/extensions/tester-extension.js
src/scope/models/version.js
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1070)

backward compatibility for components with environments with latest version

---

CHANGELOG.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1071)

fix handle tsx files when detectiveOption is empty

---

CHANGELOG.md
src/api/consumer/lib/login.js
src/cli/commands/public-cmds/login-cmd.js
src/consumer/login/login.js

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1076)

change no-launch-browser to suppress-browser-launch in bit login

---

CHANGELOG.md
src/specs-runner/worker.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1075)

fix unhandled rejection on bit test

---

src/api/consumer/lib/list-scope.js
src/cli/loader/loader-messages.js

-
-
-
[ci-skip]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1078)

add loader when running list on local components

---

CHANGELOG.md
src/cli/default-error-handler.js
src/consumer/component/consumer-component.js
src/extensions/env-extension.js
src/scope/exceptions/component-not-found.js
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1079)

show dependent component id when trying to install missing environment

---

CHANGELOG.md
e2e/commands/checkout.e2e.js
e2e/e2e-helper.js
src/api/consumer/lib/checkout.js
src/api/consumer/lib/diff.js
src/api/consumer/lib/export.js
src/bit-id/bit-id.js
src/cli/commands/public-cmds/checkout-cmd.js
src/cli/commands/public-cmds/merge-cmd.js
src/consumer/component/components-list.js
src/consumer/versions-ops/checkout-version.js
src/consumer/versions-ops/merge-version/index.js
src/consumer/versions-ops/merge-version/merge-version.js

- support `bit checkout latest` for checkout to the latest version
- add `--reset` flag to `bit checkout` command for removing local modifications
- add `--all` flag to `bit checkout` command for executing the checkout on all components
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1086)

Feature: support "latest", "--all" and "--reset" for bit-checkout

---

CHANGELOG.md
src/cli/commands/public-cmds/status-cmd.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1087)

add troubleshooting-isolating link to bit status

---

.circleci/config.yml

- set circle ci to run against bitsrc production
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1096)

Ci prod hub

---

CHANGELOG.md
src/consumer/component/consumer-component.js
src/scope/network/ssh/ssh.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1094)

show environments when running bit show on remote component

---

CHANGELOG.md
e2e/commands/commit.e2e.js
src/api/consumer/lib/commit.js
src/cli/commands/public-cmds/commit-cmd.js
src/consumer/consumer.js
src/scope/component-ops/tag-model-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1091)

add new flag `--skip-tests` to bit tag command

---

e2e/e2e-helper.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1097)

refactor e2e-helper file

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1099)

 configure CircleCI to run bit-javascript unit tests

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1107)

fix detection of "export * from" syntax of ES6 (bit-javascript)

---

README.md

- Replace png badge with svg for retina display
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1110)

Replace png badge with svg

---

e2e/commands/status.e2e.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1122)

bug fix - missing packages were not presented on Windows

---

CHANGELOG.md
e2e/flows/es6-link-files.e2e.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1124)

avoid trying tree shaking on CommonJS code (on bit-javascript)

---

src/links/link-generator.js
src/links/link-generator.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1133)

make the check of whether a link-file has "default" property safer

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1135)

update packages according to npm audit report

---

CHANGELOG.md
e2e/commands/import.e2e.1.js
e2e/flows/import-from-bit-hub.e2e.3.js
src/consumer/component-ops/write-components.js
src/consumer/component/package-json.js
src/links/link-generator.js
src/links/node-modules-linker.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1145)

fix bit-import of a component with authored dependencies

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1146)

update typescript version from 2.7 to 2.9

---

.circleci/config.yml

and enforce node_modules cache invalidation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1149)

update circle image to node version 6.14.3

---

src/consumer/component/consumer-component.js
src/extensions/compiler-extension.js
src/extensions/tester-extension.js

- add context path to getDynamicPackageDependencies 
- add context path to action from consumer.runSpecs
- fixes #1154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1155)

provide context path to tester

---

CONTRIBUTING.md
src/consumer/component/consumer-component.js

I've pushed code to master which broke testing. This PR is meant to fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1157)

fixing master after breaking

---

e2e/fixtures/compilers/webpack-relative/base/base.config.js
e2e/fixtures/compilers/webpack-relative/compiler.js
e2e/fixtures/compilers/webpack-relative/dev.config.js
e2e/flows/envs.e2e.3.js
src/consumer/bit-json/bit-json.js
src/consumer/bit-map/bit-map.js
src/consumer/bit-map/bit-map.spec.js
src/consumer/component-ops/components-object-diff.js
src/consumer/component/consumer-component.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js
src/extensions/env-extension.js
src/extensions/extension-file.js
src/extensions/tester-extension.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1177)

(wip) add relative paths for environment files properties

---

src/extensions/env-extension.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1182)

improve consumerComponent to object

---

README.md

- Deleted double word @ line 46: "This environment enables you **to to** use and develop..."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1185)

README.md: Fix typo on line 46

---

e2e/flows/env-dependencies.e2e.3.js
src/consumer/component-ops/inject-conf.js
src/extensions/env-extension.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1193)

fix inject-conf to delete the generated link files

---

e2e/fixtures/compilers/new-babel/compiler.js
src/consumer/component-ops/build-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1196)

rename context.rootDistFolder to context.rootDistDir

---

CHANGELOG.md
e2e/commands/dependency-status.e2e.1.js
package.json
src/consumer/component/consumer-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1216)

improve scalability of the dependency resolution

---

CHANGELOG.md
e2e/commands/install.e2e.1.js
e2e/e2e-helper.js
e2e/flows/import-package-json.e2e.3.js
src/api/consumer/lib/import.js
src/constants.js
src/consumer/bit-map/bit-map.js
src/consumer/bit-map/component-map.js
src/consumer/component-ops/add-components/add-components.js
src/consumer/component-ops/import-components.js
src/consumer/component-ops/manipulate-dir.js
src/consumer/component/consumer-component.js
src/consumer/component/dependencies/dependencies.js
src/consumer/component/dependencies/dependency.js
src/consumer/consumer.js
src/environment/environment.js
src/links/link-generator.js
src/links/node-modules-linker.js
src/scope/component-ops/remove-model-components.js
src/scope/component-ops/tag-model-component.js
src/scope/component-version.js
src/scope/models/model-component.js
src/scope/models/version.js
src/scope/repositories/sources.js
src/scope/version-dependencies.js
src/scope/version-validator.js
src/utils/fs/create-symlink-or-copy.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1224)

support adding package.json file as a component file

---

e2e/commands/import.e2e.1.js
src/consumer/component-ops/manipulate-dir.js
src/consumer/component/consumer-component.js
src/scope/repositories/sources.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1241)

fix dir manipulation when a dependency is imported directly

---

CHANGELOG.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1251)

update bit-javascript to have the latest babel version

---

CHANGELOG.md
e2e/commands/diff.e2e.1.js
src/cli/default-error-handler.js
src/constants.js
src/utils/diff-files.js
src/utils/git/exceptions/git-not-found.js
src/utils/git/git-executable.js
src/utils/merge-files.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1248)

support configuring Git executable path

---

CHANGELOG.md
src/cli/default-error-handler.js
src/extensions/base-extension.js
src/extensions/env-extension.js
src/extensions/exceptions/extension-get-dynamic-config-error.js
src/extensions/extension.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1253)

pass config files and context in getDynamicConfig extension's life cycle

---

CHANGELOG.md
src/scope/objects/repository.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1258)

improve performance by caching objects after loading them

---

CHANGELOG.md
src/scope/component-version.js
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1265)

improve export performance by removing obsolete steps

---

CHANGELOG.md
src/logger/logger.js
src/scope/objects/object.js
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1268)

improve bit export performance

---

src/cli/commands/public-cmds/show-cmd.js
src/cli/loader/loader-messages.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1275)

add loader when running "bit show" for a remote component

---

CHANGELOG.md
e2e/api/api.e2e.1.js
e2e/commands/export.e2e.1.js
e2e/commands/list.e2e.2.js
src/api.js
src/api/consumer/lib/list-scope.js
src/api/consumer/lib/list-scope.spec.js
src/api/scope/lib/scope-list.js
src/cli/commands/private-cmds/_list-cmd.js
src/cli/commands/public-cmds/list-cmd.js
src/cli/templates/bare-list-template.js
src/cli/templates/list-template.js
src/consumer/component/components-list.js
src/consumer/component/components-list.spec.js
src/remotes/remote.js
src/scope/component-ops/untag-component.js
src/scope/network/fs/fs.js
src/scope/network/network.js
src/scope/network/ssh/ssh.js
src/scope/scope.js
src/search/search-adapter.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1285)

improve "bit list" performance by retrieving only the information needed

---

CHANGELOG.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1287)

update bit-javascript to support Vue files with typescript

---

src/cli/default-error-handler.js
src/extensions/exceptions/extension-get-dynamic-config-error.js
src/extensions/exceptions/extension-get-dynamic-packages-error.js
src/extensions/exceptions/extension-init-error.js
src/extensions/exceptions/extension-load-error.js
src/specs-runner/specs-runner.js
src/specs-runner/worker.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1291)

improve errors when running bit test

---

CHANGELOG.md
e2e/commands/test.e2e.2.js
e2e/flows/envs.e2e.3.js
src/cli/command-registrar.js
src/cli/commands/public-cmds/test-cmd.js
src/consumer/specs-results/specs-results.js
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1290)

return status code 1 when bit test has failing tests

---

src/cli/commands/private-cmds/_delete-cmd.js
src/cli/commands/private-cmds/_deprecate-cmd.js
src/cli/commands/private-cmds/_fetch-cmd.js
src/cli/commands/private-cmds/_latest-cmd.js
src/cli/commands/private-cmds/_list-cmd.js
src/cli/commands/private-cmds/_put-cmd.js
src/cli/commands/private-cmds/_search-cmd.js
src/cli/commands/private-cmds/_show-cmd.js
src/error/custom-error.js
src/scope/network/check-version-compatibility.js
src/scope/network/check-version-compatibility.spec.js
src/scope/network/exceptions/index.js
src/scope/network/exceptions/old-client-version.js
src/scope/network/ssh/ssh.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1307)

throw an exception from the server if a client has an old major version

---

CHANGELOG.md
e2e/e2e-helper.js
e2e/flows/id-with-wildcard.e2e.2.js
src/api/consumer/lib/checkout.js
src/api/consumer/lib/commit.js
src/api/consumer/lib/diff.js
src/api/consumer/lib/exceptions/no-id-match-wildcard.js
src/api/consumer/lib/export.js
src/api/consumer/lib/merge.js
src/api/consumer/lib/remove.js
src/api/consumer/lib/untag.js
src/api/consumer/lib/untrack.js
src/cli/commands/public-cmds/checkout-cmd.js
src/cli/commands/public-cmds/commit-cmd.js
src/cli/commands/public-cmds/diff-cmd.js
src/cli/commands/public-cmds/export-cmd.js
src/cli/commands/public-cmds/list-cmd.js
src/cli/commands/public-cmds/merge-cmd.js
src/cli/commands/public-cmds/remove-cmd.js
src/cli/commands/public-cmds/untag-cmd.js
src/cli/commands/public-cmds/untrack-cmd.js
src/cli/default-error-handler.js
src/consumer/bit-map/bit-map.js
src/consumer/component/components-list.js
src/consumer/component/components-list.spec.js
src/consumer/consumer.js
src/scope/component-ops/untag-component.js
src/utils/string/has-wildcard.js
src/utils/string/has-wildcard.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1318)

support id with wildcard when tagging components

---

CHANGELOG.md
src/api/consumer/lib/watch.js
src/cli/command-registrar-builder.js
src/cli/commands/public-cmds/watch-cmd.js
src/cli/templates/help.js
src/consumer/component/components-list.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1336)

add new bit watch command

---

CHANGELOG.md
e2e/flows/cyclic-dependencies.e2e.2.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1348)

fix errors when component files require each other using module path

---

package-lock.json
src/jsdoc/parser.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1343)

added default values to react property tables

---

CHANGELOG.md
e2e/commands/link.e2e.2.js
src/links/node-modules-linker.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1351)

fix running "bit link" from an inner directory for author

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1355)

yaml-prettify

---

.circleci/config.yml
e2e/commands/add-many.e2e.2.js
e2e/fixtures/components/add-many/add_many_test_files/inner_folder/add_components_inner_folder_programmatically.js
package.json
src/utils/ignore/ignore.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1349)

fix gitignore error when add componet even it's not on ignore list

---

CHANGELOG.md
package-lock.json
package.json

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1368)

fix parse error on css file

---

CHANGELOG.md
fixtures/jsdoc/react-docs.js
src/jsdoc/parser.js
src/jsdoc/parser.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1370)

fix parsing React docs to show the @example tag

---

e2e/commands/commit.e2e.1.js
src/scope/component-ops/tag-model-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1377)

show a better error when a component was tagged without its dependencies

---

src/jsdoc/parser.js

supported flow types in react docgen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1371)

supported flow types in react docgen

---

CHANGELOG.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1385)

bit-javascript: replace caporal package with commander to support node 6

---

e2e/flows/custom-module-resolutions.e2e.2.js
src/consumer/component-ops/component-writer.js
src/consumer/component/dependencies/dependency-resolver/dependencies-versions-resolver.js
src/consumer/component/package-json.js
src/links/dependency-file-link-generator.js
src/links/link-generator.js
src/links/node-modules-linker.js
src/utils/bit/component-id-to-package-name.js
src/utils/bit/component-node-modules-path.js
src/utils/bit/npm-registry-name.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1386)

fix resolveAliases in package.json to not have a relative path

---

CHANGELOG.md
src/hooks/utils/enrich-context-from-global.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1393)

imporove import performance by caching the enrich-context object

---

e2e/flows/custom-module-resolutions.e2e.2.js
src/links/dependency-file-link-generator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1404)

fix resolveAliases in package.json to not have relative paths

---

e2e/commands/import.e2e.1.js
e2e/e2e-helper.js
e2e/fixtures/fixtures.js
e2e/flows/require-internal-files.e2e.2.js
src/links/dependency-file-link-generator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1412)

fix link generated to an internal package file when the dependency uses a compiler

---

CHANGELOG.md
e2e/typescript/typescript.e2e.3.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1418)

fix parsing .tsx files on bit-javascript

---

CHANGELOG.md
src/scope/removed-components.js
src/scope/removed-components.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1428)

fix "bit remove --remote" to show the dependents correctly

---

CHANGELOG.md
e2e/flows/dependencies-as-packages.e2e.2.js
e2e/npm-ci-registry.js
src/consumer/component-ops/many-components-writer.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js
src/consumer/consumer.js
src/consumer/versions-ops/checkout-version.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1429)

fix bit-checkout to not always install dependencies as components

---

src/links/link-generator.js
src/links/node-modules-linker.js
src/scope/component-ops/untag-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1421)

fix symlinks to be created with the same phase as other links

---

CHANGELOG.md
src/consumer/component/consumer-component.js
src/consumer/component/consumer-component.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1435)

do not extract docs from tests files

---

CHANGELOG.md
e2e/commands/export.e2e.1.js
e2e/functionalities/components-index.e2e.2.js
src/api/consumer/lib/untag.js
src/api/scope/lib/cat-scope.js
src/api/scope/lib/refresh-scope.js
src/cli/commands/public-cmds/list-cmd.js
src/cli/default-error-handler.js
src/consumer/component/components-list.js
src/scope/component-ops/export-scope-components.js
src/scope/component-ops/remove-model-components.js
src/scope/component-ops/untag-component.js
src/scope/exceptions/index.js
src/scope/exceptions/invalid-index-json.js
src/scope/graph/graph.js
src/scope/models/model-component.js
src/scope/objects/components-index.js
src/scope/objects/components-index.spec.js
src/scope/objects/repository.js
src/scope/repositories/sources.js
src/scope/scope.js
src/utils/fs-remove-file.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1436)

improvement - index scope components

---

package.json
src/analytics/analytics.js
src/consumer/component-ops/add-components/add-components.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1442)

improve analytics to show flags and args more clearly

---

e2e/e2e-helper.js
e2e/functionalities/components-index.e2e.2.js
e2e/functionalities/symlink-object-without-component.e2e.2.js
src/cli/commands/private-cmds/cat-scope-cmd.js
src/consumer/component/components-list.js
src/consumer/consumer.js
src/scope/component-ops/remove-model-components.js
src/scope/repositories/sources.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1443)

throw a descriptive error when a scope has a Symlink object referencing to a non-exist component

---

CHANGELOG.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1447)

enable custom resolve of aliases to symlink packages (bit-javascript)

---

src/api/consumer/lib/build.js
src/api/consumer/lib/export.js
src/consumer/component-ops/import-components.js
src/consumer/component-ops/many-components-writer.js
src/consumer/versions-ops/checkout-version.js
src/consumer/versions-ops/merge-version/merge-version.js
src/scope/component-ops/export-scope-components.js
src/scope/component-ops/tag-model-component.js
src/scope/flatten-dependencies.js
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1444)

(wip) avoid reading and writing the same file at the same time

---

CHANGELOG.md
e2e/commands/remote.e2e.2.js
src/api/consumer/lib/remote.js
src/global-config/global-remotes.js
src/scope/scope-json.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1448)

show errors when "bit remote del" fails, either by deleting a non-exist remote or when "--global" flag was missing

---

README.md

Added new readme content and examples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1455)

Update README.md / Updated readme content

---

src/cli/commands/public-cmds/add-cmd.js

- adding links to docs
- showing how to add a list of files to `--test`
- slight text changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1457)

bit-add docs suggestion

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1460)

set a performance test in circle

---

src/hooks/hooks-manager.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1462)

enable logging hook args when prefixing the command with "BIT_LOG=*"

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1461)

fix dependency-resolver to support alias to package with dist

---

CHANGELOG.md
e2e/commands/checkout.e2e.1.js
src/consumer/versions-ops/checkout-version.js
src/consumer/versions-ops/merge-version/merge-version.js
src/consumer/versions-ops/merge-version/three-way-merge.js
src/consumer/versions-ops/merge-version/two-way-merge.js
src/scope/repositories/tmp.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1464)

fix "error: Could not stat (filename) No such file or directory" when bit-checkout updates multiple files

---

e2e/functionalities/components-index.e2e.2.js
src/cli/default-error-handler.js
src/scope/exceptions/index.js
src/scope/exceptions/outdated-index-json.js
src/scope/objects/components-index.js
src/scope/objects/repository.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1467)

show a descriptive error when index.json has components that are missing from the scope

---

src/links/dependency-file-link-generator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1468)

make sure the link's targetDir is of type string and not empty

---

src/consumer/component/sources/data-to-persist.js
src/links/node-modules-linker.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1469)

throw early when a file or a symlink of node_module links has an empty path

---

src/cli/default-error-handler.js
src/error/abstract-error.js
src/error/clone-error-object.js
src/error/hash-error-object.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1473)

avoid sending user errors to Sentry

---

e2e/functionalities/link-generation.e2e.2.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1475)

add e2e-tests for EISDIR and EEXIST errors

---

CHANGELOG.md
src/extensions/base-extension.js
src/npm-client/npm-client.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1476)

show a descriptive error when npm 5.0.0 fails with "--json" flag

---

CHANGELOG.md
e2e/commands/add.e2e.1.js
src/cli/default-error-handler.js
src/consumer/component-ops/add-components/add-components.js
src/consumer/component-ops/add-components/exceptions/index.js
src/consumer/component-ops/add-components/exceptions/path-outside-consumer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1477)

improve error message when adding files outside the workspace

---

src/api/consumer/lib/export.js
src/consumer/consumer-loader.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1478)

avoid loading the same consumer multiple time during the process

---

.eslintignore-circle
CHANGELOG.md
e2e/commands/import.e2e.1.js
src/cli/default-error-handler.js
src/consumer/bit-json/consumer-bit-json.js
src/consumer/bit-json/exceptions/index.js
src/consumer/bit-json/exceptions/invalid-bit-json-prop-path.js
src/consumer/dir-structure/dir-structure.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1479)

validate consumer bit.json path properties

---

e2e/commands/add.e2e.1.js
e2e/commands/install.e2e.1.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1483)

Fix windows tests

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1486)

Vulnerability audit

---

CHANGELOG.md
e2e/commands/import.e2e.1.js
src/npm-client/install-packages.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1489)

avoid installing "undefined" npm package when importing authored components

---

CHANGELOG.md
e2e/commands/export.e2e.1.js
e2e/commands/import-all.e2e.1.js
e2e/commands/import.e2e.1.js
e2e/e2e-helper.js
e2e/flows/dependencies-as-packages.e2e.2.js
src/api/consumer/lib/export.js
src/cli/commands/public-cmds/export-cmd.js
src/cli/default-error-handler.js
src/consumer/bit-json/consumer-bit-json.js
src/consumer/component-ops/eject-components.js
src/consumer/component-ops/import-components.js
src/consumer/consumer.js
src/consumer/versions-ops/checkout-version.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1490)

obsolete the "dependencies" property of consumer bit.json

---

src/scope/network/ssh/ssh.js

- updated errors for token
- update errors for ssh agent
- update errors from ssh_key_file
- update errors for username+password
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1494)

update ssh connection errors

---

src/scope/network/ssh/ssh.js

according to david's comments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1495)

update ssh key errors

---

CHANGELOG.md
e2e/bitsrc-tester.js
e2e/commands/import.e2e.1.js
e2e/commands/test.e2e.2.js
e2e/e2e-helper.js
e2e/flows/dependencies-versions-resolution.e2e.2.js
e2e/flows/env-dependencies.e2e.3.js
e2e/flows/envs.e2e.3.js
e2e/functionalities/component-config.e2e2.js
e2e/functionalities/workspace-config.e2e.2.js
src/bit-id/bit-id.js
src/constants.js
src/consumer/bit-config/abstract-bit-config.js
src/consumer/bit-config/component-bit-config.js
src/consumer/bit-config/components-overrides.js
src/consumer/bit-config/consumer-bit-config.js
src/consumer/bit-map/bit-map.js
src/consumer/component-ops/add-components/add-components.js
src/consumer/component-ops/eject-conf.js
src/consumer/component/component-loader.js
src/consumer/component/consumer-component.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js
src/consumer/component/dependencies/dependency-resolver/dependencies-versions-resolver.js
src/consumer/component/package-json.js
src/consumer/versions-ops/checkout-version.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1499)

introduce "overrides" property to component configuration

---

CHANGELOG.md
e2e/commands/tag.e2e.1.js
src/consumer/component/components-list.spec.js
src/consumer/component/package-json.js
src/jsdoc/parser.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1508)

fix tagging imported components to not loose package.json properties

---

e2e/bitsrc-tester.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1515)

fix testing on bit.dev env to login successfully

---

CHANGELOG.md
e2e/flows/binary-files.e2e.2.js
e2e/npm-ci-registry.js
src/consumer/component/templates/postinstall.default-template.js
src/links/dependency-file-link-generator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1514)

bug - link unsupported file with npm-install

---

CHANGELOG.md
e2e/e2e-helper.js
e2e/functionalities/workspace-config.e2e.2.js
package.json
src/cli/templates/component-template.js
src/consumer/bit-config/component-bit-config.js
src/consumer/bit-config/component-overrides.js
src/consumer/bit-config/consumer-bit-config.js
src/consumer/bit-config/consumer-overrides.js
src/consumer/bit-config/consumer-overrides.spec.js
src/consumer/component-ops/component-writer.js
src/consumer/component-ops/components-object-diff.js
src/consumer/component-ops/many-components-writer.js
src/consumer/component/consumer-component.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js
src/consumer/component/dependencies/dependency-resolver/dependencies-versions-resolver.js
src/consumer/consumer.js
src/scope/models/model-component.js
src/scope/models/version.js
src/scope/version-validator.js
src/utils/validate-type.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1503)

Support removing dependencies

---

e2e/commands/remove.e2e.2.js
src/utils/fs-remove-file.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1522)

fix "bit remove" to ignore non-exist files/dirs

---

CHANGELOG.md
e2e/functionalities/workspace-config.e2e.2.js
src/bit-id/bit-id.js
src/bit-id/bit-ids.js
src/constants.js
src/consumer/bit-config/component-overrides.js
src/consumer/component/consumer-component.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js
src/consumer/component/dependencies/dependency-resolver/dependencies-versions-resolver.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1523)

"overrides" property supports manually adding dependencies (wip)

---

e2e/functionalities/workspace-config.e2e.2.js
src/consumer/bit-config/component-overrides.js
src/consumer/component/consumer-component.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js
src/consumer/component/dependencies/dependency-resolver/overrides-dependencies.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1525)

Overrides refactoring

---

CHANGELOG.md
e2e/flows/binary-files.e2e.2.js
src/links/dependency-file-link-generator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1541)

but with unsupported files when installed via npm with dists

---

e2e/functionalities/workspace-config.e2e.2.js
src/consumer/bit-config/component-overrides.js
src/consumer/component-ops/manipulate-dir.js
src/consumer/component/consumer-component.js
src/scope/repositories/sources.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1547)

support originallySharedDir when manually changing files dependencies

---

e2e/bitsrc-tester.js
e2e/functionalities/workspace-config.e2e.2.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1548)

fix e2e-tests on Windows

---

e2e/flows/dependencies-versions-resolution.e2e.2.js
e2e/functionalities/workspace-config.e2e.2.js
src/consumer/bit-config/component-overrides.js
src/consumer/component/consumer-component.js
src/scope/models/model-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1549)

prevent consumer-config overrides from affecting imported components

---

e2e/e2e-helper.js
e2e/functionalities/symlink-object-without-component.e2e.2.js
src/doctor/core-diagnoses/orphan-symlink-objects.js
src/doctor/diagnosis.js
src/doctor/doctor-registrar-builder.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1559)

implement diagnosis for orphan symlink objects

---

e2e/flows/pad-left-and-is-string.e2e.3.js
e2e/functionalities/workspace-config.e2e.2.js
src/consumer/bit-config/abstract-bit-config.js
src/consumer/bit-config/component-overrides.js
src/consumer/bit-config/consumer-overrides.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1560)

stabilizing the 'overrides' feature

---

CHANGELOG.md
e2e/commands/tag.e2e.1.js
src/cli/templates/list-template.js

- remove chalk characters
- improve format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1556)

fix output for `bit list -j` 

---

e2e/commands/merge.e2e.2.js
e2e/e2e-helper.js
src/utils/index.js
src/utils/string/remove-chalk-characters.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1555)

move remove-chalk-characters to utils

---

e2e/commands/show.e2e.2.js
src/cli/commands/public-cmds/show-cmd.js
src/cli/templates/component-template.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1569)

show overrides data on "bit show" only when "--detailed" flag is used

---

e2e/functionalities/component-config.e2e2.js
src/consumer/bit-config/component-bit-config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1572)

avoid writing overrides object into component config when it is empty

---

e2e/flows/env-dependencies.e2e.3.js
e2e/flows/envs.e2e.3.js
e2e/functionalities/component-config.e2e2.js
src/consumer/component-ops/add-components/add-components.js
src/consumer/component-ops/component-writer.js
src/consumer/component/consumer-component.js
src/consumer/component/package-json.js
src/consumer/config/component-config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1576)

enable changing envs from package-json "bit.env" key for imported components

---

src/consumer/component-ops/components-object-diff.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1587)

fix #1582, sort the dependencies before printing them on bit-show

---

CHANGELOG.md
e2e/flows/copy-workspace-with-env.e2e.2.js
src/doctor/core-diagnoses/broken-symlink-files.js
src/doctor/doctor-registrar-builder.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1590)

add a new bit-doctor diagnose for broken symlinks paths on environments directories

---

CHANGELOG.md
src/cli/default-error-handler.js
src/constants.js
src/scope/network/exceptions/export-another-owner-private.js
src/scope/network/exceptions/remote-resolver-error.js
src/scope/network/ssh/ssh.js

to collection under another owner
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1589)

improve error when user try to export components with private dependencies

---

src/cli/templates/eject-template.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1592)

fix #1583, improve the error message when ejecting a modified component

---

CHANGELOG.md
e2e/commands/add.e2e.1.js
src/consumer/component-ops/add-components/add-components.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1595)

fix #1406, ignore directories upon "bit add" when their files are added

---

e2e/flows/custom-module-resolutions.e2e.2.js
e2e/flows/import-package-json.e2e.3.js
src/consumer/component/components-list.spec.js
src/consumer/component/consumer-component.spec.js
src/consumer/component/sources/data-to-persist.spec.js
src/consumer/consumer.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1594)

fix e2e-tests for Windows

---

appveyor.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1601)

attempt to make AppVeyor green again

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1633)

attempt to make the performance tests green again on CircleCI

---

CHANGELOG.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1639)

fix #1613, ignore import/require statements from CDN (http/https) - fix on bit-javascript

---

CHANGELOG.md
src/api/consumer/lib/doctor.js
src/cli/commands/public-cmds/doctor-cmd.js
src/cli/templates/doctor-results-template.js
src/npm-client/npm-client.js

- Add metadata to bit doctor output:
bit version
node version
npm version
yarn version
platform
userDetails
- move npm / yarn version function to npm-client
- relate to #1596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1644)

Add metadata to bit doctor output:

---

CHANGELOG.md
src/cli/commands/public-cmds/add-cmd.js

Updating `bit add`'s help message with info about how to use glob patterns.
Relevant to this issue #1637
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1646)

Update add help quatation marks

---

src/consumer/component/package-json-utils.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1658)

remove the "componentRootFolder" property from generated package.json, it is obsolete

---

CHANGELOG.md
src/doctor/core-diagnoses/validate-bit-version.js
src/doctor/doctor-registrar-builder.js
src/npm-client/npm-client.js

related to #1596
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1669)

add bit version validation to `bit doctor` command

---

package.json

- downgrade detect-indent version to support node 6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1672)

restore node 6 support

---

.eslintignore-circle
src/api/scope/lib/deprecate.js
src/cli/commands/private-cmds/_deprecate-cmd.js
src/cli/commands/public-cmds/deprecate-cmd.js
src/consumer/consumer.js
src/scope/component-ops/components-deprecation.js
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1673)

refactor bit-deprecate code to make it easy to implement bit-undeprecate

---

e2e/flows/out-of-sync-componets.e2e.3.js
src/api/consumer/lib/export.js
src/consumer/component/component-loader.js
src/consumer/component/components-list.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1674)

fix two more cases of sync issues between .bitmap and the local store

---

CHANGELOG.md
src/api/consumer/lib/login.js
src/cli/commands/public-cmds/login-cmd.js
src/consumer/login/login.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1682)

implement #1567, introduce a new flag "--machine-name" for "bit login" to help CI servers keep their token not revoked

---

CHANGELOG.md
e2e/commands/tag.e2e.1.js
e2e/flows/auto-tagging.e2e.2.js
e2e/flows/vue.e2e.3.js
src/api/consumer/lib/tag.js
src/cli/commands/public-cmds/tag-cmd.js
src/consumer/consumer.js
src/scope/component-ops/auto-tag.js
src/scope/component-ops/tag-model-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1685)

implement #1627, improve "bit tag" output

---

e2e/flows/out-of-sync-componets.e2e.3.js
src/cli/commands/public-cmds/export-cmd.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1693)

Improve output when exporting not tracked components

---

e2e/flows/out-of-sync-componets.e2e.3.js
src/cli/commands/public-cmds/add-cmd.js

remove the warning about already existing components in the scope during bit add
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1695)

remove the warning about already existing components during bit add

---

e2e/doctor/doctor-git-exec.e2e.3.js
src/doctor/core-diagnoses/broken-symlink-files.js
src/doctor/core-diagnoses/orphan-symlink-objects.js
src/doctor/core-diagnoses/validate-git-exec.js
src/doctor/core-diagnoses/validate-npm-exec.js
src/doctor/core-diagnoses/validate-workspace-bit-json-syntax.js
src/doctor/core-diagnoses/validate-yarn-exec.js
src/scope/exceptions/component-not-found.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1694)

improve doctor check names and outputs

---

CHANGELOG.md
src/global-config/config.js

- fixes #1699 - issue when loading the global config for the first time
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1701)

fixes #1699 - config.get is not a function

---

e2e/flows/typescript-link-files.e2e.3.js
e2e/typescript/typescript.e2e.3.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1737)

ignore two e2e-tests on AppVeyor that fail there for unknown and unreproducible error

---

CHANGELOG.md
e2e/fixtures/fixtures.js
e2e/flows/capsule.e2e.2.js
src/environment/isolator.js
src/npm-client/npm-client.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1740)

improve isolation by capsule to install peer-dependencies

---

CHANGELOG.md
src/api/scope/lib/build-in-scope.js
src/api/scope/lib/ci-update-action.js
src/cli/commands/private-cmds/ci-update-cmd.js
src/scope/ci-ops/run-and-update-ci.js
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1754)

add `--no-cache` flag to `bit ci-update` command

---

CHANGELOG.md
src/consumer/component-ops/build-component.js
src/consumer/component/consumer-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1755)

fix `directory` flag of `bit ci-update` command

---

CHANGELOG.md
e2e/flows/es6-link-files.e2e.3.js
src/links/dependency-file-link-generator.js
src/links/link-content.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1757)

fix #1752, consider the ImportSpecifiers when generating dependency links for packages

---

CHANGELOG.md
e2e/flows/dependencies-as-packages.e2e.2.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js

currently, it shows the link file as an untracked file incorrectly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1760)

fix #1750, improve the output to clarify when a dependency package is missing

---

CHANGELOG.md
src/constants.js
src/consumer/component/component-loader.js
src/links/link-generator.js
src/links/linker.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1761)

add a custom entry point file for Angular components

---

src/constants.js
src/links/link-generator.js

Also, make sure it does not overwrite user files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1765)

change angular entry point file name from __index.ts to public_api.ts

---

e2e/e2e-helper.js
e2e/flows/copy-workspace-with-env.e2e.2.js
e2e/flows/typescript-link-files.e2e.3.js
e2e/typescript/typescript.e2e.3.js
src/links/dependency-file-link-generator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1776)

fix e2e-tests related to stg.bit.dev

---

e2e/flows/capsule.e2e.2.js
src/links/node-modules-linker.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1777)

avoid creating symlinks from node_modules to the capsule root dir

---

.circleci/config.yml
e2e/commands/install.e2e.1.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1783)

Upgrade circle to node 10

---

src/consumer/component-ops/build-component.js
src/consumer/component-ops/component-writer.js
src/consumer/component/package-json-file.js
src/consumer/component/sources/dists.js
src/environment/isolator.js
src/links/linker.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1785)

enable compilers to build dists on capsule

---

CHANGELOG.md
src/consumer/component-ops/build-component.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1795)

fix #1788 - updating package.json props from a compiler that uses isolate function

---

CHANGELOG.md
e2e/fixtures/components/import-relative-path/import-by-2-files/a1.js
e2e/fixtures/components/import-relative-path/import-by-2-files/a2.js
e2e/fixtures/components/import-relative-path/import-by-2-files/b.js
e2e/flows/dependencies-from-relative-path.e2e.3.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js

- fix dependency resolution when 2 files of component import different things from a file of another component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1797)

fix #1796 import from same file

---

CHANGELOG.md
src/scope/component-ops/export-scope-components.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1800)

fix #1798, fix replacing the component to full ids to work for all cases

---

CHANGELOG.md
e2e/e2e-helper.js
e2e/flows/capsule.e2e.2.js
src/environment/isolator.js
src/npm-client/npm-client.js

by adding them into devDependencies of the capsule root package.json.
Fixes https://github.com/teambit/bit/issues/1789.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1805)

prevent removal of peer-dependencies from capsule 

---

CHANGELOG.md
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1811)

fix #1807 - resolution of dependency when 2 files require it and one of them using alias

---

CHANGELOG.md
e2e/typescript/typescript.e2e.3.js
src/links/dependency-file-link-generator.js

that are generated for custom-resolve-modules of typescript components
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1824)

generate an index.d.ts file for node_modules links

---

CHANGELOG.md
e2e/flows/es6.e2e.3.js
src/links/link-content.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1826)

avoid generating duplicate "require" statements within dependency links files of ES6

---

.circleci/config.yml
CHANGELOG.md
bin/bit.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1832)

Require node 8

---

.circleci/config.yml
CHANGELOG.md
bin/bit.js

Otherwise, `execa` will throw errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1834)

Change the minimum node supported to v8.12.0 (instead of v8.0.0)

---

CHANGELOG.md
e2e/e2e-helper.js
e2e/platforms/angular.e2e.3.js
package-lock.json
package.json

See https://github.com/teambit/bit-javascript/pull/109 for more details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1835)

update bit-javascript to fix finding tsconfig.json for Angular projects

---

CHANGELOG.md
e2e/commands/add.e2e.1.js
e2e/commands/build.e2e.1.js
e2e/commands/init.e2e.1.js
e2e/commands/install.e2e.1.js
e2e/commands/remove.e2e.1.js
e2e/commands/show.e2e.2.js
e2e/commands/status.e2e.2.js
e2e/commands/tag.e2e.1.js
e2e/e2e-helper.js
e2e/flows/delete-files.e2e.2.js
e2e/flows/dependencies-as-packages.e2e.2.js
e2e/flows/dist-outside-components.e2e.2.js
e2e/flows/out-of-sync-componets.e2e.3.js
e2e/functionalities/capsule.e2e.2.js
e2e/functionalities/env-dependencies.e2e.3.js
e2e/functionalities/envs.e2e.3.js
e2e/functionalities/link-generation.e2e.2.js
e2e/functionalities/symlink-object-without-component.e2e.3.js
e2e/functionalities/workspace-config.e2e.3.js
src/consumer/component/sources/dists.js
src/scope/scope.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1843)

fix error "unable to link" upon bit-build when dist is outside the components dir

---

CHANGELOG.md
e2e/e2e-helper.js
e2e/flows/dependencies-from-relative-path.e2e.3.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js

Happens when the first file of a component requires another one without import-specifier and other files of the same component require with import-specifiers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1847)

fix "Cannot read property push of undefined" error

---

e2e/commands/watch.e2e.2.js
e2e/e2e-helper.js
e2e/watch-runner.js
src/consumer/bit-map/bit-map.js
src/consumer/component-ops/watch-components.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1848)

Fix watch tests on windows

---

CHANGELOG.md
src/consumer/component-ops/import-components.js
src/scope/component-ops/scope-components-importer.js

Done by reducing the round trips to the SSH.
Fixes https://github.com/teambit/bit/issues/1710.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1851)

improve import performance of multiple components with multiple versions

---

appveyor.yml
e2e/commands/watch.e2e.2.js
e2e/watch-runner.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1849)

add some more e2e-tests for bit watch

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1855)

circle-optimization

---

CHANGELOG.md
e2e/e2e-helper.js
e2e/functionalities/envs.e2e.3.js
src/scope/objects/repository.js

to avoid a situation when a component object is saved and its Version object is invalid
Fixes https://github.com/teambit/bit/issues/1727.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1859)

Validate all objects before saving the first one

---

CHANGELOG.md
e2e/e2e-helper.js
e2e/flows/id-with-wildcard.e2e.2.js
src/api/consumer/lib/list-scope.js
src/cli/commands/public-cmds/list-cmd.js
src/consumer/component/components-list.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1861)

implement #1683, improve "bit list" to support wildcards

---

CHANGELOG.md
e2e/platforms/angular.e2e.3.js
src/consumer/component/sources/data-to-persist.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1875)

fix capsule to respect the "override" property of vinyl files

---

CHANGELOG.md
e2e/functionalities/track-directories.e2e.3.js
src/consumer/bit-map/bit-map.js
src/consumer/component-ops/component-writer.js
src/consumer/component-ops/move-components.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1876)

bug fix - do not delete trackDir when a component is imported

---

CHANGELOG.md
bin/bit.js
e2e/flows/permissions-errors.e2e.3.js
src/cli/default-error-handler.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1882)

fix #1774, improve access errors and warn when sudo is used

---

e2e/functionalities/capsule.e2e.2.js
src/scope/graph/components-graph.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1881)

improve capsule-compiler error when it finds circle dependencies to print the circle components

---

src/api/consumer/lib/remove.js
src/consumer/component-ops/remove-components.js
src/consumer/consumer.js

extract the remove-components code from the Consumer class and move to a new file src/consumer/component-ops/remove-components.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1886)

refactoring - remove components

---

CHANGELOG.md
e2e/functionalities/workspace-config.e2e.3.js
src/consumer/config/consumer-overrides.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1891)

implements #1863, allow excluding components from "overrides" rules

---

CHANGELOG.md
e2e/commands/export.e2e.1.js
e2e/commands/list.e2e.1.js
e2e/commands/remove.e2e.1.js
e2e/commands/tag.e2e.1.js
e2e/e2e-helper.js
e2e/flows/sort-components-output.e2e.3.js
src/cli/commands/public-cmds/list-cmd.js
src/cli/templates/bare-list-template.js
src/cli/templates/raw-list-template.js

Show a deprecation warning when using `--bare`.
Implements https://github.com/teambit/bit/issues/1892
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1897)

Rename "bit list --bare" to "bit list --raw"

---

CHANGELOG.md
e2e/flows/dependencies-versions-resolution.e2e.2.js
e2e/functionalities/workspace-config.e2e.3.js
src/consumer/component/consumer-component.js
src/consumer/component/dependencies/dependency-resolver/dependencies-versions-resolver.js
src/consumer/config/component-overrides.js
src/consumer/config/consumer-overrides.js
src/extensions/env-extension.js
src/scope/models/version.spec.js
src/scope/version-validator.js

Implements https://github.com/teambit/bit/issues/1867.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1899)

Apply workspace overrides configuration on imported components

---

CHANGELOG.md
e2e/typescript/typescript.e2e.3.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js

when found in the user package.json and it is a typescript component.
Implements https://github.com/teambit/bit/issues/1889.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1904)

Automatically add @types/pkg-name as a package dependency

---

CHANGELOG.md
e2e/commands/import.e2e.1.js
src/consumer/component-ops/import-components.js

Fixes https://github.com/teambit/bit/issues/1903.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1905)

Fix importing dependents to not override dependencies

---

.eslintignore-circle
CHANGELOG.md
e2e/api/show.e2e.1.js
e2e/commands/show.e2e.2.js
src/api.js
src/api/consumer/index.js
src/api/consumer/lib/get-consumer-component.js
src/api/consumer/lib/get-scope-component.js
src/api/consumer/lib/show.js
src/api/scope/index.js
src/api/scope/lib/graph.js
src/cli/command-registrar-builder.js
src/cli/commands/private-cmds/_graph-cmd.js
src/cli/commands/public-cmds/show-cmd.js
src/cli/templates/component-template.js
src/consumer/component/dependencies/dependencies.js
src/remotes/remote.js
src/scope/graph/scope-graph.js
src/scope/network/fs/fs.js
src/scope/network/network.js
src/scope/network/ssh/ssh.js
src/scope/scope.js
src/scope/version-validator.js

To display them all recursively.
Implements part of https://github.com/teambit/bit/issues/1885.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1914)

Introduce new flags `--dependents` and `--dependencies` for `bit show` 

---

CHANGELOG.md
package-lock.json
package.json

Fixes https://github.com/teambit/bit/issues/1925.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1926)

Update bit-javascript to fix Angular non-relative paths from decorators

---

CHANGELOG.md
src/consumer/component-ops/build-component.js
src/consumer/component-ops/many-components-writer.js

Fixes https://github.com/teambit/bit/issues/1924.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1929)

Avoid writing dists files when generating a capsule during "bit build"

---

CHANGELOG.md
e2e/commands/import.e2e.1.js
src/api/consumer/lib/get-consumer-component.js
src/cli/commands/public-cmds/import-cmd.js
src/consumer/component-ops/import-components.js
src/remotes/remote.js
src/remotes/remotes.js
src/scope/graph/scope-graph.js

to import them all directly.
Implements part of https://github.com/teambit/bit/issues/1885.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1927)

Introduce new flags "--dependents" and "--dependencies" for "bit import"

---

package-lock.json
package.json
src/api/consumer/index.js
src/api/consumer/lib/paint-graph.js
src/cli/command-registrar-builder.js
src/cli/commands/public-cmds/graph-cmd.js
src/scope/graph/scope-graph.js
src/scope/graph/vizgraph.js
src/scope/objects/ref.js

For painting a dependency graph of the workspace/scope or a specific component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1931)

(experimental) add "graph" command

---

CHANGELOG.md
e2e/functionalities/capsule.e2e.2.js
e2e/functionalities/env-dependencies.e2e.3.js
src/consumer/component-ops/component-writer.js
src/consumer/component-ops/eject-conf.js
src/links/link-generator.js
src/links/linker.js

using the new extension API.
Fixes https://github.com/teambit/bit/issues/1934
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1936)

Fix capsule compilers when configured to work with custom files

---

CHANGELOG.md
e2e/commands/build.e2e.1.js
src/api/consumer/lib/build.js

Fixes https://github.com/teambit/bit/issues/1916.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1939)

Do not throw an error when there are no components to build

---

src/cli/commands/public-cmds/checkout-cmd.js
src/cli/commands/public-cmds/diff-cmd.js
src/cli/commands/public-cmds/export-cmd.js
src/cli/commands/public-cmds/import-cmd.js
src/cli/commands/public-cmds/merge-cmd.js
src/cli/commands/public-cmds/remove-cmd.js
src/cli/commands/public-cmds/tag-cmd.js
src/cli/commands/public-cmds/untag-cmd.js
src/cli/commands/public-cmds/untrack-cmd.js
src/constants.js

to emphasis the need for the quotes wrapping the pattern.
Resolves https://github.com/teambit/bit/issues/1938.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1942)

Improve the help of commands that support wildcards

---

CHANGELOG.md
src/cli/commands/public-cmds/import-cmd.js

Implements https://github.com/teambit/bit/issues/1937.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1944)

Introduce "--json" flag for "bit import"

---

.circleci/config.yml
CHANGELOG.md
e2e/flows/require-internal-files.e2e.2.js
src/consumer/component/sources/dists.js
src/e2e-helper/e2e-scope-helper.js
src/links/dependency-file-link-generator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1943)

Fix linking to an internal and non-exist dist file to fallback to the main package

---

CHANGELOG.md
e2e/commands/export.e2e.1.js
e2e/fixtures/compilers/add-scope-name/compiler.js
src/scope/component-ops/export-scope-components.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1948)

Fix dist changing of bit-ids on export to make the replacement on exact matches only

---

e2e/commands/link.e2e.1.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1962)

fix a failing e2e-test on Windows

---

CHANGELOG.md
src/cli/commands/public-cmds/build-cmd.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1963)

fix #1959 - improve message when running `bit build` when compiler not configured

---

package.json

Add keywords for a better search result in package manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1964)

Update package.json / add keywords

---

CHANGELOG.md
package-lock.json
package.json
src/cli/command-registrar.js
src/extensions/env-extension.js
src/logger/logger.js
src/npm-client/npm-client.js
src/scope/extensions/install-extensions.js
src/scope/models/version.js
src/scope/network/check-version-compatibility.js
src/specs-runner/specs-runner.js

* Upgrade Winston from v2 to v3.
* Add an option to print into the console only when `--json` flag was not used.
Fixes https://github.com/teambit/bit/issues/1966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1976)

Prevent intermediate console printing when "--json" flag is used

---

CHANGELOG.md
e2e/functionalities/component-config.e2e.2.js
src/extensions/env-extension.js

by its package.json file.
Resolve https://github.com/teambit/bit/issues/1721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1979)

bug fix - there was no option to remove a compiler from a component

---

src/scope/version-validator.js

to include the files list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1983)

improve the error message when bit-tag is unable to find the main-file

---

e2e/commands/export.e2e.1.js
src/bit-id/bit-ids.js

when exporting to multiple remotes and components have dependencies from other remotes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1987)

fix error "exportingIds.hasWithoutVersion is not a function"

---

CHANGELOG.md
e2e/commands/import.e2e.1.js
src/consumer/component-ops/import-components.js

Fixes https://github.com/teambit/bit/issues/1988.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1989)

Avoid adding a component to root package.json when importing with "--ignore-package-json" flag

---

e2e/commands/log.e2e.1.js
src/bit-id/bit-ids.js
src/cli/chalk-box.js
src/e2e-helper/e2e-command-helper.js
src/scope/models/model-component.js
src/scope/scope.js

when running bit log of a component that not all its versions are in the scope
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1991)

fix an error "Cannot read property log of null"

---

src/cli/commands/private-cmds/resolver-cmd.js
src/consumer/bit-map/bit-map.js
src/consumer/bit-map/component-map.js
src/consumer/component-ops/add-components/add-components.js
src/consumer/component-ops/component-writer.js
src/consumer/component-ops/components-diff.js
src/consumer/component-ops/eject-conf.js
src/consumer/component-ops/import-components.js
src/consumer/component-ops/inject-conf.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js
src/consumer/component/package-json-utils.js
src/consumer/config/component-config.js
src/consumer/consumer.js
src/error/show-doctor-error.js
src/links/symlink.js
src/npm-client/npm-client.js
src/scope/component-ops/scope-components-importer.js
src/scope/component-ops/tag-model-component.js
src/scope/component-version.js
src/scope/models/model-component.js
src/utils/fs/create-symlink-or-copy.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1995)

Remove the message of run-bit-doctor when is not relevant

---

src/cli/commands/public-cmds/graph-cmd.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2002)

support running "bit graph" with no image path

---

CHANGELOG.md
e2e/commands/export.e2e.1.js
src/api/consumer/lib/export.js
src/cli/commands/public-cmds/export-cmd.js
src/e2e-helper/e2e-command-helper.js
src/prompts/index.js
src/prompts/schemas/fork-components.js

(forking components).
Omit the prompt in case `--force` is used.
Implements https://github.com/teambit/bit/issues/2004.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2012)

Ask for approval before exporting a component to another scope

---

CHANGELOG.md
e2e/commands/export.e2e.1.js
src/api/consumer/lib/export.js
src/cli/commands/public-cmds/export-cmd.js
src/prompts/schemas/fork-components.js

- relate to #1956 
- rename `--codemod` to `--rewire-scope`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2021)

rename `--codemod` to `--rewire-scope`

---

CHANGELOG.md
e2e/commands/export.e2e.1.js
src/api/consumer/lib/export.js
src/cli/commands/public-cmds/export-cmd.js
src/prompts/schemas/fork-components.js

- relate to #1956
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2022)

rename  `--rewire-scope` to `--rewire`

---

CHANGELOG.md
e2e/commands/eject.e2e.1.js
src/consumer/component-ops/eject-components.js
src/consumer/component/components-list.js
src/consumer/component/package-json-file.js
src/scope/component-ops/untag-component.js
src/scope/graph/scope-graph.js

Also, run `npm install` in the dependents directories after ejecting the dependencies.
Fixes https://github.com/teambit/bit/issues/2011.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2025)

Update dependents package.json files when ejecting dependecies

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2028)

reuse circle configurations between jobs

---

CHANGELOG.md
e2e/flows/dependencies-as-packages.e2e.2.js
src/consumer/component-ops/load-flattened-dependencies.js
src/consumer/consumer.js
src/e2e-helper/e2e-command-helper.js
src/environment/isolator.js
src/scope/component-dependencies.js

Happens when they were imported using npm.
Fixes https://github.com/teambit/bit/issues/2027.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2029)

When isolating a component using capsule, import dependencies if they are missing

---

src/scope/network/check-version-compatibility.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2032)

resolve #2030, do not show a minor version mismatch as a fatal error

---

CHANGELOG.md
src/api/consumer/lib/export.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2036)

call pre and post export hooks actions

---

src/cli/commands/public-cmds/remove-cmd.js
src/cli/commands/public-cmds/untag-cmd.js

See https://github.com/teambit/bit/issues/2006 for more info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2044)

Change the help of remove --force to warn the user about potential components corruption

---

CHANGELOG.md
e2e/functionalities/auto-tagging.e2e.2.js
src/scope/component-ops/auto-tag.js
src/scope/component-ops/tag-model-component.js
src/scope/models/model-component.js
src/scope/repositories/sources.js

It happens when components have cycle dependencies and a version is specified in the bit tag command
Fixes https://github.com/teambit/bit/issues/2034.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2040)

Make sure versions are not deleted upon tag 

---

CHANGELOG.md
e2e/functionalities/component-config.e2e.2.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js

Happens when package.json of an imported component is missing
Fixes https://github.com/teambit/bit/issues/2035.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2042)

Fix "unable to manually add the dependency" error 

---

src/api/consumer/lib/export.js
src/consumer/bit-map/bit-map.js
src/consumer/component-ops/eject-components.js
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js
src/environment/isolator.js
src/extensions/base-extension.js
src/extensions/extensions-loader.js
src/hooks/hooks-manager.js
src/npm-client/npm-client.js
src/scope/component-version.js
src/scope/network/ssh/ssh.js
src/utils/os-resolve-group-id.js

They got broken after upgrading Winston to v3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2045)

Fix logging Error objects by passing them always as the second argument

---

CHANGELOG.md
e2e/functionalities/merge.e2e.3.js
src/consumer/component-ops/many-components-writer.js
src/e2e-helper/e2e-command-helper.js

Fixes https://github.com/teambit/bit/issues/2019.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2048)

Fix "bit import --merge" to not override changed depencies

---

bin/bit.js
package-lock.json
src/api/consumer/lib/global-config.ts
src/cli/commands/public-cmds/add-cmd.ts
src/cli/commands/public-cmds/build-cmd.ts
src/cli/commands/public-cmds/clear-cache-cmd.ts
src/cli/commands/public-cmds/config-cmd.ts
src/cli/commands/public-cmds/export-cmd.ts
src/cli/commands/public-cmds/import-cmd.ts
src/cli/commands/public-cmds/init-cmd.ts
src/cli/commands/public-cmds/install-cmd.ts
src/cli/commands/public-cmds/link-cmd.ts
src/cli/commands/public-cmds/list-cmd.ts
src/cli/commands/public-cmds/log-cmd.ts
src/cli/commands/public-cmds/move-cmd.ts
src/cli/commands/public-cmds/remote-cmd.ts
src/cli/commands/public-cmds/remove-cmd.ts
src/cli/commands/public-cmds/show-cmd.ts
src/cli/commands/public-cmds/status-cmd.ts
src/cli/commands/public-cmds/tag-cmd.ts
src/cli/commands/public-cmds/test-cmd.ts
src/cli/commands/public-cmds/untag-cmd.ts
src/cli/commands/public-cmds/untrack-cmd.ts
src/cli/default-error-handler.ts
src/npm-client/npm-client.ts
src/prompts/schemas/analytics-reporting.ts
src/scope/network/check-version-compatibility.ts

- Fix links to docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2068)

Fix docs links

---

.eslintrc.js
CHANGELOG.md
e2e/commands/checkout.e2e.1.ts
e2e/fixtures/fixtures.ts
package-lock.json
package.json
src/consumer/component-ops/import-components.ts
src/consumer/component/consumer-component.ts
src/consumer/component/sources/abstract-vinyl.ts
src/consumer/component/sources/dists.ts
src/consumer/component/sources/source-file.ts
src/consumer/versions-ops/checkout-version.ts
src/consumer/versions-ops/merge-version/three-way-merge.ts
src/extensions/extension-file.ts
src/scope/repositories/sources.ts
src/utils/encryption/sha1.ts
src/utils/fs/search-files-ignore-ext.spec.ts
src/utils/fs/search-files-ignore-ext.ts

Fixes https://github.com/teambit/bit/issues/2067.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2070)

Fix bit-checkout to not duplicate modified files when the shared dir has changed

---

src/extensions/extensions-loader.ts
src/jsdoc/parser.ts
src/jsdoc/vue-parser.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2076)

fix a few "undefined" entries in the log

---

CHANGELOG.md
package-lock.json

Resolves https://github.com/teambit/bit/issues/2072.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2073)

Upgrade bit-javascript to support React fragments

---

.circleci/config.yml
CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2078)

Convert bit-javascript from Flow to TS

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2081)

update circle schema to v2.1

---

CHANGELOG.md
e2e/commands/import.e2e.1.ts
package-lock.json
package.json

Resolves https://github.com/teambit/bit/issues/2079.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2082)

Add e2e-tests for a case when nohoist option of Yarn workspaces is used

---

CHANGELOG.md
e2e/functionalities/auto-tagging.e2e.2.ts
src/api/consumer/lib/tag.ts
src/cli/commands/public-cmds/tag-cmd.ts
src/consumer/consumer.ts
src/scope/component-ops/tag-model-component.ts
src/utils/string/is-string.ts

Implements https://github.com/teambit/bit/issues/2066.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2083)

Introduce --skip-auto-tag flag for bit-tag

---

e2e/flows/copy-workspace-with-env.e2e.2.ts
e2e/typescript/typescript-link-files.e2e.3.ts
e2e/typescript/typescript.e2e.3.ts
src/e2e-helper/e2e-env-helper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2107)

fix typescript e2e-tests after staging has updated with the latest typescript compiler

---

CHANGELOG.md
e2e/functionalities/envs.e2e.3.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/component/dependencies/dependency-resolver/overrides-dependencies.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2110)

Fix overrides to respect dependencies received by a compiler/tester

---

bin/bit.js
src/cli/command-registrar.ts

Minor code refactoring to eliminate code redundancy.

chore(refactor): avoid repeated conditional checks

---

src/utils/fs/propogate-until.ts
src/utils/ssh/parse-url.ts

Use `Array.includes()` to check for existence.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2113)

refactor: use includes to check for existence

---

.circleci/config.yml
package-lock.json
package.json
src/consumer/login/login.ts

Closes #2112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2114)

chore(deps): switch to open

---

CHANGELOG.md
src/cli/command-registrar.ts
src/cli/command.ts
src/cli/commands/public-cmds/build-cmd.ts
src/cli/commands/public-cmds/deprecate-cmd.ts
src/cli/commands/public-cmds/export-cmd.ts
src/cli/commands/public-cmds/graph-cmd.ts
src/cli/commands/public-cmds/import-cmd.ts
src/cli/commands/public-cmds/isolate-cmd.ts
src/cli/commands/public-cmds/list-cmd.ts
src/cli/commands/public-cmds/log-cmd.ts
src/cli/commands/public-cmds/remove-cmd.ts
src/cli/commands/public-cmds/show-cmd.ts
src/cli/commands/public-cmds/tag-cmd.ts
src/cli/commands/public-cmds/test-cmd.ts
src/cli/commands/public-cmds/undeprecate-cmd.ts
src/cli/commands/public-cmds/watch-cmd.ts
src/cli/global-flags.ts
src/constants.ts
src/scope/network/ssh/ssh.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2117)

support `--token` flag for commands that runs against a remote server

---

src/scope/models/model-component.ts

to include the component-name.
Before, it used to throw the `ENOENT` error of node fs module.
Now, the error looks like the following:
```
fatal: an object of "bit.utils/object/has-own-property" was not found at /Users/davidfirst/wp/.bit/objects/a9/fb49a3926e9bc7bb46eb7cdf4c7ec9a1c4c222
please try to re-import the component
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2130)

improve the error message when an object was not found in the scope

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2127)

generate types in circle ci build and test flow

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2134)

Fix bit hub tests in Circle

---

CHANGELOG.md
e2e/functionalities/peer-dependencies.e2e.3.ts
src/scope/extensions/install-extensions.ts

Fixes https://github.com/teambit/bit/issues/2132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2136)

Fix compiler import to install peer dependencies

---

package-lock.json
src/e2e-helper/e2e-command-helper.ts
src/scope/models/model-component.ts

- add stdio for runCMD to debug envs
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2137)

add stdio to runCMD

---

src/interactive/utils/run-interactive-cmd.ts

- small fix in order to consume declarations without error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2138)

better type information

---

CHANGELOG.md
e2e/typescript/typescript.e2e.3.ts
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2142)

resolve #2140, update bit-javascript to support "import { x as y }" syntax

---

CHANGELOG.md
e2e/typescript/typescript.e2e.3.ts
src/cli/command-registrar.ts
src/links/link-content.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2148)

fix symlink errors when generating links to d.ts files

---

package-lock.json
src/api.ts
src/api/consumer/lib/build.ts

- add directory to buildOne
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2152)

buildOne with directory

---

CHANGELOG.md
e2e/commands/init.e2e.1.ts
e2e/interactive/init.interactive.e2e.3.ts
src/cli/commands/public-cmds/init-cmd.ts
src/e2e-helper/e2e-scope-helper.ts
src/interactive/commands/init-interactive.ts
src/interactive/utils/should-show-interactive.ts

fixes #2161 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2160)

change init interactive to be true by default

---

CHANGELOG.md
e2e/commands/init.e2e.1.ts
e2e/interactive/init.interactive.e2e.3.ts
src/cli/commands/public-cmds/init-cmd.ts
src/e2e-helper/e2e-scope-helper.ts
src/interactive/commands/init-interactive.ts
src/interactive/utils/should-show-interactive.ts

- Revert "change init interactive to be true by default
- This reverts commit ae73cb22ca3c85070784570ce45eaf712902893b.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2169)

make init interactive not default - (#2160)

---

CHANGELOG.md
e2e/typescript/typescript.e2e.3.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

Fixes https://github.com/teambit/bit/issues/2178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2181)

Fix adding ts-types-packages to respect overrides settings

---

.eslintrc.js
CHANGELOG.md
e2e/commands/show.e2e.2.ts
e2e/commands/status.e2e.2.ts
e2e/functionalities/workspace-config.e2e.3.ts
src/cli/commands/public-cmds/status-cmd.ts
src/cli/templates/component-issues-template.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/component/dependencies/dependency-resolver/overrides-dependencies.ts

fixes #2175 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2177)

fixes #2175 - show missing packages from overrides configuration

---

CHANGELOG.md
e2e/fixtures/testers/capsule/tester.js
src/extensions/extension-isolate-result.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2187)

support write dists from testers isolate API

---

scripts/doc-generator.js

Cli generator now generates for subcommands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2192)

Add support for sub commands in cli generator

---

src/logger/logger.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2194)

fix BIT_LOG env variable, it stopped working after upgrading to Winston 3

---

CHANGELOG.md
e2e/flows/dependencies-as-packages.e2e.2.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

Fixes https://github.com/teambit/bit/issues/2196.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2198)

Fix dependency resolution when Bit component is imported in a sub-package

---

package-lock.json
package.json

We published librarian to npm, so let's use it from there instead of github. :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2200)

chore(packages): get librarian from npm

---

CHANGELOG.md
e2e/commands/log.e2e.1.ts
src/api/consumer/lib/get-component-logs.ts
src/api/consumer/lib/get-scope-component.ts
src/api/consumer/lib/list-scope.ts
src/api/consumer/lib/paint-graph.ts
src/api/scope/lib/log.ts
src/cli/command-registrar-builder.ts
src/cli/commands/private-cmds/_log-cmd.ts
src/cli/commands/public-cmds/log-cmd.ts
src/consumer/consumer-loader.ts
src/remotes/get-remote-by-name.ts
src/remotes/remote.ts
src/scope/models/model-component.ts
src/scope/network/fs/fs.ts
src/scope/network/network.ts
src/scope/network/ssh/ssh.ts
src/scope/scope.ts

Implements https://github.com/teambit/bit/issues/1894
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2223)

introduce "--remote" flag for bit-log to show logs of a remote component

---

CHANGELOG.md
e2e/commands/checkout.e2e.1.ts
e2e/functionalities/envs.e2e.3.ts
src/cli/commands/public-cmds/checkout-cmd.ts
src/consumer/versions-ops/checkout-version.ts

Same as what "bit import" has.
Also, improve the performance of `bit checkout` by writing multiple components in parallel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2227)

add --conf and --ignore-package-json flags to "bit checkout"

---

src/consumer/bit-map/bit-map.spec.ts
src/consumer/bit-map/bit-map.ts
src/consumer/bit-map/component-map.ts
src/consumer/component-ops/add-components/add-components.ts
src/consumer/component-ops/dependency-status.ts
src/consumer/component-ops/install-components.ts
src/consumer/component-ops/watch-components.ts
src/consumer/component/components-list.ts
src/consumer/migrations/bit-map/to-semver-migration.ts

to be an array of ComponentMap instead of an object. It makes it easier to work with and also reduces the risk of a mismatch between the key-id and the value id.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2235)

refactor BitMap.component member

---

CHANGELOG.md
src/cli/commands/public-cmds/tag-cmd.ts

- fixes #2247 - improve auto-tag output
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2254)

fixes #2247 - improve auto-tag output

---

CHANGELOG.md
src/consumer/component-ops/many-components-writer.ts
src/environment/environment.ts
src/environment/isolator.ts
src/npm-client/install-packages.ts
src/npm-client/npm-client.ts
src/scope/extensions/install-extensions.ts

Implements https://github.com/teambit/bit/issues/2258.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2259)

Don't install devDependencies packages upon extensions

---

CHANGELOG.md
e2e/commands/export.e2e.1.ts
e2e/commands/link.e2e.1.ts
src/api/consumer/lib/export.ts
src/bit-id/bit-ids.ts
src/consumer/config/component-overrides.ts
src/consumer/config/consumer-overrides.ts
src/links/node-modules-linker.ts
src/scope/component-ops/export-scope-components.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2265)

support overrides of the workspace defaultScope per components

---

CHANGELOG.md
e2e/flows/dependencies-as-packages.e2e.2.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

Happens when multiple test files require the same bit component.
Fixes https://github.com/teambit/bit/issues/2267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2269)

Fix duplicate devDependencies 

---

e2e/bit-hub/import-from-bit-hub.ts
e2e/commands/export.e2e.1.ts
e2e/commands/import.e2e.1.ts
e2e/commands/isolate.e2e.1.ts
e2e/commands/link.e2e.1.ts
e2e/commands/log.e2e.1.ts
e2e/commands/remove.e2e.1.ts
e2e/commands/show.e2e.2.ts
e2e/commands/status.e2e.2.ts
e2e/commands/tag.e2e.1.ts
e2e/commands/watch.e2e.2.ts
e2e/flows/dist-outside-components.e2e.2.ts
e2e/flows/sort-components-output.e2e.3.ts
e2e/functionalities/auto-tagging.e2e.2.ts
e2e/functionalities/capsule.e2e.2.ts
e2e/hooks/javascript-hooks.e2e.3.ts
e2e/typescript/typescript.e2e.3.ts
src/e2e-helper/e2e-fixtures-helper.ts

this is done to facilitate blocking relative-path feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2266)

refactor e2e fixtures, remove lots of fixtures duplication

---

CHANGELOG.md
e2e/functionalities/capsule.e2e.2.ts
src/consumer/component/sources/data-to-persist.ts

happpens when a component and its dependency have the same filename
fixes https://github.com/teambit/bit/issues/2264
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2270)

fix dependencies link generation on capsule

---

CHANGELOG.md
src/scope/component-ops/export-scope-components.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2275)

fix memory heap error when exporting a large amount of data

---

.bitmap
src/cli/command-registry.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2290)

fix circular json

---

src/app.ts

- improve error printing
- relate to #2280
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2287)

improve error printing

---

src/e2e-helper/e2e-extensions-helper.ts
src/extensions/bit/bit.ts
src/harmony/extension-graph/extension-graph.ts
src/harmony/extension.ts
src/harmony/harmony.ts
src/legacy-extensions/extensions-loader.ts

- load extensions by the correct loader (legacy or harmony)
- load only extension that marked as legacy via the old extension loader
- load new extensions via harmony
- relate to #2280
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2288)

load extensions by the correct loader (legacy or harmony)

---

src/scope/graph/components-graph.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2311)

basic component graph with dependencies labeled

---

src/environment/capsule-builder.ts
src/extensions/capsule/capsule.ts
src/extensions/capsule/orchestrator/types/capsule-options.ts
src/extensions/pipes/component-walker.ts
src/extensions/workspace/workspace.ts

- Reuse capsules.
- Sync modification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2327)

Pipes cache communication

---

src/consumer/component-ops/component-writer.ts
src/consumer/component-ops/many-components-writer.ts
src/environment/capsule-builder.ts

They are exactly the same as "populateComponentsFilesToWrite()"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2347)

refactor, remove "populateComponentsFilesToWriteForCapsule" methods

---

e2e/extensions/extension.e2e.3.ts
src/e2e-helper/e2e-extensions-helper.ts
src/e2e-helper/e2e-helper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2346)

add basic extension e2e-test to make sure extensions are loaded

---

CHANGELOG.md
e2e/commands/build.e2e.1.ts
src/consumer/component-ops/component-writer.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2348)

fix dynamic dist reference from package.json (#1808) when isolating via capsule

---

e2e/harmony/extensions-config.e2e.3.ts

remove only from e2e

---

CHANGELOG.md
README.md
e2e/commands/build.e2e.1.ts
e2e/commands/export.e2e.1.ts
e2e/flows/no-scope.e2e.2.ts
e2e/harmony/extensions-config.e2e.3.ts
src/app.ts
src/cli/commands/public-cmds/export-cmd.ts
src/consumer/component-ops/component-writer.ts
src/e2e-helper/e2e-fixtures-helper.ts
src/fixtures/fixtures.ts
src/utils/bit/package-name-to-component-id.spec.ts
src/utils/bit/package-name-to-component-id.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2358)

fix conflicts after merging master to harmony/main

---

src/consumer/component/consumer-component.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-versions-resolver.ts
src/consumer/component/package-json-file.ts
src/consumer/component/package-json-utils.ts
src/environment/isolator.ts
src/links/dependency-file-link-generator.ts
src/links/link-generator.ts
src/links/node-modules-linker.ts
src/utils/bit/component-id-to-package-name.ts
src/utils/bit/component-node-modules-path.ts

also, refactor getNodeModulesPathOfComponent to use componentIdToPackageName
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2361)

Use defaultScope when setting "name" prop of package.json

---

package.json
src/extensions/cli/legacy-command.tsx
src/extensions/compile/compile.cmd.tsx
src/extensions/composer/compose.cmd.tsx
src/extensions/graph/insights.cmd.tsx
src/extensions/install/failed-to-install.tsx
src/extensions/install/install.cmd.tsx
src/extensions/paper/command.tsx
src/extensions/paper/commands/help.cmd.tsx
src/extensions/paper/exceptions/already-exists.tsx
src/extensions/paper/exceptions/paper-error.tsx
src/extensions/scripts/run.cmd.tsx
src/extensions/test/test.cmd.tsx
src/extensions/watch/watch.cmd.tsx
src/extensions/workspace/list.cmd.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2370)

restore sanity to .tsx files by configuring prettier to treat them as well

---

src/extensions/capsule-ext/component-capsule.ts
src/extensions/capsule-ext/container.ts
src/extensions/compile/compile.manifest.ts
src/extensions/compile/compile.provider.ts
src/extensions/compile/compile.ts
src/extensions/composer/compose.cmd.tsx
src/extensions/scripts/ids-and-scripts.ts
src/extensions/scripts/pipe/pipe.ts
src/extensions/scripts/run.cmd.tsx
src/extensions/scripts/script.ts
src/extensions/scripts/scripts.ts
src/extensions/scripts/walker/component-walker.spec.ts
src/extensions/scripts/walker/component-walker.ts
src/extensions/scripts/walker/execution-reporter.ts
src/extensions/scripts/walker/sub-graph.ts
src/extensions/test/test.ts

enable communication between the main process and the scripts running on the capsules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2379)

Improve scripts infrastructure 

---

src/extensions/dependency-resolver/readme.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2376)

README for dependency-resolver

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2383)

update librarian to v3.6.1

---

src/extensions/install/install.cmd.tsx
src/extensions/install/install.provider.ts
src/extensions/install/install.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2392)

refactor bit-install, move the logic from the command tsx file to a new class

---

CHANGELOG.md
e2e/commands/link.e2e.1.ts
e2e/commands/status.e2e.2.ts
e2e/flows/dependencies-as-packages.e2e.2.ts
package-lock.json
package.json
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

without resolving their paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2391)

resolve bit components by package.json only 

---

e2e/fixtures/extensions/gulp-ts/react.manifest.js
e2e/harmony/tasks.e2e.3.ts
src/e2e-helper/e2e-command-helper.ts
src/extensions/bit/bit.manifest.ts
src/extensions/create/README.md
src/extensions/create/create.cmd.tsx
src/extensions/create/create.manifest.ts
src/extensions/create/create.provider.ts
src/extensions/create/create.ts
src/extensions/create/index.ts
src/extensions/workspace/workspace.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2403)

introduce a new extension "create" to generate components by templates

---

src/extensions/compile/README.md
src/extensions/compile/compile.ts

before it used a workaround to get it from build task.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2410)

fix compile extension to get the config from the workspace config 

---

src/cli/command-registry.ts
src/npm-client/npm-client.ts

"defaultPackageManagerArgs[packageManager] is not iterable"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2409)

Fix logging errors and fix error on import

---

src/api/consumer/lib/capsule-isolate.ts
src/extensions/bit/bit.ts
src/extensions/component/component.ts
src/extensions/network/network.ts
src/extensions/workspace/workspace.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2413)

refactor(network): graph as network property

---

src/api/consumer/lib/capsule-isolate.ts
src/cli/commands/public-cmds/capsule-cmd.ts
src/extensions/bit/bit.ts
src/extensions/capsule/capsule.manifest.ts
src/extensions/capsule/capsule.ts
src/extensions/component/component.ts
src/extensions/network/index.ts
src/extensions/network/network.ts
src/extensions/network/orchestrator/types/capsule-options.ts
src/extensions/workspace/workspace.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2414)

refactor(network): separate consumer and network subnetwork creation

---

e2e/commands/add.e2e.1.ts
e2e/commands/export.e2e.1.ts
e2e/commands/show.e2e.2.ts
e2e/functionalities/binary-files.e2e.2.ts
e2e/functionalities/capsule.e2e.2.ts
e2e/platforms/angular.e2e.3.ts
src/e2e-helper/e2e-env-helper.ts
src/e2e-helper/e2e-fixtures-helper.ts

(preparation of a future feature that adds a flag for all add commands)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2423)

refactor e2e-tests, use "bit add" command only through the helper

---

src/extensions/isolator/readme.md

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2428)

docs(isolator): readme

---

CHANGELOG.md
e2e/functionalities/workspace-config.e2e.3.ts
src/cli/command-registrar.ts
src/cli/commands/private-cmds/cat-component-cmd.ts
src/consumer/config/consumer-overrides.ts
src/e2e-helper/e2e-command-helper.ts
src/logger/logger.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2429)

deprecate overrides of files (using file:// prefix)

---

e2e/commands/import.e2e.1.ts
e2e/commands/tag.e2e.1.ts
src/cli/commands/public-cmds/add-cmd.ts
src/cli/commands/public-cmds/install-cmd.ts
src/cli/commands/public-cmds/link-cmd.ts
src/cli/commands/public-cmds/tag-cmd.ts
src/cli/default-error-handler.ts
src/cli/templates/all-help.ts
src/cli/templates/component-issues-template.ts
src/scope/component-ops/export-scope-components.ts

Improve messaging of recent flags/errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2436)

Messages editing

---

package-lock.json
package.json
src/api/consumer/lib/capsule-isolate.ts
src/cli/commands/public-cmds/capsule-cmd.ts
src/extensions/package-manager/package-manager.manifest.ts
src/extensions/package-manager/package-manager.provider.ts
src/extensions/package-manager/package-manager.ts
src/extensions/reporter/index.ts
src/extensions/reporter/reporter.manifest.ts
src/extensions/reporter/reporter.provider.ts
src/extensions/reporter/reporter.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2441)

feat(harmony): reporter extension

---

CHANGELOG.md
src/api/consumer/lib/feature-toggle.ts
src/constants.ts
src/e2e-helper/e2e-command-helper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2442)

add infrastructure for feature-toggle

---

src/extensions/bit/bit.manifest.ts
src/extensions/bit/bit.provider.ts
src/extensions/bit/bit.ts
src/extensions/install/install.manifest.ts
src/extensions/install/install.provider.ts
src/extensions/install/install.ts
src/extensions/isolator/isolator.ts
src/extensions/package-manager/package-manager.ts
src/extensions/reporter/reporter.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2448)

feat(install): use reporter to report status

---

package-lock.json
src/consumer/component-ops/component-writer.ts
src/consumer/component-ops/many-components-writer.ts
src/consumer/component/package-json-file.ts
src/consumer/component/package-json-utils.ts
src/extensions/isolator/isolator.ts
src/extensions/isolator/write-components-to-capsules.ts
src/extensions/package-manager/package-manager.ts

- Un-remove install cache
- Added packageManager entry in capsule package.json for install cache
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2453)

caching install keeps getting removed

---

src/extensions/isolator/isolator.ts

- Comment caching for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2457)

comment out

---

package-lock.json
package.json
src/api/consumer/lib/tag.ts
src/cli/templates/list-template.ts
src/consumer/component-ops/component-writer.ts
src/consumer/component-ops/import-components.ts
src/consumer/component/components-list.ts
src/scope/component-ops/auto-tag.ts
src/scope/models/model-component.ts
src/scope/scope.ts
src/utils/resolveLatestVersion.ts

- update harmony to v0.0.11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2452)

update harmony version

---

src/extensions/package-manager/package-manager.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2458)

fix(package-manager): show command being run in output

---

package-lock.json
src/extensions/bit/bit.provider.ts
src/extensions/bit/bit.ts
src/extensions/workspace-config/extension-config-list.ts
src/extensions/workspace-config/readme.md
src/extensions/workspace/core-configurable-extensions.ts
src/extensions/workspace/workspace.provider.ts
src/extensions/workspace/workspace.ts

- move extension loading and resolving to workspace extension
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2462)

move extension loading and resolving to workspace extension

---

src/extensions/install/install.ts
src/extensions/workspace/workspace.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2468)

refactor(reporter): change api to only end at the end

---

package-lock.json
package.json
src/extensions/reporter/reporter.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2475)

feat(reporter): make spinner responsive to terminal size

---

CHANGELOG.md
e2e/commands/link.e2e.1.ts
src/consumer/component-ops/codemod-components.ts
src/e2e-helper/e2e-fs-helper.ts
src/utils/string/replace-package-name.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2476)

fix "bit link --rewire" for css/sass/less files

---

e2e/harmony/extensions-config.e2e.3.ts
src/extensions/package-manager/package-manager.ts
src/extensions/reporter/README.md
src/extensions/reporter/get-column-count.ts
src/extensions/reporter/logger.ts
src/extensions/reporter/reporter.ts
src/extensions/reporter/status-line.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2477)

refactor(reporter): logger interface

---

CHANGELOG.md
src/environment/isolator.ts
src/npm-client/npm-client.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2489)

fix capsule to not hang forever when running build/tag/isolate and npm emits errors

---

src/scope/graph/components-graph.ts
src/scope/scope.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2491)

add a method to get components graph by scope

---

src/extensions/flows/flows.ts

- Just to emphasis current bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2505)

cant find config

---

e2e/harmony/extensions-config.e2e.3.ts
src/consumer/config/component-config.ts
src/consumer/config/extension-data.ts
src/extensions/workspace/workspace.provider.ts

- enable extensions config e2e tests
- do not load extension config for itself
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2511)

enable extensions config e2e tests

---

src/extensions/flows/flow/flow.ts
src/extensions/flows/flows.ts

- take flows config from components correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2518)

take correctly flows config from components

---

.circleci/config.yml
CHANGELOG.md
package-lock.json
src/consumer/component/consumer-component.ts
src/jsdoc/jsdoc/jsdoc-parser.ts
src/jsdoc/parser.ts
src/jsdoc/react/react-parser.spec.ts
src/jsdoc/react/react-parser.ts
src/jsdoc/vue/vue-parser.spec.ts
src/jsdoc/vue/vue-parser.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2522)

support react-docs of multiple exports

---

e2e/fixtures/extensions/gulp-ts/transpile.js
e2e/harmony/flows.e2e.4.ts
src/e2e-helper/e2e-command-helper.ts
src/extensions/flows/task/execution-stream.ts
src/extensions/flows/task/task.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2524)

fix flows ("bit run build")

---

src/extensions/flows/run/handle-run-stream.tsx
src/extensions/flows/run/run.cmd.tsx
src/extensions/workspace/workspace.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2532)

fix(output): do not end unnecessarily

---

src/extensions/isolator/isolator.ts
src/extensions/package-manager/package-manager.ts
src/extensions/workspace/workspace.ts

- cache package install
- detect package manager change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2531)

cache install package, identify packageManager change

---

src/extensions/flows/cache.ts

- chance cache-flow.json location
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2533)

insert cache-flow to capsule folder

---

e2e/harmony/flows.e2e.4.ts
src/extensions/isolator/isolator.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2535)

improve and fix the flow test to make sure the dists are written

---

e2e/harmony/compile.e2e.4.ts
src/e2e-helper/e2e-command-helper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2540)

add e2e-test for bit compile command

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2553)

update pkg to v4.4.6 and re-enable it

---

.circleci/config.yml

- merge from prod branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2554)

update pkg to v4.4.6 and re-enable it (#2553)

---

e2e/functionalities/auto-tagging.e2e.2.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2558)

fix an e2e-test that failed on harmony/main

---

src/extensions/insights/all-insights/duplicate-dependencies.tsx
src/extensions/insights/all-insights/find-cycles.tsx
src/extensions/insights/exceptions/no-data-for-insight.tsx
src/extensions/insights/insights.cmd.tsx

- changed rendering
- bug fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2556)

Insight fixes

---

e2e/harmony/load-extensions.e2e.4.ts
src/extensions/install/install.ts
src/extensions/package-manager/package-manager.ts
src/extensions/reporter/reporter.ts
src/extensions/workspace/workspace.provider.ts
src/extensions/workspace/workspace.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2567)

refactor(reporter): treat reporter as a view layer

---

package-lock.json
package.json
src/consumer/login/login.ts

- Updated "Open" from 7.0.2 => 7.0.3
- Added option url = true when using open
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2557)

fix #2551, Updated open dependency and added url:true

---

src/extensions/reporter/status-line.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2570)

fix(spinner): make arbitrary stdout playnice with the status line

---

.circleci/config.yml
CHANGELOG.md
e2e/commands/link.e2e.1.ts
package-lock.json
package.json
src/api/consumer/lib/link.ts
src/cli/commands/public-cmds/link-cmd.ts
src/consumer/component-ops/codemod-components.ts
src/consumer/login/login.ts
src/e2e-helper/e2e-command-helper.ts
src/links/linker.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2571)

merge from master and prod into harmony/main

---

src/extensions/reporter/reporter.ts
src/extensions/reporter/status-line.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2575)

fix(reporter): output properly

---

e2e/harmony/compile.e2e.4.ts
e2e/harmony/extensions-config.e2e.3.ts
e2e/harmony/flows.e2e.4.ts
src/e2e-helper/e2e-fixtures-helper.ts
src/e2e-helper/e2e-helper.ts
src/extensions/flows/cache.ts

- Fix flows to work on imported components.
- Add an e2e-test for Flows on imported components.
- Add an e2e-test to make sure 3rd party extensions work on imported components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2587)

Make Flows working on imported components

---

src/extensions/flows/flows.ts
src/extensions/flows/network/network.ts
src/extensions/flows/run/run.cmd.tsx
src/extensions/reporter/reporter.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2589)

feat(flows): output skeleton

---

e2e/harmony/extensions-config.e2e.3.ts
src/consumer/component/consumer-component.ts
src/scope/component-ops/get-flattened-dependencies.ts
src/scope/graph/components-graph.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2594)

add extensions flattened dependencies into dev flattened dependencies

---

src/api/consumer/lib/capsule-isolate.ts
src/cli/commands/public-cmds/capsule-cmd.ts
src/extensions/flows/flows.manifest.ts
src/extensions/flows/run/handle-run-stream.tsx
src/extensions/flows/run/run.cmd.tsx
src/extensions/install/install.ts
src/extensions/logger/README.md
src/extensions/logger/index.ts
src/extensions/logger/logger.manifest.ts
src/extensions/logger/logger.provider.ts
src/extensions/logger/logger.ts
src/extensions/package-manager/package-manager.manifest.ts
src/extensions/package-manager/package-manager.ts
src/extensions/reporter/reporter.manifest.ts
src/extensions/reporter/reporter.provider.ts
src/extensions/reporter/reporter.ts
src/extensions/workspace/workspace.manifest.ts
src/extensions/workspace/workspace.provider.ts
src/extensions/workspace/workspace.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2610)

refactor(logger): own extension once again

---

src/extensions/flows/run/handle-run-stream.tsx
src/extensions/flows/run/run.cmd.tsx
src/extensions/package-manager/index.ts
src/extensions/package-manager/package-manager.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2615)

fix(flows): better output for flows run

---

src/extensions/flows/README.md
src/extensions/flows/index.ts

- Improved docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2620)

Flows docs api

---

src/extensions/flows/README.md

- iterate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2622)

docs ver 0.0.2

---

src/extensions/flows/README.md

Hi @qballer I made the following changes to the readme, please review and see if you think they fit.
I don't know if the changes i made to "how to implement" actually makes sense (+ i don't know what you mean by the note about `devdependencies` in that context).
- Change the title to the full module name, as this is what people should be used to configure and find. making it easier to understand.
- added more detailed description
- most explanations rely heavily on internal lingo - rewrote some to make it easier to understand for other peeps.
- remove "compileHack" example
- 'variance' renamed to  'variants'
- "fixed" workflow joke ;)
- minor markdown updates
- minor grammar fixes
- added command synopsis
There are some things I think might be missing from the docs:
- are there any …

updated flows readme

---

src/extensions/flows/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2627)

small typo

---

src/extensions/flows/run/run.cmd.tsx
src/extensions/reporter/status-line.ts

-
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2631)

fix(status-line): play nice with stderr

---

src/extensions/compile/compile.ts

Compile extension used to read all paths inside "dist" as files. As a result, if a path is a directory it threw an error. This PR fixes the reading process to fetch files recursively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2639)

fix "bit compile" to not throw an error when a component has directories

---

e2e/commands/watch.e2e.2.ts
e2e/harmony/compile.e2e.4.ts
src/api/consumer/lib/test.ts
src/consumer/component-ops/watch-components.ts
src/extensions/compile/compile.ts
src/scope/scope.ts

or don't have any compiler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2644)

fix "bit compile" to save dists when some components have legacy compilers

---

src/consumer/component-ops/load-flattened-dependencies.ts
src/consumer/component/component-loader.ts
src/consumer/component/consumer-component.ts
src/consumer/config/component-config.ts
src/consumer/consumer.ts
src/extensions/isolator/isolator.ts
src/extensions/workspace/workspace.ts
src/scope/graph/components-graph.ts

Also, add some useful logs to mitigate debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2650)

avoid loading multiple components in parallel

---

.eslintrc.js
src/extensions/cli/legacy-command.tsx
src/extensions/component/component.provider.ts
src/extensions/component/component.ts
src/extensions/component/snap.ts
src/extensions/component/tag-map.ts
src/extensions/graph/component-graph/index.ts
src/extensions/graph/duplicate-dependency.ts
src/extensions/paper/index.ts
src/extensions/paper/paper.extension.ts
src/extensions/paper/paper.provider.ts
src/extensions/workspace-config/index.ts
src/extensions/workspace/core-configurable-extensions.ts
src/extensions/workspace/workspace.ts

enforce to not have more cycles via lint on src/extensions dir.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2651)

remove some cycles from harmony extensions

---

scripts/doc-generator.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2653)

fix doc-generator script to work with harmony

---

src/extensions/scope/scope.provider.ts
src/extensions/workspace/workspace.provider.ts
src/scope/scope.ts

throw an exception if the scope failed loading for an unknown reason
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2656)

avoid loading consumer in the scope extension

---

src/consumer/component-ops/component-writer.ts
src/extensions/compile/compile.ts

Also, ignore the version when searching for the compile ext.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2670)

Avoid installing bit-bin on the capsule

---

src/extensions/isolator/isolator.ts

in the package.json of the capsule.
For example, the "name" can be changed between tags or the "main" can be changed before and after the compile runs. However, since the dependencies were not changed, there is no reason to run the package-manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2669)

avoid running package-manager install when non-dependencies fields were changed

---

e2e/commands/watch.e2e.2.ts
src/e2e-helper/e2e-command-helper.ts
src/extensions/compile/compile.ts
src/extensions/typescript/tsconfig.default.json
src/extensions/typescript/typescript.manifest.js
src/extensions/watch/watch.ts

and external watchers in general.
See https://github.com/teambit/bit/issues/2677 for the specs.

improve "Bit Watch" to support TS Project References

---

src/app.ts
src/cli/default-error-handler.ts
src/extensions/paper/exceptions/paper-error.tsx

- removing legacy usage of paper.

legacy should not consume modern

---

.circleci/config.yml

- require manual approval of windows tests

require manual approval of windows tests

---

CHANGELOG.md
package.json
src/npm-client/npm-client.ts

fix importing compilers and testers for old node versions

---

CHANGELOG.md
e2e/api/add-many.e2e.1.ts
src/specs-runner/worker.ts

wait for the next event loop before exit child process in bit test

---

src/consumer/component-ops/component-writer.ts
src/consumer/config/legacy-workspace-config-interface.ts
src/extensions/config/workspace-config.ts
src/links/node-modules-linker.ts

and link src to node_modules for imported when using workspace.json (not for legacy).

write artifacts on import on node_modules

---

src/api/consumer/lib/feature-toggle.spec.ts
src/api/consumer/lib/feature-toggle.ts
src/cli/commands/public-cmds/init-cmd.ts

to start a new workspace with workspace.jsonc

introduce a new flag "harmony" to "bit init" 

---

src/cli/commands/public-cmds/eject-conf-cmd.ts
src/cli/commands/public-cmds/inject-conf-cmd.ts
src/cli/commands/public-cmds/search-cmd.ts
src/cli/templates/all-help.ts
src/extensions/builder/run.cmd.tsx
src/extensions/cli/cli.extension.ts
src/extensions/cli/commands/help.cmd.tsx
src/extensions/compiler/compiler.cmd.tsx
src/extensions/create/create.cmd.tsx
src/extensions/insights/insights.cmd.tsx
src/extensions/isolator/capsule-create.cmd.tsx
src/extensions/isolator/capsule-list.cmd.tsx
src/extensions/pkg/pack.cmd.tsx
src/extensions/tester/test.cmd.tsx
src/extensions/ui/start.cmd.tsx
src/extensions/watch/watch.cmd.tsx
src/extensions/workspace/install.cmd.tsx

- remove commands not ready for production
- add a group for various commands

improve and organise bit help

---

CHANGELOG.md
e2e/fixtures/scopes/repository-hooks-fixture.js
e2e/functionalities/repository-hooks.e2e.ts
src/e2e-helper/e2e-helper.ts
src/e2e-helper/e2e-scope-json-helper.ts
src/scope/objects/repository-hooks.ts
src/scope/objects/repository.ts
src/scope/scope-json.ts

support hooks for persist and read bit objects into scope

---

CHANGELOG.md
src/api.ts
src/api/consumer/lib/get-scope-component.ts
src/api/scope/lib/scope-list.ts
src/scope/scope-loader.ts
src/scope/scope.ts

- add an option to not use cache when loading scope 
- do not use scope cache by default when loading scope programmatically

Scope cache

---

.circleci/config.yml
package-lock.json
package.json
src/jsdoc/vue/vue-parser.spec.ts

- fix ci
- upgrade @vuedoc/parser

fix ci for workspace ui

---

src/consumer/component-ops/component-writer.ts
src/consumer/component-ops/many-components-writer.ts
src/extensions/config/workspace-config.ts

workspace ui - fix e2e tests

---

package-lock.json
package.json
src/extensions/express/express.extension.ts
src/extensions/express/index.ts
src/extensions/express/types/index.ts
src/extensions/express/types/next.ts
src/extensions/express/types/request.ts
src/extensions/express/types/response.ts
src/extensions/express/types/route.ts

add express extension

---

src/extensions/pkg/publisher.ts
src/extensions/pkg/readme.md
src/scope/component-ops/publish-during-export.ts

Also, add an option to publish all by running `bit publish '*'`.

change publish criteria from having "publishConfig" to having the "name" prop changed

---

src/extensions/react/webpack/webpack.config.js

- support modules for pure css

support modules for pure css

---

src/extensions/react/react.env.ts
src/extensions/typescript/typescript.compiler.ts

Also, try to fix the Windows tests.

improve typescript compiler to write the tests and types async

---

.circleci/config.yml

clone and link explorer project

---

.circleci/config.yml

add npmjs token to circle ci

---

.circleci/config.yml

remove manual linking of react-new-project and explorer

---

package-lock.json
package.json

- component card - added hover effect and link
-
-

component card - added hover effect and link

---

src/extensions/workspace/ui/workspace/workspace.tsx
src/extensions/workspace/workspace-component/component-status.ts
src/extensions/workspace/workspace.graphql.ts
src/extensions/workspace/workspace.ts

- is auto tag - true or false ,will component is waiting for  automatically tag

add component pending to be auto tag, to gql api

---

package.json

- bump for component card - preview now clickable

component card preview should be clickable

---

src/extensions/component/component.graphql.ts
src/extensions/scope/scope.extension.ts
src/extensions/scope/ui/scope.tsx

- fix comp version 
- add env data to scope (id, icon url)

remove status from compoent, add env to scope,

---

src/extensions/isolator/capsule/capsule.ts

fix execute (exec)

---

src/extensions/bit/manifests.ts
src/extensions/compiler/workspace-compiler.ts
src/extensions/dependency-resolver/dependency-resolver.extension.ts
src/extensions/environments/environments.extension.ts
src/extensions/pkg/pkg.extension.ts

change to configure concrete env instead of configure the envs extension with env id inside

---

e2e/commands/watch.e2e.2.ts
e2e/harmony/compile.e2e.4.ts
e2e/harmony/dependency-resolver.e2e.ts
e2e/harmony/publish.e2e.4.ts

fix e2e tests

---

extensions/express/express.main.runtime.ts
extensions/graphql/graphql.main.runtime.ts
extensions/ui/ui-server.ts
extensions/workspace/workspace.ui-root.ts

fix env ws

---

extensions/notifications/ui/notification-center/notification-center.module.scss

fix notification center hiding concealred by zindex

---

.bitmap
extensions/changelog/changelog.section.tsx
extensions/changelog/changelog.ui.runtime.tsx
extensions/component/component.ui.runtime.tsx
extensions/component/section/section.tsx
extensions/component/ui/menu/index.ts
extensions/component/ui/menu/menu-nav.tsx
extensions/component/ui/menu/menu.tsx
extensions/component/ui/menu/nav-plugin.tsx
extensions/compositions/composition.section.tsx
extensions/compositions/compositions.ui.runtime.tsx
extensions/docs/docs.ui.runtime.tsx
extensions/docs/overview.section.tsx

order top bar menu items

---

e2e/commands/tag.e2e.1.ts
e2e/flows/id-with-wildcard.e2e.2.ts
e2e/functionalities/auto-tagging.e2e.2.ts
src/api/consumer/index.ts
src/api/consumer/lib/snap.ts
src/api/consumer/lib/status.ts
src/api/consumer/lib/tag.ts
src/api/consumer/lib/untag.ts
src/cli/commands/public-cmds/status-cmd.ts
src/cli/commands/public-cmds/tag-cmd.ts
src/cli/commands/public-cmds/untag-cmd.ts
src/consumer/bit-map/component-map.ts
src/consumer/component/components-list.ts
src/consumer/component/consumer-component.ts
src/consumer/consumer.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/component-ops/tag-model-component.ts
src/scope/component-ops/untag-component.ts
src/scope/repositories/sources.ts

See #2712  for the full specs.
* introduce `bit tag --persist` flag. On Harmony, without the flag, it does only soft-tag (record the changes to be tagged).
* introduce `bit untag --persisted` flag. On harmony, without the flag, it only removes the soft-tags.

Introduce soft-tag

---

extensions/config/schema.json
extensions/config/workspace-template.jsonc

- Added a JSON schema file for Bit workspace config.
- Update the workspace config template file to use the schema file.

Add json schema and update template to use it

---

extensions/component/component.graphql.ts
extensions/component/ui/use-component-query.ts
extensions/workspace/workspace.graphql.ts

- fix show 404 at start when enter to component page 
- change logic to know if component is not in scope or workspace

fix compoent satus page

---

extensions/sidebar/ui/drawer/drawer.module.scss
extensions/workspace/ui/workspace/workspace-overview/workspace-overview.module.scss
extensions/workspace/ui/workspace/workspace-overview/workspace-overview.tsx

-  sidebar drawer and component card tooltip ui updates

ui improvements 

---

extensions/aspect-loader/aspect-loader.main.runtime.ts
workspace.jsonc

aspect loaded

---

src/consumer/consumer.ts

This happened due to a `Promise.all` instance. Imagine tagging comp1 with auto-tagged comp2, comp1 package.json is written while comp2 is trying to get the dependencies of comp1 using its package.json. 
It is fixed by changing it to be serial, not parallel.

fix random error of "Unexpected end of JSON" when tagging components

---

e2e/commands/watch.e2e.2.ts
extensions/compiler/workspace-compiler.ts
extensions/workspace/index.ts
extensions/workspace/on-component-add.ts
extensions/workspace/on-component-change.ts
extensions/workspace/on-component-events.ts
extensions/workspace/on-component-load.ts
extensions/workspace/watch/output-formatter.ts
extensions/workspace/watch/watch.cmd.tsx
extensions/workspace/watch/watcher.ts
extensions/workspace/workspace.main.runtime.ts
extensions/workspace/workspace.provider.ts
extensions/workspace/workspace.ts

Also, fix the watcher to not break on adding files.

trigger OnComponentRemove event by the watcher

---

extensions/jest/jest.tester.ts
extensions/tester/test-results.ts
extensions/tester/tester.graphql.ts
extensions/workspace/workspace.ts
workspace.jsonc

add error log per test

---

extensions/pnpm/lynx.ts
workspace.jsonc

- write the requested version (in case it's a valid semver) to workspace.jsonc on installing new dependency

requested version on bit install new dependnecy

---

extensions/pnpm/pnpm.package-manager.ts

add default store dir when resolving package version

---

extensions/workspace/watch/watch.cmd.tsx

fixe for time formatting bug

---

.bitmap
extensions/workspace/workspace.ts

include component extensions in workspace always

---

e2e/commands/snap.e2e.2.ts
extensions/dependency-resolver/manifest/workspace-manifest.ts
src/api/consumer/lib/feature-toggle.ts
src/api/consumer/lib/untag.ts
src/consumer/config/extension-data.ts
src/consumer/consumer.ts
src/e2e-helper/e2e-command-helper.ts
src/fixtures/fixtures.ts
src/scope/component-ops/tag-model-component.ts
src/scope/graph/graph.ts
src/scope/models/version.ts
src/scope/repositories/sources.ts

- e2e-helper: support multiple features.
- untag-soft: fix ComponentNotFound error. 
- fix "bit snap" on harmony and fix to have parents.

fix Snap feature to work on Harmony

---

extensions/ui/env-console.tsx

fix ink problem

---

extensions/workspace/watch/output-formatter.ts

fix watch alignment

---

extensions/react/component.json
extensions/react/react.env.ts

- add @babel/runtime and react-dom to get deps from react env
- add @babel/runtime as dep for the react env

add @babel/runtime and react-dom to get deps from react env

---

e2e/commands/snap.e2e.2.ts
e2e/commands/tag.e2e.1.ts
src/consumer/consumer.ts
src/scope/component-ops/tag-model-component.ts
src/scope/models/version.ts
src/scope/repositories/sources.ts

* fix soft-tag after a soft-tag to show the newest version.
* change soft-tag to not run the import for finding flattened dependencies.

fix soft-tag to show the correct versions and not persist anything

---

extensions/graph/dependency.ts
extensions/graph/graph-builder.ts
extensions/graph/graph.graphql.ts
extensions/graph/graph.main.runtime.ts
extensions/graph/graph.provider.ts
extensions/insights/all-insights/duplicate-dependencies.tsx
extensions/insights/all-insights/find-cycles.tsx
extensions/insights/insights.cmd.tsx

- fix graph builder
- add graph query to graphql
- fix insights template to work with ink3 (WIP)

component graph query

---

extensions/component/component.main.runtime.ts
extensions/workspace/workspace.ts

fixed default scope in data entries

---

.circleci/config.yml

support making nightly manually

---

.bitmap
extensions/isolator/isolator.main.runtime.ts
extensions/isolator/symlink-dependencies-to-capsules.ts
extensions/workspace/workspace.ts
src/consumer/bit-map/bit-map.ts
src/scope/network/http/http.ts
workspace.jsonc

- Error handling in HTTP
- Aspect loading.

Http improvements

---

extensions/component/aspect-entry.ts
extensions/component/aspect-list.ts
extensions/component/component.graphql.ts
extensions/workspace/workspace.ts
workspace.jsonc

- expose aspect list on component graphql
- add serialize API to aspect-list and aspect-entry
- add graphql-type-json package
- merge extensions added by legacy code

Aspects graphql

---

extensions/ui/start.cmd.tsx
workspace.jsonc

fix bit start command duration

---

extensions/builder/artifact/artifact-definition.ts
extensions/builder/artifact/artifact-factory.ts
extensions/preview/strategies/env-strategy.ts
src/scope/network/http/http.ts

- Preview now working with artifacts.

preview working

---

build-harmony/package.json

bump build harmony to v0.0.58

---

extensions/dependency-resolver/dependency-resolver.main.runtime.ts
extensions/dependency-resolver/index.ts
extensions/dependency-resolver/package-manager.ts
extensions/dependency-resolver/types.ts
extensions/pnpm/lynx.ts
extensions/pnpm/pnpm.package-manager.ts
workspace.jsonc

add get registries function

---

extensions/graph/graph-builder.ts
extensions/isolator/isolator.main.runtime.ts
extensions/typescript/typescript.compiler.ts
extensions/ui/ui.main.runtime.ts

removing types after compile

---

src/consumer/bit-map/bit-map.spec.ts
src/consumer/bit-map/component-map.ts

Sort files fields of .bitmap file alphabetically to avoid git conflicts

---

extensions/dependency-resolver/registry/registry.ts
extensions/yarn/yarn.package-manager.ts

support base auth for yarn
