extensions/ui/start.cmd.tsx
=> add-no-browser flag

src/consumer/component-ops/load-flattened-dependencies.ts
=> visited for load flatten dependencies

extensions/pnpm/lynx.ts, extensions/pnpm/pnpm.package-manager.ts
=> pass regisries to pnpm install API

.bitmap, extensions/isolator/capsule-list.ts, extensions/preview/generate-link.ts, extensions/typescript/typescript.compiler.ts, extensions/ui/create-root.ts, toolbox/to-windows-compatible-path/index.ts, toolbox/to-windows-compatible-path/to-windows-compatible-path.ts
=> Windows fixes

extensions/compositions/compositions.main.runtime.ts, extensions/docs/docs.main.runtime.ts, extensions/react/component.json, extensions/react/typescript/style.d.ts, extensions/react/webpack/webpack.config.ts, extensions/react/webpack/webpack.preview.config.ts, extensions/ui/component.json, extensions/ui/webpack/webpack.config.js, extensions/ui/webpack/webpack.dev.config.js
- load compositions files with js/jsx file extension
- load docs files with js/jsx file extension	
- support less be default in react env / UI	
- support jsx extensions from webpack
=> Envs fixes

extensions/environments/environments.main.runtime.ts
Once this merged you can configure env id via:
```js
"{ui/*}": {
"teambit.bit/environments": {
"env": "teambit.bit/react"
}
},
```
=> add option to configure env id via teambit.bit/environments

extensions/logger/logger.ts, extensions/pkg/pack.cmd.tsx, extensions/pkg/packer.ts, src/api.ts, src/logger/logger.ts, src/pack/index.ts, src/pack/packer.ts
=> refactor packing components

build-harmony/package.json
=> bump build harmony version to 0.0.87

extensions/workspace/workspace.ts
=> run import objects after bit install

extensions/component/component.graphql.ts, extensions/pkg/pkg.graphql.ts
=> add package name to component graphql

.circleci/config.yml, babel.config.js, build-harmony/package.json
so then working locally will be faster due to the performance improvement of v0.0.90
=> update teambit/bit version in build-harmony

extensions/ui/start.cmd/output-templates/webpack-errors.tsx, extensions/ui/start.cmd/output-templates/webpack-warnings.tsx
=> indexes and other minor fixes

package.json, scripts/assert-master.js
=> add assert master

e2e/harmony/http.e2e.ts, e2e/http-helper.ts
Hopefully, CircleCI will be nicer now.
=> re-enable-http-tests

.eslintrc.js, scopes/component/isolator/capsule/container.ts, scopes/dependencies/dependency-resolver/dependency-installer.ts, scopes/dependencies/dependency-resolver/package-manager-legacy.ts, scopes/harmony/bit/app.ts, scopes/harmony/config/workspace-config.ts, scopes/harmony/pubsub/pubsub.preview.runtime.ts, scopes/pipelines/flows/task/task.ts, scopes/react/react/jest/transformer.js, scopes/stencil/stencil/stencil.tester.ts, scopes/ui-foundation/ui/start.cmd/cli-output.tsx, scopes/workspace/workspace/workspace.ts, scopes/workspace/workspace/workspace.ui-root.ts, src/api/consumer/lib/export.ts, src/bootstrap.ts, src/cli/command-runner.ts, src/consumer/component-ops/many-components-writer.ts, src/consumer/config/consumer-overrides.ts, src/consumer/login/login.ts, src/consumer/migrations/harmony-migrator.ts, src/interactive/utils/run-interactive-cmd.ts, src/jsdoc/vue/vue-parser.ts, src/legacy-extensions/extension-isolate-result.ts, src/scope/component-ops/export-scope-components.ts, src/scope/component-ops/scope-components-importer.ts, src/scope/graph/vizgraph.ts, src/specs-runner/worker.ts
* activate the `@typescript-eslint/no-floating-promises` rule
* fix many places where promises were called without `await`. This fixes many random bugs.
=> fix floating promises

scopes/component/graph/graph-builder.ts
=> fix loading graph from scope

scopes/compilation/compiler/compiler.cmd.ts
=> typo fixing

scopes/ui-foundation/ui/start.cmd/output-templates/component-preview-server-started.tsx
=> fixed the order of servers on the cli

scopes/ui-foundation/ui/start.cmd/cli-output.tsx
- Replacing the two first stages to "Starting..."
Due to the await bug. 
-
-
=> wording on different components server stages

scopes/preview/preview/preview.main.runtime.ts, scopes/preview/preview/runtime-components.ts
- generate link file per executionContext
- track and update components by executionContext (=== envId)
=> Fix compositions

scopes/compilation/compiler/compiler.task.ts, scopes/component/isolator/capsule-list.ts, scopes/component/isolator/isolator.main.runtime.ts, scopes/component/isolator/symlink-dependencies-to-capsules.ts, scopes/pkg/pkg/prepare-packages.task.ts, scopes/pkg/pkg/publisher.ts, scopes/preview/preview/strategies/component-strategy.ts, scopes/scope/scope/scope.main.runtime.ts, scopes/workspace/workspace/capsule-create.cmd.ts, scopes/workspace/workspace/workspace.ts
Currently, it's a complex map, which is not really needed. This simplifying many places we use the CapsuleList.
=> refactor CapsuleList to be an array of capsules only without ids

scopes/ui-foundation/ui/exceptions/unknown-ui.ts, scopes/ui-foundation/ui/ui.main.runtime.ts
happened a lot to me when I tried starting the project with another ui-root. Thought I'd might as well fix this for good.
- hint what UI roots can be used when getting error about invalid ones!
=> show available ui roots when current one is invalid

scopes/component/changelog/ui/change-log-page.tsx, scopes/component/component/ui/use-component-query.ts, scopes/component/ui/version-block/version-block.module.scss, scopes/component/ui/version-block/version-block.tsx, scopes/design/ui/Avatar/user-avatar.tsx
- added links to version's test and compositions tabs
- use component query - request user details in component snap data
- fixed bug in user avatar component
- updated styles according to design QA
=> history tab - ui updates

scopes/scope/scope/scope.graphql.ts, scopes/scope/scope/scope.main.runtime.ts
- Programmatic API for icon.
- GraphQL API for icon.
- Supporting `icon` property on the scope config.
=> Icon support for scopes.

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts, scopes/dependencies/dependency-resolver/registry/registries.ts, scopes/dependencies/dependency-resolver/registry/registry.ts, scopes/dependencies/dependency-resolver/types.ts, scopes/dependencies/pnpm/get-registries.ts, scopes/dependencies/pnpm/lynx.ts, scopes/dependencies/pnpm/pnpm.package-manager.ts, workspace.jsonc
=> send tokens correctly to pnpm

scopes/dependencies/dependency-resolver/dependencies/dependency-list-factory.ts
=> fixes for out of memory in dependency resolver

src/remotes/remote-resolver/remote-resolver.ts
=> add token to resolver function

.bitmap, scopes/component/ui/component-tooltip/component-tooltip.composition.tsx, scopes/component/ui/component-tooltip/component-tooltip.docs.tsx, scopes/component/ui/component-tooltip/component-tooltip.spec.tsx
- Add compositions, docs, and tests for component-tooltip.
=> ui/component-tooltip add compositions, docs and tests

.bitmap, scopes/component/ui/deprecation-icon/deprecation-icon.composition.tsx, scopes/component/ui/deprecation-icon/deprecation-icon.docs.tsx, scopes/component/ui/deprecation-icon/deprecation-icon.spec.tsx
- Add compositions, docs, and tests for deprecation-icon.
=> ui/deprecation-icon add compositions, docs and tests

e2e/harmony/http.e2e.ts, scopes/scope/scope/routes/delete.route.ts, scopes/scope/scope/routes/index.ts, scopes/scope/scope/scope.graphql.ts, scopes/scope/scope/scope.main.runtime.ts, src/api/scope/lib/delete.ts, src/scope/network/http/http.ts
Implemented by creating a new route `api/scope/delete`.
=> implement bit remove --remote for http protocol

.circleci/config.yml, build-harmony/package.json, package.json
=> bump build harmony version

scopes/scope/scope/ui/scope.module.scss, scopes/scope/scope/ui/scope.tsx
=> fixed scope styles - added resets and fixed top bar styles

scopes/compilation/webpack/webpack.main.runtime.ts, workspace.jsonc
- Resolving issues with conflicts re webpack types.
=> Webpack types

src/scope/component-ops/get-flattened-dependencies.ts
E.g. foo requires bar that has baz as a devDependency. 
Currently, we don't save baz a flattenedDevDependency of foo.
=> add dev-deps required by prod-deps as dev-deps

src/scope/network/http/http.ts
=> add headers to all graphql http requests

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts, scopes/dependencies/yarn/yarn.main.runtime.ts, scopes/dependencies/yarn/yarn.package-manager.ts, scopes/workspace/workspace/install.cmd.tsx, scopes/workspace/workspace/workspace.ts
- move bit import to the beginning of the install process
- improve bit install outputs
=> move bit import to the beginning of the install process

scopes/scope/scope/scope.main.runtime.ts, scopes/workspace/workspace/workspace.ts
- import aspects when loading them
- do not try to import local components
=> import aspects when loading them

scopes/ui-foundation/react-router/react-router/route-context.tsx
- include initial state when creating MemoryRouter
=> initial state for in memory react-router

src/logger/logger.spec.ts, src/logger/logger.ts, src/logger/pino-logger.ts, src/logger/winston-logger.ts
Currently, it is very difficult to understand what the issue is.
=> throw for an invalid log level

scopes/ui-foundation/react-router/react-router/react-router.ui.runtime.tsx
In preparation for full links synchronization with bit.dev (including version and state).
Keeping backward compatibility to to allow dependents to update gradually.
=> react-router.navigate() - support full location object

scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
=> only merge top level of extension data in load slot

scopes/dependencies/yarn/yarn.package-manager.ts
=> restore package.json after yarn finish installing

.circleci/config.yml, package.json, src/bootstrap.ts
=> bump minimal node version to 12.15.0

scopes/compilation/compiler/workspace-compiler.ts
It was done historically so then one watch command takes care of legacy and Harmony components, but that's not the case anymore. There are two different watch commands.
=> refactor the new compiler to remove the case of compiling legacy components

src/consumer/component/component-loader.ts, src/consumer/component/dependencies/dependency-resolver/dependencies-data.ts, src/consumer/component/dependencies/dependency-resolver/dependencies-loader.ts, src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
This is needed for the upcoming change of caching the dependencies-data.
=> refactor, remove side effects from DependeciesResolver

scopes/explorer/ui/base-component-card/base-component-card.module.scss, scopes/explorer/ui/base-component-card/base-component-card.tsx
=> base-component-card - removed link

scopes/component/graph/graph.graphql.ts, scopes/ui-foundation/uis/top-bar/top-bar.module.scss
- fix - top bar dropdown hide items from deps graph 
- fix - stable order in graph api results
-
=> stable graph

.bitmap, scopes/design/ui/server-error-page/server-error-page.composition.tsx, scopes/design/ui/server-error-page/server-error-page.docs.tsx, scopes/design/ui/server-error-page/server-error-page.spec.tsx, scopes/design/ui/server-error-page/server-error-page.tsx
- Add compositions, docs, and tests to server-error-page component.
=> server-error-page component - add composition, test and docs files

.bitmap, scopes/dependencies/dependency-resolver/dependency-resolver.graphql.ts, scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
add dependencies to components
=> add dependencies to graphql

src/links/symlink.ts
=> replace fs.unlinkSync with fs.removeSync

scopes/component/dev-files/dev-files.main.runtime.ts, scopes/defender/jest/jest.tester.ts, scopes/defender/tester/index.ts, scopes/defender/tester/tester.service.tsx, scopes/defender/tester/tester.task.ts, scopes/defender/tester/tester.ts, workspace.jsonc
- fix tests pattern that run on all test in workspace
- fix update ui when add new file to watch
=> fix tests pattern

src/scope/models/version.spec.ts, src/scope/version-validator.ts
=> allow tagging versions with deps with resolveFromEnv

scopes/component/component/show/show.cmd.ts, scopes/dependencies/dependency-resolver/show-fragments/serialize-by-lifecycle.ts
- fix bit show column width 
- align dependencies types in bit show
=> fix bit show column width

scopes/dependencies/dependency-resolver/index.ts, scopes/dependencies/dependency-resolver/policy/index.ts
=> added exported types to dependency-resolver index

src/consumer/component/dependencies/dependency-resolver/dependencies-versions-resolver.ts
This is the same as https://github.com/teambit/bit/pull/3524. Only it applies to master rather than `legacy` branch.
=> fix dependencies version resolution to use the dependent package.json

.circleci/config.yml
- new command - update_ssh_agent
- new command - set_git_credentials
- rename tag_and_publish to bit_tag
- new job - bump-bit-bin (extracted from tag_and_publish)
- new job - bit export (extracted from tag_and_publish)
=> circle ci updates

scopes/design/ui/surfaces/menu/section/section.module.scss
- increase css specificity for menu padding. (fixes indent)
=> fix sidebar menu items indent

scopes/dependencies/dependency-resolver/dependency-resolver.graphql.ts
add dependencies policy to graphql
=> add policies to graphql

scopes/preview/preview/ui/component-preview/preview.tsx
=> fix component id overview url

scopes/preview/preview/preview.preview.runtime.tsx, scopes/react/react/component.json, scopes/react/react/webpack/webpack.config.ts, scopes/react/react/webpack/webpack.preview.config.ts, scopes/ui-foundation/ui/webpack/webpack.config.js
- compile mdx to js during preview generation
- add md extension to webpack configs
=> compile mdx to js during preview generation

scopes/component/component/component-factory.ts, scopes/component/component/component.ts, scopes/component/component/snap/snap.ts, scopes/component/component/tag-map.ts, scopes/component/ui/version-block/version-block.tsx, scopes/scope/scope/scope.main.runtime.ts, scopes/workspace/workspace/workspace.ts
-  add new APIs for the component :
- load snap
- get snap iterable
- getClosestTag
- add new API to tag-map to get a map of snap hash to tag
- add getSnap to component factory interface + implement in workspace and scope
- change snap parent prop to be a string[] instead of Snap[]
=> Snaps iterable

scopes/compositions/compositions/compositions.main.runtime.ts, scopes/defender/tester/tester.main.runtime.ts, scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts, scopes/docs/docs/docs.main.runtime.ts, scopes/pipelines/flows/flow/flow.spec.ts
change to recursive glob pattern:
- change it to support spec file to run in subfolder
=> change to recursive glob pattern

scopes/react/react/webpack/webpack.config.ts, scopes/react/react/webpack/webpack.preview.config.ts
=> add '@teambit/babel.bit-react-transformer' as a dependency for the react env

scopes/scope/scope/scope.main.runtime.ts
=> do not build network when resolving scope's user aspects if there are no user aspects

workspace.jsonc
The theme-context component was updated to include the new Roboto font component because the link was removed from the theme-context.
=> update documenter theme-context version

scopes/defender/tester/tester.main.runtime.ts
get tests results from builder aspect
=> get tests results from builder aspect

src/api/consumer/lib/untag.ts, src/cli/commands/public-cmds/tag-cmd.ts, src/cli/commands/public-cmds/untag-cmd.ts, src/e2e-helper/e2e-command-helper.ts
A similar change was made for `bit tag`. The default is not "soft" anymore.
=> replace "persisted" flag of bit-untag with "soft"

scopes/harmony/express/express.main.runtime.ts
prevent from api health check in express to print logger to avoid unnecessary logs
=> ignore health check

scopes/scope/scope/scope.ui-root.ts, scopes/ui-foundation/ui/ui.ui.runtime.tsx
- use location without hostname in react router
- re-enable ssr for scopes
=> Fix scope in bit dev

scopes/scope/sign/sign.cmd.ts, scopes/scope/update-dependencies/update-dependencies.cmd.ts
they shouldn't be shown when running `bit`.
=> change bit-sign and bit-update-dependencies commands to be private

package.json, src/api/consumer/lib/global-config.ts, src/hooks/utils/enrich-context-from-global.ts
=> move from @teambit/gitconfig to the original gitconfig

scopes/mdx/ui/snippet/snippet.spec.tsx
=> comment spec temporarily

src/scope/network/http/http.ts
=> fix deprecate

.circleci/config.yml, scripts/soft-tag-scope-teambit.js
- checkout latest all before tagging
- remove ignore-newest-version from circle tag
- tag modified components instead of all of them
=> circleci - checkout latest all before tagging

scopes/dependencies/dependency-resolver/policy/variant-policy/variant-policy.ts, src/consumer/config/component-overrides.ts, src/scope/models/version.spec.ts, src/scope/version-validator.ts
=> save dependencies with resolve from env with the version only (not as objects)

.circleci/config.yml, scripts/bump-bit-bin-ver.js
It's already part of the bit-tag job.
=> remove the bump-bit-bin job, it is redundant

scopes/compilation/webpack/config/webpack.dev.config.ts, scopes/react/react/react.env.ts
=> support additional entries by custom webpack provided by custom env

scopes/mdx/modules/compiler/mdx-compiler.composition.tsx, scopes/mdx/modules/compiler/mdx-compiler.docs.md
- update MDX compiler examples
=> update mdx compiler examples

scopes/react/react/react.preview.runtime.ts, scopes/ui-foundation/ui/create-root.ts
- support multi providers in the preview
- fix aspect ids on ui root
=> Multi providers and aspect ids

scopes/scope/scope/ui/scope-overview/scope-overview.tsx, scopes/workspace/workspace/ui/workspace/workspace-component-card/workspace-component-card.tsx
- display version in component card
=> added version to cards in workspace/scope

scopes/harmony/logger/logger.ts, src/logger/logger.ts
add support with env to logger json format
=> json logger format

src/logger/pino-logger.ts
- add severity log level to logger
- disable prettyPrint when json format is true
=> add severity level and disable prettyPrint for jso

scopes/workspace/workspace/ui/workspace/workspace-component-card/workspace-component-card.tsx
- workspace component card - dont show version if new
-
-
=> workspace component card - dont show version if new

scopes/react/react-native/index.ts, scopes/react/react-native/jest/jest.config.js, scopes/react/react-native/react-native.main.runtime.ts
- add react-native to jest config.
- export jest config from react-native env to let extensions use it and merge with another config.
=> Update react-native env

e2e/harmony/import-harmony.e2e.ts, src/consumer/component-ops/many-components-writer.ts
It stopped working since the change from `trackDir` to `rootDir`.
=> fix import --path on Harmony

scopes/scope/scope/scope.main.runtime.ts
=> do not reload aspects defined in root config during tagging them

scopes/harmony/graphql/graphql.main.runtime.ts, workspace.jsonc
fix remote subscriptions for api gateway
=> fix remote schemas on subs

scopes/pkg/pkg/pkg.docs.md
=> add docs to pkg

src/api/consumer/lib/fetch.ts, src/cli/commands/public-cmds/fetch-cmd.ts, src/consumer/component-ops/import-components.ts, src/consumer/consumer.ts, src/scope/component-ops/scope-components-importer.ts
- improve the delta calculation between the local and the remote 
- add some more loader messages on import
- introduce a new flag "--from-original-scopes" for "bit fetch" to be able to import indirect dependencies from their original scopes
=> some more performance improvement and a better loader

e2e/harmony/recovery-after-deletion.e2e.ts, src/api/scope/lib/cat-scope.ts, src/api/scope/lib/run-action.ts, src/cli/command-registry-builder.ts, src/cli/commands/private-cmds/run-action.cmd.ts, src/scope/actions/fetch-missing-deps.ts, src/scope/component-ops/scope-components-importer.ts
also, add a command run-action to execute actions against a remote
=> add an option "fetchFromOriginalScopes" to the fetchMissingDeps action

scopes/dependencies/dependency-resolver/dependency-resolver.docs.md, scopes/dependencies/pnpm/pnpm.docs.md, scopes/dependencies/yarn/yarn.docs.md
=> add docs to dependency-resolver, yarn, pnpm

scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts, scopes/dependencies/dependency-resolver/policy/variant-policy/variant-policy.ts, scopes/dependencies/dependency-resolver/policy/workspace-policy/workspace-policy.ts, scopes/harmony/aspect/aspect.env.ts
- find depVersion by the policy with the correct lifecycleType
- use the same getDependencies in aspect env as in the react env
-
=> dep-resolver fixes

scopes/dependencies/dependency-resolver/dependency-installer.ts
- remove node modules dir for all components dirs, since it might contain leftovers from a previous install
=> remove node modules dir for all components dirs

scopes/envs/envs/envs.docs.md
=> add docs to the envs aspect

scopes/harmony/logger/logger.ts, src/logger/logger.ts
Pino supports it but Bit interface didn't have it.
=> logger: support "fatal" level

scopes/component/legacy-bit-id/bit-id.spec.ts, scopes/component/legacy-bit-id/bit-id.ts, scopes/component/legacy-bit-id/utils/is-valid-id-chunk.ts
Currently it allows adding the component but crashes when running any command after that.
=> bit-add: replace spaces in the dir-name with dashes

e2e/fixtures/extensions/node-env/index.ts, e2e/fixtures/extensions/node-env/node-env.extension.ts, e2e/harmony/custom-env.e2e.ts, src/consumer/consumer.ts, src/e2e-helper/e2e-env-helper.ts
currently it throws a ComponentNotFound error.
=> fix untag of a custom env on Harmony

scopes/compilation/bundler/bundler.main.runtime.ts
fix devserver url after add new component
=> fix devserver url after add new component 

scopes/scope/scope/scope.main.runtime.ts, scopes/ui-foundation/ui/start.cmd.tsx
=> made local aspect work on bare scopes

.bitmap, scopes/design/ui/Avatar/styles.module.scss
- add border color to all UI avatar.
=> add border color to all avatar

scopes/harmony/aspect-loader/core-aspects.spec.ts, scopes/harmony/aspect-loader/core-aspects.ts, scopes/workspace/e2e/workspace/e2e-workspace.aspect.ts
also, fix the id of e2e/workspace aspect
=> fix package names of core-aspects to include namespaces

src/scope/network/http/http.ts
=> add connection: keep-alive to http headers

.circleci/config.yml, scripts/bump-bit-legacy-ver.js
to get it work when rerunning the bit_tag job
=> Circle: git-pull before committing the bump-legacy-bit

scopes/scope/scope/routes/action.route.ts, scopes/scope/scope/routes/delete.route.ts, scopes/scope/scope/routes/fetch.route.ts, scopes/scope/scope/routes/put.route.ts, scopes/scope/scope/scope.main.runtime.ts, src/scope/scope.ts
increase node http timout to avoid getting 502 from the server when import huge data of objects.
=> increase node timeout

scopes/scope/scope/scope.main.runtime.ts, src/scope/scope.ts
=> improve scope has id function

scopes/design/ui/not-found-page/not-found-page.tsx, scopes/design/ui/server-error-page/server-error-page.tsx
- Update bit harmony docs link in error and not found pages.
=> Update bit docs link in error and not-found pages

scopes/harmony/config/workspace-template.jsonc
=> add react and react-dom to workspace.jsonc template

src/error/hash-error-object.ts
=> fix Cannot assign to read only property ‘options’ of object when hashing errors

src/api/consumer/lib/deprecation.ts, src/consumer/component-ops/remove-components.ts, src/consumer/lanes/remove-lanes.ts, src/remotes/remote.ts, src/remotes/remotes.ts, src/scope/component-ops/components-deprecation.ts, src/scope/network/http/http.ts, src/scope/network/network-lib.ts, src/scope/scope-remotes.ts, src/scope/scope.ts
This is very useful for remote scopes communication to understands what scope initiate the request.
=> add "x-request-scope" header to identify the source scope

scopes/harmony/graphql/graphql.ui.runtime.tsx, scopes/harmony/graphql/render-lifecycle.tsx
- Remove unused api in `gql.ui`.
- (Already updated in symphony)
=> remove old gql client api

scopes/docs/docs/docs.preview.runtime.tsx, scopes/react/react/docs/docs-app.tsx, scopes/react/react/docs/index.tsx
- Don't pass ApolloProvider for docs (is not using it anyways)
- Handle undefined Provider in DocsApp (just in case..)
=> fix Provider error in workspace docs

src/scope/component-ops/scope-components-importer.ts, src/scope/lanes/remote-lanes.ts
Currently, when merging component-objects during import, it loads the same remote-lane ref files multiple times in parallel, causing some records to get lost. This fixes the issue by loading the file only once.
=> fix writing remote-lanes ref files to not loose records

src/consumer/component-ops/import-components.ts, src/consumer/lanes/create-lane.ts, src/scope/component-ops/scope-components-importer.ts, src/scope/lanes/lanes.ts, src/scope/objects/repository.ts
Similar to https://github.com/teambit/bit/pull/3885.
=> avoid caching objects to persist them later for lane-removal and artifacts-download

scopes/ui-foundation/empty-component-gallery/empty-component-gallery.composition.tsx, scopes/ui-foundation/empty-component-gallery/empty-component-gallery.module.scss, scopes/ui-foundation/empty-component-gallery/empty-component-gallery.tsx, workspace.jsonc
- update link to new docs
- change texts
=> update texts and link in empty collection page

scopes/design/ui/pill-label/index.ts
- add export type from this component.
=> add export type from pill-label component

scopes/compositions/compositions/compositions.tsx, scopes/defender/tester/ui/tests-page.tsx
replace docs links from netlify to new docs.
=> replace docs links

.bitmap, scopes/toolbox/string/ellipsis/ellipsis.docs.md, scopes/toolbox/string/ellipsis/ellipsis.spec.ts, scopes/toolbox/string/ellipsis/ellipsis.ts, scopes/toolbox/string/ellipsis/index.ts
=> add ellipsis function to toolbox scope

scopes/react/react/typescript/tsconfig.json, scopes/stencil/stencil/typescript/tsconfig.json
as it causes some issues with the vscode.
=> remove the recent changes of rootDir in the tsconfig of the workspace

scopes/component/component-id/component-id.spec.ts, scopes/component/component-id/component-id.ts
- fixed namespace in component-id
- added tests for namespace
=> component id - fixed namespace and added some tests

src/consumer/bit-map/bit-map.ts
.bitmap file should not be changed manually, however, if it does, for any reason, `bit status` might show incorrect entries. The reason is that the file paths are cached and this cache is only invalidated when the root-dir is changed. 
This PR invalidates the cache also when the .bitmap is changed.
=> clear file-paths cache upon .bitmap changes

e2e/harmony/custom-env.e2e.ts, src/scope/component-ops/tag-model-component.ts
- fixes the setting of a custom env during tag (not the first tag) when tagging the env along with the components that use it
=> Fix custom env calc

scopes/scope/scope/scope.main.runtime.ts, src/api/scope/lib/fetch.ts, src/scope/scope.ts
helps to get notification when a new import occurs
=> add a new slot for pre-fetch-objects

scopes/scope/scope/routes/fetch.route.ts, src/scope/objects/object-list.ts
- indicate when the server is gone during fetch and throw a descriptive error to the client
- when client canceled the import process, do not crush the server. instead, log the incident and continue
=> handle abort request and response during fetch

build-harmony/package.json, scopes/scope/scope/ui/components-drawer/components.drawer.tsx, scopes/workspace/workspace/ui/workspace-components-drawer/workspace-components.drawer.tsx, workspace.jsonc
- Install new version of base-ui text component that now exist in NPM.
- Use it in scope/workspace components drawer.
https://www.npmjs.com/package/@teambit/base-ui.text.text
=> install new version of base text component

e2e/harmony/clear-cache.e2e.ts, src/consumer/component/component-fs-cache.ts
=> recreate cache path in case of integrity check failure

scopes/design/ui/Avatar/user-avatar.tsx, scopes/design/ui/styles/colors-by-letter/colors-by-letter.docs.md, scopes/design/ui/styles/colors-by-letter/index.ts, scopes/design/ui/styles/colors-by-letter/letter-bg-colors.module.scss, scopes/design/ui/styles/colors-by-letter/letter-colors.module.scss
- Update colors letter to export two separate objects, one for text color and second for backgroundcolor.
- Update Avatar to use the new object.
=> create two separate objects in colors text

src/api/consumer/lib/dependencies.ts, src/cli/commands/public-cmds/dependencies-cmd.ts, src/cli/templates/component-template.ts
It makes it easier to understand the relation between components.
=> improve bit-dependencies command to show the dependencies graph (textually)

scopes/generator/generator/generator.graphql.ts, scopes/generator/generator/generator.main.runtime.ts, scopes/generator/generator/templates.cmd.ts
- add a GraphQL Mutation to create a new component from a template.
- add a GraphQL query to list all available templates.
=> Consume the Generator API through GraphQL

scopes/design/ui/Avatar/avatar.tsx, scopes/design/ui/Avatar/default-avatar.tsx, scopes/design/ui/Avatar/org-avatar.tsx, scopes/design/ui/Avatar/user-avatar.tsx
- add native props to avatar so we can pass onClick function for example.
=> add native props to ui avatar

src/scope/exceptions/component-not-found.ts
=> add the message prop to ComponentNotFound error to be shown correctly on GraphQL

scripts/docker-teambit-bit/Dockerfile, src/consumer/consumer.ts, src/consumer/exceptions/unexpected-package-name.ts, src/scope/scope.ts
Fixes https://github.com/teambit/bit/issues/3982.
=> show a descriptive error when a package-name was used instead of a component-name

scopes/dependencies/dependency-resolver/dependency-linker.ts
should fix https://github.com/teambit/bit/issues/3998.
With this fix, if the previous symlinks were pointing to an older version of bit, this `bit install` will remove the symlinks and re-create them.
=> override aspect-core symlinks in node_modules to accommodate new bit versions

.bitmap, scopes/react/react/react.templates.ts, scopes/react/react/templates/component.ts, scopes/react/react/templates/react-component.ts
@davidfirst need to test locally to see if it works but not sure how to so let me know or merge and I will test it then
=> feat: react component template

.bitmap, scopes/react/react/templates/example-button.ts, scopes/react/react/templates/react-component.ts
add describe block
improve test message
-
-
-
=> fix: react templates describe

scopes/harmony/aspect/aspect.template.ts, scopes/react/react/react.templates.ts, scopes/react/react/templates/react-button/component.ts, scopes/react/react/templates/react-button/composition.ts, scopes/react/react/templates/react-button/docs.ts, scopes/react/react/templates/react-button/index.ts, scopes/react/react/templates/react-button/test.ts, scopes/react/react/templates/react-component/component.ts, scopes/react/react/templates/react-component/composition.ts, scopes/react/react/templates/react-component/docs.ts, scopes/react/react/templates/react-component/index.ts, scopes/react/react/templates/react-component/test.ts
change import of `'@teambit/generator/component-template'` to `'@teambit/generator'`
=> fix import of an internal file of generator

e2e/harmony/create.e2e.4.ts, scopes/generator/generator/generator.main.runtime.ts, src/e2e-helper/e2e-command-helper.ts
=> improve bit-create to auto-recognize namespace as part of the entered name

e2e/harmony/create.e2e.4.ts, scopes/generator/generator/generator.main.runtime.ts
Currently, it creates the record in the .bitmap file without the namespace.
=> fix bit-create with --namespace flag to add the component to the .bitmap file with the namespace

scopes/react/react/templates/react-button/index.ts, scopes/react/react/templates/react-button/test.ts, scopes/react/react/templates/react-component/composition.ts, scopes/react/react/templates/react-component/index.ts, scopes/react/react/templates/react-component/test.ts
remove chai
use toBeTruthy() instead of to.exist
-
-
-
=> fix: react testing templates

scopes/design/ui/Avatar/styles.module.scss, scopes/design/ui/Avatar/user-avatar.tsx
- not render the tooltip on mobile.
=> not render avatar tooltip on mobile

scopes/react/react/templates/react-button/docs.ts, scopes/react/react/templates/react-component/docs.ts
add code snippet and remove playground comment
-
-
-
=> fix: add code snippet to docs

e2e/harmony/preview.e2e.ts, scopes/react/react/webpack/webpack.config.preview.ts
=> add react preset to the react-env to fix preview for jsx files

scopes/generator/generator/component-template.ts, scopes/generator/generator/generator.main.runtime.ts, scopes/generator/generator/templates.cmd.ts, scopes/harmony/aspect/templates/aspect/index.ts, scopes/harmony/node/templates/node-env/index.ts, scopes/react/react-native/templates/react-native-env/index.ts, scopes/react/react/templates/react-button/index.ts, scopes/react/react/templates/react-component/index.ts, scopes/react/react/templates/react-env/index.ts
It makes it easier to understand what each templates does when running `bit templates`.
=> add description field to templates

scopes/generator/generator/component-generator.ts, scopes/generator/generator/create.cmd.ts, scopes/generator/generator/generator.main.runtime.ts
- remove the "files" section.
- add the env-id configured to the created components.
- add a footer with link how to configure the env.
=> add envs data to the bit-create output

scopes/react/react/react.templates.ts, scopes/react/react/templates/react-button-jsx/component.ts, scopes/react/react/templates/react-button-jsx/composition.ts, scopes/react/react/templates/react-button-jsx/docs.ts, scopes/react/react/templates/react-button-jsx/index.ts, scopes/react/react/templates/react-button-jsx/test.ts, scopes/react/react/templates/react-component-jsx/component.ts, scopes/react/react/templates/react-component-jsx/composition.ts, scopes/react/react/templates/react-component-jsx/docs.ts, scopes/react/react/templates/react-component-jsx/index.ts, scopes/react/react/templates/react-component-jsx/test.ts
create templates for jsx
-
-
-
=> feat: react jsx components

scopes/compilation/compiler/events/compiler-error.ts, scopes/compilation/compiler/events/component-compilation-on-done.ts, scopes/docs/docs/events/click-inside-an-iframe.ts, scopes/explorer/command-bar/command-bar.preview.runtime.tsx, scopes/explorer/command-bar/model/key-event/key-event.tsx, scopes/harmony/pubsub/bit-base-event.ts, scopes/harmony/pubsub/pubsub.preview.runtime.ts, scopes/harmony/pubsub/pubsub.ui.runtime.ts, scopes/harmony/pubsub/types.ts, scopes/preview/preview/events/click-inside-an-iframe.ts, scopes/preview/preview/preview.preview.runtime.tsx, workspace.jsonc
- use EventEmitter as event bus in PubSub aspect
- fix PubSub.Preview provider: do not wait for parent connection
- allow sending events from parent (preview.UI) to preview iframes
- fix timestamp type in PubSub event
=> Improve pubsub

scopes/react/react/react.docs.md
=> update react aspect docs

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts, scopes/workspace/workspace/workspace.provider.ts, scopes/workspace/workspace/workspace.ts
=> take into account the package.json in different policy calculations

src/scope/exceptions/no-common-snap.ts
=> fix: grammer error in no common snap

scopes/scope/scope/scope.ui.runtime.tsx, scopes/workspace/workspace/workspace.ui.runtime.tsx
=> feat: rename overview to gallery in workspace

scopes/harmony/node/node.docs.md, scopes/react/react-native/react-native.docs.mdx
=> update node aspect docs

workspace.jsonc
- bump version documenter import action component
-
-
=> feat: bump version doucmenter-ui-import-action

e2e/harmony/dependency-resolver.e2e.ts, scopes/react/react-native/component.json, scopes/react/react-native/react-native.main.runtime.ts, scopes/react/react/component.json, scopes/react/react/react.env.ts, scopes/ui-foundation/ui/component.json, scopes/ui-foundation/ui/webpack/webpack.base.config.ts, workspace.jsonc
- remove redundant dependencies 
- set react versions to be ^16.8 || ^17
to check
=> cleanup react dependencies and set to ^16.8.0 + ^17

scopes/design/ui/Avatar/styles.module.scss, scopes/design/ui/owner-avatar/owner-avatar.module.scss
add default colors when css variables not exist.
- add default colors to ui/avatar.
- add default colors to ui/owner-avatar.
=> add default colors to Avatar and Owner Avatar

scopes/workspace/workspace/workspace.ts
currently, when `workspace.loadAspects()` loads aspects from both workspace and scope, it fails to load the scope aspects from the workspace and it falls back to load them all from the scope. However, once it does that, the workspace component fails. 
In this PR, the components are determined before whether they're workspace or scope and are loaded by the workspace/scope accordingly.
=> fix loading aspects of workspace and scope together

scopes/dependencies/dependency-resolver/dependency-resolver.docs.md
update docs as per Benjis pr to docs repo
https://github.com/teambit/docs/pull/141/files
-
-
-
=> docs: update dependency resolver

scopes/harmony/bit/load-bit.ts, scopes/harmony/cli/cli.main.runtime.ts, src/analytics/analytics.ts, src/bootstrap.ts, src/cli/command-runner.ts
Instead of showing the loader multiple times during the bootstrap, show it only once when loading the aspects. Currently, it's too verbose.
=> fewer loader messages on bootstrap

scopes/harmony/bit/load-bit.ts
=> fix --safe-mode flag to work regardless of the arg location

.circleci/config.yml
=> fix bundling bit for bvm on Mac

e2e/commands/lane.e2e.1.ts, e2e/commands/watch.e2e.2.ts, e2e/functionalities/track-directories.e2e.3.ts, e2e/harmony/babel.e2e.ts, e2e/harmony/custom-env.e2e.ts, e2e/harmony/http.e2e.ts, e2e/harmony/pkg.e2e.ts
Created originally for https://github.com/teambit/bit/pull/3980. Cherry-picked from that PR.
=> Fix Windows e2e-tests

scopes/explorer/ui/base-component-card/card/card.module.scss, scopes/explorer/ui/base-component-card/preview-container/preview-container.module.scss, scopes/explorer/ui/component-card/component-card.composition.tsx, workspace.jsonc
=> install new version of theme provider from base-ui

scopes/scope/ui/scope-title/scope-title.composition.tsx, scopes/scope/ui/scope-title/scope-title.docs.md, scopes/scope/ui/scope-title/scope-title.tsx
- split scopeName prop to pass only the scope name and not the `owner.scopename`. So the color in the Avatar will be the same as in the scope corner.
- add composition file.
- add docs file.
=> update scope title component

scopes/react/react/templates/react-hook/files/component.ts, scopes/react/react/templates/react-hook/files/composition.ts, scopes/react/react/templates/react-hook/files/docs.ts, scopes/react/react/templates/react-hook/files/test.ts, scopes/react/react/templates/react-hook/index.ts
hooks should be camel case not pascal
-
-
-
=> fix: camel case for hooks

scopes/harmony/aspect-loader/aspect-definition.ts, scopes/scope/scope/scope.main.runtime.ts, scopes/ui-foundation/ui/create-root.ts
=> fix for distinguishing core aspect name from the rest

scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
improves HMR and works better than setting cache to false
-
-
-
=> fix: webpack dev server

scopes/component/deprecation/deprecation.fragment.ts, scopes/component/deprecation/deprecation.main.runtime.ts
- add deprecated to bit show using show fragment slot
=> add deprecated to bit show

scopes/mdx/mdx/mdx.main.runtime.ts, scopes/react/react/react.templates.ts, scopes/react/react/templates/mdx-component/files/component.ts, scopes/react/react/templates/mdx-component/files/composition.ts, scopes/react/react/templates/mdx-component/files/docs.ts, scopes/react/react/templates/mdx-component/files/test.ts, scopes/react/react/templates/mdx-component/index.ts
template for mdx
mdx icon for workspace added with correct size
-
-
-
=> feat: mdx template

scopes/compilation/webpack/config/webpack-fallbacks.ts, scopes/compilation/webpack/config/webpack.config.ts, scopes/compilation/webpack/config/webpack.dev.config.ts, workspace.jsonc
- add various fallbacks for webpack
=> Webpack fallbacks

scopes/compilation/webpack/config/webpack.dev.config.ts, scopes/compilation/webpack/webpack.dev-server.ts, scopes/ui-foundation/ui/start.cmd.tsx, scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
- show errors only for preview dev server
- show errors only for ui dev server
- prevent different port between the config port and the listen arg port
=> Webpack outputs - show errors only

src/scope/objects/repository.ts
This mainly affects artifacts generated by Preview aspect (webpack files). It's better to re-load them from the disk if needed than storing them in-memory.
=> do not cache objects bigger than 100KB in-memory to avoid out-of-memory errors

scopes/react/react/react.application.ts
fix relative path of react application
=> react root path

scopes/compilation/bundler/dev-server.service.ts, scopes/defender/linter/linter.service.ts, scopes/defender/tester/tester.service.tsx, scopes/docs/docs/docs.service.ts, scopes/harmony/application/application.service.ts, scopes/pipelines/builder/builder.service.tsx, scopes/semantics/schema/schema.service.ts
I added missing service names which are used in error messages (a real name is better than "undefined"!)
=> add missing service names

src/cli/templates/component-issues-template.ts
to suggest running "bit compile" on Harmony
=> improve "missing packages dependencies" error on bit-status

.bitmap, scopes/design/ui/empty-box/empty-box.composition.tsx, scopes/design/ui/empty-box/empty-box.module.scss
- added border radius
- added truncate to all texts
=> updated empty box

.bitmap, scopes/angular/angular/angular.env.ts, scopes/angular/angular/angular.main.runtime.ts, scopes/angular/angular/eslint/eslintrc.ts, scopes/angular/angular/typescript/tsconfig.json, scopes/angular/eslint-config-bit-angular/bit-angular-eslint.docs.md, scopes/angular/eslint-config-bit-angular/bit-angular-eslint.js, scopes/angular/eslint-config-bit-angular/component.json, scopes/angular/eslint-config-bit-angular/index.js, scopes/defender/eslint/eslint.linter.ts, scopes/defender/eslint/eslint.main.runtime.ts, scopes/defender/linter/index.ts, scopes/envs/envs/environment.ts, scopes/react/react/react.env.ts, scopes/stencil/stencil/stencil.env.ts
This PR adds eslint for Angular aspect, the env is still WIP (but that's ok because we're merging into the angular branch, not master).
=> add eslint-config-bit-angular aspect

scopes/react/react/react.docs.md, scopes/react/react/templates/mdx-component/files/docs.ts, scopes/react/react/templates/mdx-component/files/test.ts, scopes/react/react/templates/mdx-component/index.ts, scopes/react/react/templates/react-component-js/files/docs.ts, scopes/react/react/templates/react-component-js/files/test.ts, scopes/react/react/templates/react-component-js/index.ts, scopes/react/react/templates/react-component/files/docs.ts, scopes/react/react/templates/react-component/files/test.ts, scopes/react/react/templates/react-component/index.ts, scopes/react/react/templates/react-context/files/docs.ts, scopes/react/react/templates/react-context/files/test.ts, scopes/react/react/templates/react-hook/files/component.ts, scopes/react/react/templates/react-hook/files/docs.ts, scopes/react/react/templates/react-hook/files/test.ts
better docs generation
remove describe block
improve labels ordering and texts
add templates to aspect docs
remove live playground when not necessary to show
-
-
-
=> feat: improve templates for react

scopes/component/component/ui/use-component-query.ts
- fix parse error useComponentQuery. (do not try to parse empty object)
=> fix parse error useComponentQuery

scopes/workspace/modules/match-pattern/match-pattern.spec.ts, scopes/workspace/modules/match-pattern/match-pattern.ts, scopes/workspace/variants/variants.main.runtime.ts
=> support excluding in variants by using "!"

scopes/component/component/ui/aspect-page/aspect-page.tsx
=> fix: link to correct docs

workspace.jsonc
- moved @apollo/client to peer and added as a dependency only inside teambit/bit
=> moved @apollo/client to peer

src/consumer/component/package-json-transformer.ts, src/utils/bit/component-id-to-package-name.ts, src/utils/bit/component-placeholders.spec.ts, src/utils/bit/component-placeholders.ts
=> fix wrong package name when creating capsules

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts, src/utils/packages/resolve-pkg-data.ts
Currently, it shows this issue on Windows although everything is fine.
=> fix import from non-main file issue on Windows

scopes/envs/envs/environments.main.runtime.ts, scopes/envs/envs/exceptions/env-not-configured-for-component.ts
- improve the error `EnvNotConfiguredForComponent` to suggest adding the env to the workspace.jsonc correctly.
- remove duplications of this error message.
=> improve the error EnvNotConfiguredForComponent to suggest a solution

scopes/harmony/cli/commands/help.cmd.tsx
add colors so its visually easier to see
fix docs link
add more spacing
=> feat: add colors to help command

scripts/establish-dev-link-windows.js
=> avoid using fs.rmSync in the dev-link-windows script as it is supported only from v14.14.0

src/cli/command-registry.ts
-improve colors for cli commands
=> feat: add colors for cli commands

scopes/component/graph/ui/graph-page/graph-page.tsx
- Modify text to say Component dependencies so users don't think its all dependencies. This makes it clearer that its only component dependencies
=> update: dependencies title

scopes/compositions/compositions/compositions.module.scss
- reintroduced the css that fixed the underline
-
-
=> fix link underline in composition menu bar

scopes/harmony/node/node.main.runtime.ts, scopes/react/react/react.main.runtime.ts
- expose the overrideCompiler and overrideCompilerTasks apis on the base node env
-
-
=> add compiler override to node env

e2e/harmony/log.e2e.ts, src/cli/command-registry.ts
It broke after the recent changes with the CLI help.
=> fix global --log flag

scopes/react/react/webpack/webpack.config.preview.dev.ts
Fixes #4312
Fix local images not working in React environment in Bit workspace.
=> fix local images not working in React environment (#4312)

e2e/harmony/show-harmony.e2e.ts, scopes/component/component/component-factory.ts, scopes/component/component/show/show.cmd.ts, scopes/scope/scope/scope-component-loader.ts, scopes/scope/scope/scope.main.runtime.ts, src/api/consumer/lib/get-scope-component.ts, src/consumer/component/component-loader.ts, src/scope/component-ops/scope-components-importer.ts
This flag stopped working on Harmony since `bit show` was re-implemented.
This PR implements the flag.
=> fix "--remote" flag of "bit show" on Harmony

scopes/react/react/component.json, scopes/react/react/webpack/webpack.config.preview.dev.ts, scopes/react/react/webpack/webpack.config.preview.ts
- add svg-url-loader as dependency
- configure svg-url-loader for react env 
- resolves #4341
=> add svg-url-loader

scopes/react/react/webpack/webpack.config.preview.dev.ts, scopes/react/react/webpack/webpack.config.preview.ts
=> add webpack alias for react/jsx-runtime and react/jsx-dev-runtime

scopes/harmony/node/node.main.runtime.ts
- add useWebpack to node env
-
-
=> Add usewebpack to node env

scopes/react/aspect-docs/react-native/react-native.mdx
- Explain the issue with component that use native library and the composition can't be rendered on the Web.
- Explain the solution and how to do.
I already explained this on an issue with this problem: https://github.com/teambit/bit/issues/4230#issuecomment-849032809
=> React Native composition issue with native library

scopes/design/ui/Avatar/styles.module.scss, scopes/design/ui/Avatar/user-avatar.tsx, scopes/design/ui/owner-avatar/owner-avatar.composition.tsx, scopes/design/ui/owner-avatar/owner-avatar.module.scss, scopes/design/ui/owner-avatar/owner-avatar.tsx
- Fix fallback solo avatar in owner avatar.
- Center solo avatar icon.
=> fix solo avatar

scopes/component/component/component.ui.runtime.tsx, scopes/component/component/ui/component.tsx, scopes/ui-foundation/react-router/ui/link/link.tsx, scopes/ui-foundation/react-router/ui/nav-link/nav-link.tsx
- new slot in comp page, before / after internal routes
=> add new slot for comp page content

workspace.jsonc
- Install new version of Consumable Link component that use the latest version of Copy Box.
=> install new version of consumable link

scopes/workspace/workspace/ui/workspace/use-workspace.ts
=> fix build status query

scopes/workspace/workspace/link/component-list-links.ts, scopes/workspace/workspace/link/link.cmd.ts
It's a regression due to another PR that was merged today.
=> fix bit link output to show each component link in a separate row

scopes/react/aspect-docs/react/react.mdx
- fix docs re overriding webpack configs
-
-
=> fix webpack overrides documentation

workspace.jsonc
- Install new version of import action that including the new version of copy-box with font changes.
=> install new version of import action component

scopes/compilation/bundler/component-server.ts, scopes/compilation/bundler/dev-server.service.ts, scopes/compilation/bundler/select-port.ts, scopes/toolbox/network/get-port/get-port.spec.ts, scopes/toolbox/network/get-port/get-port.ts
=> fix port issues

scopes/ui-foundation/react-router/ui/link/link.tsx, scopes/ui-foundation/react-router/ui/nav-link/nav-link.tsx
- disable types for our react-router link adapters
- should work around #4401
=> workaround for react-router link types

scopes/dependencies/yarn/yarn.package-manager.ts, yarn.lock
Also, updated the yarn.lock file in this repo.
=> fix yarn package-manager to update yarn.lock file

src/utils/fs/create-symlink-or-copy.ts
It should help us debugging the EPERM error on Windows.
=> add more logs inside the symlink function for better debugging

scopes/preview/preview/preview.route.ts
=> send buffer back instead of string when sending preview artifacts

.circleci/config.yml, scripts/docker-teambit-bit/Dockerfile-bit, scripts/docker-teambit-bit/Dockerfile-bit-server, scripts/docker-teambit-bit/Dockerfile-symphony, scripts/docker-teambit-bit/README.md
- make docker image for cli with bvm
- make docker image for bit server
- make docker image for symphony (internal use)
- add readme for using bit's docker containers
=> docker restructuring 

.circleci/config.yml, scripts/docker-teambit-bit/Dockerfile-bit, scripts/docker-teambit-bit/Dockerfile-bit-server, scripts/docker-teambit-bit/README.md
=> Fix bit server docker

scopes/defender/ui/test-table/test-table.tsx, scopes/design/ui/Avatar/index.ts, scopes/design/ui/Avatar/org-avatar.tsx
- pass ...rest in test table
- exposed orgAvatarProps
=> UI updates

scopes/scope/ui/empty-scope/empty-scope.tsx
- fix double quote in empty workspace component.
=> fix double quote in empty workspace component

e2e/harmony/update-dependencies.e2e.ts, scopes/scope/update-dependencies/update-dependencies.cmd.ts, scopes/scope/update-dependencies/update-dependencies.main.runtime.ts, src/e2e-helper/e2e-scope-helper.ts
to not fetch the remote dependencies objects
=> introduce "--simulation" flag for bit update-dependencies

scopes/generator/generator/generator.main.runtime.ts, scopes/generator/generator/templates.cmd.ts
- run "bit install" on the new workspace during "bit new" command
- fix the output of "bit templates" when executed outside a workspace.
=> run "bit install" on the new workspace during "bit new" command

src/constants.ts, src/consumer/component-ops/add-components/determine-main-file.ts, src/links/link-generator.ts
- Add `bit add` support for Angular components
=> support bit add for Angular components

scopes/compilation/compiler/compiler.main.runtime.ts, scopes/generator/generator/workspace-generator.ts, scopes/workspace/workspace/workspace.ts
In case the template adds components, run the compilation step to make sure the workspace is ready.
=> run compilation during bit-new

scopes/generator/generator/new.cmd.ts, scopes/generator/generator/workspace-generator.ts, scopes/generator/generator/workspace-template.ts, scopes/react/react/templates/react-workspace-learn-bit/files/workspace-config.ts, scopes/react/react/templates/react-workspace/files/workspace-config.ts
to set the `defaultScope` in the workspace.jsonc file.
=> add a new flag "--default-scope" for bit-new

workspace.jsonc
- update hidden dependency base-ui.surfaces.background
=> fix bg color for alert-card

scopes/dependencies/aspect-docs/dependency-resolver/dependency-resolver.mdx, workspace.jsonc, yarn.lock
=> upgrade react and react-dom versions for the main bit aspect

scopes/pkg/pkg/pkg.main.runtime.ts
when pkg doesn't have checksum just ignore the version, and not throw an error, just avoid the version.
=> do not throw error when don't have checksum

scopes/defender/eslint/eslint.linter.ts, scopes/defender/linter/index.ts, scopes/defender/linter/lint.cmd.ts, scopes/defender/linter/linter-context.ts, scopes/defender/linter/linter.main.runtime.ts, scopes/defender/linter/linter.service.ts, scopes/defender/linter/linter.ts, src/toolbox/timer/index.ts
- implement --fix flag for bit lint command
- implement --fix-type flag for bit lint command
- support bit lint --json
- add raw results to lint results to get the original linter results
- expose TimerResponse from time
- resolves #4543
=> Lint fix flag

.bitmap, scopes/defender/formatter/formatter-context.ts, scopes/defender/formatter/formatter.main.runtime.ts, scopes/defender/formatter/formatter.service.ts, scopes/defender/prettier-config-mutator/config-mutator.docs.md, scopes/defender/prettier-config-mutator/config-mutator.ts, scopes/defender/prettier-config-mutator/index.ts, scopes/defender/prettier/index.ts, scopes/defender/prettier/prettier.formatter.ts, scopes/defender/prettier/prettier.main.runtime.ts, scopes/envs/envs/environment.ts, scopes/harmony/node/node.main.runtime.ts, scopes/html/html/html.main.runtime.ts, scopes/react/react-native/react-native.main.runtime.ts, scopes/react/react/react.env.ts, scopes/react/react/react.main.runtime.ts
- new prettier/config-mutator component
- add new API - usePrettier to mutate the prettier config for the react env
- add usePrettier to node, react-native, html envs
- resolves #4557
=> use prettier api

.bitmap, scopes/defender/eslint-config-mutator/config-mutator.docs.md, scopes/defender/eslint-config-mutator/config-mutator.ts, scopes/defender/eslint-config-mutator/index.ts, scopes/defender/eslint/eslint.main.runtime.ts, scopes/defender/eslint/index.ts, scopes/defender/linter/linter.service.ts, scopes/defender/prettier-config-mutator/config-mutator.ts, scopes/envs/envs/environment.ts, scopes/harmony/node/node.main.runtime.ts, scopes/html/html/html.main.runtime.ts, scopes/react/react-native/react-native.main.runtime.ts, scopes/react/react/react.env.ts, scopes/react/react/react.main.runtime.ts
- add new useEslint API
- new eslint config mutator component
- fix prettier mutator to return itself (make it chainable)
- resolves #4382
=> Add new useEslint api to customize eslint config

scopes/react/react/templates/react-workspace/files/workspace-config.ts
=> add react, react-dom and testing library react to template dependencies

scopes/ui-foundation/ui/ui-server.ts
=> remove host from exprss

scopes/react/react/templates/react-workspace/index.ts
- add env component to bit new template
-
-
=> add env to template

scopes/workspace/modules/match-pattern/exceptions/dir-pattern-with-star.ts, scopes/workspace/modules/match-pattern/exceptions/index.ts, scopes/workspace/modules/match-pattern/match-pattern.ts
=> show an error when a folder variant includes *

scopes/react/react/react.templates.ts, scopes/react/react/templates/react-workspace-app/index.ts, scopes/react/react/templates/react-workspace-lib/index.ts
- register app and lib templates
- still experimental so they are hidden
=> register app and lib templates

scopes/compilation/compiler/types.ts, scopes/compilation/compiler/workspace-compiler.ts
- pass the component parameter to the `transpileComponent` method
=> pass component parameter to transpileComponent

scopes/react/react/templates/react-workspace/files/workspace-config.ts, scopes/react/react/templates/react-workspace/index.ts
- fixes issue and adds all files to templates folder so path and namespace are the same
=> add templates namespacing

scopes/generator/generator/new.cmd.ts
=> improve success message for bit new

scopes/scope/ui/scope-icon/scope-icon.module.scss
- Add font-weight in scope icon.
=> add font-weight in scope icon

package.json, scopes/defender/eslint-config-mutator/config-mutator.ts, scopes/defender/eslint/component.json, yarn.lock
- fix setRule and addExtends in eslint-config-mutator
- update eslint types
- upgrade eslint 7.20.0 -> 7.32.0
=> Fix eslint config mutator set rule

scopes/html/html/templates/html-component/files/component.ts, scopes/html/html/templates/html-component/files/composition.ts, scopes/html/html/templates/html-component/files/test.ts
- fix template for basic html component
-
-
=> Html template fix

scopes/generator/generator/generator.docs.mdx, scopes/generator/generator/templates/workspace-generator/files/docs-file.ts, scopes/generator/generator/templates/workspace-generator/files/readme-tpl.ts, scopes/generator/generator/templates/workspace-generator/index.ts
- improve readme with better example
- add aspect docs for workspace generator
=> Workspace generator docs

scopes/generator/generator/new.cmd.ts
Fixes https://github.com/teambit/bit/issues/4695
=> bit-new: fix --standalone flag to be boolean, not string

scopes/generator/generator/workspace-generator.ts
=> bit-new: delete the newly created workspace upon failure

scopes/harmony/express/middlewares/error.ts, scopes/preview/preview/preview.main.runtime.tsx, scopes/preview/preview/preview.route.ts
- revert express error handler to return json
- catch errors and return 500 pages specifically for preview page
=> remove http error from general express to sepcifically preview

scopes/design/ui/tooltip/tippy.module.scss, scopes/design/ui/tooltip/tooltip.module.scss, scopes/design/ui/tooltip/tooltip.tsx
- updated tooltip global styles to use css modules
=> tooltip global styles with css modules

scopes/react/aspect-docs/react-native/react-native.mdx
- Add a link on how to create a RN extension inside the issue.
=> add a link on how to create RN extension in the issue that use an extension.

scripts/docker-teambit-bit/README.md
Fixed a typo in docker spellings
=> fixed a typo in Dockerfile spellings

scopes/html/aspect-docs/html/html.docs.mdx, scopes/html/aspect-docs/html/html.mdx
- fix html env docs so they're compatible with harmony docs site
=> remove header from .mdx file

scopes/ui-foundation/uis/pages/preview-not-found/preview-not-found.tsx, scopes/ui-foundation/uis/pages/static-error/static-error-pages.tsx
- fix "preview not found" message in preview card
before:
after:
=> fix "preview not found" message in preview card

scopes/react/react/templates/common-files/git-ignore.ts, scopes/react/react/templates/react-workspace-app/files/readme-file.ts, scopes/react/react/templates/react-workspace-app/files/workspace-config.ts, scopes/react/react/templates/react-workspace-app/index.ts, scopes/react/react/templates/react-workspace-lib/files/readme-file.ts, scopes/react/react/templates/react-workspace-lib/files/workspace-config.ts, scopes/react/react/templates/react-workspace-lib/index.ts, scopes/react/react/templates/react-workspace/files/readme-file.ts, scopes/react/react/templates/react-workspace/files/workspace-config.ts, scopes/react/react/templates/react-workspace/index.ts
- add targetName
- add dynamic value for env scope
- add better comments for env
- fixes to readme
=> Bit new target name

scopes/react/react/templates/react-workspace/files/workspace-config.ts
Currently, although the react workspace template has comments in the variant section, it is not being saved. This PR fixes it by using the `assign` and `parse` method of comment-json package. 
Asked by @debs-obrien .
=> preserve comments in react templates of workspace.jsonc

e2e/harmony/new.e2e.ts, src/e2e-helper/e2e-command-helper.ts, src/e2e-helper/e2e-scope-helper.ts, src/remotes/exceptions/scope-not-found-or-denied.ts, src/remotes/remote-resolver/remote-resolver.ts, src/scope/objects-fetcher/objects-fetcher.ts
Currently it shows: `scope-name: access denied`. With this PR it shows a more descriptive error with the component in question.
=> improve the error message when a scope not found during import

e2e/commands/export.e2e.1.ts, e2e/commands/import.e2e.1.ts, src/cli/commands/public-cmds/list-cmd.ts, src/cli/templates/list-template.ts
=> improve bit-list table header description

scopes/generator/generator/workspace-generator.ts
so then, the next "bit start" is quick.
=> build UI during "bit new"

e2e/harmony/custom-env.e2e.ts
This test was failing on Windows due to the copy process of the e2e-tests.
=> fix an e2e-test of replacing envs on Windows

scopes/generator/generator/workspace-generator.ts, src/scope/component-ops/tag-model-component.ts, src/scope/models/model-component.ts
Also, validate that "head" prop exists for Harmony components.
=> add "schema" field to model component

scopes/generator/generator/templates.cmd.ts
- changes Example message of bit new and bit create
=> update bit new + create messages

scopes/generator/generator/workspace-generator.ts
it slows down `bit new` dramatically.
=> roll back the change of building UI during bit new

e2e/commands/snap.e2e.2.ts, e2e/harmony/custom-env.e2e.ts, scopes/workspace/workspace/tag-cmd.ts, src/api/consumer/lib/status.ts, src/api/consumer/lib/tag.ts, src/cli/commands/public-cmds/status-cmd.ts, src/consumer/component/components-list.ts, src/e2e-helper/e2e-command-helper.ts, src/scope/lanes/lanes.ts, src/scope/models/model-component.ts
Also, add a new section "snapped components" in `bit status` to display these components.
=> enable tagging components that their head is a snap rather than a tag

scopes/react/eslint-config-bit-react/bit-react-eslint.js, scopes/react/react/eslint/eslintrc.js, scopes/react/react/templates/common-files/types/style.ts, scopes/react/react/typescript/style.d.ts
- move eslint configs from react aspect to eslint-config-bit-react component
- add global types for styles
=> React eslint improvements

workspace.jsonc
=> prop table bump

e2e/harmony/workspace-config.e2e.ts, scopes/workspace/workspace/workspace.ts
Suggesting to edit/remove the component-id from this file.
Asked by @ranm8 .
=> improve ComponentNotFound error when the component was set in the workspace.jsonc file

scopes/defender/eslint/eslint.linter.ts, scopes/defender/linter/lint.cmd.ts, scopes/defender/linter/linter.ts
- exit lint command with status code 1 in case there are errors
- add lint total erros/warning
- resolves #4835
=> exit lint command with status code 1 in case there are errors

scopes/react/react/templates/react-env/files/main.runtime.ts, scopes/react/react/templates/react-env/files/webpack.config.ts, scopes/react/react/templates/react-env/index.ts
- Update Webpack config to use the new API.
=> update webpack transformers in react template to use the new API

scopes/react/react/templates/react-env/files/main.runtime.ts
- remove the old require to the Webpack config.
=> remove unnecessary code in react env template

scopes/explorer/command-bar/ui/autocomplete-input/autocomplete-input.tsx
- fix ts error at `autocomplete-input`
=> ignore ts errors - autocomplete-input

src/cli/commands/public-cmds/snap-cmd.ts
- remove [collection] from post-tag export suggestion
-
-
=> fix message

scopes/dependencies/yarn/yarn.composition.tsx, scopes/webpack/webpack/webpack.composition.tsx
=> add simple composition with logo to yarn and webpack aspects

scopes/harmony/config/config.provider.ts, scopes/harmony/config/workspace-config.ts, src/consumer/component/package-json-file.ts, src/consumer/config/workspace-config.ts, src/consumer/consumer.ts
=> fix "bit init --reset-hard" to remove the legacy "bit" prop in package.json and to re-create the workspace.jsonc file

scopes/compilation/compiler/compiler.main.runtime.ts, scopes/compilation/compiler/templates/compiler/files/aspect-file.ts, scopes/compilation/compiler/templates/compiler/files/compiler-file.ts, scopes/compilation/compiler/templates/compiler/files/index-file.ts, scopes/compilation/compiler/templates/compiler/files/main-runtime-file.ts, scopes/compilation/compiler/templates/compiler/index.ts
=> Add compiler template

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- remove unnecessary items in deps-resolver template
- Also removed from config type
-
=> fix deps-resolver template

scopes/react/bit-react-transformer/bit-react-transformer.ts, scopes/react/bit-react-transformer/index.ts, scopes/react/bit-react-transformer/model.ts, scopes/react/component-highlighter/component-highlighter/hover-highlighter/hover-highlighter.spec.tsx, scopes/react/component-highlighter/component-highlighter/hover-highlighter/hover-highlighter.tsx
- Fix highlighter getting removed when hovering on the highlighter bubble
- add tests! 😄 
- expose bit metadata fields
=> fix highlighter bubble to be reachable + tests

scopes/component/component/index.ts
=> export tag and snap props

scopes/workspace/workspace/install.cmd.tsx
- fix bit install help docs, for `type` options
-
-
=> fix bit install help menu for type

scopes/react/eslint-config-bit-react/component.json, scopes/react/react-native/component.json, scopes/react/react/component.json, scopes/ui-foundation/ui/component.json, workspace.jsonc
some props, such as `keywords` and `license` were missing from some aspects due to override by component.json file. fixed to use the data from the workspace.jsonc.
=> add missing package.json props to some aspects

e2e/harmony/dependencies-cmd.e2e.ts, src/api/consumer/lib/dependencies.ts, src/e2e-helper/e2e-command-helper.ts, src/scope/exceptions/id-not-found-in-graph.ts, src/scope/graph/scope-graph.ts
(bug reported by @itaymendel ).
=> fix(bit-dependencies): allow running bit dependencies command on new components

scopes/mdx/ui/mdx-layout/md-example.md, scopes/mdx/ui/mdx-layout/mdx-layout.css
- Change h3 to h5 in mdx layout css.
- Add `display flex` to align the icon with the text.
=> fix notes css in mdx layout

e2e/harmony/uninstall-cmd.e2e.ts, scopes/workspace/workspace/uninstall.cmd.tsx, scopes/workspace/workspace/workspace.provider.ts, scopes/workspace/workspace/workspace.ts, src/e2e-helper/e2e-command-helper.ts
=> feat: add `bit uninstall` command

scopes/dependencies/pnpm/lynx.ts
- pnpm should use the right global content-addressable store. So if users use pnpm CLI on the same machine, bit CLI and pnpm CLI will use the same content-addressable store for packages.
=> fix: the right global content-addressable store should be used by pnpm

scopes/dependencies/pnpm/lynx.ts
=> refactor: remove code comments from the pnpm aspect's source code

scopes/workspace/workspace/workspace.ts
=> fix(create): convert scope entered by "bit create --scope" to full scope-name including owner if needed

scopes/workspace/workspace/workspace.ts
=> fix duplicate identifier error caused by #5162

scopes/component/component/component.ui.runtime.tsx, scopes/component/component/index.ts, scopes/dependencies/pnpm/index.ts, scopes/dependencies/pnpm/pnpm.ui.runtime.tsx, scopes/dependencies/yarn/index.ts, scopes/dependencies/yarn/yarn.ui.runtime.tsx, scopes/pkg/pkg/index.ts, scopes/pkg/pkg/pkg.ui.runtime.tsx
=> refactor: register the consume methods in the appropriate aspects

.circleci/config.yml, CONTRIBUTING.md, e2e/npm-ci-registry.ts, workspace.jsonc, yarn.lock
=> test: access the registry's API directly to create a user for e2e tests

e2e/harmony/install-missing-peer-dependencies.e2e.ts, scopes/workspace/workspace/workspace.ts
=> Install new packages and missing peers at the same time

scopes/react/ui/docs-app/component-overview/component-overview.tsx
- fix incorrect window check breaking SSR (made by #5120)
=> fix incorrect window check

scopes/pipelines/builder/templates/build-task/files/task-file.ts
=> fix build task template typos

src/cli/commands/public-cmds/status-cmd.ts
- fix `bit status` command to correctly display the export msg when on a lane
=> update stagedDesc to show the correct msg when on a lane

.bitmap
It will be replaced with design/inputs.menu-item
=> deprecate surfaces menu item

src/api/consumer/lib/global-config.ts
see https://github.com/teambit/bit/pull/4491 for more details about this feature.
Currently, it only replacing the first dot.
=> fix(config): fix config with multiple dots to be able to set them with env variables

scopes/scope/scope/scope.ui.runtime.tsx, scopes/scope/scope/ui/scope.tsx
add scope ui context as slot to, to support add multiple  contexts
=> add scope context as slot

scripts/docker-teambit-bit/Dockerfile-symphony
=> symphony build

scopes/react/bit-react-transformer/bit-react-transformer.ts, scopes/react/dom-to-react/dom-to-fiber.ts, scopes/react/dom-to-react/dom-to-react.ts, scopes/react/dom-to-react/fiber-node.ts, scopes/react/dom-to-react/index.ts
resolves #5190 
- add support for forwardRef components to the component highlighter
=> fix highlighter for forwardRef components

scopes/explorer/ui/base-component-card/base-component-card.composition.tsx, scopes/explorer/ui/base-component-card/base-component-card.tsx, scopes/explorer/ui/base-component-card/details/details.module.scss, scopes/explorer/ui/base-component-card/details/details.tsx
=> Add isVerified option in base component details component

scopes/compilation/bundler/bundler.ts, scopes/compilation/bundler/index.ts, scopes/component/component-sizer/component-sizer.graphql.ts, scopes/component/component-sizer/component-sizer.main.runtime.ts, scopes/preview/preview/index.ts, scopes/preview/preview/preview.main.runtime.tsx, scopes/preview/preview/strategies/component-strategy.ts, scopes/webpack/webpack/webpack.bundler.ts
- copy images to components
- change component size structure
=> copy images to components

scopes/docs/docs/overview/overview.tsx
=> scroll fix

scopes/ui-foundation/uis/side-bar/component-tree/component-tree.tsx
- fixed active component collision in the component tree.
-
-
=> Component tree fix

scopes/react/react/jest/jest.config.js
=> css testing improvements

scopes/component/graph/ui/dependencies-graph/dependencies-graph.tsx
=> add ReactFlowProvider

scopes/dependencies/dependency-resolver/apply-updates.spec.ts, scopes/dependencies/dependency-resolver/apply-updates.ts, scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts, scopes/dependencies/dependency-resolver/get-all-policy-pkgs.spec.ts, scopes/dependencies/dependency-resolver/get-all-policy-pkgs.ts, scopes/dependencies/dependency-resolver/policy/workspace-policy/workspace-policy.ts, scopes/workspace/workspace/workspace.ts
=> fix: update should work when variants have object versions

pnpm-lock.yaml, scopes/workspace/workspace/workspace.ts
=> fix: --add-missing-peers shouldn't fail when there are no missing peers

workspace.jsonc
=> moved @testing-library/jest-dom back to deps

scopes/webpack/webpack/webpack.bundler.ts
- fix for webpack 4 in Angular v8 to 11: https://github.com/teambit/bit-angular/runs/5126716919?check_suite_focus=true
=> support missing assets for compressed size

scopes/mdx/mdx/mdx.main.runtime.ts
- expose mdx env from mdx aspect
=> expose mdx env

src/scope/models/model-component.ts, src/scope/scope.ts
- update `loadComponentLogs` to allow fetching logs from a specific component version
=> allow fetching component logs from a version

scopes/defender/ui/test-loader/test-loader.tsx, scopes/pkg/pkg/pkg.ui.runtime.tsx, scopes/ui-foundation/use-box/dropdown/dropdown.composition.tsx, scopes/ui-foundation/use-box/menu/menu.compositions.tsx, scopes/ui-foundation/use-box/menu/menu.docs.mdx
- replace `http` images with `https`
- verified each image url
=> fix: insecure assets

scopes/workspace/workspace/tag-cmd.ts, src/scope/component-ops/message-per-component.ts
Also, delete the temporary file with the messages per id after reading it.
=> fix: mark "tag --editor" as experimental. 

scopes/component/component/component-factory.ts, scopes/scope/scope/scope.main.runtime.ts, scopes/workspace/workspace/workspace.provider.ts, scopes/workspace/workspace/workspace.ts
by passing the component-id that asked for the aspects.
=> improvement: facilitate debugging loadAspect method 

scopes/workspace/workspace/envs-subcommands/envs-replace.cmd.ts, scopes/workspace/workspace/workspace.provider.ts, scopes/workspace/workspace/workspace.ts
to replace the environment for all components that use the old env with a new env.
=> feat: introduce "bit env replace <old-env> <new-env>"

scripts/docker-teambit-bit/README.md
- Fixed typos on scripts/docker-teambit-bit
=> Fixed typos in /scripts/docker-teambit-bit

scopes/design/ui/surfaces/menu/link-item/item.compositions.tsx
- removing unrelated `@teambit/ui.routing.provider`, so it won't be available in the workspace
=> fix - remove deprecated @teambit/ui.routing.provider

scopes/component/component/ui/use-component-query.ts
=> fix error on component 

e2e/harmony/component-config.e2e.ts, scopes/workspace/workspace/eject-conf.cmd.ts, scopes/workspace/workspace/workspace.ts, src/e2e-helper/e2e-component-json-helper.ts
=> improvement: enable running "bit eject-conf" on multiple components

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts, scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts, scopes/scope/scope/scope.main.runtime.ts, scopes/workspace/workspace/workspace.ts
- try to load envs before load scope aspects
- load scope aspects before workspace aspects
- fixes side affects to aspects manifests caused by other aspects in the same loading iteration
- default to default dist folder when trying to require aspect runtime file if the env wasn't loaded correctly
=> many fixes for aspect loading process

scopes/react/react/webpack/webpack.config.base.ts
- load cjs files are regular js instead of url assets
resolves #5455
=> fix loading cjs files

scopes/component/component-sizer/component-sizer.ui.runtime.tsx, scopes/docs/docs/overview/overview.tsx
- fixed scroll issue in component page iframe
- commented out size badge until we are ready do deploy symphony as well
=> Fix scroll issue

scopes/compilation/bundler/dev-server.service.tsx, scopes/ui-foundation/ui/webpack/webpack.dev.config.ts, scopes/webpack/webpack/config/webpack.config.ts, scopes/webpack/webpack/webpack.bundler.ts
- replace all hard-coded path separators with path's `sep` value
- fixes issue with webpack outputs on Windows machines
- fixes issue #5482
=> make public paths os-agnostic

scopes/harmony/aspect/aspect.cmd.ts
"bit update" -> "bit aspect update"
=> fix: fix bit aspect-update command description

scopes/dependencies/pnpm/lynx.ts
=> fix: install should remove projects that don't exist from the lockfile

scopes/component/ui/version-dropdown/version-dropdown.module.scss, scopes/component/ui/version-dropdown/version-dropdown.tsx, scopes/component/ui/version-dropdown/version-info/version-info.tsx, scopes/ui-foundation/tree/drawer/drawer.module.scss
- Update user avatar in dropdown to show the author name on hover
- Hide tabs if there is only tag or snap or lane
- Add a separator between the components and lanes drawer
=> Lane UI and Version Dropdown Style Fixes

e2e/harmony/pkg-manager-config.e2e.ts, pnpm-lock.yaml, scopes/component/isolator/isolator.main.runtime.ts, scopes/dependencies/dependency-resolver/dependency-installer.ts, scopes/dependencies/dependency-resolver/package-manager.ts, scopes/dependencies/pnpm/pnpm.package-manager.ts, scopes/dependencies/pnpm/read-config.ts, scopes/dependencies/yarn/yarn.package-manager.ts, scopes/scope/scope/scope.main.runtime.ts, scopes/workspace/workspace/workspace.ts, src/e2e-helper/e2e-capsules-helper.ts, src/e2e-helper/e2e-helper.ts, src/e2e-helper/e2e-scope-helper.ts, workspace.jsonc
=> fix: the configuration from `.yarnrc.yml` should be applied when installing in capsules

scopes/preview/preview/strategies/component-strategy.ts, scopes/react/react/webpack/webpack.config.base.ts
- put webpack assets in static dir
- keep preview webpack assets internal paths
=> fix assets urls on remote scope

scopes/component/component/ui/use-component-query.ts
=> remove onLane property from log query

scopes/pipelines/builder/build.cmd.ts
=> fix(build): pass package manager config location to bit build

.bitmap, scopes/cloud/cloud/cloud.aspect.ts, scopes/cloud/cloud/cloud.main.runtime.ts, scopes/cloud/cloud/index.ts, scopes/community/community/community.aspect.ts, scopes/community/community/community.main.runtime.ts, scopes/community/community/index.ts, scopes/harmony/bit/manifests.ts, src/constants.ts, workspace.jsonc
- new core aspect called `community` to provide community-related stuff like the community site URLs
- new core aspect called `cloud` to provide default cloud-related stuff like the bit.cloud URL, and the registry URL
=> Community and cloud aspects

scopes/scope/scope/ui/components-drawer/components-drawer.module.scss, scopes/scope/scope/ui/components-drawer/components.drawer.tsx, scopes/ui-foundation/tree/drawer/drawer.module.scss, scopes/workspace/workspace/ui/workspace-components-drawer/workspace-components-drawer.module.scss, scopes/workspace/workspace/ui/workspace-components-drawer/workspace-components.drawer.tsx
- Improve CSS of the filter widget.
- Add hover and active state to the collapse widget.
- Use SVG images instead of icomoon icons for both widgets and deprecated filter.
=> Update filter and widgets

scopes/component/isolator/isolator.main.runtime.ts, scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- add capsulesOverrides key for dependency resolver workspace config
- support capsulesOverrides and overrides for dependencies installations in capsules
=> Capsules deps overrides

scopes/ui-foundation/use-box/menu/import.tsx, scopes/ui-foundation/use-box/menu/menu.module.scss
=> Add bit fork to use dropdown

src/cli/default-error-handler.ts
=> fix: improve the error message when "bit login" is unable to connect to the default port

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts, scopes/dependencies/dependency-resolver/package-manager.ts, scopes/dependencies/pnpm/lynx.ts, scopes/dependencies/pnpm/pnpm.package-manager.ts, scopes/workspace/workspace/workspace.ts
- allow to choose how packages are linked into node_modules by setting [`package-import-method`](https://pnpm.io/npmrc#package-import-method) in `.npmrc`.
=> feat(pnpm): allow to set package-import-method

scopes/ui-foundation/collapser-button/collapser-button.module.scss
- use token for toggler background color, so it will work in dark mode
=> Fix toggler color

scopes/component/component-drawer/component-drawer.module.scss, scopes/component/component-drawer/component-drawer.tsx, scopes/ui-foundation/tree/drawer/drawer.module.scss, scopes/workspace/workspace/workspace.ui.drawer.tsx
=> Fix tree node

scopes/react/component-highlighter/element-highlighter/element-highlighter.compositions.tsx, scopes/react/component-highlighter/hover-highlighter/bubble-to-component.spec.tsx, scopes/react/component-highlighter/hover-highlighter/bubble-to-component.tsx, scopes/react/component-highlighter/hover-highlighter/hover-highlighter.compositions.tsx, scopes/react/component-highlighter/hover-highlighter/use-hover-highlighter.tsx, scopes/react/component-highlighter/mock-component.tsx
- highlighter - bubble to parents recursively, when they are the same component
=> Highlighter parent bubbler

scopes/react/react-native/jest/jest.config.js
- see https://bit-dev-community.slack.com/archives/CCDHG0TPY/p1648724203001329 
- adding all react-native-* packages to jest's transformIgnorePattern as they will all likely need to be transformed in a react-native project
-
=> need to transform all react-native-* packages (not just button)

scopes/preview/preview/env-preview-template.task.ts
- fix max call stack error during "GenenrateEnvTemplate" task
=> remove clone deep of bundler context in env-preview-template task

scopes/react/react/templates/workspace-common/files/launch-json.ts, scopes/react/react/templates/workspace-common/generate-files.ts
=> generate launch.json for vscode debugging for workspace templates

scopes/ui-foundation/ui/start.cmd.tsx, scopes/ui-foundation/ui/ui.main.runtime.ts
Fixes https://github.com/teambit/bit/issues/5012
=> improvement: improve the error message when running bit-start outside workspace/scope

e2e/harmony/refactor.e2e.ts
Should have been part of https://github.com/teambit/bit/pull/5667.
=> test: add refactoring e2e tests

pnpm-lock.yaml, scopes/react/react/apps/web/plugins/prerender.ts, scopes/react/react/apps/web/react-app-options.ts, scopes/react/react/apps/web/react.app-type.ts, scopes/react/react/apps/web/react.application.ts
-add a config option to the react app that allows passing proxy config.
resolved #5661
=> add proxy support to prerender

scopes/explorer/command-bar/command-bar.ui.runtime.tsx, scopes/explorer/command-bar/index.ts, scopes/explorer/command-bar/ui/command-bar-context/command-bar-context.tsx, scopes/explorer/command-bar/ui/command-bar-context/index.ts
- removed command bar context (unused, and not needed)
=> Remove command ctx

scopes/component/component-filters/envs-filter.module.scss, scopes/component/component-filters/envs-filter.tsx
=> fix env filter grouping

workspace.jsonc
- fix command bar in dark mode
- fix keybinding in safari, when closing the command bar with the Esc key
=> bump command bar

pnpm-lock.yaml, scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.spec.ts, scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.ts, workspace.jsonc
=> replace semver-intersect with semver-range-intersect

scopes/component/deprecation/index.ts
- fix webpack error in deprecation aspect
=> fix webpack error in deprecation aspect

scopes/dependencies/yarn/yarn.ui.runtime.tsx, scopes/pkg/pkg/pkg.ui.runtime.tsx
- fixed copy text to set registry from `node.bit.dev` to `node.bit.cloud`
=> fixed registry text. bit.dev -> bit.cloud

scopes/component/snapping/snap-cmd.ts, scopes/component/snapping/snapping.main.runtime.ts, scopes/component/snapping/tag-cmd.ts, scopes/harmony/logger/logger.ts
In about two weeks, `--message` will be mandatory. This is a preparation to not break users.
=> warn about not using "--message" in bit tag/snap

scopes/component/component/ui/use-component-query.ts
=> fetch compositions for lane overview preview

scopes/react/react/react.templates.ts, scopes/react/react/templates/react-workspace-analytics/index.ts, scopes/react/react/templates/react-workspace-data-fetching/index.ts, scopes/react/react/templates/react-workspace-wiki/index.ts
- add templates for analytics, data fetching and wiki
- note that wiki is set to hidden as there is an error with the router. Adding it here as hidden will make it easier for Oded or Uri to test out and when fixed we can remove the hidden flag.
=> Workspace templates

scopes/react/react/templates/react-workspace-wiki/index.ts
remove version numbers as new version has been released. Footer needs to be updated to get new Env but Ella is working on this and will be done shortly.
Hidden flag has been removed.
Co-Authored-By: Oded Reuveny <15064762+odedre@users.noreply.github.com>
=> fix: wiki template

src/scope/models/lane.ts
This should help debugging lanes that got too many components for no reason.
=> log when a new component is added to a lane

scopes/lanes/lanes/merge-lanes.ts
- During lane merge, do not merge lane readme from main lane
=> fix(lanes): handle merging main lane readme

.circleci/config.yml
=> circleci - download esbuild arm64 on a separate job

scopes/lanes/ui/gallery/lane-gallery.tsx, scopes/scope/scope/ui/scope-overview/scope-overview.tsx
=> pass lane comp url to scope card

src/consumer/bit-map/component-map.ts
=> fix duplicate lane entry on bitmap while snapping

scopes/harmony/graphql/create-remote-schemas/create-remote-schemas.ts
pass the cookie header from the remote schema to the main gql server, 
we need that to support set cookie from different services
=> add set cookie on Remote Schema

scopes/component/ui/version-dropdown/version-dropdown.tsx
=> fix lane components cannot be viewed on bit.cloud

scopes/component/component-filters/envs-filter.tsx, scopes/ui-foundation/uis/side-bar/component-tree/component-view/component-view.module.scss, scopes/ui-foundation/uis/side-bar/component-tree/component-view/component-view.tsx
- make env tool tip navigable in components drawer
- route to the latest env version from env filter dropdown
=> fix env url in env filter + make env tool tip navigable in comp tree

scopes/scope/sign/sign.main.runtime.ts
export sign component to central hub
=> export bit sign central hub

scopes/workspace/workspace/scope-subcommands/scope-set.cmd.ts, scopes/workspace/workspace/workspace.provider.ts, scopes/workspace/workspace/workspace.ts, src/hooks/utils/enrich-context-from-global.ts
to set the default-scope for specific component(s).
=> feat: implement bit scope set command

pnpm-lock.yaml, workspace.jsonc
- updated timeAgo version which locks the package javascript-time-ago version
- updated lock file
=> locked time ago version

scopes/harmony/application/app-build-result.ts, scopes/harmony/application/build.task.ts, scopes/react/react/apps/web/compute-results.ts, scopes/react/react/apps/web/react.application.ts
- show errors during app build process
-
-
=> show app build errors

pnpm-lock.yaml, workspace.jsonc
=> fix: update @pnpm/core

scopes/react/react-native/templates/react-native-component/index.ts, scopes/react/react-native/templates/react-native-env/index.ts
Set correct env automatically in env and component templates.
=> react native templates - set correct env automatically

scopes/preview/preview/strategies/component-strategy.ts
=> handle cases where the output asset name has hash extension - `?hash?

scopes/webpack/config-mutator/config-mutator.ts
- enables adding a oneOf rule 
-
-
=> add config mutator for adding to oneOf rule

workspace.jsonc
- add missing peer dep of react-router-dom to @teambit/bit
=> fix react-router dep

scopes/react/react/typescript/tsconfig.json
=> add "experimentalDecorators": true  to react ts config

scopes/react/react/react.templates.ts, scopes/react/react/templates/react-workspace-blog/index.ts
-Added a React blog Workspace template
Resolved #5844
=> added a react blog template

scopes/react/react/webpack/webpack.config.base.prod.ts
- remove workbox plugin. Creates difficult-to-debug errors and doesnt add enough benefit
- In coordination with @GiladShoham 
-
=> remove workbox plugin

scopes/scope/scope/scope.main.runtime.ts
=> fix: pass configuration location to capsules isolator

scopes/component/component/ui/menu/mobile-menu-nav.tsx
- closed #5891 
- fixed missing text in compact mobile component menu
=> fix menu items for path '.'

scopes/react/react/typescript/tsconfig.build.json, scopes/react/react/typescript/tsconfig.json
- restore package.json exclude from tsconfig (got removed in a previous merge/fix)
-
-
=> restore package.json exclude from tsconfig

.circleci/config.yml, scripts/docker-teambit-bit/Dockerfile-bit-server
- move docker build to its own circle ci command
-
-
=> add docker build for node 16 to circle ci

scopes/workspace/workspace/watch/watch.cmd.tsx, scopes/workspace/workspace/watch/watcher.ts
by implementing debounce mechanism.
Some actions trigger multiple files changes at (almost) the same time. e.g. "git pull".
This causes some performance and instability issues. a debouncing mechanism was implemented to help with this.
When a file is changed, it waits 100ms before executing anything, if in the meantime another file of the same component has changed, it'll be added to the same execution of the first file and won't be triggered as a new execution.
=> improvement(watch): improve stability and performance of the watch process

scripts/docker-teambit-bit/Dockerfile-symphony
=> Update Dockerfile symphony

e2e/harmony/lanes/bit-import-on-lanes.e2e.ts, scopes/scope/importer/import.cmd.ts, src/api/consumer/lib/import.ts, src/cli/commands/public-cmds/import-cmd.ts, src/consumer/component-ops/import-components.ts
also, change the `--skip-lane` flag to `--save-in-lane`
=> breaking: change the default import ids on lane to save on main

src/consumer/component-ops/import-components.ts
See https://github.com/teambit/bit/pull/5931 for all details. 
In that PR the optimization was disabled on the client side in order for the server to get the changes first.
Here, it's enabled. (the code has been deployed successfully).
=> enable import on lane optimization of fetching the delta

scopes/semantics/entities/semantic-schema/api-schema.ts, scopes/semantics/entities/semantic-schema/class-transformers/schema-obj-to-class.ts, scopes/semantics/entities/semantic-schema/schemas/index.ts, scopes/semantics/entities/semantic-schema/schemas/unknown-schema.ts, scopes/semantics/entities/semantic-schema/schemas/variable-like.ts, scopes/semantics/schema/mock/button-old-schema.json, scopes/semantics/schema/mock/button-schemas.json, scopes/semantics/schema/schema.spec.ts, scopes/typescript/typescript/transformers/binding-element.ts, scopes/typescript/typescript/transformers/utils/class-element-to-schema.ts, scopes/typescript/typescript/transformers/utils/type-element-to-schema.ts, scopes/typescript/typescript/transformers/variable-declaration.ts
also, add basic backward and forward compatibility for Schema classes.
=> schema: change VariableSchema to VariableLikeSchema

scopes/component/snapping/tag-cmd.ts, scopes/harmony/cli/cli-parser.ts, scopes/harmony/cli/generate-doc-md.ts, scopes/harmony/cli/yargs-adapter.ts, scopes/workspace/workspace/envs-subcommands/envs-replace.cmd.ts, src/cli/command.ts
With this change, it's possible for commands to add examples and they'll be shown in the command help.
=> improvement(cli): support adding examples to commands

pnpm-lock.yaml, scopes/ui-foundation/ui/component.json
=> upgrade sass-loader for ui aspect to 12.1.0 for node16 support

scopes/react/react/templates/react-app/index.ts
- react-app template -> add teambit.harmony/aspect as default env for 
-
-
=> add aspect env as default for react-app

scopes/react/react-native/component.json, scopes/react/react-native/webpack/webpack-transformers.ts
=> add "@babel/plugin-proposal-class-properties": "7.12.13" to react-native webpack

.circleci/config.yml
The latest is now fixed so we can change it back.
=> ci: change Circle config to install the latest of bvm

scopes/component/component/component.graphql.ts
return array of string on when using parents
=> fix parents gql

scopes/compilation/compiler/compiler.cmd.ts, scopes/component/component/show/show.cmd.ts, scopes/component/forking/fork.cmd.ts, scopes/component/renaming/scope-rename.cmd.ts, scopes/component/snapping/snap-cmd.ts, scopes/component/snapping/tag-cmd.ts, scopes/component/status/status-cmd.ts, scopes/defender/tester/test.cmd.tsx, scopes/envs/envs/envs.cmd.tsx, scopes/generator/generator/create.cmd.ts, scopes/generator/generator/new.cmd.ts, scopes/harmony/application/app.cmd.ts, scopes/harmony/application/run.cmd.tsx, scopes/harmony/config/use.cmd.ts, scopes/lanes/lanes/lane.cmd.ts, scopes/scope/export/export-cmd.ts, scopes/scope/importer/import.cmd.ts, scopes/scope/scope/scope-cmd.ts, scopes/ui-foundation/ui/start.cmd.tsx, scopes/workspace/workspace/envs-subcommands/envs-replace.cmd.ts, scopes/workspace/workspace/envs-subcommands/envs-set.cmd.ts, scopes/workspace/workspace/envs-subcommands/envs-unset.cmd.ts, scopes/workspace/workspace/install.cmd.tsx, scopes/workspace/workspace/scope-subcommands/scope-set.cmd.ts
add argument descriptions/minor doc fixes, to the following commands:
- show
- create
- envs
- fork
- import
- export
- tag
- snap
- status
- new
- start
- scope
- lane
- test
- compile
- install
- use
- app
=> Command descriptions

scopes/workspace/workspace/pick-outdated-pkgs.ts
=> fix(update): print out the selected choices correctly

package.json
=> add missing @teambit/component-version to package.json

scopes/harmony/node/node.application.ts, scopes/harmony/node/node.main.runtime.ts, scopes/harmony/node/templates/express-app/files/app-root.ts, scopes/harmony/node/templates/express-app/files/composition.ts, scopes/harmony/node/templates/express-app/files/doc.ts, scopes/harmony/node/templates/express-app/files/get-port.ts, scopes/harmony/node/templates/express-app/files/index.ts, scopes/harmony/node/templates/express-app/files/mock-route.ts, scopes/harmony/node/templates/express-app/files/node-app.ts, scopes/harmony/node/templates/express-app/files/route.ts, scopes/harmony/node/templates/express-app/files/test.ts, scopes/harmony/node/templates/express-app/index.ts, scopes/harmony/node/templates/express-route/files/composition.ts, scopes/harmony/node/templates/express-route/files/doc.ts, scopes/harmony/node/templates/express-route/files/index.ts, scopes/harmony/node/templates/express-route/files/main.ts, scopes/harmony/node/templates/express-route/files/test.ts, scopes/harmony/node/templates/express-route/index.ts
- add a new express app template
- add a new express route template
- return port from a node application
=> express templates

workspace.jsonc
- hard code navigation/link version to be 2.0.27
(bypass some indirect dependencies forcing version 1.23.0)
=> fix navigation/link version

scopes/react/react/templates/react-env/files/main.runtime.ts
add required type
- fix react-env template code (didnt trigger issues because it's commented out...)
-
-
=> move commented code to the right place in file

workspace.jsonc
=> add bvm configuration to @teambit/bit to set runtime node version

package.json, pnpm-lock.yaml, src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts, src/consumer/config/abstract-config.ts, src/scope/component-ops/tag-model-component.ts
=> get rid of ramda-adjunct dependency

pnpm-lock.yaml, scopes/dependencies/pnpm/lynx.ts, workspace.jsonc
- We downgraded the pnpm reporter because it was printing warnings about `@teambit/legacy`: https://github.com/teambit/bit/pull/5219.
-
-
=> fix: update pnpm reporter

e2e/harmony/checkout-harmony.e2e.ts, src/consumer/versions-ops/checkout-version.ts
also,  do not show it as an error.
=> improvement: improve the text indicating when checking out latest of a new component 

scopes/docs/docs/docs.preview-definition.ts, scopes/preview/preview/generate-link.ts
- handle workspace components that are missing some of their previews (docs/compositions)
=> handle components with missing previews

scopes/react/react/apps/web/react.application.ts
- when running app-types configured to be consumed in real-time, we need a cors header to enable local consumption when locally deploying with `bit run`
- Won't have any effect for standalone app components
-
=> add cors headers (for umd, single-spa etc)

.circleci/config.yml
ref https://github.com/teambit/bvm/issues/31
-
-
-
=> feat: change filesystem structure for bit CLI artifacts stored in GCP

.circleci/config.yml, scripts/update-bit-gcp-index.js
=> Upload index json

scripts/update-bit-gcp-index.js
=> fix: download the bit CLI index.json file from the right location

.circleci/config.yml
=>  do not download chromium when installing puppeteer

scopes/component/deprecation/deprecate-cmd.ts, scopes/component/renaming/scope-rename.cmd.ts, scopes/lanes/lanes/lane.cmd.ts, scopes/scope/importer/import.cmd.ts, src/cli/commands/public-cmds/checkout-cmd.ts, src/cli/commands/public-cmds/dependencies-cmd.ts, src/cli/commands/public-cmds/dependents-cmd.ts
- bit scope rename: update ‘—factor’ description
- bit lane create: add missing ‘lane-name’ description
- bit import: update ‘dependents’ option description
- bit deprecate: add missing description
- bit dependencies: add missing description. fix arg names.
- bit dependents: add missing description. fix arg names.
=> Command descriptions part 3

scopes/harmony/diagnostic/diagnostic.graphql.ts, scopes/harmony/diagnostic/diagnostic.main.runtime.ts
- Include diagnostics tool in gql
=> show diagnostics in gql

scopes/lanes/lanes/switch-lanes.ts, scopes/lanes/lanes/switch.cmd.ts
when components were not changed legitimately
=> improvement(bit-switch): avoid showing red messages 

e2e/performance/many-components.performance.spec.ts, package.json
=> ci: run performance e2e tests

.bitmap, e2e/harmony/lanes/lanes.e2e.ts, e2e/harmony/lanes/switch-lanes.e2e.ts, scopes/component/status/status-cmd.ts, src/e2e-helper/e2e-command-helper.ts
instead, show the number of snaps.
=> improvement(bit-status): avoid showing the snap hashes in bit-status

e2e/harmony/binary-files.e2e.ts, e2e/harmony/checkout-harmony.e2e.ts, e2e/harmony/lanes/lanes.e2e.ts, e2e/harmony/lanes/merge-lanes.e2e.ts, e2e/harmony/snap.e2e.2.ts, src/api/consumer/lib/checkout.ts, src/cli/commands/public-cmds/checkout-cmd.ts, src/constants.ts, src/e2e-helper/e2e-command-helper.ts
"latest" is more appropriate in Semver context. Versions can be snaps or tag so "head" is more accurate.
=> change "bit checkout latest" to "bit checkout head"

scopes/explorer/command-bar/command-bar.ui.runtime.tsx, scopes/explorer/command-bar/searchers/search-provider.ts, workspace.jsonc
- update command bar to v2.0.2
- allow searchers to return promise
- use new paired-hook pattern
=> async command bar

scopes/mdx/modules/compiler/mdx-compiler.ts
Fixes https://github.com/teambit/bit/issues/6152.
=> improvement(bit-status): improve the error coming from yaml.parse

e2e/commands/init.e2e.1.ts, src/consumer/bit-map/bit-map.ts, src/consumer/consumer.ts
Back it up to the local scope inside `bitmap-history` dir.
=> feat: backup .bitmap file before writing to it

scopes/component/merging/merge-cmd.ts, scopes/component/merging/merging.main.runtime.ts, src/consumer/versions-ops/merge-version/index.ts, src/consumer/versions-ops/merge-version/merge-version.ts
Also, show a summary with all conflicts, so it'll be easier to find them in one place.
=> fix(bit-lane-merge): do not snap-merge when some of the components have conflicts

e2e/harmony/lanes/merge-lanes.e2e.ts, scopes/lanes/lanes/lane.cmd.ts
=> breaking(bit-lane-merge): rename "--existing" flag to "--workspace"

scopes/react/react/react.main.runtime.ts, scopes/ui-foundation/ui/create-root.ts, scopes/ui-foundation/ui/ssr-middleware/ssr-middleware.ts
- use default export for bit ui rendering
=> Default render

package.json
on my local it fixes some issues running `npm run build`.
=> chore: upgrade babel-plugin-ramda to the latest

scopes/envs/envs/environments.main.runtime.ts
=> fix getEnvAspectDef

scopes/harmony/application/index.ts
- expose application artifact dirname from application aspect
-
-
=> export app artifacts dirname

.circleci/config.yml
=> remove bit link from setup harmony circle job

scopes/webpack/webpack/transformers/transformers.ts
=> skip unresolved peer dependencies when computing the webpack aliases

scopes/defender/jest/jest.tester.ts
=> rollback auto setting the module name mapper for jest

e2e/harmony/dependencies-cmd.e2e.ts, scopes/dependencies/dependencies/dependencies-cmd.ts, scopes/dependencies/dependencies/dependencies.main.runtime.ts, scopes/harmony/aspect/aspect.cmd.ts, scopes/harmony/aspect/aspect.main.runtime.ts, scopes/workspace/workspace/bit-map.ts, scopes/workspace/workspace/component-config-file/component-config-file.ts, scopes/workspace/workspace/workspace.ts, src/e2e-helper/e2e-command-helper.ts
This command makes it easy to set a package dependency to a component on multiple components (by a pattern).
=> feat(bit-deps): introduce a new sub-command: "bit dependencies set"

scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.ts, scopes/dependencies/dependency-resolver/manifest/update-dependency-version.spec.ts, scopes/dependencies/dependency-resolver/manifest/update-dependency-version.ts, scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts, scopes/dependencies/dependency-resolver/policy/variant-policy/variant-policy.ts, scopes/dependencies/dependency-resolver/policy/workspace-policy/workspace-policy.ts
=> better support for snaps installation

scripts/update-bit-gcp-index.js
=> fix: add time to the release date

scopes/component/component/index.ts, scopes/component/component/show/index.ts
=> expose ShowJSONRow type from component aspect

.circleci/config.yml
=> ci: fix job on Windows

e2e/harmony/dependencies-cmd.e2e.ts, scopes/dependencies/dependencies/dependencies.main.runtime.ts
currently it throws an error when trying to set a scoped package.
=> fix(bit-deps-set): support scoped packages

e2e/harmony/lanes/merge-lanes.e2e.ts, scopes/lanes/lanes/merge-lanes.ts
also, fix the algorithm to search for the correct version.
=> improve the error when a dependency was not included in the lane merge

scopes/scope/scope/ui/scope-overview/scope-overview.tsx, scopes/workspace/workspace/ui/workspace/workspace-overview/workspace-overview.tsx
remove deprecated components from component card galleries
=> Filter deprecated components

scopes/dependencies/dependencies/dependencies-cmd.ts, scopes/dependencies/dependencies/dependencies.main.runtime.ts
resolve to the latest version if packages were entered without version or with `@latest` suffix.
=> improvement(bit-deps-set): support adding packages without version

scopes/lanes/lanes/lanes.ui.runtime.tsx
=> Lanes refactor

scopes/compilation/bundler/dev-server.service.tsx
=> do not crash if there is no envAspectDef during bit start

e2e/commands/add.e2e.1.ts, src/consumer/component-ops/add-components/add-components.ts
=> fix(bit-add): show the ignored files when a directory is empty

scopes/react/react/apps/web/react.app-type.ts, scopes/react/react/apps/web/react.application.ts, scopes/react/react/apps/web/ssr/app/runner, scopes/react/react/react.main.runtime.ts
- add runner to ssr app 
- fix build ssr app.
=> build ssr on react app 

scopes/component/ui/pipelines/artifacts-panel/artifacts-panel.tsx
- Fix rendering nested artifacts
=> Component Pipeline: UI: Fix rendering nested artifacts

scopes/component/snapping/index.ts, scopes/component/snapping/snapping.main.runtime.ts, scopes/component/snapping/tag-model-component.ts, scopes/scope/sign/sign.main.runtime.ts, scopes/scope/update-dependencies/update-dependencies.main.runtime.ts
because it gets consumed by the browser when running `bit start`.
=> remove node stuff from snapping index file

workspace.jsonc
=> revert apollo client version to 3.0.0 due to bit-start issues

scopes/generator/generator/generator.main.runtime.ts, scopes/generator/generator/new.cmd.ts, scopes/generator/generator/workspace-template.ts, scopes/react/react/templates/react-workspace-app/index.ts
- suggest running `bit run <appName>` if a workspace template contains the appName prop
- add appName to react-app workspace template
=> workspace template app name

scopes/react/react-native/webpack/webpack-transformers.ts
- fix os-agnostic webpack regex
-
-
=> react-native: fix webpack os-agnostic separator

e2e/harmony/multiple-testers.e2e.ts
=> skip multi testers e2e tests with jest on windows

scopes/component/ui/component-deprecated/component-deprecated.tsx
- Make deprecated arrow clickable link when it's a link.
=> Update component deprecated link

scopes/component/graph/ui/component-node/component-node.module.scss
- add env size to the component node in dependencies graph
=> Fix Custom Env Icon size

scopes/react/react/jest/transformers/base-transformer-presets.js
- add jest support for jsx runtime to react env (and all envs derived from it)
- 
-
=> add jsx-transform to jest config

scopes/harmony/cli/cli.main.runtime.ts
=> do not throw an error if trying to register the same cli group (show warning instead)

scopes/scope/scope/scope.main.runtime.ts, scopes/workspace/workspace/workspace.ts
=> load potential plugins from scope

scopes/scope/scope/scope.main.runtime.ts
=> when loading aspects from scope make sure to load their envs first

scopes/component/isolator/isolator.main.runtime.ts, scopes/dependencies/pnpm/pnpm.package-manager.ts, scopes/dependencies/yarn/yarn.package-manager.ts, scopes/scope/scope/scope.main.runtime.ts
- install peers from components/envs when isolating scope aspects
- improve pnpm and yarn logs
=> install peers on scope aspects

scopes/scope/scope/scope.main.runtime.ts
=> install peers on scope.getResolvedAspects

e2e/commands/remove.e2e.1.ts, scopes/component/status/status-cmd.ts, scopes/component/status/status.main.runtime.ts, src/consumer/component/components-list.ts
Suggest the user to "bit remove" them.
=> improvement(bit-status): show a new section of "soft-removed components on the remote

scopes/component/snapping/tag-model-component.ts
This is a regression caused by https://github.com/teambit/bit/pull/6333.
=> fix(soft-tag): fetch the username from the soft-tag data first then from the cloud

scopes/envs/envs/environments.main.runtime.ts, scopes/preview/preview/preview.main.runtime.tsx, scopes/react/react/react.env.ts, scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
- change the calculation of isScaling
- add isUsingCoreEnv API to envs aspect
- treat core envs as scaling always
=> fix is scaling data

scopes/compositions/compositions/compositions.tsx, scopes/preview/preview/preview.preview.runtime.tsx
=> Fix preview

scopes/compositions/compositions/composition.ts, scopes/compositions/compositions/compositions.preview-definition.ts, scopes/compositions/compositions/compositions.preview.runtime.ts, scopes/preview/preview/preview-definition.ts, scopes/preview/preview/preview.preview.runtime.tsx, scopes/preview/preview/strategies/component-strategy.ts, scopes/preview/preview/strategies/generate-component-link.ts, scopes/preview/preview/types/preview-module.ts
- support preview definition metadata
- add compositions metadata
- show first composition in the component card in the gallery
=> composition order

scopes/component/component/index.ts, scopes/component/component/ui/index.ts, scopes/component/component/ui/top-bar-nav/top-bar-nav.tsx, scopes/compositions/compositions/compositions.tsx, scopes/compositions/compositions/ui/compositions-panel/compositions-panel.tsx, scopes/preview/ui/component-preview/preview.tsx
- fixed preview's iframe height calculation
- component composition tab - fixed links to open in new tab
- fixed warning in component top bar caused by widget's `displayName`
=> Iframe height fix

scopes/preview/preview/preview.preview.runtime.tsx
=> preview runtime resize event fix

scopes/preview/preview/preview.main.runtime.tsx, scopes/preview/ui/component-preview/use-iframe-content-height.tsx
=> merge is scaliing fix

scopes/react/react/react.env.ts
- rename (and deprecate) non-dev-service get... functions to create...
- make getBuildPipe compiler agnostic
-
=> React env refactor

scopes/compositions/compositions/compositions.preview.runtime.ts, scopes/envs/envs/environments.main.runtime.ts, scopes/preview/preview/preview.graphql.ts, scopes/preview/preview/preview.main.runtime.tsx, scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
- fix all calculations of is scaling to better support components tagged before is scaling
- fallback to take a composition from the first query param if there is no name
=> fix preview compostion is scaling

scopes/defender/eslint-config-mutator/config-mutator.ts, scopes/defender/eslint/eslint.linter.ts, scopes/defender/eslint/eslint.main.runtime.ts, scopes/defender/linter/lint.cmd.ts, scopes/defender/linter/lint.task.ts, scopes/defender/linter/linter-context.ts, scopes/defender/linter/linter.main.runtime.ts, scopes/defender/linter/linter.service.tsx, scopes/defender/linter/linter.ts, scopes/react/eslint-config-bit-react/bit-react-eslint.js, scopes/react/react/react.env.ts
- improve the performance of bit lint command by a lot (see example image below)
- improve bit lint command outputs
=> make bit lint lightning fast

scopes/react/react/react.env.ts, scopes/react/react/react.main.runtime.ts
=> fix useTypescript

scopes/lanes/lanes/lane.cmd.ts
It was copied & pasted from "bit remove" command. Now it actually describes what it does.
=> fix(bit-lane-remove): correct the "--force" flag description

e2e/harmony/install-and-compile.e2e.ts, scopes/compilation/compiler/types.ts, scopes/compilation/compiler/workspace-compiler.ts, scopes/dependencies/dependency-resolver/dependency-installer.ts, scopes/dependencies/dependency-resolver/dependency-linker.ts, scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts, scopes/dependencies/dependency-resolver/index.ts, scopes/dependencies/dependency-resolver/package-manager.ts, scopes/dependencies/pnpm/lynx.ts, scopes/dependencies/pnpm/pnpm.main.runtime.ts, scopes/dependencies/pnpm/pnpm.package-manager.ts, scopes/dependencies/yarn/yarn.main.runtime.ts, scopes/dependencies/yarn/yarn.package-manager.ts, scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts, scopes/harmony/bit/hook-require.ts, scopes/workspace/install/install.main.runtime.ts, scopes/workspace/workspace/workspace.ts
=> feat: all custom envs are compiled during installation

e2e/harmony/lanes/merge-lanes.e2e.ts, scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts, scopes/scope/export/export.main.runtime.ts
This is part of the newly introduced command to merge lanes from scope: https://github.com/teambit/bit/pull/6478.
In this PR the export is implemented for both: central hub and local-scope.
=> feat: allow exporting merged lanes from scope

scopes/component/merging/merging.main.runtime.ts
So then it won't disturb the merge process and leave the workspace in an undermined state.
=> improvement(merging): run package-installation only after writing objects and .bitmap

src/api/scope/lib/fetch.ts
=> perf: improve lane import performance

scopes/harmony/bit/app.ts
=> add heapdump path location

e2e/harmony/custom-env.e2e.ts, scopes/workspace/workspace/workspace.ts
=> do not store env version in the envs data in model

e2e/harmony/install-and-compile.e2e.ts, scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.spec.ts, scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.ts, src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
- add missing packages to component if they were specified by its env
- install peers on root if all components use the same range
- fix bit install infinite loop
=> dep install fixes

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
=> fix: logging network configuration settings

scopes/dependencies/dependencies/dependencies-cmd.ts
- change the command name to its alias, 'deps'
- change the arg description of 'package' to 'packages...'
=> switch cmd alias with cmd name

scopes/harmony/node/templates/node-env/files/main.runtime.ts
- fixes for useTypescript and useWebpack pre-logic
-
-
=> fix node env template

scopes/component/snapping/tag-cmd.ts, scopes/pipelines/builder/build.cmd.ts, src/e2e-helper/e2e-command-helper.ts
To be align with `bit tag` synopsis.
=> improvement(bit-build): replace "--all" flag with "--unmodified"

e2e/harmony/root-components.e2e.ts
=> test: don't run install/compile/install in root component tests

scopes/scope/scope/scope.ui.drawer.tsx
* Handle when scope index is falsy
=> fix scope ui drawer

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts, scopes/scope/update-dependencies/update-dependencies.main.runtime.ts, scopes/workspace/workspace/workspace-component/workspace-component-loader.ts, scopes/workspace/workspace/workspace.ts
=> load dependencies from unmerged head of components

scopes/component/component/component.graphql.ts
add parents to graphql component log
=> add parents

src/scope/scope.ts
It might be a bug with fs-extra (there are some issues about it in their repo). In some rare cases, it throws ENOTEMPTY during `fse.remove`. It causes the export to gets stuck because the queue cannot get deleted. This PR makes another try after a second.
=> fix: retry to delete pending-objects dir in case of ENOTEMPTY error

e2e/harmony/install-angular.e2e.ts, scopes/component/isolator/isolator.main.runtime.ts, scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts, scopes/dependencies/dependency-resolver/package-manager.ts, scopes/dependencies/yarn/yarn.package-manager.ts, scopes/scope/scope/scope.main.runtime.ts, src/e2e-helper/e2e-command-helper.ts
=> fix: packages should be deduped in yarn capsules, unless root components are on

.circleci/config.yml
=> use nightly version of bit in circle ci

package.json
=> upgrade @teambit/component-version to v0.0.406 in the legacy

scopes/ui-foundation/ui/start.cmd.tsx, scopes/ui-foundation/ui/ui.main.runtime.ts
add flag to skip ui build at start
=> add flag to skip ui build at start

scopes/api-reference/renderers/grouped-schema-nodes-summary/grouped-schema-nodes-summary.tsx, scopes/api-reference/renderers/parameter/parameter.renderer.tsx, scopes/semantics/entities/semantic-schema/schemas/parameter.ts, scopes/semantics/schema/mock/button-schemas.json, scopes/typescript/typescript/transformers/utils/get-params.ts, scopes/typescript/typescript/transformers/utils/parse-type-from-quick-info.ts, scopes/typescript/typescript/transformers/utils/to-function-like-schema.ts
- Extract Destructured Params from Parameter
- Render Destructured Params in Parameter Renderer
=> API Reference + Schema: Parse Object Binding Elements

e2e/flows/out-of-sync-componets.e2e.3.ts, src/consumer/component/components-list.ts
currently, it's only determined by checking the existence of the component in the local scope.
=> fix(status): determine whether a component is new based also on .bitmap record

scopes/api-reference/renderers/api-node-details/api-node-details.module.scss, scopes/api-reference/renderers/api-node-details/api-node-details.tsx, scopes/api-reference/utils/code-editor-options/code-editor-options.ts
=> API Reference: Monaco Editor: Design Refinement

e2e/harmony/root-components.e2e.ts, scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts
=> fix: dependencies should be hoisted even when root components are used

scopes/api-reference/renderers/api-node-details/api-node-details.module.scss, scopes/api-reference/renderers/api-node-details/api-node-details.tsx, scopes/api-reference/renderers/enum/enum.renderer.tsx, scopes/api-reference/renderers/function/function.renderer.tsx, scopes/api-reference/renderers/schema-nodes-index/schema-nodes-index.module.scss, scopes/api-reference/renderers/schema-nodes-index/schema-nodes-index.tsx, scopes/api-reference/renderers/type-ref/type-ref.renderer.tsx, scopes/api-reference/renderers/type/type.renderer.tsx
- Hide Schema Node Index if less than the `THRESHOLD WIDTH`
- Show Schema Node Index for only `Classes` and `Interfaces`
- style fixes
=> API Reference: Design refinement: Schema Node Index

components/ui/table-row/table-row.tsx, scopes/api-reference/renderers/grouped-schema-nodes-summary/grouped-schema-nodes-summary.module.scss, scopes/api-reference/renderers/grouped-schema-nodes-summary/grouped-schema-nodes-summary.tsx, scopes/api-reference/renderers/schema-node-member-summary/function-node-summary.module.scss, scopes/api-reference/renderers/schema-node-member-summary/function-node-summary.tsx, scopes/api-reference/renderers/type-ref/type-ref.renderer.tsx
https://user-images.githubusercontent.com/8999604/202811482-bf46cc40-3bb2-4a69-a042-b41f18b7d038.mov
=> API Reference: Method Signature Details

e2e/harmony/install-and-compile.e2e.ts, scopes/workspace/install/install.cmd.tsx, scopes/workspace/install/install.main.runtime.ts
=> feat: install support a --skip-compile option

e2e/harmony/root-components.e2e.ts, scopes/dependencies/pnpm/pnpm.package-manager.ts
- fixes a regression introduced via: https://github.com/teambit/bit/pull/6662
=> fix: compilation when root components are on

scopes/api-reference/api-reference/api-reference.aspect.ts, scopes/component/component-compare/component-compare.aspect.ts, scopes/component/component-sizer/component-sizer.aspect.ts, scopes/component/component-tree/component-tree.aspect.ts, scopes/component/deprecation/deprecation.aspect.ts, scopes/component/graph/graph.aspect.ts, scopes/dependencies/pnpm/pnpm.aspect.ts, scopes/dependencies/yarn/yarn.aspect.ts, scopes/explorer/command-bar/command-bar.aspect.ts, scopes/harmony/aspect/aspect.aspect.ts, scopes/harmony/node/node.aspect.ts, scopes/lanes/lanes/lanes.aspect.ts, scopes/mdx/mdx/mdx.aspect.ts, scopes/pkg/pkg/pkg.aspect.ts, scopes/react/react-native/react-native.aspect.ts, scopes/react/react/react.aspect.ts, scopes/scope/scope/scope.aspect.ts, scopes/ui-foundation/react-router/react-router/react-router.aspect.ts, scopes/ui-foundation/sidebar/sidebar.aspect.ts
- add default export to all core aspects
=> Aspects default export

scopes/component/component/component.graphql.ts, scopes/scope/scope/scope.main.runtime.ts
=> add component log

scopes/component/ui/component-meta/component-overview.tsx, scopes/docs/docs/overview/overview.tsx
=> remove unnecessary code from component overview

scopes/component/ui/component-meta/component-overview.module.scss, scopes/component/ui/component-meta/component-overview.tsx, workspace.jsonc
- Update version.
- Pass component type instead of react node.
- Add eslint comment to avoid error. 
@GiladShoham this is the error I get on the component property I pass.
https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/display-name.md
=> Update content tabs version and make changes according to the new version

src/consumer/component/dependencies/dependency-resolver/overrides-dependencies.ts
=> fix: bit status should not show missing deps incorrectly

e2e/harmony/dependencies/policies-order.e2e.ts, e2e/harmony/root-components.e2e.ts, src/e2e-helper/e2e-fixtures-helper.ts, src/e2e-helper/e2e-fs-helper.ts
=> test: move envMainRuntimeFile to fixtures helper
