teambit/bit

tasks/test-runner.js

'npm run test' is working now.

fix gulp running ES6 tests

---

docs/installation.md

Homebrew once again has a working formula for `bit`, so remove the 'currently unavailable' label from the command to install `bit` via Homebrew.

update Homebrew install method availability

---

CHANGELOG.md
docs/CLI-reference.md
docs/getting-started.md

The links in "Getting Started" and "CLI Reference" to bitsrc.io did not work.

Docs - fix bitsrc links 

---

e2e/commands/import.e2e.js
e2e/commands/install.e2e.js
src/cli/chalk-box.js
src/cli/commands/public-cmds/import-cmd.js
src/cli/commands/public-cmds/install-cmd.js
src/cli/default-error-handler.js

- deprecated install command
- added `--environment` option for `bit import`
- reformatted `bit import` output (components, dependencies, environments)

import outputs and environment installation

---

src/api/consumer/lib/add.js

this is related to the  bug : https://app.asana.com/0/137456040763555/422670930696674
after excluding file bit didnt print the correct number of components

added correct print after removing excluded files

---

src/scope/network/ssh/ssh.js

the current error message is not clear enough and does not help with fixing the issue.

clear error message when Bit can't find private ssh key

---

CHANGELOG.md
src/scope/models/version.js

add the default binding prefix to the version model id when not specified (fix a bug which makes imported components considered as modified)

add the default binding prefix to the version model id 

---

CHANGELOG.md
src/cli/templates/help.js

In the process of fixing typos, editorconfig found some trailing spaces.

fix(cli): remove typos from help page

---

.gitignore
package-lock.json
package.json

This PR addresses packaging Bit as an executable for macOS, linux and windows.
- added `pkg` to npm scripts for building a `releases` directory with all supported executables.
- added `releases` directory to .gitignore
@davidfirst @GiladShoham - would love your feedback.

packaging bit as executable

---

src/scope/network/ssh/ssh.js

fixed bug for better handling of SSH agent auth failures.
Now falling back to private key auth in case Bit failed to authenticate using ssh-agent.
@GiladShoham would be great if you can check if it works for you before merging

bug: skip ssh agent

---

src/api/consumer/lib/add.js
src/consumer/component/components-list.js
src/scope/scope.js

fix error "TypeError: Invalid Version: latest" when running bit status on local components with auto-tagging candidates

fix Invalid version latest

---

src/scope/objects/repository.js
src/scope/scope.js

(because we might have old invalid objects)

skip validation of objects during migration 

---

e2e/flows/es6-link-files.e2e.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/981)

support "export X from Y" syntax of ES6 without importing X first

---

package.json

as you can see `requestify` appears twice in package.json. It is used outside the context of tests so I removed it from devDependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1125)

remove dependency mentioned twice in package.json

---

CHANGELOG.md
src/scope/scope.js

1) fix "Error: EMFILE: too many open files" by opening the objects files of a component by one by and not all at the same time. 
2) fix "JavaScript heap out of memory" by running toVersionDependencies() of the components one after another and not all at once
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1270)

fix errors when exporting a huge number of components. 

---

CHANGELOG.md
src/links/node-modules-linker.js

In vue environment during bit install the process was creating .vue files with module.exports of relative path. The index.vue file is generated fine (the file is generated using getLinkContent) but the internal files contain only module.exports = require... without the script tag.
The change I applied is to use the getLinkContent function in authored components generation too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1299)

fixed file content generation on authored components linking

---

src/cli/commands/public-cmds/link-cmd.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1297)

fix bit-link error messages to not be shown as a stringified JSON

---

src/app.js
src/cli/version-command.js

- bit version command took over 2 sec, after it take only 0.05s.
-
-
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1372)

make Bit version command faster

---

README.md

I fixed the spelling of Ramda
- fix the spelling of the Ramda library
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1534)

Typo: one letter swap

---

CHANGELOG.md
e2e/commands/build.e2e.1.js
src/cli/commands/public-cmds/build-cmd.js

fix build command with no cache flag.
and now is posible to run the short flag: `bit build -c`
I opened an issue about this https://github.com/teambit/bit/issues/1533
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1535)

reintroduce -c alias for no cache flag in build command

---

README.md

- Change word "components" to singular in the sentence: `You won’t need to refactor or create separate directories and configurations for every component.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1545)

Remove "s" from a sentence in Bit monorepo section

---

CHANGELOG.md
src/npm-client/npm-client.js

Fixes https://github.com/teambit/bit/issues/1617.
The error is thrown due to a race condition between npm installation of the directories.
The error can be reproduced by running the e2e-test `‘import dependency and dependent with the same command => when the dependent comes before the dependency` multiple times.
In the example of this e2e-test, `bar/foo` has a dependency `utils/is-string`, which has a dependency `utils/is-type`. 
The package.json of `bar/foo` has `utils/is-string` as a relative path (instead of a version), so ‘npm install’ of `bar/foo` causes installation of npm in `utils/is-string` as well. 
When installing npm in parallel for both `bar/foo` and `utils/is-string`, it’s like running in parallel npm installation twice for the same directory `components/utils/is-string`. …

fix "npm ERR! enoent ENOENT" errors when importing/installing multiple components

---

CHANGELOG.md
package.json
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.js

The fix is done on bit-javascript.
A case example for this fix:
compA requires compB with `import { Utils } from compB.js;` , compB requires `Utils` from some_file.js, however, it doesn't export it, only uses it internally.
In this case, bit-javascript identified compB.js as a link file incorrectly. 
With this fix, a link file is identified only when it import and export `Utils`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1621)

fix #1606, fix dependency resolution to identify link (proxy) files correctly

---

e2e/commands/import.e2e.1.js
e2e/commands/install.e2e.1.js
e2e/flows/binary-files.e2e.2.js
e2e/flows/import-from-bit-hub.e2e.3.js
e2e/flows/pad-left-and-is-string.e2e.3.js
e2e/typescript/typescript.e2e.3.js
src/consumer/bit-map/component-map.js
src/consumer/component-ops/manipulate-dir.js
src/scope/repositories/sources.js

Currently, we have a mix of behaviors. 
Authored - not stripped.
Imported - stripped.
Nested - if installed via npm - stripped, otherwise - not stripped.
It causes some weird issues with components that were nested before and now imported with different versions. 
This PR simplify the feature to strip the shared directory for any non-author component, including local nested dependencies that are imported into `components/.dependencies` directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1651)

simplify stripping shared-dir feature to apply for any non-authored component

---

CHANGELOG.md
e2e/commands/remove.e2e.2.js
e2e/flows/dist-outside-components.e2e.2.js
e2e/typescript/typescript.e2e.3.js
src/consumer/component-ops/delete-component-files.js
src/consumer/component-ops/eject-components.js
src/consumer/component/package-json-utils.js
src/consumer/component/sources/dists.js
src/consumer/consumer.js

* fix bit-remove and bit-eject to delete the dist directory when located outside the components dir. 
* fix bit-eject to support component custom npm registry scope
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1664)

fix #1656, remove dist dir upon eject

---

CHANGELOG.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1689)

fix #1665 on bit-javascript. fix resolve-modules prefix with tilda on css files

---

.circleci/config.yml
appveyor.yml

Currently, CIs build fails often due to using old cache.
With this change, the CI won't use the NPM cache and node_modules cache when one of the following files has changed:
- package.json
- package-lock.json
- CI config file (.circleci/config.yml or appveyor.yml)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1748)

stabilize CIs (CircleCI and AppVeyor) by invalidating cache upon package.json/package-lock.json/ci-config-file changes

---

e2e/fixtures/fixtures.js
e2e/flows/capsule.e2e.2.js
src/consumer/component-ops/component-writer.js
src/consumer/component-ops/many-components-writer.js

Specifically, change the following:
- component files are on the root directory of the capsule
- dependencies are imported into `.dependencies` of the capsule root and not on `components/.dependencies`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1763)

re-structure the isolated component files on the capsule as described in #1758

---

CHANGELOG.md
e2e/fixtures/fixtures.js
e2e/typescript/typescript.e2e.3.js
src/links/dependency-file-link-generator.js
src/links/link-content.js

When a component requires an internal file (not main file) of another component, the generated link had the `require`/`import` statement with the extension. For example:
```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import isString from '@bit/yxlgnwmi-remote.utils.is-string/dist/is-string-internal.ts';
export default isString;%
```
This fix makes sure to strip the extension in this case when the extension is one of the following:
[.js, .ts, .tsx, .jsx]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1773)

fix require statements to an internal package file

---

CHANGELOG.md
e2e/commands/untag.e2e.2.js
e2e/flows/capsule.e2e.2.js
src/api/consumer/lib/untag.js
src/consumer/consumer.js
src/scope/models/model-component.js

so then it won't throw ComponentNotFound when tagging after export & tag & untag.
Also, unify the process of updating the versions in `.bitmap` and `package.json` upon tag and untag.
Before, they were unsynced two different processes.
Fix https://github.com/teambit/bit/issues/1817.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1820)

update component's package.json of authored upon untag

---

package-lock.json
package.json

It has been reduced from 375 to only 3. These 3 are coming from Verdaccio, which is a devDependency, and there is no way to fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1839)

fix vulnerabilities found by npm audit

---

CHANGELOG.md
e2e/commands/watch.e2e.2.js
e2e/e2e-helper.js
e2e/fixtures/fixtures.js
package-lock.json
package.json
src/api/consumer/lib/watch.js
src/consumer/component-ops/watch-components.js
src/consumer/component/components-list.js

- improve the output according to https://github.com/teambit/bit/issues/1634.
- add infrastructure of e2e testing of `bit watch`.
- avoid building all component for every change, build only the component needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1846)

improve output and performance of bit watch and add tests

---

CHANGELOG.md
e2e/commands/add.e2e.1.js
src/consumer/bit-map/bit-map.js
src/consumer/component-ops/add-components/add-components.js
src/consumer/component-ops/add-components/determine-main-file.js
src/consumer/component-ops/component-writer.js

Also, extract the logic of finding the mainFile from bitMap class to a new file and reorganize the code to loop through the different strategies
Implements https://github.com/teambit/bit/issues/1714.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1860)

Auto recognize mainFile when one of the added files has the same name as its dir

---

e2e/commands/import.e2e.1.js
src/consumer/component-ops/many-components-writer.js
src/consumer/component-ops/move-components.js

- when a component has trackDir, move the component after import.
- when there is no trackDir, throw an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1877)

Fix import with "--path" flag for author

---

e2e/e2e-helper.js
e2e/fixtures/compilers/capsule/compiler.js
e2e/fixtures/compilers/dist-main/compiler.js
e2e/fixtures/compilers/pkg-json/compiler.js
e2e/flows/dist-main-is-different.e2e.2.js
e2e/functionalities/capsule.e2e.2.js

* add an e2e-test to make sure the new functionality added to the compiler API (such as a method to isolate a component) is available also in the new compiler API.
* add another e2e-test to make sure the new values returned by the compiler, such as dist-main-file is also taken care of in the new compiler API
Done for https://github.com/teambit/bit/issues/1888.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1909)

Add tests to make sure the new compiler API has the new capsule related functionality

---

.circleci/config.yml
CHANGELOG.md
e2e/platforms/angular.e2e.3.js
package-lock.json
package.json
src/consumer/component/component-loader.js

Fixes https://github.com/teambit/bit/issues/1917 and https://github.com/teambit/bit/issues/1906.
These packages were needed originally to detect Angular dependencies. The decorators are now parsed with the TS compiler to detect the `styleUrl` and `templateUrl`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1921)

Update bit-javascript to remove Angular packages dependencies

---

CHANGELOG.md
e2e/commands/export.e2e.1.js
src/api/consumer/lib/export.js
src/bit-id/bit-ids.js
src/cli/commands/public-cmds/export-cmd.js
src/e2e-helper/e2e-command-helper.js
src/e2e-helper/e2e-scope-helper.js
src/scope/component-ops/export-scope-components.js

By omitting the `remote` arg and using `--last-scope` flag (the flag name might be changed later)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1953)

(experimental) support exporting components to their last remote

---

CHANGELOG.md
fixtures/consumer-components/sass/bar-foo.json
fixtures/consumer-components/sass/utils-is-string.json
fixtures/consumer-components/sass/utils-is-type.json
src/links/dependency-file-link-generator.js
src/links/dependency-file-link-generator.spec.js
src/links/link-content.js
src/links/link-generator.js

Fixes https://github.com/teambit/bit/issues/1965.
Sadly, node-sass doesn't resolve directories to the default 'index.scss', so the generated link needs to manually point to the main file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1968)

Fix generated links for .scss and .sass packages to point to the main file

---

src/cli/templates/component-template.js

to display the immediate-dep as `<self>` when it is the same component
According to the suggestion in https://github.com/teambit/bit/issues/1885.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1975)

Improve bit-show --dependencies/--dependents 

---

CHANGELOG.md
e2e/commands/log.e2e.1.js
src/api/consumer/lib/export.js

currently, it fails only when collecting the objects with an error "ENOENT: no such file or directory"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1992)

fail early when exporting nested dependency

---

CHANGELOG.md
src/api/consumer/lib/tag.js
src/utils/resolveLatestVersion.js
src/utils/resolveLatestVersion.spec.js

Otherwise, the user will get an error of "getLatestVersionNumber failed to find ..."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/1994)

fail early when tagging a component with a prerelease version

---

src/scope/component-ops/scope-components-importer.js

to be done by `R.partition` rather than `R.splitWhen`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2008)

change importMany implementation of splitting the local & external components 

---

CHANGELOG.md
e2e/commands/export.e2e.1.js
src/api/consumer/lib/export.js
src/bit-id/bit-ids.js
src/scope/component-ops/export-scope-components.js

* fix exporting to a different scope than workspace configuration of `defaultScope` to not export it to the default-scope.
* fix `toGroupByScopeName() expect ids to have a scope name` error when exporting multiple components when some of them were exported before and some were not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2007)

Fix bugs when exporting with the newly introduced "bit export" enhancements

---

CHANGELOG.md
src/logger/logger.js
src/logger/logger.spec.js

Happens when logging a circular metadata object.
Implemented by catching the error and printing a message saying the metadata has a circular structure and can't be printed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2009)

Fix "Converting circular structure to JSON" error 

---

src/links/node-modules-linker.js
src/utils/fs/search-files-ignore-ext.js
src/utils/fs/search-files-ignore-ext.spec.js

This is an attempt to fix the hard-to-reproduce bug of "fatal: trying to write a link file into a symlink file".
There is a good chance that it happens when Bit finds the wrong parallel file in the `dists` and generates a symlink instead of a link.
When the error happens to a user, the first thing to check is the log messages start with `search-file-ignore-ext`, it shows what were the options and what ended up used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2010)

prioritize .js files when searching for a parallel file in the dists

---

CHANGELOG.md
e2e/functionalities/custom-module-resolutions.e2e.2.js
package-lock.json
package.json
src/links/link-generator.js

By adding a suffix of `index.js` when needed.
Fixes https://github.com/teambit/bit/issues/2013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2016)

Fix bit import when one module resolution alias is a directory of another alias

---

CHANGELOG.md
src/cli/commands/public-cmds/link-cmd.js
src/consumer/component/consumer-component.js
src/links/linker.js
src/links/node-modules-linker.js

Fixes part of https://github.com/teambit/bit/issues/2033.
Currently, when custom-resolved-links or dependency links are missing, Bit regenerate them on 'bit link'. However, turned out that in some cases not all missing links are found and in such cases, bit link won't generate them. 
With this fix, as long as some links are missing, Bit will regenerate them all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2043)

Improve bit link to regenerate all links in case some links were reported missing

---

.circleci/config.yml

- remove bit-javascript jobs from circle (they are part of the bit-javascript repo circle now)
- unit_test_bit_javascript
- lint_bit_javascript
- check_types_bit_javascript
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2080)

remove bit-javascript jobs from circle 

---

CHANGELOG.md
src/cli/chalk-box.ts
src/cli/commands/public-cmds/test-cmd.ts
src/consumer/component/consumer-component.ts
src/consumer/specs-results/specs-results.ts
src/scope/scope.ts
src/specs-runner/specs-runner.ts

- add `--no-warnings` flag to bit test child process
- show a message about missing test files in the compiled files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2098)

test cmd improvements

---

CONTRIBUTING.md
src/app.ts

to get the complete stack trace while running bit commands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2121)

enable users to change the long-stack-traces settings 

---

CHANGELOG.md
e2e/commands/export.e2e.1.ts
src/scope/component-ops/scope-components-importer.ts

Before the fix, it used to throw an error ComponentNotFound of the dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2129)

Fix fork of a component when a dependency exists in an older version only

---

src/scope/scope.ts

When we build/tag a component without a compiler, the loader shows a success status, so I update the code to check if the component has a compiler attached to it before running the loader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2156)

Not show fail or success icon when building component without compiler

---

CHANGELOG.md
e2e/commands/export.e2e.1.ts
src/scope/component-ops/export-scope-components.ts
src/scope/graph/components-graph.ts
src/scope/scope.ts

and there are dependencies between them. Fixes https://github.com/teambit/bit/issues/2171.
This happens when a component in one scope has a dependency in another remote. e.g. a component remoteA/compA depends on remoteB/compB.
in case remoteA/compA was exported first, remoteA throws an error that remoteB/compB was not found.
The solution implemented in this PR, sorts the components topologically, which ensures that we export remoteB/compB first.
It also takes care of the following cases:
1) in case there are cycle dependencies between the scopes, it's impossible to toposort, so Bit throws a descriptive error, suggesting to untag.
2) the cycle dependencies can be between different versions. e.g. remoteA/compA@0.0.1 requires remoteB/compB@0.0.1 and remoteB/compB@0.0.2 requires …

Fix component-not-found when exporting to multiple scopes 

---

CHANGELOG.md
e2e/functionalities/workspace-config.e2e.3.ts
src/consumer/config/consumer-overrides.ts

Fixes https://github.com/teambit/bit/issues/2176.
This happened due to `object.assign` mutating the workspace overrides, which should be immutable.
It has been fixed by cloning the workspace-overrides before doing any calculation for specific components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2179)

Fix workspace-overrides to not leak rules to unrelated components

---

CHANGELOG.md
e2e/fixtures/compilers/capsule/compiler.js
e2e/functionalities/capsule.e2e.2.ts
src/consumer/component/consumer-component.ts

Fixes one out of two issues found in https://github.com/teambit/bit/issues/2182.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2188)

Avoid writing dependencies dists to a capsule when their compiler was removed

---

CHANGELOG.md
src/scope/component-ops/export-scope-components.ts
src/utils/string/replace-package-name.spec.ts
src/utils/string/replace-package-name.ts

Fixes one out of two issues found in #2182.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2189)

Fix package-name replacement of dists when a package has a tilda prefix

---

CHANGELOG.md
e2e/functionalities/workspace-config.e2e.3.ts
src/consumer/config/consumer-overrides.ts

Fixes https://github.com/teambit/bit/issues/2255.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2257)

Avoid adding unneeded overrides to workspace config upon import

---

CHANGELOG.md
e2e/commands/link.e2e.1.ts
src/links/node-modules-linker.ts
src/utils/bit/component-node-modules-path.ts

when a component id doesn't have a scope-name. (before export for an author).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2262)

use workspace defaultScope to generate node-modules links 

---

CHANGELOG.md
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

Happens when a dependency has a different version in the main package.json and in the dist/package.json (relevant for typescript components).
This PR makes sure to disregard the dependencies versions and not add them twice.
Fixes #2260.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2271)

fix duplicate dependencies 

---

src/app.ts
src/harmony/exceptions/extension-potential-circular.ts
src/harmony/exceptions/harmony-error.ts
src/harmony/exceptions/index.ts
src/harmony/extension-graph/from-extension.ts

- Throw proper error when there are circular dependencies between harmony extensions
- relate to #2280
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2282)

Throw proper error when there are circular dependencies between harmony extensions

---

src/consumer/component-ops/component-writer.ts
src/consumer/component-ops/many-components-writer.ts
src/consumer/component/package-json-utils.ts
src/environment/capsule-builder.ts
src/environment/capsule-paths.ts

in order to retrieve a capsule-path by BitId rather than by a string
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2296)

change capsule-workspace-map object to a class CapsulePaths

---

CHANGELOG.md
e2e/commands/export.e2e.1.ts
src/api/consumer/lib/export.ts
src/cli/commands/public-cmds/export-cmd.ts
src/e2e-helper/e2e-scope-helper.ts
src/scope/component-ops/export-scope-components.ts
src/scope/models/model-component.ts

Fixes part of #2300 .
Currently, `bit export` pushes all versions (tags) of a component, regardless of whether it has changed or not.
With this fix, it sends only the staged versions.
In case of a fork, or codemod, where all versions are changed, it sends them all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2304)

Improve bit export performance by pushing new tags only

---

CHANGELOG.md
e2e/commands/export.e2e.1.ts
src/scope/component-ops/export-scope-components.ts

Happens when exporting to multiple scopes (by running `bit export` with no id).
The bug was related to the graph built to make sure the export is done in topological order. This graph contains all dependencies of the pending-export components. 
After the sort, Bit was trying to export these dependencies as well although they were not export-pending.
Fixes #2211 and #2308 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2309)

fix bit export to not export non-staged dependencies

---

CHANGELOG.md
CONTRIBUTING.md
package-lock.json
package.json
src/api/consumer/lib/migrate.ts
src/app.ts
src/constants.ts
src/consumer/component/package-json-vinyl.ts
src/consumer/component/sources/data-to-persist.ts
src/consumer/consumer.ts
src/extensions/env-extension.ts
src/extensions/env-factory.ts
src/jsdoc/jsdoc/jsdoc-parser.ts
src/jsdoc/react/react-parser.ts
src/logger/logger.ts
src/scope/models/model-component.ts
src/scope/models/version.ts
src/scope/objects/repository.ts
src/scope/scope.ts

Fixes #2268.
* prevent logger from holding the terminal once a command is completed by adding an error handler.
* introduce a new log level `silly`.
* change some `logger.debug` to `logger.silly`.
* support configuring the logger level by running `bit config set log_level <level>`.
* limit the number of concurrent files written to the fs in the `DataToPersist` class to 100.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2310)

prevent logger from holding the terminal once a command is completed

---

e2e/commands/link.e2e.1.ts
e2e/functionalities/default-scope.e2e.2.ts
src/consumer/consumer.ts
src/e2e-helper/e2e-bit-json-helper.ts
src/e2e-helper/e2e-fixtures-helper.ts
src/utils/bit/package-name-to-component-id.spec.ts
src/utils/bit/package-name-to-component-id.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2313)

make sure a basic flow of defaultScope functionality is working

---

src/api/consumer/lib/capsule-isolate.ts
src/bit-id/bit-id-and-value-array.ts
src/consumer/component/package-json-utils.ts
src/environment/capsule-builder.ts
src/environment/capsule-list.ts
src/environment/capsule-paths.ts
src/extensions/bit/bit.ts
src/extensions/capsule/capsule.ts
src/extensions/workspace/workspace.ts

- fix Workspace to get BitIds as a parameter (still, support bitId as a string)
- add a new class "capsule-list" for an array of BitId and Capsule to eliminate the use of BitId as strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2318)

More fixes of misuse BitId as strings

---

CHANGELOG.md
e2e/commands/export.e2e.1.ts
src/cli/commands/public-cmds/export-cmd.ts

To enable re-exporting a component after deleting it.
Fixes part of #2341 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2345)

enable "--all" flag when "--all-versions" is used and vice versa

---

README.md

Link to quick start guide is broken, should contain subdirectory docs in URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2338)

Fixed broken link leading to quick start guide

---

package-lock.json
package.json

This is to fix an issue where we would get errors for very large files in a capsule's node_modules.
The fix in librarian has to do with a race condition when extracting tarballs to memory synchronously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2389)

chore(packages): upgrade librarian to 3.6.2

---

src/cli/commands/public-cmds/capsule-cmd.ts

* remove `--workspace` flag as it is defined as an argument already. 
* add `--json` flag to support json format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2398)

Improve capsule-list command

---

e2e/flows/dependencies-as-packages.e2e.2.ts
src/extensions/package-manager/package-manager.ts
src/extensions/workspace/workspace.ts

This includes a few fixes:
1. when installing with npm, use the `--no-package-lock` option. This is because there are platform bugs with package locks and optional dependencies (eg. fsevents on linux/windows).
2. use execa to delete/link bit-bin inside capsules instead of capsule-fs. This is much safer and does what we want (as explained in the comment).
3. Use the default package manager in the project for installing non-extensions components rather than hard-coded npm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2395)

fix(extensions): installation and build bugs

---

CHANGELOG.md
e2e/flows/no-scope.e2e.2.ts
src/cli/commands/public-cmds/export-cmd.ts
src/scope/component-ops/export-scope-components.ts

e.g. having the following statement in the code `require('@bit/is-string')` can be only valid for the author, but won't work once the component is imported.
This PR makes sure to throw an error on export suggesting to use the `--rewire` flag to automatically change all import/require statements to include the scope-name.
As a result, the previous `require('@bit/is-string')` becomes `require('@bit/your-scope.is-string')`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2417)

prevent exporting components when import/require doesn't have scope-name

---

CHANGELOG.md
e2e/api/add-many.e2e.1.ts
e2e/commands/import.e2e.1.ts
e2e/commands/install.e2e.1.ts
e2e/commands/link.e2e.1.ts
e2e/commands/tag.e2e.1.ts
e2e/commands/untag.e2e.2.ts
e2e/flows/es6-link-files.e2e.3.ts
e2e/flows/pad-left-and-is-string.e2e.3.ts
e2e/flows/sort-components-output.e2e.3.ts
e2e/functionalities/env-dependencies.e2e.3.ts
e2e/functionalities/workspace-config.e2e.3.ts
e2e/typescript/typescript-link-files.e2e.3.ts
src/api/consumer/lib/link.ts
src/api/consumer/lib/tag.ts
src/cli/command-registrar-builder.ts
src/cli/commands/public-cmds/link-cmd.ts
src/cli/commands/public-cmds/tag-cmd.ts
src/cli/templates/codemod-template.ts
src/cli/templates/component-issues-template.ts
src/cli/templates/link-template.ts
src/consumer/component-ops/codemod-components.ts
src/consumer/component-ops/install-components.ts
src/consumer/component/consumer-component.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/consumer.ts
src/e2e-helper/e2e-command-helper.ts
src/links/linker.ts

- introduce `bit link --rewire` to change relative paths in the source code to module paths
- prevent tagging components that require each other by relative paths (bypassed by `--allow-relative-paths`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2419)

prevent tagging relative-paths components 

---

CHANGELOG.md
e2e/commands/add.e2e.1.ts
e2e/commands/checkout.e2e.1.ts
e2e/commands/export.e2e.1.ts
e2e/commands/import.e2e.1.ts
e2e/commands/move.e2e.1.ts
e2e/commands/remove.e2e.1.ts
e2e/commands/show.e2e.2.ts
e2e/commands/status.e2e.2.ts
e2e/commands/tag.e2e.1.ts
e2e/flows/big-file.e2e.2.ts
e2e/flows/import-package-json.e2e.3.ts
e2e/flows/permissions-errors.e2e.3.ts
e2e/functionalities/binary-files.e2e.2.ts
e2e/functionalities/dev-dependencies.e2e.2.ts
e2e/functionalities/link-generation.e2e.2.ts
e2e/platforms/angular.e2e.3.ts
src/api/consumer/lib/add.ts
src/cli/commands/public-cmds/add-cmd.ts
src/cli/default-error-handler.ts
src/consumer/bit-map/component-map.ts
src/consumer/component-ops/add-components/add-components.ts
src/consumer/component-ops/add-components/exceptions/addding-individual-files.ts
src/e2e-helper/e2e-command-helper.ts

This will help stabilize the product by enabling only directories to be added.
Adding individual files means there is no one base-dir for the component and many components can have the same base-dir, as a result, when importing the component, a process of stripping-shared-dir needs to be done. This process is complex and error-prone. This PR is a big step toward eliminating it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2426)

disallow adding individual files by bit-add unless --allow-files flag is used

---

CHANGELOG.md
e2e/commands/export.e2e.1.ts
src/scope/component-ops/export-scope-components.ts

And a flattened dependency was converted from no-scope to a remote-scope.
See this for more details:
https://github.com/teambit/bit/issues/2171#issuecomment-600135982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2466)

Fix ComponentNotFound when using bit-export with no args

---

CHANGELOG.md
e2e/functionalities/components-index.e2e.2.ts
src/cli/default-error-handler.ts
src/scope/objects/components-index.ts
src/scope/objects/repository.ts

Fixes https://github.com/teambit/bit/issues/2482.
Until now, Bit was throwing an error suggesting the user to delete the file manually.
The idea was to catch these occurrences and understand why they happen.
According to the issue above, it could happen when exporting a component and canceling the operation by ^c, which makes sense. Bit does try to be atomic here so then the update of the scope and index.json occur within the same function.
However, if the cancellation happened exactly after deleting the component file in the scope and before writing the index.json file, they both won't be synced. 
It is possible to keep track of the deleted files one by one and map them to the components and then do some rollback to have it atomic for real, however, it's out of the scope of this PR.
--- …

Delete index.json file in case its content does not match the scope content

---

CHANGELOG.md
e2e/commands/link.e2e.1.ts
src/api/consumer/lib/link.ts
src/cli/commands/public-cmds/link-cmd.ts
src/consumer/component-ops/codemod-components.ts
src/e2e-helper/e2e-command-helper.ts
src/links/linker.ts

Currently, `bit link` links all components with no option to specify individual components.
This PR enables link specific components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2490)

add "ids" argument to bit-link to support linking particular components

---

e2e/commands/eject.e2e.1.ts
e2e/commands/import.e2e.1.ts
e2e/commands/init.e2e.1.ts
e2e/commands/status.e2e.2.ts
e2e/flows/cyclic-dependencies.e2e.2.ts
e2e/flows/dependencies-as-packages.e2e.2.ts
e2e/flows/import-package-json.e2e.3.ts
e2e/flows/out-of-sync-componets.e2e.3.ts
e2e/flows/pad-left-and-is-string.e2e.3.ts
e2e/functionalities/auto-tagging.e2e.2.ts
e2e/functionalities/binary-files.e2e.2.ts
e2e/functionalities/component-config.e2e.2.ts
e2e/functionalities/dev-dependencies.e2e.2.ts
e2e/functionalities/env-dependencies.e2e.3.ts
e2e/functionalities/envs.e2e.3.ts
e2e/functionalities/peer-dependencies.e2e.3.ts
e2e/functionalities/workspace-config.e2e.3.ts
src/e2e-helper/e2e-command-helper.ts

Instead, use the --json flag to parse the status results.
This is done to prevent CLI styling from affecting the test results. Specifically, this is fixing React/Ink adding '\n' in the status output in the Harmony branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2550)

refactor e2e-tests to not check for a success message of bit-status

---

e2e/platforms/vue.e2e.3.ts
src/extensions/package-manager/package-manager.ts

This has been fixed in the past for the workspace. Now it's been an issue on the capsules.
When running `Promise.all` of `npm install` on multiple capsules, it fails randomly.
The reason is that capsules are connected to each other by the file paths in their `dependencies` prop of the package.json. As a result, npm ends up running on the same directory with multiple instances and depends on the exact point when it happens it can fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2569)

avoid running multiple instances of npm & yarn in parallel

---

e2e/harmony/compile.e2e.4.ts
src/constants.ts
src/consumer/component/consumer-component.ts
src/consumer/config/component-config.ts
src/consumer/config/extension-data.ts
src/e2e-helper/e2e-bit-jsonc-helper.ts
src/e2e-helper/e2e-scope-helper.ts
src/scope/models/model-component.ts

- makes sure the extension's objects are imported.
- prevent showing an imported component with extensions as modified.
- load the extensions data from the model if not exists on the file-system.
- add an e2e-test to verify that `bit compile` works on an imported component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2580)

make extensions work on imported components

---

src/scope/objects/repository.ts

Currently, it's hard to find errors happening during the parse phase of a BitObject.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2579)

avoid suppressing errors of BitObject.parse()

---

CHANGELOG.md
fixtures/jsdoc/react/react-docs.js
src/jsdoc/extract-data-regex.ts
src/jsdoc/react/react-parser.spec.ts
src/jsdoc/react/react-parser.ts

Fixes #2512 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2577)

Fix react-docs to preserve spaces/tabs of @example

---

e2e/harmony/extensions-config.e2e.3.ts
src/consumer/component-ops/load-flattened-dependencies.ts
src/consumer/component/component-loader.ts
src/consumer/component/consumer-component.ts
src/consumer/component/package-json-utils.ts
src/consumer/config/extension-data.ts
src/extensions/isolator/write-components-to-capsules.ts
src/scope/component-dependencies.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/component-ops/tag-model-component.ts
src/scope/graph/components-graph.ts
src/scope/graph/graph.ts
src/scope/graph/scope-graph.ts
src/scope/models/version.ts
src/scope/version-dependencies.ts

- remove extension ids from the model devDependencies. (it was implemented this way as a temporary solution. Now it's implemented the correct way).
- throw a descriptive error when tagging/exporting a component without its extension. 
- write extension dependencies into package.json as devDependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2590)

Remove extensions from devDependencies

---

CHANGELOG.md
e2e/commands/export.e2e.1.ts
e2e/commands/import.e2e.1.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/scope.ts

Fixes https://github.com/teambit/bit/pull/2591.
See my last comment in the issue above for more info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2591)

Fix parsing bit-id from scope to get the correct scope name

---

e2e/commands/import.e2e.1.ts
e2e/interactive/init.interactive.e2e.3.ts

This is related to a refactor we have done a while ago to remove all tests related to bit.dev and replace them with local tests. One test seemed to be forgotten and it's fixed here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2607)

fix an e2e-test to not interact with "bit.dev"

---

e2e/api/add-many.e2e.1.ts
src/consumer/component-ops/component-writer.ts
src/consumer/component-ops/many-components-writer.ts
src/consumer/component/package-json-file.ts
src/consumer/component/package-json-utils.ts
src/extensions/isolator/isolator.ts
src/extensions/isolator/symlink-dependencies-to-capsules.ts
src/extensions/isolator/write-components-to-capsules.ts
src/extensions/package-manager/package-manager.ts

Currently, the package-manager installs them via the relative path but it fails on circular dependencies.
With this PR, the component dependencies are removed from the package-json before "npm install" and then they're back after the installation with versions (rather than relative-paths).
Also, the caching mechanism has improved in terms of readability, performance, and stability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2612)

Symlink dependencies to capsules 

---

src/consumer/component-ops/component-writer.ts
src/consumer/component-ops/many-components-writer.ts
src/consumer/component/package-json-utils.ts
src/extensions/create/create.ts
src/extensions/flows/flows.ts
src/extensions/isolator/capsule-list.ts
src/extensions/isolator/capsule-paths.ts
src/extensions/isolator/isolator.ts
src/extensions/isolator/symlink-dependencies-to-capsules.ts
src/extensions/isolator/write-components-to-capsules.ts

- change classes that inherit BitIdAndValueArray to be self-contained. It makes these classes more readable.
- delete the CapsulePaths class. (previously inherited BitIdAndValueArray and was needed when the package.json written in the capsule had the relative paths for other capsules. currently, the package.json doesn't have the relative paths but actual versions).
- delete TemplateFileVinyl class. Not needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2617)

Refactoring. Mostly related to BitIdAndValueArray class

---

src/consumer/component-ops/load-flattened-dependencies.ts

Happens when loading one component that has extensions (as opposed to loading all components from the workspace).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2618)

fix error "Cannot read property 'clone' of undefined"

---

src/consumer/component-ops/load-flattened-dependencies.ts
src/extensions/isolator/write-components-to-capsules.ts
src/scope/graph/components-graph.ts

Currently, when a graph is built using `buildOneGraphForComponents` method, it has only the flattened of dependencies but not the flattened of devDependencies and extensionDependencies.
In this PR, the missing dependencies are part of the graph and in case some deps are missing, it fails early with a descriptive error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2635)

fix graph built for capsules from the workspace to include indirect non-prod deps

---

src/extensions/bit/bit.manifest.ts
src/extensions/compile/compile.cmd.tsx
src/extensions/compile/compile.ts
src/extensions/component/component-factory.ts
src/extensions/component/component.provider.ts
src/extensions/component/component.ts
src/extensions/flows/cache.ts
src/extensions/flows/flow/flow.ts
src/extensions/flows/flows.ts
src/extensions/flows/index.ts
src/extensions/flows/network/network.ts
src/extensions/flows/run/run.cmd.tsx
src/extensions/flows/task/execution-stream.ts
src/extensions/flows/task/task.ts
src/extensions/flows/util/create-capsule.ts
src/extensions/flows/util/create-fake-network.ts
src/extensions/graph/component-graph/component-graph.ts
src/extensions/graph/index.ts
src/extensions/insights/all-insights/duplicate-dependencies.tsx
src/extensions/insights/insights.cmd.tsx
src/extensions/isolator/capsule/index.ts
src/extensions/isolator/index.ts
src/extensions/pack/pack.cmd.tsx
src/extensions/package-manager/package-manager.ts
src/extensions/paper/index.ts
src/extensions/test/index.ts
src/extensions/test/test.cmd.tsx
src/extensions/test/test.ts
src/extensions/workspace/resolved-component.ts

Makes sure that extensions expose all their APIs from the main `index.ts` file, so then no need to import their internals. (this is needed for the "bit link --rewire" that will be running later).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2636)

fix extensions to not use internal paths of other extensions

---

src/scope/models/version.ts
src/scope/version-validator.ts

Normally version-validator makes sure to not tag a Version that has the same dependency in prod-deps and dev-deps. 
This PR excludes extension-dependencies from this duplication check.
It's needed because a component may have another component as a dependency and also as an extension. Removing it from the extensions list will result in not finding the extension for the component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2640)

allow having the same dependency as a prod/dev dependency and as an extension dependency

---

src/consumer/component/sources/data-to-persist.ts
src/consumer/component/sources/source-file.ts
src/extensions/cli/legacy-command.tsx
src/extensions/flows/flows.ts
src/extensions/logger/logger.ts
src/extensions/paper/index.ts
src/extensions/reporter/logger.ts
src/extensions/scope/scope.ts
src/extensions/workspace/core-configurable-extensions.ts
src/extensions/workspace/workspace.ts
src/scope/scope.ts

As part of the dogfooding process, in `harmony/dogfooding` branch all extensions are components and compiled with "bit compile". Some errors are thrown from `tsc` that are not shown in the linter of bit-bin workspace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2641)

fix some more tsc errors thrown during "bit compile" of core extensions

---

e2e/harmony/compile.e2e.4.ts
src/extensions/flows/flow/flow.ts
src/extensions/flows/flows.ts
src/extensions/flows/network/network.ts
src/extensions/flows/task/execution-stream.ts

Flows exited the process with a success code during processing the flows/tasks. 
This happened when the workspace had two components, one with no tasks and one with a task that ended up with an error.
This PR includes lots of logger statements to easier the debugging process of Flows.
@qballer , please, leave them there until Flows is simplified. As of now, debugging it is time-consuming and the loggers help a lot.
The most important part of this fix is:
```
if (seederAmount === 0) {
walk();
}
```
Inside `subscribe.error`. 
@qballer , although this fixed my issue. I'm still not sure why RxJS would exit the process.
You can easily debug the issue by uncommenting the lines above and running the test 'add another component that does not need any compilation' inside compile.e2e file.
---
This …

Fix flows to not exit the process unexpectedly

---

scripts/build-types.bash
tsconfig.types.json

This script used to emit also .js files, as a result, after running this script, "bit" wasn't working anymore.
This PR changes the tsconfig.json of this script to emit only "d.ts" files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2647)

fix built-types script to not override dists files 

---

src/bit-id/bit-ids.ts
src/scope/component-ops/get-flattened-dependencies.ts

Currently, they might be duplicate. e.g. `test` component has `compile` as a dependency and also as an extension dependency, it shows twice, once in flattenedDependencies and also in flattenedDevDependencies.
This PR removes the duplicated ids.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2649)

remove flattened extension dependencies that are also flattened dependencies

---

src/extensions/compile/compile.ts
src/scope/repositories/sources.ts

This is needed for the dogfooding branch when the core-extensions are components and the name of the compile extension is changed to have the full name including the scope name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2662)

Fix compile to work with the full-name "bit.core/compile"

---

src/extensions/package-manager/package-manager.ts

to work when the extensions are loaded from node_modules
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2663)

fix symlinks between bit-bin and capsules 

---

src/utils/bit/component-id-to-package-name.ts

@GiladShoham , I'm not sure this is how you expected it to be. 
Please let me know if It's needed to be changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2664)

avoid applying the owner-as-prefix strategy when the user is "bit"

---

src/extensions/workspace-config/workspace-config.ts

if missing from the dist.  (happens when the compiler is tsc and not babel).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2665)

support coping the bit.jsonc template from the src dir 

---

src/extensions/flows/util/sort-graph-by-levels.ts

It turns out, typescript knows to handle circulars in the majority of the cases (typescript compiler was the main reason for sorting the components before compiling them).
Later, @qballer , will figure out whether the default should be toposort or not and what flags would be used to choose one or another.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/teambit/bit/2668)

Fallback to not topological sort when a graph has circular dependencies

---

e2e/fixtures/extensions/gulp-ts/gulp-ts.manifest.js
e2e/harmony/compile.e2e.4.ts
src/e2e-helper/e2e-fixtures-helper.ts
src/extensions/compile/README.md
src/extensions/compile/compile.provider.ts
src/extensions/compile/compile.ts
src/extensions/flows/index.ts
src/extensions/flows/task/task.ts
src/extensions/typescript/typescript.manifest.js

This is one of the tasks in https://github.com/teambit/bit/issues/2523.

add api to get the task-file from the compiler extension

---

src/consumer/component/consumer-component.ts

Available through the second parameter `context.componentRootDir`.
This is needed for testers to save artifacts into the component's dir. For example, it helps Jest tester to save the screenshots files.

add componentRootDir to the tester API

---

e2e/commands/watch.e2e.2.ts
src/extensions/compile/compile.ts
src/extensions/watch/watch.ts

see #2677.
It is not needed anymore because the compilation during development is happening on the workspace.

Remove the new multiple-watch

---

src/consumer/component/dependencies/files-dependency-builder/filing-cabinet/index.spec.ts

Before, when running the unit-tests on node versions such as v12.17.x or v14, it'd just exit the process without any error.
At some point, we'll need to fix this, probably by removing the mock-fs altogether from the unit tests.

show a descriptive error when unit-tests fail to load requirejs package on some node versions

---

e2e/harmony/compile.e2e.4.ts
src/consumer/component-ops/component-writer.ts
src/consumer/consumer.ts
src/links/node-modules-linker.ts

of the component instead of the component-dir. (for Harmony only).
This way, the files' structure of imported and authored are the same.

Write the package.json of imported components on he node_modules

---

.circleci/config.yml

The long term support of node 8 was terminated by the end of last year (2019).
Continue supporting node 8 prevent us from installing Prettier 2, which in turn, prevents some babel packages to be installed, which in turn, prevents using `import type` syntax of TS, and future features of TS.

support node 10 (drop support of node 8)

---

src/extensions/typescript/typescript.compiler.ts

* format typescript errors nicely when they are not related to any component
* remove the colors from the errors when it is not TTY

Fix typescript compiler error formatting

---

src/cli/command.ts
src/extensions/builder/run.cmd.tsx
src/extensions/compiler/compiler.cmd.tsx
src/extensions/create/create.cmd.tsx
src/extensions/insights/insights.cmd.tsx
src/extensions/isolator/capsule-create.cmd.tsx
src/extensions/pkg/pack.cmd.tsx
src/extensions/tester/test.cmd.tsx
src/extensions/ui/start.cmd.tsx
src/extensions/watch/watch.cmd.tsx

Currently, the only type they accept is the generic `CLIArgs` and `Flags`.
Also, replace the args and flags of new commands with the concrete types.

enable new commands to declare the args and flags types

---

e2e/commands/_scope.e2e.1.ts
src/cli/command-runner.ts
src/cli/command.ts
src/cli/commands/private-cmds/_delete-cmd.ts
src/cli/commands/private-cmds/_deprecate-cmd.ts
src/cli/commands/private-cmds/_fetch-cmd.ts
src/cli/commands/private-cmds/_graph-cmd.ts
src/cli/commands/private-cmds/_latest-cmd.ts
src/cli/commands/private-cmds/_list-cmd.ts
src/cli/commands/private-cmds/_log-cmd.ts
src/cli/commands/private-cmds/_put-cmd.ts
src/cli/commands/private-cmds/_scope-cmd.ts
src/cli/commands/private-cmds/_search-cmd.ts
src/cli/commands/private-cmds/_show-cmd.ts
src/cli/commands/private-cmds/_undeprecate-cmd.ts
src/cli/commands/private-cmds/ci-update-cmd.ts
src/cli/legacy-command.ts
src/extensions/cli/commands/help.cmd.tsx
src/extensions/cli/legacy-command-adapter.ts

Currently, the "private" prop used for two different things: 
1. indicating that a command should not be shown in help.
2. making sure to serialize the error if it throws.
Now, "private" is responsible for # 1. "internal" is responsible for # 2.

add a new prop "internal" to Command and LegacyCommand interfaces 

---

src/cli/command-runner.ts
src/cli/default-error-handler.ts
src/consumer/component-ops/eject-components.ts
src/e2e-helper/e2e-general-helper.ts
src/extensions/cli/exceptions/already-exists.tsx
src/extensions/cli/exceptions/command-not-found.tsx
src/extensions/cli/exceptions/paper-error.tsx
src/extensions/config/exceptions/invalid-config-file.tsx
src/extensions/insights/exceptions/insight-already-exists.tsx
src/extensions/insights/exceptions/insight-not-found.tsx
src/extensions/insights/exceptions/no-data-for-insight.tsx
src/extensions/pkg/exceptions/scope-not-found.tsx
src/logger/logger.ts

No need to render React component when throwing an error. It's easier to work with strings.

change PaperError to not render React component

---

src/cli/command-runner.ts
src/extensions/logger/logger.ts
src/extensions/reporter/reporter.ts

Also, remove the duplicated render() call.

write to legacy logger when calling Harmony logger

---

CHANGELOG.md
e2e/commands/export.e2e.1.ts
src/scope/component-ops/export-scope-components.ts
src/utils/string/replace-package-name.spec.ts

Currently, in some cases, when comp-a requires comp-b and comp-b was exported to scope-b and the user is now exporting comp-a to scope-a, the following happens:
1. if it's the first export for comp-a, it shows an error suggesting to use `--rewire` incorrectly.
2. if it's not the first export, it replaces the dists require/import statement incorrectly to the scope-a. Although the `--rewire` flag was not used.

fix export of component with dependency of another scope

---

e2e/flows/dependencies-versions-resolution.e2e.2.ts
e2e/harmony/publish.e2e.4.ts
src/consumer/component-ops/dependency-status.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-versions-resolver.ts
src/consumer/component/dependencies/files-dependency-builder/build-tree.spec.ts
src/consumer/component/dependencies/files-dependency-builder/build-tree.ts
src/consumer/component/dependencies/files-dependency-builder/group-missing.ts
src/consumer/component/dependencies/files-dependency-builder/index.ts
src/consumer/component/dependencies/files-dependency-builder/types/dependency-tree-type.ts
src/consumer/config/component-overrides.ts
src/utils/packages/index.ts
src/utils/packages/resolve-pkg-data.ts
src/utils/packages/resolve-pkg-name-by-path.ts
src/utils/packages/resolve-pkg-path.ts

Extract it to a new file and makes it clearer.
Also, add an e2e-test to make sure we get the component-id from build-tree.

refactor the group missing packages/components logic

---

e2e/commands/status.e2e.2.ts
e2e/flows/dependencies-as-packages.e2e.2.ts
src/consumer/component/dependencies/files-dependency-builder/group-missing.ts

require the package.json of the package to make sure whether it is a component or a package

avoid resolving package data from the main package.json

---

CHANGELOG.md
src/scope/component-ops/tag-model-component.ts

fix legacy compilers that use component.extensions to be build upon tag

---

src/consumer/component-ops/component-writer.ts
src/consumer/component-ops/many-components-writer.ts
src/consumer/component/package-json-utils.ts
src/environment/environment.ts
src/environment/isolator.ts
src/extensions/isolator/isolator.extension.ts
src/extensions/isolator/symlink-dependencies-to-capsules.ts
src/extensions/isolator/write-components-to-capsules.ts

create capsules only for workspace dependencies and npm-install the rest.

fix tagging Harmony components that have legacy dependencies

---

CHANGELOG.md
src/environment/isolator.ts

Fixes #2809 .
This is happening due to some changes in the `capsule.exec` method. Specifically, the command `npm list -j` was hanging when NPM throws the peer-dependencies errors.
Fixed by changing to `execa`.

Fix legacy capsule exec to not hang on error

---

CHANGELOG.md
src/bit-id/bit-ids.ts
src/consumer/component/components-list.ts
src/scope/component-ops/export-scope-components.ts

The `--all` flag caused the ids to get into the export process with versions.
The `--include-dependencies` adds to the ids all dependencies ids.
As a result, even though the duplications were removed before pushing the ids to the remote, these duplications were Versions aware, so for example "scope/component@0.0.1" and "scope/component" were not considered duplications.
The fix in this PR is to make sure the `--all` flag gets the ids without version.
Also, a preventive measurement was taken to avoid sending duplications to the remote.

fix export --all --include-dependencies flags to not duplicate components

---

babel.config.js
package.json
src/api.ts
src/app.ts

Make use of Babel's `preset-env` to automatically inject all required polyfills.
as described in Babel's docs:
> ### useBuiltIns: 'usage'
> Adds specific imports for polyfills when they are used in each file. We take advantage of the fact that a bundler will load the same polyfill only once.
We can also use `useBuiltIns: entry`, which will replace `import 'core-js'` with relevant polyfills.
Tested and working with `harmony/workspace` branch, after `rm -rf node_modules dist`

automatic polyfill

---

e2e/performance/many-components.performance.ts
package-lock.json
src/api/consumer/lib/export.ts
src/app.ts
src/cli/command-runner.ts
src/consumer/component-ops/component-status-loader.ts
src/consumer/component-ops/import-components.ts
src/consumer/component/component-loader.ts
src/consumer/component/components-list.ts
src/consumer/component/consumer-component.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/consumer.ts
src/logger/logger.ts

* resolve performance regression by fixing the dependency resolution cache.
* show the entire stack trace formatted on error when setting the "BIT_LOG" environment variable.
* fix the logger to wait until all logs are written on export.
* avoid loading multiple components in parallel to keep the memory usage low.
* disable the `longStackTraces` by default, unless either BLUEBIRD_DEBUG or BIT_LOG is set.
* fix errors to be written to the log formatted with line breaks

fix performance regression

---

e2e/harmony/dependency-resolver.e2e.ts
src/consumer/component-ops/codemod-components.ts
src/consumer/component-ops/component-writer.ts
src/consumer/component-ops/eject-components.ts
src/consumer/component/consumer-component.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-versions-resolver.ts
src/consumer/component/dependencies/files-dependency-builder/build-tree.ts
src/consumer/component/dependencies/files-dependency-builder/missing-handler.ts
src/consumer/component/package-json-file.ts
src/consumer/component/package-json-utils.ts
src/consumer/component/package-json.ts
src/consumer/consumer.ts
src/environment/isolator.ts
src/extensions/compiler/compile.ts
src/extensions/isolator/isolator.extension.ts
src/extensions/isolator/symlink-dependencies-to-capsules.ts
src/extensions/workspace/utils.ts
src/links/dependency-file-link-generator.spec.ts
src/links/dependency-file-link-generator.ts
src/links/link-generator.ts
src/links/linker.ts
src/links/node-modules-linker.ts
src/scope/component-ops/export-scope-components.ts
src/utils/bit/component-id-to-package-name.ts
src/utils/bit/component-node-modules-path.ts
src/utils/bit/component-placeholders.ts
src/utils/packages/resolve-pkg-data.ts

Currently, the package name is calculated based on the id with no options to change/add anything.
This PR provides full support of having the package-name different than the component-id. 
The implementation of this feature itself was done previously, this is more about fixing all occurrences that convert bit-id to package name so it could actually work.

support custom package name

---

src/consumer/component-ops/codemod-components.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

Currently, when relative-path points to an internal file of another component, the `bit link --rewire` replace it with the link to the package without the internal file part. 
This PR finds the internal file and preserves it.

improve bit link --rewire to preserve internal paths

---

package.json
src/extensions/changelog/changelog.section.tsx
src/extensions/component/component.ui.tsx
src/extensions/component/section/section.tsx
src/extensions/component/ui/top-bar-nav/top-bar-nav.tsx
src/extensions/component/ui/top-bar-widget-link/top-bar-widget-link.tsx
src/extensions/component/ui/top-bar/top-bar.tsx
src/extensions/compositions/composition.section.tsx
src/extensions/docs/overview.section.tsx
src/extensions/react-router/extend-path/index.ts
src/extensions/react-router/link/index.ts
src/extensions/react-router/link/link.tsx
src/extensions/react-router/nav-link/index.ts
src/extensions/react-router/nav-link/nav-link.tsx
src/extensions/react-router/slot-router.tsx
src/extensions/stage-components/side-bar/component-tree/component-view/component-view.tsx

- Wrap react router's Link and NavLink
- Specifically, use `href` instead of `to`, to align with browser standard `<a/>` tag and reduce coupling with react-router-dom
- Add `external` flag from bit.dev

[WIP] wrap react router links with local links

---

src/api/consumer/lib/status.ts
src/cli/commands/public-cmds/status-cmd.ts
src/consumer/component/components-list.ts

On Harmony, only directories can be added not individual files. This makes sure to show a warning on "bit status" when migrating from legacy to Harmony and components have individual files.

on harmony warn about components without rootDir/trackDir in bit-status

---

e2e/commands/move.e2e.1.ts
src/cli/commands/public-cmds/move-cmd.ts
src/consumer/component-ops/move-components.ts

Previously, it was moving the files correctly but the records in .bitmap were off.

fix bit move --component when running from an inner dir

---

src/api/consumer/lib/feature-toggle.ts
src/api/consumer/lib/migrate.ts
src/cli/commands/private-cmds/migrate-cmd.ts
src/cli/commands/public-cmds/init-cmd.ts
src/cli/commands/public-cmds/status-cmd.ts
src/consumer/migrations/harmony-migrator.ts
src/extensions/config/workspace-config.ts

For now, this flag does the following:
* converts `trackDir` to `rootDir` in .bitmap file and changes the file paths accordingly.
* shows the list of the components that need to be fixed in regards to the individual-files issue.
* suggest how to re-init an existing workspace as Harmony.
Also, fix "bit init" with Harmony feature set and no legacy data to init as Harmony.

introduce "--harmony" flag for "bit migrate" 

---

src/extensions/builder/builder.service.ts
src/extensions/isolator/isolator.extension.ts
src/extensions/workspace/capsule-create.cmd.ts
src/extensions/workspace/workspace.ts

* add an option to specify package-manager in the create-capsule command.
* add types for `createNetwork` and `isolateComponents` methods.

improve create-capsule command and add types for isolate-components-options

---

src/extensions/compiler/workspace-compiler.ts
src/extensions/workspace/on-component-change.ts
src/extensions/workspace/watch/watcher.ts
src/extensions/workspace/workspace.ts

Currently, both, legacy and new components are passing to the `onComponentChange` hook, which, later are passed to the `workspace.get` potentially causing issues when a legacy component doesn't have dir.

refactoring, separate the watch of legacy components from the onComponentChange hook

---

e2e/harmony/publish.e2e.4.ts
src/extensions/builder/build-pipe.ts
src/extensions/builder/builder.extension.ts
src/extensions/builder/builder.service.ts
src/extensions/builder/run.cmd.tsx
src/extensions/dependency-resolver/package-manager.ts
src/extensions/logger/README.md
src/extensions/logger/logger.ts
src/extensions/logger/long-process-logger.ts
src/extensions/reporter/reporter.ts
src/extensions/reporter/status-line.ts
src/extensions/types/log-publisher.ts
src/extensions/workspace/workspace.ts

* log long processes effectively. 
* show them in the status line using the reporter
To log a long process, declare that you start a long-process-logger and give it the number of items. Then, as you continue, you will let this object know what is the current processing item. That's it.
The logger does the following for you:
* It logs everything to the logger with the extension-id and the current progress. (a big improvement from the legacy-logger that there was no progress indication).
* It fires event "logProcess", which the reporter knows to catch and show the progress in the status line nicely.
* When completed it logs the time in ms of the process.

Infrastructure for logging long processes

---

e2e/commands/show.e2e.2.ts
e2e/functionalities/reduce-path.e2e.3.ts
e2e/harmony/relative-paths.e2e.3.ts
src/api/consumer/lib/status.ts
src/cli/commands/public-cmds/status-cmd.ts
src/cli/default-error-handler.ts
src/cli/templates/component-issues-template.ts
src/consumer/component/components-list.ts
src/consumer/component/consumer-component.ts
src/consumer/component/exceptions/no-component-dir.ts
src/consumer/migrations/harmony-migrator.ts
src/e2e-helper/e2e-command-helper.ts
src/e2e-helper/e2e-scope-helper.ts
src/extensions/workspace/workspace.ts

* show warning on bit-status when a component has trackDir in Harmony, suggest to run `bit migrate --harmony`.
* fix the error of no-component-dir to be caught on bit-status and show a descriptive message with suggestions on how to fix.

show warning on bit-status when a component has trackDir in Harmony

---

e2e/commands/show.e2e.2.ts
e2e/commands/tag.e2e.1.ts
src/cli/commands/public-cmds/show-cmd.ts
src/consumer/component/dependencies/files-dependency-builder/build-tree.ts
src/extensions/isolator/isolator.extension.ts
src/extensions/isolator/symlink-dependencies-to-capsules.ts
src/extensions/workspace/capsule-list.cmd.ts
src/extensions/workspace/workspace.provider.ts
src/links/node-modules-linker.ts
src/utils/packages/resolve-pkg-data.ts

* On Harmony when exporting a component, the package.json for authored was changed to include the version. However, when tagging later, that version wasn't changed. 
As a result, the dependency-version-resolution was using the wrong version on the package.json.
This was fixed by removing the version field altogether, so then no need to maintain it.
* improve the capsule-list command to show the rootDir of the capsules.
* fix bit show --json to show the artifacts as strings and not as buffers.

fix ComponentNotFound when tagging after export for author

---

src/extensions/logger/README.md
src/logger/logger.ts

currently, when the logger is printed to the console, the second parameter is ignored. this makes sure to print it in case it's an object, similar to file printing.

print the second parameter passed to the logger to the console

---

e2e/harmony/migrate.e2e.ts
src/api/consumer/lib/init.ts
src/api/consumer/lib/migrate.ts
src/consumer/config/workspace-config.ts
src/consumer/consumer.ts
src/consumer/migrations/harmony-migrator.ts

Currently, the `.bitmap` file must be deleted and the legacy configuration files must be removed in order to init the workspace as Harmony.
This is fixed to let `bit migrate --harmony` backup the configuration files and init harmony while keeping the .bitmap file.

enable init legacy workspace as Harmony using bit migrate command

---

e2e/harmony/publish.e2e.4.ts
src/extensions/builder/builder.extension.ts
src/extensions/builder/run.cmd.tsx
src/extensions/cli/cli.extension.ts
src/extensions/compiler/README.md
src/extensions/environments/README.md
src/extensions/tester/test.cmd.tsx
src/extensions/tester/tester.extension.ts

These commands: build and test are used in the legacy workspace differently.
This PR makes sure that on Harmony the old commands are unregistered and the new are registered.

on harmony: "bit run" => "bit build". "bit test-new" => "bit test"

---

src/consumer/component-ops/load-flattened-dependencies.ts
src/environment/isolator.ts
src/scope/graph/components-graph.ts

Huge performance improvement when loading bit-bin extensions as components. (from 15 minutes to 30 seconds).
The mechanism of the loading the flattened dependencies was inefficient and repetitive. Improve it by caching the results.

improve performance of flattened-dependency-loader dramatically

---

src/cli/loader/loader.ts

This happened probably due to the proxies of process.stdout in the loader. It was part of the old Reporter and probably is not needed anymore.
In a quick test, running `bit build` and stopping it with Ctrl+C multiple times, it seems to fix the issue.

fix terminal stdout to not be taken by bit-bin

---

package-lock.json
package.json
src/extensions/dependency-resolver/dependency-installer.ts
src/extensions/dependency-resolver/manifest/deduping/dedupe-dependencies.ts
src/extensions/dependency-resolver/manifest/deduping/hoist-dependencies.ts
src/extensions/dependency-resolver/manifest/deduping/index.ts
src/extensions/dependency-resolver/manifest/workspace-manifest.ts
src/extensions/dependency-resolver/package-manager.ts
src/extensions/isolator/isolator.extension.ts
src/extensions/pnpm/pnpm.package-manager.ts
src/extensions/workspace/install.cmd.tsx
src/extensions/workspace/workspace.ts

- add an option to not deduping when installing dependencies
- do not dedupe when installing dependencies on capsules by default
- when no deduping installing the peer dependencies in the subdirectories

Skip dedupe dependencies

---

scripts/dogfooding.sh
src/consumer/component/package-json-file.ts
src/extensions/builder/task-process.ts
src/extensions/compiler/compiler.extension.ts
src/extensions/isolator/capsule/capsule.ts
src/extensions/pkg/pkg.extension.ts
src/extensions/pkg/prepare-packages.task.ts
src/extensions/pnpm/pnpm.package-manager.ts
src/extensions/stencil/stencil.extension.ts
src/extensions/typescript/typescript.extension.ts
src/extensions/webpack/webpack.extension.ts
workspace.jsonc

To support components that import from internal paths of other components, we need to copy the dist files into the capsule root.  See this [repo](https://github.com/davidfirst/typescript-internal-paths-monorepo) for more info.

add a task to copy dists to the capsule root to support importing from internal paths

---

e2e/harmony/dependency-resolver.e2e.ts
scripts/dogfooding.sh
src/app.ts
src/bootstrap.ts
src/extensions/cli/app.ts
src/extensions/dependency-resolver/manifest/manifest.ts
src/extensions/dependency-resolver/manifest/workspace-manifest.ts
src/extensions/isolator/isolator.extension.ts
src/extensions/pnpm/pnpm.package-manager.ts
src/extensions/react/react.env.ts
src/extensions/typescript/typescript.compiler.ts
workspace.jsonc

* add app.ts to the cli extension to be able to bootstrap bit-bin from there.
* avoid duplicating dependencies into peerDependencies when installing packages using the pnpm api.
* fix capsules to install peerDependencies
* delete tsBuildInfo files after compiling on capsules (file needed for `tsc --build` but should not be part of the package).
* add missing peerPackages to dependency-resolver policy.

fix capsules installation and enable running bit-bin from CLI extension

---

extensions/bit/bit.provider.ts
extensions/bit/manifests.ts
extensions/dependency-resolver/dependency-resolver.main.runtime.ts
extensions/pkg/publisher.ts
extensions/tester/utils/detect-spec-files.ts
extensions/workspace/workspace.provider.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

- use resolved legacy ids for extensions on components
- remove core extensions from unidentified packages
- add used core aspects to dependency resolver extension data

Extensions ids legacy

---

extensions/react/component.json
extensions/ui/component.json
extensions/workspace/workspace.ts

even when it has overrides in workspace.jsonc or component.json file.
@GiladShoham , see the commit. I commented-out your code.
The problem is that when I tag the bit-bin extensions and then load the extensions, the data from the model is gone. This is because they have override data in the workspace.jsonc. (some also have their own component.json file).
We need to figure out how to tackle this. For example, the "compiler" extension is not set in the workspace.jsonc, so we do want to merge its data (the artifacts = dists) from the scope.
Please let me know if you have a suggestion. I'll be merging this for now, so we could publish bit-bin.

temporarily change loading components from scope to merge the data from the model 

---

src/bootstrap.ts

Currently, `bit --version` shows the bit-bin version, it's useful to see the version of `@teambit/bit` as well.

add Harmony version on "bit --version"

---

src/logger/logger.ts

Currently, when passing the error as the second parameter to the `logger`, it gets JSON serialized, which makes it hard to understand the stack.

format the stack nicely when using --log flag

---

src/consumer/component-ops/dependency-status.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/component/dependencies/files-dependency-builder/build-tree.spec.ts
src/consumer/component/dependencies/files-dependency-builder/build-tree.ts
src/consumer/component/dependencies/files-dependency-builder/generate-tree-madge.ts
src/consumer/component/dependencies/files-dependency-builder/missing-handler.ts
src/consumer/component/dependencies/files-dependency-builder/types/dependency-tree-type.ts
src/utils/packages/resolve-pkg-name-by-path.ts
workspace.jsonc

on Harmony use only package.json `componentID` prop to determine whether a dependency is a package or a component.

fix bindingPrefix issues

---

extensions/workspace/workspace.ts
src/bit-id/bit-ids.spec.ts
src/bit-id/bit-ids.ts
src/consumer/component-ops/load-flattened-dependencies.ts
src/consumer/component/dependencies/dependencies.ts

- new difference api for bitIds class
- new getIdsMap api on dependencies class
- filter ignore ids on load flattened dependencies prior to the actual loading
- filter components which are not aspects of the aspects we try to load

Aspect graph loading

---

e2e/commands/snap.e2e.2.ts
e2e/commands/tag.e2e.1.ts
e2e/functionalities/auto-tagging.e2e.2.ts
e2e/functionalities/workspace-config.e2e.3.ts
extensions/workspace/workspace.ts
src/api/consumer/lib/status.ts
src/cli/commands/public-cmds/merge-cmd.ts
src/cli/commands/public-cmds/snap-cmd.ts
src/cli/commands/public-cmds/tag-cmd.ts
src/consumer/component/components-list.ts
src/consumer/consumer.ts
src/scope/component-ops/auto-tag.spec.ts
src/scope/component-ops/auto-tag.ts
src/scope/component-ops/tag-model-component.ts
src/scope/graph/components-graph.ts
src/scope/graph/scope-graph.ts

To understand why this is needed, consider the following case:
comp1 depends on comp2. The user has modified comp2 and tagged comp2. During the tag of comp2, we find that comp1 is a dependent and we auto-tag it as well.
The way how we do auto-tag is as follows: we load comp1 from the model (not workspace), change only the dependency version of comp2, and tag/snap.
On Harmony, after changing the dependencies of comp1, we run the OnTag hook, which runs the build-pipeline. During the build pipeline, we load all components from the workspace, including this auto-tag candidate "comp1". The problem is that the component from the workspace has the old dependency version of comp2, because only the model component of comp1 got updated.
To resolve this issue, this PR simplifies the super complex …

simplify auto-tag process to behave the same as tag

---

extensions/workspace/watch/watcher.ts

when multiple components have the same prefix.
For example, when .bitmap had two components 'bar/foo' and 'bar/foo2', the file on 'bar/foo2' was associated incorrectly to 'bar/foo'.

fix watcher to find the correct component-id

---

extensions/aspect/aspect.main.runtime.ts
extensions/builder/builder.main.runtime.ts
extensions/builder/builder.service.ts
extensions/environments/README.md
extensions/pkg/pkg.main.runtime.ts
extensions/pkg/publisher.ts
extensions/preview/preview.main.runtime.ts
extensions/react/react.env.ts
extensions/react/react.main.runtime.ts
extensions/stencil/stencil.env.ts

Currently, the build-pipe does the deployment as well in case of bit-tag.
One issue with this behavior is that when a later env fails, the current env is published unexpectedly.
This makes sure to publish only once all build-pipe has completed successfully.

implement deploy pipe to be running after the build pipe

---

extensions/builder/storage/default-resolver.ts
extensions/component/aspect-entry.ts

Happened as a result of the `Artifacts` class leaking into the UI.

fix out-of-memory during preview

---

e2e/fixtures/extensions/babel-env/babel-env.extension.ts
e2e/fixtures/extensions/multiple-compilers-env/multiple-compilers-env.extension.ts
extensions/aspect/core-exporter.task.ts
extensions/babel/babel.compiler.ts
extensions/babel/babel.main.runtime.ts
extensions/builder/artifact/artifact-list.ts
extensions/builder/artifact/artifact.ts
extensions/builder/build-pipe.ts
extensions/builder/build-pipeline-result-list.ts
extensions/builder/build-task.ts
extensions/compiler/README.md
extensions/compiler/compiler.main.runtime.ts
extensions/compiler/compiler.task.ts
extensions/compiler/types.ts
extensions/pkg/prepare-packages.task.ts
extensions/pkg/publish-dry-run.task.ts
extensions/pkg/publish.task.ts
extensions/preview/preview.task.ts
extensions/react/react.env.ts
extensions/react/react.main.runtime.ts
extensions/stencil/stencil.env.ts
extensions/tester/tester.task.ts
extensions/typescript/typescript.compiler.ts

- change task.id to task.aspectId
- make `task.name` mandatory. otherwise, there is no way to distinguish between "babel" and "typescript" tasks as they're both have `aspectId` of "tambit.bit/compiler".
- remove `compiler.task` prop. instead, use `compiler.createTask()` to create a new task.
- add a new React-env API `overrideCompilerTasks` to easily override only the compiler tasks in the buildPipe and leave other tasks intact.
- add a sugar syntax `createTask` to a specific compiler (e.g. babel/typescript).

change task.id to task.aspectId, make task.name mandatory

---

extensions/babel/README.md
extensions/babel/babel.compiler.ts

To avoid confusion and make sure that components are isolated from different babel config on the machine, the `babelrc` prop is set to false in the babel compiler.

babel-compiler, avoid searching for .babelrc files

---

scopes/compilers/babel/babel.compiler.ts

This has been fixed before for compiling on the capsule, this PR fixed the same for the workspace.
Before the fix, Babel would propagate to various config files on the machine and use them unexpectedly.

fix compiling on the workspace using Babel to ignore Babel config files

---

babel.config.js
package.json
scopes/harmony/aspect/babel/babel-config.ts
scopes/react/react/jest/transformer.js
workspace.jsonc

It was needed in the past to support old node versions. Now that we support node 10+, the async/await syntax is backed in.

remove @babel/plugin-transform-async-to-generator plugin

---

e2e/commands/import-all.e2e.1.ts
src/consumer/component-ops/import-components.ts

Currently, if a component was exported and then tagged locally, `bit import` throws component-not-found. 
It happens because Bit searches for this local tag in the remote and unable to find it. This PR changes the version to be "latest" before searching in the remote.

fix component-not-found upon bit-import (no id) with staged components

---

src/consumer/component-ops/many-components-writer.ts

This fixes the randomly failed e2e-test of bit-snap.

fix import on Harmony to wait for the install() promise

---

e2e/commands/export.e2e.1.ts
src/scope/component-ops/export-scope-components.ts
src/scope/objects/object-list.ts
src/scope/repositories/sources.ts

There are two issues currently when exporting components to different scopes.
1. a bug. when the components are new and have different `defaultScope`, it changes the dependencies scope to the component scope unexpectedly. 
2. by design. when there is a circular dependency between the components from different scopes, it throws an error that the toposort failed and that is unable to export.
This PR fixes both issues.
To enable circulars, it sends the dependencies along with the components. So then scopeA doesn't need to go to scopeB to import the dependencies, it gets them from the client already.
It introduces a new issue. What if after exporting to scopeA, scopeB fails. Then, scopeA has a component that its dependencies don't exist. We'll fix this issue in the next phase of this task.

enable export to multiple scopes even when components have circular dependencies

---

scopes/react/react/jest/transformer.js

Because the Jest transformer doesn't require the package directly but uses `require.resolve`, it needs to be specified in the workspace.json/component.json file.
Currently, `babel-preset-jest` is configured in the global workspace.jsonc and not specifically on the react aspect. As a result, locally, it finds the package, but globally, it does not.
In this PR, all `require.resolve` were changed to `require`, so then Bit dependency resolution would find them and automatically add them as dependencies.

fix error Cannot find module "babel-preset-jest" when bit is installed globally

---

e2e/commands/export.e2e.1.ts
src/links/node-modules-linker.ts

Currently, on export, the node-modules/pkg-name dir is deleted. It was needed for the legacy, but in Harmony it causes the dists files to be deleted and leaves the workspace in a problematic state. 
This makes sure to delete only for legacy workspaces.

fix bit-export to not delete the node-modules content on Harmony

---

scopes/pipelines/builder/builder.main.runtime.ts
scopes/scope/scope/scope.main.runtime.ts
src/api/consumer/lib/tag.ts
src/cli/commands/public-cmds/tag-cmd.ts
src/consumer/consumer.ts
src/scope/component-ops/tag-model-component.ts
src/scope/scope.ts

This way it'll be possible to run "bit tag" without publishing the components.
Also, refactor the tag parameters to avoid passing the same params multiple times.

introduce a new flag "--disable-deploy-pipeline" for bit tag

---

scopes/harmony/aspect/aspect.main.runtime.ts
scopes/pipelines/builder/build-pipeline-order.ts
scopes/pipelines/builder/builder.main.runtime.ts
scopes/pkg/pkg/pkg.main.runtime.ts
scopes/preview/preview/preview.main.runtime.ts
scopes/react/react/react.env.ts

No reason for every env to configure them. They're core tasks that should be running on all components regardless of the env.

move dry-run and prepare-publish tasks from the build-pipeline to slots

---

e2e/commands/lane.e2e.1.ts
e2e/commands/snap.e2e.2.ts
scopes/scope/scope/export/export-cmd.ts
src/api/consumer/lib/export.ts
src/api/consumer/lib/feature-toggle.ts
src/api/consumer/lib/fetch.ts
src/api/consumer/lib/import.ts
src/api/consumer/lib/lane.ts
src/api/consumer/lib/merge.ts
src/api/consumer/lib/remove.ts
src/api/consumer/lib/snap.ts
src/api/consumer/lib/switch.ts
src/cli/commands/public-cmds/fetch-cmd.ts
src/cli/commands/public-cmds/import-cmd.ts
src/cli/commands/public-cmds/lane-cmd.ts
src/cli/commands/public-cmds/merge-cmd.ts
src/cli/commands/public-cmds/remove-cmd.ts
src/cli/commands/public-cmds/snap-cmd.ts
src/cli/commands/public-cmds/switch-cmd.ts
src/cli/default-error-handler.ts
src/consumer/lanes/exceptions/lanes-is-disabled.ts
src/consumer/versions-ops/merge-version/merge-snaps.ts
src/scope/models/model-component.ts
src/scope/models/version.ts

Currently, a feature flag `lanes` is needed to enable snaps/lanes features.
This `lanes` feature-flag has been removed and it's enabled by default when the workspace is Harmony.

enable Lanes/Snaps features on Harmony workspace without a feature flag

---

.circleci/config.yml

It currently fails due to out-of-memory errors.

change Circle bit-build task to use resource:large

---

scopes/react/react/react.env.ts

Jest compiles the ts files using Babel and it needs the core-js package.

add core-js to react aspect dependencies, it is needed for Jest

---

scopes/compilation/babel/babel.compiler.ts
scopes/compilation/compiler/compiler.task.ts
scopes/component/isolator/network.ts
scopes/defender/tester/tester.task.ts
scopes/harmony/aspect/core-exporter.task.ts
scopes/pipelines/builder/artifact/artifact-factory.ts
scopes/pipelines/builder/build-task.ts
scopes/pipelines/builder/builder.main.runtime.ts
scopes/pipelines/builder/builder.service.tsx
scopes/pkg/pkg/prepare-packages.task.ts
scopes/pkg/pkg/publish-dry-run.task.ts
scopes/pkg/pkg/publish.task.ts
scopes/preview/preview/strategies/component-strategy.ts
scopes/preview/preview/strategies/env-strategy.ts
scopes/typescript/typescript/typescript.compiler.ts
scopes/workspace/workspace/capsule-create.cmd.ts
scopes/workspace/workspace/workspace.ts

Currently, it's confusing. It has `capsules` and `seedersCapsules`. 
- Changed `capsules` to `graphCapsules`. 
- Changed `seedersCapsules` to return `CapsuleList` (same as `graphCapsules`).
- Removed `components` prop. The components can be easily retrieved by the `getAllComponents` of `CapsuleList`.

change Network API to clearly differentiate between seeder-capsules and graph-capsules

---

e2e/harmony/http.e2e.ts
scopes/scope/scope/scope.graphql.ts
scopes/scope/scope/scope.main.runtime.ts
src/api/consumer/lib/get-component-logs.ts
src/cli/chalk-box.ts
src/cli/commands/public-cmds/log-cmd.ts
src/remotes/remote.ts
src/scope/models/model-component.ts
src/scope/network/fs/fs.ts
src/scope/network/http/http.ts
src/scope/network/network.ts
src/scope/network/ssh/ssh.ts
src/scope/scope.ts

- refactor log() methods to use an array instead of an object.
- implement `log` for HTTP protocol.

fix bit-log --remote on http

---

src/scope/network/exceptions/graphql-client-error.ts
src/scope/network/http/http.ts

Errors coming from the GraphQL are not clear. 
This PR shows the most important info from the error object and logs the rest, so then `--log` can be used to show the full error formatted.

catch graphql-client errors and show a formatted message instead

---

src/utils/fs-remove-file.ts
src/utils/fs/is-dir-empty.ts
src/utils/fs/read-dir-ignore-ds-store.ts
src/utils/fs/remove-containing-dir-if-empty.ts
src/utils/fs/remove-empty-dir.ts

Hopefully, that would be the end of the random CircleCI errors.

fix ENOENT error when deleting multiple objects directories in parallel

---

e2e/fixtures/extensions/babel-env/babel-env.extension.ts
scopes/compilation/babel/babel.main.runtime.ts

Currently, you have to use the following syntax `babelCompiler.createTask!()` with the `!`. This PR fixes it.

fix creating babel task to not require adding "!"

---

e2e/harmony/compile.e2e.4.ts
e2e/harmony/pkg.e2e.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/pipelines/builder/build.cmd.ts
scopes/pipelines/builder/builder.main.runtime.ts

Currently, it only empties the capsules it's about to build but it may have capsules from different versions. 
This makes sure that build and tag start fresh with no previous capsules. 
Also, removed the `--rebuild` flag of bit-build, it's not needed anymore because by default it deletes the root dir of the capsules.

delete capsule-root-dir before build/tag

---

scopes/ui-foundation/ui/ui.main.runtime.ts

Currently, when running `bit start` on a bare-scope for the first time, it shows an error:
```
➜  bit start
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
ENOENT: no such file or directory, scandir '/private/tmp/sch/public'
➜  
```
@guysaar223 , please review. Not sure what's the purpose of this line `if (fs.readdirSync(config.output.path).length > 0) return;`, it can't work because in the previous line you made sure that this exact directory doesn't exist.

fix ENOENT error when running bit-start for the first time

---

scopes/explorer/command-bar/ui/component-searcher/component-searcher.ts

when searching components in the command bar, improve results by adding weight to component name, and not just the whole component id.

increase command bar accuracy by indexing component name

---

e2e/commands/lane.e2e.1.ts
e2e/commands/snap.e2e.2.ts
e2e/harmony/harmony-import.e2e.ts
e2e/harmony/harmony-tag.e2e.ts
src/scope/component-ops/export-scope-components.ts
src/scope/models/model-component.ts

- currently, if the second snap is done on a clean scope, it throws an error in case artifacts are missing.
- this PR makes sure to not search for exported parents, export only the local snaps.

fix exporting lanes to only export the local snaps

---

e2e/commands/lane.e2e.1.ts
e2e/harmony/compile.e2e.4.ts
scopes/compilation/compiler/compiler.cmd.ts
scopes/compilation/compiler/workspace-compiler.ts
scopes/workspace/workspace/workspace.ts
scripts/soft-tag-teambit.js

- `bit compile` with no ids compiles only new and modified components.
- introduce a new `--all` flag to compile all components.
- set the CI to tag only modified components, not all.

compile only new and modified components unless --all flag is used

---

scopes/scope/scope/export/export-cmd.ts
src/scope/component-ops/export-scope-components.ts

On Harmony, there is no need to do codemod anymore because the fork feature is gone and the typescript is now compiled without the need for the link files.
Also, the versions refs should not be changed because on Harmony their hash is not determined by the content.

differentiate export on Harmony to not change version hashes and avoid codemod

---

e2e/commands/lane.e2e.1.ts
e2e/harmony/compile.e2e.4.ts
scopes/compilation/compiler/compiler.cmd.ts
scopes/compilation/compiler/workspace-compiler.ts

- remove the `--all` flag. this will be the default behavior now - compile all components. 
- add a new flag `--changed` to compile only new and modified components.

bit-compile: remove "all" flag, add "changed" flag instead

---

scopes/scope/scope/scope.main.runtime.ts
src/scope/actions/export-persist.ts
src/scope/objects/repository.ts

- clear Repository objects after persisting the data, so then the next export using HTTP won't rewrite the same objects.
- catch `onPutHook` errors and log the process.

fix http-export to clear the objects after export

---

scopes/component/graph/component-graph/component-graph.ts
scopes/component/graph/ui/graph-page/graph-page.tsx

- ComponentGraph.buildFromLegacy() - resolve componentID for edge ids.
- This fixes "node not in graph" errors

dep graph api - fix inconsistent edge id

---

scopes/harmony/express/middlewares/error.ts
scopes/preview/preview/preview.route.ts

Currently, it shows the error message on the web. This PR writes the error with the stack trace into the log file.
Also, it shows a descriptive error when the preview is unable to get a component object.

add log messages when express failed with error 500

---

e2e/fixtures/extensions/extension-add-dependencies/extension-add-dependencies.main.runtime.ts
e2e/harmony/dependency-resolver.e2e.ts
scopes/compilation/compiler/compiler.main.runtime.ts
scopes/compilation/compiler/workspace-compiler.ts
scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
scopes/workspace/workspace/workspace.ts

In case an aspect failed to load due to module-not-found error, it probably happened because the dists are missing. 
Let the compiler register to AspectLoader slot and compile it on failure.

compile aspects on load failure

---

e2e/functionalities/track-directories.e2e.3.ts
src/consumer/bit-map/component-map.ts

As a result of a new cache mechanism, sub-dir changes weren't tracked. This PR checks all subdirectories modified data and avoid using the cache if they were modified after the last track.

fix dir-tracking-cache to take sub-dirs into account

---

scopes/workspace/workspace/watch/watcher.ts

Currently, it shows an error `_legacy of undefined`.

fix watch errors when switching git branches

---

.bitmap
scopes/pkg/pkg/pkg.main.runtime.ts
scopes/workspace/workspace/exceptions/incorrect-env-aspect.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
scopes/workspace/workspace/workspace.ts

Only envs that are configured in workspace.jsonc to use core "aspect" env (or any composition of that env) are valid. Currently, the user has no indication when the env is invalid, it falls back to the default "node" env.

throw a descriptive error when user env is compiled by non-aspect env

---

scopes/workspace/workspace/workspace.ts
src/api/consumer/lib/feature-toggle.ts
src/cli/commands/public-cmds/clear-cache-cmd.ts
src/constants.ts
src/consumer/bit-map/component-map.ts
src/consumer/component/component-fs-cache.ts
src/consumer/component/component-loader.ts
src/consumer/component/consumer-component.ts
src/consumer/component/dependencies/dependency-resolver/README.md
src/consumer/component/dependencies/dependency-resolver/dependencies-data.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-loader.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/consumer.ts
src/jsdoc/parser.ts
src/links/node-modules-linker.ts
src/utils/fs/last-modified.ts

To improve component-loading performance, the dependencies data is cached in the filesystem.
1. The component-dir or sub-dirs have been changed. (modified-date of the dirs paths)
2. One of the component files have been changed.
3. A component config file (component.json/package.json) has modified.
1. workspace-config file (bit.json/workspace.jsonc) has changed.
2. package.json file has changed.
3. node_modules-dir (only root dir, not sub-dirs) has changed. - not sure if needed.
4. On completion of "bit link".
5. On completion of "bit install".
6. During 'bit tag --persist', before loading the components.
1. No root-dir/track-dir (legacy).
2. Component has one of the following issues: missingPackagesDependenciesOnFs, untrackedDependencies.
1. If a user deleted the dists directories of a …

Cache dependencies data for performance improvement

---

scopes/compilation/bundler/bundler.main.runtime.ts
scopes/react/react/webpack/webpack.config.ts

- fix `bundler.devServer()` to throw errors (if found) during the dev server load.
- fix react to have the mdx-loader as a dependency.

fix error on bit-start "Cannot find module @teambit/modules.mdx-loader"

---

scopes/dependencies/dependency-resolver/dependency-linker.ts
scopes/dependencies/dependency-resolver/index.ts
scopes/workspace/workspace/link/link.cmd.tsx
scopes/workspace/workspace/link/nested-deps-in-nm-links.tsx
scopes/workspace/workspace/workspace.ts
src/links/node-modules-linker.ts
src/links/symlink.ts

This pr will add links from 
`componentSrcDir/node_modules/*` to `root/node_modules/componentPackageName/node_modules/*`
This is important since:
when we have a conflict of dependency between components, we nest some of the packages into the component.
we write those nested dependencies in the component src folder (in order to have correct types and autocomplete in the ide)
but the dists are running from `root/node_modules/componentPackageName` which doesn't have access to those nested dependencies, so it will resolve in action the wrong version (the conflicted one).
This PR will link all the packages from node modules in component src to the node_modules inside the package name of the component in the root node modules

Nested deps links

---

scopes/envs/envs/index.ts
scopes/workspace/workspace/exceptions/incorrect-env-aspect.ts
scopes/workspace/workspace/workspace.ts

The IncorrectEnvAspect is thrown when a custom env is compiled by a non-aspect core env. However, when the node-modules is empty, all components include custom-env are default to node-env, which is not an aspect env. 
This PR prevents the error to be thrown in such a case and let Bit compiles the custom-envs.

fix IncorrectEnvAspect to not be thrown when bit defaults to the node-env

---

scopes/react/react/react.env.ts
workspace.jsonc

Otherwise, users will need to manually add this dependency for every typescript project.

remove the types/node from the general and add to react-env

---

scopes/harmony/graphql/graphql.main.runtime.ts

Currently, the errors are shown in the UI only and without important data, which makes it difficult to debug.

log graphql errors to the debug.log file

---

scopes/react/react/react.env.ts

This meant to make sure that the jest tests will work.
Since we have a jest transformer in the react env that uses babel to compile the source code on the fly.
Those plugins added `@babel/runtime` in the compiled code, but this must be installed.
Now all components will have this as dev dependnecy.

added @babel/runtime as dev dep to all components that uses react-env

---

src/consumer/component/dependencies/dependency-resolver/dependencies-versions-resolver.ts

The issue started once the `resolveNodePackage` has changed to return an object with the package-json data. The way how to get the version from that data is different. 
This PR fetches the data correctly according to the `ResolvedNodePackage` interface. It first tries to use the concrete installed version in the node-modules and if not found, it uses the version written in the dependent package-json file.

fix dependencies version resolution to use the dependent package.json

---

e2e/harmony/import-harmony.e2e.ts
src/consumer/component-ops/import-components.ts
src/scope/graph/build-graph-from-fs.ts
src/scope/graph/components-graph.ts
src/utils/fs/last-modified.ts

Currently, the seeders are loaded from the FS and if one of them failed, it loads them all from the model. However, it's possible that some in the FS and some in the Model. 
This PR fixes it to load the seeders the same as the dependencies.

fix build-one-graph to load the seeders properly

---

scopes/workspace/workspace/workspace.ts

when a component is directly imported and installed as a package with a different version, create only one capsule for the imported.

Avoid creating capsules for the same components with different versions

---

e2e/commands/diff.e2e.1.ts
src/api/consumer/lib/dependents.ts
src/api/consumer/lib/get-scope-component.ts
src/cli/command-registry-builder.ts
src/cli/commands/public-cmds/dependents-cmd.ts
src/cli/default-error-handler.ts
src/cli/templates/all-help.ts
src/cli/templates/component-template.ts
src/scope/component-ops/get-flattened-dependencies.ts
src/scope/component-ops/traverse-versions.ts
src/scope/exceptions/version-not-found.ts
src/scope/graph/scope-graph.ts
src/scope/models/model-component.ts

* Introduce a new command `bit dependents`, it shows the dependents of the given component-id nicely with the level of how far is it from the id.
* improve `ComponentNotFound` error to suggest using this command.
* improve `VersionNotFound` error to include the component-id.

introduce a new command "bit dependents" to help debug component-not-found errors

---

scopes/scope/sign/sign.cmd.ts
scopes/scope/sign/sign.main.runtime.ts

- if the previous sign has failed, allow re-try. 
- if the previous sign has succeed, don't throw an error. instead, show a message saying that it was signed already.
- if the build failed, exit with status code 1.

enable re-sign failed components

---

e2e/commands/snap.e2e.2.ts
src/cli/commands/private-cmds/cat-object-cmd.ts
src/cli/default-error-handler.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/component-ops/traverse-versions.ts
src/scope/models/model-component.ts
src/scope/repositories/sources.ts

This is working properly when snapping. However, with tags, when the local and the remote components have diverged and the component is exported, the export was going through unexpectedly.

block exporting outdated components

---

scopes/workspace/workspace/workspace.ts
src/consumer/bit-map/bit-map.ts
src/consumer/bit-map/component-map.ts
src/consumer/consumer.ts

currently, the lastTrack entered to the cache even if the .bitmap changes were not written

enter last-track data to the cache only during bitmap.write process not before

---

workspace.jsonc

- currently, projects that use it get "error: component "teambit.component/component-id@0.0.207" was not found on your local workspace".

change component-id component env to node, not aspect

---

scopes/scope/sign/sign.cmd.ts
scopes/scope/sign/sign.main.runtime.ts
src/api/scope/lib/action.ts
src/remotes/remote.ts
src/scope/actions/action.ts
src/scope/actions/clear-scope-cache.ts
src/scope/actions/export-validate.ts
src/scope/actions/fetch-missing-deps.ts
src/scope/actions/index.ts
src/scope/actions/remove-pending-dir.ts
src/scope/objects/repository.ts

- with this change, once bit-sign changes the objects, the main bit-start process could fetch the updated data. (these two are running in two different processes).

clear scopes caches after bit-sign

---

e2e/commands/lane.e2e.1.ts
e2e/harmony/import-harmony.e2e.ts
src/consumer/bit-map/component-map.ts

it broke recently after changing the get-all-bit-ids method to consider lanes.

fix bit-import to install components dependencies

---

scopes/explorer/command-bar/ui/command-searcher/command-searcher.ts
scopes/explorer/command-bar/ui/component-searcher/component-searcher.ts

On Circle it shows these errors for some reason:
```
scopes/explorer/command-bar/ui/command-searcher/command-searcher.ts:24:5 - error TS2322: Type 'unknown[]' is not assignable to type 'CommanderSearchResult[]'.
Type 'unknown' is not assignable to type 'CommanderSearchResult'.
24     return searchResults.map((x) => x.item);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scopes/explorer/command-bar/ui/component-searcher/component-searcher.ts:37:5 - error TS2322: Type 'unknown[]' is not assignable to type 'ComponentSearchResult[]'.
Type 'unknown' is not assignable to type 'ComponentSearchResult'.
Type 'unknown' is not assignable to type 'CommanderSearchResult'.
37     return searchResults.map((x) => x.item);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 2 errors.
```

fix tsc errors on Circle

---

src/cli/default-error-handler.ts
src/scope/exceptions/version-not-found.ts

Currently, it doesn't show the error message only the class name.

fix VersionNotFound to show the error message when thrown by the remote

---

src/hooks/hooks-manager.ts

Currently, it prints them during the export, which is useless and makes it hard to navigate through the log. 
Instead, show only the number of objects.

avoid printing the entire object-list into the log

---

scopes/harmony/graphql/graphql.ui.runtime.tsx
workspace.jsonc

- fix different gql objects having the same id
- prefix gql id with typename (e.g. fixes conflict between graphNodeComponent and component)
- fallback to typename + hash when id is an object

fix unique gql ids

---

scopes/harmony/bit/load-bit.ts

- support configuring local aspects in the workspace.jsonc without specifying a version and still get the config from the workspace.jsonc

attach aspects versions from bitmap to aspect ids during harmony config load

---

e2e/harmony/update-dependencies.e2e.ts
scopes/scope/update-dependencies/update-dependencies.cmd.ts
scopes/scope/update-dependencies/update-dependencies.main.runtime.ts
src/e2e-helper/e2e-command-helper.ts

We don't want this to be running from the original scope (like bit-sign). 
This command tags or snaps the results, a process that takes some time due to the build pipeline. If we start the tag on the original scope, build and then save the tag to the filesystem, we might get another tag during the process and our tag could override it.

remove "multiple" flag from bit update-dependencies

---

scopes/react/react/docs/component-overview/component-overview.module.scss
scopes/react/react/docs/component-overview/component-overview.tsx

- Add break line in scope description.
At the moment, descriptions that have breaks lines are shown as a single line.
example: https://bit.dev/teambit/mdx

add break line in scope description

---

scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.spec.ts
scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.ts
scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts
scopes/scope/sign/sign.main.runtime.ts

- pass  copyPeerToRuntimeOnComponents: true from bit sign to isolator
- hoist peer dep to root in case it appears only with one version

fix peer install for bit sign

---

e2e/harmony/compile.e2e.4.ts
e2e/harmony/harmony-tag.e2e.ts
src/e2e-helper/e2e-general-helper.ts
src/scope/component-ops/tag-model-component.ts

Currently, it saves the builder data of the older versions unexpectedly. 
As a result, the following export failed due to missing artifact files.

fix tag without build to not save the old builder data

---

scopes/explorer/command-bar/command-bar.preview.runtime.tsx

- do not trigger hotkeys, or pass any key events, from preview iframe, when target element is an input (including textarea, select, and content-editable)

preview iframe - ignore hotkeys focusing input

---

e2e/harmony/sign.e2e.ts
src/scope/component-ops/export-scope-components.ts

we're going to change many things in this area very soon. currently, it seems to do more harm than good, so we disable it for now.

disable pushing flattened dependencies to the remotes

---

scopes/preview/ui/component-preview/urls.spec.ts
scopes/preview/ui/component-preview/urls.ts

- preview urls will not work without trailing '/', specifically when running bit start on workspaces
- this fix ensures trailing slash as a quick fix
- a fix to the preview regex might follow

ensure trailing slash at the end of preview urls

---

src/scope/component-version.ts

Due to missing `await`, in some rare cases, objects of old versions were missing.

fix importing objects of old versions

---

scopes/component/component/aspect-entry.ts
scopes/component/component/index.ts
scopes/component/dev-files/dev-files.main.runtime.ts
scopes/compositions/compositions/compositions.main.runtime.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/envs/envs/environments.main.runtime.ts
scopes/pkg/pkg/pkg.main.runtime.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/workspace/workspace/index.ts
scopes/workspace/workspace/on-component-events.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
scopes/workspace/workspace/workspace.ts
src/consumer/component/consumer-component.ts
src/scope/component-ops/tag-model-component.ts

- fix loading user envs during tagging them 
- throw an error in case a non-existing env defined on the component
- add an aspect data type
- add previously used version prop to consumer component during component tag
- change the get env to get the calculated data instead of re-calc it from config

Fix env config calculation

---

e2e/commands/export.e2e.1.ts
e2e/harmony/recovery-after-deletion.e2e.ts
src/scope/component-ops/export-scope-components.ts

because it causes race-condition on multiple remotes with circular dependencies.

cancel the step of fetch-missing-dependencies-on-remote 

---

scopes/scope/scope/scope.main.runtime.ts
src/scope/component-ops/export-scope-components.ts
src/scope/scope.ts

currently it shows an error `TypeError: Cannot read property 'values' of undefined`.

fix prePersist hook to not throw an error and rename it to prePersistExport

---

e2e/harmony/init-harmony.e2e.ts
src/api/consumer/lib/init.ts
src/cli/commands/public-cmds/init-cmd.ts
src/consumer/bit-map/bit-map.ts
src/consumer/consumer.ts
src/e2e-helper/e2e-command-helper.ts
src/interactive/commands/init-interactive.ts

At times, it can be useful to start Bit from scratch but to keep .bitmap file to map the directories to the components.
This flag does the following:
1. changes all components in the .bitmap file as if they were just added. (removed data about tagging/exporting).
2. removes all objects in the scope.

introduce a new flag "--reset-new" to "bit init" to reset .bitmap to new components

---

src/cli/loader/loader.ts

Currently, it's mostly noticeable during `bit build` command at the typescript compilation step.
It seems to be a bug in Ora package, see here for more info: https://github.com/sindresorhus/ora/issues/156
I tried the suggested workaround there and it's working.

configure Ora to avoid messing with Ctrl+C

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/dependency-resolver/index.ts
scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/get-proxy-config.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
scopes/dependencies/yarn/yarn.package-manager.ts
src/constants.ts

- read proxy config from bit's global config, npmrc config and dep-resolver config
- support proxy for pnpm
- support proxy yarn

Package manager proxy

---

scopes/ui-foundation/ui/webpack/webpack.base.config.ts

- remove "environment plugin in main webpack config (ui.ui's)
- the plugin is automatically configured by webpack when setting 'mode'
- mode is 'production' by default
This fixes the `using minified ... outside mode === "production"` error

fix node env define

---

scopes/ui-foundation/uis/side-bar/component-tree/component-view/component-view.module.scss
scopes/ui-foundation/uis/side-bar/component-tree/component-view/component-view.tsx

- Fixed text color in the Env Tooltip.
Before:
Fixed:
Tooltip text had text color set to `--border-color`. When I applied `DarkTheme` to the tooltips, this color has changed from `#ededed` (pearl) to `#414141` (darkness).
Default text color in `DarkTheme` is already pearl, so just removing the css.

fix text color in env tooltip

---

src/api/scope/lib/fetch.ts

With SSH/FS protocol this is not an issue because it load the entire Bit for every command. HTTP on the other hand, re-use the Scope instance for multiple requests, which is fine for the most cases. 
For fetch, however, this creates hard-to-find problems. For example: scopeA/compA -> scopeB/compB.
UserA asks for compA, scopeA gets a "fetch" request, finds out that it doesn't have the compB dependency and gets it from scopeB, once the components received, it's being added to the objects-cache. During the persist-on-the-filesystem phase it got an error and was unable to persist. However, the component object of compB is still in the cache. 
As a result, the next time scopeA gets a fetch request it'll assume that this component exists, as it finds it in the cache. However when it starts …

avoid re-using the scope instance for "fetch" operation

---

scopes/harmony/pubsub/pubsub.preview.runtime.ts
scopes/harmony/pubsub/pubsub.ui.runtime.ts

Improvements to the pubsub setup for docs/preview:
- Remove timeout from parent setup (now waits indefinitely, without having to retry)
- Start docs setup asap, instead of the slow window.onLoad()
- Increase child retries to 10, in case the iframe loads before the parent (e.g. due to ssr). In most cases, it will connect on first try.

fix pubsub lag

---

scopes/harmony/pubsub/pubsub.ui.runtime.ts

- add `catch()` to Penpal's `connectToChild()` promise.
- this prevents uncaught promise rejections when switching between components quickly in Scope view

catch promise errors of connection, in pubsub

---

e2e/harmony/import-harmony.e2e.ts
src/consumer/component-ops/import-components.ts
src/scope/component-ops/traverse-versions.ts

currently it has two bugs:
1. the import-delta brings all old tags (not snaps) due to some backward compatibility code.
2. the output of `bit import` doesn't show the newly added tags correctly.
This PR fixes both.

fix import delta to not fetch existing tags and to show only the newly added version

---

src/scope/models/model-component.ts
src/scope/scope.ts

It's not safe to run the objects merge in parallel for all components because the same component may retrieved from different scopes (origin and cache). In this PR the parallel is executed per remote, which is safe and improves the performance dramatically (from 36 sec to 18 sec for 188 components in bit-bin).

improve component-objects merge performance by running them in parallel per remote

---

scopes/scope/scope/scope.main.runtime.ts
scopes/scope/sign/sign.main.runtime.ts
scopes/scope/update-dependencies/update-dependencies.main.runtime.ts

Currently, it loads the components from the scope without the aspects (using `scope.get` instead of `scope.load`).

load components aspects when running update-dependencies command

---

src/scope/objects/object-list.ts

Currently, it concatenates the buffer for every chunk.

relax the cpu load on export by concatenating the buffers only once all data is there

---

scopes/scope/scope/scope-component-loader.ts
scopes/scope/scope/scope.main.runtime.ts

- refactoring: extract all component-load of the scope aspect to a new class `ScopeComponentLoader`
- cache components once loaded from the scope.

cache components loaded from the scope

---

src/scope/component-ops/tag-model-component.ts

This is happening when some components have range and some use exact-version

fix soft-tag to respect the SemVer range when some components have exact versions

---

src/scope/component-ops/model-components-merger.spec.ts
src/scope/component-ops/model-components-merger.ts
src/scope/repositories/sources.ts
src/scope/scope.ts

Currently, when importing components and merging the objects into the local scope, Bit traverse the entire history in order to find the diff between the incoming component and existing component. 
Instead, traverse the incoming component only (which is already in-memory) until you find the existing head, this way, it's easy to get the added snaps without traversing the local component.

avoid traversing the entire component graph when merging a component-object

---

src/api/scope/lib/fetch.ts
src/consumer/component/component-loader.ts
src/remotes/remotes.ts
src/scope/component-ops/scope-components-importer.ts
workspace.jsonc

- use mutex to ensure that "fetch-with-dependencies" runs sequentially. otherwise, on the remotes, multiple requests are fetching external dependencies at the same time, causing "refs" and "object" files to be corrupted.
- remove `getExternal` and `getExternalWithoutDependencies` apis, use the "many" counterparts. 
- use the cached scope instance for "fetch" operation to avoid high memory consumption that leads to out-of-memory error.

allow only one fetch-with-deps at a time to avoid files corruption

---

scopes/harmony/graphql/graphql.main.runtime.ts
src/scope/objects/repository.ts

files such as `refs` and `index.json` could be corrupted if for some reason, `repository.persist()` gets called by multiple requests at the same time.

prevent persisting objects in parallel to avoid files corruption

---

scopes/harmony/express/express.main.runtime.ts
scopes/harmony/graphql/graphql.ui.runtime.tsx
scopes/harmony/graphql/render-lifecycle.tsx

- `gql.createClient()`: extract uri generation to consumer, and separate WebSocket uri to its own option.
- add `legacy=true` option, to use old method until fully replaced
- @KutnerUri will remove the legacy code in a separate commit (after updating Symphony)

simplify gql client factory

---

src/cli/commands/public-cmds/clear-cache-cmd.ts

- support deleting .bit/index.json using `bit cc`
- improve the clear-cache output to show what type of cashes were cleared

delete index.json file in the scope by bit clear-cache

---

src/scope/objects/repository.ts

With the new way the objects are written to the FS (see https://github.com/teambit/bit/pull/3885), they don't go through the cache of `Repository` class. This might cause other processes accessing the cache to get stale data.

update repository.cache when an object is written to the filesystem

---

src/scope/component-ops/components-deprecation.ts

Similar to https://github.com/teambit/bit/pull/3885.
The idea is to make these deprecation methods stateless and not rely on the repo.objects which can be modified by other processes.

avoid caching components objects on deprecation commands

---

src/cli/default-error-handler.ts
src/scope/exceptions/merge-conflict-on-remote.ts

With the current structure it shows an obscure error to the end user when going through the central-export.

improve MergeConflictOnRemote error to have "message" field

---

src/scope/component-ops/export-scope-components.ts
src/scope/component-ops/remove-model-components.ts
src/scope/exceptions/merge-conflict-on-remote.ts
src/scope/lanes/unmerged-components.ts
src/scope/objects/repository.ts
src/scope/repositories/sources.ts

Similar to https://github.com/teambit/bit/pull/3885. Make the "remove" process stateless in order for multiple processes to work concurrently.

avoid caching data during bit-remove

---

e2e/harmony/clear-cache.e2e.ts
scopes/harmony/bit/load-bit.ts
scopes/workspace/workspace/workspace.provider.ts
src/api/consumer/index.ts
src/api/consumer/lib/clear-cache.ts
src/cli/command-registry.ts
src/cli/commands/public-cmds/clear-cache-cmd.ts
src/e2e-helper/e2e-command-helper.ts

During Bit bootstrap phase, all core-aspects and user aspects are loaded. This is done before commands are registered to the CLI aspect. As a result, if anything goes wrong in the core/user aspects, there is no way to recover by any of the commands as they weren't registered yet. 
Sometimes, a simple command such as `bit clear-cache` can fix the issue, or, at times, some low-level commands, such as `bit cat-scope` are needed to debug the issues.
- entirely skip the aspect loading phase and load only the CLI aspect for the following commands: `clear-cache`, `cat-scope`, `cat-object`, `init`, `cat-component`, `cat-lane`.
- introduce a new global flag `--safe-mode`, which does the above (load only the CLI aspect) for any command. Keep in mind that for most commands this won't be helpful as …

help recovering from bootstrap errors

---

scopes/pkg/pkg/pkg.main.runtime.ts
scopes/react/react/react.env.ts
scopes/react/react/webpack/webpack.config.preview.dev.ts
scopes/ui-foundation/ui/webpack/webpack.dev.config.js

- limit source-map-loader to apply only dist files in the current workspace
- disable source-map-loader in internal dev webpack (i.e. `start --dev`)

enable source-map-loader only for dists in the current workspae

---

scopes/react/react/webpack/webpack.config.preview.dev.ts

- comment out source-map-loader for docs/compositions
- also disable bit id transformer, which is currently unused

disable source map loader for compositions and docs

---

src/consumer/component/component-loader.ts
src/remotes/remote.ts
src/remotes/remotes.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/network/fs/fs.ts
src/scope/network/http/http.ts
src/scope/network/network.ts
src/scope/network/ssh/ssh.ts
src/scope/objects/object-list.ts
src/scope/objects/objects-writable-stream.ts
src/scope/objects/repository.ts

Currently, the `fetch` operation gets all objects from the remotes, store them in-memory and then process them and write to the filesystem. 
This PR utilizes streams to write the objects as soon as they arrive from the remote scope.
Bit supports 3 protocols: FS, SSH and HTTP.
Since these three don't get the data in the same way, a new `stream.Readable` (aliased as `ObjectItemsStream` type ) was created to have them all use the exact same interface. This Stream Readable works with `objectMode: true` and emits an `ObjectItem` object upon `data` event.
For SSH and FS, since we get the data as `ObjectItem[]` it just converts them to Readable using the built-in `Readable.from` method.
For HTTP, the data is coming as [tar-stream](https://github.com/mafintosh/tar-stream). To convert them to our …

improve memory consumption dramatically during bit-import

---

scopes/scope/scope/routes/fetch.route.ts
scopes/scope/scope/scope.main.runtime.ts
src/api/scope/lib/fetch.ts
src/cli/commands/private-cmds/_fetch-cmd.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/component-version.ts
src/scope/exceptions/error-from-remote.ts
src/scope/flatten-dependencies.ts
src/scope/network/fs/fs.ts
src/scope/objects/object-list.ts
src/scope/objects/objects-readable-generator.ts
src/scope/objects/objects-writable-stream.ts
src/scope/scope.ts
src/scope/version-dependencies.ts

The consumer of the fetch API already uses streams, see https://github.com/teambit/bit/pull/3909.
This PR is to make a similar change for the Fetch API implementation, which normally happens on the remote.
Currently, all objects are cached in-memory and pushed all in once into the client. For large scopes this can cause out-of-memory.
This PR changes the implementation to use streams instead. It implements a `Readable` stream, which processes the objects that need to be sent and pushes them as soon as they're ready.
With this change, the `fetch` API returns `stream.Readable`, instead of `ObjectList`. Here is how it works for each one of the network protocol.
**HTTP** - the `fetch` API returns `Readable`, then, it is piped into `tar-stream`, which eventually piped into the response.
**FS** …

change fetch implementation to use streams to keep the memory usage low

---

scopes/compilation/cli/webpack/error/error.tsx
scopes/preview/cli/preview-server-status/preview-server-status.tsx
scopes/react/react/typescript/tsconfig.json
scopes/stencil/stencil/typescript/tsconfig.json

- add `"rootDir": "."` to tsconfig of the react env. This only changes the dists for the local (workspace) components, and is already included in the build `tsconfig.json`
- this will fix source maps for all components with folders in workspace start
- also fix outputs for errors and warnings. (used to show them in columns)

Fix source maps

---

src/constants.ts
src/remotes/remotes.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/objects-fetcher/objects-fetcher.ts
src/scope/objects-fetcher/objects-writable-stream.ts
src/scope/objects-fetcher/write-components-queue.ts
src/scope/objects-fetcher/write-objects-queue.ts

Up until now, the fetch process would wait for all remotes to return an answer and then it would process them one by one, mainly to avoid merging the same component-object from multiple remotes.
This PR takes advantage of the recent changes in the Fetch process (https://github.com/teambit/bit/pull/3916 and https://github.com/teambit/bit/pull/3909) and as soon as the remote responses with a stream, it pipes it to a `writable` stream, which sends the objects to a central queue.
This queue is shared between all remotes and is responsible to limit the concurrency and to make sure the same files are not written at the same time and that each component is merged in sequence.
This PR cut the import time in a half since the last https://github.com/teambit/bit/pull/3916 change.

improve import performance by writing the objects as soon as they arrive

---

e2e/commands/checkout.e2e.1.ts
src/api/consumer/lib/checkout.ts
src/cli/commands/public-cmds/checkout-cmd.ts
src/consumer/lanes/switch-lanes.ts
src/consumer/versions-ops/checkout-version.ts
src/consumer/versions-ops/merge-version/merge-snaps.ts
src/consumer/versions-ops/merge-version/merge-version.ts

Remove up-to-date components from bit-checkout output when `--all` flag was used as this is too verbose and confusing.
Show them only when the `--verbose` flag is used.

fixes #2362, remove up-to-date components from bit-checkout output

---

scopes/dependencies/dependency-resolver/dependency-linker.ts
src/links/symlink.ts

- fix the error: failed linking core aspect 'teambit.harmony/aspect-loader' with the following error: Error: EEXIST: file already exists, symlink {srcPath} -> {targetPath}

fix error when trying to link core aspects which is already linked

---

e2e/harmony/sign.e2e.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/repositories/sources.ts

When running `bit import`, existing components are not fetched from a remote. 
This PR checks whether the existing component has already built (using bit-sign) and if not, it fetches it from the remote because the remote might have it build.

re-import components if their build status is pending or failed

---

e2e/harmony/sign.e2e.ts
src/bit-id/bit-ids.ts
src/consumer/consumer.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/models/model-component.ts
src/scope/repositories/sources.ts

Due to a recent change, `bit import` re-fetch a component when its Version object has a build-status of Pending/Failed.
During tag, the build-status is pending, as such it tried to re-import it again and again from a remote. In this PR it checks whether a version exists only locally and then it won't try to re-fetch it.
Another issue was that `getExternalMany()` used to go to the remotes for each one of the components for its flattened-dependencies. With this PR it first accumulate all ids and then go to the remote once.

fix multiple fetching during tag

---

e2e/functionalities/merge.e2e.3.ts
src/cli/default-error-handler.ts
src/scope/exceptions/merge-conflict.ts
src/scope/objects-fetcher/objects-writable-stream.ts
src/scope/objects-fetcher/write-components-queue.ts
src/scope/objects-fetcher/write-objects-queue.ts

Fetch process sends the objects to a queue to be written to the filesystem and doesn't wait to completion. 
Originally it was done to make the process faster and let the queue control the concurrency. However, it causes issues with error handling. 
This PR changes the implementation to wait for the queue to complete processing before continuing to the next object. 
The performance had been tested before and after this change and there was no noticeable difference. (on bit-bin with more than 10K objects it took 1:10 min in both cases, which is mostly the download time)

fix unhandled promise reject during fetch process

---

scopes/scope/sign/sign.main.runtime.ts
scopes/scope/update-dependencies/update-dependencies.main.runtime.ts

It is needed to wait for the slots to wait until completion, otherwise, the artifacts data could be gone during the process

wait for post-sign and post-update-dependencies to complete

---

src/cli/commands/public-cmds/import-cmd.ts
src/cli/commands/public-cmds/install-cmd.ts

Currently, `bit install` doesn't have any alias. Add the alias `i` and remove it from `bit import`. (as per @ranm8  request).

remove the alias "i" from bit-import and add it to bit-install

---

scopes/generator/generator/create.cmd.ts
scopes/generator/generator/generator.main.runtime.ts

In order to create a component not in the default directory (scope/namespace/name).

introduce a new flag "--path" to bit-create

---

e2e/harmony/compile.e2e.4.ts
e2e/npm-ci-registry.ts
scopes/typescript/typescript/typescript.compiler.ts
scopes/typescript/typescript/typescript.docs.md
src/e2e-helper/e2e-fs-helper.ts

Currently, for nested-dir the `sources` value of the source-map file is incorrect as a result of removing the `rootDir` prop from the tsconfig.json file of the workspace.
This PR adds the `rootDir` value programmatically during the compilation so then the tsconfig file could be kept without the rootDir.
The reason not to add it directly to the tsconfig.json file is that in some cases it's advisable to extend this tsconfig for the IDE to have the auto-complete and other features.

fix source-map files when a component has nested directories

---

scopes/compilation/webpack/webpack.dev-server.ts
scopes/ui-foundation/react-router/ui/slot-router/slot-router.tsx
scopes/ui-foundation/ui/ui-server.ts
yarn.lock

The errors appear here:
https://app.circleci.com/pipelines/github/teambit/bit/10608/workflows/1048206d-00d5-4ff1-ae56-38a9a7335ce2/jobs/141707
Seems like the Webpack types and Webpack types of webpack-dev-server are not compatible. It's unclear why these errors are shown only now.
@GiladShoham , I started investigating this and I see that webpack-dev-server has webpack types as version 5.x instead of 4.x. Maybe you have an insight here.

fix failing bit-build due to some unclear typescript errors

---

scopes/mdx/mdx/mdx.docs.md

remove link as this is imported into our docs site. we will work on a solution for links in near future but for now it make sense to remove all links
-
-
-

docs: remove link mdx docs

---

e2e/harmony/create.e2e.4.ts
scopes/generator/generator/component-generator.ts
scopes/generator/generator/generator.main.runtime.ts
scopes/workspace/workspace/workspace.ts
src/consumer/component-ops/add-components/add-components.ts

Fixes #4016.
- in case a component was written but failed to be added to the .bitmap file, make sure to delete the created component.
- if the component-path exists, throw an error and avoid overriding that dir.
- refactoring: extract the component-generator logic to a new class.

make the bit-create command atomic and avoid overriding existing components/files

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/config/abstract-config.ts
src/scope/component-ops/tag-model-component.ts

I observed this while watching process-monitor on a Windows machine. It reads 400+ files from `ramda-adjunct` package.
In this PR I removed all occurrences we had of `import * as RA from 'ramda-adjunct'`.

improve loading performance by importing only the needed methods from ramda-adjunct

---

scopes/generator/generator/component-generator.ts
scopes/generator/generator/component-template.ts
scopes/harmony/aspect/templates/aspect/files/aspect-file.ts
scopes/harmony/aspect/templates/aspect/files/index.ts
scopes/harmony/aspect/templates/aspect/files/main-runtime.ts
scopes/harmony/aspect/templates/aspect/index.ts
scopes/harmony/node/templates/node-env/files/extension.ts
scopes/harmony/node/templates/node-env/files/index.ts
scopes/harmony/node/templates/node-env/index.ts
scopes/react/react-native/templates/react-native-env/files/extension.ts
scopes/react/react-native/templates/react-native-env/files/index.ts
scopes/react/react-native/templates/react-native-env/index.ts
scopes/react/react/templates/react-button/component.ts
scopes/react/react/templates/react-button/composition.ts
scopes/react/react/templates/react-button/docs.ts
scopes/react/react/templates/react-button/index.ts
scopes/react/react/templates/react-button/test.ts
scopes/react/react/templates/react-component/component.ts
scopes/react/react/templates/react-component/composition.ts
scopes/react/react/templates/react-component/docs.ts
scopes/react/react/templates/react-component/index.ts
scopes/react/react/templates/react-component/test.ts
scopes/react/react/templates/react-env/files/extension.ts
scopes/react/react/templates/react-env/files/index.ts
scopes/react/react/templates/react-env/index.ts

- rename `componentName` to `name`.
- rename `componentNameCamelCase` to `namePascalCase`
- introduce `nameCamelCase` for lower camel case.

change component-templates API to accommodate the different cases

---

e2e/commands/lane.e2e.1.ts
src/scope/models/model-component.ts

Currently, if all versions of master are exported and a new snap was created on a lane, bit-status shows no versions.

fix bit-status to show the correct staged versions when snapping on a lane after exporting master

---

src/constants.ts
src/consumer/component/sources/data-to-persist.ts
src/remotes/remotes.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/objects-fetcher/objects-fetcher.ts
src/scope/objects-fetcher/write-objects-queue.ts
src/scope/objects/object-list.ts
src/scope/objects/repository.ts
src/scope/repositories/sources.ts
src/utils/concurrency.ts
src/utils/fs/remove-files-and-empty-dirs-recursively.ts

Currently the concurrency limit for IO/Component/Fetch are hard-coded. 
This PR enables setting them to a non-default number by changing the global Bit configuration as following:
```
bit config set concurrency.io 100
bit config set concurrency.components 50
bit config set concurrency.fetch 15
```

make the concurrency limit configurable

---

src/utils/eol.ts

In some scenarios, when files were saved on Linux and then opened and written on Windows, the new lines characters were duplicated.
The reason for this duplication is that we looped through `['\r\n', '\r', '\n']` inside the buffer and replace this with `\r\n` on Windows. So, `\r` was replaced by `\r\n` and then `\n` was replaced with `\r\n`, hence the double EOL.
In this PR, the algorithm of changing the EOL in buffers has changed to convert it to string and then use regex to replace them all. (instead of the loop).

fixes #4040, fix writing files on Windows to not multiply the EOL

---

src/api/consumer/lib/global-config.ts

Currently, if a config value is not in bit-config, it goes to Git and if not found, it doesn't cache the result. It causes the fetch operation on the remote to be very slow.

fix bit-import performance by caching the concurrency-limit value

---

scopes/harmony/pubsub/no-parent-error.ts
scopes/harmony/pubsub/pubsub.preview.runtime.ts

parent doesn't always listen for child, for example, in search results page.

do not error when pubsub fails connecting to parent

---

scopes/component/component-id/component-id.ts
scopes/preview/preview/preview.preview.runtime.tsx
scopes/react/component-highlighter/label/label.tsx

Fix this error:
```
Uncaught (in promise) Error: error: component ID "" is invalid, please use the following format: [scope]/<name>
```
(for example, here - https://k1lh7jpk.scopes.bit.dev/api/teambit.documenter/ui/table/td@3.0.6/~aspect/preview/)
- add `.tryFromString()` to component id (returns undefined, instead of exception)
- in preview page, show PreviewNotFound when component id fails to parse

show previewNotFound when getting parse error in previews

---

e2e/commands/lane.e2e.1.ts
e2e/commands/snap.e2e.2.ts
e2e/flows/out-of-sync-componets.e2e.3.ts
e2e/functionalities/reduce-path.e2e.3.ts
e2e/functionalities/track-directories.e2e.3.ts
e2e/harmony/compile.e2e.4.ts
e2e/harmony/dependency-resolver.e2e.ts
e2e/harmony/eject-harmony.e2e.ts
e2e/harmony/extensions-config.e2e.3.ts
e2e/harmony/flows.e2e.4.ts
e2e/harmony/http.e2e.ts
e2e/harmony/import-harmony.e2e.ts
e2e/harmony/pkg.e2e.ts
e2e/harmony/relative-paths.e2e.3.ts
e2e/harmony/set-default-owner-and-scope.e2e.4.ts
e2e/harmony/sign.e2e.ts
e2e/harmony/tag-harmony.e2e.ts
scopes/scope/export/export-cmd.ts
src/api/consumer/lib/export.ts
src/e2e-helper/e2e-command-helper.ts

Since the introduction of `defaultScope` no need to enter the scope-name. The components are exported to their current scope or `defaultScope` if they're new.
The way to "fork" a component is to change the default-scope (for now at least) and then `bit export`. 
Implements #4098.

Replace "bit export <scope>" with "bit export" for Harmony

---

src/links/node-modules-linker.ts

Due to the recent change of replacing all soft-link to hard-link, the IDE navigates form one component to the node-modules of the other component, instead of going to the component source files.
Another issue is that we get errors such:
```
Type 'import("/Users/davidfirst/teambit/bit/scopes/pipelines/builder/task-results-list").TaskResultsList[]' is not assignable to type 'import("/Users/davidfirst/teambit/bit/node_modules/@teambit/builder/task-results-list").TaskResultsList[]'.
```
It's happening because typescript fails to see that these two files are linked via hard-link. (same inode).

replace the hard-links from node-modules to source files with soft-links

---

src/utils/fs/create-symlink-or-copy.ts

By replacing fs-extra with fs.

fix error "EXDEV: cross-device link not permitted" on docker

---

scopes/dependencies/yarn/yarn.package-manager.ts

- prevent yarn duplicate workspace
- change persistProject: false to make sure yarn won't mutate package.jsons

prevent yarn duplicate workspace

---

scopes/scope/scope/scope-component-loader.ts

Currently, it shows a cryptic error.

throw a descriptive error when getSnap cannot find the snap

---

scopes/defender/linter/lint.cmd.ts
scopes/defender/linter/linter.main.runtime.ts
scopes/workspace/workspace/workspace.ts

- Adding the option to pass a "component" argument to only lint this component
- Adding the `-c` option to only lint changed/new components in the current workspace

update `bit lint` cmd to support component arg & `changed` option

---

README.md
scopes/compilation/compiler/compiler.main.runtime.ts
scopes/compilation/compiler/dist-artifact.ts
scopes/compilation/compiler/exceptions/dist-artifact-not-found.ts
scopes/compilation/compiler/exceptions/index.ts
scopes/component/graph/graph-builder.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/component/isolator/symlink-dependencies-to-capsules.ts
scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts
scopes/scope/scope/scope-component-loader.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts

- do not mutate scope component by workspace component
- filter components with the upcoming version (by tag) from workspace manifest
- provide an option to pass host to isolator and pass it when loading aspects from the scope
- get dists files api for compiler

Capsules filter components upcoming version + do not mutate scope component

---

scopes/generator/generator/component-template.ts
scopes/generator/generator/generator.main.runtime.ts
scopes/generator/generator/templates.cmd.ts
scopes/generator/generator/workspace-template.ts

I added a hidden property on templates so that they don't show up when you use `bit templates` (just to make sure that no one uses this for now).
You can use `bit templates --show-all` to show hidden templates.

add the ability to hide templates for `bit templates` cmd

---

scopes/compilation/multi-compiler/multi-compiler.compiler.ts
scopes/docs/docs/docs.main.runtime.ts
scopes/mdx/mdx/index.ts
scopes/mdx/mdx/mdx.compiler.ts
scopes/mdx/mdx/mdx.main.runtime.ts

- add new API for docs aspect to get the patterns
- do not compile mdx files that matches the docs pattern by the mdx compiler
- fix should copy non supported files for multi compiler
- get the dist path for src file by the multi compiler by the first matching compiler

fix tagging mdx components

---

scopes/compilation/compiler/workspace-compiler.ts

Currently, if component files were deleted, the dist directory inside `node_modules/<component-name>` still has them, which leads to confusion in some scenarios. 
With this fix, during `bit compile` (or `bit watch` as long as it rewrite the entire component), before it writes the dists files, it removes the directory.

clean the dist directory inside node-modules before writing the new dists

---

build-harmony/package.json
src/links/node-modules-linker.ts

As a result of not symlinking all files in the workspace one by one, but symlinking the entire dir to 'src' folder (see #4135 ), `bit status` showed errors when importing scss files.
The reason is that scss files are imported using the entire file-path inside the component and not from the main index file. This path didn't exist anymore.
This PR takes care of these files and symlink only them. The rest are handled with the `src` dir symlink.

fix bit-status when importing scss files (regression due to #4135)

---

e2e/harmony/set-default-owner-and-scope.e2e.4.ts
src/constants.ts
src/links/node-modules-linker.ts

Practically, roll back #4135 changes for Linux users and apply them only for Windows users.
Also, change the dir of `src` to `_src`, to not conflict with a potential user's src dir.
To sum it up, with this change:
Linux users -> symlink each one of the files. No dir symlink.
Windows users -> symlink each one of the files if possible (admin), otherwise, hard-link. Also, symlink _src to the entire dir.
The reason for this rollback is that sometimes it is needed to import/require an internal file, e.g. for .scss files (see #4178 ) or for config files (webpack/babel).
Therefore, for all users we have to have a symlink/hardlink of each one of the files to the root of node_modules/component-dir. 
Doing so, leaves us with the IDE navigation issue on Windows when using hard-link, because it …

symlink _src dir from node_modules to source files for Windows users only

---

src/links/node-modules-linker.ts
src/utils/fs/create-symlink-or-copy.ts

This was the purpose in https://github.com/teambit/bit/pull/4182. However, in that PR, by mistake it hard-linked for Linux as well.

hard link source-files from node_modules on Windows only, for Linux, symlink them

---

e2e/bit-hub/import-from-bit-hub.ts
e2e/commands/import2.e2e.1.ts
e2e/commands/lane.e2e.1.ts
e2e/commands/remove.e2e.1.ts
e2e/commands/snap.e2e.2.ts
e2e/flows/dist-outside-components.e2e.2.ts
e2e/flows/id-with-wildcard.e2e.2.ts
e2e/flows/out-of-sync-componets.e2e.3.ts
e2e/flows/remote-commands-outside-workspace.e2e.2.ts
e2e/functionalities/components-index.e2e.2.ts
e2e/harmony/http.e2e.ts
e2e/harmony/remove-harmony.e2e.ts
src/api/consumer/lib/untrack.ts
src/cli/commands/public-cmds/untrack-cmd.ts
src/cli/templates/all-help.ts
src/cli/templates/remove-template.ts
src/consumer/component-ops/delete-component-files.ts
src/consumer/component-ops/remove-components.ts
src/consumer/component/package-json-utils.ts
src/e2e-helper/e2e-command-helper.ts

Resolves #4051 .
- deprecate `bit untrack`.
- enable removing new components by `bit remove`, which opens the possibility to delete the component files.
- fix `bit remove` for Harmony to delete the component root-dir.
- fix deleting the directories from node-modules for new components.

enable deleting files for new components, deprecate "bit untrack"

---

src/consumer/versions-ops/merge-version/three-way-merge.ts

Before making the comparison between the file-system and the model, change the EOL to be LF (same procedure done before saving the component into the model).

fix bit-checkout on Windows to not get conflicts due to EOL changes

---

scopes/compilation/compiler/compiler.cmd.ts
scopes/compilation/compiler/compiler.main.runtime.ts
scopes/compilation/compiler/workspace-compiler.ts

Due to a recent change of #4177 , the dist directory is deleted before compilation. 
This causes an issue with watch processes, such as Webpack that expect the dist dir to be there.  (reported by @odedre ).
Here is an example error from Webpack:
```
watchpack Error (watcher): Error: EINTR: interrupted system call, watch '/Users/davidfirst/teambit/bit/node_modules/@teambit/panels/dist
```
This PR changes the default to not delete the dist dir unless it's `bit compile`.

avoid deleting the dist directory during watch

---

e2e/harmony/custom-env.e2e.ts
src/e2e-helper/e2e-bit-jsonc-helper.ts
src/e2e-helper/e2e-scope-helper.ts

These tests were failing due to `pnpm` hard-links. Switching to Yarn fixed the issue.

fix custom-env e2e-tests on Windows

---

.circleci/config.yml

It's not needed for a while now as the tests are isolated from bit.dev.

CircleCI - remove the bit.dev login configuration step

---

src/consumer/component/package-json-file.ts
src/consumer/component/package-json.ts
src/links/node-modules-linker.ts
src/utils/packages/resolve-pkg-data.ts

currently, the generated package.json inside node_modules, looks like the following:
```
{
"name": "@my-scope/bar",
"main": "dist/foo.js",
"componentId": {
"name": "bar"
},
...
```
The "scope" is missing from the componentId prop.

add the defaultScope to the componentId prop of package.json of a new component

---

src/utils/packages/resolve-pkg-name-by-path.spec.ts
src/utils/packages/resolve-pkg-name-by-path.ts

Resolve #3663.
Currently, if the import statement has something like this: `~@teambit/base-ui.theme.colors/colors.module.scss` and the package is not installed, it shows only `~@teambit`. 
This PR fixes it to show the full package-name `@teambit/base-ui.theme.colors`

Fix bit-status to show missing scoped packages with tilda correctly

---

scopes/react/react/react.env.ts
scopes/react/react/webpack/webpack.config.preview.dev.ts
scopes/ui-foundation/ui/webpack/webpack.dev.config.ts

- uncomment source-map-loader for `bit start --dev`
- limit loader to apply only to bit components, filtering by `componentId` field in package.json
- also use the same filter for Preview, instead of pre-calculating dists.
I tried this out on Symphony, bit-bin, and Evangelist.

re-enable source map loader for main UI dev

---

scopes/ui-foundation/react-router/react-router/index.ts

- expose routing components via the react-router aspect
this will allow bit extensions to use the Routing components as bit core, and control the location.

expose routing components via the react-router aspect

---

.bitmap
scopes/react/react/index.ts
scopes/react/react/webpack/postcss.config.ts
scopes/react/react/webpack/webpack.config.preview.dev.ts
scopes/react/react/webpack/webpack.config.preview.ts
scopes/ui-foundation/ui/webpack/webpack.base.config.ts
scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
scopes/webpack/style-regexps/index.ts
scopes/webpack/style-regexps/style-regexps.docs.md
scopes/webpack/style-regexps/style-regexps.ts

- webpack styles regexps component
- add style regexp to bit
- use style regexp component in ui foundation webpack configs
- use postcss inline instead of passing a config path (to improve extendability)
- export postcss config as regular object
- use style regexps component in react webpack configs 
- add css modules rule for ui foundation webpack dev config
- re-export styles regexps from react aspe

Webpack improvements

---

scopes/scope/scope/routes/fetch.route.ts
src/scope/objects/object-list.ts

This is an attempt to determine what's going on from the server side when the client gets `server terminated the stream unexpectedly` error. 
(here for example: https://app.circleci.com/pipelines/github/teambit/bit/11698/workflows/b85c09bd-9576-44ca-850b-d314fe75165a/jobs/149434).

add more logs to better understand stream issues during fetch

---

e2e/harmony/create.e2e.4.ts
scopes/generator/generator/generator.main.runtime.ts

Reported by @debs-obrien . 
Currently it shows an obscure error `Cannot read property 'loadAspects' of undefined`.

throw ConsumerNotFound when running bit-create outside a workspace

---

e2e/harmony/create.e2e.4.ts
scopes/component/legacy-bit-id/exceptions/invalid-scope-name.ts
scopes/component/legacy-bit-id/index.ts
scopes/generator/generator/generator.main.runtime.ts

Reported by @debs-obrien . 
This is happening when `--scope` flag of `bit create` gets an invalid scope.

throw an error when an invalid-scope was entered to bit-create command

---

scopes/react/react-native/react-native.main.runtime.ts
scopes/react/react-native/webpack/webpack-transformers.ts

- support useWebpack in react-native API
- use useWebpack in raect-native to mutate the react webpack config
- remove overridePreviewConfig and overrideDevServerConfig from react-native

support useWebpack in react-native API

---

package.json
scopes/workspace/modules/match-pattern/match-pattern.spec.ts
scopes/workspace/modules/match-pattern/match-pattern.ts
scopes/workspace/variants/variants.docs.md
workspace.jsonc

- this will break the previous `{namespace/*}` which will now won't match longer names like `{namespace/inner-ns/name}`

support `*` and `**` in variants namespaces selectors

---

scopes/component/deprecation/deprecation.main.runtime.ts

Resolve #4215.
Currently, they're shown only after re-running `bit start`. It is fixed by clearing the scope cache once the http executes the deprecation logic.

Fix deprecation commands to be shown on the UI 

---

e2e/harmony/custom-env.e2e.ts
src/scope/component-ops/get-flattened-dependencies.ts

Currently it shows a cryptic error `scope.getVersionInstance - id <component-id> is missing the version`.
This is happening when an environment is configured in the workspace.jsonc but is not part of the workspace (it's in the `.bitmap` file). In which case, the env-id must include a version.

throw a descriptive error during tag when an external env is configured without a version in workspace.jsonc

---

src/cli/command-registry.ts

Due to a regression caused by #4289, many flags aren't working on the CLI. (on the CI they're fine as `chalk` removes the special characters).
This PR fixes the flags and the aliases while keeping the help page of the commands styled. It also separates the flags from the global-flags.

fix commands flag after a regression caused by #4289

---

scopes/component/component-issues/missing-packages-dependencies-on-fs.ts

Here is the problem, on Harmony, if I delete the node_modules dir and run `bit status` it shows this message:
```
> comp1 ...  issues found
missing packages dependencies (make sure you've added it to the package dependencies, and use `bit install` to make sure all package dependencies are installed. On Harmony, run also `bit compile`):
index.ts -> @my-scope/comp2
```
This is not accurate. No package is missing. What's missing is the symlink between node_modules and the component in the workspace.
In the legacy we could "guess" by the package-name what is the component-name, and accordingly shows a different "missing-links" message.
In Harmony, it's impossible. The import statement `import comp2 from "@my-scope/comp2"` can be an external package and can be a component. If there is a …

fix missing-package-on-fs message to mention the missing link scenario

---

scopes/component/changelog/ui/change-log-page.module.scss
scopes/component/changelog/ui/change-log-page.tsx
scopes/compositions/compositions/compositions.module.scss
scopes/compositions/compositions/compositions.tsx
scopes/defender/tester/ui/tests-page.module.scss
scopes/defender/tester/ui/tests-page.tsx
scopes/design/ui/alert-card/alert-card.module.scss

- adds spacing at bottom of card to see shadow
- changes width to be seen properly as was cut off on larger acreens
- adds isPresentational for separator in changelog page
- 
From:
To:

fix: alert card visual improvements

---

scopes/compilation/compiler/compiler.task.ts

and only for the seeders.
Currently, for Babel compiler, which compiles only seeders and not the entire graph, the copy-files mechanism runs on the entire graph. 
In cases where a component has one env and a dependency has another env and one of them configured to copy-non-supported-files and the other does not, the file is always copied. 
This PR fixes it by running the copy process on the seeders only. 
Also, it runs it on the pre-build phase to avoid cases when TS finds other components by their dists and fails with an error about missing scss files. (it basically fixes the issue caused #4300 to fail).

fix copy-non-supported-files during build to happen in the pre-build phase

---

scopes/react/react/component.json

Reported by @debs-obrien . When using CRA it shows an error about missing `@mdx-js/react`. 
@GiladShoham , please review. It is used in the webpack configuration of react-env, but when running `bit show react`, it's not a dependency. In this PR I added it to the component.json of react as a package dependency.

add @mdx-js/react package as a dependency of react env

---

src/cli/command-registry.ts
src/cli/command-runner.ts
src/logger/logger.ts

For example, when starting `bit add` command, the log shows this:
```
started a new command: "add [path...]" with the following data
```
It has been fixed to be:
```
started a new command: "add" with the following data
```

show the command-name in the logs and the loader correctly without the args

---

src/cli/commands/public-cmds/checkout-cmd.ts
src/scope/component-ops/tag-model-component.ts

This is happening when the aspectData of the Builder is undefined. 
It was happening to a user, however, sadly, all the attempts to reproduce it were failed. Therefore, a test can't be written and the root cause remains unclear.

fix "Cannot read property 'find' of undefined" error during tag

---

scopes/react/bit-react-transformer/meta-from-pkg-json.ts
scopes/react/react/webpack/webpack.config.preview.ts

- build preview: limit webpack loaders to source files only 
- build preview: apply highlighter transformer to bit's node_modules packages only
This improved the build time on Evangelist from 6min to 4min (~30%!)

improve build webpack loaders

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/component/dependencies/dependency-resolver/overrides-dependencies.ts

- Make sure that when we added a component dependency by its package name (for example from env's get dependencies function) we resolve the package name correctly

resolve manually added component dependency package name

---

scopes/component/component-url/scope-url.spec.ts

component `teambit.component/modules/component-url` was incorrectly tagged as `@teambit/.modules.component-url`.
According to @GiladShoham, this only happened because it was tagged for the first time.
So, this should be fixed by a tag to be:
`@teambit/component.modules.component-url`

add tests to scope-url

---

e2e/commands/tag.e2e.1.ts
e2e/harmony/status-harmony.e2e.ts
scopes/component/component-url/scope-url.spec.ts
src/cli/commands/private-cmds/cat-object-cmd.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/component/dependencies/files-dependency-builder/build-tree.spec.ts
src/consumer/component/dependencies/files-dependency-builder/build-tree.ts
src/consumer/component/dependencies/files-dependency-builder/generate-tree-madge.ts
src/consumer/component/dependencies/files-dependency-builder/missing-handler.ts
src/consumer/component/dependencies/files-dependency-builder/types/dependency-tree-type.ts
src/e2e-helper/e2e-command-helper.ts
src/utils/packages/resolve-pkg-data.ts

- fix `missing packages` on bit-status when dists are missing and the main file is not an index.js/ts file.
- refactor the dependencies resolution results to be a class.
- change the old name `bits` in these dependency-resolution files to `components`.

fix missing-packages warning when dists are missing, refactor the DependenciesResults

---

scopes/workspace/workspace/watch/watcher.ts
src/cli/default-error-handler.ts
src/consumer/bit-map/exceptions/missing-bit-map-component.ts

These two commands `bit watch` and `bit start` use the `Watcher` service of the workspace.
In case error is happening during the handle-change process, the error is thrown, which introduces two issues:
1. these services shouldn't break, they should show the error and continue running.
2. the error is thrown inside an event-handler of `chokidar` and is not handled correctly. as a result we get unhandled promise.
This PR wrap the vulnerable code in try/catch to avoid it.

avoid crushing bit-start and bit-watch on errors

---

scopes/component/component-issues/component-issue.ts
scopes/component/component-issues/custom-module-resolution-used.ts
scopes/component/component-issues/import-non-main-files.ts
scopes/component/component-issues/index.ts
scopes/component/component-issues/issues-list.ts
scopes/component/component-issues/missing-dists.ts
scopes/component/component-issues/parse-errors.ts
scopes/component/component-issues/relative-components-authored.ts
scopes/component/component-issues/relative-components.ts
scopes/component/component-issues/untracked-dependencies.ts
scopes/workspace/workspace/workspace-component/workspace-component.ts
scopes/workspace/workspace/workspace.graphql.ts
scopes/workspace/workspace/workspace.ts
src/cli/templates/component-issues-template.ts

This will be helpful to show the issues (normally shown in `bit status`) in the web UI.
Query for example:
```
query {
workspace {
components {
id {
scope,
name
}
issuesCount,
issues {
type,
description
data
}
}
}
}
```

add GrpahQL query to get component issues

---

e2e/harmony/add-harmony.e2e.ts
src/consumer/component-ops/add-components/add-components.ts
src/consumer/component-ops/add-components/exceptions/parent-dir-tracked.ts

E.g. .bitmap has an existing component located in `comp1`, and the user is running `bit add comp1/foo`.
Currently, it shows `ComponentNotFound` error, which is very confusing. 
This has been fixed to show the following error:
```
➜  bit add comp1/foo
unable to add "comp1/foo", an existing component "comp1" already has its parent-dir "comp1" as the root-dir.
if you would like "comp1/foo" as a separate component, please extract it outside "comp1"
```

show a descriptive error when adding a sub-dir of a tracked directory

---

scopes/react/react/react.env.ts

- fixing 
```
or TS2339: Property 'toHaveValue' does not exist on type 'JestMatchersShape<Matchers<void, HTMLElement>, Matchers<Promise<void>, HTMLElement>>'.
9     expect(input).toHaveValue("test value");
``` 
during bit build
- resolves #4004

added "@types/testing-library__jest-dom" as dev dependency for react components

---

src/hooks/hooks-manager.ts
src/scope/actions/export-persist.ts
src/scope/component-ops/export-scope-components.ts
src/scope/objects/bit-object-list.ts
src/scope/objects/repository.ts
src/scope/repositories/sources.ts

Currently, when this is happening, the cache is populated/deleted unpredictably. 
With this change, the cache is not used for persisting the data. Instead, the data is aggregated from different functions and then written at once.

avoid caching objects during export to allow multiple bit-sign exporting to the same scope at the same time

---

scopes/harmony/cli/cli-parser.ts
scopes/harmony/cli/command-runner.ts

- enable Yargs completion for command-names and flags.
- customize the completion to auto-complete component names in some commands.
- color the flags in the help with green.

enable basic autocomplete in the CLI

---

e2e/commands/import2.e2e.1.ts
scopes/component/component-issues/component-issue.ts
scopes/component/component-issues/custom-module-resolution-used.ts
scopes/component/component-issues/import-non-main-files.ts
scopes/component/component-issues/missing-components.ts
scopes/component/component-issues/missing-custom-module-resolution-links.ts
scopes/component/component-issues/missing-dependencies-on-fs.ts
scopes/component/component-issues/missing-dists.ts
scopes/component/component-issues/missing-links.ts
scopes/component/component-issues/missing-packages-dependencies-on-fs.ts
scopes/component/component-issues/parse-errors.ts
scopes/component/component-issues/relative-components-authored.ts
scopes/component/component-issues/relative-components.ts
scopes/component/component-issues/resolve-errors.ts
scopes/component/component-issues/untracked-dependencies.ts
scopes/workspace/workspace/workspace.graphql.ts

This way it's easier to show only the issues in the UI, without mixing the suggested solutions inside the issue description.

component-issues: split the description field to description and solution

---

scopes/harmony/cli/cli-parser.ts
scopes/harmony/cli/cli.main.runtime.ts
scopes/harmony/cli/completion.cmd.ts

So it'll be shown in the main help and also users won't get errors when running it.
This command shows the script to add to the bash/zsh to enable the auto-complete.

add "completion" as a command

---

scopes/dependencies/dependency-resolver/dependency-linker.ts
scopes/dependencies/dependency-resolver/index.ts
scopes/workspace/workspace/link/link-to-dir.ts
scopes/workspace/workspace/link/link.cmd.ts

The functionality is similar to `npm link` or `yarn link`.  It is helpful when other projects depend on the this workspace. 
From the current workspace run `bit link --target <external-dir>`, it'll create symlinks from the node_modules of the current workspace to the target-dir/node_modules directory.

introduce "bit link --target" to link components to another project

---

scopes/react/react-native/react-native.main.runtime.ts
scopes/react/react/react.main.runtime.ts

Sometimes we want to pass only the second param, the object with the types option, but without the requirements of passing also a tsconfig file because we don't need it.
So I changed tsconfig to be optional. 
For example I can use the function like that:
```
reactNative.overrideTsConfig(undefined, {types: [dtsPath]}),
reactNative.overrideBuildTsConfig(undefined, {types: [dtsPath]}),
```
And send "undefined" without getting a TS error.

make tsconfig optional in overrideTsConfig function

---

e2e/flows/dependencies-as-packages.e2e.2.ts
e2e/functionalities/custom-module-resolutions.e2e.2.ts
e2e/harmony/mix-harmony-legacy.e2e.ts
scopes/component/component-issues/issues-list.ts
scopes/component/component-issues/legacy-inside-harmony.ts
src/consumer/component-ops/component-writer.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/scope/component-ops/tag-model-component.ts

- prevent importing legacy components inside Harmony workspace
- prevent tagging components that have legacy dependencies installed as packages
- `bit status` shows warning when a component is legacy inside Harmony

prevent using legacy components in Harmony workspace

---

babel.config.js
package.json
scopes/pipelines/builder/build-pipeline-order.ts
scopes/pkg/pkg/publisher.ts
scopes/workspace/eject/components-ejector.ts
src/scope/models/model-component.ts

This is done by adding [babel-plugin-ramda](https://github.com/megawac/babel-plugin-ramda) to the babel config. 
It knows to convert `import R, {map} from 'ramda';` into:
```
import add from 'ramda/src/add';
import map from 'ramda/src/map';
```

enable tree shaking for Ramda to avoid loading the entire lib

---

src/utils/fs/create-symlink-or-copy.ts

This is happening when `EXDEV` error is shown on Windows. Currently, it fallback to the fs native but doesn't use the `junction` option.

fix EPERM error on Windows during bit-link

---

scopes/harmony/aspect/babel/babel-config.ts

Currently, if the path includes `.ui` or `.preview` it doesn't apply the lazy-loading improvements.

remove lazy-loading exclusion from ui and preview files

---

e2e/harmony/clear-cache.e2e.ts
package.json
src/consumer/bit-map/bit-map.ts
src/consumer/bit-map/component-map.ts
src/consumer/component-ops/add-components/add-components.ts
src/consumer/component/consumer-component.ts
src/utils/fs/last-modified.ts
workspace.jsonc

The slowness of this cache was caused by a few factors:
1. calling `cacache` multiple times, one for each component.
2. globbing all components dirs to get their sub-dirs for checking the timestamp to potentially invalidate the cache.
3. accessing the stat for each one of the dirs and sub-dirs. 
4. the glob was sync.
5. the glob was fetching node_modules dir inside the components dir.
Even when fixing some of the points above, still, keeping the cache was a bit slower than not using it.
The big improvement after removing the cache was switching the `glob` package with `globby`.

remove components file-paths cache to improve performance

---

e2e/harmony/custom-env.e2e.ts
scopes/scope/scope/scope-component-loader.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
src/consumer/component/component-loader.ts

Currently, if the out-of-sync mechanism adds a scope-name to a component, a user might get ComponentNotFound in some scenarios.

fix out-of-sync id changes to work well on Harmony

---

scopes/component/component/aspect-list.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/component/legacy-bit-id/bit-id.ts
scopes/dependencies/dependency-resolver/dependencies/dependency-list.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.ts
scopes/dependencies/dependency-resolver/manifest/deduping/index-by-dep-id.ts
scopes/dependencies/dependency-resolver/manifest/deduping/merge-with-root.ts
scopes/dependencies/dependency-resolver/policy/variant-policy/variant-policy.ts
scopes/dependencies/dependency-resolver/policy/workspace-policy/workspace-policy.ts
scopes/dependencies/pnpm/get-registries.ts
scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
scopes/harmony/cli/cli.main.runtime.ts
scopes/harmony/config/workspace-config.ts
scopes/pipelines/builder/build-pipeline-result-list.ts
scopes/pkg/pkg/pkg.main.runtime.ts
scopes/react/react/react.main.runtime.ts
scopes/scope/export/export-cmd.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/workspace/modules/match-pattern/match-pattern.ts
scopes/workspace/variants/variants.main.runtime.ts
scopes/workspace/workspace/watch/watcher.ts
scopes/workspace/workspace/workspace.ts

If not possible, or difficult, import specific files from Ramda lib. 
This helps to avoid bringing the entire Ramda lib into bit.

replace ramda with lodash in Harmony code wherever possible

---

workspace.jsonc

- bump design icon button to v0.2.1
- should fix dependencies (react was direct, instead of peer)

update design button

---

e2e/harmony/publish.e2e.4.ts
e2e/harmony/tag-harmony.e2e.ts
scopes/component/component-id/component-id.ts
scopes/component/component-version/version.ts
scopes/component/component/tag-map.ts
scopes/component/legacy-bit-id/bit-id.ts
scopes/pipelines/builder/build.cmd.ts
scopes/pkg/pkg/pkg.main.runtime.ts
scopes/pkg/pkg/publisher.ts
scopes/scope/scope/scope.main.runtime.ts
src/api/consumer/lib/tag.ts
src/cli/commands/public-cmds/tag-cmd.ts
src/consumer/bit-map/component-map.ts
src/consumer/consumer.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/component-ops/tag-model-component.ts
src/scope/models/model-component.ts
src/scope/scope.ts
src/utils/resolveLatestVersion.spec.ts
src/utils/resolveLatestVersion.ts
src/utils/semver-helper.ts

Currently it's impossible.
With this PR, you can `bit tag --pre-release dev` to get a pre-release version with "dev" identifier. 
Then, on the following tags, you can omit the identifier and just `bit tag --pre-release` to increment it. 
Alternatively, you can use an exact version, e.g. `bit tag --all 1.0.0-alpha.2`.
Added support in the GrpahQL query of Component at packageManifest.distTag, see screenshot.
Todo:

support pre-release tagging

---

scopes/component/component/show/show.cmd.ts
scopes/harmony/cli/cli-parser.ts
scopes/harmony/cli/yargs-adapter.ts
scopes/pkg/pkg/pack.cmd.tsx
scopes/pkg/pkg/publish.cmd.tsx
scopes/workspace/workspace/eject-conf.cmd.tsx
src/cli/commands/private-cmds/ci-update-cmd.ts
src/cli/commands/public-cmds/build-cmd.ts
src/cli/commands/public-cmds/deprecate-cmd.ts
src/cli/commands/public-cmds/init-cmd.ts
src/cli/commands/public-cmds/isolate-cmd.ts
src/cli/commands/public-cmds/login-cmd.ts
src/cli/commands/public-cmds/remove-cmd.ts
src/cli/commands/public-cmds/show-cmd.ts
src/cli/commands/public-cmds/undeprecate-cmd.ts

currently, if a flag had a typo, it continues without indicating the issue, which is confusing.
With this change, it stops the process and shows the help page.

disallow non-exist options and commands

---

.circleci/config.yml
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
workspace.jsonc

- new config for dependency resolver workspace config - installFromBitDevRegistry - let you decide if you want to be proxied by the bit.dev registry
- set the installFromBitDevRegistry config to false on bit repo to make sure we are not consuming packages from bit.dev registry

Skip bit dev registry

---

CONTRIBUTING.md
package.json

and add `full-setup:bit` script to use `bit` from `bvm` to build bit-bin.

instruct users to build bit-bin using full-setup:bit in CONTRIBUTING.md

---

scopes/scope/update-dependencies/update-dependencies.cmd.ts
scopes/scope/update-dependencies/update-dependencies.main.runtime.ts

Otherwise, it could save local data in the ModelComponent into the original remote-scope unexpectedly.  For example:
```
"state": {
"versions": {
"3.0.13": {
"local": true
}
}
}
```

bit-update-dependencies, validate that this command is running from a new bare scope

---

scopes/scope/scope/scope-component-loader.ts
src/api/scope/lib/cat-object.ts
src/scope/objects/repository.ts

Currently, it only shows the ENOENT error with no stack. It is fixed to show the stack in the log and also, if the error is coming from the ScopeComponentLoader, it shows the component whose this object belongs to.

improve the error when an object file is missing from the filesystem

---

scopes/typescript/typescript/typescript.parser.ts

Add class compositions support for the typescript parser: users can now export a class and it will be detected as a valid composition (which is important for Angular since it uses classes for almost everything)

support class compositions for typescript

---

scopes/react/react/docs/docs-app.tsx
scopes/react/react/docs/docs.headers.module.scss

- introduce the css variables overrides used by Documenter.
- these will be included in `@teambit/documenter.theme.theme-context` `v4.0.1`, and replaced once all usages are updated.
(left is too big, right is the correct one)

fix large headers in docs

---

scopes/react/bit-react-transformer/bit-react-transformer.ts

- remove `path.stop()`, which caused all babel plugins to stop.
- add guard to each visitor.
- perf should be ok, since webpack only runs the plugin for components (and not say, npm packages)
This fixes error "Module parse failed", that happens when adding a new composition file.
```
ERROR in ./src/components/react04.composition.tsx 8:9
Module parse failed: Unexpected token (8:9)
File was processed with these loaders:
* ../../bit-bin/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
* ../../bit-bin/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export function BasicReact01() {
|   // return null;
>   return <React01 text="hello from React02" />;
| }
| 
```
(I wonder how this ever worked before, it …

fix: ״module parse error" when adding composition file

---

scopes/scope/scope/scope-component-loader.ts
src/scope/objects/repository.ts

This is happening because the `TagMap` on Harmony wasn't aware of the orphaned-versions (tags that are coming from a non-origin scope). This is fixed by including these versions in the TagMap.

fix ENOENT error upon loading components when it has orphaned versions

---

scopes/compilation/bundler/dev-server.service.ts
scopes/webpack/webpack/config/webpack.dev.config.ts

We were using the wrong output path in the webpack config (on windows AND linux/mac), it was only causing an error on windows because of the way ntfs absolute paths work.
The root cause is in this function:
```
const resolveWorkspacePath = (relativePath) => path.resolve(workspaceDir, relativePath);
```
Our relative path was actually absolute (it was starting with a leading `/`), which was generating a wrong resolve (see: https://github.com/nodejs/node/issues/14719#issuecomment-321370167).

fix watch mode on Windows & EPERM / EBUSY errors

---

e2e/harmony/harmony-workspace.e2e.ts
e2e/harmony/mix-harmony-legacy.e2e.ts
src/consumer/bit-map/bit-map.ts
src/consumer/component/component-loader.ts

Currently, when asking the Workspace aspect for an older version of a component, we get a mix of the current version with the old version data, which later on, result in ComponentNotFound error. 
This is a regression started since https://github.com/teambit/bit/pull/4414, which we ignored the scope/version when loading a component.
In this PR, a different approach was taken for the out-of-sync issue. Instead of ignoring the scope/version, we save the old-id and the new-id in case of out-of-sync, so later on, we could retrieve the updated data of that id.

fix getting old versions of components from the workspace

---

scopes/lanes/diff/index.ts
scopes/lanes/diff/lane-diff-generator.ts
scopes/lanes/diff/lane-diff.cmd.ts
scopes/lanes/lanes/lane.cmd.ts
scopes/lanes/lanes/lanes.graphql.ts
scopes/lanes/lanes/lanes.main.runtime.ts
src/e2e-helper/e2e-command-helper.ts

- introduce `getLanes()` query to list all lanes.
- introduce `getLaneByName(name)` to show one lane.
- introduce `getCurrentLaneName()` to get the current lane name when on the workspace.
- introduce `getDiff(values)` to get diff between lanes.

Add GraphQL queries for list-lanes, show-lane and lane-diffs

---

e2e/harmony/build-cmd.e2e.ts
scopes/harmony/bit/load-bit.ts
src/consumer/consumer-loader.ts

For now, It's needed for the e2e-tests. 
It wasn't working before because some state were left from the previous `loadBit` called.

enable calling loadBit multiple times in the same process

---

scopes/compilation/babel/babel.compiler.ts
scopes/preview/preview/preview.main.runtime.tsx
scopes/react/react/react.env.ts
scopes/react/react/webpack/webpack.config.component.dev.ts
scopes/react/react/webpack/webpack.config.component.prod.ts

- improve babel replace file ext to js to only replace if the file is supported
- point webpack entry files for compositions and docs to the dist files instead of the source files
- remove webpack rules with bit-react-transformer by file map
Before this change the link modules in the entry file for the webpack looks like this:
Workspace (dev server)
```
linkModules("overview", defaultModule, {
"my-comp": [
require("workspace-path/my-comp/my-comp.composition.tsx"),
],
});
```
Capsule (build/tag):
```
linkModules('overview', defaultModule, {
'my-comp': [require('capsules/8cf3a1e5b3f8b8d890c4e18a256129f06a3b00e1/my-comp@0.0.5/dist/my-comp.composition.tsx')],
});  
```
This means that we give webpack the source files for the dev server, but for build/tag, we give it the dist files (after …

Webpack entry files dev server dist

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/dependency-resolver/exceptions/index.ts
scopes/dependencies/dependency-resolver/exceptions/invalid-version-with-prefix.ts
scopes/workspace/workspace/install.cmd.tsx
scopes/workspace/workspace/workspace.ts

- add an option to configure savePrefix via dependency-resolver config
- add an option to configure savePrefix via bit install --save-prefix
- resolves #4175 
With this PR you can now:
1. configure `"savePrefix"` in the workspace.jsonc under `teambit.dependencies/dependency-resolver`
for example `"savePrefix": "~"`
2. pass `--save-prefix` flag to `bit install command. for example `bit install lodash.get --save-prefix="^"`
3. In case of conflicts between the install flag and the dep resolver config in workspace.jsonc, the install flag is stronger.
4. default is just empty string which behave as save exact version

add option to configure savePrefix for bit install

---

workspace.jsonc

- change the (default) env of components having a namespace - from 'aspect' to be 'node'
- this should change the following components:
- `teambit.compositions/model/composition-type`
- `teambit.compositions/model/composition-id`
TODO

apply env 'node' for components using namespace

---

scopes/compilation/babel/babel.compiler.ts
scopes/compilation/modules/babel-compiler/babel-compiler.ts

Currently, when using Babel compiler, the source maps include absolute paths to the capsules. This PR fixes it to have the source-map always relative to the source file.

fix source-map on capsules, replace absolute paths with relative

---

scopes/compilation/compiler/workspace-compiler.ts

currently it's taken into account only during the build process (on the capsules).

respect the "shouldCopyNonSupportedFiles" compiler option for the compilation in the workspace

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts

With this PR if you have a scoped registry that points to bit.dev registry configured in your npmrc file, bit will know automatically to send it with bit's token without you need to configure it manually.
for example, let's say you have this entry in your .npmrc file
`@my-org-bit:registry=https://node.bit.dev`
Bit will take its auth token from (ordered)
A token defined for the `@bit` scoped registry, or bit's `user.token` as defined in your bit global config

Add auth headers to scoped registries point to bit.dev registry

---

scopes/defender/linter/linter.main.runtime.ts
scopes/react/eslint-config-bit-react/bit-react-eslint.js
scopes/react/react/component.json
scopes/react/react/eslint/eslintrc.js
scopes/react/react/react.env.ts
yarn.lock

- change eslintrc.ts to eslintrc.js in react env
- fix linter extensions formats
- add eslint-plugin-mdx as dependency to react env
- use the `eslint-config-airbnb-typescript` only for ts/js files (including jsx/tsx/mjs)
- add md/mdx rules to react env linting config, using the plugin:mdx/recommended

Bit mdx lint fixes

---

src/api/consumer/lib/global-config.ts
src/constants.ts

- resolved #4488 
The formant of the variables is as follow:
- starts with BIT_CONFIG
- any "." in the config name will be replaced with "_"
- upper case
for example:
instead of doing bit config set user.token <token>
you can set an env variable called BIT_CONFIG_USER_TOKEN

support getting any bit config via environment variable

---

scopes/harmony/cli/cli.cmd.ts
scopes/harmony/cli/cli.main.runtime.ts
scopes/harmony/cli/generate-doc-md.ts

Also, change `generate` to be a sub-command of `bit cli`, rather than a flag.

allow customizing the metadata/front-matter of the .md file generated by bit cli generate

---

scopes/dependencies/dependency-resolver/dependencies/dependency-list.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
scopes/harmony/aspect-loader/index.ts

Before this pr if you had a custom aspect imported into your workspace, and this custom aspect uses another custom aspect is an aspect dependency (via the static dependencies prop) it will fail to find this custom aspect dependency in harmony engine because it was resolved without the correct version.
This PR fixes it by updating the manifest dependencies recursively before send them to harmony.

resolve custom aspects versions when they are aspect deps of another custom aspect

---

scopes/defender/jest/jest.main.runtime.ts
scopes/defender/jest/jest.tester.ts
scopes/defender/jest/jest.worker.ts
scopes/react/react/react.env.ts
scopes/react/react/react.main.runtime.ts

- We use the jest instance from the env for regular tests, but the tests displayed in the "tests" tab of the preview are using a worker that was using jest from bit instead. Since we cannot pass the jest module directly to the worker, we pass the path to require it instead

use jest instance from env for jest worker

---

scopes/component/isolator/isolator.main.runtime.ts
src/consumer/component-ops/component-writer.ts
src/consumer/component/sources/artifact-files.ts

Currently, if multiple components are isolated, it fetches missing artifacts for each one individually. With this fix, it starts the import only once all artifacts are grouped per scope.

optimize artifacts fetching during capsule creation to be grouped by scope

---

scopes/generator/generator/workspace-generator.ts

Currently, `.bit` directory is located in the workspace root.
See https://github.com/teambit/bit/issues/4056 for more info about `bit new`.

bit-new - fix bit scope to be inside .git dir

---

scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
scopes/webpack/webpack/config/webpack.dev.config.ts

- disable `firewall` (previously `disableHostCheck` in v3) in webpack dev server
This will allow using the local dev server with a different url so companies like Dell can access their API without Cross-Origin Resource Sharing errors. We already use it internally to work on symphony and a dev version of `bit.dev`.
Reference to the config can be found [here](https://sourcegraph.com/github.com/webpack/webpack-dev-server/-/blob/CHANGELOG.md):
> the disableHostCheck and allowedHosts options were removed in favor of the firewall option
```js
// Previously disableHostCheck and allowedHosts
module.exports = {
// ...
devServer: {
// Can be
// firewall: ['192.168.0.1', 'domain.com']
firewall: false,
},
};
```

remove url limitations

---

.bitmap
scopes/react/react/compositions-app.tsx
scopes/react/ui/loader-fallback/index.ts
scopes/react/ui/loader-fallback/loader-fallback.compositions.tsx
scopes/react/ui/loader-fallback/loader-fallback.docs.mdx
scopes/react/ui/loader-fallback/loader-fallback.spec.tsx
scopes/react/ui/loader-fallback/loader-fallback.tsx

- fixes bug where we'd get an error message "not found" when changing composition name
- shows a loader when composition turns to undefined
- shows "not found" error after timeout (15 seconds!) or when component starts undefined.

show a loader when compositions are having a hard time loading

---

src/scope/lanes/lanes.ts

It's a regression since renaming `master` to `main`.

fix an error "unable to export the following lanes master"

---

scopes/mdx/modules/compiler/mdx-compiler.ts

For example, a component has an .mdx file with the following content:
```
---
label: ['a', 'b'];
---
```
Which is an invalid syntax because of the `;`.
`bit status` gives:
```
> bar ...  issues found
error found while parsing the file (edit the file and fix the parsing error):
test.mdx -> All collection items must start at the same column
```
It's improved to show a better error:
```
> bar ...  issues found
error found while parsing the file (edit the file and fix the parsing error):
test.mdx -> failed extracting metadata/front-matter using Yaml lib, due to an error: All collection items must start at the same column
```

provide better error when yaml fails to parse front-matter in mdx files

---

scopes/typescript/aspect-docs/typescript/typescript.mdx
scopes/typescript/typescript/typescript.compiler.ts

This is done to avoid confusion when the distDir is `x` and ts-config outDir is `y`, in which case, the dists in the capsule are written into `y`, but other bit processes expect to find them in `x`.

override typescript outDir configuration with CompilerOption.distDir

---

scopes/generator/generator/component-generator.ts
scopes/workspace/workspace/workspace.ts

Currently, it shows a confusing error message:
```
unable to add individual files outside the root dir (shoe/ui/button) of ui/button.
you can add the directory these files are located at and it'll change the root dir of the component accordingly
```
Now, it shows a better error
```
unable to create a component "ui/button", a component with the same name already exist
```

improve error when "bit create" generates a component with an existing name

---

scopes/generator/generator/workspace-generator.ts
scopes/generator/generator/workspace-template.ts
scopes/harmony/config/index.ts
scopes/harmony/config/workspace-config.ts
scopes/react/react/templates/react-workspace-learn-bit/index.ts
scopes/react/react/templates/react-workspace/files/workspace-config.ts
scopes/react/react/templates/react-workspace/index.ts

- change "react-workspace" template to re-use the default workspace.jsonc template.
- change the `generateFiles` API to return a promise.

preserve workspace.jsonc comments when creating workspaces via bit-new

---

scopes/generator/generator/generator.main.runtime.ts
scopes/generator/generator/new.cmd.ts

To shorten the feedback loop, this PR introduces `--load-from` flag, which lets using a template from an existing workspace. 
Otherwise, the workspace-template needs to be tagged and exported before using it and for each change.

bit-new - support using templates from another workspace

---

e2e/harmony/build-cmd.e2e.ts
scopes/pkg/pkg/pack.task.ts
scopes/pkg/pkg/pkg.main.runtime.ts
scopes/pkg/pkg/publish.task.ts

Currently, the pack is done during the publish-task. As a result, the snap-pipeline, doesn't generate the .tgz file, as it doesn't run the publish-task by default.
This PR makes them two separate tasks and register the pack-task to the snap-pipeline.

extract pack-task from the publish-task

---

e2e/commands/lane.e2e.1.ts
scopes/scope/export/export-cmd.ts
src/cli/commands/public-cmds/fetch-cmd.ts
src/consumer/component-ops/components-diff.ts
src/consumer/component-ops/components-object-diff.ts
src/scope/lanes/README.md
src/utils/fs/save-into-os-tmp.ts

- fix `bit lane diff` to not throw `git EPERM` errors. It happened because the tmp dir containing the files to diff were deleted prematurely. 
- remove the `id` field when running diff, it is not needed and confusing.

bit-lane-diff: fix git EPERM error and remove the redundant id field

---

scopes/ui-foundation/cli/ui-server-console/ui-server-console.tsx
scopes/ui-foundation/ui/start.cmd.tsx
scopes/ui-foundation/ui/ui-server.ts
scopes/ui-foundation/ui/ui.main.runtime.ts

- open browser on `bit start`
- allow setting a custom `publicUrl` to open instead of local host (@itaymendel  FYI)
example configuration:
```json
"teambit.ui-foundation/ui": {
"publicUrl": "https://sym.bit.dev"
},
```

Bit start open browser + publicUrl

---

scopes/react/react/component.json
scopes/react/react/webpack/webpack.config.base.ts
scopes/ui-foundation/ui/webpack/webpack.base.config.ts
workspace.jsonc

- replace `babel-plugin-named-asset-import` with svgr and native webpack5 tools
- remove svgr from main-ui (we don't have any inline svgs, but they are still allowed)
resolves #4462

replace babel-svg-loader with svgr+new-url-loader

---

scopes/ui-foundation/ui/start.cmd.tsx

- add `--no-browser` flag to bit start, to skip opening the browser.
- this replaces `suppress-browser-launch` which is harder to type / understand

reintroduce flag to skip opening the browser on bit start

---

src/scope/models/lane.ts

For backward compatibility reasons, we need to have special treatment for the previous main-lane "master". For this reason, it's better to disallow users from creating it.

disable creating a lane "master" as it used to be the main lane

---

scopes/react/react/templates/react-workspace-learn-bit/files/types/asset.ts
scopes/react/react/typescript/asset.d.ts
scopes/react/react/webpack/webpack.config.base.ts

- add the svgr props included in the previous setup, as per @marella's comment [here](https://github.com/teambit/bit/pull/4595#pullrequestreview-709393730):
- pass titleProp
- pass ref
- (do not disable `svgo` svg optimizer.)
- add the types needed to tag svg-as-react. (`ReactComponent`)
- add the same types to the `react-workspace-learn-bit` template. (not sure how to check it, but `bit new` isn't user facing yet)

Fix svgr + svg types

---

scopes/scope/ui/scope-title/scope-title.composition.tsx
scopes/scope/ui/scope-title/scope-title.tsx

- a temp fix because the API not return the background icon color at the moment.

scope title fix

---

e2e/commands/import2.e2e.1.ts
e2e/commands/lane.e2e.1.ts
src/consumer/bit-map/bit-map.ts
src/consumer/component-ops/component-writer.ts
src/e2e-helper/e2e-command-helper.ts

Currently, when switching lanes from main to an existing remote-lane dev, and then back to main, and then again to dev, the .bitmap has the wrong version, which result in the wrong bit-status when switching again to main.  (yes, lots of switching are needed to see the issue).

fix bit-status when switching lanes back and forth

---

scopes/generator/generator/templates.cmd.ts
scopes/generator/generator/templates/component-generator/index.ts
scopes/generator/generator/templates/workspace-generator/index.ts
scopes/html/html/html.main.runtime.ts
scopes/html/html/templates/html-component/index.ts
scopes/mdx/mdx/mdx.templates.ts
scopes/mdx/mdx/templates/mdx-component/index.ts
scopes/react/react/react.templates.ts
scopes/react/react/templates/react-component-js/index.ts
scopes/react/react/templates/react-component/index.ts

- shorten names for bit create but keep others as hidden so no breaking changes. both bit create react-component and bit create react will work
- add links to docs for workspace and component generators

shorten template names

---

scopes/defender/eslint/eslint.linter.ts
scopes/defender/eslint/eslint.main.runtime.ts
scopes/react/react/react.env.ts
workspace.jsonc
yarn.lock

- upgrade @types/eslint
- merge eslint options with context during createLinter
- add default transformer for react env get linter which adds md and mdx files
- ignore extensions that are not part of the extension list during linting
- update yarn.lock file
- resolves #4606

Lint files extensions

---

e2e/commands/lane.e2e.1.ts
src/links/linker.ts

Currently, when the dependent is import, during the link process, it re-imports the dependency and override its head.

fix merging lanes when a dependency is local

---

src/consumer/component/component-loader.ts

Currently, `.bitmap` is not taken into account when deleting the dependencies cache. As a result, after lanes merge, some components are modified as they have the old dependencies from the cache.

clear dependencies cache after .bitmap changes

---

scopes/scope/export/export-cmd.ts
src/api/consumer/lib/export.ts
src/scope/component-ops/export-scope-components.ts
src/scope/models/model-component.ts
src/scope/objects/repository.ts

Mostly useful when running `bit export --all` to export all versions, not only staged. In which case, the artifacts of old versions are in the remote but probably not exist locally.

bit-export: introduce a new flag "--ignore-missing-artifacts"

---

e2e/harmony/new.e2e.ts
scopes/generator/generator/generator.main.runtime.ts

Currently, it's allowed and it ends up in an invalid state of a workspace inside another workspace.

block running bit-new inside a workspace

---

scopes/scope/models/scope-model/scope.model.ts
scopes/scope/scope/ui/scope-overview/scope-overview.tsx

- Update scope model with `backgroundIconColor`.
- Create props `ScopeModelProps` for scope.
- Use the backgroundIconColor in ScopeOverview.

add backgroundIconColor to scope model and use it in ScopeOverview

---

scopes/design/ui/Avatar/styles.module.scss

- replace css var with correct string as the background parameter for imgix
Example of the problem:
Should look like this:

fix avatar default bg color

---

e2e/harmony/new.e2e.ts

They're not failing on CircleCI with a strange error, after trying to install a non-exist package: `@teambit/react.templates.env.templates`.

fix bit-new tests

---

.bitmap
workspace.jsonc

- update `workbox-webpack-plugin` from `6.1.5` to `6.2.2`
- should fix #4706

fix dep - cannot find module workbox-build

---

scopes/generator/generator/workspace-generator.ts
scopes/generator/generator/workspace-template.ts

Resolve #4683.
With this prop, when creating a workspace template, you can set different component names than the original.

introduce "targetName" prop to the components added during bit-new

---

e2e/harmony/out-of-sync-components-harmony.e2e.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts

In case userA has locally tagged a new version, but not exported. He then pushes his changes to the repo. Someone else (or a CI process) tries to load the repo, some commands such as bit build fail because the new version only exists on the local scope of the author, and nowhere else.
These scenarios were fixed in the legacy by a process called 'out-of-sync'. It would change the .bitmap and remove the local version.
This PR fixes the issue on Harmony by synchronizing the component-id between the legacy and Harmony.

fix running bit-build when components are out-of-sync

---

scripts/docker-teambit-bit/README.md

- fixes a typo in 
where `bitcli/bit-server:latest` image is used instead of the `bitcli/bit:latest`.

fixes cli image name in docker command

---

scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts

currently, when `bit new --aspect <component-id>` has no version, it load the latest version from the cache. If a new version was published, it doesn't check for it and just reload the last one. 
This PR re-imports the aspect in this case to make sure it always has the lastest.

bit-new: import the latest component if --aspect component has no version

---

e2e/harmony/graph-harmony.e2e.ts
scopes/component/graph/index.ts
scopes/component/graph/object-list-to-graph.ts
scopes/scope/scope/scope.main.runtime.ts
src/scope/component-ops/traverse-versions.ts

Add a new API to convert an array of bit objects to a graph when the nodes are component ids and the edges are the type of the dependency (either `runtime` or `dev`).

add an API to convert ObjectList to IdGraph

---

e2e/harmony/new.e2e.ts
scopes/generator/generator/generator.main.runtime.ts

Currently, it shows an unhelpful error: `failed loading extension teambit.workspace/workspace`.
With this PR it shows a descriptive error:
```
fatal: "/non/exist/workspace" is not a valid Bit workspace, make sure the path is correct
```
Reported by @debs-obrien .

bit-new: improve the error when --load-from was entered with an invalid workspace

---

e2e/harmony/workspace-config.e2e.ts
scopes/harmony/bit/load-bit.ts

Currently, the error only says that the string is not a component-id but it doesn't say where it was taken from.
The new error shows this:
```
unable to parse the component-id "non-comp" from the workspace.jsonc file, make sure this is a component id
```
Reported by @ranm8 .

improve error when the workspace.jsonc has a non-component key

---

scopes/workspace/workspace/workspace.ts

When using an external aspect and creating a custom env that extends this external aspects, we need to load the external aspect first otherwise it cannot be injected into the local custom env

fix aspects loading order for custom envs

---

e2e/harmony/custom-env.e2e.ts
scopes/component/component-issues/issues-list.ts
scopes/component/component-issues/multiple-envs.ts
scopes/component/component/state.ts
scopes/envs/envs/environments.main.runtime.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
scopes/workspace/workspace/workspace.ts
src/e2e-helper/e2e-bit-jsonc-helper.ts
src/e2e-helper/e2e-extensions-helper.ts
workspace.jsonc

When a component has multiple envs, it's probably due to replacing the env and not removing the old env via the variants. 
This PR shows a warning in `bit status` in such case and blocks `bit tag` from tagging until it's fixed.
See https://github.com/teambit/bit/issues/4753 for more context.

warn for multiple envs

---

scopes/generator/generator/workspace-generator.ts

Currently, it installs some of the packages inside the node_modules of the components. 
This PR fixes it by passing the correct parameters to `workspace.install()` method.
Reported by @ranm8 .

fix installation during bit-new to have the general node_modules with common packages

---

scopes/generator/generator/new.cmd.ts
scopes/generator/generator/workspace-generator.ts

Asked by @ranm8 , to make the flag clearer.

bit-new: rename --standalone flag to --skip-git

---

e2e/commands/export.e2e.1.ts
package.json
src/e2e-helper/e2e-scope-helper.ts
yarn.lock

Also, upgrade fs-extra from 9.x to 10.x to fix coping dirs with broken symlinks (see https://github.com/jprichardson/node-fs-extra/pull/779). 
This makes the copy scopes during tests much faster and less error prone.

e2e-tests: remove "dereference" option from the copy on linux

---

scopes/react/react/react.main.runtime.ts

related to https://github.com/teambit/bit/discussions/4764
resolves #4757

fix passing types in compiler options when using react.overrideTsConfig and react.overrideBuildTsConfig

---

src/cli/commands/public-cmds/import-cmd.ts
src/consumer/component-ops/import-components.ts
src/consumer/consumer.ts
src/scope/component-ops/scope-components-importer.ts

Currently, `bit import` with no ids brings only the delta between the local and the remote. In some rare cases, objects are still missing. This flag fetches all objects.

bit-import: introduce a new flag "--all-history" to skip optimizations and bring all history objects

---

e2e/commands/lane.e2e.1.ts
src/api/consumer/lib/untag.ts
src/scope/component-ops/untag-component.ts
src/scope/models/model-component.ts

Currently, when creating a lane, snapping and then running `bit untag -a` it says "no components found with version to untag on your workspace" incorrectly.
This PR fixes it by changing the way of fetching staged-components to be the same as `bit status`.

fix untag to work on lane snaps

---

e2e/commands/lane.e2e.1.ts
scopes/lanes/lanes/lane.cmd.ts
scopes/lanes/lanes/lanes.main.runtime.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/scope-json.ts

- introduce `bit lane track` to change the remote-scope and the remote-name of a local-lane.
- introduce new flags `--remote-scope` and `--remote-name` to `bit lane create`.
- by default, when creating a new lane and no `--remote-scope` entered, use the default-scope from the workspace.jsonc

introduce "bit lane track" to change the remote-scope of a lane

---

e2e/commands/lane.e2e.1.ts
scopes/lanes/lanes/lanes.docs.md
scopes/scope/export/export-cmd.ts
src/api/consumer/lib/export.ts
src/consumer/lanes/export-lanes.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/component-ops/export-scope-components.ts

Currently, it's required to specify a remote when exporting lanes. 
With this change, Bit uses the tracking data from scope.json to get the remote-scope of the current lane.
Also, the options to export multiple lanes is disabled. Only the current lane is allowed to be exported. 
The `--lanes` flag is removed, as it's not needed anymore.

export current lane to its tracked remote-scope

---

e2e/harmony/http.e2e.ts
e2e/http-helper.ts
scopes/scope/scope/scope.graphql.ts
scopes/ui-foundation/ui/start.cmd.tsx
scopes/ui-foundation/ui/ui-server.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/graph/scope-graph.ts
src/scope/network/http/http.ts

- resolve #4601, fix "bit import --dependents` in Harmony.
- fix `bit log --remote`. it stopped working since https://github.com/teambit/bit/pull/3673.
- fix http e2e-tests to start working again. 
- remove `report` method from `bit start` command, seems like it's not needed (and it makes issues to the e2e-tests).

 implement "graph" method in http

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
src/consumer/component/dependencies/files-dependency-builder/build-tree.ts
src/scope/network/ssh/ssh.ts

Currently, Bit allows installing legacy component packages inside Harmony workspace, and then when running `bit build`, it shows a cryptic error from the TSCompiler: `error TS2307: Cannot find module '@bit/legacy-package-name' or its corresponding type declarations`.
Now, when loading the component, it shows the following error:
```
error: legacy dependency "legacy-package-name" was imported to one of the files in "/component/dir".
this workspace is Harmony and therefore legacy components/packages are unsupported.
remove the import statement to fix this error
```
Also, when importing a legacy component into Harmony, it used to show the following inaccurate error:
```
unexpected network error has occurred during fetching scopes: bit.envs
server responded with the following error messages: …
```

improve errors when importing/installing legacy components/packages inside Harmony

---

e2e/harmony/status-harmony.e2e.ts
src/consumer/component/components-list.ts

If the component is new, it's a candidate for tagging, so no need to show it in the auto-tag-pending section. 
Reported by @ranm8 .

bit-status: don't show new components in the auto-tag-pending section

---

scopes/harmony/application/app.cmd.ts
scopes/harmony/application/application.main.runtime.ts

Deprecate `bit app-list` in favor of `bit app list`. 
Asked by @ranm8 .

replace "bit app-list" with "bit app list" to support app subcommands

---

scopes/generator/generator/component-generator.ts

Currently, the path where to place the component consists of the entered `--path` flag and the component full-name. With this PR, in case `--path` was entered, it will be used for the whole path. 
For example:
```
bit create react-component-js ui/button --path my-button
```
path before: `my-button/ui/button`.
path now:      `my-button`.
Asked by @ranm8 .
Also resolve https://github.com/teambit/bit/issues/4813.

bit-create: change --path flag to include the whole path and not only the root-dir

---

scopes/lanes/diff/lane-diff.cmd.ts

Before it looked like part of the "diff" section and was easily overlooked. 
Now the new section is more prominent.

bit-lane-diff:make the newComponents section more visible

---

e2e/commands/lane.e2e.1.ts
src/consumer/component-ops/remove-components.ts
src/scope/component-ops/remove-model-components.ts

Currently, when removing a new components when checked out to a lane, it shows a message that the component was removed from the lane, but it's still in the .bitmap file.
With this fix, it removes the component from the .bitmap file as expected.
Reported by @ranm8 .

fix removing new components when on a lane

---

e2e/harmony/custom-env.e2e.ts
scopes/compilation/compiler/workspace-compiler.ts
scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/workspace/workspace/capsule.cmd.ts
src/e2e-helper/e2e-command-helper.ts
src/e2e-helper/e2e-env-helper.ts

When loading aspects from isolated capsules, they may throw MODULE_NOT_FOUND error due to missing/corrupted packages or maybe the previous capsule installation never completed.
With this fix, in this case, the capsule is recreated and the aspect is re-loaded.

recreate capsules in case they errored with MODULE_NOT_FOUND

---

e2e/harmony/custom-aspects.e2e.ts
scopes/scope/scope/scope.main.runtime.ts

The added e2e-test makes sure that when the aspects in the current workspace depend on external aspects, the loading order is correct.

add tests for external aspects loading order

---

src/bootstrap.ts
src/doctor/core-diagnoses/validate-bit-version.ts

Currently, it works with the legacy version and shows "fails" incorrectly.

bit-doctor: fix validate-bit-version to work with Harmony version

---

e2e/harmony/artifacts.e2e.ts
scopes/scope/scope/scope.main.runtime.ts
src/e2e-helper/e2e-command-helper.ts

Currently, it shows an error:
```
scope was not defined directly or by "envs/my-react@0.0.1"
```
Reported by @giteden .

fix bit-artifacts command when a component was not exported yet

---

scopes/component/component-id/component-id.ts
scopes/envs/envs/environments.main.runtime.ts
workspace.jsonc

When a component has an env set up via `"teambit.envs/envs"`, then this is the only env.

avoid showing the multiple-envs issue when it has "envs" set

---

e2e/harmony/status-harmony.e2e.ts
src/cli/commands/public-cmds/status-cmd.ts

This is helpful for automation tools such as a CI to make sure the status is fine.

bit-status: introduce a new flag --strict to exit with code 1 when issues found

---

scopes/typescript/modules/ts-config-mutator/ts-config-mutator.spec.ts
scopes/typescript/modules/ts-config-mutator/ts-config-mutator.ts

using `typescript.addExclude(['one', two'])` ends up creating a tsconfig like this:
```ts
{
// ...
exclude: [
["one", "two"]
]
}
```
this PR simply fix it to be:
```ts
{
// ...
exclude: [
"one",
"two"
]
}
```

fix tsconfig exclude

---

scopes/react/react/component.json
scopes/ui-foundation/ui/component.json

- lock version of sanitize.css to be 12.0.1 when postcss-normalize is used (it's an indirect dependency)
It was caused by https://github.com/csstools/sanitize.css/issues/225

lock version of sanitize.css (remove when postcss-normalize supports 13+)

---

scopes/workspace/workspace/watch/watcher.ts

Currently, if a component directory has the word `dist`, it's ignored by `bit watch`. 
It was done for historic reasons, when the "dist" dir was inside the workspace. Now it's not needed anymore.
Bug reported by @odedre .

fix bit-watch to watch components contain the word dist

---

scopes/preview/cli/preview-server-status/preview-server-status.tsx

When generating the bundle with compositions for bit start, we need to include all the files because we don't know what the user will end up importing, so it's normal to get this warning, but we need to hide it otherwise we will get bug reports for nothing

ignore unused file warning from ts

---

src/consumer/component-ops/many-components-writer.ts

Currently, since package installation takes place during import, the dists directories are deleted.
The "compile" process that happens after the installation was only compiling the imported component.
In this PR it has been fixed to compile all components on the workspace.

fix bit-import to recreate dists directories

---

scopes/ui-foundation/cli/ui-server-loader/ui-server-loader.tsx

- comment out `ink-spinner`  from `UIServerLoader`
- this avoids this bug - https://github.com/vadimdemedes/ink-spinner/issues/12
⚠️ Note we still use the problematic `cli-spinners` at `src/constants.ts`  
(though it may be safely locked to a specific version)
Before:
After:

comment out ink-spinner

---

scopes/react/react/webpack/webpack.config.base.prod.ts
scopes/ui-foundation/ui/ssr/render-middleware.ts
scopes/ui-foundation/ui/webpack/webpack.base.config.ts

- fix webpack manifest file (content was stringified twice, Ran was right, types were wrong)
- add logs to ssr middleware
waiting for https://github.com/shellscape/webpack-manifest-plugin/issues/276 to remove console logs

fix webpack manifest

---

scopes/preview/preview/preview.main.runtime.tsx

- Fixing name for the function `getPreviewComponentRootPath` on the `Compiler`

Fix compiler `getPreviewComponentRootPath` function name

---

e2e/harmony/publish.e2e.4.ts
scopes/pkg/pkg/packer.ts
scopes/pkg/pkg/pkg.main.runtime.ts

This dry-run task, runs `npm publish --dry-run` and `npm pack --dry-run`, which are mostly to show the user some output, but not a real test to make sure the publish will succeed. 
It takes long time to complete and the value it provides doesn't justify the performance penalty.
Also, configure the pack task to run in parallel or 10 at a time.

bit-build: remove publish/pack dry-run task

---

src/consumer/component/dependencies/files-dependency-builder/detectives/detective-css-and-preprocessors/index.ts
src/consumer/component/dependencies/files-dependency-builder/detectives/detective-sass/index.spec.ts

The dependency detection currently only recognizes `@import`.
This PR adds support for the newer syntax of `@use` and `@forward`.

support scss "@use" and "@forward" to function the same as "@import"

---

workspace.jsonc

This fixes the warning shown in the log from time to time about invalid aspects.

configure non-aspects component to use the node-env instead of the aspect-env

---

scopes/ui-foundation/tree/folder-tree-node/folder-tree-node.module.scss
scopes/ui-foundation/tree/folder-tree-node/folder-tree-node.tsx
scopes/ui-foundation/tree/folder-tree-node/index.ts
workspace.jsonc

- Use base collapsable tree node from [base-ui](https://bit.dev/teambit/base-ui/graph/tree/collapsable-tree-node).
- Move `getCustomIcon` function upper in the file - eslint recommendation.
- Remove unnecessary import with the use of the new collapsable component.

use base collapsable tree node in folder tree node

---

scopes/pipelines/builder/build.cmd.ts
scopes/workspace/workspace/workspace.ts

Implements the `bit build` part of #5050.
- if no pattern entered, build only new and modified components.
- introduce `--all` flag to build all components. 
- indicate how many components are about to be built when build started.
- show a descriptive message when there is no components to build.

bit-build: if no pattern is specified, build only new and modified components

---

src/scope/models/model-component.ts

Currently it's slow due to traversal on the entire versions graph. This is fixed by re-using the `getDivergeData` method which traverse the graph more efficiently.

improve bit-status performance dramatically when components have lots of versions

---

scopes/typescript/ts-server/ts-server-client.ts
scopes/typescript/typescript/cmds/check-types.cmd.ts
scopes/typescript/typescript/typescript.main.runtime.ts

Currently, checking types is done as part of `bit watch --check-types`. 
At times, this is needed as part of the CI process, so a dedicated command is very helpful.
By default is only type-checks modified/new components. Use `--all` to check them all. 
Use `--strict` to exit with code 1 in case types error were found.

introduce a new command "bit check-types" to check for typescript errors

---

scopes/explorer/ui/component-card/component-card.composition.tsx
scopes/explorer/ui/component-card/component-card.tsx

- Add `href` prop to support external link.
- Add a composition with an external link example.
- Remove `isInternal` prop because it's not used at all.
- Move `isDeprecated` default value to the function instead of `defaultProps` object.

update component card to support external link

---

src/cli/commands/public-cmds/list-cmd.ts

- Fixed subparam alias 'ids' that was not working for command 'list'
Steps to reproduce:
`bit list -ids`
> bit list -h
> Usage: list|ls [options] [scope]
> 
> list components on a local or a remote scope.
>   https://docs.bit.dev/docs/view#list
> 
> Options:
>   **-ids**, --ids               show only component ids unformatted
>   -s, --scope               show all components of the scope, including indirect dependencies
>   -b, --bare                DEPRECATED. use --raw instead
>   -r, --raw                 show raw output (only components ids, no styling)
>   -o, --outdated            show latest versions from remotes
>   -j, --json                show the output in JSON format
>   -n, --namespace <string>  show only specified namespace by using wildcards
>   --skip-update …

bugfix fixed 'list' param alias not working

---

.circleci/config.yml
tsconfig.json

- configure Circle to run the build-types task on Windows.
- configure tsconfig.json to preserve comments in the d.ts files of bit-legacy.

fix(circle-ci): run the build:types task before the tests to fix Windows tests on Circle

---

.bitmap
package.json
scopes/harmony/bit/app.ts
scopes/harmony/bit/load-bit.ts
scopes/toolbox/performance/v8-cache/file-system-blob-store.ts
scopes/toolbox/performance/v8-cache/index.ts
scopes/toolbox/performance/v8-cache/v8-compile-cache.ts
yarn.lock

Replacing v8-compile-cache with a custom version that you can disable on demand until https://github.com/zertosh/v8-compile-cache/issues/30 is fixed because it prevents ESM loaders to work. If TypeScript allows for native imports to work, we could probably re-enable this lib as well.

replace v8-compile-cache to support esm loaders

---

e2e/commands/import.e2e.1.ts

There is one legacy e2e-test failing on CircleCI Windows only. It doesn't reproduce locally, and not that important to invest time for. Skipped for now on Windows.

fix(circle-ci): skip a failing test on Windows

---

scopes/workspace/workspace/workspace.ts

Due to a recent change to `bit test` to include the dependents of the modified and new component, a new error appeared when multiple components have the same dependent:
```
found duplicated components: component-name@0.0.1
```
This PR fixes it by making sure the dependents ids are unique and there are no duplications.

fix(test): remove redundant ids when calculating the dependents of modified and new components

---

workspace.jsonc

- This new version includes a fix for Heading titles that was only an h3, now they will be h1, h2, h3, h4, h5, h6.
- CSS fix with `max-width: 100%` to only img instead of everything.

install new version of documenter markdown mdx

---

scopes/react/react/react.env.ts
scopes/react/react/webpack/webpack.config.component.dev.ts
scopes/ui-foundation/ui/ui-server.ts
scopes/ui-foundation/ui/webpack/webpack.dev.config.ts

- use fast refresh loader explicitly, with the existing Webpack heuristics! Thanks to https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/456
- remove hacks trying to set which packages / components should be included by the plugin.
This should improve:
- webpack perf in large projects
- enable hot reloading for newly created components
- fix race condition errors around MDX.

use react fast refresh loader explicitly where relevant

---

e2e/commands/import2.e2e.1.ts

This is the second legacy e2e-test failing on CircleCI Windows only. It doesn't reproduce locally, and not that important to invest time for. Skipped for now on Windows. (a similar one was fixed a few days ago - https://github.com/teambit/bit/pull/5076).

fix(circle): skip another legacy e2e-test on Windows

---

scopes/harmony/aspect/aspect.env.ts
scopes/harmony/aspect/aspect.main.runtime.ts

To avoid publishing/packing TS files for Aspect env. See https://github.com/teambit/bit/pull/5032 for more context.
The problem we had with white listing the files, is that we ended up with some `**/*.*` patterns which caused out-of-memory upon `npm pack` during `bit tag`. Interestingly enough, this is happening with npm 7 only, not with npm 6.

fix(tag): switch from "package.json#files" to ".npmignore" 

---

e2e/commands/snap.e2e.2.ts
src/cli/commands/public-cmds/status-cmd.ts
src/e2e-helper/e2e-general-helper.ts
src/scope/component-ops/untag-component.ts
src/scope/repositories/sources.ts

Currently, when components have diverged from a remote, they're shown in `bit status` as "pending merge" with a suggestion to use `bit merge <id>`.
This `bit merge` command, creates a snap-merge with two parents, the local and the remote. While this is a good solution to keep the local snaps/tags, it is confusing for users to see the hash in the output of `bit merge` and later on in `bit status` and in the .bitmap file.
This PR, suggests to run `bit untag` instead. It also fixes `bit untag` to point to the remote head instead of the previous head. This way, after bit-untag is running the component model locally is the same as the remote and the status is `modified`.

fix(merge-pending): better handling diverge components

---

scopes/generator/generator/component-generator.ts
scopes/workspace/workspace/workspace.ts
src/consumer/component-ops/add-components/add-components.ts

This is related to the out-of-sync mechanism described in https://github.com/teambit/bit/discussions/5074. Specifically the last case. If the added component (during `bit add` or `bit create`) doesn't exist in .bitmap, and a similar component exists in the scope, we assume this is the same component and we re-adding the one from the scope to the .bitmap.
In case `bit create --scope` was used, and we know that the entered scope is different than the scope-name of the component found in the model, no need to make changes to the added component and we add it as new.
Bug was reported by @ranm8 .

fix(create): don't change newly created component scope from existing component in workspace.jsonc

---

src/consumer/component-ops/components-object-diff.ts

fix(diff): show the correct diff when multiple dependencies have the same name with different scope-name

---

scopes/react/react/compositions-app.tsx
scopes/react/ui/loader-fallback/index.ts
scopes/react/ui/loader-fallback/loader-fallback.docs.mdx
scopes/react/ui/loader-fallback/loader-fallback.tsx

- convert LoaderFallback component into a hook, so it will be included in the highlighter
- refactor
It specifically fixes this:
verified working with compositions and tests.

fix loader fallback getting into highlighter

---

e2e/harmony/dependency-resolver.e2e.ts
scopes/dependencies/aspect-docs/dependency-resolver/dependency-resolver.mdx
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
scopes/dependencies/yarn/yarn.package-manager.ts
scopes/workspace/workspace/workspace.ts
workspace.jsonc
yarn.lock

related PR in pnpm:
- https://github.com/pnpm/pnpm/pull/4050
For now, I only added the possibility to override by pkg name and pkg version. This has the same syntax in npm, pnpm, and Yarn. In order to override the pkg only when it is in the dependencies of a specified other package, we need to choose which syntax to use: yarn, pnpm, or npm. Looks like Yarn we cannot use, as it uses `>` as a separator.
Here's how to tell pnpm to override bar in the deps of `@scope/foo`:
```json
{
"overrides": {
"@scope/foo>bar": "1.0.0",
"@scope/foo": "3"
}
}
```
Here's the same with npm (although npm has not implemented it yet):
```json
{
"overrides": {
"@scope/foo": {
".": "3",
"bar": "1.0.0"
}
}
}
```
-
-
-

feat: support overrides

---

e2e/fixtures/extensions/elements-storage-resolver-env/elements-storage-resolver.env.ts
e2e/fixtures/extensions/elements-storage-resolver-env/elements-storage-resolver.extension.ts
e2e/fixtures/extensions/elements-storage-resolver-env/fake-storage-resover.ts
e2e/fixtures/extensions/elements-storage-resolver-env/index.ts
e2e/harmony/artifacts-storage-resolver.e2e.ts
scopes/pipelines/builder/artifact/artifact-definition.ts
scopes/pipelines/builder/artifact/artifact-factory.ts
scopes/pipelines/builder/artifact/artifact-list.ts
scopes/pipelines/builder/artifact/artifact.ts
scopes/pipelines/builder/artifact/index.ts
scopes/pipelines/builder/builder.main.runtime.ts
scopes/pipelines/builder/index.ts
scopes/pipelines/builder/storage/default-resolver.ts
scopes/pipelines/builder/storage/index.ts
scopes/pipelines/builder/storage/storage-resolver.ts
scopes/react/react-elements/react-elements.main.runtime.ts
scopes/react/ui/docs-app/component-overview/component-overview.tsx
scopes/web-components/elements/compute-results.ts
scopes/web-components/elements/compute-targets.ts
scopes/web-components/elements/elements-artifact.ts
scopes/web-components/elements/elements.main.runtime.ts
scopes/web-components/elements/elements.task.ts
src/consumer/component/consumer-component.ts
src/consumer/component/sources/artifact-files.ts
src/consumer/component/sources/artifact.ts
src/e2e-helper/e2e-env-helper.ts

- Storage resolver for artifacts is a way to provide a resolver that will store the artifact files in remote hosting, and store the public URL of the artifact in bit's objects
- remove unused artifact storage resolver slot
- change element to elements in some internal places

support storage resolver for artifacts

---

e2e/harmony/create.e2e.4.ts
scopes/workspace/workspace/workspace.ts
src/consumer/bit-map/bit-map.ts
src/consumer/bit-map/component-map.ts
src/consumer/component-ops/add-components/add-components.ts

Currently, upon creating a component, the defaultScope is determined by the workspace.jsonc file. With this PR, the `--scope` flag is taken into account and is used later to export to this scope.
Implementation wise, a new prop is added to the .bitmap file `defaultScope` and gets deleted upon `bit export`.

chore(create): improve "bit create --scope" to save the scope as the defaultScope

---

scopes/compilation/babel/babel.compiler.ts
scopes/compilation/compiler/compiler.cmd.ts
scopes/compilation/compiler/types.ts
scopes/compilation/compiler/workspace-compiler.ts
scopes/typescript/typescript/typescript.compiler.ts

This should fix an issue when you run `bit compile` when `bit start` is running in the background and get errors as a result of it

 delete the dist dir during compilation according to the specific compiler configuration

---

scopes/lanes/lanes/lanes.main.runtime.ts
scopes/lanes/lanes/switch.cmd.ts
src/cli/command-registry-builder.ts

Currently, to switch between lanes, you should run `bit switch`. This PR adds the command to be a sub-command of `bit lane`, so you could run also `bit lane switch`.

feat(lanes): add switch command as a sub-command of "bit lane" as well

---

scopes/ui-foundation/tree/tree-node/tree-node.tsx

- Remove default value `undefined` from TreeNode, so link will be able to calculate activity by itself.
- Code Tab tree (used with an explicit value - no defaults) - ✓ verified
Does not seem to be used anywhere else

treeNode - allow default undefined value for 'isActive'

---

e2e/commands/lane.e2e.1.ts
scopes/lanes/lanes/lanes.docs.md
src/api/consumer/lib/untag.ts
src/cli/commands/public-cmds/status-cmd.ts
src/consumer/bit-map/bit-map.ts
src/consumer/consumer.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/component-ops/untag-component.ts
src/scope/repositories/sources.ts

- fix workspace-lane to remove the component when unsnapped and is back to new.
- fix lane object to either remove the component or to update to the new head upon untag.
- avoid deleting the component object when one of the snaps were untagged and the head (on the lane) points to another snap.

fix(lane): update lane data when un-snapping on a lane

---

e2e/commands/lane.e2e.1.ts
src/scope/component-ops/untag-component.ts

currently, when on a lane, `bit untag comp1` throws "unable to untag comp1, the component is not staged" error.

fix(lanes): do not throw an error when specifying the component id in "bit untag" command

---

src/utils/packages/resolve-pkg-data.ts
src/utils/packages/resolve-pkg-name-by-path.ts

This is happening on Angular component for example. `bit status` shows a package `@angular/core/testing` as missing. 
With this PR, it parses the package-name correctly as `@angular/core` and finds it.
Reported by @ocombe .

fix(status): parse scoped-packages from a file-path correctly on Windows

---

e2e/harmony/untag-harmony.e2e.ts
src/scope/component-ops/untag-component.ts
src/scope/repositories/sources.ts

Currently, when tagging multiple versions locally and untagging them all, it shows a hash in the .bitmap as the version unexpectedly. 
Reported by @benjgil .

fix(untag): set the component head correctly when untagging multiple versions

---

e2e/harmony/create.e2e.4.ts
scopes/component/deprecation/deprecation.main.runtime.ts
scopes/envs/envs/environments.main.runtime.ts
scopes/generator/generator/component-generator.ts
scopes/generator/generator/component-template.ts
scopes/generator/generator/create.cmd.ts
scopes/generator/generator/index.ts
scopes/generator/generator/templates/component-generator/index.ts
scopes/generator/generator/templates/workspace-generator/index.ts
scopes/generator/generator/workspace-generator.ts
scopes/harmony/aspect/templates/aspect/index.ts
scopes/harmony/node/templates/node-env/index.ts
scopes/pipelines/builder/templates/build-task/index.ts
scopes/workspace/workspace/bit-map.ts
scopes/workspace/workspace/workspace.ts
src/consumer/bit-map/bit-map.ts
src/consumer/bit-map/component-map.ts
src/consumer/component-ops/add-components/add-components.ts
yarn.lock

With this improvement, a template can add `config` prop and specify the configuration of the various aspects. 
A real example from the aspect template, where the config is used to set the env to `teambit.harmony/aspect`. this way, when running `bit create aspect` no need to configure this in the workspace.jsonc manually.
```
{
name: 'aspect',
description: 'extend Bit capabilities',
generateFiles: (context: ComponentContext) => {  ... },
config: {
'teambit.harmony/aspect': {},
'teambit.envs/envs': {
env: 'teambit.harmony/aspect',
},
},
```
Specifically for envs, it also check whether the variants has other envs configured on this component and it makes sure to remove them, so that the component won't have multiple envs.

feat(create): support adding component configuration via the component-template

---

scopes/mdx/mdx/mdx.detector.spec.ts
scopes/mdx/mdx/mdx.detector.ts
scopes/mdx/modules/compiler/import-specifier.ts
scopes/mdx/modules/compiler/mdx-compiler.ts
src/consumer/component/dependencies/files-dependency-builder/detectives/detective-es6/index.ts
src/consumer/component/dependencies/files-dependency-builder/detectives/parser-helper.ts
workspace.jsonc

an interesting bug was found by @debs-obrien , where an mdx file has the following import statement:
```
import { removeFromCart } from './remove-from-cart';
```
and `bit status` shows a component-issue:
```
non-existing dependency files (make sure all files exists on your workspace):
btn.docs.mdx -> ./remove-
```
Turns out, the parser was used `parse-es6-imports` doesn't handle module names with dashes well. It splits them. So `./remove-from-cart` becomes `./remove-`. 
This PR fixes it by replacing that package with the legacy way of parsing ES6 import.

fix(mdx): parse module decleration with dashes correctly by the mdx detector

---

e2e/harmony/checkout-harmony.e2e.ts
src/consumer/component-ops/import-components.ts
src/consumer/versions-ops/checkout-version.ts
src/consumer/versions-ops/merge-version/merge-snaps.ts
src/consumer/versions-ops/merge-version/merge-version.ts
src/consumer/versions-ops/merge-version/three-way-merge.ts

Two bugs were fixed here:
1. component `comp` has a file `foo.ts` in version 0.0.1 and 0.0.2 and the user is on 0.0.1 and deleted foo.ts locally. When running `bit checkout latest comp`, the file was rewritten. This PR fixes it to leave the file deleted.  (reported by @GiladShoham ). 
2. the function `applyModifiedVersion` was updating the component files by mutating the `componentFiles` arg. It worked for most cases, but when files were removed, this arg was re-assigned, and as a result wasn't updating the original component files. It is fixed by returning a new array of modified files instead of mutating the existing one.

fix(checkout): avoid writing files that were deleted locally but exist on the checked out version

---

scopes/ui-foundation/react-router/react-router/index.ts
scopes/ui-foundation/react-router/ui/link/link.tsx
scopes/ui-foundation/react-router/ui/nav-link/nav-link.tsx

- allow react-router link implementation to receive the `component` prop
- expose `routing-provider` and `react-router`, so external aspects can get the same singleton instance
this will allow us to move the implementation of link base url to an external plugin

expose routing-provider from react-router aspect

---

e2e/harmony/rename.e2e.ts
scopes/component/forking/fork.cmd.ts
scopes/component/forking/forking.main.runtime.ts
scopes/component/new-component-helper/new-component-helper.main.runtime.ts
scopes/component/renaming/rename.cmd.ts
scopes/component/renaming/renaming.main.runtime.ts

to add the scope as the defaultScope and use it for the path calculation.

fix(rename/fork): fix "--scope" flag of bit-rename and bit-fork 

---

e2e/harmony/deprecate.e2e.1.ts
scopes/component/deprecation/deprecation.fragment.ts
src/consumer/component-ops/many-components-writer.ts
src/consumer/versions-ops/checkout-version.ts

Currently, when deprecating a component and trying to undo it by running `bit checkout --reset`, it doesn't do anything.
With this change, the config is removed and the component is not shown as modified anymore.

fix(checkout): remove config from .bitmap upon bit checkout --reset

---

scopes/component/forking/forking.main.runtime.ts
scopes/workspace/workspace/workspace.ts
src/api/consumer/lib/add.ts
src/consumer/component-ops/add-components/add-components.ts

Currently, when running `bit create` or `bit new` or `bit fork` and a similar component with the same name exists in the scope, Bit assume that this is the same component, which got out-of-sync and re-add it to the .bitmap. (see the last case here: https://github.com/teambit/bit/issues/1543 ). 
While this makes sense for `bit add`, it doesn't normally happen for other commands, such as create/new/fork. Recently, users having more and more different component with the same name in the scope and they expect these commands to create new components and not re-adding from the scope.

fix(fork): change component tracking to handle the out-of-sync only when running bit-add

---

e2e/harmony/rename.e2e.ts
scopes/component/renaming/rename.cmd.ts
scopes/component/renaming/renaming.main.runtime.ts
scopes/workspace/workspace/bit-map.ts

For new components, no need to deprecate the source component, as it wasn't saved in the model yet. It's cleaner to just rename the component in the .bitmap file.

fix(rename): simplify renaming new components to change the .bitmap only

---

workspace.jsonc
yarn.lock

Downgrade `@pnpm/default-reporter` to temporarily disable peer
dependency issues reporting.
-
-
-

fix: don't print peer dependency warnings

---

package.json
src/constants.ts

With a more recent version of ora, we can use unicode loaders on windows.
I tried the one that we use for unix (`bits12`) but it doesn't render well (not sure if it's just windows or it's just not a great loader?). So I used `bits` instead which is already what the preview loader uses anyway.

improve cli loader on windows

---

e2e/harmony/multiple-envs.e2e.ts
scopes/workspace/workspace/workspace.ts
src/e2e-helper/e2e-command-helper.ts

Component's extensions are merged from multiple places, such as `workspace.jsonc#variants` and `.bitmap#config`.  Currently, if these sources has different envs, `bit status` shows "multiple-envs" warning.
This PR changes this merge algorithm to ignore envs that are less concrete/strong.

fix(envs): choose the most concrete env when merging extensions from various sources

---

e2e/commands/lane.e2e.1.ts
src/consumer/bit-map/bit-map.ts
src/consumer/bit-map/component-map.ts

Normally, when snapping on a lane or switching to a non-main lane, the version is written to the workspace-lane, not to the .bitmap. The .bitmap file represents the main lane. always.
This PR fixes the case when switching lanes from a remote lane to not save the snap inside the .bitmap file.

fix(lanes): avoid replacing the version in .bitmap with the lane version when switching to a remote lane

---

e2e/commands/lane.e2e.1.ts
src/consumer/lanes/switch-lanes.ts
src/consumer/versions-ops/checkout-version.ts

- `lane switch` command now identifies the deleted files before switching and deletes them

Bug Fix: lane switch command doesn't delete files that don't exist in the switched lane

---

scopes/harmony/cli/cli-parser.ts
scopes/harmony/cli/command-runner.ts
src/cli/default-error-handler.ts
src/cli/handle-errors.ts
src/logger/logger.ts
src/scope/repositories/sources.ts

Currently, from the log it's hard to determine what the user typed in the CLI and what was the received output.
This PR logs these two with a distinctive prefix. E.g.
```
[2022-01-07 10:24:09.287 -0500] DEBUG (42404): [+] CLI-INPUT: lane merge dev
[2022-01-07 10:24:09.434 -0500] ERROR (42404): [+] CLI-OUTPUT: unable to switch to "dev", the lane was not found
```
Later, we can easily parse the log files and extract only the data the user saw in the terminal.

feat: log CLI input and output

---

pnpm-lock.yaml
workspace.jsonc

`@pnpm/headless` had a prod dependency in dev dependencies.
Related fix: https://github.com/pnpm/pnpm/commit/df69150fc6c880b24122b47b71a565cab0c5c8ea

fix: update pnpm dependencies

---

src/cli/handle-errors.ts

Error was "Expected 2 arguments, but got 3". It happened because for some reason the import statement in the legacy referred to the package "@teambit/legacy" instead of using the relative paths.

fix(types): fix typescript error in src/cli/handle-errors.ts 

---

scopes/dependencies/pnpm/lynx.ts

This fixes `bit install` on the bit-bin repository on Windows.
The generated command shims are too big when the node path env variable is set. And this is causing a crash when building dependencies. This property is not needed anyway.
- Don't extend [NODE_PATH](https://pnpm.io/npmrc#extend-node-path) in command shims.

Don't extend node path in command shims

---

package.json

otherwise, instead of running `bit` from the BVM, NPM tries to run them from the local binary.

chore: fix full-setup script to delete the binary "bit" first from the local node-modules

---

e2e/commands/lane.e2e.1.ts
src/consumer/lanes/merge-lanes.ts

- Update `mergeLanes` function to handle the case when the user is merging the `main` lane
- Update `mergeLanes` function to handle the case when the main lane is empty (has no snapped/tagged components)

fix(`lane merge`): `main` lane is not recognized and cannot be merged if it is empty

---

e2e/harmony/custom-env.e2e.ts
src/consumer/bit-map/bit-map.ts

Currently, during tag, when asking Harmony for aspect-ids, it returns them with the old version. 
With this fix, once the ids are resolved, they get the correct version.

fix(tag): resolve aspect-version correctly during the tag

---

e2e/harmony/checkout-harmony.e2e.ts
src/consumer/versions-ops/merge-version/three-way-merge.ts

This PR fixes the following use-case: comp1@0.0.1 has one file. comp1@0.0.2 has another file. When a user is checked out to 0.0.1 and is running `bit checkout latest --all` it doesn't write this new file.
(this is a regression caused by https://github.com/teambit/bit/pull/5192).
Reported by @NitsanCohen770 .

fix(checkout): write files that were introduce in a new version and does not exist on the filesystem

---

scopes/harmony/aspect/aspect.cmd.ts
scopes/harmony/aspect/aspect.docs.mdx
scopes/harmony/aspect/aspect.main.runtime.ts
scopes/harmony/graphql/graphql.main.runtime.ts
scopes/workspace/modules/match-pattern/match-pattern.spec.ts
scopes/workspace/modules/match-pattern/match-pattern.ts
scopes/workspace/variants/variants.main.runtime.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
scopes/workspace/workspace/workspace.provider.ts
scopes/workspace/workspace/workspace.ts

- `bit aspect list <component-id>` - list all aspect names configured on a component
- `bit aspect get <component-id>` - show aspects' data and configuration of the given component. (with `--debug` flag it shows the origins were the aspects were taken from).
- `bit aspect set <pattern> <aspect-id> [config]` - set an aspect to component(s) with optional config
- `bit aspect unset <pattern> <aspect-id>` - unset an aspect from component(s)

introduce "bit aspect" command to set/unset/list aspects

---

pnpm-lock.yaml
scopes/harmony/aspect/aspect.main.runtime.ts
scopes/workspace/workspace/envs-subcommands/envs-set.cmd.ts
scopes/workspace/workspace/envs-subcommands/envs-unset.cmd.ts
scopes/workspace/workspace/pattern.cmd.ts
scopes/workspace/workspace/workspace.provider.ts
scopes/workspace/workspace/workspace.ts
workspace.jsonc

- introduce `idsByPattern` API for the workspace that returns all matching component ids according to the pattern. A pattern may consist multiple patterns separated by a comma. Also, a pattern can exclude ids by the `!` syntax.
- introduce `bit pattern <pattern>` command to list the ids matching the pattern.

feat: improve "pattern" to accept multiple patterns and negate syntax

---

scopes/harmony/application/application.main.runtime.ts
scopes/preview/preview/env-preview-template.task.ts

- The Object.assign() method only copies enumerable and own properties from a source object to a target object. It uses [[Get]] on the source and [[Set]] on the target, so it will invoke getters and setters. Therefore it assigns properties, versus copying or defining new properties. This may make it unsuitable for merging new properties into a prototype if the merge sources contain getters.

use `cloneDeep` to copy the context in order to keep getters & setters

---

e2e/harmony/checkout-harmony.e2e.ts
src/e2e-helper/e2e-fixtures-helper.ts
src/utils/merge-files.ts

Currently, in case of a merge, e.g. when a file has conflicts, then in the written file, the last "\n" is removed.
The culprit was `execa`, which returned the data from Git without the last newline. This PR fixed it by changing the configuration of execa to not strip this newline.

fix(checkout): avoid stripping the newline when running Git to merge files

---

scopes/ui-foundation/notifications/ui/notification/notification.module.scss

- handle long notification messages that don't break line correctly
after fix:

fix long notifications

---

scopes/harmony/aspect/aspect.cmd.ts
scopes/harmony/cli/cli-parser.ts
scopes/harmony/cli/yargs-adapter.ts
scopes/workspace/workspace/envs-subcommands/envs-set.cmd.ts
scopes/workspace/workspace/envs-subcommands/envs-unset.cmd.ts
src/cli/command.ts
src/constants.ts

closes #5361 
- introduce "extendedDescription" property for `Command` class. this extended description is shown just after the "description" in the command help output, but not in the "bit --help" page.
- improve the bit env/aspect commands to explain what the `<pattern>` is. 
- re-construct the command help output so it's easier now to manipulate and add more data to different parts of the output.

feat: introduce "extendedDescription" prop for commands, add details about "<pattern>"

---

scopes/harmony/aspect-loader/constants.ts
src/consumer/component-ops/many-components-writer.ts
src/logger/logger.ts

during import/checkout to suggest using `--skip-dependency-installation` flag.
Asked by @ranm8 .

fix: improve error-message when PM fails to install packages 

---

e2e/harmony/import-harmony.e2e.ts
scopes/scope/importer/import.cmd.ts
src/cli/chalk-box.ts
src/consumer/component-ops/import-components.ts

- instead of listing all component-ids that are up-to-date, add `X components are up to date` to the title.
- instead of listing all the new versions imported to a component, show `N new versions available, latest x.y.z`.

feat: improve "bit import" output to show the total of up-to-date and total of new-versions

---

e2e/commands/lane.e2e.1.ts
src/consumer/lanes/switch-lanes.ts

currently, it shows an error `error: version "latest" of component comp1 was not found.`.

fix(lanes): fix an error when snapping on a lane, switching to main, then back to the lane

---

scopes/component/legacy-bit-id/exceptions/index.ts
scopes/component/legacy-bit-id/exceptions/invalid-scope-name-from-remote.ts
scopes/component/legacy-bit-id/index.ts
scopes/workspace/workspace/workspace.ts
src/api/consumer/lib/fetch.ts
src/remotes/remote-resolver/remote-resolver.ts

Currently, when the scope-name has no dot, it shows the following error:
```
error: "my-scope" is invalid, component scope names can only contain alphanumeric, lowercase characters, and the following ["-", "_", "$", "!"]
```
which is confusing to the end user, as the scope-name does comply with the scope-name requirements.
With this PR, when this happens, it shows the following error-message instead:
```
cannot find scope 'my-scope'.
if you are targeting a self-hosted scope, please ensure the scope is configured in your remotes (via "bit remote" command) and that the scope name is correct.
if this is a scope on bit.dev please add the organization name before the scope (yourOrg.some-scope-name)
```
Requested by @benjgil .

improvement: show a descriptive error when scope-name might be self-hosted or missing the org-name

---

scopes/workspace/eject/components-ejector.ts
scopes/workspace/workspace/workspace.ts
src/consumer/component-ops/eject-components.ts
src/consumer/component-ops/remove-components.ts
src/consumer/consumer.ts
src/scope/component-ops/remove-model-components.ts
src/scope/models/model-component.ts
src/scope/removed-components.spec.ts
src/scope/removed-components.ts
src/scope/removed-local-objects.ts
src/scope/scope.ts

Currently, when deleting a component, we loop through the flattened-dependencies and delete the dependencies from the scope if the following conditions were met:
1. locally: the dependency is not part of the workspace. (Not exist in .bitmap).
2. on remote: the dependency scope-name is different than the component-to-remove. This is to ensure we only delete "cache", never components belong to the current scope.
3. there is no dependents for this dependency in the scope OR there is a dependent but this dependent has different scope-name as the dependency.
According to the above, in the following scenario, we'll delete the dependency:
Comp-to-remove: scopeA/comp
dep-graph:
scopeA/comp -> scopeB/comp
scopeC/comp -> scopeB/comp
Since the dep "scopeB/comp" has a dependent but from a different …

fix: avoid removing dependencies when removing a component from the scope

---

e2e/harmony/env.e2e.ts
scopes/workspace/workspace/workspace.ts

Currently, when running `bit env set` and the .bitmap has another env from a previous run of the same command, it only removes it from the envs/envs, but not from the root.
Reported by @NitsanCohen770

fix: remove the previous env when running "bit env set"

---

scopes/dependencies/pnpm/pnpm.package-manager.ts

Hoisting types causes issues in some workspaces (for instance, in the symphony workspace).
By default `publicHoistPattern` is hoisting `@types`.
So we are overriding its value in order to exclude types.

fix(pnpm): don't hoist `@types`

---

scopes/scope/scope/scope.main.runtime.ts

Currently, the UI for bare-scope shows all components including ones that belong to lanes only.
This PR filters out the components from lanes. Later on (in another PR), the lanes be shown in their own section.

fix: avoid showing components from lanes in the scope UI

---

scopes/workspace/workspace/workspace.ts

Currently, if the `.bitmap` file got deleted, it shows a cryptic error: `defaultScope is missing`.
With this PR, it shows a more descriptive error, suggesting to run `bit init` to fix the issue.

improvement: show a descriptive error when .bitmap file is missing

---

scopes/harmony/application/run.cmd.tsx

It's not needed, it has `render` method already.

refactor: remove "report" method from Run command

---

src/scope/removed-components.ts

This is happening when removing components from a remote with Bit <= 0.0.646.

fix: fix error "Cannot read property map of undefined" on bit-remove

---

scopes/workspace/workspace/tag-cmd.ts
src/api/consumer/lib/tag.ts
src/bit-id/bit-ids.ts
src/scope/component-ops/message-per-component.spec.ts
src/scope/component-ops/message-per-component.ts
src/scope/component-ops/tag-model-component.ts
workspace.jsonc

Currently, it's not possible when tagging a component to specify a message per component.
With the new `--editor` flag, it'll open an editor, default to `vim` with the possibility to enter a message per component, or a default message to catch all empty messages.
It also provides an option to specify the messages for auto-tagged components with a pre-filled default ("bump dependencies versions").
The editor is what the user entered in the `--editor` flag. 
If none was specify, it'll use the `$EDITOR` or `$VISUAL` os variables. 
If they're empty, it'll default to `vim`.

feat: introduce "--editor" flag for "bit tag" to enable editing tag messages per component

---

scopes/preview/preview/exceptions/index.ts
scopes/preview/preview/exceptions/preview-output-file-not-found.ts
scopes/preview/preview/strategies/component-strategy.ts
scopes/webpack/webpack/webpack.bundler.ts

- improve error when preview can't find bundler output files
- improve webpack errors by taking the following error fields: `['message', 'moduleId', 'moduleName', 'moduleIdentifier', 'loc'];`

Preview errors

---

scopes/component/component/aspect-list.ts

For example, I created a new workspace, added a new aspect "my-aspect", its legacy string ID is just `my-aspect`, its harmony string ID is `scope.org/my-aspect`.
Currently, getting the aspect data from a component `component.state.aspects.get(MyAspect.id)` doesn't work. This is because the `get()` method uses the `legacyEntry.stringId`, which is not aware of the default-scope, so it compares it to `my-aspect` only.
With this PR it does the comparison against the Harmony string ID as well.

fix: support passing component-id with default-scope (for new components) to aspects.get()

---

scopes/workspace/eject/components-ejector.ts
scopes/workspace/eject/eject-cmd.ts
scopes/workspace/workspace/envs-subcommands/envs-set.cmd.ts
scopes/workspace/workspace/pattern.cmd.ts
scopes/workspace/workspace/workspace.ts

With this PR, it's possible to run `bit eject <pattern>` instead of specific "ids".

improvement: support <pattern> for bit-eject

---

scopes/component/isolator/isolator.main.runtime.ts

It's being shown also when all capsules are retrieved from the cache, which makes it confusing. 
It was needed in the past when the package-installation wasn't shown, currently, it's not needed.

remove the "create capsules network" message in the cli

---

src/scope/objects/object.ts
src/scope/objects/repository.ts
src/utils/zlib-deflate.ts
src/utils/zlib-inflate.ts

Currently, when an object file is empty, it'd show "unexpected end of file", with no context. 
In this PR, the error explains what the issue is and where the file located, so the user could delete it.

fix: show a descriptive error upon zlib failure

---

e2e/harmony/init-harmony.e2e.ts
src/e2e-helper/e2e-scope-helper.ts
src/utils/fs/propogate-until.ts

Currently, when Git is initiated and `.git/bit/objects` is deleted, then `loadBit` assumes that `.git/objects` is the scope-path.
As a result, it'll parse Git object files and throw cryptic errors.

fix: avoid setting Git path as the scope path

---

scopes/workspace/workspace/capsule.cmd.ts

only the "scope's aspects capsules root-dir" is used, not the "scope capsules root-dir".

improvement: remove the scope capsule root-dir from "bit capsule list", it is not used

---

scopes/component/isolator/network.ts
scopes/pipelines/builder/builder.main.runtime.ts
scopes/pipelines/builder/builder.service.tsx

Currently, when running `bit build <some-id>`, the `seedersCapsules` provided by the builder aspect, contains the entire graph of this component that use the same env.  
This PR, provides a way to get only the original seeders of the current env. 
(see https://github.com/teambit/bit/pull/5407 for a different route, which didn't go well).

improvement: add "originalSeedersCapsules" to the Network API

---

scopes/compilation/babel/babel.compiler.ts
scopes/compilation/babel/compiler-options.ts
scopes/compilation/compiler/compiler.cmd.ts
scopes/compilation/compiler/events/component-compilation-on-done.ts
scopes/compilation/compiler/output-formatter.ts
scopes/compilation/compiler/types.ts
scopes/compilation/compiler/workspace-compiler.ts
scopes/compilation/multi-compiler/multi-compiler.compiler.ts
scopes/dependencies/dependency-resolver/dependency-installer.ts
scopes/dependencies/dependency-resolver/index.ts
scopes/harmony/application/app.plugin.ts
scopes/preview/preview/preview.main.runtime.tsx

- [only build supported files with the babel compiler](https://github.com/teambit/bit/commit/3d9d51ffcf79c9b0250052ca21411c40db463076)
- [fix preview throwing a 404 when there are no compositions](https://github.com/teambit/bit/commit/ade6b76ba30a089bd0a55cb7ef6e3d83e203ec7b)
- [add supportedFilesGlobPatterns option to the babel compiler](https://github.com/teambit/bit/commit/a4e0e239116b977ee43296170f64de4dc7344b6f)
- [fix multi compiler to support transpiling all files at once](https://github.com/teambit/bit/commit/90c4e1bf31061c093be7701a056497b435a76c9e)
- [replace ConsumerComponent by Component in workspace compiler](https://github.com/teambit/bit/commit/b180b0ef57684eeda39b12ee863430734b59c078)
- [add missing exports from dependency …

Babel & multi compiler changes for apps

---

scopes/component/component/component.ts

- Currently, if a component has no tags (only snaps), the graphql query returns '[object Object]', as it tries to `toString()` the entire head `Snap` object, instead of returning the `head hash`. This fixes the query to return the `head hash` if there are no tags.

fix: gql(component/latest) return head version when there are no tags

---

scopes/scope/scope/scope-component-loader.ts

I don't have a good explanation for this, it's probably related to some internal optimization of v8. the fact is that with this changes, loading 419 versions of one component via `scope.get()` is down from 17 seconds to 4 seconds.

improvement: improve performance of component loading from scope

---

e2e/fixtures/extensions/custom-react-env/custom-react-env.aspect.ts
e2e/fixtures/extensions/custom-react-env/custom-react-env.main.runtime.ts
e2e/fixtures/extensions/custom-react-env/index.ts
e2e/fixtures/extensions/custom-react-env/jest/jest.config.js
e2e/fixtures/extensions/custom-react-env/typescript/tsconfig.json
e2e/fixtures/extensions/custom-react-env/webpack/webpack-transformers.ts
e2e/harmony/deps-in-capsules.e2e.ts
e2e/harmony/jest.e2e.ts
package.json
scopes/defender/jest/jest.tester.ts
scopes/defender/tester/index.ts
scopes/defender/tester/test.cmd.tsx
scopes/defender/tester/tester.graphql.ts
scopes/defender/tester/tester.service.tsx
scopes/defender/tester/tester.task.ts
scopes/defender/tester/tester.ts
scopes/defender/tester/ui/tests-page.tsx
scopes/defender/tester/utils/junit-generator.ts
scopes/defender/tests-results/tests-files.ts
scopes/defender/ui/test-table/test-table.tsx
scopes/envs/envs/runtime/runtime.ts
src/e2e-helper/e2e-command-helper.ts
workspace.jsonc

- a major refactoring to the way how errors are handled for tests. During "bit test", "bit build" and "bit start".
- currently, errors are saved as "general-errors" and shown in bit-build for each one of the component. So the exact same error will be shown 10 times, if there are 10 components. This is fixed to not show duplicate errors.
- change the `error` of the `testFiles` to be string, no need to have two properties: `failureMessage` and `error`. Only the "error" is needed because if Jest encountered an issue, e.g. syntax error, it'll report it as error. The failureMessage of Jest is just an aggregation of the failures of all individual tests. The only place this failureMessage is needed is when running `bit start`, which for some reason the error is empty and the `failureMessage` has …

fix(test-task): avoid showing the same error multiple times in bit-build

---

scopes/compositions/compositions/ui/composition-preview.tsx
scopes/harmony/pubsub/pubsub-context.tsx
scopes/harmony/pubsub/pubsub.ui.runtime.ts
scopes/preview/ui/component-preview/index.ts
scopes/preview/ui/component-preview/preview.tsx
scopes/preview/ui/preview-placeholder/preview-placeholder.tsx
workspace.jsonc

- update pubsub 
- the update fixes the `[Pubsub.ui] failed connecting to child iframe` error happening when switching between component pages, see [here](https://github.com/Aaronius/penpal/releases/tag/v6.0.0).
- turn off pubsub for gallery pages
- remove the unused hotReload flag that also trigger errors

Fix pubsub errors

---

workspace.jsonc

- change react-dev-utils from v12.0.0 to v11.0.4 because of node compatability
- this was the previous version we used, and there doesn't seem to be a lot of difference between the versions.
-

revert react-dev-utils to v11.0.4

---

workspace.jsonc

Downgraded `react-error-overlay` back to 6.0.9.
Version 6.0.10 is only compatible with `react-dev-utils` v12, which is not compatible with node 12 :(
Fixes this error:
```
Uncaught ReferenceError: process is not defined
at Object.4043 (<anonymous>:2:13168)
at r (<anonymous>:2:306599)
at Object.8048 (<anonymous>:2:9496)
at r (<anonymous>:2:306599)
at Object.8641 (<anonymous>:2:1379)
at r (<anonymous>:2:306599)
at <anonymous>:2:315627
at <anonymous>:2:324225
at <anonymous>:2:324229
at HTMLIFrameElement.e.onload (main.bundle.js:182081:370
```

fix error 'process'

---

scopes/react/react/templates/workspace-common/files/ts-config.ts

- add `"noEmit": true` to the compiler options in the tsconfig file of new workspaces template
this allows users to run `tsc -w` without emitting transpiled files

ts "no emit" in new react workspaces

---

workspace.jsonc

- bumping penpal to v6.2.2 to benefit from https://github.com/Aaronius/penpal/issues/85#issuecomment-1062741357
- the new version fix an error showing up in the console  
`Cannot read properties of null (reading 'postMessage')`
- the error was benign, happened when penpal tried to establish a connection with a closed iframe.

bump penpal (fix postmessage errors)

---

scopes/mdx/ui/mdx-layout/mdx-layout.css

markdown preprocessor
- fix yellow note text color
- fix 'caution' note to use the same token as "note" (yellow, instead of orange)

fix markdown note colors

---

scopes/workspace/workspace/workspace.ts

fixing error:
```
"<env id>" is configured in workspace.json, but using the "teambit.envs/env" environment, which is type "env".
please make sure to either apply the aspect environment or a composition of the aspect environment for the aspect to load.
```

consider envs using the env env as valid aspects when loading workspace aspects

---

.circleci/config.yml
scopes/envs/envs/environment.ts
scopes/envs/envs/environments.main.runtime.ts
scopes/harmony/aspect/aspect.env.ts
scopes/preview/preview/env-preview-template.task.ts
scopes/preview/preview/preview.main.runtime.tsx
scopes/react/react-native/react-native.main.runtime.ts
scopes/react/react/react.env.ts

- add new `getTemplateBundler` API to the envs API interface
- add new `getAdditionalHostDependencies` and `getHostDependencies` API to the envs API interface
- expose `getAdditionalHostDependencies` from react env
- override `getHostDependencies` for react-native env, to filter out react-native from the bundle
- add a new API to get the `teambit.envs/env` env definition
- Add new APIs to react env: `createComponentsWebpackBundler` and `createTemplateWebpackBundler`
- implement `getTemplateBundler` for aspect env to be used as a default bundler for envs templates
- use `getTemplateBundler` from the env if exist or fallback to default one when bundling the env template
- re-write the entire bundling logic for env templates
- only bundle component which are original seeders in the …

Env template bundler

---

scopes/generator/generator/component-generator.ts
scopes/generator/generator/component-template.ts
scopes/generator/generator/generator.main.runtime.ts
scopes/generator/generator/index.ts

- allow config in component template to be a function that return config
- provide the aspect id in the config context
an example template config can be now something like this
```js
config: (context: ConfigContext) => {
return ({
[`${context.aspectId}`]: {},
'teambit.envs/envs': {
env: 'teambit.harmony/node',
}
});
},
```

allow config in component template to be a function that return config

---

scopes/compilation/multi-compiler/multi-compiler.compiler.ts

- The multi compiler is missing support for `getPreviewComponentRootPath`, making it impossible to support this API in compilers used by multi compilers. As for other methods of the multi compiler, the first matched compiler that supports this method will be used.

fix(multi-compiler): add support for `getPreviewComponentRootPath`

---

workspace.jsonc

This is a temporary workaround to fix `bit compile` on macOS and Windows. `bit compile` breaks `node_modules` when hard links are used.
The description of the issue that is fixed:
pnpm uses content-addressable-storage for the files. (so, if the content is the same, it'll have the same source/object).
In this case, originally, the content of the index.js file of these two packages were the same. I tried to npm install them on a new temp dir and verified it.
Later on, when "bit compile" was running, it changes the content of the dist file of toolbox, which effectively changed the content of all other index.js that use the same hard-link.

Set packageImportMethod to copy

---

scopes/preview/preview/preview.main.runtime.tsx
scopes/preview/preview/strategies/component-strategy.ts

You can now add this new config to `workspace.jsonc`
```
"teambit.preview/preview": {
"maxChunkSize": 20
},
```

add option to limit concurrent components during generate preview task

---

e2e/harmony/create.e2e.4.ts
scopes/envs/envs/environments.main.runtime.ts
scopes/generator/generator/component-generator.ts
scopes/generator/generator/create.cmd.ts
scopes/workspace/workspace/bit-map.ts

- with this change the env is calculate by the following: from the `--env` flag. If not entered, from the variants, if not exists, from the the template.
- improve the output of `bit create` to indicate where the env is coming from.

improvement(bit-create): avoid overriding env from workspace variants by env from the template

---

scopes/compilation/bundler/bundler-context.ts
scopes/compilation/bundler/dev-server-context.ts
scopes/react/react/apps/web/react-app-options.ts
scopes/react/react/apps/web/react.app-type.ts
scopes/react/react/apps/web/react.application.ts
scopes/webpack/webpack/config/webpack.config.ts
scopes/webpack/webpack/config/webpack.dev.config.ts
scopes/webpack/webpack/webpack.dev-server.ts

I ended up adding it with the webpackHTML plugin (and not adding another plugin)
closed #5603
-add favicon support to React apps
-have the ability to extend it to more apps in the future (as it is part of the webpack config

added favicon support

---

scopes/react/react-native/component.json
scopes/react/react-native/webpack/webpack-transformers.ts

- require.resolve for babel presets in rn webpack
- add to component.json (probably not needed, as currently installed in bit because of react env dependency - but best to have it in the rn dependencies too)
-

require resolve babel presets and add to component.json

---

scopes/mdx/ui/mdx-layout/md-example.md
scopes/mdx/ui/mdx-layout/mdx-layout.css

- Left icon is align center when text is long - fixed.
Before:
After:

Fix notes icon aligns in mdx

---

e2e/commands/lane.e2e.1.ts
scopes/component/merging/merging.main.runtime.ts

When a lane is merged into master, there is no indication in the `Component` object that there is a local change, such as the `state.local` created by snap/tag. 
As a result, when running `bit import` afterwards, the `Component` object gets replaced by the remote one and the merge data is gone. 
This fixes it by marking the merged head as local. (see another alternative I tried and failed https://github.com/teambit/bit/pull/5616).

fix: avoid overriding components after merge from main by the remote

---

scopes/component/issues/issues.main.runtime.ts
scopes/component/issues/non-exist-issue-error.ts
scopes/component/snapping/snapping.main.runtime.ts
scopes/component/status/status.main.runtime.ts

Currently, ignoring issues from workspace.jsonc only works globally. With this change it's possible to add the config to the variants to enable it to a specific set of components.

improvement: enable ignore issues for specific components

---

scopes/generator/generator/templates/component-generator/index.ts
scopes/generator/generator/templates/workspace-generator/index.ts

- Fixes the URLs shown in the help text of the bit CLI command `bit templates`
- URLs fixed for "workspace generator" and "component generator"

fix: update templates CLI help text

---

scopes/mdx/mdx/mdx.compiler.ts

- remove 'bit flavor' of mdx in production builds
- already removed in regular preview and compilation, so it will create a more consistent experience
- this fixes a bug where highlighter shows "mdx-scope-context" instead of the component name

mdx build - use same logic for build as for preview

---

scopes/component/component/component-factory.ts
scopes/component/component/component.ts
scopes/component/component/state.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/pipelines/builder/builder.main.runtime.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/typescript/typescript/typescript.compiler.ts
scopes/workspace/workspace/workspace.ts

The performance improvement of this PR is huge when building a small set of components that have many dependencies on the workspace. Currently, when creating the capsules (during `bit build` or `bit tag`), they are written without the dists and the compiler task is responsible of compiling all these components. 
The thing is that if these dependencies weren't changed since the last tag/snap, there is no reason to re-compiling them. It's possible to get the dists and the d.ts files from the last tag/snap. 
This PR does exactly this, it writes the dists to the capsules when creating them in case they weren't modified.

improvement: avoid compiling unmodified components on capsules

---

scopes/react/component-highlighter/element-highlighter/element-highlighter.compositions.tsx
scopes/react/component-highlighter/frame/frame.tsx
scopes/react/component-highlighter/label/label-container.tsx
scopes/react/component-highlighter/label/label.module.scss

- prevent the highlighter overflowing when target element reaches the bottom for the document

prevent highlighter from overflowing the document

---

e2e/commands/lane.e2e.1.ts
scopes/component/merging/merging.main.runtime.ts

This error is happening when main has tagged version and it's being merged to a lane.
Reported by @NitsanCohen770 .

fix "getDivergeData: unable to find Version" error when merging from main to a lane

---

src/lane-id/lane-id.ts

In some scenarios when checking out to lane and running `bit run`, it throws an error: 
```
RangeError: Maximum call stack size exceeded
```
This PR fixes it.

fix(lanes): fix "RangeError" in some cases when working on a lane

---

scopes/generator/generator/generator.main.runtime.ts
scopes/generator/generator/workspace-generator.ts
scopes/generator/generator/workspace-template.ts
scopes/react/react-native/templates/react-workspace/index.ts
scopes/react/react/templates/react-workspace-app/index.ts
scopes/react/react/templates/react-workspace-deprecated/index.ts
scopes/react/react/templates/react-workspace-lib/index.ts
scopes/react/react/templates/react-workspace/index.ts
scopes/scope/importer/importer.main.runtime.ts
src/consumer/component-ops/component-status-loader.ts

To use it, in the workspace-template, instead of using `importComponents()` which got deprecated, use `import()`. To fork the components (same behavior as now), use `fork()`.

feat: support import components during bit-new without forking them

---

scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts

This way, the `--log=error` suggested in the error-message will work.

fix: change the extension-loading-failure log level from warn to error

---

scopes/lanes/lanes/lane.cmd.ts
scopes/lanes/lanes/switch.cmd.ts

specifically, for  `bit switch` and `bit lane import`.

improvement: introduce "--skip-dependency-installation" flag for lanes commands

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/envs/envs/environments.main.runtime.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

- add dependencies added by env.getDependencies().peers to the env itself as regular dependencies
- new getEnvDefinitionByLegacyId API
with this PR, if you have env with something like this:
```js
getDependencies: () => {
return {
peers: [
{
name: 'graphql',
version: '14.3.0',
supportedRange: '^14.0.0',
}
]
}
}
```
The env itself will have `graphql` with version `14.13.0` as regular dependency

envs peers as self deps

---

scopes/envs/envs/envs.cmd.tsx
scopes/toolbox/tables/cli-table/cli-table.ts

Asked by @ocombe . 
(Windows does't have Ctrl+F in the CLI so it's hard to find when is not sorted).

improvement: sort "bit envs" table by the component-id alphabetically

---

scopes/scope/importer/import.cmd.ts

Currently, it just ignores the flag and leave the user confused.

fix: throw an error when running bit import --dependencies/--dependents without ids

---

scopes/component/isolator/capsule/capsule.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/workspace/workspace/workspace.ts

- add a new API to the Isolator for cloning a capsule and having all packages installed in the new capsule. The content inside the capsule is the same as the original.
- remove some unneeded methods from `Workspace`.

feat: add an option to clone a capsule

---

scopes/component/capsules-syncer/capsules-syncer.task.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/pkg/pkg/pkg.main.runtime.ts
scopes/preview/preview/preview.main.runtime.tsx
scopes/workspace/workspace/workspace.ts

- move getPackageName, getModulePath and getRuntimeModulePath APIs implementation to the dep resolver aspect
- proxy getPackageName, getModulePath and getRuntimeModulePath APIs from pkg aspect
- add hasRootComponents API to dep resolver aspect
- use the new hasRootComponents API from dep resolver

re-organize pkg and dep-resolver APIs

---

.circleci/config.yml

- the fix was done via running the bvm bundle debug, with the step to re-generate the cache enabled
- this pr does not change anything, just add some more debug steps around docker for the bvm bundle debug workflow

fix circle cache and publish version

---

scopes/compilation/bundler/bundler-context.ts
scopes/preview/preview/env-preview-template.task.ts
scopes/preview/preview/preview.main.runtime.tsx
scopes/react/react/react.env.ts
scopes/react/react/webpack/get-exposed-rules.ts
scopes/react/react/webpack/transformers.ts
scopes/react/react/webpack/webpack.config.base.prod.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/scope/scope/scope.ui-root.ts
scopes/ui-foundation/ui/ui-root.tsx
scopes/ui-foundation/ui/ui.main.runtime.ts
scopes/webpack/config-mutator/config-mutator.ts
scopes/workspace/workspace/workspace.ts
scopes/workspace/workspace/workspace.ui-root.ts

- fix preview root file name (add '.' separator)
- use the runtime module path when updating preview link files
- update the getComponentPackagePath in the workspace to use the new dep resolver getRuntimeModulePath
- add hostRootDir to the bundler target interface
- update ui root interface to have optional component ids in resolve aspects
- pass on component ids from workspace and scope ui roots to resolve aspects
- filter results from resolve aspects by provided component ids
- add resolve aspects API to preview aspect
- add new addModuleRules API to webpack config mutator
- pass host root dir to bundler target for env preview template task
- add new generateExposePeersTransformer to react env
- support hostRootDir for generateAddAliasesFromPeersTransformer and for …

Injected-peers--webpack-paths

---

scopes/scope/scope/scope.graphql.ts
scopes/scope/scope/scope.main.runtime.ts
src/scope/network/http/http.ts

- This also fixes the scenario when importing from a remote scope with components that exist only on lane. It filters the components from the scope list query which do not have `head` defined

update scope list http to use the new gql query

---

e2e/commands/lane.e2e.1.ts
scopes/lanes/lanes/lane.cmd.ts
src/scope/lanes/lanes.ts

Currently, when deleting a lane from a remote, the components are not getting deleted although they were used only in that scope. In this fix, it is validated that the components from the deleted lanes are not used anywhere else, and then get deleted.

fix: delete orphaned components upon lane removal

---

e2e/commands/lane.e2e.1.ts
src/consumer/component-ops/import-components.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/objects-fetcher/objects-fetcher.ts
src/scope/objects-fetcher/write-objects-queue.ts

running `bit import <id>` when on a lane and the id has a different scope-name than the current lane result in importing all objects of the current lane but the component in question is not imported. It's filtered out before accessing the remote-scope.

fix(lanes): enable importing a non-lane component from a scope different than the currently lane-tracked scope

---

e2e/commands/lane.e2e.1.ts
src/scope/repositories/sources.ts

Currently, if the head is empty on the remote-component, e.g. when the component was exported as part of the lane. Then, later, when this component is exported from main it's not saved correctly on the remote. 
This PR fixes it and shows the snaps that were exported.

fix: export components properly when their head is empty on a lane

---

scopes/component/refactoring/index.ts
scopes/component/refactoring/refactoring.main.runtime.ts
scopes/component/renaming/renaming.main.runtime.ts
scopes/component/renaming/scope-rename.cmd.ts
scopes/harmony/cli/cli.main.runtime.ts
scopes/harmony/config/config.main.runtime.ts
scopes/harmony/config/workspace-config.ts
scopes/scope/scope/scope-cmd.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/workspace/workspace/bit-map.ts
src/consumer/config/component-config.ts

- introduce `bit scope <sub-command>` command to manage scope.
- introduce `bit scope rename` command to change the scope-name for new components
- add `--refactor` flag to change the source code and replace the old package-name with the new one.

feat: introduce "bit scope rename" to change a scope-name

---

scopes/component/isolator/network.ts
scopes/typescript/typescript/typescript.compiler.ts

This is happening due to the optimization done in https://github.com/teambit/bit/pull/5636. 
As a result of this optimization, modified components that were not part of the original-seeders weren't compiled by typescript. This PR fixed it by including them as well.

fix(bit-build): fix error occurring during preview task regarding missing dists files

---

package.json
pnpm-lock.yaml
scopes/harmony/logger/logger.ts
workspace.jsonc

Currently, when the log messages are written by an aspect, it has a unique color to easily differentiate between the aspects.
While this was working well for most aspects, some of them got unreadable colors. Also, in some instances, the background of the log file stream was changed to yellow for some weird reason (happened to @ranm8 ).
In this PR, the log messages are all have the same color. To make is easier to see the aspect-name, it was changed to be bold.

fix: avoid coloring the log messages according to the aspect-name

---

scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.ts

`semver-intersect` does not support `*` asterisk version value and throws an exception
```
Cannot read properties of null (reading '1')
```
asterisk means any version so it could be skipped during grouping
- ignore asterisk symbol during `groupByRangeOrVersion`

Ignore asterisk version during grouping

---

src/api/scope/lib/cat-lane.ts
src/api/scope/lib/cat-scope.ts
src/cli/commands/private-cmds/cat-scope-cmd.ts

with this change, `bit cat-scope` will show lanes with a suffix of `[lane]`. See screenshot.

improvement: add lanes to cat-scope

---

scopes/lanes/lanes/switch-lanes.ts
src/consumer/consumer.ts

Currently, if a component has a snap on a lane and the component is modified due to dependencies changes, the user can't switch to another lane. It shows an error: "unable to checkout comp-name, the component is modified and belongs to another lane".
With this change, we check for component files changes specifically.

fix(lanes): enable switching lanes if the modification on a lane is not source-files related

---

scopes/lanes/lanes/lane.cmd.ts

Currently it shows "the operation has been canceled" no matter what the input is.

fix(lanes): fix the prompt of "bit lane remove"

---

e2e/harmony/lanes/import-lanes.e2e.ts
e2e/harmony/lanes/merge-lanes.e2e.ts
scopes/lanes/lanes/create-lane.ts
scopes/lanes/lanes/lanes.main.runtime.ts
scopes/lanes/lanes/switch-lanes.ts
src/scope/repositories/sources.ts

- avoid creating a new Lane object with a new hash upon import
- move the create-lane code from legacy to Harmony.

fix(lanes): preserve the same Lane hash during lane-import

---

scopes/lanes/lanes/create-lane.ts
scopes/lanes/lanes/lane.cmd.ts
scopes/lanes/lanes/lanes.main.runtime.ts
src/scope/lanes/lanes.ts
src/scope/models/lane.ts

For now, it's shown in `bit lane show` (and `bit cat-lane`).

feat: add log (author, email, date) upon lane creation

---

scopes/scope/export/export-cmd.ts

- introduce `--json` flag for `bit export`, it includes the component-ids and lane objects that were exported.

feat: introduce bit export --json

---

scopes/react/react/react.env.ts
scopes/react/react/react.main.runtime.ts
scopes/react/react/webpack/transformers.ts

- this should solve errors like `ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/test-utils' in '.../node_modules/@testing-library/react/'`

resolve generated webpack peers aliases to the folder of the module

---

e2e/harmony/tag-harmony.e2e.ts
src/scope/component-ops/tag-model-component.ts

rather than a numerical version.
(this is probably a regression caused by #5671).

fix: enter auto-tagged as "patch" in the .bitmap during soft-tag

---

src/scope/models/model-component.ts
src/scope/repositories/sources.ts

The bug this is fixes is running `bit checkout latest --all` when on a lane and a component has no head. 
It shows the error `has no versions and the head is empty`. the reason is that during the import process, the model-component is rewritten to the filesystem and re-entered to the cache. Because it's in the cache, Bit assumes that the lanes data is already populated.

fix: populate lanes data on ModelComponent object when it was rewritten

---

src/scope/objects/repository.ts

Currently, when a component object got a different path for some reason, it is still showing in `bit cat-scope`, it is indexed into the `index.json` file. However, when Bit tries to load it, it fails since the hash path doesn't exist.
This PR makes sure to never consider objects with malformed paths.

fix: ignore invalid bit object paths

---

package.json
pnpm-lock.yaml
src/doctor/core-diagnoses/validate-bit-version.ts
workspace.jsonc

Currently `bit doctor` shows errors when Bit version on NPM is newer although it's not available on BVM.

fix(bit-doctor): fetch bit-remote-version from the BVM instead of NPM

---

scopes/compilation/bundler/bundler-context.ts
scopes/react/react/react.env.ts
scopes/react/react/webpack/get-exposed-rules.ts
scopes/react/react/webpack/resolve-peer.ts
scopes/react/react/webpack/transformers.ts
scopes/react/react/webpack/webpack.config.base.prod.ts
scopes/webpack/config-mutator/config-mutator.ts

- improve resolution for exposed peers rules (resolve to module field instead of the main field in package.json if exist)
- add new generateExposePeersTransformer to react env
- use the new generateExposePeersTransformer from the react env
- add hostRootDir to the bundler target interface
- support hostRootDir for generateAddAliasesFromPeersTransformer and for generateExposePeersTransformer
- support hostRootDir for getExposedRules
- resolve host root dir to its real location before calling require.resolve
- add new addModuleRules API for webpack config mutator

improve resolution for exposed peers rules

---

e2e/harmony/jest.e2e.ts

Four tests are failing on Windows with a message from Jest about tests-not-found.
The reason for this error is that Node provides paths in the windows-short format of 8.3 and Jest needs the full-path.
E.g. # 1 is the path passed to Jest, which Jest doesn't recognize well. # 2 is the path that Jest recognizes and could work.
1. `C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\bit\\e2e\\2zmx1543-local\\comp1\\comp1.spec.ts`
2. `C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\bit\\e2e\\2zmx1543-local\\comp1\\comp1.spec.ts`

ci: skip some Jest e2e-tests on Windows due to short-path issues

---

scopes/semantics/schema/schema.graphql.ts

To get a schema via GraphQL, run the following query:
```
query Schema {
getHost {
getSchema(id: "teambit.base-react/buttons/button")
}
}
```
Once you have the JSON object, you can deserialize it by `getSchemaFromObject()` API of Schema aspect.

schema: fix schema GraphQL query to return the entire JSON object

---

scopes/dependencies/aspect-docs/dependency-resolver/dependency-resolver.mdx
scopes/dependencies/dependency-resolver/dependency-installer.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
scopes/workspace/workspace/workspace.ts
workspace.jsonc

- allow to set which node.js version should be used when checking the engines field of dependencies.
- allow to set strict-engine to true

feat: configuring Node.js engine checks

---

e2e/harmony/lanes/lanes.e2e.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/component-ops/traverse-versions.ts

Currently, when traversing the component versions, once the traversal is done, it goes to each one of the tags and search for it as well. It was done originally to support legacy that didn't have the concept of head/parents. 
This PR avoid this extra work if the component is Harmony. 
In case when the traversal starts at a certain point, it also avoid errors of VersionNotFound when they're not part of the graph. (the attached e2e-test demonstrates it).

fix: avoid traversing tags on Harmony

---

scopes/component/component/ui/component.tsx
scopes/component/component/ui/menu/menu.tsx
scopes/component/component/ui/use-component-query.ts
scopes/component/component/ui/use-component.tsx
scopes/lanes/ui/hooks/lanes-context/lanes-model.ts

- update `use-component` to accept only `string` component ids
- remove lanes logic from use components and move it up to the caller

update use-component to only accept string comp ids

---

e2e/harmony/lanes/lanes.e2e.ts
src/scope/component-ops/export-scope-components.ts

- during export, make sure that the default-scope exists.
- during export, make sure that there is no other component with the same name in the original scope when exporting a new component.

improvement(lanes): validate component's default scope when is different than the lane-scope

---

e2e/harmony/lanes/bit-import-on-lanes.e2e.ts
scopes/defender/tester/tester.task.ts
scopes/scope/importer/import.cmd.ts
scopes/scope/importer/importer.ts
scopes/workspace/workspace/bit-map.ts
scopes/workspace/workspace/workspace.ts
src/consumer/bit-map/bit-map.ts
src/consumer/component-ops/import-components.ts

When checked out to a lane, `bit import` fetches all objects from the lane-scope. In case the lane is new, it doesn't find it in the remote and falls back to main lane. 
Instead, this PR, stops immediately and shows an error that there is nothing to import because the lane is new.

fix(lanes): avoid importing from main when on a new lane

---

e2e/harmony/aspect.e2e.ts
e2e/harmony/custom-env.e2e.ts
e2e/harmony/load-extensions.e2e.4.ts
e2e/harmony/workspace-config.e2e.ts
scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
scopes/harmony/aspect-loader/constants.ts
scopes/harmony/bit/load-bit.ts
scopes/harmony/cli/command-runner.ts
src/e2e-helper/e2e-bit-jsonc-helper.ts
src/e2e-helper/e2e-extensions-helper.ts
src/logger/logger.ts

- fix `--log` flag to print log message right away, even before the aspects are loaded. this way, when the error is happening during bootstrap, it'll be able to print the log.
- remove error-logging duplications. now when using `--log=error`, it shows the aspect-loading failure only once.
- improve the `UNABLE_TO_LOAD_EXTENSION` message to include the first line of the error message. for the most cases, this is enough, and no need to use the `--log=error` flag.

fix: improve handling aspect failures

---

e2e/harmony/sign.e2e.ts
src/api/scope/lib/fetch.ts
src/consumer/component-ops/import-components.ts
src/consumer/consumer.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/models/lane.ts
src/scope/repositories/sources.ts

- import only "delta" when on a lane with the same way it is done for main. meaning, send to the server the current hash and only fetch if the server has a newer hash, in which case, fetch the delta between the two.
- in case the components exist locally but their version are unbuilt, avoid fetching them again from the remote with all their dependencies, unless their `builtStatus` has changed and is now successful.

improvement: improve performance of bit-import on lane

---

e2e/harmony/multiple-envs.e2e.ts
scopes/component/component-issues/multiple-envs.ts
scopes/workspace/workspace/envs-subcommands/envs-unset.cmd.ts

- in case of "multiple-envs" issue, suggest to run `bit env set` to fix it. (currently, it suggests adding minus key to variants, which it less clear and more work).
- in case `bit env unset` didn't make any changes, show it clearly in the command output.
- clarify in the description of `bit env unset` that it affects only components set by `bit env set` before.

fix: clarify the solution for multiple-envs, clarify "bit env unset" command

---

e2e/harmony/custom-env.e2e.ts
src/scope/scope.ts

currently, if the remote was added locally (via `bit remote add some-remote`) and the component doesn't exist in the local scope, it assumes the id doesn't have scope-name. 
with this fix, it'll check whether the first part of the id is the scope-name by comparing it to the local remotes.

fix: consider locally-configured-remotes when resolving bit-id from scope

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

Before:
```
error found while parsing the file (edit the file and fix the parsing error):
foo.ts -> Expression expected.
```
After:
```
error found while parsing the file (edit the file and fix the parsing error):
foo.ts -> Expression expected. (line: 6, column: 2)
```

improvement: show the line+column of a parsing-error in bit-status

---

scopes/harmony/bit/bit.provider.ts
scopes/harmony/bit/load-bit.ts

Implements #5928.
This configuration is part of `teambit.harmony/bit` aspect, and utilizes two properties: `engine` to compare the Semver and `engineStrict` to throw an error instead of just showing a warning. 
Here is an example how to configure it in workspace.jsonc to support Bit version 0.0.700 and above. It'll throw an error if current version is < 0.0.700.
```
"teambit.harmony/bit": {
"engine": ">0.0.700",
"engineStrict": true
},
```

feat: allow enforcing minimum supported Bit CLI version

---

scopes/workspace/workspace/watch/watch-queue.ts
scopes/workspace/workspace/watch/watcher.ts

Currently, multiple components and .bitmap changes execution can still be processed concurrently.
The following example explains why this is an issue:
compA is changed in the .bitmap file from version 0.0.1 to 0.0.2. its files were changed as well. All these changes get pulled at the same time by "git pull", as a result, the execution of compA and the .bitmap happen at the same time.
During the execution of compA, the component id is parsed as compA@0.0.1, later, it asks for the Workspace for this
id. While the workspace is looking for this id, the .bitmap execution reloaded the consumer and changed all versions.
After this change, the workspace doesn't have this id anymore, which will trigger an error.
To ensure this won't happen, we keep a flag to indicate whether the .bitmap execution …

improvement: implement queue mechanism for the watch process

---

scopes/component/ui/version-dropdown/version-dropdown-placeholder.module.scss
scopes/component/ui/version-dropdown/version-dropdown-placeholder.tsx
scopes/component/ui/version-dropdown/version-info/version-info.tsx

- remove `smooth` scrolling to the current version when the version dropdown opens
- hide down arrow in the version placeholder when there is only one version present

regression: version dropdown fixes

---

scopes/design/ui/pages/standalone-not-found-page/standalone-not-found.tsx

- remove old theme from StandaloneNotFound page
This component is used as a fallback in the compositions-app. Its styles seep into the env template, and break component docs. Removing this theme from the component should fix it:

remove theme from compositions app

---

scopes/react/react/templates/workspace-common/files/workspace-config.ts

- update `bit new react` template to use `@testing-library/react` version `^12.1.15`, which is better compatible with react 17.

set testing library to match react 17

---

scopes/code/ui/code-compare/code-compare.module.scss
scopes/code/ui/code-tab-page/code-tab-page.module.scss
scopes/component/component-filters/envs-filter.module.scss
scopes/component/ui/compare/aspects/compare-aspects.module.scss
scopes/component/ui/compare/version-picker/component-compare-version-picker.module.scss
scopes/compositions/compositions/compositions.module.scss
scopes/compositions/ui/composition-compare/composition-dropdown.module.scss
scopes/design/ui/pages/standalone-not-found-page/standalone-not-found.tsx
scopes/scope/scope/ui/scope.module.scss
scopes/ui-foundation/uis/constants/z-indexes/z-indexes.module.scss
scopes/ui-foundation/uis/top-bar/top-bar.module.scss
scopes/workspace/workspace/ui/workspace/workspace.module.scss

- ensure top bar dropdowns are above split-pane's splitter 
- fix env filter being above the mobile-topbar-menu (and fix border-radius)
- start using named z-index
z-index are an _order_ problem. Since each instance only knows its own index, a _[mediator](https://en.wikipedia.org/wiki/Mediator_pattern)_ is needed to assign the correct values.
(as a metaphor - you'd want the control tower to assign flight heights, not the airplanes themselves)
We should try not to abuse zindexes, and consolidate them where possible. For now we can let the list grow and consolidate when we have a better understanding of the values in our system.
Fixes:

Fix zindexes

---

scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm-error-to-bit-error.spec.ts
scopes/dependencies/pnpm/pnpm-error-to-bit-error.ts

- On fetching errors, pnpm adds information to the error object about the used auth headers. This information is safe to print as the tokens are obfuscated.
Before/after:

fix: print more information on fetch errors

---

scopes/dependencies/pnpm/lynx.ts

Issue when installing a new version and we have an older version already installed.
- it’s preventing vscode error on the code when trying to use a new api of the component.
- node modules are updated correctly with the new version.
- sometimes it’s makes autocomplete correct with the new api and sometimes not, but I think that this is related to vscode.

Change pnpm cache install option

---

scopes/component/component-issues/multiple-envs.ts

In case a component has more than one env, and its config is corrupted, `bit env set` might not help.
For example, this happens when a component doesn't use `teambit.envs/envs` to configure the env, resulting this this output:
This PR suggests running `bit aspect unset` in case `bit env set` is not helpful.

improvement: suggest alternatives for multiple-envs if bit-env-set does not help

---

scopes/component/ui/use-fetch-docs/use-fetch-docs.tsx
scopes/harmony/graphql/graphql.preview.runtime.tsx
workspace.jsonc

- remove all traces of apollo and the main graphql aspect during preview
Trying to get rid of `subscriptions-transport-ws`, and found that graphql aspect is not even used in the preview.
Also `@apollo/client` is opinionated, and could conflict between versions, and configurations, So, it's a good idea to remove it from the preview where user code can is running.

remove gql aspect / apollo from preview

---

src/consumer/component-ops/move-components.ts

to avoid confusion. this was supported on legacy, but not on Harmony. 
On Harmony, no need to move files within the component-dir. and it's impossible to track files from other directories.

block moving files via "bit move" command on Harmony

---

e2e/harmony/status-harmony.e2e.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

It could happen that by mistake instead of importing from a file within a component, the import statement has the component-package. 
Although this is not an issue currently, (because it's filtered out before saving the data), it is confusing when debugging the component. 
This PR removes it immediately before setting the `dependencies` prop.

ignore import statements of a component to itself

---

scopes/component/snapping/tag-cmd.ts
scopes/harmony/cli/yargs-adapter.ts

Before: `bar@0.0.1` => `bar@0.0.2-true.0`
After:    `bar@0.0.1` => `bar@0.0.1-0`

fix(bit-tag): fix --pre-release flag to not have "true" as identifier if not provided

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
scopes/toolbox/network/agent/agent.ts
src/constants.ts
src/scope/network/http/http.ts

- `network.strict_ssl` setting renamed to `network.strict-ssl`
- do not overwrite strictSSL with `undefined` when Yarn is the package manager and strict SSL is configured through global Bit settings
- do not overwrite strictSSL with `true` when pnpm is the package manager and strict SSL is configured through global Bit settings
- add default values for network settings

fix: read strict-ssl

---

scopes/preview/preview/strategies/component-strategy.ts
scopes/preview/preview/strategies/generate-component-link.ts

- upgrade tag link file to use esm syntax (and not mixed export/require)
- handle previews with no files
setup for fixing the `preview for name: "overview" was not found` error.
<details>
<summary>externals sample</summary>
before this PR:
```js
export const compositions = [require('/Users/kutner/Library/Caches/Bit/capsules/5ac02f09bfe0eccb84aec7cb198a40776d572fff/my-org.my-scope_comp01@0.0.1/dist/comp01.composition.js')]
export const overview = [require('/Users/kutner/Library/Caches/Bit/capsules/5ac02f09bfe0eccb84aec7cb198a40776d572fff/my-org.my-scope_comp01@0.0.1/dist/comp01.docs.mdx')]
```
after this PR:
```js
import * as compositions_0 from '/Users/kutner/Library/Caches/Bit/capsules/5ac02f09bfe0eccb84aec7cb198a40776d572fff/my-org.my-scope_comp01@0.0.1/dist/comp01.composition.js' …
```

esm tag link

---

scopes/component/isolator/isolator.main.runtime.ts
src/consumer/component-ops/component-writer.ts

Currently if the component's build-status is failed, `bit sign` throws an error when on a lane:
```
ENOENT: no such file or directory, open '/tmp/scope-fs/objects/ed/af2594be2b2603149910c7ae86197e7c3d3975
```
Because the dists paths are saved into the model, Bit tries to fetch them when writing the capsule from the original-scope. 
This PR fixes it to not fetch the dists from the remote in case the build was not success. 
(if the build is success, then bit-sign won't try to get the dists anyway, so no issues there).

fix(bit-sign): avoid fetching dists of build-failed

---

e2e/flows/out-of-sync-componets.e2e.3.ts
e2e/harmony/lanes/lanes.e2e.ts
scopes/component/snapping/reset-cmd.ts
scopes/component/snapping/snapping.main.runtime.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/workspace/workspace/envs-subcommands/envs-set.cmd.ts
src/cli/commands/public-cmds/untag-cmd.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/component-ops/untag-component.ts

Because this command reverts also snaps, not only tags, the name `reset` is more accurate. 
Also, added a new API to be able to untag/unsnap using the Snapping aspect.

deprecate bit-untag, introduce bit-reset

---

scopes/component/component-issues/circular-dependencies.ts
scopes/explorer/insights/all-insights/find-circulars.ts

improvement: rename "circular dependencies" insight to "circular"

---

scopes/pipelines/builder/artifact/artifact-extractor.ts

by omitting the component-id from the path.

improvement(bit-artifacts): shorten the out-dir path when asked for one component

---

e2e/harmony/lanes/merge-lanes.e2e.ts
scopes/component/merging/index.ts
scopes/component/merging/merge-cmd.ts
scopes/component/merging/merging.main.runtime.ts
scopes/lanes/lanes/lane.cmd.ts
scopes/lanes/lanes/lanes.main.runtime.ts
scopes/lanes/lanes/merge-lanes.ts
src/cli/commands/public-cmds/dependencies-cmd.ts
src/consumer/consumer.ts

introduce `--pattern` to merge some of the components from the lane.
If these components have dependencies in the lane that are not part of the pattern, it'll throw an error suggesting to enter `--include-deps` flag which merge also the dependencies.

feat(bit-lane-merge): introduce "--pattern" and "--include-deps" flags to merge part of a lane

---

scopes/react/react/templates/react-hook/files/index-file.spec.ts
scopes/react/react/templates/react-hook/files/index-file.ts

- Fixes export name casing issue with generated React Hooks.
- closes #6043

React Hook name should be in camelCase instead (#6043)

---

.husky/pre-commit
package.json
pnpm-lock.yaml

- The old version of husky doesn't work well with side-effects cache because it uses postinstall scripts to setup the hooks. The new version works because it requires a prepare script to install the hooks. We don't have a prepare script but we have a full setup script that we recommend contributors to run.

fix: update husky

---

src/scope/repositories/sources.ts

This is a regression since the removal of legacy-code. The paths weren't converted to Linux upon saving into objects.

fix(bit-tag): convert paths to linux before saving into object

---

scopes/component/snapping/tag-cmd.ts

currently, it shows the warning when using the flag `--disable-tag-pipeline` incorrectly.

fix(bit-tag): fix deprecation warning when using --disable-deploy-pipeline

---

scopes/component/graph/component-graph/component-graph.ts
scopes/component/graph/graph-builder.ts

This is happening when a dependency is imported to the local scope in an older version, which, as a result, the head `Version` object is missing.
Two fixes were done in this PR:
1. avoid calculating the latest in the graph unless it's really needed. Only "bit insight" needs this info, so no need to run it every time a capsule is created.
2. avoid using the "laterThan" method, which is not good anymore for hashes.

fix "invalid version" error when the head Version is missing

---

workspace.jsonc

- added Ellipsis for long versions
- updated floating-ui to v0.7.2
- fix dep: move @types/react from peer to regular dev dependencies
Went for `13ch`, which allows 9 digits and 3 dots. Expends on hover to reveal the whole version.
Tested on design scope

highlighter ellipsis for long hashes (+ update floating-ui)

---

src/scope/component-ops/export-scope-components.ts

Currently, when exporting on a lane, the output only shows the exported-ids from the lane-scope.
This PR fixes it by showing all exported-ids.

fix(bit-export): show the exported components correctly when exporting on a lane

---

src/scope/network/http/http.ts

currently, when running from bit-bin repo, it shows `last-tag {version}` , which makes it hard in the remote to parse it.
Instead, send always a valid semver version.

fix: send bit-client-version as a valid Semver to the remote

---

scopes/workspace/workspace/workspace.ts

implements #6089.
At first, the plan was to add it as a component-issue, so then it'll be shown in `bit status` and possibly block `bit tag`. However, during bit-status, we don't have env component (which might not be in the workspace), and therefore we don't have a way to figure out its env. Also, in case multiple components are using the same env, it'll show the warning multiple times.
With current implementation, it shows it during the component-load and only once per env.

improvement: show a warning when an env is not of type "env"

---

e2e/harmony/lanes/bit-import-on-lanes.e2e.ts
scopes/scope/importer/importer.ts
src/consumer/component-ops/import-components.ts

currently, when a lane is not on the remote, it stops the import. However, there are main-components that may need updates. This PR fixes it by importing the main component and ignoring the local lane.

fix(lane): enable importing main component when checked out to a new lane

---

scopes/workspace/workspace/workspace.ts

See https://github.com/teambit/bit/pull/6123 for context. 
- change from an error to a warning.
- show the warning only for components belong to this workspace.

improvement: show the non-env-type as a warning and only if part of the workspace

---

src/scope/component-ops/tag-model-component.ts
src/scope/repositories/sources.ts

Currently, the version-validation is happening before writing the object to the filesystem, which is after the pipeline is running. As a result, a component during tag could be published to npm as part of the pipeline but end up not tagged.

fix: validate Version object before running the build pipeline

---

scopes/workspace/workspace/bit-map.ts
scopes/workspace/workspace/workspace.ts

- Cache the list of workspace component IDs, which is accessed hundreds of
times and is an expensive operation.

perf: fix a performance regression in `bit status`

---

e2e/harmony/aspect.e2e.ts
scopes/harmony/aspect/aspect.cmd.ts
scopes/harmony/aspect/aspect.main.runtime.ts
src/e2e-helper/e2e-command-helper.ts

When running `bit aspect update`, no need to add the previous aspect with minus. 
The merge operation when a component is load already makes sure to not load the same aspect with different versions.

fix(aspect-update): avoid adding the previous aspect with minus to the .bitmap file

---

e2e/flows/id-with-wildcard.e2e.2.ts
e2e/functionalities/auto-tagging.e2e.2.ts
e2e/harmony/lanes/lanes.e2e.ts
e2e/harmony/lanes/merge-lanes.e2e.ts
e2e/harmony/snap.e2e.2.ts
scopes/component/status/status-cmd.ts
scopes/component/status/status.main.runtime.ts
scopes/lanes/lanes/lanes.docs.mdx
scopes/lanes/lanes/merge-lanes.ts
src/api/scope/lib/fetch.ts
src/consumer/bit-map/bit-map.ts
src/consumer/component-ops/import-components.ts
src/consumer/component/components-list.ts
src/consumer/consumer.ts
src/e2e-helper/e2e-command-helper.ts
src/scope/component-ops/diverge-data.ts
src/scope/component-ops/get-diverge-data.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/exceptions/no-common-snap.ts
src/scope/repositories/sources.ts
src/scope/scope.ts

- when running `bit import`, fetch lane-components not only from lane-scope but also from original scope.
- when running `bit status`, show how many snaps the main is ahead. 
- when running `bit status` and there are issues getting the diverge-data, show them to the user.
- improve `bit status --json` to show the staged versions.
- fix components with multiple parents in the history to show the staged versions correctly.

improvement(lanes): fetch updates from main when on a lane

---

scopes/react/react/apps/web/react.application.ts

- include content hash in t he webpack output file, when building app 
This should fix some cache busting problems where an older version of `main.js` got stuck in the cdn.

app build - add hash to mainfile

---

scopes/component/snapping/snapping.main.runtime.ts
scopes/component/snapping/tag-cmd.ts
scopes/harmony/cli/cli-parser.ts
scopes/harmony/cli/cli.main.runtime.ts
scopes/harmony/cli/legacy-command-adapter.ts
src/cli/command.ts
src/cli/legacy-command.ts

The current mechanism of adding a URL to the command output is cumbersome. The command aspect needs to add the community aspect as a dependency, get the base-url from it and then move the extendedDescription to the constructor and concatenate it there.
With this PR, a new prop `helpUrl` was added to the `Command` class. The CLI aspect is the one that responsible to concatenate the base-url from the community aspect to the relative-url provides by the `helpUrl` of the command. 
Since the output provided by `yargs` is already parsed and manipulated heavily, it was easy to let it render the URL as well (and with an underline style). 
Users can always override the base-url. Or override specific commands with full-url. In case the `helpUrl` has full-url, then, it won't concatenate from the …

improvement: introduce helpUrl prop for commands

---

scopes/preview/ui/component-preview/urls.ts

- added the component id the query of the preview iframe
This will fix rare errors happening when moving between components of the same env. The iframe might not  reload, and have some left overs from older components.

add component id to preview query

---

scopes/component/component-version/version.ts

for some reason, bit-build get new errors related to this file. on master `resolve()` method returns `string | null | undefined`, which makes sense. but inside the d.ts of the package it shows `string` for some reason.
this PR casts it to `string`. we really should not use this version-parser. it doesn't make sense anymore.

fix: fix errors about legacy-bit-id during bit-build of bit

---

.bitmap
e2e/harmony/lanes/lanes.e2e.ts
scopes/lanes/lanes/create-lane.ts

currently, it points to the current lane even when it's new.

fix(lane-create): fix lane.forkedFrom to point to the last exported lane

---

scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts

Currently, the filter that removes workspace-components from package-installation is considering the version. As a result, if a dependency exists in the workspace but with a different version, it's installed as package.
This PR filters out components that exist in the workspace regardless of their version.

fix(bit-install): avoid installation of a component that exists in the workspace, regardless the version

---

scopes/workspace/workspace/workspace.ts

This mutation caused bit-status in some (very) specific scenarios to show components as modified although bit-diff wasn't showing any diff.

fix: avoid mutating the workspace variants when loading components config

---

src/scope/component-ops/export-scope-components.ts

this way, when the head is missing in the original scope for some reason (e.g. component was deleted), it won't throw errors in various commands.

push main-head to the lane-scope upon export

---

workspace.jsonc

- upgrade node for bvm from 16.15.1 to 16.16.0
- upgrade engine limitation for bit install from 12.22.0 to 14.19.3

drop node12 support

---

src/consumer/component/sources/artifact-files.ts
src/scope/models/model-component.ts

currently, if checked out to a lane, and the lane has the id with a different version, it'll fetch the dists for the capsule from the lane's scope incorrectly.

fix: avoid fetching main-artifacts from lane-scope

---

e2e/harmony/snap.e2e.2.ts
scopes/component/merging/merge-cmd.ts
scopes/component/merging/merging.main.runtime.ts
scopes/component/snapping/snap-cmd.ts
scopes/component/snapping/snapping.main.runtime.ts
scopes/component/snapping/tag-cmd.ts
scopes/component/status/status-cmd.ts
src/consumer/component/components-list.ts
src/scope/component-ops/tag-model-component.ts
src/scope/repositories/sources.ts

After merging lanes, instead of requiring the users to run `bit merge --resolve`, allow using `bit snap` and `bit tag` to complete the merge process.
This is relevant only when the `bit lane merge` was used with `--no-snap` or it has unresolved conflicts. Otherwise, this command already auto-snap. 
Also, introduce `--unmerged` flag for `bit tag` and `bit snap` to tag/snap only the component-during-merge.

improvement(lanes): allow resolving unmerged via bit-tag and bit-snap

---

e2e/harmony/checkout-harmony.e2e.ts
src/cli/commands/public-cmds/checkout-cmd.ts
src/consumer/versions-ops/checkout-version.ts
src/consumer/versions-ops/merge-version/merge-version.ts

Currently, when files left with conflicts after the checkout process, Bit runs the package installation ("bit install") and compile the components. It leads to two issues:
1. since it unable to parse the files with the conflicts, it doesn't know which packages are imported in those files, so the manifest created for the package-manager is missing these packages. It leads to confusion, because users don't expect packages to be removed. 
2. since the files have conflicts, the compilation will always fail. The failure output is verbose and makes it difficult to understand the checkout results.
This PR disable these two (installation and compilation) and instead, it shows a summary of all files with conflicts and suggests to run `bit install` and `bit compile` once they're resolved.

fix(bit-checkout): avoid running package installation and compilation when files left with conflicts

---

scopes/compositions/compositions/compositions.preview-definition.ts

- fix the preview link file compositions.
link file was missing components without compositions. examples:
correct:
incorrect:
fixed to be:

fix workspace preview for components with no compositions

---

src/cli/templates/remove-template.ts

we prefer not to encourage removing a remote component as it's a dangerous operation. (deprecation is better).

improvement(bit-remove): remove suggestion to use --remote to remove a component from remote

---

e2e/harmony/lanes/merge-lanes.e2e.ts
e2e/harmony/snap.e2e.2.ts
src/scope/component-ops/untag-component.ts
src/scope/repositories/sources.ts

Currently, an error is thrown when running `bit reset` after lanes merge: 
```
removeComponentVersions found multiple parents for a local (un-exported) version snapX of comp-name
```
with this PR it's possible to revert the merge by `bit reset`.

fix(bit-reset): enable reset a local merge of lanes before export

---

scopes/scope/scope/scope.main.runtime.ts

e.g. a workspace with two components: "foo", "bar". currently, running `bit pattern "!foo"` yield zero results. 
This PR include `**` in this case and returns "bar".

fix(patterns): support patterns that have only exclude syntax

---

scopes/defender/jest/jest.tester.ts

rollback jest's root path to be the workspace / capsule for now to fix --coverage flag

---

package.json
src/consumer/config/component-config.ts
src/consumer/config/workspace-config.ts
src/npm-client/npm-client.ts
src/scope/scope-remotes.ts

removed all R.merge occurrences. seems like this function was removed from the latest (0.28.0) version. although we don't use this version, other packages are using it and it causes issues when `babel-plugin-ramda` finds it in the code.

remove R.merge

---

src/consumer/component/components-list.ts
src/scope/objects/components-index.ts
src/scope/objects/repository.ts
src/scope/scope.ts

a user was getting an error with the following stack trace
```
got an error from command tag: TypeError: component.populateLocalAndRemoteHeads is not a function
TypeError: component.populateLocalAndRemoteHeads is not a function
at C:\Users\user\AppData\Local\.bvm\versions\0.0.809\bit-0.0.809\node_modules\@teambit\legacy\dist\scope\scope.js:587:61
at Array.map (<anonymous>)
at Scope.listIncludeRemoteHead (C:\Users\user\AppData\Local\.bvm\versions\0.0.809\bit-0.0.809\node_modules\@teambit\legacy\dist\scope\scope.js:587:34)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ComponentsList.getModelComponents (C:\Users\user\AppData\Local\.bvm\versions\0.0.809\bit-0.0.809\node_modules\@teambit\legacy\dist\consumer\component\components-list.js:183:31)
at async …
```

make sure scope.list() returns only ModelComponent

---

scopes/component/merging/merge-cmd.ts
scopes/component/merging/merging.main.runtime.ts
scopes/dependencies/dependency-resolver/dependency-linker.ts
scopes/lanes/lanes/lane.cmd.ts
scopes/lanes/lanes/lanes.main.runtime.ts
scopes/lanes/lanes/merge-lanes.ts
scopes/scope/scope/scope.main.runtime.ts

This fix is for both `bit merge` and `bit lane merge`. Currently, it was looping throw the components, and running the package-manager on each one of them.
This PR fixes it to run it once and only if `--skip-dependency-installation` was not entered and only if no conflicts were found. 
Also, fixed an issue with pattern containing negation.

fix(merge): avoid running package-installation for each one of the components individually

---

e2e/harmony/lanes/merge-lanes.e2e.ts
scopes/lanes/lanes/merge-lanes.ts
src/consumer/versions-ops/checkout-version.ts
src/consumer/versions-ops/merge-version/three-way-merge.ts

currently, when the lane is diverged and the other lane introduced new files, they don't get created during merge.

fix(bit-lane-merge): add files that were introduced in the other lane

---

e2e/fixtures/components/custom-dev-files/comp.custom-composition-suffix.tsx
e2e/fixtures/components/custom-dev-files/comp.custom-docs-suffix.mdx
e2e/fixtures/components/custom-dev-files/custom-dev-files.js
e2e/fixtures/components/custom-dev-files/custom-dev-files.registered-test.spec.js
e2e/fixtures/components/custom-dev-files/custom-dev-files.spec.js
e2e/fixtures/components/custom-dev-files/file.custom-dev-file.js
e2e/fixtures/components/custom-dev-files/index.js
e2e/fixtures/extensions/dev-files-env/dev-files-env.extension.ts
e2e/fixtures/extensions/dev-files-env/index.ts
e2e/harmony/dev-files.e2e.ts
scopes/component/dev-files/dev-files.main.runtime.ts
scopes/compositions/compositions/compositions.main.runtime.ts
scopes/defender/tester/tester.main.runtime.ts
scopes/defender/tester/tester.service.tsx
scopes/envs/envs/environment.ts
src/e2e-helper/e2e-env-helper.ts
src/e2e-helper/e2e-fixtures-helper.ts

- new envs API:
- `getCompositionsDevPatterns?: (component: Component) => string[];`
- `getDevPatterns?: (component: Component) => string[];`
- `getTestsDevPatterns?: (component: Component) => string[];`
An example of a custom env that uses it looks something like this:
```js
envs.override({
getTestsDevPatterns: () => ['**/*.registered-test.spec.+(js|ts|jsx|tsx)', '**/*.registered-test.test.+(js|ts|jsx|tsx)'],
getDocsDevPatterns: () => ['**/*.custom-docs-suffix.*'],
getCompositionsDevPatterns: () => ['**/*.custom-composition?(s)-suffix.*'],
getDevPatterns: () => ['**/*.custom-dev-file.*']
}),
```

better support for dev file registration by a component env

---

scopes/webpack/webpack/config/webpack.dev.config.ts

- delete resolve.extensions array coming from webpack aspect, which was placing .js/.ts etc before the more specific extensions in the env's webpack config, causing unexpected behaviour and bugs, e.g. with packages exposing .web.js modules
- resolves #6161
- 
-

remove duplicate resolve.extensions causing bugs

---

scopes/workspace/workspace/build-graph-from-fs.ts
scopes/workspace/workspace/workspace.ts

sometimes `workspace.loadAspects()` calls itself during the run to complete the aspect load. as a result, it's difficult to figure out from the logs why particular aspects were loaded. 
This PR makes it easier. Just search for `loadAspects, `, find your aspect, then search the log by the call-id to find out which aspects needed it.

improvement(aspect-loader): log with a unique id for each loadAspects call

---

scopes/component/component-compare/component-compare-widget.tsx
scopes/pipelines/builder-ui/builder.section.tsx
scopes/pipelines/builder-ui/builder.ui.runtime.tsx
scopes/pipelines/builder-ui/component-pipeline-widget/component-pipeline-widget.module.scss
scopes/pipelines/builder-ui/component-pipeline-widget/component-pipeline-widget.tsx
scopes/pipelines/builder-ui/component-pipeline-widget/index.ts

- Move Pipeline tab to widgets tabs instead of the main tabs.
- Not register the widget for the moment. (Still available via the route)

Move pipeline tab to widgets and hide it for the moment

---

scopes/component/component/component-factory.ts
scopes/component/dev-files/dev-files.main.runtime.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/workspace/workspace/build-graph-from-fs.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
scopes/workspace/workspace/workspace.provider.ts
scopes/workspace/workspace/workspace.ts
src/consumer/bit-map/component-map.ts
src/consumer/component-ops/component-writer.ts
src/consumer/component/component-loader.ts
src/consumer/consumer.ts

This is a long overdue task.
When writing a component to the capsule, until now, the component-writer used to mutate the `Component` object and replace its rootDir (to `.` via the component-map prop). In order to avoid changing the instance of the normal Component object, the component-loader used to have two caches, one for the capsule and one for the normal loading. 
Besides the complexity it creates where `get()` method has the `forCapsule` boolean, it also caused some issues where in one instance it didn't ask for the capsule, got the normal one and mutated it. 
This PR fixes it by not mutating the component object for capsules. Instead, it gather all the data it needs to write the component in the capsule in one place and writes it.

avoid mutating Component object for capsules

---

e2e/harmony/import-harmony.e2e.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

this fixes an issue of bit-status shows an imported component as modified due to missing "types" package.

fix: resolve @types packages from model if not exists in workspace.jsonc

---

e2e/fixtures/extensions/custom-jest-resolve-env/custom-jest-resolve-env.aspect.ts
e2e/fixtures/extensions/custom-jest-resolve-env/custom-jest-resolve-env.main.runtime.ts
e2e/fixtures/extensions/custom-jest-resolve-env/index.ts
e2e/fixtures/extensions/custom-jest-resolve-env/jest/jest.config.js
e2e/fixtures/extensions/custom-jest-resolve-env/typescript/tsconfig.json
e2e/fixtures/extensions/custom-jest-resolve-env/webpack/webpack-transformers.ts
e2e/harmony/jest.e2e.ts
scopes/defender/jest/jest.main.runtime.ts
scopes/defender/jest/jest.tester.ts
scopes/defender/tester/index.ts
scopes/defender/tester/tester.service.tsx
scopes/defender/tester/tester.task.ts
scopes/defender/tester/tester.ts

- change tester's ComponentPatternsMap API - add component dir, and move the paths into paths prop
- support new opts for creating jest tester - patterns, roots, resolveSpecPaths

support new opts for creating jest tester - patterns, roots, resolveSpecPaths

---

scopes/lanes/lanes/lanes.main.runtime.ts
scopes/scope/sign/sign.main.runtime.ts
src/consumer/component/sources/artifact-files.ts
src/consumer/consumer.ts
src/scope/scope.ts

Also, improve the debug-log when artifacts were not found in the scope. Previously, it was throwing ENOENT from the remote. Now, it prints to the log for each object its origin component-id.

fix(bit-sign): fetch dists of dependencies aspects from the lane-scope

---

e2e/commands/untag.e2e.2.ts
scopes/component/snapping/snapping.main.runtime.ts
scopes/component/snapping/tag-model-component.ts
scopes/scope/export/export.main.runtime.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/scope/scope/staged-config.ts
src/consumer/consumer.ts
src/e2e-helper/e2e-command-helper.ts
src/e2e-helper/e2e-general-helper.ts

Currently, if a config was added to the .bitmap file, it gets deleted during `bit tag`. as a result, when running `bit reset`, there is no way to get it back, and the workspace is left without the config changes unexpectedly. 
This PR implements a new mechanism of storing this config between the tag and the export, so then, `bit reset` can copy the config from this file and put it back in the .bitmap file.
See https://github.com/teambit/bit/discussions/5074#discussioncomment-1787197 for more info about this topic.

fix(bit-reset): revert the config in .bitmap

---

e2e/harmony/status-harmony.e2e.ts
scopes/workspace/workspace/build-graph-from-fs.ts
src/scope/component-ops/auto-tag.ts

Currently, if a component is deleted from the filesystem, we know to show it as an "invalid component" in bit-status.
However, if this deleted component is a dependency of another component, and that dependent is modified, Bit thrown an error ComponentNotFondInPath. This PR fixes it to not throw.

fix(bit-status): avoid throwing when modified and a dependency is deleted from the filesystem

---

e2e/harmony/lanes/bit-reset-on-lanes.e2e.ts
e2e/harmony/lanes/lanes.e2e.ts
src/scope/repositories/sources.ts

In some scenarios deleting the Version objects can be an issue. See the e2e-test in this PR for such a case.
It's ok to leave them as they lightweight and their hash is unique (v4). If needed, we'll develop a GC mechanism to remove them later.

fix(bit-reset): avoid deleting Version objects

---

e2e/harmony/checkout-harmony.e2e.ts
src/consumer/versions-ops/checkout-version.ts

so then `bit checkout head` checks out to the remote-head rather than the local-head.

improvement(bit-checkout): import components before checkout 

---

scopes/component/isolator/isolator.main.runtime.ts
src/consumer/component/components-list.ts

it causes some race-condition when these components need external aspect to be loaded. the same aspects are isolated at the same time in the same capsule, as a result, some files are deleted by one call while they're being read by another call.

fix: avoid loading the same components at the same time

---

e2e/harmony/init-harmony.e2e.ts
src/consumer/consumer-locator.ts
src/consumer/consumer.ts

currently, it shows command-not-found unexpectedly.

fix: show a descriptive error when workspace has workspace.jsonc but not .bitmap nor .bit

---

scopes/component/merging/merging.main.runtime.ts
scopes/lanes/merge-lanes/merge-lane.cmd.ts
scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts

when the modification is config only (such as dependencies changes), not files.

feat(bit-lane-merge): introduce "--ignore-config-changes" to merge modified components 

---

e2e/harmony/checkout-harmony.e2e.ts
scopes/component/checkout/checkout.main.runtime.ts

In some cases, the .bitmap is not up to date with exported component. Locally, a component is new, but in fact the component has been exported to the remote.
This could happen for example when the CI tags+exports and for some reason the .bitmap wasn't pushed to Git. 
With this PR, these new components are updated during `bit checkout head` to the latest version on the remote.
(other cases of out-of-sync are already taken care during the component-load. this case involves going to the remote for all new components, so for performance reasons it's done on bit-checkout).

improvement(bit-checkout-head): sync non-exported components with their remote default-scope

---

e2e/harmony/tag-harmony.e2e.ts
src/consumer/component/consumer-component.ts
src/scope/models/model-component.ts
src/scope/objects/repository.ts
src/scope/repositories/sources.ts

In case `bit tag` reaches the default `cache.max.objects`, it throws VersionNotFound error because the Version object got removed from the cache.
This PR fixes it by grabbing the object from `repo.objects` first.

fix(bit-tag): avoid relying on the repo.cache when tagging components

---

scopes/component/forking/forking.main.runtime.ts

When forking components via `bit new`, search & replace old package names with new names. 
It used to work in the past, but for some reason the "refactor: true" option wasn't passed to `refactorMultipleAndInstall` method.

fix(bit-new): refactor forked components

---

scopes/workspace/workspace/workspace-component/workspace-component-loader.ts

Otherwise, the typescript server will throw an error because the files are not in the filesystem.

fix: avoid running on-load for removed components

---

scopes/component/merging/merge-cmd.ts
src/consumer/component/components-list.ts

It can happen when merging laneA to laneB, and comp1 is newly introduced to laneB, so on laneB remote it doesn't exist. 
This PR removes these entries as they are not needed. Getting updates from main (by "bit lane merge main") helps to resolve these as well.

fix(bit-status): avoid showing a component as pending-merge when it is in updates-from-main section

---

e2e/harmony/lanes/merge-lanes.e2e.ts
scopes/component/component-log/log-cmd.ts
src/consumer/versions-ops/checkout-version.ts
src/consumer/versions-ops/merge-version/merge-version.ts
src/scope/component-ops/traverse-versions.ts
src/scope/models/model-component.ts

- fix bit-log to not show duplicate entries when history is split by having two parents.
- fix bit-checkout to not throw an error when one of the file versions removes the content from the file.
- add e2e-tests for merge-lanes when the local lane has soft-removed components.

remove duplications from getAllVersionsInfo and fix bit-checkout of empty files

---

scopes/component/component/component.ts

When running sort and limit on components' logs, make sure to run sort before the limit

fix sort + limit logs entries on components

---

scopes/component/component/component.graphql.ts

when fetching component logs via gql, if the component id is hash take it as head

---

e2e/harmony/lanes/lanes.e2e.ts
e2e/harmony/lanes/merge-lanes.e2e.ts
scopes/component/merging/merging.main.runtime.ts
scopes/scope/importer/import-components.ts
src/consumer/consumer.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/exceptions/no-head-no-version.ts
src/scope/models/model-component.ts

- when on a lane, import components from main even when they do not have head because it's possible that a component was created later on the origin-scope.
- fix resolve-unrelated case of bit-lane-merge when main got more snaps after a lane was resolved and the current lane is merging that lane.

fix(import): import components from main even when they do not have head

---

e2e/harmony/lanes/lanes.e2e.ts
scopes/lanes/lanes/switch-lanes.ts

Currently when switching between local lanes and they're all exported, the prop in bitmap shows "exported: false". this PR fixes it by verifying against the scope.json

fix(bit-switch): set "exported" prop in bitmap-lane-key correctly

---

src/consumer/component/sources/artifact-files.ts

Currently, in some cases it throws `ParentNotFound` during `bit sign`. With this PR, before we check whether an id is on the lane, we fetch all history of that component.

fix(bit-sign): fetch all history of components that their dists are missing

---

src/scope/exceptions/no-common-snap.ts

Not only main as it was before.

improvement: fix the error message of no-common-snap to be applicable to any bit-lane-merge

---

src/consumer/component/sources/artifact-files.ts

similar to a previous PR: https://github.com/teambit/bit/pull/6473, this is about fetching from main to not get an error about head is missing from the filesystem.

fix(bit-sign): fetch lane components from main when dists are missing

---

scopes/component/isolator/isolator.main.runtime.ts
src/consumer/component/package-json-utils.ts

currently, in some occurrences (during bit-sign), when a component version is a hash (snap) its package.json inside the capsule has the hash as the version.

fix(isolator): write the package.json inside capsules with valid version when it is a snap

---

e2e/harmony/lanes/merge-lanes.e2e.ts
scopes/lanes/merge-lanes/merge-lane-from-scope.cmd.ts
scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts

currently, when merging from multiple scopes, it pushes only the Component and Version objects, but not the files.
This PR is using the high-level `exportMany` method to fix the issue.

fix(merge-lane-from-scope): export all objects to all scopes

---

scopes/component/snapping/snapping.main.runtime.ts
scopes/component/snapping/tag-model-component.ts
scopes/pipelines/builder/builder.main.runtime.ts
scopes/scope/scope/index.ts
scopes/scope/scope/scope.main.runtime.ts
src/scope/scope.ts

Previously, the tag was on legacy and to get the builder aspect running during tag, a few indirections was needed. There indirections weren't trivial and confusing. (tag called legacy-scope, which had the harmony-scope register to its onTag. this onTag registered the builder tagListener which eventually got called during tag).
Now it's easier to just call the builder directly from the Snapping aspect.

refactor: remove onTag slot, call builder directory during tag/snap

---

e2e/harmony/extensions-config.e2e.3.ts
e2e/harmony/lanes/lanes.e2e.ts
scopes/component/component/component-factory.ts
scopes/component/graph/graph-builder.ts
scopes/workspace/workspace/build-graph-from-fs.ts
scopes/workspace/workspace/workspace.ts
src/scope/component-ops/export-scope-components.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/exceptions/component-not-found.ts
src/scope/models/model-component.ts
src/scope/objects-fetcher/objects-fetcher.ts

- when running `bit status` and components have missing dependencies, do not throw an error.
- when exporting components and dependencies are missing from a non-head version, do not throw an error.
- fix the ComponentNotFound message to not suggest running "bit dependent". in most cases it doesn't help and is only confusing.

fix(bit-export): avoid throwing ComponentNotFound when a dependency is missing from non-head

---

scopes/component/graph/graph-builder.ts

This graph was cache for no reason.

fix: avoid caching the component-graph

---

e2e/harmony/lanes/lanes.e2e.ts
scopes/component/merging/merging.main.runtime.ts
scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
scopes/scope/export/export.main.runtime.ts
src/consumer/component/components-list.ts
src/scope/component-ops/export-scope-components.ts
src/scope/component-ops/get-diverge-data.ts
src/scope/component-ops/traverse-versions.ts
src/scope/models/model-component.ts
src/scope/objects/objects-readable-generator.ts
src/scope/repositories/sources.ts
src/scope/scope.ts

- improve bit-export performance when on a lane by checking the head on the remote and sending only the missing objects.
- when merging lane objects, do not rely on the local cache to get Version/Component objects. in case many objects were exported, the cache won't have them all. instead, check the object received during export.

fix(bit-export): send only objects needed when exporting on lane and do not rely on the cache

---

e2e/harmony/lanes/lanes.e2e.ts
scopes/scope/export/export.main.runtime.ts
src/scope/models/model-component.ts

by sending only the snapped versions to the remote. the algorithm to find them on a lane is the same one used in `bit status`.
Also, fixed the "getDivergeData" for a new lane, to compare the local-lane vs remote-lane and not versus the main.

improvement(bit-export): improve lane-export performance
