teambit/bit

- e2e/harmony/lanes/bit-reset-on-lanes.e2e.ts
- e2e/harmony/lanes/lanes.e2e.ts
- scopes/scope/export/export.main.runtime.ts
- src/scope/models/model-component.ts
In some cases, due to a recent change (https://github.com/teambit/bit/pull/6507), `bit reset` throws errors while trying to remove exported-versions. 
For now, the code mostly reverts what was done in that PR. Later, a new PR will be created to calculate the local versions more accurately.
> fix(bit-reset): make local-versions on lane be aware of main to not reset it

- scopes/dependencies/pnpm/pnpm-error-to-bit-error.spec.ts
- scopes/dependencies/pnpm/pnpm-error-to-bit-error.ts
> fix: don't fail when error from pnpm doesn't have a code

- e2e/harmony/lanes/bit-reset-on-lanes.e2e.ts
- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/scope/export/export.main.runtime.ts
- src/scope/component-ops/get-diverge-data.ts
- src/scope/component-ops/traverse-versions.ts
- src/scope/lanes/remote-lanes.ts
- src/scope/models/model-component.ts
- src/scope/objects/objects-readable-generator.ts
- src/scope/repositories/sources.ts
Until now, it was done by traversing the local and remote snaps. The “remote-head” was the head on the remote-lane, and if not-exist (the component is new on this lane), it’s the remote-head of main.
The issue with this is that sometimes we get incorrect results. In case of merging lane-a into lane-b, and a new component introduced as part of the merge to lane-b, all the history of this component of lane-a is considered local. Because this history is considered local, bit-reset removes it unexpectedly.
Another issue is the export performance. We send way too many objects unnecessarily. Especially when lane-a is merged into lane-b, both on the same scope and lane-a has tons of snaps that were already exported. 
This PR fixes it by searching all remote-refs files (of lanes only, not main) …
> fix finding local-versions when on a lane

- e2e/harmony/lanes/lanes.e2e.ts
- src/scope/component-ops/get-diverge-data.ts
This is a regression caused by https://github.com/teambit/bit/pull/6504.
> fix(bit-export): fix parent-not-found error when sending multiple snaps to a remote

- package.json
This package is used in the legacy code and needs to be part of the package.json file.
> add @teambit/component-issues package to legacy

- src/consumer/component/sources/artifact-files.ts
When an artifacts is needed, Bit goes to the lane-remote or main-remote depends whether this version is on the lane.
In case a component is during merge, its aspects config/data consist of both: the current version and the merged version, as such, it's hard to know where to get the artifacts from. the current-version scope or the merged-version scope.
This PR attempts to go to the merged-scope first, and then to the current-version scope.
> fix: download artifacts from unmerged-lane-id when applicable

- src/scope/component-ops/traverse-versions.ts
- src/scope/objects/objects-readable-generator.ts
By memoizing the `getAllVersionHashes` method.
> fix: keep memory consumption sane when traversing history during fetch

- e2e/harmony/corrupted-objects.e2e.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/scope/importer/fetch-cmd.ts
- scopes/scope/importer/import-components.ts
- scopes/scope/importer/import.cmd.ts
- scopes/scope/importer/importer.main.runtime.ts
- scopes/workspace/install/install.main.runtime.ts
- src/e2e-helper/e2e-general-helper.ts
- src/utils/zlib-inflate.ts
Currently, if `bit import` is interrupted, the objects might be corrupted and there is no easy way to recover other than deleting the local scope.
With this PR, it's possible to recover by running `bit import --all-history`.
> allow recovering when objects are corrupted

- e2e/harmony/aspect.e2e.ts
- scopes/harmony/aspect/aspect.cmd.ts
- scopes/harmony/aspect/aspect.main.runtime.ts
Currently it shows a misleading message: "unable to find any component that use ..."
> fix(bit-aspect-update): indicate in the output when components are up to date

- .gitignore
- scopes/harmony/ui/aspect-box/aspect-box.module.scss
- scopes/harmony/ui/aspect-box/aspect-box.tsx
- scopes/react/ui/docs-app/index.tsx
- Allow expanding/collapsing config/data for nested objects in aspects page
- Allow copying config/data json
> Aspects Page: Expand/Collapse nested objects + Copy JSON

- scopes/workspace/workspace/build-graph-from-fs.ts
- src/scope/component-ops/scope-components-importer.ts
- src/scope/models/model-component.ts
also, makes the log cleaner by removing lots of ids from certain import functions.
> perf: avoid refetching unbuilt versions when building a graph

- e2e/harmony/lanes/lanes.e2e.ts
- src/api/scope/lib/action.ts
- src/e2e-helper/e2e-command-helper.ts
- src/scope/actions/fetch-missing-history.ts
- src/scope/actions/index.ts
- src/scope/component-ops/scope-components-importer.ts
This is useful for a remote when exporting a lane with components from another scope to get the history of those components.
> feat: add a new "FetchMissingHistory" action

- scopes/semantics/schema/schema-extractor.ts
- scopes/semantics/schema/schema.main.runtime.ts
- scopes/semantics/schema/schema.spec.ts
- scopes/typescript/typescript/typescript.extractor.ts
currently, when running `bit test schema`, the process never exit. This PR fixes it by killing the TS-Server once done.
> test: fix schema tests to exit the process after getting the schema

- scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts
Currently, when running `bit build` on bit repo, the `node_modules/@teambit/legacy` in the capsules is a package, not symlink. As a result, PRs fail with errors about mismatch types between the last version of teambit/legacy package and the current code of the legacy.
(this change was done with @GiladShoham ).
> fix: filter teambit/legacy from root policy

- src/consumer/consumer.ts
- src/logger/logger.ts
It's gonna be very helpful for debugging to understand what commands were running on this workspace.
> feat: save all commands history on the workspace into .bit/command-history

- e2e/harmony/lanes/lanes.e2e.ts
- scopes/component/checkout/checkout-cmd.ts
- scopes/component/checkout/checkout.main.runtime.ts
- src/consumer/versions-ops/merge-version/merge-version.ts
- allow adding components that exist on the lane but don't exist locally by running `bit checkout head --entire-lane`.
- show a quick summary with the data about the checkout results.
> feat(bit-checkout): introduce --entire-lane flag to get new components on a lane

- scopes/defender/mocha/mocha.tester.ts
Currently, when mocha is set as the default tester, the tests output are displayed during `bit start`. 
Since Mocha doesn't have a worker/watch built-in mechanism, it's best to disable it for now in case the tests are coming from the UI.
> fix(bit-start): avoid showing mocha tests output during bit-start

- scopes/component/snapping/snapping.main.runtime.ts
- scopes/scope/export/export.main.runtime.ts
- src/consumer/component/consumer-component.ts
- src/scope/models/version.ts
This is a preparation for a future improvement of not importing all flattened dependencies.
> add flattened dependencies as a graph to the model

- e2e/harmony/snap.e2e.2.ts
- src/scope/models/model-component.ts
- src/scope/repositories/sources.ts
Currently, in case of diverge, during reset, the head (of the component or inside the lane) is set to the remote-head. Inside the .bitmap the version is set to be the same as the head. 
This PR fixes it to set the head back to what it was before the local snaps as expected.
> fix(reset): change the head to be the common-before-diverge instead of the remote-head

- scopes/scope/export/export.main.runtime.ts
- src/scope/actions/export-validate.ts
- src/scope/component-ops/export-scope-components.ts
- src/scope/component-ops/scope-components-importer.ts
currently, when exporting a lane with external components (components on a lane that belong to other scopes), there is a calculation of additional objects needed to be sent to the lane-scope in case it's missing from there. 
This PR takes a different approach. It only sends the local-snapped objects. Other missing objects on the lane-scope, will be fetched directly by the lane-scope during the validation phase.
> fix(export): avoid sending historical Version objects during export on lane

- e2e/harmony/dependencies-cmd.e2e.ts
- scopes/dependencies/dependencies/dependencies.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
This is happening when running `bit deps set X`, tagging, then `bit deps set Y --dev`, the last one overrides what was set before the tag. This PR fixes it by ejecting the specific dep-resolver config into the .bitmap.
> fix(deps-set): avoid overriding dependencies set before tag/snap

- e2e/harmony/lanes/bit-import-on-lanes.e2e.ts
- src/scope/component-ops/scope-components-importer.ts
- src/scope/models/model-component.ts
Although it was implemented in the original performance improvement PR (https://github.com/teambit/bit/pull/6639), it wasn't working properly because it was trying to import only delta. (delta is not really useful with the new optimization). Fixed by asking the component-delta to get all history from head.
> fix(bit-log): import all history in case they are missing

- e2e/commands/list.e2e.1.ts
- e2e/functionalities/workspace-config.e2e.3.ts
- e2e/harmony/dependencies-cmd.e2e.ts
- scopes/component/component-issues/issues-list.ts
- scopes/component/component-issues/missing-manually-configured-packages.ts
- src/cli/templates/component-issues-template.ts
- src/consumer/component/dependencies/dependency-resolver/dependencies-loader.ts
- src/consumer/component/dependencies/dependency-resolver/overrides-dependencies.ts
- src/e2e-helper/e2e-bit-jsonc-helper.ts
- src/e2e-helper/e2e-general-helper.ts
- src/e2e-helper/e2e-scope-helper.ts
currently, when running `bit deps set` and the component dependency is not imported nor installed and is added with a specific version, it is added as package instead of a component.
It's happening because Bit doesn't have the package.json to know that it's a componnet.
This PR shows the component/package as missing until it's installed. Once installed, it's recognized correctly.
> improvement: show missing packages when manually added with versions

- scopes/component/isolator/capsule-list.ts
For build you can use `toposort()` on the network `seedersCapsules` to ensure that the capsules are sorted by dependencies.
> add `toposort` method to `CapsuleList`

- scopes/harmony/bit/load-bit.ts
- scopes/harmony/config/config.main.runtime.ts
Looks like Config aspect doesn't use it, so it should be safe to remove. (currently, `loadLegacyConfig()` function loads Config aspect before anything else and it causes the CLI aspect to be loaded. as well).
> fix: avoid loading cli aspect twice by removing it from ConfigAspect dependencies

- scopes/component/isolator/isolator.main.runtime.ts
- scopes/scope/sign/sign.main.runtime.ts
- src/scope/objects-fetcher/objects-fetcher.ts
- print to the console how long took installation on capsules
- print to the console how long took import on `bit sign`
- don't show the objects count during import if is running on a CI. (`process.env.CI` is `true`).
> improvement: print install and import duration, suppress object-count on ci

- scopes/component/testing/mock-components/index.ts
- scopes/component/testing/mock-components/mock-components.ts
- scopes/harmony/testing/load-aspect/load-aspect.ts
- scopes/lanes/lanes/lanes.spec.ts
- `loadAspect()` of the testing framework supports non-core aspects.
- add a new API to modified mocked components.
> improvement(testing): support non-core aspect loading

- scopes/dependencies/yarn/yarn.package-manager.ts
- settings provided by Bit should have higher priority than internal Yarn settings.
> fix: Yarn should write the global cache to the folder that Bit specifies

- scopes/dependencies/yarn/yarn.package-manager.ts
- Yarn should hardline the files to node_modules from its global content-addressable store.
> perf: Yarn should use a content-addressable store

- e2e/harmony/mocha-tester.e2e.ts
- scopes/component/component-issues/issues-list.ts
- scopes/component/issues/issues.main.runtime.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/defender/mocha/mocha.tester.ts
- scopes/lanes/lanes/lanes.spec.ts
Until now, failure during hooks, such as `before()` was ending with code 0 (success). 
This PR registers to an event on Mocha that catches these errors and report them correctly to the tester.
> fix(mocha): handle failures inside hooks

- e2e/harmony/tag-harmony.e2e.ts
- scopes/component/snapping/tag-model-component.ts
currently, for auto-tag it always bump by patch. for pre-release, it makes sense to use the same pre-release for the auto-tag.
> fix(tag): use pre-release for auto-tag as well instead of patch

- scopes/workspace/workspace/workspace.ts
Bit calculates the aspect based on different sources, such as, model, workspace.json, bitmap. At each source, the aspects are loaded. The reason was to get the envs registered so then we know whether we have already an env configured, and then ignore other envs from different sources.
This is now not needed, because all envs are registered via `teambit.envs/envs`, so it's possible to get the env from there and no need to load the aspect to check whether it's an env.
The load is done at the end, once all aspects from different sources are merged.
> fix: load extensions only once after merging from different sources

- scopes/pipelines/builder/artifact/artifact-list.ts
Currently, multiple artifacts are imported concurrently. As a result, it's possible that the same file being written to the filesystem from multiple remotes at the same time, causing them to be corrupted.
> fix(artifacts): fix objects corruption during artifacts import by importing them one by one

- scopes/lanes/lanes/lanes.graphql.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/lanes/lanes/lanes.spec.ts
- Allow querying `diffStatus` for given `source` and `target` LaneIds
**Schema**
type LaneComponentDiffStatus {
componentId: ComponentID!
changeType: String!
upToDate: Boolean!
}
type LaneDiffStatus {
source: LaneId!
target: LaneId!
upToDate: Boolean!
componentsStatus: [LaneComponentDiffStatus!]!
}
type Lanes {
diffStatus(source: String!, target: String): LaneDiffStatus!
}
> Lanes: Gql API: diff status

- scopes/workspace/install/install.main.runtime.ts
- Remember the manifests that were already used to install dependencies. Don't repeat installation for the same set of dependencies.
- Don't run installation more than 5 times.
> fix: don't rerun install for the same manifests again

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/merging/merging.main.runtime.ts
Until this fix it wasn't merging only if the other lane has it as removed. This PR also checks the current lane/main.
> fix(lane-merge): avoid merging when current component is soft-removed

- e2e/harmony/dependencies-cmd.e2e.ts
- scopes/dependencies/dependencies/dependencies.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
currently, `bit deps remove` adds a new entry to .bitmap in case it doesn't have any. as a result, this entry overrides any other deps setting created previously. 
This PR fixes it by retrieving the current deps data from the scope and apply the removal on this data.
> fix(deps-remove): avoid removing deps that were set before tag/snap

- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- support setting default bit registry by using `bit config set registry <registry-url>`
This registry will be used to replace the default registry in case it was configured to `https://registry.npmjs.org`
> support setting default bit registry in global bit config

- e2e/harmony/multiple-envs.e2e.ts
- scopes/dependencies/dependencies/dependencies.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
otherwise, it shows a warning of multiple-env on bit-status.
> fix(envs-set): remove the previous env even when not in the .bitmap

- scopes/workspace/workspace/workspace.ts
- check whether a source (model/bitmap/workspace.jsonc, etc) has an env configured not only by the config but also by the data
- ignore the version when searching for duplicate envs aspects because that's how they're stored in envs/envs.
> fix: avoid loading envs aspects from various sources once an env is determined either by config or data

- scopes/compilation/bundler/bundler.main.runtime.ts
- scopes/compilation/bundler/bundler.service.tsx
- scopes/compilation/bundler/dev-server.service.tsx
- scopes/compilation/compiler/compiler.service.tsx
- scopes/defender/formatter/formatter.service.tsx
- scopes/defender/linter/linter.service.tsx
- scopes/defender/tester/tester.service.tsx
- scopes/envs/envs/env.plugin.ts
- scopes/envs/envs/environments.main.runtime.ts
- scopes/envs/envs/index.ts
- scopes/envs/envs/services/index.ts
- scopes/envs/envs/services/service.ts
- scopes/generator/generator/generator.main.runtime.ts
- scopes/generator/generator/generator.service.tsx
- scopes/pipelines/builder/builder.service.tsx
- scopes/pkg/pkg/pkg.service.tsx
- scopes/preview/preview/preview.main.runtime.tsx
- scopes/preview/preview/preview.service.tsx
- scopes/semantics/schema/schema.service.ts
- env services transform API
- remove hard coded transform functions from env.plugin
- implement schema transform
- implement preview service with transform func
- implement generator service with transform func
- implement bunlder service with transform func
- implement builder transform
- implement dev server transform
- implement tester transform
- implement compiler transform
- implement pkg transform
- improve service transform type
- implement linter transform
- implement formatter transform
> env service transformers

- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/tag-model-component.ts
- scopes/scope/update-dependencies/update-dependencies.main.runtime.ts
Due to some previous bugs, some components might have missing flattened dependencies. As a result, the flattenedEdges may have more components than the flattenedDependencies, which will cause issues later on when the graph is built. 
This fixes it by adding the missing flattened dependencies, and then recursively adding the flattenedEdge accordingly.
> fix: add missing flattened and edges to new snap/tag

- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
Currently, when dependencyResolver.data.policy has auto-detected dependencies and they're missing from node-modules, `bit install` doesn't install them. 
This PR adds them to the dependencies list during the dependency resolution, so then `bit install` will install them successfully.
(implemented according to @GiladShoham 's instructions)
> fix: auto install auto-detected from overrides

- e2e/harmony/lanes/diverged-from-forked.e2e.ts
- e2e/harmony/lanes/merge-lanes.e2e.ts
- e2e/harmony/updates-from-main-and-lane.e2e.ts
- scopes/component/checkout/checkout.main.runtime.ts
- scopes/component/status/status-cmd.ts
- scopes/component/status/status.main.runtime.ts
- scopes/lanes/merge-lanes/merge-lane-from-scope.cmd.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- src/consumer/component/components-list.ts
- src/e2e-helper/e2e-command-helper.ts
- src/scope/models/model-component.ts
- src/scope/scope.ts
Here is a scenario to help explaining the confusion this PR aims to solve.
A workspace is checked out to a lane "dev", and  has two components: comp1 -> comp2 (comp1 is using comp2). comp2 is part of the lane (was snapped on the lane), but comp1 was just imported to the workspace and belong to main.
Assuming comp1 is ahead on main and comp2 is ahead in the remote-lane, until now, `bit status` was showing them both in "pending updates" section, and `bit checkout head` was updating them both.
It might seem logical, because these two components are available in the workspace, however, what if on main a feature was implemented (e.g. an API breaking change) and during the change on comp2, comp1 was changed as well to accommodate these changes. Merging only comp1 from main could break the app …
> improvement(status/checkout): pendingUpdates only shows current-lane/main

- e2e/harmony/merge-config.e2e.ts
- scopes/workspace/workspace/workspace.ts
In the case the env is received from the model and the workspace has the env component with different version, use the version from the workspace.
> fix: change env version according to the workspace

- scopes/dependencies/yarn/yarn.package-manager.ts
- when Yarn is used, use copying for importing packages from the store by default
-
-
> fix: use copying by default for importing packages from the store by Yarn

- src/scope/component-ops/get-diverge-data.ts
Currently, the `commonSnapBeforeDiverge` is not necessarily the first/closest ancestor when there are two parents at some point. This PR fixes it by assigning a weight/depth for each common-snap.
> fix: fix the common parent between two heads to be the first parent

- scopes/code/ui/code-compare/code-compare-view/code-compare-view.tsx
- scopes/lanes/ui/compare/lane-compare-drawer/lane-compare-drawer-name.tsx
- scopes/lanes/ui/compare/lane-compare/lane-compare.tsx
- Add Custom Bit theme to Monaco. Remove box shadow from scrollbar
- Display shortHash (6 char) in Lane Compare Drawer Name
- Remove loading: undefined check when constructing lane component lookup
> Component/Lane Compare: Style Fixes

- scopes/component/merging/merging.main.runtime.ts
Helpful to get the base-snap when merging lanes.
> log(merge): add snaps details into the debug.log

- scopes/dependencies/dependencies/dependencies-cmd.ts
- scopes/dependencies/dependencies/dependencies.main.runtime.ts
- introduce `bit deps reset` to reset dependencies to the default values (revert any previously "bit deps set")
- introduce `bit deps eject` to write dependencies that were previously set via "bit deps set" into .bitmap
> feat(deps-reset): implement bit deps reset and bit deps eject

- scopes/preview/preview/index.ts
- scopes/scope/importer/import.cmd.ts
In this case, just shows it as `removed`. the deprecation is less relevant. 
Also, make the output of `bit import` without args more clear by dimming the details of individual component and placing the summary at the end.
> fix(import): fix the output when a component is deprecated and removed

- e2e/commands/remove.e2e.1.ts
- e2e/flows/out-of-sync-componets.e2e.3.ts
- e2e/harmony/import-harmony.e2e.ts
- e2e/harmony/lanes/bit-remove-on-lanes.e2e.ts
- e2e/harmony/lanes/lanes.e2e.ts
- e2e/harmony/out-of-sync-components-harmony.e2e.ts
- e2e/harmony/snap.e2e.2.ts
- e2e/harmony/track-directories-harmony.e2e.ts
- scopes/component/remove/remove-components.ts
- scopes/component/remove/remove.main.runtime.ts
- src/e2e-helper/e2e-bitmap-helper.ts
- src/scope/component-ops/remove-model-components.ts
- src/scope/graph/graph.ts
From the workspace, it's ok to remove components that other components are using them, because the user can always install the component as a package or re-import it.
From the scope, this action is irreversible, so it makes sense to require the `--force` flag.
> fix: allow removing components with dependents from the workspace without --force

- src/scope/models/model-component.ts
Currently, in this case it shows an obscure error: `TypeError: Cannot read properties of null (reading 'refsWithOptions')`. 
With this PR, it shows the standard VersionNotFound error, which outlines the component name and the missing snap.
> fix(export): provide a clear error when local snaps are missing

- scopes/compilation/bundler/dev-server.service.tsx
- scopes/webpack/webpack/webpack.dev-server.ts
- scopes/webpack/webpack/webpack.main.runtime.ts
- pass a resolved path of `webpack-dev-server` instead of its instance to `WebpackDevServer` class
- resolve `webpack-dev-server` version from its package.json
> resolve webpack-dev-server version for bit envs get <component>

- e2e/harmony/lanes/switch-lanes.e2e.ts
- scopes/component/checkout/checkout.main.runtime.ts
- scopes/component/status/status-cmd.ts
- scopes/component/status/status.main.runtime.ts
- scopes/scope/importer/import-components.ts
- scopes/workspace/workspace/bit-map.ts
- scopes/workspace/workspace/workspace.ts
- src/consumer/bit-map/bit-map.ts
A popular use-case when this is needed is when creating new components on a lane then this lane was merged by someone else or by the cloud to main. Now, when switching to main, all these components are unavailable.
This PR handle it in two places:
1. `bit status` shows a new section of such components.
2. `bit checkout head` makes them available.
> feat: allow making components to be available on main

- scopes/component/snapping/snap-cmd.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/tag-cmd.ts
Also, suppress the warning about adding message when `--editor` is used.
> feat(snap): introdue --editor flag, similar to what bit-tag has

- scopes/component/isolator/isolator.main.runtime.ts
- scopes/dependencies/dependency-resolver/dependency-installer.ts
- scopes/dependencies/dependency-resolver/manifest/update-dependency-version.ts
- scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts
> fix: only resolve dependency versions from dependencies (not policies) when installing in capsules

- e2e/harmony/lanes/lane-from-lane.e2e.ts
- e2e/harmony/lanes/switch-lanes.e2e.ts
- scopes/lanes/lanes/create-lane.ts
- scopes/lanes/lanes/switch-lanes.ts
- scopes/workspace/workspace/workspace.ts
This fixes a bug found in the following scenario:
A component has a different scope than the lane. It was snapped on main, as a result, the `head` prop of the Component model has changed locally. Later, the lane was switched to a local lane, running `bit export` threw the following error:
> unexpected network error has occurred.
> server responded with: "scope "teambit.webpack". error: head snap a4197234768854dea33ff782e4de7196b4d0d496 was not found for a component learnbit-react.module-federation/apps/remote-app"
> 
It happened because the remote-scope of the lane got the component object with a head that only exists locally.
It's not easy to fix this issue and it could happen only when switching from main to another lane. not from one lane to another. so for now, we just block it. …
> fix(lane-switch): block switching a lane when on main and there are staging components

- .bitmap
- e2e/harmony/lanes/diverged-from-remote-lane.e2e.ts
- src/scope/component-ops/get-diverge-data.ts
In case a local snap was found in other lane in the same remote but not in the remote-lane, then, continue traversing to check whether the component is diverged or not. Previously, in this case we would stop and assume the local is ahead.
> fix(divege-data): keep traversing if found on other lanes in the same remote

- scopes/component/snapping/tag-model-component.ts
- scopes/scope/export/export.main.runtime.ts
- src/scope/repositories/sources.ts
- src/scope/scope.ts
- src/scope/staged-snaps.ts
Currently, to get this info whether or not a version is local, we have to run the expensive `getDivergeData` call.
Not only this is not good for performance reasons, but this is also throw errors in some cases when the version we search for is coming from another lane, not the currently checked out one. 
Also, in these cases, it's unable to determine whether it's local, because the `setDivergeData` only checks the currently checked out lane against the remote.
> improvement: cache staged-snaps hashes to avoid fetching them from a remote

- scopes/lanes/lanes/lanes.graphql.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/lanes/lanes/lanes.ui.runtime.tsx
- scopes/lanes/ui/compare/lane-compare-hooks/use-lane-diff-status/use-lane-diff-status.ts
- scopes/lanes/ui/compare/lane-compare-page/lane-compare-page.module.scss
- scopes/lanes/ui/compare/lane-compare-page/lane-compare-page.tsx
- scopes/lanes/ui/compare/lane-compare/lane-compare.module.scss
- scopes/lanes/ui/compare/lane-compare/lane-compare.tsx
- scopes/lanes/ui/inputs/lane-selector/lane-grouped-menu-item.tsx
- scopes/lanes/ui/inputs/lane-selector/lane-menu-item.tsx
- scopes/lanes/ui/inputs/lane-selector/lane-selector.module.scss
- scopes/lanes/ui/inputs/lane-selector/lane-selector.tsx
- scopes/lanes/ui/navigation/lane-switcher/lane-switcher.module.scss
- src/logger/pino-logger.ts
- Add `Compare` tab to the Lane Page
- Allows comparing a lane with another lane
- default to main for non main lanes, and the first non main lane for main
- hidden if the scope has only (1) lane
- Fix `diffStatus` API on `lanes.main.runtime`. 
- Allow diffing when source lane is `main`
- When comparing two lanes, diff the `sourceHead` with the last `commonSnap` instead of head on `target`
- Add `snapDistance` to `LaneComponentDiffStatus` result
- query common snaps, sourceOnly or targetOnly snaps between components in `source` and `target` lane
https://user-images.githubusercontent.com/8999604/217300164-1019dd2f-b4ac-4085-b3bc-f6318ac7805d.mov
> Lanes: Lane Compare + SnapsDistance GQL API

- .circleci/config.yml
- scopes/component/isolator/isolator.main.runtime.ts
- scopes/harmony/bit/load-bit.ts
- scopes/harmony/testing/load-aspect/load-aspect.ts
- scopes/pkg/pkg/pkg.main.runtime.ts
- scopes/typescript/ts-server/process-based-tsserver.ts
- scopes/workspace/modules/node-modules-linker/index.ts
- scopes/workspace/modules/node-modules-linker/node-modules-linker.ts
- scopes/workspace/modules/node-modules-linker/package-json-transformer.ts
Currently in some cases it throws ComponentNotFound.
Also, refactor the package-json-transformer to work with the Component and not with the legacy ConsumerComponent.
> fix pkg-json generation during tag

- e2e/harmony/scope-cmd.e2e.ts
- scopes/component/renaming/exceptions/old-scope-exported.ts
- scopes/component/renaming/exceptions/old-scope-not-found.ts
- scopes/component/renaming/exceptions/old-scope-tagged.ts
- scopes/component/renaming/renaming.main.runtime.ts
- scopes/component/renaming/scope-rename-owner.cmd.ts
- src/e2e-helper/e2e-bit-jsonc-helper.ts
- src/e2e-helper/e2e-command-helper.ts
To only rename the owner part of the scope. (helpful when multiple different scopes need to be aligned with a new owner-name)
> feat: introduce a new command "bit scope rename-owner"

- e2e/harmony/publish.e2e.4.ts
- scopes/pkg/aspect-docs/pkg/pkg.mdx
- scopes/pkg/pkg/pkg.main.runtime.ts
- scopes/pkg/pkg/publisher.ts
Currently, if the `packageJson.name` prop is set in the pkg aspect, the tag pipeline publishes the component to npm. There are cases, when the custom-name is needed without publishing, e.g. when a component is a VSCode extension. For these scenarios, a new config-prop is introduced `avoidPublishToNPM` to stop publishing.
> feat(pkg): allow custom-package-name without publishing to NPM

- e2e/harmony/sign.e2e.ts
- scopes/scope/sign/sign.main.runtime.ts
currently, it's always running the tag-pipeline, which it should not.
> fix(sign): run snap-pipeline when signing snaps

- e2e/harmony/snap-from-scope.e2e.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/scope/export/export.main.runtime.ts
No need for the history. The usage of this command is for creating a new lane from main (not forking) and snapping on that new lane. The history, if needed, can be obtained by FetchMissingHistory action.
> fix(snap-from-scope): export only the current snap, ignore the history

- e2e/harmony/lanes/lanes.e2e.ts
- src/scope/models/model-component.ts
In some scenarios, `bit export` throws an error:
```
error: version "a683008508bf68c6cd48d0c26253e32c11fd9589" of component X was not found on the filesystem.
```
This fixes it by not attempting to export snaps that are already exist in the original scope.
(regression caused by https://github.com/teambit/bit/pull/6992 ).
> fix(export): do not try to export snaps existing on main

- e2e/harmony/install-angular.e2e.ts
- e2e/harmony/install.e2e.ts
- e2e/harmony/merge-config.e2e.ts
- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/workspace/workspace/aspects-merger.ts
- scopes/workspace/workspace/workspace.provider.ts
- scopes/workspace/workspace/workspace.ts
- src/e2e-helper/e2e-command-helper.ts
Currently, if data are retrieved from merge-config (when merging lanes), the config is saved as an array in order to support the `force` field.
In this PR, the `force: false` goes to the dependencies.data so then the config can be an object as it was before.
This fixes issues with `bit envs` commands that were running after the data was saved in the model as an array.
> fix, change deps-resolver config policy to be saved as an object. always

- scopes/dependencies/pnpm/lynx.ts
- scopes/dependencies/pnpm/pnpm.package-manager.ts
> fix: use the default store and cache locations for pnpm

- e2e/harmony/dependencies-cmd.e2e.ts
- scopes/dependencies/dependencies/dependencies-cmd.ts
- scopes/dependencies/dependencies/dependencies.main.runtime.ts
- src/e2e-helper/e2e-command-helper.ts
To unset only deps that were set by `bit deps set`. 
Dependencies that were auto-detected won't be affected.
> feat(deps-unset): introduce a new sub-command "bit deps unset"

- scopes/component/merging/config-merger.ts
- scopes/component/merging/merging.main.runtime.ts
Otherwise, along the line, it runs some hooks that calls scope.get(), which runs loadAspects, which imports aspects if they are missing. This could easily import the same missing aspect multiple time in parallel and throw timeout errors and corrupt the objects.
> fix(lane-merge): avoid loading multiple components in parallel

- e2e/harmony/dependencies/env-jsonc-policies.e2e.ts
- scopes/generator/generator/new.cmd.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/lanes/lanes/lanes.spec.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- src/scope/lanes/lanes.ts
- src/scope/objects/repository.ts
This PR changes `bit lane remove` to be a soft-remove. It moves the object in the a `trash` directory in the scope, so it's possible to restore it later.
> feat(lane-remove): support restoring lanes after deletion

- e2e/harmony/custom-env.e2e.ts
- e2e/harmony/dependencies/env-jsonc-policies.e2e.ts
- scopes/workspace/workspace/workspace.ts
currently, in this case it adds the env from the current workspace with a version and a minus, causing to fallback to default env (node).
> fix(env-set): set workspace-env correctly after multiple bit-env-set

- scopes/scope/sign/sign.main.runtime.ts
It's not needed for `--multiple`, only when the sign is done on the same scope of the components.
> fix(sign), avoid running clear-cache when --multiple is used

- scopes/scope/importer/import-components.ts
- scopes/scope/importer/importer.main.runtime.ts
Currently, the import during install only fetches from main. This PR fetches from a lane if checked out to a lane.
> fix(install): import objects according to the current lane/main

- scopes/component/merging/merging.main.runtime.ts
currently, when running `bit lane merge --theirs` it changes the version in the .bitmap file according to the other lane. This PR fixes it to keep the version and only change the files.
> fix(merge): avoid changing .bitmap version when using --theirs strategy

- src/scope/exceptions/server-is-busy.ts
Otherwise, the components won't be indexed by bit.cloud.
> fix, change the ServerIsBusy error message to not suggest using export --persist

- e2e/harmony/deduplication.e2e.ts
- e2e/harmony/import-harmony.e2e.ts
- e2e/harmony/imported-component-deps.e2e.ts
- e2e/harmony/install.e2e.ts
- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/dependencies/dependency-resolver/package-manager.ts
- scopes/dependencies/pnpm/lynx.ts
- scopes/dependencies/pnpm/pnpm.package-manager.ts
- scopes/dependencies/yarn/yarn.package-manager.ts
- scopes/workspace/install/install.cmd.tsx
- scopes/workspace/install/install.main.runtime.ts
- `bit install --update` updates all dependencies (direct and indirect). Existing semver ranges are respected.
- Newly installed dependency are saved in `workspace.jsonc` with the `^` prefix by default.
> feat: install --update

- scopes/harmony/aspect-loader/plugins.ts
- This prevents harmony from throwing an error when trying to `harmony.get(pluginComponentId)`
- This will fix an issue with forking a component that uses the new env format (env plugin with *.bit-env.* file)
> fix(aspects): return an empty object from a plugin auto generated provider

- scopes/lanes/lanes/lanes.main.runtime.ts
No need to filter those as they were filtered already in the remote.
Also, if the model-component exists locally but not the version on the lane, it throws ComponentNotFound error.
> fix(lane-list), avoid checking for soft-remove when using --remote

- scopes/workspace/workspace/aspects-merger.ts
otherwise, it gets a priority over workspace.jsonc and almost everything else unexpectedly.
> fix, avoid adding deps from scope into merge-config

- src/scope/component-ops/scope-components-importer.ts
- src/scope/models/version-history.ts
Instead of loading all versions objects, load only the VersionHistory, get the graph from head, then only check whether the objects exist in the filesystem.
> perf, improve FetchMissingHistory performance and memory consumption

- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- src/scope/component-ops/scope-components-importer.ts
otherwise, in some case, it needs the artifacts later on in the merge process where it doesn't have the lane object at hand and then throw an error about missing objects.
> fix(lane-merge), import missing artifacts before starting the merge process

- e2e/harmony/install-angular.e2e.ts
With the newly released one, the e2e-test fails with `template "ng-workspace" was not found` error.
> test, skip an angular test for now

- e2e/harmony/lanes/lanes.e2e.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- scopes/scope/export/export.main.runtime.ts
- scopes/scope/importer/importer.main.runtime.ts
- src/e2e-helper/e2e-command-helper.ts
- src/scope/models/model-component.ts
Currently, when merging lanes from a bare-scope, it doesn't import the artifacts. As a result, when it pushes the components after the merge to main or to another lane, the artifacts are missing from that scope. 
It wasn't throwing an error during the export about missing artifacts because it assumed they're all external and exist in the scope.
This PR imports the missing artifacts and also throw an error during the export if they're missing.
> fix(merge-from-scope), push artifacts to original scopes

- scopes/semantics/entities/semantic-schema/api-schema.ts
- scopes/semantics/entities/semantic-schema/schemas/docs/tag.ts
- scopes/semantics/schema/mock/button-schemas.json
This is in preparation to render a subset of the component schema in the preview. 
- `taggedModuleExports` contains list of all explicitly tagged exports using jsdocs `@exports` tag
> feat(Schema): allow querying explicitly tagged exports

- e2e/commands/remove.e2e.1.ts
- scopes/component/remove/remove.main.runtime.ts
- src/consumer/component-ops/component-status-loader.ts
- src/e2e-helper/e2e-command-helper.ts
- when a lane is new (not exported yet), don't allow soft-remove. suggest to "bit remove" instead. we already do the same when components are new.
- fix obscure error `"Cannot read properties of undefined (reading 'id')` when importing locally soft-removed component.
> fix, handle soft-remove on a new lane and import soft-removed components

- e2e/harmony/lanes/bit-import-on-lanes.e2e.ts
- src/scope/models/model-component.ts
currently, if the remote-lane doesn't exist, or it doesn't have this specific component, it falls back to the either the forked-lane or to the `component.head`. For bit-status or bit-checkout-head this is incorrect. The comparison needs to be against the remote-lane, and if it doesn't exist there, it should assume that the local is ahead.
(this regression caused by https://github.com/teambit/bit/pull/7036. but this time, instead of changing the divergeData, we treat bit-status/checkout differently)
> fix(status): avoid showing components as pending-update when their remote-lane is empty

- e2e/harmony/lanes/lanes.e2e.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- block `bit lane change-scope` when the lane is not new, because then, whole history of the current lane needs to be exported, otherwise, on the next export, the remote will throw about missing objects. It's much easier to just create a new lane with the new scope-name.
- in case the scope-name is invalid, throw an error about it. Currently, it lets you use an invalid scope-name and saves it in the lane-object incorrectly.
> fix(lane-change-scope), block when lane is exported, throw when scope-name is invalid

- scopes/component/component/component.ui.runtime.tsx
- scopes/dependencies/pnpm/pnpm.ui.runtime.tsx
- scopes/dependencies/yarn/yarn.ui.runtime.tsx
- scopes/pkg/pkg/pkg.ui.runtime.tsx
- fix displaying the package version for snaps on main
https://user-images.githubusercontent.com/8999604/224407868-55992b6b-a4c2-44fc-b0c3-862985410ed9.mov
> fix(ComponentUI): Package version for snaps on main

- scopes/react/react/apps/web/webpack/webpack.app.ssr.config.ts
- scopes/react/react/webpack/webpack.config.base.ts
- scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
- scopes/ui-foundation/ui/webpack/webpack.ssr.config.ts
- scopes/webpack/webpack/config/webpack.dev.config.ts
Change sourcemaps to better quality
> chore(webpack): better development sourcemaps

- scopes/workspace/workspace/aspects-merger.ts
this fixes the multiple-envs warning in some scenarios.
> fix(status), avoid loading envs that are not set via envs/envs if found an env previously

- package.json
- src/utils/fs-write-file.ts
This will help with the error users get about corrupted objects in case the process interrupted during the import. 
With this PR the objects are written to a tmp file first, and once done successfully, they’re renamed.
> fix, write objects atomically

- e2e/harmony/lanes/lanes.e2e.ts
- scopes/scope/importer/import-components.ts
currently, when checked out to a lane, `bit import` fetches main components from main and lane components according to the versions in the lane. 
In some scenarios, the .bitmap can be out-of-sync and a version in .bitmap is different than a version in the lane object. Or maybe `bit checkout` was running to a different version. In such cases, if the local scope is deleted, bit was throwing `ComponentsPendingImport` error. 
This PR fixes the import process to fetch these versions as well.
> fix(import): fetch versions that are shown in .bitmap but not in the lane object

- scopes/component/component/component-factory.ts
- scopes/workspace/workspace/workspace-aspects-loader.ts
- scopes/workspace/workspace/workspace.ts
This fixes an issue when an env without a version is set in the generator like this:
```
"teambit.generator/generator": {
"envs": [
"teambit.web-components/stencil"
]
}
```
It wasn't able to correctly load the env to get the templates
- allow pass options to load aspects
- temporarily set useScopeAspectsCapsule in load aspects to true
> fix(templates) - load envs' templates correctly from ws.jsonc

- scopes/workspace/workspace/workspace-aspects-loader.ts
- when loading a list of aspects and the list contains envs of other aspects of the list, make sure to first load the envs into harmony before loading the rest of the aspects.
> Make sure to load envs first when loading a list of aspects

- scopes/compilation/compiler/workspace-compiler.ts
from the ConsumerComponent instance.
Although it should not happen. It did happened due to a different bug. Regardless, no need to check for this rootDir anymore, because on Harmony all components have rootDir.
> fix(compile): avoid ignoring components that their ComponentMap is missing 

- scopes/compilation/compiler/workspace-compiler.ts
- scopes/workspace/workspace/workspace.ts
This is a regression caused by https://github.com/teambit/bit/pull/7183. 
When a component is coming from the scope (happens when loadAspects from scope fails, which is register to `onAspectLoadErrorSlot`), don't try to compile it, otherwise, it throws ComponentNotFound.
> fix, avoid compiling scope components

- e2e/harmony/lanes/merge-lanes.e2e.ts
- src/scope/repositories/sources.ts
The use-case this PR fixes is when merging one lane to another and during this merge a new component is introduced to this lane, after export, the remote-lane wasn't saving this newly introduced component.
> fix(export): save newly introduced components on a lane from previous merge

- scopes/toolbox/fs/hard-link-directory/hard-link-directory.spec.ts
- scopes/toolbox/fs/hard-link-directory/hard-link-directory.ts
> fix: skip broken symlinks when copying components to .bit_roots

- e2e/harmony/lanes/merge-lanes.e2e.ts
- e2e/harmony/sign.e2e.ts
- scopes/component/snapping/index.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/tag-model-component.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- scopes/scope/sign/sign.main.runtime.ts
- src/scope/models/version.ts
- src/scope/objects-fetcher/objects-writable-stream.ts
In some cases, the `Version` object is mutated. For example when merging with squash or when building on CI. 
Currently, the object-writer is not aware of that and treat this object as immutable. As a result, it's possible that locally a `Version` object has changed and has the `squashed` prop and `parents` modified, but an import process that fetched this Version as a dependency of another component, overrode it. 
This PR fixes it by adding a new `modified` property to the `Version` object and it allows overriding only in case the incoming object is newer.
> fix, avoid overriding mutated Version objects

- scopes/defender/eslint/eslint-config-writer.ts
- scopes/defender/prettier/prettier-config-writer.ts
- scopes/typescript/typescript/ts-config-writer.ts
- scopes/workspace/workspace-config-files/config-writer-entry.ts
- scopes/workspace/workspace-config-files/dedup-paths.spec.ts
- scopes/workspace/workspace-config-files/format-outputs.ts
- scopes/workspace/workspace-config-files/index.ts
- scopes/workspace/workspace-config-files/workspace-config-files.main.runtime.ts
- Add new API for extending config files to replace extending file name with its abs/relative path
- Use relative paths in extending files for ts-config-writer, eslint-config-writer, and prettier-config-writer
- Add more context to the `generateExtendingFile` function
> improvement(ws-config) - Add new API for extending config files to replace extending file name with its abs/relative path

- e2e/harmony/out-of-sync-components-harmony.e2e.ts
- scopes/scope/importer/import-components.ts
- scopes/scope/importer/import.cmd.ts
This is an out-of-sync case which apparently we didn't handle.
It happens when a component is exported. One user tagged the exported component locally, committed and pushed, another user clones the repo, gets the .bitmap with the versions according to the tagged one, which only exist on the first-user local but not on the remote.
Until now, in this case, `bit status` was showing the import-pending message, suggesting to import, but `bit import` was throwing `ComponentNotFound` error.
This PR fixes the import to not throw. Instead, in the output it shows the not-found components and suggests running `bit status` to sync the .bitmap back to the remote.
> fix(import), avoid throwing ComponentNotFound when .bitmap component was not found

- src/utils/fs-write-file.ts
Writing object files is 16 times faster with this change. See https://github.com/npm/write-file-atomic/issues/155 for more info.
> perf, fix writing files performance by disabling fsync

- scopes/defender/eslint/eslint-config-writer.ts
- scopes/typescript/typescript/expand-include-exclude.ts
- scopes/typescript/typescript/index.ts
- scopes/typescript/typescript/ts-config-writer.ts
- scopes/workspace/workspace-config-files/workspace-config-files.main.runtime.ts
- add include to the generated global types folder from the generated tsconfig files
- add `node_modules/@types` to the `typeRoots` in the generated root tsconfig file
- reference relative config files with `./` at the beginning (some tools like TS don't know to use relative path correctly when not start with `.` or `..`)
> fix(ws-config) - various fixes for ws-config write generated config files

- e2e/harmony/dependencies/policies-order.e2e.ts
- scopes/workspace/install/install.main.runtime.ts
This fix reduces the number of repeat installs
> fix: clear workspace cache before calculating component manifests

- src/consumer/component/dependencies/files-dependency-builder/detectives/detective-css/index.ts
- src/consumer/component/dependencies/files-dependency-builder/detectives/detective-es6/index.ts
- src/consumer/component/dependencies/files-dependency-builder/detectives/detective-less/index.ts
- src/consumer/component/dependencies/files-dependency-builder/detectives/detective-sass/index.ts
- src/consumer/component/dependencies/files-dependency-builder/detectives/detective-scss/index.ts
- src/consumer/component/dependencies/files-dependency-builder/detectives/detective-typescript/index.ts
Reverted files to make sure those packages below could be properly imported.
- `@teambit/legacy/dist/consumer/component/dependencies/files-dependency-builder/detectives/detective-es6`
- `@teambit/legacy/dist/consumer/component/dependencies/files-dependency-builder/detectives/detective-typescript`
- `@teambit/legacy/dist/consumer/component/dependencies/files-dependency-builder/detectives/detective-css`
- `@teambit/legacy/dist/consumer/component/dependencies/files-dependency-builder/detectives/detective-sass`
- `@teambit/legacy/dist/consumer/component/dependencies/files-dependency-builder/detectives/detective-scss`
- `@teambit/legacy/dist/consumer/component/dependencies/files-dependency-builder/detectives/detective-less`
Since I have no existing test cases. I just _manually and locally_ …
> revert legacy detective entries

- e2e/harmony/lanes/merge-lanes.e2e.ts
A similar case threw ComponentNotFound on `bit export`, which I'm unable to reproduce. This test case is important regardless, so I leave it.
> test, add an e2e-test for multi-scopes and a new lane forked from another lane

- scopes/typescript/typescript/typescript.compiler.ts
- src/utils/bit/component-placeholders.ts
- fix the `main` prop of package.json to be empty. currently it's `dist/<file-name>.d.js` (which doesn't exist, as d.ts files are not compiled into d.js, they're just copied).
- fix the `types` prop during build to not get deleted.
> feat, better handling of types components

- e2e/harmony/scope-cmd.e2e.ts
- scopes/component/renaming/renaming.main.runtime.ts
- scopes/workspace/modules/node-modules-linker/node-modules-linker.ts
- scopes/workspace/workspace/workspace.ts
Remove old links to node_modules once `bit scope rename` renamed the components. Then, re-link and compile.
Same for `bit scope rename-owner`.
> improvement(scope-rename), remove old links, create new links and compile

- src/consumer/component/sources/artifact-files.ts
- src/scope/scope.ts
When isolating non-modified components into capsules, the dists are written from the artifacts saved in the scope.
If checked out to a lane, sometimes we don't know whether the requested id is on the lane and therefore the artifacts should be fetched from the lane-scope or it's on main and the import should go to the original scope. 
To determine this better we fetch delta from both main and lane so then we could traverse the history and find out whether it's on main or lane.
Thing is that in most cases, this import is not needed and we're able to easily determine whether a component is on a lane, especially because we have the VersionHistory object.
This PR skips the import, and in case we're unable to determine the origin due to missing Version object, it tries to find the dists on …
> fix(snap), avoid importing-delta when isolating non-modified comps

- e2e/harmony/load-extensions.e2e.4.ts
- scopes/component/component/component-factory.ts
- scopes/component/component/index.ts
- scopes/component/isolator/isolator.main.runtime.ts
- scopes/dependencies/pnpm/pnpm.package-manager.ts
- scopes/envs/envs/environments.main.runtime.ts
- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
- scopes/harmony/aspect-loader/constants.ts
- scopes/harmony/cli/cli.main.runtime.ts
- scopes/scope/scope/scope-aspects-loader.ts
- scopes/workspace/install/install.cmd.tsx
- scopes/workspace/install/install.main.runtime.ts
- scopes/workspace/workspace/aspects-merger.ts
- scopes/workspace/workspace/workspace-aspects-loader.ts
- scopes/workspace/workspace/workspace.provider.ts
- scopes/workspace/workspace/workspace.ts
- improve aspects loading errors
- getting workspace name for different scope aspects funcs
- remove pnpm output divider
- remove your workspace is ready to use from the install output
- change ensured capsule success message
- improve LoadAspectsOptions type and expose it
- add currentCommand name to cli onStartFn
- add "addFailedToLoadExtension" API to envs aspect
- add break line to output
- add "inInstallContext" to workspace aspect
> load aspects error handling

- e2e/harmony/custom-env.e2e.ts
- scopes/workspace/workspace/aspects-merger.ts
- scopes/workspace/workspace/workspace.ts
currently, when changing the env from one local env to another non-core env, the local env wasn't removed because of a mismatch between the legacy-id and component-id.
This PR adds ComponentID to the aspects during the extensions calculation so it's possible to use it for the comparison.
> fix(status): avoid showing multiple-env error when the env was not exported yet

- scopes/workspace/workspace/workspace.ts
See https://github.com/teambit/bit/pull/7296.
After investigating the issue, the reason for the ComponentNotFound in that case is due to another bug.
A component from laneX was depend on another component from laneY, which is invalid. (this [PR](https://github.com/teambit/bit/pull/7275) started the work to block it.) When it was set to fetch all deps, this dep was successfully fetched during importAndGetAspects because these two lanes belong to the same scope. 
However, when it was set to not fetch deps, this dependency was missing during the build-graph of load-aspect, which doesn't go automatically to the scope-lane but checks whether a component is belong to a lane. In this case, the dep wasn't part of the lane, and as such, it tried to fetch it from main and failed.
> revert #7296 change

- src/scope/models/version.ts
Before v0.1.27,  tagging with `-m ""` resulted in `log.message` being boolean instead of a string. It was fixed in #7278, but older objects may have the wrong type already. This PR fixes the type during `Version.parse`.
> fix(import): fix error of log.message being boolean upon import

- scopes/workspace/workspace/workspace.ts
This is useful in case the env used by the workspace components was installed as a package and is now imported. 
With this PR, `bit envs updates` updates the component to use the env from the workspace by removing the version.
> improvement(envs-update): in case workspace-envs have versions, remove the versions

- package.json
- src/api/consumer/lib/doctor.ts
- src/cache/in-memory-cache.ts
- src/cli/commands/public-cmds/doctor-cmd.ts
For now, it includes the local scope, but ignores the node-modules. Later we'll have this configurable.
> feat(doctor): introduce "--archive" to archive the workspace as well

- scopes/workspace/install/install.main.runtime.ts
> fix: don't run install again if a dependency changes its type

- src/scope/objects-fetcher/objects-writable-stream.ts
Currently set to 5 minutes. If the remote doesn't complete the stream, show a warning in the console about it.
> improvement(import), show a warning for very slow remotes

- scopes/lanes/lanes/lanes.main.runtime.ts
> fix(start), imporove CopmonentNotFound error when a component is missing on a lane

- .bitmap
- scopes/component/component-log/component-log.main.runtime.ts
- scopes/component/component-log/log-cmd.ts
- scopes/component/snapping/snap-cmd.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/harmony/cli/cli-parser.ts
- scopes/harmony/cli/cli.cmd.ts
- scopes/harmony/cli/cli.main.runtime.ts
- scopes/scope/importer/import.cmd.ts
- scopes/scope/importer/importer.main.runtime.ts
- scopes/workspace/clear-cache/clear-cache-cmd.ts
- scopes/workspace/clear-cache/clear-cache.main.runtime.ts
- scopes/workspace/install/install.main.runtime.ts
- scopes/workspace/install/link/link.cmd.ts
They are not needed since the `helpUrl` was introduced a while ago.
> refactor: remove old dependencies to community aspects

- scopes/workspace/workspace/aspects-merger.ts
- scopes/workspace/workspace/workspace.ts
Previously, in the workspace this was tested on and on the ids matching the criteria, `workspace.resolveComponentId` took 41ms in average. After this optimization it took 0.2ms.
> perf, improve resolveComponentId performance when BitID is passed with a scope-name

- src/scope/component-ops/scope-components-importer.ts
- src/scope/objects-fetcher/objects-fetcher.ts
- src/scope/objects-fetcher/objects-writable-stream.ts
- src/scope/objects-fetcher/write-objects-queue.ts
- currently, when fetching objects, the client hold them all in memory and write at once. This PR changes it to work the same way as fetching components, which utilizes the stream mechanism.
- as a result of the above, it's now able to show whether a scope is too slow.
- decreased the timeout limit of this warning from 5 minutes to 3.
- change the spinner message during fetch to only show the "downloaded" not the "completed" because the completion is not relevant, it happens pretty fast.
> improvement(fetch), change object-fetch to use writable stream

- scopes/component/merging/config-merger.ts
- scopes/component/merging/merging.main.runtime.ts
- Currently, `semver.satisfies` was checked only when the current-policy and other-policy were a range, which never happened, because saving the policy upon tag wasn't implemented yet. This PR removes this condition and always check whether it satisfies, and if it is, it won't be shown as a conflict.
- Fixes a bug where other-lane had the same version as workspace.jsonc, but different version than current-component. It was showing the same version from current/other as a conflict.
> fix(lane-merge), avoid showing workspace conflicts when it Semver satisfied

- e2e/harmony/out-of-sync-components-harmony.e2e.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- src/consumer/bit-map/bit-map.ts
- src/consumer/consumer.ts
Currently, in this case, the .bitmap still has the lane-id but the scope doesn't have the lane object, so the user might be under impression that the workspace is checked out to a lane. Snap command doesn't throw and is snapped on main. Once the user is trying to export, an error is thrown about missing lane object.
This PR re-create the lane in this case. since the .bitmap has the full lane-id, the data to recreate the lane exists and it's possible to do.
> fix(out-of-sync): recreate a lane if local scope got deleted and is new

- scopes/pipelines/builder/artifact/artifact-extractor.ts
- scopes/scope/scope/scope.main.runtime.ts
In some cases, the first run of `bit artifact` after `bit tag` was throwing an error of ComponentNotFound. 
This PR uses `scope.getMany` instead of `scope.loadMany` because there is no need to load all aspects. This change also improves this command performance dramatically.
> fix(artifacts), fix missing component error after tag

- e2e/harmony/lanes/lanes.e2e.ts
- scopes/component/checkout/checkout.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
- src/consumer/consumer.ts
Currently, this is working only when `bit import` was running first, which updates the local lane object with the remote.
Otherwise, it wouldn't bring the new components because the local lane doesn't have them.
> fix(checkout), fetch current lane object first to find new comps

- scopes/harmony/aspect/aspect.env.ts
Exclude `ui-bundle` artifact folder in `.npmignore` for `@teambit/ui` 
```
dist/tsconfig.tsbuildinfo
/*.ts
artifacts/
```
```
dist/tsconfig.tsbuildinfo
/*.ts
artifacts/
!artifacts/ui-bundle
```
> fix: exclude `ui-bundle` folder from `.npmignore` for core aspect

- src/pack/packer.ts
Currently, in case of failure it shows:
```
failed running npm pack at /Users/davidfirst/Library/Caches/Bit/capsules/c8faea78513ab52bfd30032f9fa81289c5628e6c/my-scope_bar@0.0.1
undefined
```
This PR fixes it to show the original error-message and log the error instance.
> fix(tag/snap): show the error message when "npm pack" fails

- scopes/dependencies/dependency-resolver/dependency-installer.ts
- scopes/dependencies/dependency-resolver/package-manager.ts
- scopes/dependencies/pnpm/lynx.ts
- scopes/dependencies/pnpm/pnpm-prune-modules.ts
- scopes/dependencies/pnpm/pnpm.package-manager.ts
- scopes/workspace/install/install.main.runtime.ts
Looks like the fix in https://github.com/teambit/bit/pull/7310 was not enough, we need to clean node_modules only after all installation iterations were complete.
-
-
-
> fix: clean node_modules only after all iteration of installation were completed

- e2e/harmony/custom-aspects.e2e.ts
- scopes/compilation/bundler/index.ts
- scopes/component/component/component-factory.ts
- scopes/dependencies/dependency-resolver/index.ts
- scopes/harmony/aspect-loader/aspect-definition.ts
- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
- scopes/harmony/cli/index.ts
- scopes/pipelines/builder/index.ts
- scopes/workspace/workspace/types.ts
- scopes/workspace/workspace/workspace-aspects-loader.ts
- scopes/workspace/workspace/workspace.provider.ts
- do not auto-load aspects' dependencies that are not configured in the workspace.jsonc
- add a new flag to use the old behavior of auto load aspects' deps
```
/**
* If set to `true`, bit will try to load aspects dependencies automatically.
* even if the aspects dependencies are not configured in the workspace.jsonc root config.
* for example having the aspect
* main aspect
* export class MainAspectMain {
*  ...
*   static dependencies = [MyDepAspect];
* }
* and the in the workspace.jsonc file:
* {
*  ...
*   main-aspect: {}
* }
* when set to true, bit will try to load MyDepAspect automatically.
*/
autoLoadAspectsDeps?: boolean;
```
> change(aspects) - do not auto-load aspects' dependencies that are not configured in the workspace.jsonc

- e2e/harmony/lanes/lanes.e2e.ts
- src/scope/models/model-component.ts
when their scope is not the same.
> fix(lane-fork), push all snaps from the original lane to the forked lane scope

- scopes/react/react/react.env.ts
- scopes/react/react/react.main.runtime.ts
- scopes/webpack/webpack/webpack.main.runtime.ts
- allow for a custom env to override `webpack` and `webpack-dev-server` instances by providing alternative paths to load these modules.
- react UseWebpackModifiers now gets to new options: `webpackModulePath` and `webpackDevServerModulePath`
```ts
export type UseWebpackModifiers = {
previewConfig?: WebpackConfigTransformer[];
devServerConfig?: WebpackConfigTransformer[];
webpackModulePath?: string;
webpackDevServerModulePath?: string;
};
```
- react getDevServer API now accept the `webpackModulePath` and `webpackDevServerModulePath`
- react getBundler API now accept the `webpackModulePath`
- webpack createDevServer API now accept the `webpackModulePath` and `webpackDevServerModulePath`
- webpack createBundler API now accept the either a path to webpack (new) or webpack instance (existing)
> feature(react-env) - allow overriding webpack and webpack-dev-server for react env

- src/scope/lanes/remote-lanes.ts
Currently, once a ref file (.bit/refs/...) is loaded, it kept in memory until the process exits, and then when the refs are written, it is re-written even if it wasn't changed. For long processes, such as bit start, this can be an issue as it may write old values.
This PR fixes most of this issue by writing only the refs that were changed.
This approach replaces a previous PR from today: https://github.com/teambit/bit/pull/7386. 
A future PR will handle the cases when refs were changed by other commands, and in a long process, such as "bit start", one of them is changed as well and as a result, wrote some old data.
> fix, write only changed lane-refs

- scopes/component/component-writer/component-writer.main.runtime.ts
So then if the user hit Ctrl+C during the installation, the .bitmap will have the imported components records.
> fix(import), write .bitmap before starting the installation process

- scopes/component/status/status-cmd.ts
to not be confused with "staged components".
> improvement(status): change "snapped components" to "snapped components (tag pending)"

- scopes/scope/importer/import-components.ts
- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/workspace/build-graph-from-fs.ts
- scopes/workspace/workspace/workspace.ts
- src/consumer/component/components-list.ts
- src/scope/component-ops/scope-components-importer.ts
No need for an array of lanes because they all end up calling `getExternalMany` or `getExternalManyWithoutDeps` which don't support multiple lanes and throw if they get more than one.
> refactor(import), change import methods to work with one lane instead of an array

- scopes/dependencies/dependency-resolver/get-all-policy-pkgs.ts
Happens when `policy` param is undefined.
> fix(update): fix error "Cannot read properties of undefined (reading 'dependencies')" 

- scopes/preview/preview/preview.start-plugin.tsx
- scopes/ui-foundation/ui/start.cmd.tsx
- use the same pattern matching for components that we use in all other commands (build, test, ...) instead of the deprecated one that bit start was using
- refactor the command to move "type" (aka ui root name) to flags instead of arguments since it was required if you wanted to use a component pattern, and no one seems to even know what it is. The descriptions are also updated to make it more clear (although I still don't think anyone uses it, should we just remove it ?)
> fix bit start pattern

- scopes/webpack/config-mutator/config-mutator.ts
- workspace.jsonc
- Bump version for `@teambit/html.modules.inject-html-element` and use same types (The new version allows the use of `raw` property instead of using attributes and element tags)
> feat: add raw property to the HTML Injector

- scopes/ui-foundation/ui/ui.main.runtime.ts
This PR restores the `buidUiHash` that was removed as part of #7336 as this API was reported to being used by external users.
> API(ui aspect) - restore the public buildUiHash API

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/lanes/merge-lanes/merge-lane.cmd.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
Until now, only when merging to main it was squashing by default. This PR introduces a new flag `--squash` for when merging two lanes.
> feat(lane-merge), support squash when merging one lane to another

- src/scope/scope.ts
`idOnLane` method is used to check whether a version exists on the lane or on main. Until now, given the bitId, it was loading not only the Component object but also the Version object, and if not exits it was throwing ComponentNotFound.
It's definitely possible that the version in question doesn't exist locally. This PR fixes it to only load the Component object.
> fix, avoid loading the version object for idOnLane

- src/scope/objects-fetcher/objects-writable-stream.ts
Here is an example how the client can wait forever for a remote:
https://app.circleci.com/pipelines/github/teambit/bit/29462/workflows/e5534691-6533-4d43-bbf7-3c48decb86a8/jobs/276346
To avoid this, just exit the process if it takes more than X minutes. Currently set to 30.
> fix(fetch), throw if the remote does not complete in 30 minutes

- scopes/defender/tester/tester.main.runtime.ts
`getComponentDevPatterns` in TesterMain is not coherent with the same function from DocsMain & CompositionsMain, it is supposed to return `{name: string, pattern: string[]}`, but in TesterMain it sometimes will return `string[]` and sometimes `{name: string, pattern: string[]}`.
Also typescript incorrectly infers the return type to `string[]` (why it doesn't detect the issue? I don't know, it should have thrown a typecast error), which means that you would falsely believe that you would get the correct type until it doesn't...
> fix `getComponentDevPatterns` for `TesterMain`

- e2e/harmony/lanes/bit-checkout-on-lanes.e2e.ts
- scopes/component/checkout/checkout.main.runtime.ts
When on main, `bit checkout head` makes lane-components available on main. However, in some scenario it was needed to run `bit import` first. This PR fixes it to import during the checkout before determining the ids to checkout.
> fix(checkout), make components available on main without pre-bit-import

- scopes/workspace/workspace/workspace.main.runtime.ts
- scopes/workspace/workspace/workspace.provider.ts
- scopes/workspace/workspace/workspace.ts
- src/constants.ts
- new global config `default_resolve_envs_from_roots` to set the default value of resolveEnvsFromRoots
- to use it, run `bit config set default_resolve_envs_from_roots true` (or `false`)
> improvements(envs resolution) - add a global config to set default value for whether to resolve envs from root components

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/snapping/snapping.main.runtime.ts
Fixes an issue when snapping during merge-lane, the snap is using the cached components with the unmerged data.
> fix(lane-merge), clear component cache before tag/snap

- scopes/dependencies/dependency-resolver/dependency-installer.ts
- This fixes a case when an env has a component in its env.jsonc and this component also exist in that workspace. 
before this fix, this would have been added as packages to some of the sub manifest, in that case, sometimes this can lead to different instances of that component.
> fix(dependencies) - do not add dependencies from env to the manifest if they are also components in the workspace

- scopes/component/tracker/tracker.main.runtime.ts
currently, when running bit-new for templates using fork-components and the scope name has no owner (e.g. `my-org`), it throws an error:
> the entered scope has no owner nor the defaultScope in workspace.jsonc
It's related to an improvement added by https://github.com/teambit/bit/pull/5135. 
This PR just ignores this case and allow specifying such a scope-name.
> fix(new), allow specifying scope-without-owner in --scope flag

- pnpm-lock.yaml
- scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
- scopes/webpack/webpack/config/webpack.dev.config.ts
- workspace.jsonc
- update webpack version from 5.82.1 to 5.84.1
- this should fix warning on commands like bit start:
```
(node:56404) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
```
> chore(webpack) - update webpack version. update webpack config to remove deprecated configs

- scopes/component/new-component-helper/index.ts
- scopes/component/new-component-helper/new-component-helper.main.runtime.ts
- scopes/pkg/pkg/pkg.main.runtime.ts
- before this change, any aspect can decide if it should be copied during bit fork. 
with this change, it's hardcoded configured for the pkg aspect.
- this is required in order to support `bit config set default_resolve_envs_from_roots true` for bit new. otherwise, we are trying to load envs from the workspace before they are installed. so the entire bit new command is failing.
> improvement(fork) - explicitly don't copy pkg config when forking component

- .bitmap
- scopes/ui-foundation/uis/constants/z-indexes/index.ts
- scopes/ui-foundation/uis/constants/z-indexes/z-indexes.module.scss
Change the main file for the z-indexes component (`@teambit/ui-foundation.ui.constants.z-indexes`). From `z-indexes.module.scss` to `index.ts`
```bash
Cannot find module '<folder>/node_modules/@teambit/ui-foundation.ui.constants.z-indexes/dist/z-indexes.module.js'. 
Please verify that the package.json has a valid "main" entry
```
> change the main file for `@teambit/ui-foundation.ui.constants.z-indexes`

- scopes/dependencies/dependency-resolver/dependency-installer.ts
- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/dependencies/dependency-resolver/package-manager.ts
- scopes/dependencies/pnpm/lynx.ts
- scopes/dependencies/pnpm/pnpm.package-manager.ts
> feat: prefer offline install

- e2e/harmony/lanes/bit-remove-on-lanes.e2e.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/component/remove/remove.main.runtime.ts
- scopes/component/snapping/snap-cmd.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/tag-cmd.ts
- scopes/component/snapping/tag-model-component.ts
- scopes/scope/scope/scope.main.runtime.ts
- src/consumer/component/component-loader.ts
- src/consumer/component/components-list.ts
- src/consumer/component/consumer-component.ts
This way, lanes can get updates about components that should be removed.
When merging a lane into main - the soft-removed component are not merged.
> fix(lane-merge), merge soft-removed components when merging from one lane to another

- scopes/component/isolator/isolator.main.runtime.ts
- the signature of `getCapsulesRootDir` was changed in a previous commit, but it is a breaking change that will break angular projects. With a little bit of typescript magic, the old signature is deprecated but kept functioning instead.
> fix(isolator): remove breaking change in `getCapsulesRootDir`

- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
- scopes/scope/scope/scope-aspects-loader.ts
- when loading user aspects we used to filter them if they also local scope aspects (using the `file://` protocol). this filter was done based on checking the user aspect with the path to the local aspect.
This filter might result in wrong filters (for example when trying to load `teambit.node/node` we check if `node` exist in the path of the local aspect (which many times is true because we have `node_modules` in the path). this check is bad.
Now when filtering we are comparing the user aspects with the ids from the `.aspect` file of the local aspect.
> fix(aspects) - fix filtering the loading of user aspect when intersect with local scope aspects (file://)

- src/scope/component-ops/get-diverge-data.ts
For one component with 500 versions, it took 478ms with `R.difference` and just 1ms with `Lodash.differenceBy`. 
(this doesn't mean that Ramda is slower, probably Ramda has an equivalent method. it was just probably the wrong way to compare two huge arrays of objects without specifying the prop to compare).
> perf(get-snap-distance), huge performance improvement by switching R.difference with _.differenceBy

- e2e/harmony/import-harmony.e2e.ts
- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/component-writer/component-writer.main.runtime.ts
For example, an existing component has "foo" as the rootDir and now during the `bit lane merge`, another component has "foo/bar" as the rootDir. Instead of throwing an error, this PR changes the rootDir to be "foo_1/bar".
(until now, this path incremental was done only when the entire lane was imported and some components were parents of the others).
> fix(lane-merge), auto change root-dir in case it is collied with existing

- e2e/harmony/deprecate.e2e.1.ts
- scopes/scope/importer/import-components.ts
- scopes/scope/importer/import.cmd.ts
- src/api/consumer/lib/list-scope.ts
Exclude deprecated components when using a pattern in `bit import`.
> feat(import), introduce "--include-deprecated" flag and exclude them by default

- e2e/harmony/lanes/lanes.e2e.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- src/consumer/component-ops/component-status-loader.ts
- src/scope/component-ops/get-diverge-data.ts
In the following case the NoCommonSnap error blocks the user unnecessarily. 
lane-b forked from lane-a. 
lane-a continue snapping and then merged+squashed into main. 
On main the "squash" prop points to a newer version from lane-a, which doesn't exist on lane-b.
On lane-b, getDivergeData compares its head to main, not to lane-a because they're different scopes.
As a result, although it traverses the "squash", it's unable to connect main to lane-b. The missing history exists on lane-a only.
> default to not throw for NoCommonSnap

- scopes/harmony/bit/load-bit.ts
- scopes/harmony/testing/load-aspect/load-aspect.ts
- src/consumer/consumer.ts
- src/scope/scope.ts
- src/utils/fs/propogate-until.ts
- src/utils/index.ts
- in case the scope exists in both ".bit" and ".git/bit", resolve always to the same path.  (.bit)
- rename the unhelpful function name (with typo) `progogateUntil` to `findInScope`.
> fix, avoid resolving local-scope to two different paths

- scopes/pipelines/builder/builder.service.tsx
An example where this is an issue: the env has changed to add/replace some tasks, then running `bit compile` throws 
> Pipeline error - missing task dependency "teambit.compilation/compiler" of the "teambit.defender/tester:JestTest"
because the builder.getDescriptor is always running when the env is loaded (to show it in `bit env get <comp-id>`).
This PR fixes it by catching these errors and showing them in `bit env get`.
> fix, catch builder.getDescriptor errors to avoid blocking users

- e2e/harmony/revert.e2e.ts
- scopes/component/checkout/checkout-cmd.ts
- scopes/component/checkout/checkout.main.runtime.ts
- scopes/component/checkout/revert-cmd.ts
- src/e2e-helper/e2e-command-helper.ts
To copy the files from the specified version while keeping the component version in .bitmap intact.
> feat(revert): introduce a new command "bit revert"

- scopes/workspace/workspace-config-files/workspace-config-files.main.runtime.ts
- scopes/workspace/workspace-config-files/workspace-config-files.service.tsx
- scopes/workspace/workspace-config-files/ws-config.cmd.ts
> outputs(ws-config) - improve warning for envs that not implements the workspaceConfig API

- scopes/workspace/install/install.cmd.tsx
> outputs(install) - add link about env.jsonc and improve bit install warning's text

- scopes/component/refactoring/refactoring.main.runtime.ts
- scopes/typescript/typescript/sourceFileTransformers/transform.ts
- do not throw an error during refactoring if the env is not loaded (it's only required to get the formatter)
- In case the env was not loaded bring a default formatter -prettier with these options:
```
{
parser: 'typescript',
trailingComma: 'es5',
tabWidth: 2,
singleQuote: true,
}
```
- do not throw an error if the formatting during the refactoring fails (write the unformatted code instead)
> fix(refactoring) - fix refactoring during forking during bit new when component has custom env

- scopes/ui-foundation/uis/side-bar/component-tree/component-view/component-view.tsx
fixes the component id selection in the case when the namespace name and the component name is the same
e.g.
component - `teambit.dot-updates/updates`
`http://<host>/teambit/dot-cloud/~lane/bit-cloud/~component/teambit.dot-updates/updates`
component - `teambit.dot-updates/updates/component-updates`
`http://<host>/teambit/dot-cloud/~lane/bit-cloud/~component/teambit.dot-updates/updates/component-updates`
> fix(ui/component-drawer): set link to exact

- scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
- scopes/workspace/workspace/workspace.provider.ts
- src/consumer/component/component-loader.ts
This PR saves another `workspace.get` call per component loaded from harmony.
> improve component loading originated from workspace aspect by removing recursive call

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/lanes/merge-lanes/merge-lane-from-scope.cmd.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- src/scope/models/version.ts
This only works with `--title` was provided. It replaces the head snap message with this title and appends the squashed snaps messages.
> improvement(merge-from-scope), enable squashing the messages and providing a title

- scopes/scope/scope/get-scope-options.ts
- scopes/scope/scope/scope.ui.runtime.tsx
update `getScope` in `scope.ui.runtime` to allow overriding scope sidebar toggler
> improvement(sidebar): allow overriding scope sidebar toggler

- scopes/typescript/typescript/sourceFileTransformers/export.ts
- scopes/typescript/typescript/transform-source-file.spec.ts
This pull request addresses a bug in the exportTransformer where namespace exports, specifically those using the "export * from 'module'" syntax, were not being correctly renamed according to the provided mapping.
> fix(typescript): AST transform: handle namespace export renaming

- package.json
- pnpm-lock.yaml
- scopes/workspace/watcher/watcher.ts
- Update chokidar to latest version 3.5.3
- Update chokidar ignored paths to support multiple operating systems (including Windows)
- Use of chokidar ignored regexes
> fix(watcher): chokidar ignored paths support for windows

- scopes/component/isolator/isolator.main.runtime.ts
- scopes/dependencies/fs/linked-dependencies/linked-dependencies.ts
- src/utils/fs/create-symlink-or-copy.ts
- mark capsule as ready when creation is done (a new file named `.bit-capsule-ready` will be created at the capsule root)
- do not re-create symlinks to core aspects in scope aspects cache dir if they already exist and valid
- mark capsule as ready after it was moved from dated capsule to cache
- better logs for scope aspects isolation
- move capsule from dated capsule to cache if it already exists but not valid (ready)
- improve moving capsules from dated dir to cache dir
> scope aspects capsule cache fixes

- scopes/component/forking/forking.main.runtime.ts
- src/scope/objects-fetcher/objects-fetcher.ts
Otherwise, the components might get created before the envs, and then when loading them, bit throws an error about missing components.
> fix(new/starters), sort the components to fork to create envs first

- e2e/harmony/lanes/bit-remove-on-lanes.e2e.ts
- scopes/component/checkout/checkout-cmd.ts
- scopes/component/checkout/checkout.main.runtime.ts
- scopes/component/merging/index.ts
- scopes/component/merging/merge-cmd.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/lanes/merge-lanes/merge-abort.cmd.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- src/consumer/component/consumer-component.ts
- src/consumer/component/exceptions/component-not-found-in-path.ts
- in case the last merge deleted components from the workspace (was soft-removed by the other lane), the abort-merge rewrites it back. 
- catch checkout errors during "bit lane merge-abort" and explain in the output the status. suggest to run "bit checkout reset" after fixing the error.
> fix(lane-merge-abort), restore components deleted by the last lane-merge

- scopes/component/merging/merging.main.runtime.ts
- scopes/workspace/workspace/aspects-merger.ts
This PR fixes the issue with stale consumer references in aspect merger and merging main runtime
This specifically fixes the issue of making sure newly loaded components have the correct config loaded when accessed from another process
> fix(aspect-merger | merging): make sure consumer reference is not stale

- scopes/generator/generator/workspace-generator.ts
- this fixes a case when the first compilation (as part of the bit new) is done incorrectly as the envs are not loaded yet.
an example of this is when using:
```
bit new hello-world my-hello-world --env teambit.community/starters/hello-world
```
then looking at the compiled code, you will see - `React.createElement` which is invalid as it should use the new jsx runtime.
(for example `cat my-hello-world/node_modules/@org/scope-name.ui.hello-world/dist/hello-world.js`)
So it should be `_jsx` 
compiling again fixes the issue.
but this leaves the workspace just after the new command in an invalid state (the app will not run for example)
> fix(bit new) - compile components again once all envs and their dependencies are in place

- scopes/workspace/watcher/watcher.ts
It's unclear why `useFsEvents: false,` was used. Removing this fixes the CPU load issue on big projects.
> fix(watch), fix high CPU by removing "useFsEvents: false" from chokidar

- scopes/component/refactoring/refactoring.main.runtime.ts
- scopes/defender/formatter/formatter.ts
- scopes/defender/prettier/prettier.formatter.ts
- scopes/typescript/typescript/sourceFileTransformers/empty-line-encoder.ts
- scopes/typescript/typescript/sourceFileTransformers/transform.ts
This PR fixes the issue where the prettier api would throw the error "Cannot find parser ... "
With this PR we don't use a formatter to re format the transformed source file
Since,
1) The source file is already formatted
2) We encode/decode empty lines when we transform AST
3) Only the matching AST nodes are transformed
hence preserving the formatting of the underlying code
> fix(refactoring): source file formatting after transform

- scopes/pipelines/builder/build-pipeline-order.ts
- scopes/pipelines/builder/builder.service.tsx
This data of the pipelines coming from bit-env command is generated by `BuilderService.getDescriptor()`.
One instance generates the data for the three pipelines: build, tag and snap. However, the way how this class was design is to hold one pipeline only.
It has a member `taskSlot`, which are the tasks registered to a pipeline. It can be just one. build or snap or tag. Can’t be multiple.
What happened is that because only one instance was used, it showed the same build registered tasks for all pipelines. 
Instead of showing the task lists, it is now showing a message suggesting the users to run `bit build --list-tasks`.
> fix(env-get), remove wrong pipelines data, instead refer to using "bit build --list-tasks"

- e2e/harmony/lanes/lanes.e2e.ts
- scopes/component/snapping/tag-model-component.ts
- scopes/scope/importer/import-components.ts
- src/consumer/bit-map/bit-map.ts
This is related to https://github.com/teambit/bit/pull/7706, one case of onLanesOnly was missing. Added here.
> add onLanesOnly when snapping on a lane

- scopes/component/renaming/renaming.main.runtime.ts
Fixes an issue when scope-renaming multiple components and some of them are envs of others. It was throwing ScopeNotFound. 
This PR fixes it by replacing the env ids inside `config` prop in the .bitmap file.
> fix(scope-rename), rename scope of envs in .bitmap config

- e2e/fixtures/workspace-with-tsconfig-issue/workspace.jsonc
- e2e/harmony/custom-env.e2e.ts
- e2e/harmony/pkg-manager-errors.e2e.ts
> chore(e2e) - update react-env version in e2e tests

- e2e/harmony/update-cmd.e2e.ts
- pnpm-lock.yaml
- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/workspace/install/install.main.runtime.ts
- scopes/workspace/install/update.cmd.tsx
The `bit update` command accepts an optional array of package name patterns to pre-filter packages to update. For instance:
```sh
bit update "@mycompany/*" "!@mycompany/ignore" webpack --yes
```
This command would update:
* any packages from the `@mycompany` scope, except the `@mycompany/ignore` package
* the webpack package
> feat: update selected packages by passing patterns to the update command

- e2e/harmony/lanes/merge-lanes.e2e.ts
- e2e/harmony/snap.e2e.2.ts
- src/consumer/component/components-list.ts
Currently, components during-merge are filtered out from the list-modified. As a result, `bit diff` doesn't show them, which makes it hard after `bit lane merge` to figure out what changes were entered, especially if this process involves fixing conflicts.
This PR removes this filter, which also changes `bit status` to show these during-merge components as modified as well (which is fine).
> fix(diff), show diff of components during merge

- .circleci/config.yml
- e2e/harmony/binary-files.e2e.ts
- e2e/harmony/checkout-harmony.e2e.ts
- e2e/harmony/lanes/lanes.e2e.ts
- e2e/harmony/lanes/merge-lanes.e2e.ts
- e2e/harmony/merge-config.e2e.ts
- e2e/harmony/snap.e2e.2.ts
- scopes/component/checkout/checkout-cmd.ts
- scopes/component/merging/merge-cmd.ts
- scopes/lanes/merge-lanes/merge-lane.cmd.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
This is a preparation for new flags functionality that replaces the code according to the strategy [ours, theirs] regardless of a conflict. 
The change is for the following commands: `bit merge`, `bit checkout` and `bit lane merge`.
> replace --ours,--theirs,--manual flags with --auto-merge-resolve<merge-strategy> flag

- e2e/harmony/lanes/bit-remove-on-lanes.e2e.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/component/remove/remove.main.runtime.ts
- scopes/lanes/lanes/lane.cmd.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- src/e2e-helper/e2e-command-helper.ts
- src/scope/models/version.ts
Similar to how "deprecate" works on lanes, where it marks the component as deprecated and once merged to main, the component is deprecated on main.
This PR introduces this functionality for `bit lane remove-comp`, where by default it only marks as removed on the lane, and the component is not merged.
> feat(lane-remove-comp), implement --update-main flag

- src/scope/graph/vizgraph.ts
- src/scope/models/version-history.ts
- in case the `squash` has the same hash as the `parent`, avoid showing it as squashed.
- remove the `[object object]` in the graph
> fix(cat-version-history), minor two fixes for the --graph flag

- scopes/react/react/templates/react-app/files/app-plugin.ts
- scopes/react/react/templates/react-app/index.ts
- In the legacy React app template, change the filename for the plugin file from `{name}.react-app.ts` to `{name}.react-app.cjs`.
> fix: replace app plugin file for React to `.cjs`

- src/scope/component-ops/scope-components-importer.ts
Until we have better understand why sometimes it shows without a clear reason.
> remove the warning about incomplete version history for now

- scopes/component/isolator/isolator.main.runtime.ts
- scopes/pipelines/builder/build.cmd.ts
- scopes/pipelines/builder/builder.main.runtime.ts
- scopes/pipelines/builder/builder.service.tsx
- make a clear separation between build and snap pipelines
- dim the metadata about the graph info to avoid confusion
- clarify how many components are built per env
> improvement(pipelines), make a clear separation between build and snap pipelines

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
It just makes the graph complex for no reason. 
It's also confusing when looking at the Version object to see the same `Ref` in both: `parents` and `squashed.previousParents` props.
> fix(lane-merge), avoid squashing if the distance between the current-lane and the other lane is 1

- e2e/commands/remove.e2e.1.ts
- scopes/component/snapping/tag-model-component.ts
No need, they are removed. It's ok to not have a pkg for them. Also, many times, these components have issues that prevent them to be build successfully.
> fix(snap), avoid running pipelines on removed components

- scopes/workspace/watcher/watch.cmd.ts
- scopes/workspace/watcher/watcher.ts
- scopes/workspace/workspace/workspace.ts
- until now, `bit compile <id>` wasn't compile anything in case the id didn't have a version. This fixes it.
-  fix `bit watch --verbose` to show all events coming from Chokidar and the compiler output.
> fix(compile), allow compiling by specifying ids without their exact versions

- scopes/component/isolator/isolator.main.runtime.ts
- scopes/harmony/cli/cli.main.runtime.ts
- src/logger/logger.ts
- new slot in cli aspect to register on before exit functions. `cli.registerOnBeforeExit(onBeforeExitFn: OnBeforeExitFn)`
- new API for legacy logger to register `OnBeforeExitFn` (used by the cli aspect)
- change isolator registration of moving capsule from dated capsule to cache location to use new cli API
> feature(cli) - a slot to register on before exit functions

- scopes/component/new-component-helper/new-component-helper.main.runtime.ts
- scopes/generator/generator/component-generator.ts
**Context**:
We identified an issue with the `new-component-helper` when a path was provided for multiple components. This led to a potential conflict, causing failures for subsequent components due to existing paths.
**Enhancements**:
1. **Parameter Addition**: The `getNewComponentPath` function has been extended with a third parameter to account for the number of components being created. This ensures that the path returned is unique when multiple components are being generated.
2. **Path Adjustments**: Depending on the number of components to create and the existence of the dir, a path is created from the --path flag alone or joined with the full name of the component.
3. **Synchronous Approach**: Made a conscious effort to keep the new helper method synchronous to ensure that it …
> handle path for multiply components

- scopes/component/renaming/renaming.main.runtime.ts
This PR fixes the issue when there are no env components to rename. 
Previously, if there were no env components it throws during scope rename
```
unable to import the following component(s): org.scope-name/examples/sample-app.
the remote scope "org.scope-name" was not found
```
> fix(renaming): scope rename - handle when there are no env components to rename

- e2e/functionalities/repository-hooks.e2e.ts
- e2e/harmony/export-harmony.e2e.ts
- e2e/harmony/lanes/lanes.e2e.ts
- src/scope/component-ops/export-scope-components.ts
- src/scope/models/model-component.ts
- src/scope/objects/repository.ts
Until now, it was updated during import, which is not ideal. Now that we save the component-id inside the Version object, we can do it during export.
> update VersionHistory object on export

- scopes/generator/generator/workspace-generator.ts
Fix an issue where the logger instance is undefined and the real error will not be thrown when using the logger.error method.
> fix the a case where the logger can be undefined

- src/consumer/bit-map/component-map.ts
Previously, this was done at a later stage, when comparing with gitignore. 
With this PR it is done in the first `glob`.
> perf(bootstrap), improve scanning components dir by ignoring node-modules

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/merging/merge-status-provider.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/component/snapping/snapping.main.runtime.ts
- src/scope/lanes/unmerged-components.ts
- src/scope/models/version.ts
- src/scope/version-validator.ts
Until now, this `--resolve-unrelated` flag was working only when the component was on main, because in this scenario we know what history to keep (the one from main).
This PR handles the case where two lanes created the same component, but that component is not on main.
To decide which history to keep, we use the strategy passed to the `--resolve-unrelated` flag, which can be either `ours` or `theirs`.
> support resolving components with no snaps in common between two lanes

- components/ui/compare/lane-compare-drawer/lane-compare-drawer-name.module.scss
- components/ui/compare/lane-compare-drawer/lane-compare-drawer-name.tsx
- components/ui/compare/lane-compare-drawer/lane-compare-drawer.tsx
- components/ui/compare/lane-compare-page/lane-compare-page.tsx
- components/ui/compare/lane-compare/lane-compare.context.ts
- components/ui/compare/lane-compare/lane-compare.provider.tsx
- components/ui/compare/lane-compare/lane-compare.tsx
- components/ui/component-compare/component-compare/component-compare.module.scss
- components/ui/component-compare/component-compare/component-compare.tsx
- components/ui/component-compare/context/component-compare-context.ts
- components/ui/component-compare/layouts/compare-split-layout-preset/compare-split-layout-preset.module.scss
- components/ui/component-compare/version-picker/component-compare-version-picker.tsx
- components/ui/inputs/lane-selector/lane-grouped-menu-item.module.scss
- components/ui/navigation/lane-switcher/lane-switcher.tsx
- components/ui/surfaces/menu/section/section.module.scss
- scopes/code/ui/code-compare/code-compare-tree/code-compare-tree.tsx
- scopes/code/ui/code-compare/code-compare.module.scss
- scopes/code/ui/code-compare/code-compare.tsx
- scopes/code/ui/code-compare/use-code-compare/use-code-compare.ts
- scopes/compositions/ui/composition-compare/composition-compare.context.tsx
- scopes/compositions/ui/composition-compare/composition-compare.module.scss
- scopes/compositions/ui/composition-compare/composition-compare.tsx
- scopes/compositions/ui/composition-compare/composition-dropdown.tsx
- scopes/compositions/ui/composition-compare/index.ts
- scopes/docs/ui/overview-compare/index.ts
- scopes/docs/ui/overview-compare/overview-compare.context.tsx
- scopes/docs/ui/overview-compare/overview-compare.module.scss
- scopes/docs/ui/overview-compare/overview-compare.tsx
- scopes/lanes/lanes/lanes.ui.runtime.tsx
This PR fixes the following issues,
1. Resolving `Lane Component Ids` in the `Workspace` when the component belongs to the same scope as the lane and has a version
2. Ensuring the `Lane Switcher` and the `Lane Compare dropdown` always query lanes from `offset: 0`
3. `Lane Compare` now allows lifting its state up via LaneCompareContext and Provider for a fully controlled experience.
4. `Component Compare` fixes - add `Component Descriptor` data, handle hidden state better
5. `Code Compare` style fixes
6. `Composition Compare` now has (1) composition selector for both base and compare component compositions
7. `Overview Compare` style fixes
8. Remove syncronized scrolling from all Compare screens (Drawers, Composition dropdown, Composition/Overview Content Viewers)
> fixes(UI): sync UI fixes from cloud

- e2e/harmony/merge-config.e2e.ts
- scopes/component/snapping/tag-model-component.ts
Currently, this file is deleted only once it's empty. However, it's possible that this file still has the (relatively new) "WORKSPACE" section, and as a result, it keeps the file, which makes it very confusing later on to understand why some dependencies have specific versions. 
This PR checks whether all unmerged-components are now merged and if so deletes the file.
> fix, delete merge-conflict file upon snap/tag even when it has workspace entries

- e2e/harmony/lanes/unrelated-and-removed.e2e.ts
- scopes/component/merging/merge-status-provider.ts
- scopes/lanes/merge-lanes/merge-lane.cmd.ts
- src/consumer/component/consumer-component.ts
In this case, we set the "--resolve-unrelated" to `theirs`, so then the history is kept according to the other lane (which is not removed).
> fix(lane-merge), handle a case when a component is deleted and is also unrelated to the other lane

- e2e/harmony/lanes/lanes.e2e.ts
- e2e/harmony/lanes/rename-lane.e2e.ts
- scopes/lanes/lanes/lane.cmd.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- src/e2e-helper/e2e-command-helper.ts
---
**Description:**
Building upon the changes made in the previous PR ([#7852](https://github.com/teambit/bit/pull/7852)), this PR proposes updates to the `LaneRenameCmd` command:
1. **Re-evaluation of Required Parameters**:
- Current command definition:
```typescript
name = 'rename <current-name> <new-name>';
```
- The necessity of the `current-name` parameter is being questioned. The idea is to streamline the renaming process by potentially omitting the need to specify the current name.
2. **Command Context**:
- This command is responsible for renaming a lane both locally and on the remote, provided the lane has been exported.
- Definition:
```typescript
description = `EXPERIMENTAL. change the lane-name locally and on the remote (if exported)`;
```
The intention behind these updates is …
> Improve rename lane command

- scopes/component/component-log/component-log.main.runtime.ts
- scopes/component/component-writer/component-writer.main.runtime.ts
- scopes/workspace/watcher/watcher.ts
- src/consumer/bit-map/bit-map.ts
- src/scope/component-ops/scope-components-importer.ts
- for non-exported lanes, remove the lane prop from the fetch-options sent to the remote.
- fix log-file-history to not throw for new-components
- fix watcher to update file paths
> do not send new lanes to the remote-fetcher 

- scopes/workspace/watcher/watcher.ts
Since the watcher has changed to use `fsEvents`, in some cases it stopped watching with no indication/reason as to why it's happening. (see also https://github.com/teambit/bit/pull/7828).
Today I got a clue why this might happen by getting an error "EMFILE, too many open files" when running vscode with bit extension using the watcher. 
By running `lsof` I noticed that bit watcher opens 4,000 file descriptors (FDs) when running on bit repo (381 components). Taking a closer look as to why this is happening, I figured that for each directory passed to `chokidar`, it opens around 10 FDs. See below.
Since the watcher was configured to get an array of all components-dir, it opened a lot of FDs. (fun fact: this is not happening when chokidar is configured to use polling. It only happens when …
> fix(watch), fix issues with watcher not watching files

- scopes/workspace/workspace-config-files/config-writer-entry.ts
- scopes/workspace/workspace-config-files/writers/extending-config-files.ts
> improvement(ws-config write) - allow post process specific extending file (when same file should be written to few paths)

- scopes/component/isolator/isolator.main.runtime.ts
- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/dependencies/dependency-resolver/index.ts
- scopes/scope/scope/scope-aspects-loader.ts
- scopes/scope/scope/scope.main.runtime.ts
- Added a new config for the scope aspect:
```
"teambit.scope/scope": {
"aspectsNodeLinker": "hoisted"
}
```
- This `aspectsNodeLinker` will allow mentioning a specific node linker to be used when creating capsules for scope aspects (like envs for example). 
If not specified the aspects will be installed using the node linker that is configured by the `dependency resolver` aspect.
> feature(scope aspects) - allow specify specific node linker to be used for scope aspects capsules

- scopes/ui-foundation/uis/side-bar/component-tree/component-view/component-view.tsx
https://github.com/teambit/bit/pull/7668
The above linked PR fixed the component id selection in the case when the namespace name and the component name is the same
But resulted in a regression where it will **only match exact routes**, resulting in any sub route of the component page to unselect the component from the sidebar tree
This PR introduces custom URL matching to support both cases,
(1) when the namespace name and the component name is the same
(2) when the selected href is a subroute of the component
This also fixes an issue on the workspace where the Component Tree showed stale statuses since it didn't refresh when the viewed lane changed.
> fix(Component Tree): custom url matching 

- scopes/workspace/install/update.cmd.tsx
- Patterns passed to the update command may be splitted with commas. For example, `bit update "@babel/types,@mdx-js/mdx"`
> feat: support update patterns separated by commas

- pnpm-lock.yaml
- workspace.jsonc
added `@yarnpkg/plugin-pack` to the dependencies of bit
related issue: https://github.com/teambit/bit/issues/7885
-
-
-
> fix: install should work when Yarn is used

- scopes/workspace/install/install.main.runtime.ts
- local envs & apps will not have their version numbers in their respective directory names inside `node_modules/.bit_roots`
> fix: don't include the version of a local env or app in its root directory

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/component-writer/component-writer.main.runtime.ts
- scopes/component/component-writer/component-writer.ts
- scopes/harmony/api-server/api-for-ide.ts
Currently, when merging from main and main is ahead, it saves the components in .bitmap with the snap (hash) instead of the tags. As a result, the subsequent snap of a dependent, saves the dependency with a snap instead of a tag. 
Once this happens, the manifest generated for this component has the dependency version as `0.0.0-hash` instead of the tag and the installation fails. 
This PR fixes it by saving it with the tag to the .bitmap during the merge.
> fix(lane-merge), save versions in .bitmap as tags if exist when merging from main

- scopes/docs/docs/overview/overview.tsx
This PR fixes an issue when navigating between components and viewing their Overview Page. 
When the component Id changes, the overview iframe mounts and unmounts, but the Component Overview is updated immediately
which leads to the prev iframe being rendered for a few milliseconds before the new one mounts
This PR adds an explicit key to the parent `ComponentOverview` page which unmounts the entire Overview when the component id changes
> fix(overview): re render entire overview when comp id changes

- scopes/component/component/component.ts
- scopes/component/snapping/snapping.main.runtime.ts
currently, when deleting multiple components, some are dependencies of others, it throw `RemovedDependencies` upon snap. This PR fixes it by filtering out all deleting components.
> fix(snap), don't check component-issues for deleted components

- scopes/workspace/install/install.main.runtime.ts
Otherwise, when one process runs `bit install`, other processes (that are running the watcher) have the old components objects.
> ipc-events, clear sse client cache after install

- e2e/harmony/delete.e2e.ts
This test by mistake wan't git-added to #7896.
> add an e2e-test for #7896 - ignore component-issues for deleted comps

- scopes/workspace/watcher/watch.cmd.ts
- scopes/workspace/watcher/watcher.ts
- src/constants.ts
This is related to this bug: https://github.com/paulmillr/chokidar/issues/1196#issuecomment-1711033539.
A fix was merged to master on chokidar repo. Once a new version is released, we can default to FsEvents again.
> fix(watch), default to not use fsevents until a new chokidar release

- scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
This PR fixes the issue where the dev server **won't** open the app in the default browser of the user.
> fix(ui server): open dev server in the default browser

- e2e/harmony/sign.e2e.ts
- scopes/scope/sign/sign.cmd.ts
- scopes/scope/sign/sign.main.runtime.ts
The default is what used to be `--multiple`. 
To get the previous default, use `--original-scope`.
> deprecate --multiple flag of bit sign

- scopes/semantics/schema/index.ts
- scopes/semantics/schema/schema-extractor.ts
- scopes/semantics/schema/schema.main.runtime.ts
- scopes/typescript/typescript/typescript.extractor.ts
This PR updates the extract method in the Schema Extractor to allow overriding context and tsserver paths
Previously, this was only possible when initializing the context from the env. This allows to override it ad hoc during the extract call. 
This PR specifically fixes the issue where all the components with the new env signed from a bare scope, had all APIs extracted as `UnResolvedSchema`
> fix(schema): allow overriding context and tsserver path when extracting 

- pnpm-lock.yaml
- workspace.jsonc
> fix: yarn's peer deps should always be installed as deps of bit

- package.json
- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/watcher/watch.cmd.ts
- scopes/workspace/watcher/watcher.ts
This is a continuation of the watcher saga. See last update here: https://github.com/teambit/bit/pull/7902
It may take some time for Chokidar owners to release a new version (the last one was released Jan 22), so this repo was forked and a new version was released under `@teambit/chokidar`. 
With this new version it's possible to work with the FsEvents and avoid the high CPU load.
> fix(watch), use forked @teambit/chokidar and switch back to FsEvents

- src/consumer/component/package-json-vinyl.ts
- Use an atomic write to avoid broken package.json files
> fix: the generated package.json files should never be in a broken state

- e2e/harmony/pkg-manager-errors.e2e.ts
- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/dependencies/dependency-resolver/index.ts
- scopes/dependencies/pnpm/pnpm-error-to-bit-error.spec.ts
- scopes/dependencies/pnpm/pnpm.package-manager.ts
- scopes/dependencies/pnpm/pnpm.ui.runtime.tsx
- scopes/dependencies/yarn/yarn.ui.runtime.tsx
- scopes/pkg/pkg/pkg.ui.runtime.tsx
- scopes/toolbox/network/agent/agent.spec.ts
- scopes/ui-foundation/use-box/menu/menu.compositions.tsx
- scopes/ui-foundation/use-box/menu/menu.docs.mdx
- scripts/docker-teambit-bit/Dockerfile-symphony
- src/api/consumer/lib/login.ts
- src/cli/commands/public-cmds/login-cmd.ts
- src/consumer/login/login.ts
- Use the new registry (`https://node-registry.bit.cloud`) by default 
- Remove all old registries - (`https://node.bit.cloud` and `https://node.bit.dev`)
- Do not write the `@bit` to the npmrc during bit login
- Do not take the token from npmrc (from the `@bit` entry) but from the bit's config (`user.token`) 
- Remove bit login flags that affect the changes to npmrc (they are not needed anymore now that we don't change the npmrc at bit login)
- `npmrc-path`
- `skip-registry-config`
- Update the use box in the UI to guide the user to run `npm config set` with the new registry url
> change(registry) - use new registry by default (node-registry.bit.cloud)

- .eslintrc.js
- components/ui/component-compare/changelog/component-compare-changelog.tsx
- pnpm-lock.yaml
- scopes/component/graph/ui/component-node/component-node.tsx
- scopes/component/graph/ui/graph-page/graph-filters.tsx
- scopes/dependencies/dependency-resolver/apply-updates.ts
- scopes/react/modules/prerenderer-puppeteer/prerenderer-puppeteer.ts
- scopes/scope/scope/ui/scope.tsx
- scopes/workspace/workspace/ui/workspace/workspace.tsx
- src/consumer/component/sources/vinyl-types.ts
- workspace.jsonc
- Upgrade eslint-config-airbnb-typescript from v5 to v12 (for legacy code only)
- Update some new rules in the eslint config (to prevent the need of fixing thousands of files) 
- Fix some left overs lint errors
- This also fixes this warning when running bit from the repo 
```
⢀⠀ running command "status"...(node:51416) [DEP0128] DeprecationWarning: Invalid 'main' field in '<repo path>/node_modules/eslint-config-airbnb-typescript/package.json' of 'dist/eslint-config-airbnb-typescript.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```
> chore(eslint) - upgrade eslint-config-airbnb-typescript from v5 to v12 (for legacy code)

- scopes/defender/ui/test-page/tests-page.tsx
This PR fixes the issue of not being able to see the tests for a given component when on a lane
> fix(ui/tests): query tests with version when on a lane

- components/ui/component-compare/compare-aspects/compare-aspects/compare-aspects.tsx
- components/ui/component-compare/component-compare/component-compare.tsx
- scopes/code/ui/code-compare/code-compare-view/code-compare-view.tsx
- scopes/code/ui/code-compare/use-code-compare/use-code-compare.ts
- scopes/component/graph/ui/dependencies-compare/dependencies-compare.module.scss
This PR fixes the following issues in Component Compare
- Previously, the workspace will always try to fetch the latest when comparing components in a lane, which ends up fetching the data for the wrong version. This PR fixes it by only fetching the latest when there is no explicit compareId passed, otherwise it uses the component version to fetch
- Aspects Compare page now renders the aspect tree navigation - this was a regression introduced when aligning cloud and OSS review fixes
- Dependencies Compare Graph on workspace rendering is fixed, previously the graph had no height - which resulted in it not being rendered correctly
- Fix Code Review to correctly switch view modes
> fix(ui/ComponentCompare): Viewing diffs in a workspace

- e2e/harmony/install.e2e.ts
- scopes/workspace/install/install.cmd.tsx
- scopes/workspace/install/install.main.runtime.ts
- The `bit install` command will now accept the `--lockfile-only` flag.
> feat: installation that only update the lockfile, not node_modules

- e2e/harmony/snap.e2e.2.ts
- scopes/component/snapping/snap-cmd.ts
- removed components dont need to be shown in the "changed components" list 
- the user has deleted/removed the component, they're not bothered with how bit manages that in the background and info on version bumps only confuses the removed status
-
> dont show removed components in the "change components" list

- scopes/docs/docs/docs.main.runtime.ts
This PR fixes the issue where the extracted description on a component without a description block in the mdx files extracts jsdocs from its implementation, resulting in incorrect description extracted.
> fix(docs): remove legacy js doc parser when extracting doc description

- scopes/component/snapping/snap-cmd.ts
- scopes/pipelines/builder/builder.service.tsx
- scopes/scope/scope/scope.main.runtime.ts
- src/consumer/consumer.ts
- src/scope/scope.ts
this is important especially for long-running process (e.g. watch/start) to have the scope lane-id in sync with the consumer.
> don't cache currentLaneId when a workspace is available

- scopes/harmony/ipc-events/ipc-events.main.runtime.ts
A practical example when this is needed: bit-server is running in the background (in vscode-ext), and the user is running `bit export` in the CLI. 
If this export triggered a .bitmap change (e.g. a component was new and now exported), then bit-server knows to reload the consumer and clear all caches.
If not, then, bit-server still have the old `ModelComponent` objects in the scope cache, and it's not aware of the recent export.
> publish a new IPC event when objects are persist in the local scope

- scopes/semantics/schema/mock/button-schemas.json
- scopes/typescript/typescript/transformers/parameter.ts
- scopes/typescript/typescript/transformers/variable-declaration.ts
This PR fixes the issue of incorrectly parsing schema for arrow function declaration. 
Previously the schema extractor used the type information from the variable declaration, instead of the function initializer (`= () => {}`) which yields incorrectly extracted signature, return type, and parameter information.
e.g.
`const MyComponent: React.FC<ParamType> = ({p1, p2, ...rest}) => {}`
> fix(Schema): handle parsing arrow function declarations

- scopes/scope/export/export-cmd.ts
- scopes/scope/export/export.main.runtime.ts
To help in some edge cases when the export failed on some components, but the status is not "staged" anymore. 
Similar to `--all-versions` flag, it's running on all components regardless of "staged" status, however, this one only export the head version, not all history.
> introduce --head-only flag for bit-export

- .bitmap
- e2e/harmony/load-bit.e2e.ts
- src/consumer/consumer.ts
Otherwise, in case the components have the same scope-name, bit throws ComponentNotFound upon import, because it assumes the local scope is the remote scope.
> generate a unique name to a local-scope when created from the workspace

- scopes/semantics/entities/semantic-schema/schemas/this-type.ts
- scopes/semantics/schema/mock/button-schemas.json
- scopes/typescript/typescript/transformers/constructor.ts
- scopes/typescript/typescript/transformers/this-type.ts
Previously, all `this` (self) reference schema's only rendered `this` as their type. This PR adds the parent class's name to provide more metadata of the self referenced type, specifically in the case of constructors
> fix(schema): add class name to ThisType schema

- scopes/component/merging/config-merger.ts
Otherwise, in some cases it generates this odd output:
```
<<<<<<< bd6a9262467c86932302a6c0a508b3dc1f476b3b (teambit.vscode/config-diff)
"teambit.pipelines/builder": "-"
=======
"teambit.pipelines/builder": {}
>>>>>>> d8770f855173e65609df08ac529b799443759760 (main)
}
```
This is happening when in one end the `Version` object was not built yet, so the builder aspect is empty.
> ignore builder aspect when merging config

- src/consumer/bit-map/component-map.ts
- src/utils/ignore/ignore.ts
It helps to exclude files/patterns per component basis. This `.bitignore` file has the same syntax of `.gitignore`. The file is tracked by bit so then when importing the component, the ignored files are still ignored in case they were re-introduced.
> feat, support .bitignore within component dirs

- .bitmap
- scopes/api-reference/api-reference/api-reference.ui.runtime.tsx
- scopes/api-reference/renderers/grouped-schema-nodes-summary/grouped-schema-nodes-summary.tsx
- scopes/api-reference/renderers/schema-node-member-summary/function-node-summary.module.scss
- scopes/api-reference/renderers/schema-node-member-summary/function-node-summary.tsx
- scopes/api-reference/renderers/this/index.ts
- scopes/api-reference/renderers/this/this.renderer.tsx
- scopes/api-reference/renderers/type-ref/index.ts
- scopes/api-reference/renderers/type-ref/type-ref.renderer.tsx
- scopes/api-reference/utils/custom-prism-syntax-highlighter-theme/custom-theme.js
- scopes/api-reference/utils/custom-prism-syntax-highlighter-theme/index.ts
This PR is part (1) of style fixes in API Reference
It adds the following
- a custom Bit flavoured Prism Syntax Highlighter theme for node summary signatures
- thisType renderer to handle self referenced types
- style fixes for function node summary
> fix(schema): custom syntax highlighter theme + node summary style fixes

- scopes/compilation/compiler/compiler.main.runtime.ts
It's better for performance as it's not needed every time the component is loaded. 
Also, in some edge cases, this check throws an error if it gets called during installation/compilation.
> move the check for missing-dist from onLoad slot to status and snap/tag only

- scopes/component/snapping/tag-cmd.ts
Currently it always shows "nothing to tag" message. For `bit tag --persist` it can be confusing, so this PR changes it in this case to "no soft-tag found".
> fix(tag), adjust the message of "no component to tag" for persist

- scopes/component/isolator/isolator.main.runtime.ts
- scopes/scope/scope/scope-aspects-loader.ts
- src/constants.ts
- add new bit config named: `cache_lock_only_capsules`
- if it's true the isolator will do a few things:
* in the end of the process it will only move the lock file (pnpm-lock.yaml) into the capsule cache
* in the beginning of the process it will check if there is a lock file in the capsule cache, if yes it will move it to the temp dated dir
* it will write env's file into the dated dir (as it only contain the lock file)
* it will run install in the dated dir (as there is no node_modules there yet)
> feature(isolator) - support caching of the lock file only for scope aspects capsules

- .bitmap
- components/renderers/react/index.ts
- components/renderers/react/react.renderer.module.scss
- components/renderers/react/react.renderer.tsx
- scopes/react/react/react.api.transformer.ts
- scopes/react/react/react.schema.ts
- workspace.jsonc
This PR fixes the React API Transformer and Renderer to support extracting and rendering schema for a react component without any props.
> fix(schema/api-ref): support extracting schema for react comps without props

- scopes/dependencies/dependency-resolver/package-manager.ts
- scopes/dependencies/pnpm/lynx.ts
- scopes/dependencies/pnpm/pnpm.package-manager.ts
- Expose a setting is passed to pnpm: ignorePackageManifest. When set to `true` installation is done using information from the lockfile only. It doesn't matter if the lockfile is out of date.
> feat: add ignorePackageManifest option to the pnpm package manager aspect

- e2e/commands/diff.e2e.1.ts
- scopes/compilation/compiler/workspace-compiler.ts
- scopes/component/component-compare/component-compare.main.runtime.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
- src/consumer/component-ops/component-status-loader.ts
- src/consumer/component/components-list.ts
- src/consumer/consumer.ts
Clear the in-memory status-cache, which says whether a component is modified. Otherwise, in-memory processes, such as, vscode-ext, get the wrong status data.
> fix(snap/tag), clear status-cache when a component is modified

- scopes/component/snapping/snapping.main.runtime.ts
Previously, deps were imported earlier along with the seeders and as a result, their version-history wasn't fetched causing later calls of isOnMain/isOnLane to fail.  This PR fixes it to be imported during populate-flattened-deps, similar to how tag on the workspace works.
> fix(tag-from-scope), import deps with their version-history

- .circleci/config.yml
- bvm is installed globally with Yarn
- Yarn is installed with corepack
- Yarn v3 is used instead of Yarn v1
- Yarn v3 is configured to use the node-modules node linker
> ci: update Yarn to v3

- scopes/dependencies/dependency-resolver/dependencies/dependency.ts
- scopes/dependencies/dependency-resolver/dependency-resolver.graphql.ts
This PR fixes the sorting order of the dependencies displayed in the code tab, by sorting them alphabetically.
> fix(code): order deps by package name

- scopes/scope/export/export-cmd.ts
A new flag `--open-browser` was created to open the browser.
> change the default of bit-export to not open the browser

- e2e/harmony/snap-from-scope.e2e.ts
- scopes/component/snapping/snap-from-scope.cmd.ts
- scopes/component/snapping/snapping.main.runtime.ts
With this PR it's possible for snap-from-scope to update an existing source file, delete or create a new file.
> improvement(snap-from-scope), support update source files

- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/workspace/install/install.main.runtime.ts
- Print out an error message if there are no dependencies matching the patterns used with `bit update`.
- Print a hint about using the `--latest` flag, if no outdated dependencies are found.
> feat: add more info messages to the update command output

- scopes/scope/scope/scope.ui-root.ts
- scopes/ui-foundation/ui/bundle-ui.task.ts
- scopes/ui-foundation/ui/start.cmd.tsx
- scopes/ui-foundation/ui/ui-server.ts
- scopes/ui-foundation/ui/ui.main.runtime.ts
- bare scope `bit start` - serve from bundle
- Enable pre-bundling for scope aspect
- Generate 2 bundles - one for the workspace and another one for the scope
- Load respective bundle depending on where the dev server is starting (workspace or scope)
> add(prebundle): scope aspect

- scopes/scope/importer/import-components.ts
- scopes/scope/importer/import.cmd.ts
- scopes/scope/importer/importer.main.runtime.ts
- Now you can use new flag `--filter-envs` for bit import.
This is useful in case you import many unknown components for example when using `**` in the pattern, or when using `--dependencies` or `--dependents` flag.
- The new flag supports multiple envs at the same time wrapped by quotes, separated by `,`, for example:
```
bit import <comp-id> --filter-envs "<env-id1>, <env-id2>"
```
- The new flag supports getting `env-id` with version: `env-id@version` in that case it will only bring components using that specific version of the env.
- The new flag supports getting `env-id` without a version: `env-id` in that case it will bring components using and version of the env.
- In case you mention specific components (for example `comp-id` in the example above, it won't be filter out (so bit …
> feature(import) - new filter-envs flag for bit import command

- scopes/dependencies/pnpm/lynx.ts
- scopes/dependencies/yarn/yarn.package-manager.ts
- scopes/workspace/install/install.main.runtime.ts
- Removed linking of package.json files from pnpm.package-manager as it is already handled by node modules linker.
- Removed dead code from yarn.package-manager
> fix: don't link package.json files twice during installation

- .circleci/config.yml
- The reason we should publish the artefact for Windows from Windows is that Windows doesn't support symlinks. If we create the tarball on Linux, yarn will create symlinks in `node_modules/.bin` directories, which will fail during extraction on Windows. However, if we run install on Windows, Yarn will create command shims (not symlinks) in `node_modules/.bin`
> ci: release Bit CLI for Windows from Windows

- scopes/harmony/application/app-build-result.ts
- scopes/harmony/application/build-application.task.ts
- scopes/harmony/node/node-app-options.ts
- scopes/harmony/node/node.application.ts
to save the mainFile and artifactsDir into the objects.
Until now, it was saving the entire `BuildContext` object, which includes all capsules and components objects.
> fix(node-app), utilize the AppBuildResult.metadata 

- scopes/lanes/lanes/lanes.ui.runtime.tsx
This PR fixes the issue with not being able to navigate to a historical snap on a lane from scope.
> fix(lanes): fix fetching historical snaps on lane from bare scope

- CONTRIBUTING.md
- components/component-id/exceptions/missing-scope.ts
- scopes/harmony/bit/load-bit.ts
- scopes/scope/scope/clear-cache-action.ts
- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/clear-cache/clear-cache-cmd.ts
- scopes/workspace/clear-cache/clear-cache.main.runtime.ts
- src/api/consumer/lib/clear-cache.ts
- src/api/consumer/lib/init.ts
- src/scope/exceptions/bit-id-comp-id-err.ts
- src/scope/models/model-component.ts
- src/scope/models/version.ts
- src/scope/objects/repository.ts
- add a descriptive message when previously errored with "scope is missing from a component-id...". suggest running "bit cc".
- fix `bit cc` (clear-cache) command to not throw in case the consumer or scope failed to load. 
- fix `bit init --reset-scope` to work in case the consumer failed to load.
- add another suggestion in case the components were tagged with the old bit-version to run `bit init --reset-scope` if other options failed.
> handle errors of workspace tagged with older bit-version before ComponentID changes

- scopes/harmony/cli/cli.main.runtime.ts
- scopes/harmony/cli/version.cmd.ts
Currently the way to get bit-version is by running `bit -v`.  This PR introduces a dedicated command for this, which can be used for IDEs and also can be extended later to include remote-version and so on.
> introduce "bit version" to show bit version

- scopes/dependencies/pnpm/pnpm.ui.runtime.tsx
- scopes/pkg/pkg/pkg.ui.runtime.tsx
This PR updates the order of package managers in the use box dropdown on the component page. 
Previous order;
Bit, NPM, Yarn, PNPM
Updated order;
Bit, PNPM, Yarn, NPM
> fix(ui/component): Update package manager order in use box dropdown

- src/scope/exceptions/bit-id-comp-id-err.ts
- src/scope/objects/repository.ts
As a result of upgrading to > 1.2.10, local tags/snaps/lanes created by an older version can be invalid. For the most cases, the suggested solution: `bit reset --never-exported` fixes the issue. This PR covers the case when the command fails in the bootstrap phase.
> delete invalid objects when running bit reset --never-exported

- scopes/harmony/config/workspace-config.ts
Many IDEs adds the newline at the end of the file automatically, so if we write this file without the "\n" at the end, the file is modified whenever bit writes the file and the user is opening it with the IDE.
> add a new line at the end of the workspace.jsonc file

- src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
This is needed in order for users to not get errors in bit-status once this lane is merged.
https://bit.cloud/teambit/node/~lane/detect-require-resolve/~ripple-ci/job/teambit-detect-require-resolve-statements
> adjust ImportNonMainFiles comp-issue for the future require.resolve detection

- scopes/compositions/panels/composition-gallery/composition-gallery-skeleton/composition-gallery-skeleton.tsx
This PR fixes duplicate render keys in CompositionGallerySkeleton when rendering a list of CompositionGallerySkeleton components
> fix(CompositionGallerySkeleton): duplicate render key 

- scopes/component/component/component.ts
- scopes/component/component/config.ts
- scopes/component/component/index.ts
- scopes/component/component/state.ts
- scopes/scope/scope/scope-component-loader.ts
- scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
Currently, the `Config` class gets the `consumerComponent.extensions` into the constructor. Problem is that in some cases, after the component object is created, we replace the `consumerComponent.extensions` with another ExtensionDataList instance. (happens in snap-from-scope command). When this is happening, we get two unrelated instances of the extensions, which leads to a very hard to debug extension issues.
This PR passes the instance of consumerComponent itself into the Config constructor, and makes the `extensions` prop dynamic as a getter function, so it's always up to date.
> refactor, change Config class to return extensions from ConsumerComponent instance

- scopes/compilation/compiler/workspace-compiler.ts
- scopes/component/new-component-helper/new-component-helper.main.runtime.ts
- scopes/harmony/api-server/api-server.main.runtime.ts
- scopes/harmony/api-server/server.cmd.ts
- scopes/harmony/application/application.main.runtime.ts
- scopes/preview/preview/preview.start-plugin.tsx
- scopes/workspace/watcher/watch.cmd.ts
- scopes/workspace/watcher/watcher.main.runtime.ts
- scopes/workspace/watcher/watcher.ts
- scopes/workspace/workspace/on-component-events.ts
- scopes/workspace/workspace/workspace.ts
In some scenarios there are multiple watchers running in the background (e.g. `bit start` and vscode-ext), in which case it's best to let only one of them compile the components to avoid race condition between them.
> make the compilation during watch configurable

- scopes/workspace/workspace-config-files/workspace-config-files.main.runtime.ts
- Before this change when running `bit ws-config write` with `--clean` (for example via the `bit create` command). we first cleaned all the config files, then write again new config files.
Many times, the new config files are exactly the same as the ones before (especially on bit create).
Deleting and re-creating the files, lead to issues with the IDE ts-server which sometimes needs to be restarted as a result of this.
Now, we write all the files first (and override existing files), and then only delete files that were not written during the write action. 
This minimizes the cases of deleting and re-creating the same files, which makes it play better with IDEs.
> fix(ws-config) - do not delete config files that are going to be written as part of the write op

- scopes/generator/generator/component-generator.ts
- scopes/generator/generator/component-template.ts
- scopes/workspace/install/install.main.runtime.ts
- Add `skipIfExisting` option to `WorkspaceInstallOptions`
- New props on the ComponentTemplate interface: 
```
/**
* adds a metadata that the component that this template creates is of type env.
* This will be used later to do further configuration for example:
* - ensure to create the .bit_root for it
*/
isEnv?: boolean;
/**
* adds a metadata that the component that this template creates is of type app.
* This will be used later to do further configuration for example:
* - add it to the workspace.jsonc as app
* - ensure to create the .bit_root for it
*/
isApp?: boolean;
/**
* list of packages to install when the component is created.
*/
packages?: string[];
/**
* Perform installation of missing packages after component generation.
* This is the same as of running `bit install …
```
> feature(comp-templates) - allow templates to declare they create app/env and packages to install

- scopes/component/checkout/checkout.main.runtime.ts
- scopes/component/component-compare/component-compare.main.runtime.ts
- scopes/component/deprecation/deprecation.main.runtime.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/component/mover/mover.main.runtime.ts
- scopes/component/new-component-helper/new-component-helper.main.runtime.ts
- scopes/component/remove/remove.main.runtime.ts
- scopes/component/renaming/renaming.main.runtime.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/status/status.main.runtime.ts
- scopes/component/tracker/tracker.main.runtime.ts
- scopes/dependencies/dependencies/dependencies.main.runtime.ts
- scopes/generator/generator/component-generator.ts
- scopes/generator/generator/workspace-generator.ts
- scopes/harmony/aspect/aspect.main.runtime.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/lanes/lanes/switch-lanes.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- scopes/scope/export/export.main.runtime.ts
- scopes/scope/importer/importer.main.runtime.ts
- scopes/workspace/install/install.main.runtime.ts
- scopes/workspace/workspace/bit-map.ts
- scopes/workspace/workspace/workspace.ts
- src/api/consumer/lib/get-consumer-component.ts
- src/consumer/consumer.ts
It provides some context to help understanding the diff between historic .bitmap file. (a future feature for vscode-ext).
For example, when a .bitmap is change due to a tag, it saves the info that it's coming from "bit tag" and the tag-message.
> save metadata when backing up .bitmap files

- scopes/dependencies/dependencies/dependencies-cmd.ts
- scopes/dependencies/dependencies/dependencies.main.runtime.ts
- scopes/dependencies/dependency-resolver/package-manager.ts
- scopes/dependencies/pnpm/pnpm.package-manager.ts
- `bit why <pkg_name>` now accepts a `--depth` option for specifying how deep to search for the package in dependencies.
> feat(why): specifying the depth until which to search for dependencies

- src/scope/network/http/http.ts
because `x-request-id` is already used by CloudFlare.
> change x-request-id to x-bit-request-id

- src/scope/component-ops/get-diverge-data.ts
Only reason to traverse the "unrelated" and the "squashed" is to find the common snap and avoid the `NoCommonSnap` error. Once the common snap is found, no need to deal with the unrelated and squashed, only traverse the parents to find maybe another common snap with lower depth.
> fix(get-diverge-data), avoid traversing unrelated and squashed in case the common-snap has found

- e2e/harmony/dependencies.e2e.ts
- src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
- src/consumer/component/dependencies/dependency-resolver/overrides-dependencies.ts
- src/utils/path.ts
Because it's possible that the file doesn't exist in the source, but will be available later on in the dists.
> do not show missing-files in bit-status when the file exists in the same comp with a different extension

- scopes/component/graph/graph-cmd.ts
- src/api/scope/lib/cat-version-history.ts
- src/cli/commands/private-cmds/cat-version-history-cmd.ts
- src/scope/graph/vizgraph.ts
- src/scope/lanes/remote-lanes.ts
- src/scope/models/version-history.ts
- show tags when applicable. 
- in case a lane has a component with head pointing to one of the hashes, show it.
- introduce `--graph-path` flag to support saving the graph as other formats, e.g. `svg`. 
- introduce `--short-hash` flag to show the hash as 9 digits instead of 40.
Before:
After:
And with `--short-hash`:
> improvement(cat-version-history-graph), show tags, lane heads and squashed/unrelated text

- src/constants.ts
- src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
- src/consumer/component/dependencies/dependency-resolver/overrides-dependencies.ts
- src/consumer/config/component-overrides.ts
- src/consumer/config/consumer-overrides.ts
In the past it was possible to add to the "overrides" section a file-override (with `file://` prefix). It's not supported since Harmony.
> refactor, remove the old unused code related to overrides of files

- e2e/harmony/rename.e2e.ts
- scopes/component/renaming/renaming.main.runtime.ts
currently, if no `--scope` provided, it sets it to the defaultScope instead of the sourceId scope.
> fix(rename), set the scope-name correctly to the targetId

- src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts
- src/consumer/component/dependencies/dependency-resolver/overrides-dependencies.ts
This way it'll be possible for a future change to use this class from the scope where there is no consumer.
> refactor, remove consumer from OverridesDependencies class

- scopes/pipelines/builder/build.cmd.ts
- scopes/pipelines/builder/builder.main.runtime.ts
Helps debugging deploy tasks without requiring to actually tag/snap.
> feat(build), introduce --include-snap and --include-tag flags to include snap/tag pipeline tasks

- scopes/docs/docs/overview/overview.tsx
- scopes/react/ui/docs/properties-table/properties-table.tsx
This PR fixes the following issues
1. The iframe not handling errors correctly. Previously, it would throw an error which makes it impossible to detect in the host app, resulting in an infinite loader. This PR updates the PropertiesTable to just log the error and render nothing instead. 
2. Hiding the loader if includesEnvTemplate is true. This handles corrupted preview data for legacy components, where isScaling gets incorrectly calculated as true but the preview was bundled with env
> fix(Overview): handle legacy comps and errors in docs app

- scopes/component/snapping/snapping.main.runtime.ts
currently, when "dependencies" prop contains an extension-id it's not updated into the `consumer.extensions` due to a regression related to "newExtensionId" prop.
> fix(tag-from-scope), update extension versions correctly

- scopes/scope/export/export.main.runtime.ts
Otherwise, the user is under the impression that the export was cancelled while in fact the remote started processing the data.
> disable Ctrl+C during export once started sending objects

- scopes/generator/generator/generator.main.runtime.ts
- scopes/harmony/bit/index.ts
- scopes/harmony/bit/load-bit.ts
`loadDeps` hook is registered when Dependencies aspect is instantiated. The issue was that during `bit create`, we load another instance of bit from the global scope. When this `loadBit` is happening, it creates a new instance of Harmony and all aspects, including Dependencies aspect. In this Harmony instance, there is no Workspace because it is loaded from a global scope, hence the new registration of the `loadDeps` takes place without workspace, which fails any component load afterwards originated from the original Harmony instance. 
These ugly Globals hooks will be removed once Legacy is gone. Until then they keep bite us here and there.
> fix(create), restore LoadDeps hook after loading bit from the global scope

- e2e/commands/untag.e2e.2.ts
- e2e/flows/id-with-wildcard.e2e.2.ts
- e2e/flows/out-of-sync-componets.e2e.3.ts
- e2e/functionalities/components-index.e2e.2.ts
- e2e/harmony/custom-env.e2e.ts
- e2e/harmony/export-harmony.e2e.ts
- e2e/harmony/lanes/bit-reset-on-lanes.e2e.ts
- e2e/harmony/lanes/diverged-from-remote-lane.e2e.ts
- e2e/harmony/lanes/lanes.e2e.ts
- e2e/harmony/lanes/merge-lanes.e2e.ts
- e2e/harmony/snap.e2e.2.ts
- e2e/harmony/tag-harmony.e2e.ts
- e2e/harmony/untag-harmony.e2e.ts
- src/e2e-helper/e2e-command-helper.ts
- src/scope/objects-fetcher/objects-fetcher.ts
The issue this PR fixes is when export fails, user resets and re-snap, then `bit import` doesn't write the "ref" file of that lane, which result in `bit status` doesn't show the components as merge-pending.
> fix(import), write refs of remote lanes during import even when no comp was imported

- e2e/harmony/recover.e2e.ts
- scopes/component/remove/remove.main.runtime.ts
Currently, it tries to import it and then throw an error about the component being diverged. 
In this PR, instead of importing it, it tries to get it from the local scope first.
> fix(recover), fix recovevering a local deleted component when it is also diverged

- e2e/harmony/delete.e2e.ts
- scopes/component/checkout/checkout.main.runtime.ts
- scopes/component/snapping/snapping.main.runtime.ts
- src/consumer/component/components-list.ts
-  in case a component is both: diverge (merge-pending) and also deleted, `bit status` shows it in both categories. (previously it was showing it only as deleted).
- running `bit checkout head` on deleted component is not ignored anymore. Instead, it is updated to the head while keeping the local change of the removal. So the end result is that the files are the same as the head and it's still locally deleted.
- allow running bit-reset on deleted components (otherwise, if the component is diverged, there is no good way out of this state).
> fix(status,checkout-head), fix status to show deleted when merge-pending, fix checkout-head to consider deleted

- scopes/pipelines/builder/artifact/artifact-list.ts
- scopes/pipelines/builder/artifact/artifact.ts
- add `Artifact.artifactDir` API. (a calculation of what is probably the root dir of the artifact).
- add `ArtifactList.findByName` and `ArtifactList.findByTaskName` APIs.
> add an API to calculate artifacts rootDir

- src/scope/component-ops/scope-components-importer.ts
Currently, when import is running and a component is found to have an incomplete version-history object, it refetches it. 
This was originally done due to the new importer brings incomplete version history objects. It should be fine now.
If for some reason it's needed, run `BIT_FETCH_INCOMPLETE_VERSION_HISTORY=1 bit import`.
Keep in mind that in some cases, enabling it can cause an issue. e.g. when there is a version conflict and the import process is unable to merge between the `ModelComponent` object of the remote and the local. It also shows the VersionHistory as incomplete inaccurately, the VersionHistory doesn't have the local version.
> default to not re-fetch missing version history

- scopes/component/new-component-helper/new-component-helper.main.runtime.ts
- workspace.jsonc
This PR fixes the `NewComponentHelper` aspect by using the consumer's `composeRelativeComponentPath` method instead of `composeComponentPath` directly from legacy - which results in the default behaviour of newly created components to belong to a sub directory with their `{name}`, syncing it with how the import works. 
Previously, if you tried to create a component in a defaultDirectory without specifying an explicit pattern (e.g. `{scope}/{name}`), it will throw an error about the path existing after the first component creation since it never appended the `{name}` pattern to the defaultDir string, where else if you imported a component with the same defaultDirectory it would be imported to the `/{name}` directory instead - resulting in different behaviour for the both commands with the …
> fix(NewComponentHelper): Sync default component dir creation with import

- scopes/component/forking/forking.main.runtime.ts
- scopes/component/new-component-helper/new-component-helper.main.runtime.ts
This PR fixes the issue with forking local components with the same name (without specifying the targetId)
Previously, it would throw an error if you try to fork a local component without specifying the targetId. Now it derives the targetId from the existing component's fullName and forks it correctly.
> fix(forking): handle forking local components without specifying targetId

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/checkout/checkout-cmd.ts
- scopes/lanes/merge-lanes/merge-lane.cmd.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
The scenario is when on a lane and some of the workspace components belong to main and are not part of the lane. 
In case these main components are out of date, how to update them?
In the past, `bit checkout main` was the way to go. This had been changed to not include them, see [here](https://github.com/teambit/bit/pull/6853) the reason.
Currently, `bit lane merge main` takes care of this components. However, a change done 4 months ago, required a flag `--include-non-lane-comps` to include them.
Turns out that this is confusing, and for the most cases, it is expected to include them by default without any flag.
This PR does exactly this. In case these components are not wanted, a new flag has introduced: `--exclude-non-lane-comps` to exclude them.
> change "bit lane merge main" default to include non-lane components

- e2e/harmony/dependencies.e2e.ts
- scopes/dependencies/dependencies/dependencies-loader/dependencies-versions-resolver.ts
- src/e2e-helper/e2e-command-helper.ts
It was fixed here: https://github.com/teambit/bit/pull/8206
But in some cases it wasn't working. Fixed and added an e2e-test.
> fix(version-resolver), prefer version from deps-set over .bitmap

- e2e/harmony/lanes/rename-lane.e2e.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- src/scope/lanes/lanes.ts
Currently, `bit lane rename` doesn't update the scope.json "lanes.new" prop with the new name. 
As a result, switching back and forth, the .bitmap shows as if the lane is exported incorrectly.
> fix(lane-rename), update records about whether a lane is exported during rename

- src/consumer/bit-map/bit-map.ts
In some scenarios `bit init --reset-new` were populating the `scope` field instead of the `defaultScope`.
> fix(init-reset-new), never populate "scope" field, only "defaultScope"

- scopes/harmony/config/workspace-config.ts
- src/cli/commands/public-cmds/init-cmd.ts
currently, when running `bit init --default-scope <some-scope>`, it removes all other workspace config values, such as `defaultDirectory`.
> fix(init), keep workspace-aspect-config values when running with --default-scope

- .circleci/config.yml
- scopes/component/snapping/snap-cmd.ts
- scopes/component/snapping/snap-from-scope.cmd.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/tag-cmd.ts
- scopes/component/snapping/tag-from-scope.cmd.ts
- scopes/component/snapping/tag-model-component.ts
This is a continuation of https://github.com/teambit/bit/pull/8281.
In that PR this calculation was done only when an env variable was used. This PR takes it to the next step, which enables it by default. In case an error was thrown due to discrepancies between the methods of calculating the graph, it suggests adding `--rebuild-deps-graph` flag to not get blocked.
> default to calculate deps-graph from the saved flattened-edges unless --rebuild-deps-graph was used

- scopes/component/forking/forking.main.runtime.ts
- scopes/generator/generator/workspace-generator.ts
- scopes/generator/generator/workspace-template.ts
With this PR you can specify targetScope in any fork entry in the fork function of your starter.
for example:
```
// my.starter.ts
fork() {
return [
{
id: 'teambit.base-ui/text/heading',
targetName: 'design/heading',
targetScope: 'my-org.scope'
},
];
}
```
> feature(starters) - add option to specify targetScope in fork entry from starters

- scopes/generator/generator/index.ts
- scopes/generator/generator/workspace-generator.ts
- scopes/generator/generator/workspace-template.ts
Added a new `create` API for starters.
Example:
```
// my.starter.ts
create(){
return [
{
templateName: 'ng-app',
componentName: 'my-ng-app',
aspect: 'bitdev.angular/angular-env'
}
]
}
```
Each entry should satisfy the following:
```
export interface CreateComponentInfo {
/**
* the template for generating the component
*/
templateName: string;
/**
* component name to generate
*/
componentName: string;
/**
* sets the component's scope-name. if not entered, the default-scope will be used
*/
scope?: string;
/**
* relative path in the workspace. by default the path is `<scope>/<namespace>/<name>`
*/
path?: string;
/**
* set the component's environment. (overrides the env from variants and the template)
*/
env?: string;
/**
* aspect-id of the template.
*/
aspect?: string;
}
```
> feature(starters) - add new create API for starters API

- scopes/component/snapping/snapping.main.runtime.ts
currently, the cache-clear is done before we calculate the auto-tag components, so they're retrieved from the cache although they'll be tagged/snapped.
> fix(snap/tag), clear also the auto-tag components cache

- scopes/component/component/component.graphql.ts
- scopes/component/component/ui/component-model/component-model.ts
- scopes/component/component/ui/use-component.fragments.ts
- fix(bit start) - restore elementsUrl field in component gql to have backward compatibility
- stop querying the deprecated elementsUrl in gql requests
> fix(bit start) - restore elementsUrl field in component gql to have backward compatibility

- package.json
In some scenarios this makes `bit status` 130% faster
> perf, upgrade cleargraph to fix build-graph-ids performance

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- scripts/link-bit-legacy.js
Due to a recent change https://github.com/teambit/bit/pull/8279, the default when running `bit lane merge main` is to include non-lane components. 
The issue is that these non-lane components were also added to the lane object. So for example, if a workspace has 10 components and only 2 were part of the lane, after the merge, all 10 components became part of the lane.
This PR fixes it by updating non-lane components in the .bitmap/file-system but not adding them to the lane object.
If the flag `--exclude-non-lane-comps` is used, then it doesn't touch these non-lane components.
> fix(lane-merge), avoid adding non-lane components into the current lane when merging from main

- scopes/harmony/config/workspace-template.jsonc
we should really only comment out the tempaltes and not the entire entry. this makes the DX easier for customization.
-
-
-
> fix comment out of ws.jsonc templates

- bin/bit.js
After `bit install` of my team's workspace, I was getting the following error:
`Error: Cannot find module '../node_modules/@teambit/bit/dist/app'`. Which in the require stack trace showed it was coming from `~/.bvm/versions/0.1.52/bit-0.1.52/node_modules/@teambit/legacy/bin/bit.js`.
When poking around that folder, it seemed like the issue is that `@teambit/bit`  was hoisted from `~/.bvm/versions/0.1.52/bit-0.1.52/node_modules/@teambit/bit` to `.bvm/versions/0.1.52/bit-0.1.52/node_modules/@teambit/bit`
So I changed the require line in `~/.bvm/versions/0.1.52/bit-0.1.52/node_modules/@teambit/legacy/bin/bit.js` from `require('../node_modules/@teambit/bit/dist/app')` to `require('@teambit/bit/dist/app');` locally, which fixed the error and allowed `bit help` and `bit install` to run …
> fix(bin): update require to find hoisted dependencies

- scopes/preview/preview/pre-bundle-utils.ts
- scopes/workspace/install/install.main.runtime.ts
- scopes/workspace/install/link/rewire-row.ts
- scopes/workspace/modules/node-modules-linker/codemod-components.ts
- scopes/workspace/modules/node-modules-linker/index.ts
- scopes/workspace/modules/node-modules-linker/node-modules-linker.ts
This is a start of a broader task to move away from the legacy `loadComponents`.
> refactor, move codemod-components from legacy to node-modules-linker component

- scopes/component/checkout/checkout-cmd.ts
- scopes/component/snapping/tag-model-component.ts
- scopes/lanes/lanes/lane.cmd.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/lanes/lanes/lanes.spec.ts
This is a continuation of the Lane History feature. See https://github.com/teambit/bit/pull/8370.
It's still hidden under a feature flag until the remotes are updated.
> feat, introduce a new command "bit lane checkout" to checkout to a previous lane snapshot

- scopes/scope/importer/import-components.ts
- scopes/scope/importer/importer.main.runtime.ts
It never supported multiple lanes, and having this prop as an array made it complex for no reason.
> refactor(ImportComponents), changes "lanes" props to work with one lane

- e2e/harmony/checkout-harmony.e2e.ts
- scopes/component/checkout/checkout-cmd.ts
- scopes/component/checkout/checkout-version.ts
- scopes/component/checkout/checkout.main.runtime.ts
The `--auto-merge-resolve [ours, theirs, manual]` flag of `bit checkout` handles cases when conflicts were found during the merge. 
In some cases, a component needs to be written according to "theirs" or "ours" regardless of the conflict state. These new two flags take care of this.
> improvement(checkout), introduce --force-ours and --force-theirs flags

- workspace.jsonc
This PR reverts the peer dep `"@teambit/base-react.navigation.link"` to 2.0.27 from 2.0.31, which fixes the issue with multiple instances of it existing at runtime - resulting in ActualLinks (React Router) being rendered as Native Links.
> fix(Workspace): revert navigation link to 2.0.27

- scopes/harmony/application/deploy.task.ts
- scopes/pipelines/builder/builder.main.runtime.ts
The issue happened when running `bit build --include-tag`, the deploy method was trying to get the artifacts from the builderData, which weren't populated yet. 
This PR provides the artifacts directly from the previous tasks.
> fix(build), provide artifacts from previous build tasks to app-deploy

- scopes/compositions/compositions/compositions.tsx
- scopes/preview/preview/preview.preview.runtime.tsx
This PR adds the ability to render the Component Preview in the full viewport height of the iframe. It adds a new query param; `fullscreen` which adds a height of`100vh` to the root div. It also sets the fullscreen query param in the Compositions page for a given Component.
> feat(Preview): fullscreen - allow rendering preview in full viewport height of the iframe

- scopes/component/snapping/snapping.main.runtime.ts
- src/scope/scope.ts
This is a regression caused by a recent optimization of not importing flattened-deps during snap.
One of the validations occurring during snap/tag on lane is that all direct dependencies are either part of the same lane or main. To check this we need the `ModelComponent` object, which was missing due to the optimization above.
This PR fixes it by adding the missing one to the "missingDeps" array which later gets imported.
> fix(snap), fix ComponentNotFound error thrown during isPartOfMainHistory check

- e2e/harmony/binary-files.e2e.ts
- e2e/harmony/checkout-harmony.e2e.ts
- e2e/harmony/lanes/lanes.e2e.ts
- e2e/harmony/merge-config.e2e.ts
- e2e/harmony/snap.e2e.2.ts
- scopes/component/checkout/checkout-cmd.ts
- scopes/component/merging/merge-cmd.ts
- scopes/lanes/merge-lanes/merge-lane.cmd.ts
It had been deprecated a few months ago along with `--ours` and `--theirs`. However, there is no need to deprecate the manual flag only the others which are going to get different functionality (see https://github.com/teambit/bit/pull/8397).
> reintroduce --manual flag to manually resolve conflicts

- scopes/scope/export/export.main.runtime.ts
This was needed in the past when the original ModelComponent consisted of the name only and a symlink object was created with the same hash. Currently that ModelComponent always has the scope-name it's not needed anymore.
(the trigger of this change was an unclear scenario where the model-component wasn't there after hitting Ctrl+C during export).
> do not delete ModelComponent objects during export

- scopes/component/checkout/checkout-cmd.ts
- scopes/component/merging/merge-cmd.ts
- scopes/lanes/lanes/switch.cmd.ts
- scopes/scope/importer/import-components.ts
- scopes/scope/importer/import.cmd.ts
- add a consistent separator `\n\n` between output sections (until now, each section needed to decide about the prefix and suffix new lines).
- clarify the "up to date" output of bit-import to specify whether it's up to date on the lane.
> align the output of checkout/merge/import/switch

- scopes/scope/importer/import-components.ts
- scopes/scope/importer/import.cmd.ts
- scopes/scope/importer/importer.main.runtime.ts
With this flag it'll show the list of the found dependents before importing them and will ask the user whether or not to continue with the import.
> improvement(import), introduce a new flag --dependents-dry-run

- scopes/scope/importer/import-components.ts
- scopes/workspace/workspace/workspace.ts
For example, instead of running `bit import teambit.workspace/eject` you can run `bit import @teambit/eject`. 
The change is done in `workspace.resolveComponentId`, so it affects many places the string id is converted to `ComponentId`, including when parsing patterns, which many (if not most) commands use. 
There is no way to parse the id from the package-name because a component can have a custom package-name. 
To resolve the ComponentID, it first searches locally for the package.json of that package and if found, uses the `componentId` prop. 
Otherwise, it makes a call to the registry to get the manifest and searches the `componentId` there.
> improvement(cli), support specifying package names instead of component-ids in many commands

- .bitmap
- .circleci/config.yml
- pnpm-lock.yaml
- scopes/component/component-descriptor/component-descriptor.spec.ts
- scopes/component/snapping/snapping.spec.ts
- scopes/defender/eslint/component.json
- scopes/dependencies/dependency-resolver/apply-updates.spec.ts
- scopes/dependencies/dependency-resolver/get-all-policy-pkgs.spec.ts
- scopes/dependencies/dependency-resolver/policy/env-policy/validate-env-policy.spec.ts
- scopes/dependencies/pnpm/pnpm-error-to-bit-error.spec.ts
- scopes/harmony/aspect-loader/core-aspects.spec.ts
- scopes/harmony/cache/cache.spec.ts
- scopes/lanes/lanes/lanes.spec.ts
- scopes/preview/preview/bundler/create-peer-link.spec.ts
- scopes/react/react-native/component.json
- scopes/semantics/schema/schema.spec.ts
- scopes/typescript/typescript/dedupe-path.spec.ts
- scopes/typescript/typescript/transform-source-file.spec.ts
- scopes/ui-foundation/ui/component.json
- scopes/workspace/install/pick-outdated-pkgs.spec.ts
- scopes/workspace/workspace-config-files/dedup-paths.spec.ts
- workspace.jsonc
- refactor(core-aspects) - update core aspect env to use mocha by default
- bump core aspect env version
- refresh circle cache for core aspect env
- migrate all core aspects (except deps-resolver) to use Mocha
- install chai-subset
> refactor(core-aspects) - update core aspect env to use mocha by default

- scopes/dependencies/dependency-resolver/manifest/deduping/index-by-dep-id.ts
- scopes/dependencies/dependency-resolver/policy/workspace-policy/workspace-policy-factory.ts
- We used to have a behavior that when installing on the root node_modules we will use the deduped versions from the workspace components, over the root policy.
In case we want to "force" the root policy we used to have `preserve` as a config for root policy entries.
something like:
```
"teambit.dependencies/dependency-resolver": {
"packageManager": "teambit.dependencies/pnpm",
"policy": {
"dependencies": {
"lodash": {"version": "1.0.0", "preserve": true}
}
}
}
```
This behavior was changed at some point to always prefer the root policy versions on the root node_modules (making the `preserve` config redundant).
But the new behavior got broken at some point so we go back to the old one.
This PR changes the preserve default value to `true` to fix this regression in a "more" safe way.
With …
> change(install) - prefer root policy versions for root node_modules installation

- e2e/harmony/lanes/bit-reset-on-lanes.e2e.ts
- src/scope/repositories/sources.ts
Here is a scenario where this was an issue: `scope-a/comp` was imported to the workspace, a new lane was created on another scope: `scope-b/dev` and this component was changed and snapped so it became part of the lane. 
Then, `bit reset` was running which changed the head on the lane to be the same as main. Now `bit export` throws an error saying `scope-a/comp` doesn't exist. This is because the lane-object included this component but this component wasn't sent to the remote as it wasn't staged. 
This PR fixes it by removing the component from the lane during the reset command. Because the component doesn't exist on the remote-lane and its head is the same as main, no reason to keep it on the lane.
> fix(reset), remove from lane if was reset to main and not exist on remote-lane

- scopes/cloud/cloud/cloud.main.runtime.ts
- scopes/cloud/models/cloud-user/cloud-user.model.ts
- scopes/cloud/ui/current-user/current-user.tsx
- scopes/cloud/ui/user-bar/user-bar.tsx
This PR handles the case where the properties of the CurrentUser response from the API are null, so that it matches the signature of what UserAvatar component expects. Previously, it would throw the error, `cannot read properties of null reading '0' `
> fix(UI/CurrentUser): handle null values for current user response

- scopes/cloud/cloud/cloud.ui.runtime.tsx
- scopes/cloud/ui/user-bar/user-bar.tsx
This PR fixes the warning thrown by react at runtime about duplicate keys for the Current User menu item registered by the Cloud UI Runtime in the User Bar and in the Component Menu.
> fix(Cloud UI): duplicate render keys

- scopes/react/eslint-config-bit-react/bit-react-eslint.js
- disable eslint react rules which are not relevant for React TS components:
- disable `react/prop-types`
- disable `react/require-default-props`
> improvement(esilnt-config) - disable react eslint rules which are not relevant for TS components

- scopes/dependencies/dependencies/dependencies-loader/auto-detect-deps.ts
- scopes/dependencies/dependencies/dependencies-loader/dependencies-versions-resolver.ts
Currently, it is saved with the snap-prefix inside the component `dependencies` array incorrectly.
> fix(deps-resolver), resolve snap versions coming from overrides without the snap-prefix (0.0.0-)

- scopes/dependencies/dependencies/dependencies.main.runtime.ts
- scopes/dependencies/dependencies/dependencies.spec.ts
`bit deps set` saves the data into the `policy` of the dependencies resolver config, which accepts package name and a valid Semver. Users are not aware of the prefix added to the package version of snaps, so running `bit deps set pkg-name@snap-hash` result in saving the version as the snap-hash in the objects, which later fails the installation.
This PR adds the `0.0.0-` prefix to the snap hash to make it a valid Semver.
> fix(deps-set), add snap prefix (0.0.0-) to the version in .bitmap if needed

- scopes/preview/preview/preview.main.runtime.ts
- src/api/consumer/lib/feature-toggle.ts
This PR adds a global feature flag `only-overview` to enable the new Overview section which only renders the docs and mounts the Compositions and API Reference outside of the iframe.
> feat(Preview): onlyOverview global feature flag

- scopes/component/renaming/renaming.main.runtime.ts
- scopes/component/renaming/renaming.spec.ts
This is a regression caused by https://github.com/teambit/bit/pull/8456.
When renaming a component with a namespace it was emitting the namespace, which resulted in ComponentNotFound error.
Also, it was loading the components after the rename before changing their env in case the env was renamed as well.
Both issues are fixed in this PR.
> fix(rename-scope), keep the namespace when renaming scope

- scopes/pipelines/builder/builder.main.runtime.ts
For example, it's possible for `teambit.harmony/application` aspect to use the `build_application` task for both: build pipeline and tag pipeline. The artifacts it is generating are different and have a different name. This PR fixes the `_tag` command to keep both artifacts.
> fix(tag-from-scope), avoid overriding artifacts with the same task-id and task-name if their artifacts name is different

- scopes/component/component-compare/component-compare.ui.runtime.tsx
- scopes/pipelines/builder/artifact/artifact-factory.ts
We use `globby` package to resolve paths from the artifacts definition.
The `app-bundle` artifact has `'artifacts/app-bundle'` pattern on linux/mac but `artifacts//app-bundle` on Windows.
Turns out that globby [doesn't support Windows paths](https://github.com/sindresorhus/globby/issues/179). This PR changes the paths to Linux before sending to globby.
> fix(tag), save app artifacts into the objects on Windows

- scopes/semantics/schema/schema.main.runtime.ts
- scopes/semantics/schema/schema.task.ts
This PR adds a new config for `teambit.semantics/schema` aspect called `disabled` - which disables the extraction of schema during the build task and also disables extracting the schema ad hoc when queried from the workspace.
> feat(Schema): disable config - allow disabling schema task

- scopes/component/forking/forking.main.runtime.ts
This PR fixes the issue when forking a remote component with the `ast` flag. Previously, only the exports and imports would be refactored using the AST Transformers, leaving the variables and classes to be refactored using the default regex even with the flag. This PR fixes it by forwarding the options to the function `refactorVariableAndClasses`
> fix(forking): forward ast options flag when refactoring variables and classes

- scopes/compositions/compositions/compositions.tsx
- scopes/compositions/compositions/ui/compositions-panel/compositions-panel.tsx
This PR fixes the issue with navigating between component compositions and the code for it when on a specific version. With this fix, it takes in consideration the version from the URLParams when constructing the url to navigate to. 
https://github.com/teambit/bit/assets/8999604/fc4a7104-e23b-40c2-a045-6566696951c9
> fix(UI/Compositions): navigating when on a specific component version

- scopes/compilation/compiler/workspace-compiler.ts
- scopes/component/checkout/checkout.main.runtime.ts
- scopes/component/remove/remove.main.runtime.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
- scopes/lanes/diff/lane-diff-generator.ts
- scopes/lanes/lanes/switch-lanes.ts
- scopes/scope/export/export.main.runtime.ts
- scopes/scope/importer/dependents-getter.ts
- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/modules/node-modules-linker/node-modules-linker.ts
- scopes/workspace/workspace/workspace.ts
This was needed in the past mostly to convert `BitId` to `ComponentID`. Currently it's needed only to convert strings to `ComponentID`.
> refactor, remove resolveMultipleComponentIds when not needed

- scopes/harmony/bit/load-bit.ts
- scopes/harmony/testing/load-aspect/load-aspect.ts
- scopes/lanes/lanes/lanes.spec.ts
Otherwise, it needs to re-register them when `loadAspect` is called due to the clear-global-cache, and then it'll need teambit/harmony.bit as a dependency which is not ideal.
There is no reason to clear this cache, it's not gonna change during the life of the process.
> fix(testing/load-aspect), avoid clearing the core names cache

- scopes/component/renaming/renaming.spec.ts
- scopes/harmony/config/config.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
Instead, use the `cwd` from the config of `teambit.harmony/bit`.
Otherwise, when running tests on a different workspace, it loads the `Config` aspect with the workspace.jsonc of the bit repo. (to reproduce, run `bit test renaming` and notice how the workspace.jsonc of bit-repo is changed)
> fix(testing-load-aspects), avoid loading the config from process.cwd

- e2e/harmony/deprecate.e2e.1.ts
- scopes/component/component/component.ts
- scopes/component/deprecation/deprecate-cmd.ts
- scopes/component/deprecation/deprecation.fragment.ts
- scopes/component/deprecation/deprecation.main.runtime.ts
- scopes/scope/importer/import-components.ts
- src/consumer/component/components-list.ts
- src/scope/models/model-component.ts
Currently, `bit deprecate` marks the entire component as deprecated.
This PR introduces a new flag `--range` to specify which versions to deprecate. It accepts the same syntax of [Semver range](https://www.npmjs.com/package/semver#ranges).
> feat(deprecate), support deprecating a range of versions

- scopes/cloud/cloud/cloud.main.runtime.ts
- scopes/cloud/cloud/login.cmd.ts
- scopes/cloud/cloud/npmrc.cmd.ts
This PR adds a new command `bit npmrc generate` - that allows users to update the npmrc scope, registry and token configuration from bit cloud. It also allows passing a `--dry-run` flag to output the configuration that will be updated. 
If the user is not logged in, it prompts the user to login and then updates the config.
> feat(cloud): npmrc generate cmd

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/merging/merge-status-provider.ts
Currently it shows an unhelpful error: "Cannot read properties of undefined (reading 'isRemoved')".
> fix(lane-merge), handle a case when a component was locally deleted

- scopes/cloud/cloud/cloud.main.runtime.ts
- scopes/cloud/cloud/login.cmd.ts
- scopes/cloud/cloud/npmrc.cmd.ts
This PR adds the ability to detect conflicts in the npmrc while updating it during bit login and bit npm generate command. It allows the user to by pass the conflicts by using the `--force` flag. If the `--force` flag is not used, it prompts the user to confirm before overriding the npm config to allow them to either continue or abort the process.
> feat(Cloud): handle npmrc conflicts

- scopes/component/graph/component-id-graph.ts
- scopes/component/graph/index.ts
- scopes/dependencies/dependencies/dependencies-cmd.ts
- scopes/dependencies/dependencies/dependencies.main.runtime.ts
- scopes/scope/scope/scope.main.runtime.ts
`bit deps get` was using the legacy graph and wasn't getting all the deps for some reason, also it was throwing an error when running it outside a workspace. 
This PR uses the `getGraphIds` API which is available in both Workspace and Scope.
> fix(deps-get), include all flattened deps according to the get-graph-ids API

- scopes/harmony/config/workspace-template.jsonc
This PR updates the comment on the generators config in the workspace config template. It prompts the user to run `bit install` after uncommenting the environment in the generator config to make them available in the workspace.
> fix(ws-config-template): update comment to prompt user to run bit install after uncommenting generators

- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
Until now this method was always falling back to importing all flattened dependencies to build the graph. The reason is that it relied on `consumerComponent.flattenedEdges` which in most cases is not populated.
This PR works with the `Version` object directly to get the data.
> perf, fix scope.getGraphIds to use the saved flattenedEdges

- scopes/lanes/lanes/lanes.graphql.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- src/scope/models/lane.ts
- src/scope/models/model-component.ts
- src/scope/repositories/sources.ts
See https://github.com/teambit/bit/pull/8534 for more info about update-dependents.
This PR adds a new GraphQL query to allow removal of some or all components from the `updateDependents` prop.
An example to remove all:
```
query Lanes {
lanes {
removeUpdateDependents(laneId: "gfruwtu9-remote/dev")
}
}
```
An example to remove one id:
```
query Lanes {
lanes {
removeUpdateDependents(laneId: "gfruwtu9-remote/dev", ids: ["gfruwtu9-remote/comp2"])
}
}
```
> add a GraphQL query to remove updateDependents from the lane object

- e2e/harmony/snap-from-scope.e2e.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- src/api/scope/lib/fetch.ts
- src/scope/component-ops/scope-components-importer.ts
- src/scope/models/lane.ts
- src/scope/objects-fetcher/objects-fetcher.ts
- src/scope/repositories/sources.ts
When checked out to a lane and running `bit import <id>` of a component included in the `updateDependents` prop of the lane, don't bring it from there. Fetch it from main instead. Only once it's snapped, add it to the lane. It's ok that in this point, the component exists in both: `components` array and `updateDependents` array of the lane. Later, once this lane object is merged into the remote, it'll be removed from the `updateDependents` array and it'll be only in `components`. This removal needs to be done on the remote, because only the remote makes changes in this array unless it gets "overrideUpdateDependents" flag, which enabled by snap-from-scope only.
I was trying first to go with the approach of importing the component from the lane. However, it breaks in so many places. For …
> fix, handle the case when importing a component from updateDependents into the workspace

- scopes/component/snapping/generate-comp-from-scope.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/snapping.spec.ts
- scopes/workspace/testing/mock-workspace/index.ts
- scopes/workspace/testing/mock-workspace/mock-workspace.ts
- src/e2e-helper/e2e-scope-helper.ts
Until now, this prop was available only for components that were generated by this `_snap` command. This PR merges the deps with the previously existing ones so it won't override them for existing components'.
> improvement(snap-from-scope), support newDependencies for existing components

- scopes/workspace/workspace/workspace-component/comp-files.ts
- scopes/workspace/workspace/workspace.ts
It fixes an issue of showing an incorrect "modify" status in two places: `bit mini-status` and in the vscode extension.
> fix workspace.getFilesModification to compare against the current, not the head

- components/entities/semantic-schema/api-schema.ts
- components/renderers/class/class.renderer.module.scss
- components/renderers/type/type.renderer.tsx
- components/utils/group-schema-node-by-signature/group-schema-node-by-signature.ts
- components/utils/schema-node-signature-transform/schema-node-signature.transform.ts
- scopes/api-reference/renderers/grouped-schema-nodes-overview-summary/grouped-schema-nodes-overview-summary.module.scss
- scopes/api-reference/renderers/grouped-schema-nodes-overview-summary/grouped-schema-nodes-overview-summary.tsx
- scopes/api-reference/renderers/grouped-schema-nodes-summary/grouped-schema-nodes-summary.module.scss
- scopes/api-reference/renderers/schema-node-member-summary/function-node-summary.tsx
This PR adds an OverviewRenderer for Type node to support highlighting `@exports` type APIs
It also fixes the ordering of the member APIs extracted from Classes, Interfaces, Types, etc. (nodes that have members)
> fix(API Ref): tagged export support for type nodes

- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- scopes/scope/export/export.main.runtime.ts
- src/scope/models/model-component.ts
Previously, `collectVersionsObjects` had a bug, `ignoreMissingLocalArtifacts` didn't do anything, even when it was `false`, it was still ignoring local artifacts because `locallyChangedHashes.includes(versionObject.hash.toString())` always returned `false`. The `versionObject.hash.toString()` printed the hash method instead of the hash content. It's fixed to be `versionObject.hash().toString()` to make it work.
Because of the that bug, https://github.com/teambit/bit/pull/7119 was adding new flag `ignoreMissingExternalArtifacts` unnecessarily. It assumed that an error wasn't thrown because it was external which wasn't correct. In this PR this flag has removed.
In addition to this, when merging from scope and merging main to a lane, we can skip the import of the artifacts because once the …
> fix(merge-from-scope), do not throw an error about missing artifacts when merging main to a lane

- .bitmap
- components/ui/code-tab-page/code-tab-page.tsx
- components/ui/code-view/code-view.module.scss
- components/ui/code-view/code-view.tsx
- components/ui/code-view/index.ts
- components/ui/hooks/use-core-aspects/index.ts
- components/ui/hooks/use-core-aspects/use-core-aspects.tsx
- scopes/component/graph/index.ts
- scopes/dependencies/dependencies/dependencies-loader/auto-detect-deps.ts
- scopes/harmony/aspect-loader/aspect-loader.graphql.ts
- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
- scopes/typescript/typescript/typescript.extractor.ts
- workspace.jsonc
This PR adds the ability to navigate to imported components and packages from the Code View
https://github.com/teambit/bit/assets/8999604/403e1d60-2e1b-427c-8efa-774f41979c4f
> feat(Code): Navigate imported components and packages

- package.json
We had to fork chokidar in the [past](https://github.com/teambit/bit/pull/7915) because no release was in the horizon. Now that a new version was released we can change it back to the original package.
> chore: change back chokidar from "@teambit/chokidar" to chokidar

- scopes/component/snapping/generate-comp-from-scope.ts
- scopes/component/snapping/snap-from-scope.cmd.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/snapping.spec.ts
- scopes/component/testing/mock-components/mock-components.ts
- scopes/workspace/modules/node-modules-linker/node-modules-linker.ts
- scopes/workspace/testing/mock-workspace/mock-workspace.ts
- scopes/workspace/workspace/workspace-aspects-loader.ts
- scopes/workspace/workspace/workspace-component/component-status-loader.ts
- until now snap-from-scope supported only updating comp deps or adding new deps. this PR supports removing components/packages dependencies.
- clear components cache after linking. otherwise, mockComponents with more than one component fails to codemod (link-rewire).
- print the mocked workspace paths when `bit test` is running with `--debug` flag.
- don't try to "link" aspects that don't exist in the current workspace.
- don't clear the cache during link if no link was created.
> feat(snap-from-scope), support removing existing dependencies

- scopes/harmony/bit/load-bit.ts
See https://github.com/teambit/bit/issues/8487. 
When this property is missing, users get an obscure error. This PR explains about the missing props in workspace.jsonc.
> fix, show a descriptive error when "teambit.workspace/workspace" is missing from workspace.jsonc file

- e2e/commands/move.e2e.1.ts
- scopes/component/mover/mover.main.runtime.ts
- src/consumer/bit-map/bit-map.ts
- src/consumer/bit-map/component-map.ts
- src/consumer/component/exceptions/component-not-found-in-path.ts
Currently, in this case it throws `ComponentNotFoundInPath` error. This PR let bit change the rootDir of the component in the `.bitmap` file.
> fix(move), enable running "bit move" after manually moving a component on the fs

- e2e/flows/remote-commands-outside-workspace.e2e.2.ts
- scopes/component/component/component.main.runtime.ts
- scopes/component/component/show/show.cmd.ts
until now it was throwing `[component] error: host 'teambit.scope/scope' was not found` which is very confusing.
> improve the error when running bit-show when no host is available

- src/scope/models/version.ts
In case the `mainFile` is in a directory, e.g. `src/index.ts`, on Windows it throws an error:
> unable to save Version object of "my-scope/baz@0.0.1", the mainFile src\index.ts is invalid
This PR fixes it by converting it to Linux format.
> fix, convert mainFile to linux format before saving into the objects

- src/consumer/component-ops/components-diff.ts
This fixes a bug where an svg file downloaded from a Win machine was repeatedly shown as modified on Mac. Even after tag/snap/checkout-reset.
The reason is that when saving files into the objects, their EOF is converted to Linux (`\n`). The files on the FS on the other hand, stay the same. If they've `\r\n`, it'll stay this way. Then when sending both files to git to check the diff, it shows all lines as diff. 
This PR converts the `SourceFile` into a `Source` object which takes care of the Linux conversion and produces a hash, then if the hash is the same, it doesn't send them to git to check the diff.
> fix(diff), do not show diff when it differs only in the EOF char

- scopes/harmony/api-server/api-for-ide.ts
- scopes/workspace/watcher/watcher.ts
- scopes/workspace/workspace/workspace.ts
- src/scope/lanes/unmerged-components.ts
- src/scope/objects/repository.ts
Also, when clearing the cache, reload this unmerged.json file. 
With these changes, watchers such as "bit server" are up to date with this components during-merge.
> fix, clear cache when unmerged.json file is changed

- scopes/harmony/api-server/api-server.main.runtime.ts
- scopes/harmony/api-server/server.cmd.ts
- scopes/harmony/cli/command-runner.ts
- src/cli/command.ts
Some commands should never exit. Such as `bit watch` or `bit server` that helps IDE to communicate with bit.
Instead of hacking the `report` handler by waiting for the promise forever, this PR adds a new handler `wait`, which never exits the process.
> feat(cli), introduce "wait" handler for commands that never exit

- .bitmap
- scopes/dependencies/dependency-resolver/package-manager-legacy.ts
- scopes/dependencies/fs/linked-dependencies/linked-dependencies.ts
- scopes/toolbox/fs/link-or-symlink/create-link-or-symlink.ts
- scopes/toolbox/fs/link-or-symlink/index.ts
- src/e2e-helper/e2e-scope-helper.ts
- src/links/symlink.ts
- src/utils/index.ts
The name is changed as well because it doesn't do copy anymore. It only links (hard) or symlink.
> refactor, extract createSymlinkOrCopy to a new component teambit.toolbox/fs/link-or-symlink

- .bitmap
- scopes/dependencies/dependency-resolver/policy/workspace-policy/workspace-policy.ts
- scopes/toolbox/object/sorter/index.ts
- scopes/toolbox/object/sorter/sort.ts
- src/consumer/bit-map/bit-map.ts
- src/consumer/config/extension-data.ts
- src/consumer/consumer.ts
- src/utils/index.ts
`@teambit/toolbox.object.sorter`
> refactor, extract sort-object into a new component

- src/scope/component-ops/export-scope-components.ts
- src/scope/models/model-component.ts
- src/scope/repositories/sources.ts
Otherwise, it'll log confusing errors about missing Component objects.
Also, add some logs around the update of VersionHistory to debug issues with the remotes when some data is missing.
> fix(sign), do not try to update VersionHistory during bit sign

- scopes/component/snapping/snapping.main.runtime.ts
In some cases, when snapping it throws "component X missing data. parent <hash> of version <hash> was not found.".
This PR fixes it by adding this type of error to the catch statement that aggregate all these components and import them with their VersionHistory.
> fix(snap), import VersionHistory when ParentNotFound is thrown

- components/renderers/react/react.renderer.tsx
- components/renderers/schema-nodes-index/schema-nodes-index.tsx
- components/ui/component-filters/env-filter/envs-filter.tsx
- components/ui/menus/use-lanes-menu/use-lanes-menu.tsx
- components/ui/version-block/version-block.tsx
- scopes/api-reference/overview/api-reference-table-of-contents/api-reference.table-of-contents.tsx
- scopes/api-reference/renderers/grouped-schema-nodes-overview-summary/grouped-schema-nodes-overview-summary.tsx
- scopes/api-reference/renderers/type-ref/type-ref.renderer.tsx
- scopes/api-reference/sections/api-reference-page/api-reference-page.tsx
- scopes/cloud/ui/login/login.tsx
- scopes/component/component/ui/top-bar-nav/top-bar-nav.tsx
- scopes/component/graph/ui/dependencies-compare/dependencies-compare.tsx
- scopes/component/graph/ui/dependencies-graph/dependencies-graph.tsx
- scopes/compositions/compositions/compositions.tsx
This PR silences the type errors when rendering the Link component from `teambit.base-react/navigation/link` or `@teambit/design.ui.navigation.link` along with errors from react-flow-renderer when using the Handle component
These issues will be fixed as part of the upcoming PR which updates these deps to the latest
> temporarily ignore ts errors for Link and Handle

- e2e/harmony/import-harmony.e2e.ts
- scopes/component/graph/component-id-graph.ts
- scopes/scope/importer/dependents-getter.ts
- scopes/scope/importer/import-components.ts
- scopes/scope/importer/import.cmd.ts
Still, this is not a complete list of all paths, which can be huge and take very long to calculate (it's an NP-Hard problem).
To be able to run it in a reasonable amount of time, it's using "visitor" which helps to run each node only once. 
However, this visitor caused a bug in the following scenario: 
A -> B1 -> D -> E
A -> B2 -> D -> E
The traversal was done using DFS, so it started with A -> B1 all the way to E. Then, because D is already visited, it was skipping the other path [A, B2, D, E]. 
This PR uses BFS instead and the check for visited is done before adding to the queue. 
The end result is not only more paths, but also shorter and more relevant paths due to the BFS nature.
> fix(import-dependents), fix algorithm to get some missing paths

- scopes/ui-foundation/ui/start.cmd.tsx
> fix(bit start) - show ui server loader success when using --no-browser

- scopes/harmony/api-server/api-for-ide.ts
- scopes/lanes/lanes/lane.cmd.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/lanes/lanes/lanes.spec.ts
- scopes/lanes/lanes/switch-lanes.ts
- scopes/lanes/lanes/switch.cmd.ts
To get the previous default, use the newly introduced `--workspace-only` flag
> deprecate --get-all of bit-switch and make it the default

- e2e/harmony/lanes/merge-lanes-from-scope.e2e.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- src/scope/component-ops/scope-components-importer.ts
otherwise, when merging from main and objects are missing from the lane-scope for some reason, it fails to find them.
> fix(merge-from-scope), avoid using shouldOnlyFetchFromCurrentLane

- scopes/workspace/watcher/watcher.main.runtime.ts
(currently it shows an unhelpful error "Cannot read properties of undefined (reading 'path')").
> fix(watch), throw a descriptive error when running outside a workspace

- scopes/harmony/cli/cli-parser.ts
- scopes/harmony/cli/cli.cmd.ts
- scopes/harmony/cli/cli.main.runtime.ts
- scopes/harmony/cli/command-runner.ts
- scopes/harmony/cli/yargs-adapter.ts
Helps to interact with a command before it starts. One example (asked in community slack channel) is to manipulate the snap/tag message. The following is an example how it can be done with this slot:
1. create a new bit-aspect: `bit create bit-aspect my-aspect`.
2. replace the content of the my-aspect.main.runtime.ts with the following.
```
import { MainRuntime, CLIAspect, CLIMain } from '@teambit/cli';
import { MyAspectAspect } from './my-aspect.aspect';
export class MyAspectMain {
static slots = [];
static dependencies = [CLIAspect];
static runtime = MainRuntime;
static async provider([cli]: [CLIMain]) {
cli.registerOnCommandStart(async (commandName, args, flags) => {
if (commandName === 'snap' && flags.message) {
flags.message = `${flags.message} world!`;
}
});
return new …
```
> improvement(cli), introduce onCommandStartSlot

- scopes/workspace/workspace/workspace.ts
It's easy to mistakenly replace the first arg (comp) with the second arg (env) and then unclear errors are thrown. This PR throws an error immediately during `bit env set` if the second arg is not an env.
> fix(env-set), validate that the second arg is indeed an env

- scopes/generator/generator/exceptions/workspace-path-exists.ts
- scopes/generator/generator/generator.main.runtime.ts
- scopes/generator/generator/workspace-generator.ts
currently this check is done late in the process after aspects are loaded which can be frustrating.
> fix(new), fail fast when the specified path exists

- scopes/compilation/compiler/workspace-compiler.ts
- scopes/workspace/watcher/output-formatter.ts
- scopes/workspace/watcher/watch.cmd.ts
- scopes/workspace/watcher/watcher.ts
This `formatCompileResults` was implemented incorrectly. The watcher was building the output of the compiler based on unknown data. 
In this PR, the compiler formats its own data and returns the formatted data to the `toString()` method in `OnComponentEventResult` type as intended originally. This way, each aspect can have its own formatting and as long as it implements `toString()`, it can be shown in the output.
> make watch output more compact, refactor formatCompileResults to use toString()

- scopes/dependencies/pnpm/lynx.ts
> fix: never install @teambit/legacy as a dependency

- package.json
- scopes/scope/version-history/version-history-cmd.ts
- src/scope/graph/vizgraph.ts
- workspace.jsonc
Until now to generate a graph (either for Version History or for dependencies), the GraphViz library had to be installed in the OS, which made it cumbersome especially for Windows. 
This PR uses [viz-js](https://github.com/mdaines/viz-js) package which is basically an implementation of Graphviz in javascript. It doesn't support png/gif formats, but it does support "svg" which is superior for such graphs that can be huge. (with png trying to zoom in result in a blurry image). 
In this PR, the `bit version-history graph` command defaults to this new alternative and a new flag `--png` falls back to GraphViz.
Later, the dependency graph will be updated as well.
> improvement(version-history), enable generating graph as SVG without installing graphviz

- workspace.jsonc
This is only relevant for the warnings on this repo specifically, and not affecting bit's users
> chore(outputs) - ignore @teambit/legacy and typescript warnings on bit install

- scopes/workspace/modules/node-modules-linker/node-modules-linker.ts
- src/consumer/component/component-fs-cache.ts
currently when compiling even one component, the link process deletes all FS cache (dependencies cache) of all components. It seems to be unnecessary. This PR deletes the caches of the linked components only.
> perf, avoid deleting all components cache when one component is linked/compiled

- scopes/pkg/pkg/publisher.ts
> fix: reporting publish error messages

- scopes/lanes/lanes/switch-lanes.ts
- scopes/workspace/workspace/workspace.ts
This `workspace.listIds` in the past was converting legacy ids to ComponentIDs so it needed a cache. Now that legacy also using ComponentIDs, no need for this cache. It got removed in this PR.
> fix(switch), fix an installation error due to outdated versions from workspace.listIds

- scopes/harmony/aspect/aspect.env.ts
- scopes/react/react/react.env.ts
- This was originally added to the npmignore to resolve issues with core aspects. but since core aspects have now their own dedicated env it's not needed anymore for other aspects.
> change(aspect-env) - do not ignore *.ts files from aspect's packages

- scopes/harmony/cli/command-runner.ts
- scopes/workspace/workspace/workspace-aspects-loader.ts
- scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
- scopes/workspace/workspace/workspace.ts
- src/logger/logger.ts
With this PR, you can pass `--log=profile` to a command to print only the profile messages. 
It helps to understand what takes time during components load.
> add some profiling around component-loading, enable --log=profile to see this data

- scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.ts
When the same package is in dependencies twice with different versions, always hoist the one with the biggest version.
-
-
-
> fix: make hoisting deterministic

- scopes/component/component/component-factory.ts
- scopes/component/component/component.ts
- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
It helps to get the dependencies without having to inject the `DependencyResolver` aspect, which in many cases it's not trivial.
> add a new API "getDependencies()" to Component

- scopes/cloud/cloud/login.cmd.ts
This PR allows the user to refresh their token during bit login when they have already logged in before.
> feat(login): allow refreshing token during bit login when already logged in

- scopes/cloud/cloud/login.cmd.ts
This PR adds a new flag to the bit login cmd `--refresh-token` that re logins the user and refreshes the token even when the user is already logged in without prompting any confirmation.
> feat(login): flag `refresh-token` to allow force refreshing token during bit login when already logged in

- e2e/harmony/lanes/bit-remove-on-lanes.e2e.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/lanes/merge-lanes/merge-lane-from-scope.cmd.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- src/e2e-helper/e2e-command-helper.ts
Currently the code that merges from scope is different than the one on the workspace (except when merging main to a lane).
As a result, the change done in the last few months of allowing `--update-main` flag during bit-delete was supported only in the workspace. On the scope, it was just ignoring the component, assuming it was deleted and should not be merged.
This PR reuses the merge on the workspace instead of having different code on the scope, which as a result, merges those deleted components with "update-main" prop.
> fix(merge-from-scope), merge components that were deleted with --update-main

- src/api/consumer/lib/doctor.ts
- src/cli/commands/public-cmds/doctor-cmd.ts
- ignore public folder by default 
- add `--include-public` arg to the doctor command to include public folder
- ignore local `git` repo directory from `bit doctor --archive`
- ignore internal/nested `node_modules` folders in `bit doctor --archive`
- ignore `.DS_Store` file in `bit doctor --archive`
> improvement(doctor) - remove some folders from bit doctor --archive

- scopes/harmony/cli/command-runner.ts
- src/bootstrap.ts
- src/logger/logger.ts
It's useful for CIs.
To disable console printing during command execution: `BIT_DISABLE_CONSOLE=true`.
To disable the spinner/loader: `BIT_DISABLE_SPINNER=true`.
> allow disabling console and spinner in the CLI output

- scopes/component/isolator/capsule-list.ts
This is needed for the typescript-compiler in order to check whether it has circular dependencies.
> add a new API "getGraphIds" to CapsuleList

- scopes/harmony/logger/logger.ts
- scopes/pipelines/builder/build-pipe.ts
When registering to process.on with exit signals, Typescript doesn’t exit the process until it executes the code that registered to this event.
Because typescript programatic API is sync and JS is single threaded, it’s blocked until TS completes the build and only then it can execute the code registered to the exit event.
In the past, Ora (the spinner) pkg caused it and it was solved by instantiating it with `hideCursor: false`. Tuned out the reason it fixed it is because this option when it’s true, it calls `cliCursor` package to hide the cursor. This package, is calling `restore-cursor` package which calls `signal-exit` package to register to exit events to make sure the cursor is restored when exiting the node process.
The reason we had the same issue now is that we had two places we …
> allow exiting (Ctrl+C) during typescript-compiler step in build pipeline

- components/component-issues/issues-list.ts
In many cases, the component-issue is installed as a package in different places, causing the `instanceof` to always return `false`. Instead, change the implementation of `getIssue` to use the `getIssueByName`.
> fix, avoid using instanceof to find a component-issue

- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
- scopes/scope/scope/scope-aspects-loader.ts
> fix(envs-loading) - fix loading an env with external (non core) env from global scope

- scopes/component/graph/component-id-graph.ts
- scopes/explorer/insights/all-insights/find-circulars.ts
By doing the following two:
- reverse the order of the components to start from the dependents to the dependencies
- add the first item to the last to help understanding the circular.
For example, imagine the following circular: A1 -> B1 -> B2 -> A1 (read as A1 uses B1).
Before
```
Cyclic dependency
-----------------
- f46b89d0-remote/comp/b2@0.0.1
- f46b89d0-remote/comp/b1@0.0.1
- f46b89d0-remote/comp/a1@0.0.1
```
Now
```
Cyclic dependency
-----------------
- f46b89d0-remote/comp/a1@0.0.1
- f46b89d0-remote/comp/b1@0.0.1
- f46b89d0-remote/comp/b2@0.0.1
- f46b89d0-remote/comp/a1@0.0.1
```
> improvement(insights), make the circular dependencies output clearer

- scopes/lanes/lanes/switch.cmd.ts
This is also needed because in case of a conflict it throws an error with the following message:
> please use “--auto-merge-resolve” with ‘manual’, ‘ours’ or ‘theirs’ to resolve the conflict/s
which was correct for many commands such as `bit checkout`, `bit lane merge`, but not for `bit switch`.
> fix(switch), rename --merge to --auto-merge-resolve to be aligned with other commands

- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/watcher/watch.cmd.ts
- scopes/workspace/watcher/watcher.ts
Helpful when using git.
It resolves the following issue - a user is running `git pull` which updates the components and the .bitmap file. Because the objects locally are not updated, the .bitmap has new versions that don't exist in the local scope. As soon as the watcher gets an event about a file change, it loads the component which throws `ComponentsPendingImport` error.
To resolve this, the new `--import` flag imports the new objects as soon as the .bitmap file changes. For performance reasons, we import only when: 1) the .bitmap file has version changes and 2) this new version is not already in the scope.
> feat(watch), introduce --import to fetch objects on .bitmap change

- e2e/harmony/delete.e2e.ts
- scopes/component/snapping/tag-model-component.ts
In case compA is using compB on a lane and compB got deleted and installed as a package from main, `bit snap` was changing back the version of compB to the deleted one instead of the version from main.
This PR fixes it to keep the version from main.
> fix(snap), keep the dependency version of a deleted component as the user intended

- e2e/harmony/init-harmony.e2e.ts
- scopes/harmony/bit/load-bit.ts
- scopes/harmony/config/config.main.runtime.ts
- scopes/harmony/testing/load-aspect/load-aspect.ts
- scopes/workspace/workspace/workspace.ts
- src/consumer/config/workspace-config.ts
- src/consumer/consumer-locator.ts
Currently, if the worksapce.jsonc is missing, it throws an unclear error:
> workspace.jsonc is missing the "teambit.workspace/workspace" property
And `bit init` doesn't fix it.
Now, the error is clearer:
> fatal: workspace config is empty. probably one of bit files is missing. consider running "bit init"
And running `bit init` rewrite the file.
> fix(init), rewrite workspace.jsonc if missing

- scopes/scope/scope/scope.main.runtime.ts
- src/global-config/config.ts
This is especially useful when using the vscode extension to have the config up to date, so that changes like bit-login/logout are taking place.
> fix(watch/ide), invalidate global-config cache upon change

- scopes/ui-foundation/ui/webpack/webpack.base.config.ts
- scopes/ui-foundation/ui/webpack/webpack.browser.config.ts
- scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
This PR adds the polyfills required for @pnpm/node-fetch which replaced cross-fetch in graphql.ui.runtime. With this bit start now runs without any errors.
> fix(UI): add polyfills for @pnpm/node-fetch 

- scopes/ui-foundation/ui/webpack/webpack.base.config.ts
- scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
This PR fixes the issue with component compare not rendering configuration diffs. The issue was because of multiple versions of `@teambit/component.ui.component-compare.context` at runtime. This fix adds a webpack alias for `@teambit/component.ui.component-compare.context` ensuring there is only one instance of the context at runtime.
> fix(compare): make component compare context single instance at runtime

- workspace.jsonc
Fixes #7477 
The change was done in this PR: https://bit.cloud/teambit/defender/~change-requests/fix-eol-win.
> fix(format), avoid replacing end-of-line character on Windows, keep them as you got them from Prettier.

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/merging/merging.main.runtime.ts
The scenario is as follows:
Lane-A has comp-X in the workspace.jsonc policy, it is not part of the lane. 
Lane-B has this comp-X as part of the lane. 
Lane-B is now merged into Lane-A.
This PR removes the entry of comp-x package from workspace.jsonc, so then this component doesn't exist in both: .bitmap and workspace.jsonc.
> fix(lane-merge), remove a package from workspace.jsonc policy if newly introduced during merge

- scopes/component/remove/delete-cmd.ts
- scopes/component/remove/remove.main.runtime.ts
- scopes/lanes/lanes/lane.cmd.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- src/e2e-helper/e2e-command-helper.ts
In many cases, the reason to remove a component from a lane is by realizing that there is no need to change the component, and it's perfectly fine to use it from main. 
Until now, it required two commands: 1) `bit delete comp-x --lane` and 2) `bit install comp-x-pkg`. 
Without the installation of the package, `bit status` was complaining (rightfully so) about using deleted components. 
This new command `bit lane eject` is practically a sugar of executing the two commands above.
> feat, introduce a new command "bit lane eject" to delete from lane and install as package

- scopes/component/isolator/isolator.main.runtime.ts
The capsule base-dir is normally a `sha1` of the workspace/scope dir, which is 40 chars long. Problem is that Windows is not happy with long paths.
This PR uses a shorter hash. The number 9 is pretty random, it's what we use for short-hash of snaps.
We're aware of an extremely low risk of collision. Keep in mind that in most cases you won't have more than 10 capsules in the machine, so it's fine.
> shorten the capsule dir

- e2e/harmony/checkout-harmony.e2e.ts
- e2e/harmony/component-config.e2e.ts
- scopes/component/component-writer/component-writer.main.runtime.ts
- scopes/component/component-writer/component-writer.ts
- scopes/workspace/workspace/component-config-file/component-config-file.ts
- scopes/workspace/workspace/workspace.ts
- src/consumer/component/json-vinyl.ts
- src/consumer/component/package-json-file.ts
currently, if there are local changes in the component.json (generated by `bit config eject-conf`), then `bit checkout reset` doesn't reset them. It leaves the file as is.
This PR refactors the way how this component.json file is saved to reuse the infrastructure we had for package.json (with indent and EOL taken into account). With this, it was easier to change the component-written command to make sure this file is written if it was there before.
> fix(checkout-reset), reset component.json if exists locally

- scopes/component/remove/remove-components.ts
Otherwise, the components that depend on these removed aspects are trying to load them, find out they don't exists, then trying to import them and throw an error "unable to import".
Because these removed aspects are new, there is no easy way to fix this. It's impossible to install them as packages.
This PR blocks it unless `--force` flag was used.
> fix(remove), block removal of new aspects that are used by other components

- scopes/api-reference/api-reference/api-reference.ui.runtime.tsx
- scopes/api-reference/overview/api-reference-table-of-contents/api-reference.table-of-contents.module.scss
- scopes/api-reference/overview/api-reference-table-of-contents/api-reference.table-of-contents.tsx
- scopes/api-reference/tagged-exports/tagged-exports.module.scss
- scopes/api-reference/tagged-exports/tagged-exports.tsx
- scopes/docs/docs/overview/overview.module.scss
- scopes/docs/docs/overview/overview.tsx
This PR fixes style issues with the API Reference Overview section. Specifically it fixes the following, 
- removes overflow when loading the overview - so the loading skeleton is not scrollable
- changes the layout of the table of contents of the APIs 
- only shows the `@exports` banner when on the workspace and align it to the left instead of the center
API Reference Table of Contents re design
> fix(Overview): API Reference overview section design fixes

- scopes/generator/generator/generator.main.runtime.ts
Otherwise, the code might have a class that extends itself. 
For example, `bit create node-env node-env` produces `class NodeEnv extends NodeEnv`.
Or `bit create react-env envs/react-env --aspect teambit.react/react-env` produces `class ReactEnv extends ReactEnv`.
> fix(create), block using component-name with the same name as the template name

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/lanes/merge-lanes/last-merged.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- scopes/lanes/merge-lanes/merge-move.cmd.ts
- src/e2e-helper/e2e-command-helper.ts
This command is useful when you got a messy merge state that from one hand you don't want to loose the changes, but on the other hand, you want to keep your lane without those changes.
This command does the following:
1. create a new lane with the current merge state. including all the filesystem changes. (in practice, it leaves the fs intact).
2. reset the current lane to the state before the merge, so then once done with the new lane, you can switch to the current lane and it'll be clean.
> feat(lanes), introduce a new sub-command "merge-move"

- e2e/harmony/lanes/bit-import-on-lanes.e2e.ts
- scopes/scope/importer/import-components.ts
We used to throw an error suggesting the user to import the components individually. The reason was that when you're on a lane, you probably want to import components from the lane. not main. That's why when the wildcard matches both, lane and main, only the lane are imported.
However, if only components from main are matched, it's not very clear whether you really want to import from lane, or your wildcard syntax didn't bring the results you thought it would.
With this PR we assume that in this case you do want to import from main so we let you do that.
> improvement(import), allow importing main components with wildcard when on a lane

- scopes/scope/scope/scope.graphql.ts
- scopes/scope/scope/scope.main.runtime.ts
- src/remotes/remote.ts
- src/scope/component-ops/scope-components-importer.ts
- src/scope/network/fs/fs.ts
- src/scope/network/http/http.ts
- src/scope/network/network.ts
- src/scope/objects/repository.ts
This will be actually used once remotes are updated and support the new GraphQL query.
An example of this query:
```
query HasObjects {
scope {
hasObjects(hashes: ["075b5e1d5ab0c81e6a17648cbe966091c8d9bfb1", "075b5e1d5ab0c81e6a17648cbe966091c8d9bfb2"])
}
}
```
and a result could be:
```
{
"data": {
"scope": {
"hasObjects": [
"075b5e1d5ab0c81e6a17648cbe966091c8d9bfb1"
]
}
}
}
```
> preparation for performance improvement by asking server for existence of objects rather than trying to fetch them

- scopes/scope/scope/scope.graphql.ts
Once deployed on the remote scopes, it can help a client in negotiating with the server and adjusting API compatibility.
Example:
```
query BitVer {
scope {
getBitVersion
}
}
```
Response
```
{
"data": {
"scope": {
"getBitVersion": "1.6.150"
}
}
}
```
> add a graphql query to get bit version of the remote scope

- scopes/component/renaming/renaming.main.runtime.ts
- scopes/harmony/config/workspace-config.ts
When the `bit scope-rename` (or `bit rename`) suppose to change multiple values in the workspace.jsonc, it was changing only the first one.
> fix(scope-rename), replace aspects properly in workspace.jsonc

- package.json
This PR removes the `package-json-validator` package from package.json
> chore: remove 3rd party `package-json-validator` package

- scopes/dependencies/dependency-resolver/dependency-resolver-workspace-config.ts
This PR updates the comment in the dependency resolver workspace comment which was the cause for triggering a false warning about  asymmetric private key vulnerability
> chore: fix false warning about asymmetric private key vulnerability

- scopes/component/component-compare/component-compare.main.runtime.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/scope/importer/importer.main.runtime.ts
This PR fixes the issue of missing component objects of versions that might be from main when comparing two component versions. With the fix, it now first tries to fetch the missing components objects for both base and compare component ids before diffing.
> fix(component compare): import missing objects from main 

- components/ui/code-compare/code-compare-view/code-compare-view.tsx
This PR fixes the bug in Code Compare when the container's height changes and we try to re size the modified editor's height. In some cases, the modified editor might not be still available which results in accessing the property of undefined error.
> fix(code compare): correctly update modified editor height when container resizes

- scopes/dependencies/dependencies/dependencies-loader/dependencies-loader.ts
- scopes/dependencies/dependencies/dependencies-loader/dependencies-versions-resolver.ts
In case the current lane has `updateDependents` prop (see https://github.com/teambit/bit/pull/8534 for more info) , the dependencies versions are resolved from there.
> resolve dependencies versions from updateDependents prop if exists

- src/scope/models/version.ts
In the legacy it was completely based on hashing part of the content. Since Harmony, only tag (not snap) used this calculation and only for the first time. Once generated, the hash was saved as part of the object and was used purely by the hash prop and not by the calculation.
This PR completes the transition by aligning tag and snap and always auto-generating the hash by a random UUID. 
(the reason this was done now is because I have noticed a very rare occurrence when an e2e-test was creating two components with the exact same files and their tag hashes were identical. It's rare because part of the hash calculation based on the "log.date" which changes every second).
> change Version hash to be auto-generated and not based on content

- e2e/harmony/merge-config.e2e.ts
- scopes/component/merging/merge-cmd.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/workspace/config-merger/aggregated-deps.ts
- scopes/workspace/config-merger/config-merger.main.runtime.ts
- src/scope/models/version.ts
When merging a lane and components of that lane has different dependencies versions of workpsace.jsonc, we update workspace.json accordingly.
An exception occurs when different lane components use different versions of the same dependency. 
This PR addresses these cases by detailing in the output which component uses which version.
> improvement(lane-merge), clarify reasons for not updating dependencies in workspace.jsonc

- src/scope/models/model-component.ts
Fixes an issue when on a lane and a dependency from within the lane is deleted. In case the user installed the main version, `bit status` should not warn about using removed dependencies.
> fix(status), do not show RemovedDependencies issue when main version is used

- scopes/component/remove/remove.main.runtime.ts
Currently, in case the exact dependency version is not in the objects, it doesn't get the removed data. With this change, it's enough to have the ModelComponent there.
> fix, show RemovedDependencies issue more consistently

- scopes/harmony/bit/app.ts
- scopes/harmony/bit/autocomplete.ts
- src/scope/models/version.ts
- workspace.jsonc
The response feels almost instantaneous (0.07 seconds). 
It doesn't load any of the bit-core files. As soon as it detects autocomplete, it executes a separate file that doesn't import any bit-core internal files or packages.
Component IDs
Commands:
Flags:
> feat(cli), autocomplete component ids, commands, sub-commands and flags

- e2e/harmony/dependencies/env-jsonc-policies.e2e.ts
- scopes/component/dev-files/dev-files.main.runtime.ts
- scopes/component/dev-files/index.ts
- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/dependencies/dependency-resolver/policy/env-policy/env-policy.ts
- scopes/envs/envs/environments.main.runtime.ts
- scopes/envs/envs/index.ts
- src/e2e-helper/e2e-fixtures-helper.ts
- With this feature, you can now add new `"extends"` field in your env.jsonc
- You can use extends to extends an env.jsonc that extends another env.jsonc
- The value for `extends` should be the package name of the env you want to extend.
- You need to make sure to have that env you extend as a dependency of your env.
In the `patterns` object, each key will be overridden by the child as is (no internal merge of the arrays).
If you have a key in the parent that doesn't exist on the child it will be taken as is from the parent.
For each type of dependency (dev/peer/runtime), each object will be taken from the child by the name.
so if you have a dependency on peers in the parent like this:
```
// parent's env.jsonc
peers: [
{
name: 'react',
version: '^18.0.0',
supportedRange: '^18.0.0',
},
] …
```
> feature(envs) - support new "extends" field in env.jsonc

- scopes/harmony/bit/load-bit.ts
This change instructs browserlist to not print the following warning:
> Browserslist: caniuse-lite is outdated. Please run:
>   npx update-browserslist-db@latest
>   Why you should do it regularly: https://github.com/browserslist/update-db#readme
This message is not helpful to our users. Running the package-manager directory is not recommended.
> remove "caniuse-lite is outdated" message

- src/constants.ts
Currently, LICENSE files are ignored for historical reasons which are not relevant anymore. This PR makes them trackable.
> track LICENSE files

- e2e/harmony/custom-env.e2e.ts
- scopes/component/component/component-factory.ts
- scopes/workspace/workspace/workspace.ts
Same issue currently exists when switching to another lane. It writes the env with the specific version, which can be incorrect and belong to the origin lane and not the current one.
> fix(eject-conf), remove env-version if exists locally in the workspace

- scopes/scope/importer/import-components.ts
- scopes/scope/importer/import.cmd.ts
The current `--dependencies` flag imports the dependencies with the same version they got saved in the given component. 
This new flag imports their head versions instead. In most cases this result in a better state, with all deps up-to-date.
> feat(import), introduce a new flag "--dependencies-head"

- src/consumer/component/component-loader.ts
When multiple components don't have the dependencies cache, we have to parse lots of files to get the dependencies.
In many cases, the same files are parsed for multiple components, so loading multiple components in parallel hurts the performance by making unnecessary FS calls.
This PR fixes it by falling back to serial loading in such cases.
> fix, avoid loading consumer-components in parallel when deps cache is missing for some

- e2e/harmony/checkout-harmony.e2e.ts
- scopes/component/checkout/checkout.main.runtime.ts
- scopes/component/component-writer/component-writer.main.runtime.ts
- scopes/workspace/config-merger/config-merger.main.runtime.ts
Currently, `bit checkout head` writes dependencies conflicts into workspace.jsonc even when `--auto-merge-resolve` was used (with either `ours` or `theirs`).
This PR uses the merge strategy to conclude whether a dependency should be updated.
> fix(checkout), respect --auto-merge-resolve flag when finding workspace.jsonc conflicts

- e2e/harmony/snap-from-scope.e2e.ts
- scopes/component/snapping/snapping.main.runtime.ts
- src/scope/scope.ts
Easier to explain with example: comp1 -> comp2 -> comp3. Snapping comp2 with `--update-dependents` saves comp2 inside the `updateDependents` prop of the lane with the comp3 dependency having the same version as in the lane.
Snapping comp3 now have the same effect. It saves comp2 with the version is has in the `updateDependents` prop.
> fix(snap-from-scope), support dependents recursively with --update-dependents

- scopes/defender/eslint/eslint.linter.ts
- scopes/defender/linter/lint.cmd.ts
- scopes/defender/linter/linter.ts
- show total instead of names for components with no lint issues
> improvement(bit-lint) - show total instead of names for components with no lint issues

- src/scope/models/version.ts
- src/scope/scope.ts
It's faster than checking history graph. Also, in some (unclear) cases when the history has missing parts, this check is more accurate. Keep in mind that this works only when the "origin" is set. (this prop was added a few months ago).
> fix, consider Version.origin to determine whether a snap is part of a lane

- scopes/component/status/mini-status-cmd.ts
- scopes/harmony/application/app.cmd.ts
- scopes/harmony/application/application.main.runtime.ts
- scopes/harmony/application/run.cmd.ts
Instead, before `bit app list` or `bit app run`, the apps components are loaded as aspects to have them registered to the apps slots.
> perf, imporove bootstrap performance by making it unnecessary to add apps to workspace.jsonc

- e2e/functionalities/peer-dependencies.e2e.3.ts
- scopes/component/component/component.ui.runtime.tsx
- scopes/explorer/command-bar/command-bar.button.module.scss
- scopes/explorer/command-bar/command-bar.button.tsx
- scopes/explorer/command-bar/command-bar.ui.runtime.tsx
- scopes/lanes/lanes/lanes.ui.runtime.tsx
- scopes/workspace/workspace/workspace.ui.runtime.tsx
- workspace.jsonc
This PR adds the CommandBarButton widget to trigger the universal search in the workspace, identical to how it behaves on bit.cloud.
> feat(commandBar): add commandbar widget to workspace

- src/bootstrap.ts
It was v18 before, which for some envs (e.g. html) was throwing an error due to the unsupported import.meta.
> change the recommended node version to be >=20.0.0

- src/cli/default-error-handler.ts
- src/consumer/consumer.ts
- src/scope/exceptions/scope-not-found.ts
currently it only shows an error saying the scope wasn't found.
> fix, suggest running "bit init" when local-scope is empty

- components/entities/semantic-schema/schemas/docs/tag.ts
- components/entities/semantic-schema/schemas/inference-type.ts
- components/renderers/api-node-details/api-node-details.module.scss
- components/renderers/api-node-details/api-node-details.tsx
- scopes/api-reference/renderers/parameter/parameter.renderer.tsx
- scopes/api-reference/renderers/schema-node-member-summary/variable-node-summary.tsx
- scopes/typescript/typescript/schema-extractor-context.ts
- scopes/typescript/typescript/transformers/parameter.ts
This PR adds the ability to extract @link from jsdoc comments and render them as part of the API Reference of the node. It also adds the ability to track aliases for object binding references and propagates their js doc descriptions from the source to the binding reference.
> feat(schema | api-ref): @link support and alias support for object binding nodes

- scopes/scope/scope/scope-aspects-loader.ts
- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
- scopes/workspace/workspace/workspace.ts
> internal(component-loading) - change comp loading flow to improve performance

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/checkout/checkout-version.ts
The use-case is as follows: lane-a and lane-b are diverged, lane-a removed some files, the workspace is checked out to lane-b and is now merging lane-b into lane-a.
What happened is that the output showed as if the file was removed during merge but it didn't really remove it.
This PR removes the file as expected.
> fix(lane-merge), remove files when other lane removed them and lanes are diverged

- e2e/harmony/lanes/bit-remove-on-lanes.e2e.ts
- scopes/component/remove/delete-cmd.ts
- scopes/component/remove/remove.main.runtime.ts
Unless `--update-main` was used. Otherwise, the user is probably unaware that this component is not part of the lane.
> fix(delete), avoid deleting main component when on lane

- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
- scopes/harmony/aspect-loader/plugins.ts
- This fixes a use case when you have a component that is compiled to esm with a `type:module` in its `package.json`.
and its env is not part of the workspace.
Before this fix, the env of the component was not loaded properly resulting in missing `type: modules` in the `package.json`.
If that component is used by another env which is part of the workspace, it will always be loaded during bit component loading. but since the type: module is missing, the component won't be loaded correctly, resulting in the env not loaded.
This means the workspace is in a deadlock, and the only way to unblock it from any command, is to manually go to the relevant components and add the `type: module` to the `package.json`
> fix(install) - fix package.json generation during bit install for esm components

- workspace.jsonc
This PR upgrades the Responsive Navbar to the latest version to fix the issue with it crashing when the active tab is unavailable
> fix(navbar): bump responsive navbar

- scopes/pipelines/builder/artifact/artifact-list.ts
- scopes/pipelines/builder/builder.main.runtime.ts
- scopes/pipelines/builder/exceptions/artifact-storage-error.ts
This is one of the most bizarre things I have even seen in node. When an error of type `ArtifactStorageError` is thrown, node exits with out of memory. (I'll attach the stack trace in a comment). 
However, if I make the following simple change to this class, it shows the error nicely.
```
- constructor(private originalError: Error, private component: Component) {  
+ constructor(private originalError: Error, component: Component) {
```
This change basically tells JS to ignore the component object and don't store it in this error class. The component object is indeed huge and has some circular references. Still, it doesn't explain the strange memory leak here. 
I found out that the "factory" property of the component object is the culprit. If I only set a simple object with the …
> fix, fix OOM when ArtifactStorageError throws

- scopes/component/sources/index.ts
- src/consumer/component/package-json-file.ts
- src/consumer/component/sources/artifact-files.ts
- src/consumer/component/sources/artifact.ts
- src/consumer/component/sources/index.ts
- src/toolbox/timer/index.ts
- src/utils/index.ts
This is related to the latest refactoring done to remove parts of `teambit/legacy`. 
In order to not break components that use the "teambit/legacy", some files were added back.
> added back some files that are still in use externally

- e2e/functionalities/peer-dependencies.e2e.3.ts
- e2e/harmony/preview.e2e.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/snapping.spec.ts
- scopes/pipelines/builder/build.cmd.ts
- scopes/pipelines/builder/builder.main.runtime.ts
- scopes/pipelines/builder/exceptions/components-have-issues.ts
Allow to ignore the issue by `--ignore-issues` flag. (similar to `bit tag` and `bit snap`).
> improvement(build), stop the build as soon as a tag-blocker component-issue is found

- scopes/dependencies/dependencies/dependencies-loader/apply-overrides.ts
- fix an issue with a case where an env define the same dependency defined by its own env, in both places:
its env.jsonc, and via bit deps set, with different versions.
before this fix the env.jsonc version was taken, and the deps set version was ignored for - bit show and
package.json but it was taken into account for the actual dependency installation.
now we take the version from the deps set in both cases.
> fix(dependencies) - fix bit show / package.json shows the wrong dep version when bit deps set on env

- scopes/component/snapping/snapping.main.runtime.ts
- scopes/scope/importer/import-components.ts
- src/scope/scope.ts
Not easy to reproduce this bug (hence the absence of an e2e-test). Here are the general steps:
1. comp1 -> comp2 -> comp3, tag all to main, export.
2. create a lane from comp3 only, snap, export.
3. on the remote, add comp2 and comp3 to update-dependents.
4. undo comp2.
5. import the lane to a new workspace and also comp3 with the version shows in the update-dependents prop of the lane.
6. snap all with --unmodified.
It used to throw an error suggesting comp2 is not part of the lane. Because comp2 snap object doesn't exist locally, it can't see that the `Version` object has the origin with the same lane id. 
This PR fixes it by not checking the dependency in the first place if it was already tagged/snapped with that dep before. We only care about newly introduced dependencies.
> fix, avoid throwing an error not-part-of-the-lane after undo of update-dependents

- e2e/harmony/http.e2e.ts
- scopes/component/lister/list.cmd.ts
- scopes/component/lister/lister.main.runtime.ts
- scopes/scope/scope/scope.graphql.ts
- src/remotes/remote.ts
- src/scope/network/fs/fs.ts
- src/scope/network/http/http.ts
- src/scope/network/network.ts
By default, deleted components are not shown in `bit list` output.
This new flag `--include-deleted` includes them. Keep in mind that the remotes must update the code in order for the client to get it.
> feat(list), introduce "--include-deleted" flag

- scopes/component/lister/list-template.ts
Another [PR](https://github.com/teambit/bit/pull/9041) just merged introduced a new flag `--include-deleted` to include deleted components in the list output. This PR shows them with a red mark `[deleted]`. Also, it changes the `[deprecated]` to be yellow.
> improvement(list), improve list output to show [deleted] in red when applicable

- scopes/component/sources/index.ts
- src/api/scope/lib/scope-init.ts
- src/utils/fs/remove-files-and-empty-dirs-recursively.ts
Turns out that this API was used as well.
> fix, add back src/api/scope/lib/scope-init

- scopes/defender/eslint/eslint.main.runtime.ts
- scopes/defender/prettier/prettier.main.runtime.ts
- scopes/envs/aspect-docs/envs/envs.mdx
- scopes/react/aspect-docs/react-native/react-native.mdx
> outputs(eslint+prettier aspects) - add deprecation warnings when using eslint/prettier aspects

- workspace.jsonc
- This added `uuid: require.resolve('uuid'),` to jest's `moduleNameMapper` 
- See the real change [here](https://bit.cloud/teambit/defender/jest-tester/~compare)
- Read more about the issue [here](https://stackoverflow.com/questions/73203367/jest-syntaxerror-unexpected-token-export-with-uuid-library)
> fix(test) - fix an issue with jest29 and uuid < 9

- scopes/harmony/aspect/aspect.env.ts
- scopes/harmony/aspect/aspect.main.runtime.ts
- scopes/harmony/node/node.env.ts
- workspace.jsonc
> fix(core-envs) - fixes for node/aspect/env envs pipelines

- components/legacy/bit-map/component-map.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/snapping.spec.ts
- scopes/component/snapping/tag-cmd.ts
- scopes/component/snapping/tag-model-component.ts
- scopes/component/status/status-cmd.ts
- scopes/component/status/status.main.runtime.ts
- scopes/scope/export/export.main.runtime.ts
- scopes/workspace/workspace/bit-map.ts
- scopes/workspace/workspace/commands/local-only-cmd.ts
- scopes/workspace/workspace/filter.ts
- scopes/workspace/workspace/workspace.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
- src/e2e-helper/e2e-command-helper.ts
- mark components as local-only by `bit local-only set <pattern>` (undo by `local-only unset`, list by `local-only list`).
- these local-only components are excluded from snap/tag/export commands. (unless `--include-local-only` was used for snap/tag).
- all other commands work as normal for these local-only components.
- `bit status` shows a new section "local only components".
- added a new state-filter `$localOnly`. Can be used for all commands that support pattern.
> feat, introduce "local-only" feature to keep components locally for local debugging/test purposes

- components/models/api-reference-model/api-reference-model.ts
- scopes/api-reference/renderers/parameter/parameter.renderer.tsx
- scopes/api-reference/renderers/type-ref/type-ref.renderer.tsx
This PR fixes the API Reference parameter renderer to correctly extract and render non-exported internal references as part of the object binding node.
> fix(api-ref): internal type ref in object binding nodes

- scopes/api-reference/renderers/grouped-schema-nodes-summary/grouped-schema-nodes-summary.tsx
This PR fixes the extraction of params to be rendered as part of the function node summary in the API Ref page.
> fix(api-ref): correctly extract params for function node summary

- e2e/harmony/tag-harmony.e2e.ts
- src/scope/models/model-component.ts
- src/scope/version-validator.ts
Currently it saves the objects and throws in a later phase, which make the `Version` object corrupted.
> fix(tag), exit immediately when a pre-release id is invalid

- scopes/harmony/api-server/api-server.main.runtime.ts
- workspace.jsonc
This way it'll be possible to make graphql queries from vscode extension to the cloud.
> add a proxy from bit-server to graphql in the cloud

- scopes/harmony/api-server/api-server.main.runtime.ts
- scopes/harmony/api-server/cli-raw.route.ts
- scopes/harmony/api-server/cli.route.ts
- scopes/harmony/bit/server-commander.ts
- scopes/harmony/cli/cli-parser.ts
- scopes/harmony/cli/cli.cmd.ts
- scopes/harmony/cli/cli.main.runtime.ts
- scopes/harmony/cli/command-runner.ts
- scopes/harmony/cli/index.ts
- scopes/harmony/cli/yargs-adapter.ts
Related to the [new bit-cli-server feature](https://github.com/teambit/bit/pull/9076). Turns out that cli args that accept array were parsed as non-array. Also, sub-commands weren't working.
This PR changes the way how it communicates with bit-server. Instead of parsing the args from the cli and sending the parsed data into `api/cli/:cmd` route, it sends them as is to a new `api/cli-raw` route. 
The new route, instead of calling the `report` or `json` command method directly, it goes to Yargs, let it finds the command and then returns the `CommandRunner` instance which the return result can be retrieved from.
> fix(bit-cli-server), support all args types and subcommands

- scopes/harmony/bit/server-commander.ts
This way, on the next run, it does't have to try to re-connect again.
> fix(bit-cli-server), delete the server-port file in case the port is not available

- scopes/docs/docs/docs.preview.runtime.tsx
- scopes/html/html/html-docs-app.ts
This PR updates the docs preview runtime by gracefully handling missing compositions. When the onlyOverview param is true, compositions in the docs iframe are mounted from the client side - which results in the docs preview runtime receiving an empty array of compositions. Before this fix, the docs preview runtime would just try to extract the first element from the compositions array and forward it to the mounters - which resulted them in receiving it as undefined during runtime (even though the docs props indicated that the compositions prop is not optional)
With this fix, we fallback to an empty array when there are missing compositions so the mounters don't get undefined for compositions prop.
> fix(docs): gracefully handle missing compositions

- scopes/component/component-log/component-log.main.runtime.ts
- scopes/scope/scope/scope.main.runtime.ts
- src/scope/scope.ts
Currently it shows an empty line. This PR throws an error saying the component was not found.
> fix(log), throw an error when a component was not found

- scopes/component/component/component-factory.ts
- scopes/envs/envs/env.plugin.ts
- scopes/envs/envs/environments.main.runtime.ts
- scopes/envs/envs/envs.cmd.ts
- scopes/generator/generator/workspace-generator.ts
- scopes/harmony/aspect-loader/plugin.ts
- scopes/harmony/aspect-loader/plugins.ts
- scopes/workspace/install/install.main.runtime.ts
- scopes/workspace/workspace/workspace-aspects-loader.ts
> fix(install) - reload envs which moved (fs) during installation process

- scopes/workspace/workspace-config-files/workspace-config-files.docs.mdx
> docs(ws-config-files) - add docs for "teambit.workspace/workspace-config-files" aspect

- scopes/preview/ui/component-preview/preview.tsx
This PR fixes the calculation of height of the preview iframe when onlyOverview is set to be true. It compensates for the extra margin set in the iframe by subtracting it from the reported height it receives via the iframe pub sub.
> fix(preview): adjust height calc when onlyOverview is set

- scopes/harmony/host-initializer/host-initializer.main.runtime.ts
- scopes/harmony/host-initializer/init-cmd.ts
Default workspace name to the name of the folder.
Keep existing behaviour given greater priority to the name defined with the `--name`.
Example
- `bit init foo` ➡️ workspace name `foo` 
- `bit init foor/bar/baz` ➡️ workspace name `baz` 
- `bit init foo --name qux` or `bit init foor/bar/baz --name qux` ➡️ workspace name `qux`
> feat(cli): init with default name from path

- scopes/harmony/api-server/api-server.main.runtime.ts
- scopes/harmony/modules/send-server-sent-events/send-sse.ts
Without this, the IDE is not aware of `bit export` that was running from the cli.
> fix(api-ide), send server-event of post-export

- scopes/preview/ui/component-preview/preview.tsx
This PR reverts change introduced by this PR https://github.com/teambit/bit/pull/9119
which resulted in some components get an incorrect height. 
We expected this change to fix it universally for all components but it doesn't cover all cases.
> fix(overview): revert onlyOverview height fix

- scopes/compositions/composition-card/composition-card.tsx
This PR fixes the issue in the Compositions Card rendered as part of the Overview page. With this fix, the iframe mounted in the composition card prevents scrolling.
> fix(overview): disable scroll on composition card 

- scopes/preview/preview/generate-link.ts
- scopes/preview/preview/pre-bundle.ts
- Change preview entries from `C:\\xxx\\yyy.js` to `C:/xxx/yyy.js` which is particularly for Vite compatibility. See: https://github.com/vitejs/vite/issues/17897
Related issue: #9122
> fix: preview entries on Windows particularly for Vite

- workspace.jsonc
This PR removes the opacity for dependents components of a lane in the component sidebar.
> fix(sidebar): remove opacity for dependents

- e2e/harmony/lanes/bit-remove-on-lanes.e2e.ts
- e2e/harmony/lanes/merge-lanes.e2e.ts
- e2e/harmony/merge-config.e2e.ts
- e2e/harmony/updates-from-main-and-lane.e2e.ts
- scopes/component/merging/merge-status-provider.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/lanes/merge-lanes/merge-lane.cmd.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
Until now, in case lane-b is merged into lane-a and a component (e.g. comp-a) is ahead in lane-b, we simply updated lane-a with the new snap of lane-b. (this behavior is similar to the "fast-forward" in Git).
This was true regardless of `--no-snap` flag. The `--no-snap` flag was only for cases when comp-a is diverged in history and no conflicts found, which was auto-snapping the component and saving two parents, the head of lane-a and the head of lane-b. 
In come cases, the end result of such a merge is not desirable. Some changes might be done to this comp-a in lane-b which I would like to investigate and test before I decide to get them in lane-a. Although comp-a wasn't changed/snapped in my lane-a, still, I prefer to get the changes of comp-a as modified, so then `bit diff` will show …
> feat(merge-lane)!: change no-snap to avoid fast-forward

- scopes/api-reference/sections/api-reference-page/api-reference-page.tsx
- scopes/api-reference/tagged-exports/tagged-exports.tsx
- scopes/compositions/composition-card/composition-card.tsx
This PR fixes the Tagged Exports component to not render the API section as part of the Overview if the API is not available. It also fixes the rendering of missing icons (for Unresolved nodes) and now correctly computes the url of the code view of a lane component from the API Re's view code shortcut. (Previously, even when viewing a lane component's API Ref it would point to the component's url on main)
> fix(api ref): missing api in tagged exports + correctly calculate lane component code url

- scopes/compositions/composition-card/composition-card.tsx
This PR reverts the addition of a overlay component that prevent interaction with the underlying preview from the composition card component. This revert aligns the current behaviour to be the same as the composition cards in the overview when overviewOnly is set to be false.
> fix(compositions): revert preview overlay in composition card

- scopes/workspace/install/install.main.runtime.ts
This PR is only for the installation during `bit create`. The output of `bit install` was fine.
> fix(create), optimize pnpm output when running from the IDE

- scopes/harmony/application/run.cmd.ts
currently, it simply exits the process, which is confusing.
> fix(run), indicate when the app does not run anything in the background

- scopes/webpack/config-mutator/config-mutator.ts
> fix: types issues in config mutator

- e2e/harmony/sign.e2e.ts
- scopes/scope/export/export.main.runtime.ts
- scopes/scope/sign/sign.main.runtime.ts
Until now, `bit sign --push` was supported only on the cloud. With this PR, `--push` works also on a local bare scope.
> fix(sign), support --push to a local scope

- e2e/harmony/lanes/lanes.e2e.ts
- scopes/scope/export/export-cmd.ts
- scopes/scope/export/export.main.runtime.ts
In some cases, the export doesn't bring any new component or snap/tag to the remote, but it does update the lane object. It happens for example in the following two cases:
1. when a lane has forked from another lane and exported immediately to the same scope, without adding new snaps. 
2. when merging another lane where all snaps already in the remote.
Until now, it was showing "nothing to export" for both cases above. The first case actually didn't do any action and nothing was exported, the second case the message is misleading because the lane object itself was exported.
This PR fix both cases. The first case is now exporting the new lane to the remote and for both cases it shows the message "exported the lane xxx/yyy" in the output.
> fix(export), fix output to show the exported lane in case no new snaps added

- scopes/harmony/application/application.main.runtime.ts
This PR fixes an issue of app data not being saved after running "create component" and then "snap" from the extension. The reason it happened is complex. It involves node.js caching package.json info and an API call of "getCompsMetadata" that was executed during the "create component" call. 
Because "getCompsMetadata" gets app-data, it tries to load the apps as plugins, which makes node access its package.json. At this stage, the package.json didn't have the "type: module" yet, so node.js assumes this is a CJS file. 
Later, bit re-write the package.json with the data from the env, which includes "type: module", but it's too late. Node.js already cached the package.json and refuses to see the change. 
This fix block the access to the app files unless the env is fully loaded, which then we …
> avoid loading an app that its env was not loaded yet

- scopes/pipelines/builder/build.cmd.ts
> feature(build) - add new --skip-tasks arg for bit build command

- scopes/component/snapping/snapping.main.runtime.ts
- scopes/harmony/modules/in-memory-cache/in-memory-cache.ts
- src/scope/models/model-component.ts
- src/scope/objects/repository.ts
See a previous PR for more context - https://github.com/teambit/bit/pull/6404/files.
It's about tag/snap where the component version is changed to a future version and later on during the process the workspace/scope asking for this component by the ID. 
Turned out that in some cases this is still an issue. It fails in different places than the PR above.
In this PR, instead of passing the `preferInMemoryObjects` argument in more places, and then potentially failing in different places in the future, we simply go to the `objects` array in all cases and only if not found, we try other sources.
> fix, always try to load objects from repo.objects before going to cache or fs

- e2e/harmony/snap-from-scope.e2e.ts
- scopes/component/snapping/snapping.main.runtime.ts
The bug happened when snapping from scope a component with dependencies and creating a new lane. The `getLaneForFetcher` method was calling `scope.getCurrentLaneObject()`, which re-load the lane object from the filesystem and as a result, lost the `isNew: true` prop. 
This PR, mimics the behavior on the workspace, which is saving the info about the lane being new in scope.json. This way, loading the lane guarantees to have `isNew: true`.
> fix(snap-from-scope), set a lane as new in scope.json to avoid fetching it from a remote

- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
- scopes/workspace/workspace/workspace-aspects-loader.ts
- scopes/workspace/workspace/workspace.ts
> fix(aspects) - do not try to fetch local aspects when resolving them

- .bitmap
- scopes/component/isolator/isolator.main.runtime.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/tag-from-scope.cmd.ts
- scopes/component/snapping/tag-model-component.ts
- scopes/lanes/merge-lanes/merge-lane.cmd.ts
The need came from Angular components. Angular env uses ng-packgr to compile components during build, this tool modifies the package.json and adds different values into `exports` prop. Because the modification is done during build pipeline and is not saved as an artifact, it gets lost when tagging from scope. 
As a reminder, tag-from-scope copies artifacts from the last snap into the capsule and only runs the tag-pipeline. 
This PR, uses the package.json saved in the last snap and merge its properties into the current package.json of the capsule. It can't simply replace it, because some values, such as `version` and dependencies versions are changed in this tag.
> fix(tag-from-scope), merge package.json props from the last snap

- scopes/envs/env/env.env.ts
- scopes/envs/env/env.main.runtime.ts
> fix(core envs) - include the env template bundle in core envs package

- scopes/harmony/application/app-build-context.ts
- scopes/harmony/application/app-context.ts
- scopes/harmony/application/application.main.runtime.ts
- scopes/harmony/application/run.cmd.ts
- supported `bit run <app-name> --args"
> support bit run with args

- scopes/workspace/workspace/workspace-aspects-loader.ts
Instead, concat to the same object when found more local aspects
> fix, avoid overriding this.workspace.localAspects

- scopes/component/forking/forking.main.runtime.ts
This PR fixes the `getForkingInfo` api in the forking aspect by making sure the forking aspect data has the forkedFrom data before trying to extract the forked from component id from it.
> fix(forking): check if forkedFrom info exists in forking aspect data before extracting forked from info 

- scopes/harmony/bit/app.ts
The issue started once chokidar has upgraded from 3.x to 4.x. See https://github.com/paulmillr/chokidar/issues/1369 for more info.
> fix(watch), fix EMFILE error by monkey patching core fs by graceful-fs

- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/workspace/filter.ts
- scopes/workspace/workspace/pattern.cmd.ts
Fixes https://github.com/teambit/bit/issues/9232.
- support unlimited `AND` clauses. (until now, only one AND was permitted).
- enable multiple states-filter in the AND statement. (until now, it was permitted one state-filter and one non-state-filter).
- support filtering by a specific env version. (until now, the version was ignored).
> improvement(pattern), support multiple states in AND, support env with versions

- src/scope/objects/repository.ts
This PR reverts https://github.com/teambit/bit/pull/1624.
In case the remote encounters an outdated index.json it wasn't throw an error about it. The problem is that some functions calling it expect to get objects. (e.g. `loadLane`). This PR, removes the check whether it's a remote, and whenever an index.json file is outdated, it deletes it and throw an error telling the user to re-run the command.
> fix, delete index.json on the remote if it is outdated

- components/ui/component-filters/component-filter-context/component-filter-context.tsx
This PR fixes the component filter context to correctly handle recursive state updates by correctly memoizing the deps it need to re trigger the useEffect
> fix(component drawer): correctly handle recursive state updates

- components/modules/harmony-root-generator/harmony-root-generator.ts
- before this change on the `ui-bundle-entry.<hash>` file we have duplicate entries like:
```
import {CommunityReactPreview as communityEnvsCommunityReactRuntime} from '/private/tmp/design/node_modules/.bit_roots/teambit.community_envs_community-react@2.1.10/node_modules/@teambit/community.envs.community-react/dist/community-react.preview.runtime.js';
import {CommunityReactPreview as communityEnvsCommunityReactRuntime} from '/private/tmp/design/node_modules/.bit_roots/teambit.community_envs_community-react@2.1.8/node_modules/@teambit/community.envs.community-react/dist/community-react.preview.runtime.js';
import {CommunityReactPreview as communityEnvsCommunityReactRuntime} from '/private/tmp/design/node_modules/.bit_roots/teambit.community_envs_community-react@1.90.7/node_modules/@teambit/ …
```
> fix(preview) - fix bit start when having multiple versions of the same env

- scopes/component/component-sizer/component-sizer.module.scss
- scopes/component/component-sizer/component-sizer.ui.runtime.tsx
- scopes/workspace/workspace/ui/workspace/index.ts
This PR updates the component size badge in the Overview page to not render the size when a component has been locally modified in the workspace.
> feat(component sizer): do not show size for locally modified comps

- package.json
- scopes/workspace/watcher/watcher.ts
See https://github.com/paulmillr/chokidar/issues/1369 for more info about this error.
For reference, the upgrade to 4.x was done in this PR https://github.com/teambit/bit/pull/9221.
> fix(watcher), rollback chokidar from 4.0.1 back to 3.6.0 due to EMFILE error

- scopes/harmony/api-server/cli-raw.route.ts
- scopes/harmony/bit/server-forever.ts
- scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
- src/cli/loader/loader.ts
- fix `bit server-forever` to remove the non-exist `--pty` flag of `bit server`.
- show an error message when `bit server-forever` fails to start.
- change non-Win to have the same spinner "dots" as Win OS. this way, it's easier to ignore strings coming from a socket that start with the spinner character.
> fix(cli-server-pty), remove --pty flag, simplify spinner

- scopes/component/component/component-factory.ts
- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
- scopes/workspace/workspace/workspace-aspects-loader.ts
- Add new `ignoreErrorFunc` option for aspect loading option
- Use the new option to ignore `Cannot use 'import.meta' outside a module` error during bit new / install process
> improvement(aspects loading) - improve error handling for aspect loading

- package.json
- scopes/harmony/bit/server-forever.ts
- workspace.jsonc
The change was done in a previous PR: https://github.com/teambit/bit/pull/9259 however, the "import" statement wasn't changed. Also, the pkg moved from workspace.jsonc to the package.json.
> fix(server-forever), use the @lydell/node-pty pkg instead of node-pty

- scopes/dependencies/dependencies/dependencies.main.runtime.ts
Fixes a bug when a component is using a package that should be ignored. `bit deps remove` didn't work because it didn't search in the component-issues. It was only looking at the dependencies already configured.
> fix(deps-remove), enable removing dependencies shown as missing-packages

- e2e/harmony/stash.e2e.ts
- scopes/component/checkout/checkout.main.runtime.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/component/stash/stash-data.ts
- scopes/component/stash/stash.cmd.ts
- scopes/component/stash/stash.main.runtime.ts
- src/e2e-helper/e2e-command-helper.ts
By default, only modified components are stashed. With this flag, new components are stashed as well and then get removed from the workspace. Upon `bit stash load`, they are re-created.
> feat(stash), introduce a new flag "--include-new" for new components

- scopes/component/snapping/snap-from-scope.cmd.ts
- scopes/harmony/cli/command-runner.ts
- src/cli/loader/loader.ts
This can be used by any command by simply adding `--stream` to the `options` prop.
It's useful for processes that run bit commands with `--json` and need to show some feedback to the user during the command run. 
Normally, `--json` disables the loader to keep the output a valid JSON. When adding this `--stream`, the loader is printed in JSON format with a new line. The consuming process knows to consume one line at a time. The final output includes `end: true` to indicate this is the last output of the command.
Output example:
```
{"loader":"loading 3 component(s)"}
{"loader":"linking components"}
{"loader":"loading 3 component(s)"}
{"loader":"deduping dependencies for installation"}
{"loader":"loading 3 component(s)"}
{"loader":"running pre install subscribers"}
{"loader":"running post …
```
> feat, introduce "--stream" for --json commands to print loader as json strings

- scopes/component/snapping/snapping.main.runtime.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- scopes/scope/export/export.main.runtime.ts
- scopes/scope/update-dependencies/update-dependencies.main.runtime.ts
This is not in use since all code was changed from using BitId to use ComponentID.
> refactoring, remove idsWithFutureScope from exportMany

- scopes/harmony/aspect-loader/plugins.ts
- scopes/workspace/install/install.main.runtime.ts
- scopes/workspace/watcher/watcher.ts
- workspace.jsonc
When bit-server (or watcher) is running in the background and an env is changed, although it gets compiled, its instance in Harmony remains the same. As a result, these changes are not reflected when running `bit build` or any command that uses the env.
This PR fixes the issue by re-registering the plugins when an env is changed. It makes Harmony use the new dists.
> fix, reload env instance in Harmony upon changes

- scopes/workspace/watcher/watch.cmd.ts
- scopes/workspace/watcher/watcher.ts
Introduced a new flag `--trigger <component-id>`, when any change is happening, it runs the `workspace.onComponentChange` for the specified component-id.
A real use case when this is needed is developing a vscode extension component. Because a vscode-extension must be bundled, its dependencies are always in the dist of the extension. As a result, when a dependency in the workspace is changed, the extension is not aware of it and not getting updated. 
This flag is more like a workaround and not the best solution. Ideally, the flag would be "trigger-dependents" which would traverse the graph and trigger accordingly, but it's not worth it to implement as this point as it's an edge use-case.
> improvement(watch), enable triggering onComponentChange on another component

- scopes/preview/preview/preview.start-plugin.tsx
- scopes/webpack/webpack/plugins/webpack-bit-reporter-plugin.ts
- workspace.jsonc
- installed new dev server events listener
- update preview start plugin to subscribe both legacy webpack events and dev server events
- update webpack bit report plugin to use dev server events
- add a flag on webpack bit report plugin that indicates using dev server events (this is used for outside compatibility check. see: https://bit.cloud/teambit/vite/vite-dev-server/~code/reporter.ts?version=0.1.21#l17)
https://bit.cloud/teambit/vite/~change-requests/dev-server-pubsub-20241113-9GYlr_1uj
https://bit.cloud/teambit/vite/~change-requests/vite-pubsub-20241113
> feat: support general dev server events listener

- e2e/flows/out-of-sync-componets.e2e.3.ts
- e2e/harmony/tag-harmony.e2e.ts
- scopes/component/snapping/snapping.main.runtime.ts
currently, when tagging a snapped component by specifying the id, it requires adding `--unmodified` flag unnecessarily.
> fix(tag), include snapped components when specifying ids

- scopes/harmony/ipc-events/ipc-events.main.runtime.ts
- src/scope/scope.ts
to avoid `ENOENT` error during `bit lane merge`.
> fix(bit-server), reload staged-snaps after export

- scopes/preview/preview/preview-env.ts
The `getPreviewConfig()` should be a required member in `type Preview {}` since it would be called in `preview.service.tsx` https://github.com/teambit/bit/blob/master/scopes/preview/preview/preview.service.tsx#L42
> add type getPreviewConfig onto PreviewEnv

- scopes/component/isolator/isolator.main.runtime.ts
- ensure every capsules root has a package.json which is necessary in some cases like running Vitest tasks
See: https://bit.cloud/teambit/vite/vitest-tester/~code/utils.ts?version=0.3.4#l142
> chore: ensure package.json in capsules root

- components/ui/side-bar/component-tree/component-view/component-view.tsx
This PR fixes the issue in the Component Tree where if the component is tagged with an env that belongs to a lane it would incorrectly generate the envId url on main instead to be the one on the lane. 
https://github.com/user-attachments/assets/969fef74-4f3b-497d-bf3d-3928757ce3cd
> fix(component tree): correctly generate lane component url when the env is on a lane 

- workspace.jsonc
This was needed probably in the past when we didn't auto-detect some "require" scenario. From a quick check, seems like we are able to auto-detect this dependency, so there is no need to have it forced in the variant.
> chore, remove @teambit/harmony.content.cli-reference from teambit.harmony/bit config

- scopes/harmony/bit/bootstrap.ts
- avoid `util._extend` deprecation warning (mostly from http-proxy)
See: https://github.com/http-party/node-http-proxy/pull/1666
> chore: avoid util._extend deprecation warning

- scopes/preview/preview/generate-link.ts
- change the imported file from `preview.preview.runtime.js` to `preview-modules.js` to avoid unnecessary code being processed
> chore: optimize preview entry import

- components/ui/code-tab-page/code-tab-page.tsx
- workspace.jsonc
This PR fixes the code viewer to properly resolve file paths, when navigating between files via imports. 
https://github.com/user-attachments/assets/ab0318f3-4084-406c-8d13-38c62a89ca31
> fix(ui/code): improve file path resolution for imports and navigation in code viewer

- components/renderers/inference-type/inference-type.module.scss
- components/renderers/inference-type/inference-type.renderer.tsx
- components/ui/component-compare/version-picker/component-compare-version-picker.module.scss
This PR fixes, 
- z-index of version picker dropdown in Component Compare page so it doesnt hide behind the loader
- background color for tooltip when it renders the inference rest type in API Reference
> fix(api-ref/component-compare): style fixes

- .bitmap
- e2e/harmony/install-and-compile.e2e.ts
Currently, for some reason, some of the components using this env got an older version '0.0.10' of this env. This PR aligns them all to the same (latest) version.
> chore, update node-babel-mocha to the latest 0.0.33

- .gitignore
bit uses `.gitignore` file to un-track files. for e2e-helper some fixture files are .tgz and are needed for the component to work properly.
> avoid ignoring .tgz files, they are needed for fixtures

- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/envs/envs/environments.main.runtime.ts
- scopes/generator/generator/generator.main.runtime.ts
- scopes/generator/generator/workspace-generator.ts
- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
- scopes/harmony/bit/load-bit.ts
Bit aspect (`teambit.harmony/bit`) depends on all core aspects. This is needed because this aspect is the main entry of bit, it loads all those core aspects and also we want to this aspect to get a new version every time a core-aspect has changed, so then when running bit, all the core aspect are always up to date.
However, some core aspects, e.g. `Generator` aspect were depended on Bit aspect (practically forming a circular dependency) for mainly two tasks: loadBit() and getting core-ids. Because of this circular, changing core aspects triggers an auto-tag of most of the core aspects. Leading to unnecessary tags and slow deployment. 
This PR breaks this direction of dependency by injecting the APIs needed to those aspects from the loadBit function. It's not pretty, but it's much better …
> decouple the teambit.harmony/bit dependency from core aspects

- scopes/dependencies/pnpm/pnpm.package-manager.ts
> fix: don't export dependencies graph from workspace that doesn't use root components

- scopes/harmony/application/application.main.runtime.ts
- This change will make sure that when loading apps components in a workspace we will run the load slot and the aspects to make sure: 
- we identify them as apps
- we don't show a warning about their not-loaded envs
- This will also fix cases when snapping components will not add the apps data into the component data
-
> fix(load apps) - fix cases when components not loaded as app incorrectly

- scopes/harmony/doctor/doctor.main.runtime.ts
Also, when using this flag, only exclude the "objects" and "cache" directories which can be huge. Others are not important and can be actually useful for debugging.
> fix(doctor), no need to run "bit init" after untar doctor archive with exclude-local-scope

- scopes/lanes/lanes/lanes.main.runtime.ts
Previously, the `bit lane checkout` wasn't passing the lane object to the importer, result in missing component versions when trying to check them out.
> fix(lane-checkout), import the previous lane history components properly

- scopes/component/component-log/component-log.main.runtime.ts
`workspace.resolveComponentId` of core-aspects returns the component-id without version, as a result, bit assumes the component is new and doesn't show the log for it.
This PR fixes it by getting the component from .bitmap and checking whether it has a version.
> fix(log), show log of core aspects

- scopes/harmony/application/app.cmd.ts
- scopes/harmony/application/application.main.runtime.ts
Also, improve `AppNotFound` error message to suggests running "bit app list".
> improvement(app), display the app list when running "bit app" without a subcommand

- components/legacy/bit-map/bit-map.ts
- scopes/component/component-writer/component-writer.main.runtime.ts
In case the current component is using the same dir of an existing one, suggest using `--path` or modifying workspace.jsonc at defaultDirectory. Currently, it suggests using `--override` incorrectly.
> fix(import), improve error when importing a component on existing dir

- scopes/scope/objects/models/model-component.ts
Before:
> teambit.docs/docs-template current: 1.0.7 head: 81fafbec36995725fed26cef8feff57ef2be90e4 latest: 1.0.8
Now: 
> teambit.docs/docs-template current: 1.0.7 head: 1.0.8
> fix(status), remove irrelevant snap info for outdated components when the head is the same as latest

- components/legacy/scope/component-ops/scope-components-importer.ts
Normally, this should not happen because the lane's scope suppose to have all dependencies cached. However, in case the `FetchMissingDeps` wasn't running on the remote for some reason, this fallback ensure that the client gets the missing components from main.
> fix(import), try importing from main if imported fail finding it in the lane scope

- .bitmap
- scopes/scope/objects/objects/repository.ts
- scopes/toolbox/promise/map-pool/promise-with-concurrent.spec.ts
- scopes/toolbox/promise/map-pool/promise-with-concurrent.ts
For large scopes, when index.json is deleted it takes a while to create a new one (because it needs to read every object file). In the meanwhile, there is no indication that something is happening. This PR logs to the debug.log the progress every 1,000 files.
Also, the implementation of p-map-pool is simplified by using `chunk` from `lodash`.
> improvement, log the progress of creating the index.json file

- components/legacy/scope/exceptions/outdated-index-json.ts
- e2e/functionalities/components-index.e2e.2.ts
- scopes/scope/objects/objects/repository.ts
- scopes/scope/objects/objects/scope-index.ts
Currently, when an object (lane/component) exists in index.json but missing from the filesystem, bit deletes the index.json assuming it's corrupted and re-create it on the next command. 
For large scopes, it takes long time to re-create the file because it needs to parse each and every object file.
This PR approaches it differently. It updates the index.json file, removes the missing objects and then throws an error telling the user to re-run the command.
> improvement, avoid deleting index.json when it has missing objects

- scopes/scope/scope/scope-component-loader.ts
- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
If the env is in the current lane and marked as deleted, `bit env update` currently sets the env to the deleted version.
This PR resolves this issue by ensuring the env is set to the main version instead.
> fix(env-update), update to env from main if deleted on the current lane

- components/legacy/scope/component-ops/scope-components-importer.ts
- components/legacy/scope/objects-fetcher/objects-fetcher.ts
- components/scope/remotes/get-remote-by-name.ts
- components/scope/remotes/remotes.ts
- components/scope/remotes/scope-remotes.ts
- scopes/cloud/cloud/cloud.main.runtime.ts
- scopes/component/remove/remove-components.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/tag-model-component.ts
- scopes/component/tracker/tracker.main.runtime.ts
- scopes/lanes/lanes/remove-lanes.ts
- scopes/scope/export/export-scope-components.ts
- scopes/scope/export/export.main.runtime.ts
- scopes/scope/export/index.ts
- scopes/scope/scope/run-action/run-action.ts
- scopes/scope/scope/scope.main.runtime.ts
- scopes/scope/sign/sign.main.runtime.ts
- scopes/scope/update-dependencies/update-dependencies.main.runtime.ts
- scopes/workspace/install/install.main.runtime.ts
Improve the Snapping API by changing from ConsumerComponent to Component and prefer using Scope over LegacyScope when working with Remotes.
> refactor, reduce the usage of legacy scope/comp for snapping API

- workspace.jsonc
by upgrading `@teambit/typescript.deps-detectors.detective-typescript` which has been updated to use the same version of `typescript` and `@typescript-eslint/typescript-estree` as this repo.
> fix, fix typescript-estree warning about typescript version mismatch

- components/legacy/e2e-helper/e2e-command-helper.ts
- e2e/harmony/tag-from-scope.e2e.ts
- scopes/defender/tester/tester.task.ts
- scopes/pkg/pkg/pkg.main.runtime.ts
- scopes/pkg/pkg/write-npm-ignore.ts
- scopes/preview/preview/env-preview-template.task.ts
- scopes/preview/preview/strategies/component-strategy.ts
- scopes/preview/preview/strategies/env-strategy.ts
- scopes/semantics/schema/schema.task.ts
When tagging from scope, the artifacts from the last snap are written into the capsule as part of the pipeline execution. The paths are the same as they're saved in the model (`Version` object). 
Currently, the preview/schema/test artifacts have relativePath without the `artifacts/` prefix. It's happening due to the usage of the deprecated `rootDir`. 
This fix removes the `rootDir` from their artifact definition and use `globPatterns` instead. The paths are now written correctly to the model, and then when tagging from scope, they're written into `artifacts` dir properly.
Another issue was the `.npmignore` which wasn't get written at all when tagging from scope because it was part of the build pipeline not snap/tag. This PR copies it to the snap/tag pipeline.
> fix(tag-from-scope), avoid publishing artifacts in the package

- components/legacy/constants/constants.ts
- components/legacy/global-config/global-config.ts
- components/legacy/global-config/index.ts
- scopes/git/git/git.main.runtime.ts
Also, fix the "gitconfig" imports to use the forked one - "@teambit/gitconfig".
> refactor, fix circular between constant and global-config legacy components

- scopes/pkg/pkg/pkg.service.ts
This pull request includes changes to the `PkgService` class in the `scopes/pkg/pkg/pkg.service.ts` file to enhance the handling and display of package configuration and npm ignore entries. The most important changes include parsing the configuration JSON, extracting specific properties, and updating the rendering method to display these properties in a more structured format.
Enhancements to configuration handling and display:
* [`scopes/pkg/pkg/pkg.service.ts`](diffhunk://#diff-fae3dc422103c0e340f225aa8596f9bb56ac1064595037cf88241411718a083aL29-R36): Modified the `render` method to parse the configuration JSON, extract `packageJsonProps` and `npmIgnore`, and display them with appropriate titles using `chalk`.
* [`scopes/pkg/pkg/pkg.service.ts`](diffhunk://#diff-fae3dc422103c0e340f225aa85 …
> improvement(env get) - print npm ignore entries in env get command

- components/entities/semantic-schema/api-schema.ts
- components/entities/semantic-schema/schemas/type.ts
- components/ui/code-tab-page/code-tab-page.tsx
https://github.com/user-attachments/assets/8b1574cb-7225-4c48-ae7e-c4e01e940bb8
> fix(code | schema): handle route navigation with mismatch extensions + type schema node signature serialization fix

- scopes/harmony/express/express.main.runtime.ts
- scopes/scope/network/http/http.ts
add retry to http put, to avoid fail on export when TCP is disconnected
> add retry to put http

- scopes/scope/importer/import-components.ts
Also, limit the concurrency of scopes to fetch to 30.
> improvement(import), log the scope-name when failed to list components

- components/legacy/scope/scope.ts
- scopes/scope/scope/scope.main.runtime.ts
Otherwise, it loads all components in the bare-scope unnecessarily.
Besides the performance gain, it also prevent errors about index.json having cache components that don't exist in the filesystem.
> fix(scope-list), filter non-scope components early in the process

- scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
Currently, these global-aspects from .bitrc.jsonc file must have `scope.runtime` instead of the `main.runtime`. It causes issues when testing via `loadAspect` API, which searches for "main.runtime" files.
They also have to have `static id` prop in their runtime file in addition to the aspect file. 
This PR fixes these two issues. Normal aspects can work out of the box with no modifications.
> improvement(global-aspect), allow aspects from .bitrc.jsonc to have main.runtime and no static-id

- components/legacy/component-diff/components-diff.ts
- scopes/component/component-compare/component-compare.main.runtime.ts
- scopes/component/component-compare/diff-cmd.ts
Until now, to check what changes were done in a certain version, for example foo@0.0.2, you had to find out what was the previous version and then run `bit diff foo 0.0.1 0.0.2`.
With this PR, you can simply run `bit diff foo 0.0.2 --parent`.
> improvement(diff), introduce "--parent" flag to display changes of the specified version

- scopes/workspace/install/install.main.runtime.ts
- This should fix issues during `ws-config write` process (usually after `bit install` / `bit create`) such as:
```
failed generating workspace config files, please run "bit ws-config write" manually. error: tsconfig not found at <path> 
You must provide either specify a path to a valid 'tsconfig.json' or set 'compilerOptions'
```
> fix(envs) - reload envs after node_modules pruning

- components/legacy/extension-data/extension-data-list.ts
- e2e/harmony/lanes/merge-lanes-from-scope.e2e.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/component/snapping/generate-comp-from-scope.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/dependencies/dependencies/dependencies-loader/apply-overrides.ts
- scopes/dependencies/dependency-resolver/index.ts
- scopes/dependencies/dependency-resolver/policy/index.ts
- scopes/dependencies/dependency-resolver/policy/variant-policy/index.ts
- scopes/dependencies/dependency-resolver/policy/variant-policy/variant-policy.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
- scopes/scope/scope/scope.main.runtime.ts
- scopes/workspace/workspace/aspects-merger.ts
- scopes/workspace/workspace/workspace.ts
In case of merging main into an out-of-date lane, we compare the config and if there is no conflict, we generate `.bit/unmerged.json` file with the config to update. 
When running from the workspace, as soon as the components are re-loaded to be snapped during the process, it picks up this unmerged file and combine the config from this file into the aspect data of the componet.
However, when running from the scope, there is no concept of aspect-merge from different sources.  As a result, the config from this file are not integrated into the component. 
This PR fixes it by loading the unmerged file and adding the data to the component object.
> fix(merge-from-scope), save dependencies data after merging config

- scopes/component/forking/forking.main.runtime.ts
- scopes/generator/generator/component-generator.ts
- scopes/workspace/workspace/workspace.ts
Until now we had two APIs in the Workspace aspect:
```
hasId(componentId: ComponentID): boolean;
exists(componentId: ComponentID, opts: { includeDeleted?: boolean } = {}): boolean;
```
Both methods check whether a component ID is part of the workspace. The former checks for an exact match, while the latter ignores the version and provides an option to include deleted components. This is obviously confusing because the method names do not clearly indicate the type of comparison being performed.
In this PR, the exists method is deprecated, and hasId is modified (without a breaking change) to include all options:
```
hasId(componentId: ComponentID, opts?: { includeDeleted?: boolean, ignoreVersion?: boolean }): boolean;
```
> improvement(workspace-API), provide one complete API "hasId" for different scenarios

- .bitmap
Currently, they use node-babel-mocha, which includes the lazy loading plugin. The problem is that this plugin wraps all require/import statements in a function, and when a named export is called from an ESM file, Node throws an error. In the new environment, compilation is performed using TypeScript instead of Babel, so there are no issues when using them from an ESM file.
> change teambit.toolbox/* env to a new one: node-typescript-mocha

- scopes/envs/envs/environment.ts
- scopes/pkg/pkg/index.ts
- scopes/pkg/pkg/package-generator.ts
- scopes/pkg/pkg/pkg.main.runtime.ts
- scopes/pkg/pkg/pkg.service.ts
- scopes/scope/export/export.main.runtime.ts
Until now, it was only possible to provide static props. 
This PR provides the ability to modify the props per component dynamically before writing it to the filesystem.
> feat(pkg), add a new API "modifyPackageJson" to the env

- .bitmap
- scopes/harmony/aspect/aspect.env.ts
- scopes/react/react/react.env.ts
Added `/*` at the end of "artifacts" entry of `.npmignore` file. This way, when there are negative entries (`!`) this dir is still excluded.
> fix(npm-ignore), fix ignore of artifacts dir

- e2e/harmony/checkout-harmony.e2e.ts
- scopes/component/checkout/checkout.main.runtime.ts
`bit checkout reset --all` rewrites deleted component dirs.
Currently, when running it and a non-lane component is deleted when the workspace is on a lane, this component is not written. 
The reason is that when on a lane, the ids used by this command are the ids from the lane. While this is the expected behavior for `bit checkout head`, it's not the case for `bit checkout reset`. 
This PR changes it so that all workspace ids are used for the checkout-reset.
> fix(checkout-reset), write deleted main-component when on a lane

- scopes/pkg/pkg/pkg.main.runtime.ts
- scopes/scope/export/export.main.runtime.ts
This is a regression caused by https://github.com/teambit/bit/pull/9530.
That API needed the env to be loaded when writing the package.json. In some cases, this is hard to achieve. For `bit new`, when the env is not there, it threw an error:
> environment with ID: X configured on component Y was not found
This PR fixes it by not throwing an error in such case.
> fix(new), fix env-not-found regression error by not requiring the env to be loaded

- scopes/harmony/aspect-loader/plugin.ts
- scopes/harmony/aspect-loader/plugins.ts
- This fixes errors such as
```
Cannot find package '<wsPath>/node_modules/.pnpm/@bitdev+node.node-env@4.0.1_@babel+core@7.11.6_@babel+traverse@7.26.9_@testing-library+react@_bk5xnj5gsuxhmwvf6rvucqnsi4/node_modules/@bitdev/react.react-env/index.js' imported from <wsPath>/node_modules/.pnpm/@bitdev+node.node-env@4.0.1_@babel+core@7.11.6_@babel+traverse@7.26.9_@testing-library+react@_bk5xnj5gsuxhmwvf6rvucqnsi4/node_modules/@bitdev/node.node-env/dist/node-env.bit-env.js
```
> fix(plugins) - fix resolution of plugins paths which leads to files not found errors

- components/legacy/e2e-helper/e2e-command-helper.ts
- components/legacy/e2e-helper/e2e-env-helper.ts
- e2e/harmony/custom-env.e2e.ts
- e2e/harmony/dependencies.e2e.ts
- scopes/dependencies/dependencies/dependencies-loader/dependencies-loader.ts
Currently, when an env.jsonc is changed, for example, a file pattern becomes a dev-file, the components of this env are loaded with the old cached dependencies-data. 
This PR checks if a component contains an `env.jsonc` file and, if the file has been modified recently, deletes all dependency caches from the filesystem.
> fix, clear all dependency caches upon env.jsonc changes

- components/ui/code-tab-page/code-tab-page.tsx
When resolving file paths with multiple dots without an extension (e.g. `file.ui.runtime`), path.extname() incorrectly treated '.runtime' as the extension. Now it validates extensions against known file types before processing.
> fix(code): validate path extensions against known file types

- components/legacy/extension-data/extension-data.ts
- e2e/harmony/lanes/merge-lanes-from-scope.e2e.ts
- scopes/component/merging/merge-status-provider.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
When merging main into a lane from scope, it has to make a new snap with 2 parents: main and lane. During the snap, we used to load aspects because when trying to avoid the aspect-loading, aspects data weren't saved correctly. 
The reason is that aspects-data gets saved on the component object during load. If aspect-loading doesn't happen, the env is not loaded and then when the component is loaded, it doesn't find the env and fallback to the default node-env.
This PR introduces a new mechanism of merging aspects-data. In case both sides: lane and main has the same env, we can simply compare the aspect-data and if there is no conflict, we can keep or copy the data as needed. 
Eventually, before snap, we check which components were merged their data properly and for them, we don't load …
> improvement(merge-from-scope), skip loading aspects when merging main to a lane

- scopes/compositions/compositions/ui/composition-preview.tsx
- scopes/preview/ui/preview-placeholder/preview-placeholder.tsx
This PR fixes a regression introduced in PR #9531, specifically where a default viewport of `1280px` was incorrectly applied to all component compositions.
The regression occurred because the viewport prop was being passed unconditionally, causing all preview renders to use `width: fit-content` and `maxWidth: 1280px`. This resulted in truncated displays in the full Preview Tab where components should expand to fill the available space.
The fix ensures that:
- Component Preview in the Preview Tab uses `width: 100%` without any maxWidth constraint
- Viewport constraints (`width: fit-content` and `maxWidth`) are only applied when viewing compositions in contained contexts like Composition Cards in the Workspace Overview grid
This restores the intended behaviour where components can properly …
> fix(compositions): remove default viewport prop from component compositions 

- .bitmap
- components/entities/semantic-schema/schemas/parameter.ts
- components/entities/semantic-schema/schemas/type-ref.ts
- components/models/api-reference-model/api-reference-model.ts
- components/renderers/api-node-details/api-node-details.tsx
- components/renderers/api-node-details/extract-code-block.spec.ts
- components/renderers/api-node-details/extract-code-block.ts
- components/renderers/api-node-details/index.ts
- components/renderers/tuple-type/index.ts
- components/renderers/tuple-type/tuple-type.renderer.module.scss
- components/renderers/tuple-type/tuple-type.renderer.tsx
- scopes/api-reference/api-reference/api-reference.ui.runtime.tsx
- scopes/api-reference/renderers/parameter/parameter.renderer.tsx
- scopes/api-reference/renderers/schema-node-member-summary/function-node-summary.module.scss
- scopes/api-reference/renderers/schema-node-member-summary/function-node-summary.tsx
- scopes/api-reference/renderers/type-ref/type-ref.renderer.module.scss
- scopes/api-reference/renderers/type-ref/type-ref.renderer.tsx
- scopes/api-reference/sections/api-reference-page/api-reference-page.tsx
- scopes/semantics/schema/mock/button-schemas.json
- scopes/typescript/typescript/identifier.ts
- scopes/typescript/typescript/schema-extractor-context.ts
- scopes/typescript/typescript/transformers/export-declaration.ts
- scopes/typescript/typescript/transformers/function-like.ts
- scopes/typescript/typescript/transformers/type-query.ts
- scopes/typescript/typescript/transformers/type-reference.ts
- scopes/typescript/typescript/transformers/utils/jsdoc-to-doc-schema.ts
- scopes/typescript/typescript/typescript.extractor.ts
This PR introduces several improvements to the API reference system:
- Enhanced Type Reference Resolution for Inference Types
- Improved handling of internal and external type references
- Better handling of inferred array types, generic types, and Promise types
- Fixed type reference resolution for internal components (non exported)
- Documentation Display Improvements
- Added support for displaying examples in function documentation
- Better code block extraction and formatting in JSDoc comments
- Improved rendering of tuple types
- Added external link icons for external type references
> feat(api-ref): enhance type references and documentation display

- scopes/mdx/mdx/mdx.main.runtime.ts
Currently, `@babel/core` are loaded during bit bootstrap. Here it the relevant chain:
Mdx-aspect provider -> react.overrideCompilerTasks -> ReactEnv.getBuildPipe → ReactEnv.getJestWorker -> '@teambit/defender.jest-tester'. 
This last component is compiled by a non-lazy-loading env, and as a result, importing this component result in getting all `@babel/core`. 
Fixed by changing the method of getting the build-pipeline.
This change reduces the number of files loaded during bootstrap by 382.
> fix, avoid loading @babel/core by lazy-loading JestTester from mdx env

- scopes/generator/generator/component-template.ts
- scopes/generator/generator/generator.main.runtime.ts
- scopes/generator/generator/index.ts
- scopes/harmony/aspect/aspect.main.runtime.ts
- scopes/harmony/node/node.main.runtime.ts
- scopes/mdx/mdx/mdx.main.runtime.ts
- scopes/react/react/react.main.runtime.ts
Currently, many templates are loaded during Bit’s bootstrap process. This occurs because aspects call `generator.registerComponentTemplate` inside their `provider` function, which is invoked whenever the aspect is loaded.
It's addressed by changing the `registerComponentTemplate` to accept also a function that returns the templates. This way, the templates are retrieved only when needed. 
This change reduces the number of files loaded during bootstrap by 229.
> perf, lazy-load component-templates

- scopes/mdx/mdx/mdx.main.runtime.ts
a minor change related to the previously merged PR: https://github.com/teambit/bit/pull/9576
> refactor(mdx-env), move getBuildPipe to the envs.override

- components/legacy/scope/component-ops/model-components-merger.ts
- components/legacy/scope/exceptions/component-needs-update.ts
- components/legacy/scope/exceptions/merge-conflict-on-remote.ts
- components/legacy/scope/exceptions/merge-conflict.ts
- components/legacy/scope/repositories/sources.ts
- e2e/harmony/delete.e2e.ts
- scopes/scope/export/export-scope-components.ts
- scopes/scope/network/remote-error-handler.ts
Currently it shows merge-conflict or out-of-date errors, which are misleading.
> fix(export), improve error when a component was deleted and another one exported with the same name

- scopes/mdx/mdx/mdx.env.ts
- scopes/mdx/mdx/mdx.main.runtime.ts
Because the env implementation was inside the provider, it had to create the compilers and do heavy stuff to make the env ready. In hurts performance by adding 341 files every time bit is loaded.
> refactor(mdx-env), move the implementation into MdxEnv class instead of patching it from the main runtime

- scopes/workspace/workspace/workspace.main.runtime.ts
This is a follow-up to a previously merged PR: https://github.com/teambit/bit/pull/9588.
One instance was missed and has been fixed here, increasing the number of files saved during loading by an additional 131. This brings the total file reduction to 189!
> perf, complete the graphql lazy-load by fixing another instance in workspace aspect

- components/legacy/scope/component-ops/scope-components-importer.ts
- components/legacy/scope/lanes/remote-lanes.ts
- scopes/scope/objects/models/model-component.ts
- scopes/scope/objects/objects/repository.ts
- scopes/scope/objects/objects/scope-index.ts
In classes where the Mutex object were initialized in the constructor, it was moved to a getter function.
> perf, lazy-load Mutex

- components/legacy/e2e-helper/e2e-command-helper.ts
- e2e/performance/filesystem-read.e2e.ts
- scopes/harmony/bit/app.ts
Also, add an e2e-test to ensure the number of files loaded during bit are kept reasonable
> debug, add an option to debug filesystem read during bit-commands

- scopes/harmony/graphql/graphql.main.runtime.ts
- scopes/harmony/graphql/graphql.spec.ts
This regression was introduced by #9588. The `register` method allows a function to return a schema, but the getSchemas method was not updated to support this change.
> fix(graph), fix getSchemas API to always return Schema[]

- scopes/scope/objects/models/version.ts
Some of the remote scopes have a version older than 1.6.97, which doesn't support the new format. We'll wait until all of them are updated to re-do this change.
> revert #9601 for backward compatibility of old scopes

- scopes/generator/generator/component-generator.ts
- scopes/generator/generator/component-template.ts
- scopes/generator/generator/generator.main.runtime.ts
- scopes/generator/generator/index.ts
- scopes/harmony/api-server/api-for-ide.ts
- workspace.jsonc
- Provide an API for component-templates creator `promptOptions`. If implemented, `bit create` will show the prompts, gather the info needed, and then pass this info to the `generateFiles()` of the template.
- Support adding the prompt-options as flags. (e.g. bit create comp some-template -- --bundler webpack).
- This infrastructure eliminates the need from templates creator to import a prompt library and implement all of it themselves.
- The main reason of implementing this is to enable the IDE extension to display prompts within the IDE UI and create the components according to the user's input.
> improvement(create), provide an infra for interactive templates

- e2e/harmony/lanes/lane-eject.e2e.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/workspace/eject/eject.main.runtime.ts
Also, disable `bit eject` command when checked out to a lane.
> fix(lane-eject), show a descriptive error when ejecting a component on a lane when there is no main version

- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
In some cases, when merging main to a lane from a bare-scope, it throws an error about not finding the Version object of a squashed one in the history. 
This is happening when exporting the lane to the remote. Bit tries to export the missing history from main into the lane's scope. 
Due to recent changes in the remote, it's not needed anymore, and the remote itself fetches the missing history once the lane is exported. 
Instead, this PR, only pushes the head into the lane's scope, and doesn't try to fetch missing history.
> fix(merge-from-scope), fix VersionNotFound error when merging main into a lane in some edge cases

- scopes/component/merging/merging.main.runtime.ts
- scopes/component/snapping/snap-from-scope.cmd.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/version-maker.ts
- scopes/lanes/merge-lanes/merge-lane-from-scope.cmd.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
When merging main into a lane, the merged components are snapped. This PR finds the other components in the lane that depend on the snapped components and auto-snap them. This way, the lane is kept up-to-date, and components in the lane always have the dependencies with the same versions they appear on the lane.
> fix(merge-from-scope), enable auto-snap when merging main into a lane

- scopes/harmony/api-server/api-for-ide.ts
Currently, only `bit install` is supported, without any arg. This PR enables installing given packages.
> feat(api-ide), support installing packages

- components/legacy/bit-map/component-map.ts
- components/legacy/consumer-component/consumer-component.ts
Caused by https://github.com/teambit/bit/pull/9661 which removed the "test" prop. This PR adds it back for now.
> fix a regression that cause all components to be shown as modified

- scopes/workspace/watcher/watcher.ts
Simply log them to the watcher console and to the debug.log. The watcher should continue working.
> fix(watcher), avoid throwing when parcel returns errors

- scopes/harmony/bit/server-commander.ts
In some systems, there is no good option to get the pid by the port without having sudo access. Also, there are other ways to ensure the system has only one workspace.
Using the flag `--skip-port-validation` the validation of the dir by port is skipped.
> enable skipping port validation for "bit server" by a flag

- scopes/workspace/watcher/watcher.ts
For big projects, it happens all the time when running `bit install` or any heavy command. It's because Parcel watches the workspace root and although the node-modules is ignored, it probably stills gets the events from the FSEvents (and then discard them). 
It's not helpful to show this error message constantly, so it's simply ignored.
> avoid printing "Events were dropped by the FSEvents client" during watch

- components/legacy/e2e-helper/e2e-command-helper.ts
- e2e/harmony/deps-write.e2e.ts
- scopes/component/component-writer/component-writer.main.runtime.ts
- scopes/dependencies/dependencies/dependencies-cmd.ts
- scopes/dependencies/dependencies/dependencies.main.runtime.ts
- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/dependencies/dependency-resolver/get-all-policy-pkgs.ts
- scopes/dependencies/dependency-resolver/index.ts
- scopes/pkg/modules/semver-helper/index.ts
- scopes/pkg/modules/semver-helper/semver-helper.ts
- scopes/scope/importer/import-components.ts
- scopes/scope/importer/import.cmd.ts
- scopes/workspace/config-merger/config-merger.main.runtime.ts
- scopes/workspace/install/install.main.runtime.ts
- scopes/workspace/workspace/workspace.ts
> feat: write dependencies of imported component to workspace.jsonc or package.json

- components/legacy/e2e-helper/e2e-command-helper.ts
- e2e/functionalities/peer-dependencies.e2e.3.ts
- e2e/harmony/dependency-resolver.e2e.ts
- scopes/component/isolator/isolator.main.runtime.ts
- scopes/component/snapping/index.ts
- scopes/component/snapping/version-maker.ts
- scopes/dependencies/dependencies/dependencies-loader/apply-overrides.ts
- scopes/dependencies/dependencies/dependencies-loader/auto-detect-deps.ts
- scopes/dependencies/dependencies/dependencies-loader/dependencies-versions-resolver.ts
- scopes/dependencies/dependency-resolver/dependency-resolver-workspace-config.ts
- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/dependencies/dependency-resolver/index.ts
- scopes/workspace/workspace/workspace.ts
- Support new `componentRangePrefix` property under the "dependency-resolver" section in `workspace.jsonc`, accepting `^`, `~`, or `+`.
- `^ / ~`  → writes that prefix in package.json for every component dependency.
- `+`  → copies the exact range from the workspace’s dependency policy instead of applying a global prefix.
- if a workspace doesn’t define `componentRangePrefix`, dependencies revert to pinned versions.
- If a dependency has an exact range defined in the workspace’s dependency policy, prioritize it over the componentPolicyPrefix value, even if they conflict.
> feat, support saving components with range in package.json

- e2e/harmony/dependency-resolver.e2e.ts
- scopes/component/snapping/version-maker.ts
- scopes/dependencies/dependencies/dependencies-loader/dependencies-versions-resolver.ts
- scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
- scopes/dependencies/dependency-resolver/index.ts
- scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
This way, when importing the component to a new workspace that doesn't have any `componentRangePrefix` set , it keeps the range. 
With this change, if the user wants to remove the range-prefix, it's not enough to remove the prop from workspace.jsonc. It'll need to be set with minus. (`"componentRangePrefix": "-"`).
> improvement(deps-resolver), save componentRangePrefix in the deps-resolver data

- scopes/react/bit-react-transformer/bit-react-transformer.ts
Previously, we used `path.insertAfter()` to inject the `__bit_component` metadata assignment. 
This worked for top-level declarations but failed when the visitor was on non-statement nodes, 
such as an _ArrowFunctionExpression_ inside a chained CommonJS-style assignment:
This PR fixes it by using `path.getStatementParent()?.insertAfter(...)` to guarantee that the assignment 
is always inserted at a legal statement boundary.
> fix(bit-react-transformer): safely inject component metadata

- .circleci/config.yml
- components/legacy/e2e-helper/e2e-command-helper.ts
- e2e/flows/sort-components-output.e2e.3.ts
- e2e/harmony/eject-harmony.e2e.ts
- e2e/harmony/extensions-config.e2e.3.ts
- e2e/harmony/import-harmony.e2e.ts
- e2e/harmony/lanes/import-lanes.e2e.ts
- e2e/harmony/lanes/lane-eject.e2e.ts
- scopes/component/lister/list.cmd.ts
- scopes/component/lister/lister.main.runtime.ts
- scopes/component/snapping/reset-cmd.ts
- Renamed the `--scope` flag to `--local-scope` to clarify its purpose for listing components in the local scope.
- Introduced a new `--scope <scope-name>` flag to filter components by their scope name.
- Updated command logic and help text to reflect these changes and prevent misuse of flags with remote scopes.
> feat(list)!: rename --scope flag to --local-scope and introduce --scope <scope-name> for filtering by scope name

- package.json
This PR removes an invalid exclude pattern from the lint-staged configuration in package.json to fix lint-staged execution.
> fix: remove invalid lint-staged exclude pattern from package.json

- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- in case bit throws an error, pass the error to the mcp-client. currently, it shows EPERM incorrectly.
- pass the `cwd` from the client. it's now a mandatory arg.
- add the "extended description" of the commands.
> fix(mcp-server): handle errors correctly and pass the cwd

- scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
- remove `devServer.open` flag
- it should be only controlled by the noBrowser flag in `start.cmd.tsx`
> fix: --no-browser in bit start dev mode

- scopes/mcp/cli-mcp-server/README.docs.mdx
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/semantics/schema/schema.cmd.ts
- scopes/semantics/schema/schema.main.runtime.ts
Enable displaying schema for remote components from the CLI.
This helps the MCP server accepting id as a package name. When it was a GraphQL query, it didn't have the Workspace object, so this ability to convert a package into a component wasn't available.
> feat(schema), introduce --remote flag

- scopes/mcp/cli-mcp-server/README.docs.mdx
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/mcp-server.cmd.ts
For non-Bit workspaces that only consume Bit component packages. Enables only "schema", "show", and "remote-search" tools and automatically adds the "--remote" flag to relevant commands
> feat(cli-mcp-server): add --consumer-project flag for non-Bit workspaces

- scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.ts
- support npm alias in env.jsonc e.g.:
```
{
"name": "vite",
"version": "npm:rolldown-vite@latest",
"supportedRange": "npm:rolldown-vite@latest"
},
```
> feat: support npm alias in env.jsonc

- scopes/harmony/cli/help.ts
- scopes/harmony/global-config/remote-cmd.ts
- scopes/scope/importer/fetch-cmd.ts
Agents try using the non-exist "bit remote list". This PR helps them by introducing it.
> feat(remote): add "list" sub-command as an alias to "bit remote"

- scopes/mcp/cli-mcp-server/README.docs.mdx
This PR updates the README.docs.mdx file in the cli-mcp-server component to document the new 'bit mcp-server setup' command, which allows for automatic configuration of MCP server integration with VS Code, Cursor, and Windsurf editors.
The documentation now highlights this command as the recommended way to integrate with IDEs.
> docs: update README with new mcp-server setup command

- scopes/mcp/cli-mcp-server/README.docs.mdx
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.spec.ts
Replaces the single `bit_commands_info` tool with two focused tools for helping AI agents to use these tools.
- **bit_commands_list**: Fast command discovery with basic info
- **bit_command_help**: Detailed help for specific commands
- Updated README.docs.mdx to reflect the new tool structure
> feat: split bit_commands_info into discovery and help tools

- scopes/mcp/cli-mcp-server/README.docs.mdx
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
Refactors the MCP server to remove the `defaultTools` concept and simplifies the tool registration logic.
- Removed `defaultTools` Set that previously included `['create', 'schema', 'remote-search']`
- Made `remote-search` tool always register (like `bit_query`, `bit_execute`, and `bit_workspace_info`)
Since `bit_query` and `bit_execute` can handle any Bit command, having default tools for `schema` and `create` is redundant. The `remote-search` tool should always be available as it's essential for component discovery.
> refactor: remove defaultTools from MCP server and make remote-search always available

- scopes/generator/generator/generator.main.runtime.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.spec.ts
Improves the MCP server's remote search tool description and cleans up command list output by removing unused fields.
- **Remote search tool improvements**: Simplified description and updated queryStr guidance to recommend broad keywords
- **Command list cleanup**: Removed unused fields (`alias`, `helpUrl`, `private`) from command information for better readability
- Better user experience with clearer tool descriptions
- Cleaner, more focused command list output
- Improved component discovery guidance
> feat: improve MCP remote search tool and cleanup command list output

- scopes/harmony/api-server/api-for-ide.ts
- scopes/harmony/api-server/api-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.spec.ts
This PR enhances the `getCompDetails` MCP tool with several improvements:
- Components now include a `url` field pointing to the component's web page
- Uses `ComponentUrl.toUrl()` to generate the URL without version
- Added `componentLocation` field that indicates where the component exists:
- "exists locally in the workspace at '{path}'" for local components
- "installed as a package" for components installed via package manager
- "a remote component" for components only available remotely
- Enhanced dependency information to include lifecycle, type, source, and component ID
- Format: `{package}@{version} (lifecycle: {lifecycle}, type: {type}, source: {source}, component-id: {id})`
> feat(mcp): enhance bit_component_details with URL, location status, and improved dependencies

- scopes/harmony/api-server/api-for-ide.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
This PR adds a new `laneId` property to the `bit_workspace_info` MCP tool that returns the current lane name with scope included.
> feat(mcp): add laneId property to bit_workspace_info tool

- scopes/mcp/cli-mcp-server/README.docs.mdx
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.spec.ts
- scopes/mcp/cli-mcp-server/mcp-server.cmd.ts
- scopes/mcp/cli-mcp-server/setup-cmd.ts
- scopes/mcp/cli-mcp-server/setup-utils.ts
This PR removes the `extended` (`-e, --extended`), `include-only` (`--include-only`), and `exclude` (`--exclude`) flags from the Bit CLI MCP Server component as they are no longer needed.
> feat(mcp): remove extended, include-only, and exclude flags from MCP server

- scopes/mcp/cli-mcp-server/README.docs.mdx
- scopes/mcp/cli-mcp-server/bit-rules-consumer-template.md
- scopes/mcp/cli-mcp-server/bit-rules-template.md
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/rules-cmd.ts
- scopes/mcp/cli-mcp-server/setup-utils.ts
Adds a new `rules` subcommand to the `bit mcp-server` command that creates rule/instruction files for AI assistants working with Bit components.
- Supports workspace and global rule file creation
- Editor-specific file paths and formats. Supports VS Code and Cursor.
- Template-based content generation for easy customization
- Consumer project mode with `--consumer-project` flag for projects that only consume Bit components as packages
- `--print` flag to simply print the instructions. Useful for unsupported IDEs, such as Windsurf that use one file for instructions.
> feat(mcp): add rules subcommand for AI assistant instruction files

- scopes/mcp/cli-mcp-server/README.docs.mdx
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.spec.ts
Combines the two existing MCP tools `bit_show` and `bit_schema` in consumer project mode into a single new tool called `bit_remote_component_details`. This simplifies the API for non-Bit workspaces that only consume Bit component packages.
> feat(mcp): combine bit_show and bit_schema into bit_remote_component_details in consumer project mode

- components/legacy/component-diff/components-object-diff.ts
- scopes/component/component/show/legacy-show/show-legacy-cmd.ts
This PR adds a "Package Name" field to the legacy `bit show --legacy --remote` command output.
> feat(show): add package name field to legacy show command output

- scopes/dependencies/pnpm/lockfile-deps-graph-converter.ts
Packages w/o dependencies should be correctly added to the lockfile
-
-
-
> fix: generating lockfile from graph

- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/setup-cmd.ts
This PR enhances the `bit mcp-server setup` command to display the path where configuration was written. 
The improved output makes it easier for users to locate and manually adjust configuration files if needed after setup is complete.
> feat(mcp-server): display config file path in setup command output

- components/entities/semantic-schema/schema-node.ts
- scopes/typescript/typescript/transformers/class-declaration.ts
This PR fixes an issue where the ClassDeclarationTransformer in the schema extractor was incorrectly identifying HTML class attributes within Vue Single File Components (SFCs) as TypeScript class declarations. This resulted in malformed schema being generated.
The fix improves the predicate function of the transformer by adding stricter checks for – A valid members list in the class declaration node, ensuring it's not flagged as isMissingList.
> fix(semantics): prevent false positives in ClassDeclarationTransformer

- e2e/harmony/dependency-resolver.e2e.ts
- scopes/component/snapping/version-maker.ts
- scopes/dependencies/dependencies/dependencies-loader/dependencies-versions-resolver.ts
Fixes bug where componentRangePrefix (^ or ~) was being applied to snap versions (hashes), creating invalid semver like `0.0.0-^hash`.
Now validates that versions are not snaps before applying range prefixes, ensuring snap versions remain as clean hashes.
> fix(deps): prevent range prefix application to snap versions creating invalid semver

- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.spec.ts
- scopes/mcp/cli-mcp-server/setup-cmd.ts
- scopes/mcp/cli-mcp-server/setup-utils.ts
Adds support for Roo Code extension to the `bit mcp-server setup` command. 
- Implements local `.roo/mcp.json` configuration support
- Shows warning for global configuration (uses VS Code internal storage)
> feat: add Roo Code extension support to MCP server setup

- workspace.jsonc
- update live control utils to add the second param in `postMessage(data, '*')` to support cross-origin messages on bit cloud preview pages
relevant CR: https://bit.cloud/teambit/vite/~change-requests/fix-live-controls-type-20250524
> chore: update live-control utils to fix cross-origin messages

- e2e/harmony/lanes/merge-lanes.e2e.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/lanes/merge-lanes/merge-lane.cmd.ts
- scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
This PR adds the `--loose` flag to the `bit lane merge` command, bringing consistency with other build-related commands like `bit build`, `bit snap`, and `bit test`.
As a reminder, this flag allows "--build" to succeed even if tasks like test or lint fail.
> feat: add --loose flag to bit lane merge command

- scopes/lanes/lanes/lane.cmd.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/lanes/lanes/switch.cmd.ts
Adds a new `--branch` flag to `bit lane import` that creates and checks out a new git branch named after the lane.
Features:
- Only creates git branch when flag is specified and git repository exists
- Sanitizes lane name to create valid git branch names
- Gracefully handles git command failures with warnings
> feat(lanes): add --branch flag to bit lane import command

- .circleci/config.yml
- scopes/git/ci/ci.main.runtime.ts
- scopes/git/ci/commands/merge.cmd.ts
- scopes/git/ci/commands/pr.cmd.ts
Integrates the new `bit ci` commands into CircleCI workflows to streamline CI/CD processes and replace manual command sequences with unified operations.
- **Added `bit_pr` job**: Runs `bit ci pr --build` on PR branches to handle feature lane creation, snapping, and export
- **Added `bit_merge` job**: Runs `bit ci merge --build` on master branch to handle tagging, export, and git operations  
- **Optimized workflows**: Eliminated redundant builds since CI commands include build functionality
- **Branch name sanitization**: Replace slashes with dashes to create valid Bit lane IDs (e.g., `feat/branch-name` → `feat-branch-name`)
- **Graceful no-changes handling**: Show friendly message instead of throwing error when no components have changed
- **Error vs warning distinction**: Only fail on …
> feat: integrate bit ci commands into CircleCI workflow

- .bitmap
- scopes/git/ci/ci.main.runtime.ts
Fixes the Git push error in `bit ci merge` by detecting the actual default Git branch instead of assuming it's `main`.
> fix(ci): detect default Git branch for push operation in bit ci merge

- scopes/workspace/install/link/component-list-links.ts
- scopes/workspace/install/link/core-aspects-links.ts
- scopes/workspace/install/link/link.cmd.ts
- Modified core-aspects output to show summary by default ("x core-aspects were linked")
- Added --verbose flag support for detailed core-aspects output
- Added --comp-summary flag to show component summary instead of full listing
> feat: reduce bit link verbosity with summary output by default

- .circleci/config.yml
Removes redundant setup and tagging jobs from both nightly and harmony_deploy workflows. Since component tagging/export is now handled by the merge workflow, these workflows can focus solely on creating Docker containers and BVM bundles from published packages.
Eliminates unnecessary setup_harmony, set_ssh_key, set_npm_registries, bit_tag, bit_export, and sleep_5_minutes jobs, reducing workflow complexity and execution time.
> refactor(ci): streamline nightly and harmony_deploy workflows

- scopes/mcp/cli-mcp-server/README.docs.mdx
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/rules-cmd.ts
- scopes/mcp/cli-mcp-server/setup-cmd.ts
- scopes/mcp/cli-mcp-server/setup-utils.ts
- Add Claude Code editor support to `bit mcp-server setup` and `bit mcp-server rules` commands
- Setup command creates `.mcp.json` files with proper platform-specific global paths
- Rules command creates `.claude/bit.md` safely without overwriting existing `CLAUDE.md` files
- Updated documentation with Claude Code configuration examples and integration instructions
> feat(mcp): add Claude Code support to bit mcp-server setup and rules commands

- scopes/git/ci/ci.main.runtime.ts
Fixes stale .bitmap issue when multiple PRs are merged in sequence. Adds git pull before bit operations to ensure each merge works with the latest component state from previous merges.
Prevents version conflicts and maintains component versioning consistency in rapid merge scenarios.
> fix(ci): pull latest changes before merge to prevent stale bitmap

- .circleci/config.yml
Adds serial-group to the bit_merge job to ensure only one merge operation runs at a time organization-wide. This prevents race conditions where multiple PRs merged quickly could cause parallel tagging of the same components with identical versions.
Jobs are queued in FIFO order with a 5-hour timeout, ensuring safe sequential execution of component versioning operations.
> fix(ci): serialize merge operations to prevent race conditions

- scopes/git/ci/ci.main.runtime.ts
Improves `bit ci merge` output messages to provide richer, more informative feedback similar to what users see when running `bit tag` and `bit export` commands individually.
**Changes made:**
- **Tag output**: Replaced generic "Tagged components" message with detailed tag summary using `tagResultOutput()` function, showing component names, versions, and auto-tagged dependencies
- **Export output**: Replaced generic "Exported components" message with specific component count ("Exported X component(s)" or "Nothing to export")
> feat(ci): improve tag and export output messages with detailed summaries

- scopes/harmony/graphql/graphql.main.runtime.ts
support for a customExecuteFn option in the graphqlHTTP middleware configuration. This allows developers to override the default GraphQL execute function with a custom implementation
> add customExecuteFn

- scopes/git/ci/ci.main.runtime.ts
Previously, the checkout-head step didn't have any id to checkout and it didn't write anything to the `.bitmap` file.
> fix(ci-merge): fix the checkout-head before snapping on main

- CLAUDE.md
- scopes/git/ci/ci.docs.mdx
- scopes/git/ci/ci.main.runtime.ts
- scripts/generate-merge-commit-message.js
- workspace.jsonc
Enables custom commit message generation for `bit ci merge` through workspace configuration.
- Adds `commitMessageScript` configuration option to `teambit.git/ci` aspect
- Executes custom script to generate commit messages when configured
- Includes script for Bit repository to maintain version-aware commit messages
- Falls back to default message when no script is configured
- Uses secure command execution without shell injection risks
Replaces hardcoded commit messages with configurable, repository-specific logic while keeping the CI command generic for all users.
> feat: add pluggable commit message generator for bit ci merge

- scopes/lanes/lanes/lanes.main.runtime.ts
This is for `bit lane import <lane-id> --branch` flag.
> fix(lane-import-branch): avoid changing the branch name. keep it the same as the lane-id

- scopes/harmony/api-server/api-for-ide.ts
- scopes/workspace/watcher/watch.cmd.ts
- scopes/workspace/watcher/watcher.main.runtime.ts
- scopes/workspace/watcher/watcher.ts
- scopes/workspace/workspace/workspace.ts
Fixes the issue where `bit watch` or the IDE extension shows "your workspace has outdated objects. please use 'bit import' to pull the latest objects from the remote scope".
This is happening when the user is running `git pull`, which updates `.bitmap` file, but the local scope objects are not updated yet ("bit import" is not run yet).
To fix it, this PR checks before those two operations whether there are out of date components against .bitmap, and if it found some, it fetches the objects for them.
> fix: avoid error ComponentsPendingImport when bit-watch or IDE extension starts

- .circleci/config.yml
Updates the CircleCI configuration to use "CI" as the user name instead of "tester" for better clarity and consistency in CI operations.
> feat: update CircleCI user name from tester to CI

- scopes/typescript/typescript/transformers/export-assignment.ts
This PR correctly extracts default exports and correctly links the type referenced via them. 
https://github.com/user-attachments/assets/f6f705db-5ed0-4281-b618-d14ae1a27388
> fix(schema): handle default export type references

- components/mcp/mcp-config-writer/mcp-config-writer.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.spec.ts
Fix ENOENT error when running `bit mcp-server rules` command.
The `cli-mcp-server` was looking for template files in its own directory, but they're located in the `mcp-config-writer` component.
- Remove `templateBaseDir` parameter from `McpConfigWriter` methods
- Let `McpConfigWriter` handle its own template file resolution internally
- Add test coverage to prevent regression
> fix(mcp): resolve template file path issue in cli-mcp-server rules command

- e2e/harmony/ci-commands.e2e.ts
- scopes/git/ci/ci.main.runtime.ts
This PR fixes a critical bug where `bit ci merge` would throw a TypeError when run while checked out to a lane:
```
Cannot read properties of undefined (reading 'scope')
```
- **Bug Fix**: Fixed the scope undefined error in `ci.main.runtime.ts` when `currentLane.id().scope` was accessed
- **Comprehensive E2E Tests**: Added realistic e2e tests for CI commands with proper git workflows
- **Edge Case Coverage**: Added specific test for the lane checkout scenario that was causing the bug
The new test suite covers:
- `bit ci pr` workflow with realistic git branches and commits
- `bit ci merge` workflow with proper git remote setup
- Multi-workspace scenarios simulating CI environments  
- **Edge case**: `bit ci merge` when checked out to a lane (the bug scenario)
> fix: resolve scope undefined error in ci merge when on lane

- components/legacy/e2e-helper/e2e-git-helper.ts
- e2e/harmony/ci-commands.e2e.ts
- e2e/harmony/lanes/lane-import-git-branch.e2e.ts
- scopes/component/merging/merging.main.runtime.ts
- scopes/git/ci/ci.main.runtime.ts
- scopes/lanes/lanes/lanes.main.runtime.ts
- scopes/lanes/lanes/switch.cmd.ts
Fixes the issue where `bit lane import <lane> --branch` would silently fail to create a git branch when a branch with the same name already exists.
- Modified `createGitBranchForLane` to return warning messages instead of just logging them
- Added `gitBranchWarning` property to `ApplyVersionResults` type for proper type safety  
- Updated switch command to display git branch warnings to the user with yellow styling
- Added e2e test `lane-import-git-branch.e2e.ts` that reproduces the original bug and validates the fix
- Test covers both success and failure scenarios for git branch creation
- Existing lane import functionality remains unchanged
> fix(lanes): show warning when git branch already exists during lane import with --branch

- .circleci/config.yml
CircleCI’s “split by timings” relies on per-testcase durations, but in our suite most time happens in before/after hooks, so testcase times are near-zero while the suite shows the full wall time. With no meaningful per-test weights, the splitter can’t balance work across 25 machines, leading to uneven distribution. 
I tried adding scripts to manually parse the XML file and change the timing, but it's not easy. It didn't work well.
> ci: change circle config back to split by filesize. splitting by timing did not work

- e2e/harmony/ci-commands.e2e.ts
- e2e/harmony/tag-harmony.e2e.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/tag-cmd.ts
- scopes/component/snapping/version-file-parser.ts
- scopes/component/snapping/version-maker.ts
- scopes/git/ci/ci.main.runtime.ts
- scopes/git/ci/commands/merge.cmd.ts
- Add `--versions-file` flag to `bit tag` and `bit ci merge` commands
- Support specifying component versions from a local file with format: `component-id: version` 
- Components not mentioned in the file receive default patch bump
- Add comprehensive e2e tests validating version assignment and status output
Create a versions file (e.g., `versions.txt`):
```
DEFAULT: minor
my-org.my-scope/button: 2.0.0
my-org.my-scope/input: 1.5.0
my-org.my-scope/header: major
```
Then use it with either command:
```bash
bit tag --versions-file versions.txt
bit ci merge --versions-file versions.txt
```
- **Comments**: Lines starting with `#` are ignored
- **Default version**: `DEFAULT: <version>` - applied to components not explicitly mentioned
- **Component versions**: `<component-id>: <version>` - …
> feat: add --versions-file flag to bit tag and bit ci merge commands

- .eslintrc.js
- e2e/harmony/ci-commands.e2e.ts
- scopes/component/snapping/version-file-parser.ts
- scopes/defender/prettier/prettier.formatter.ts
- workspace.jsonc
Cleans up ESLint configuration by removing unnecessary rules and the Airbnb plugin. Many rules were removed as they are no longer needed with current ESLint and TypeScript configurations.
> chore: update ESLint configuration rules

- .circleci/config.yml
Disables the windows-nightly workflow by commenting out its triggers section, as this workflow hasn't been working for a while now.
The workflow definition remains intact and can be easily re-enabled by uncommenting the triggers when needed.
> fix: disable windows-nightly workflow triggers

- e2e/harmony/update-cmd.e2e.ts
- scopes/dependencies/dependencies/dependencies-loader/apply-overrides.ts
Fixes an issue where dependencies would appear in multiple dependency fields (e.g., both peer and dev) when moving a dependency from one type to another in env.jsonc overrides.
This ensures that when a dependency is explicitly set in one field, it's properly removed from other dependency fields to prevent duplications in package.json.
Related to #9720
> fix(deps): prevent duplicate dependencies when overriding dep types in env.jsonc

- package.json
Update dependencies in package.json and pnpm-lock.yaml to keep them up to date.
> chore(deps): bump oxlint to 1.11.2

- .circleci/config.yml
- scopes/git/ci/ci.main.runtime.ts
- scopes/git/ci/commands/merge.cmd.ts
Add support for `--auto-merge-resolve` and `--force-theirs` flags to the `bit ci merge` command, providing more flexible merge conflict resolution strategies during CI operations.
- **Added `--auto-merge-resolve` flag** with support for `ours`, `theirs`, and `manual` strategies
- **Added `--force-theirs` flag** to overwrite with incoming files without merging
- **Implemented conflict detection** for manual merge strategy with clear user guidance
- **Updated default behavior** to preserve backward compatibility while enabling new options
- **Updated CircleCI config** to use `--auto-merge-resolve manual` for safer merge operations
> feat: add --auto-merge-resolve and --force-theirs flags to bit ci merge

- scopes/preview/preview/generate-link.ts
- scopes/preview/ui/component-preview/preview.tsx
- scopes/preview/ui/component-preview/use-iframe-content-height.tsx
This PR does two things:
- **Performance:** adds a `__bitShouldSurfaceFor(...)` gate so each preview iframe imports only its own active composition (others become cheap placeholders).
- **Error Overlay:** adds `__bitSurfaceToOverlay(...)` to surface load errors only for the active component in that iframe, without breaking the UI fallback.
Previously, every iframe ran:
```
await import('.../compA.compositions.js')
await import('.../compB.compositions.js')
...
await import('.../compN.compositions.js')
```
This caused:
- Massive network overhead – hundreds of chunk requests per iframe.
- High CPU cost – V8 parsed/executed every composition and its dependencies in every iframe.
- React Refresh load – module wrapping and HMR bookkeeping for all compositions.
- CSS injection & layout work – …
> perf(preview): import + surface errors for only the active component's composition per iframe

- .circleci/config.yml
- scopes/pkg/pkg/publisher.ts
During `bit ci merge`, npm publishing fails with 409 Conflict errors when multiple `@teambit` components are published in parallel:
```
npm error 409 Conflict - PUT https://registry.npmjs.org/@teambit%2fgraph - Failed to save packument. A common cause is if you try to publish a new package before the previous package has been fully processed.
```
- **Maintain parallel publishing performance** (10 concurrent publishes)
- **Add smart retry logic** specifically for npm 409 registry conflicts  
- **Use exponential backoff** to avoid overwhelming npm registry
- **Configurable retry settings** via environment variables
> fix: add retry logic for npm 409 publish conflicts

- .bitmap
The fix was done in this CR: https://bit.cloud/teambit/typescript/~change-requests/fix-exclude-non-project-reference
This PR upgrades the core-aspect-env to 0.0.76 in order to apply the fix.
> fix: avoid generating esm.d.mts for core aspects

- package.json
This PR adds the `oxlint:with-ts-react` script to `package.json` to enable type-aware linting with React support.
> chore(scripts): add oxlint:with-ts-react script

- scopes/defender/linter/linter.service.ts
- scopes/defender/linter/linter.ts
- scopes/envs/envs/env-service-list.ts
- scopes/envs/envs/environments.main.runtime.ts
- scopes/envs/envs/envs.cmd.ts
This change updates the linter to support an asynchronous `version()` method. This allows linters to fetch their version information dynamically.
> fix(linter): support async version for linter

- scopes/harmony/application/run.cmd.ts
This change introduces a new feature to the 'bit run' command.
Key changes:
- The browser will now open automatically by default when running an application.
- A '--no-browser' flag has been added to disable this new default behavior.
> feat(application): add support for automatically opening browser on bit run

- scopes/component/isolator/isolator.main.runtime.ts
Previously when running commands with `--reuse-capsules` (which sets `getExistingAsIs` to true), if the capsule directory didn't exist yet, the process would only create the capsules and return them without completing the full capsule preparation process (e.g., package installation wouldn't run).
This fix checks if the directory exists and automatically sets `getExistingAsIs` to false when the directory is missing, ensuring the complete capsule setup process runs correctly.
> fix(isolator): disable getExistingAsIs when capsule directory missing

- scopes/scope/importer/fetch-cmd.ts
- scopes/scope/importer/importer.main.runtime.ts
- Implement `fetchUsingScope` method that enables fetch operations outside workspace context
- Modify the existing `fetch` method to gracefully fallback to `fetchUsingScope` when no workspace is available
- Update fetch command to handle both workspace and scope-only operations
This enables users to run `bit fetch` commands from bare-scopes. It can be very helpful when things go wrong and objects of other scopes are missing for some reason in this scope.
> feat(importer): enable fetch to work without workspace

- components/mcp/mcp-config-writer/bit-git-rules-template.md
- components/mcp/mcp-config-writer/mcp-config-writer.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/rules-cmd.ts
This PR introduces Git-integrated Bit MCP rules to support workspaces where Git is the source of truth for version control and CI/CD handles Bit operations.
- **New Template**: Created `bit-git-rules-template.md` specifically for Git-integrated Bit workspaces
- **Smart Detection**: Modified `mcp-config-writer` to automatically detect `.git` directory and use the appropriate template
- **Git-First Workflow**: Updated rules to use Git branches instead of Bit lanes for collaboration
- Removes local versioning commands (`bit snap`, `bit tag`, `bit export`) - handled by CI/CD
- Replaces Bit lanes workflow with standard Git branch workflow  
- Maintains all component creation, reuse, and development best practices
- Focus on local development while CI handles publishing
When users run `bit mcp …
> feat: add Git-integrated Bit MCP rules template

- scopes/git/ci/ci.main.runtime.ts
- scopes/git/ci/commands/merge.cmd.ts
- scopes/git/ci/commands/pr.cmd.ts
- scopes/git/ci/source-branch-detector.ts
Enhances `bit ci merge` to automatically detect and delete lanes even when running on the main branch after PR merge - a common CI scenario where environment variables are unavailable.
- **Problem**: `bit ci merge` couldn't delete lanes when CI runs on main after PR merge because `GITHUB_HEAD_REF` and similar vars are only available during pull_request events, not push events
- **Solution**: Added `SourceBranchDetector` utility that uses GitHub API + commit message parsing to identify the merged source branch
- **Benefit**: Enables automatic lane cleanup in typical CI workflows without manual intervention
✅ **GitHub API Integration** - Queries PR info from commit SHA (works post-merge)  
✅ **Multi-Platform Support** - GitHub Actions, CircleCI, git remote parsing  
✅ **Open Source …
> feat: enhance lane deletion in ci merge for main branch scenarios

- scopes/mcp/cli-mcp-server/README.docs.mdx
- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/cli-mcp-server.spec.ts
- Enhance bit_component_details tool to support multiple component IDs in parallel
- Limit to 5 components max to prevent context overload  
- Strict validation with clear error messages when limits exceeded
- Individual component failures don't block entire requests
- Change parameter from `componentName` (string) to `componentIds` (array)
- Add parallel processing using Promise.all() similar to remote search
- Enhanced error handling with per-component failure tracking
- Updated examples to use full component IDs (e.g., acme.design/ui/button)
> feat(mcp): add batch support to bit_component_details tool

- .github/instructions/bit.instructions.md
- CLAUDE.md
- Adds instructions in `.github/instructions/bit.instructions.md` to this repo by running `bit mcp-server rules` (this is the Git-Integrated Workflow rules).
- References new instructions file from `CLAUDE.md` for consistent AI assistant context
- Consolidates documentation by removing redundant content from `CLAUDE.md`
> feat: add bit instructions reference and consolidate documentation

- components/mcp/mcp-config-writer/bit-git-rules-template.md
Add conditional installation instructions to MCP rule templates to support external package manager mode.
When `externalPackageManager: true` is set in workspace config, AI assistants will use npm/yarn/pnpm instead of `bit install`.
- Added "Installation Commands" section with conditional logic to rule templates
- Simple approach that AI can interpret dynamically without complex processing
> feat(mcp): add external package manager support to MCP rules

- scopes/mcp/cli-mcp-server/README.docs.mdx
- Streamline installation section to focus on `bit mcp-server setup` rather than `start` command
- Add recommended setup steps for new users including scope setting, rules generation, and VS Code configuration tips
- Remove duplicate sections, verbose examples, and unnecessary content to improve readability
- Consolidate introduction and overview sections into a single clear description
> docs(mcp): improve MCP server documentation clarity and organization

- scopes/harmony/doctor/doctor.main.runtime.ts
Fixes an issue where `bit doctor --archive` creates a tar file with only the contents of the current directory when run from a nested folder instead of archiving the entire workspace.
The problem was that the code used `tarFS.pack('.')` which packs from the current working directory. Now it uses the workspace root path obtained from `getWorkspaceInfo()`.
> fix: use workspace root for doctor archive when run from nested directory

- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- scopes/mcp/cli-mcp-server/rules-cmd.ts
- Enhanced the `bit mcp-server rules` command to display the file path where rules are written
- Now all editors (Cursor, VS Code, Roo, Cline, etc.) show the path consistently, similar to how the `setup` command works
> fix: display file path when running 'bit mcp-server rules' command

- .circleci/config.yml
Reduces CircleCI resource class from 2xlarge to xlarge for bit_pr and bit_merge jobs to optimize resource usage while maintaining build performance.
The previous 2xlarge configuration is preserved in comments for easy rollback if needed.
> ci: reduce CircleCI resource class from 2xlarge to xlarge

- .circleci/config.yml
- Added Slack orb (v5.2.3) to CircleCI configuration
- Configured failure-only notifications for bit_merge job on master branch
- Added prominent alert with 🚨 emoji for master failures
The existing webhook that was sending all build notifications (success and failure) has been disabled. This PR replaces it with targeted failure-only notifications specifically when the bit_merge job fails on master branch, ensuring only critical failures are reported to the #bit-ci channel.
> feat: add Slack notifications for master branch failures

- scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
- Added validation in the MCP execute tool to prevent execution of lane switch and merge commands
- Commands `lane switch`, `lane merge`, and `switch` (alias) are now restricted from MCP execution
- These commands must be run directly in the terminal for better user visibility and control
- Modified `registerExecuteTool` method in `cli-mcp-server.main.runtime.ts` to check for and restrict lane switch/merge commands
- Returns clear error messages indicating these workspace-modifying operations must be run in the terminal
The `lane switch` and `lane merge` commands are heavy operations that modify workspace state. By restricting them to terminal execution, we ensure users have full visibility and control when these commands are run, as they will need to execute them directly in the terminal …
> feat(cli-mcp-server): restrict lane switch and merge commands to terminal execution

- .bitmap
- workspace.jsonc
This package was recently aligned with others to have the same Typescript version - 5.9.2.
> chore: update all envs to get the latest of @teambit/defender.eslint-linter

- e2e/commands/tag.e2e.1.ts
- scopes/component/snapping/snap-cmd.ts
- scopes/component/snapping/snapping.main.runtime.ts
- scopes/component/snapping/tag-cmd.ts
- scopes/component/snapping/version-maker.ts
Fixes incorrect component count display in `bit tag` and `bit snap` when a new component depends on a modified component.
When tagging components, if a new component depends on a modified component, the new component appears in both:
- The "new components" section
- The "auto-tagged dependents" section under the modified component
This caused the total count to be inflated (e.g., showing "3 component(s) tagged" when only 2 components were actually tagged).
Added a `totalComponentsCount` property to track the actual number of components tagged/snapped:
- Calculated from `allComponentsToTag.length` in version-maker, which already excludes duplicates
- Passed through the tag/snap pipeline
- Used in the output display with a fallback to the old calculation for backward compatibility
> fix: correct component count when new component depends on modified component

- .bitmap
- e2e/harmony/validate.e2e.ts
- scopes/defender/validator/index.ts
- scopes/defender/validator/validate.cmd.ts
- scopes/defender/validator/validator.aspect.ts
- scopes/defender/validator/validator.main.runtime.ts
- scopes/harmony/bit/manifests.ts
Adds a new `bit validate` command that runs check-types, lint, and test in sequence.
- Created new validator aspect in `scopes/defender/validator`
- Command stops at first failure and returns non-zero exit code (use `--continue-on-error` to run all checks)
- Shows detailed error output for each validation step
- By default validates only new/modified components, use `--all` for all components
```bash
bit validate                     # Validate modified/new components
bit validate --all               # Validate all components
bit validate --continue-on-error # Run all checks even when errors are found
bit validate [pattern]           # Validate specific components
```
> feat: add validate command

- e2e/harmony/build-cmd.e2e.ts
- scopes/pipelines/builder/build-pipeline-order.ts
Fixes an issue where `bit build --tasks <non-existent-task>` would show a misleading success message instead of an error.
**Before:**
```
✔ Running build pipeline using 6 environment(s), total 0 tasks. Succeeded in 10s
```
**After:**
```
Pipeline error - no tasks found matching the specified filter: "non-existent-task". Available tasks: BabelCompile, JestTest, teambit.compilation/compiler, teambit.defender/tester, ...
```
**Changes:**
- Added validation in `calculatePipelineOrder()` to check if task filtering resulted in an empty queue
- Error message now shows which tasks were requested and lists all available tasks
- Added e2e test to verify the error is thrown correctly
> fix: show error when --tasks flag doesn't match any tasks in build command
