teambit/bit

scopes/react/react/jest/transformers/base-transformer-plugins.js
scopes/react/react/jest/transformers/cjs-transformer.js
scopes/react/react/jest/transformers/esm-transformer.js
scopes/react/react/react.env.ts

restore @babel/runtime and core-js dependencies to not make all components modified

---

.eslintrc.js
package.json
pnpm-lock.yaml
scopes/react/eslint-config-bit-react/bit-react-eslint.js
scopes/react/eslint-config-bit-react/component.json

- upgrade eslint-config-prettier to v8.5.0
- add eslint-config-prettier to bit-react-eslint
- disable 'no-underscore-dangle' eslint rule

lint prettier rules

---

scopes/generator/generator/generator.main.runtime.ts
scopes/typescript/typescript/typescript.extractor.ts

fix loading workspace templates from remote scope with new env

---

scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts

fix: install dev deps to capsules when root components are used

---

scopes/ui-foundation/ui/create-root.ts

take named export from aspect when generating link file for webpack

---

src/consumer/component-ops/add-components/add-components.ts

improvement(add): enable tracking files that start with dot

---

scopes/generator/generator/generator.main.runtime.ts

pass aspect component when using bit new with --load from

---

scopes/component/isolator/capsule-list.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/component/isolator/network.ts
scopes/scope/sign/sign.main.runtime.ts
scopes/workspace/install/install.main.runtime.ts

fix(build): recompile components with build-status failed

---

scopes/preview/ui/component-preview/preview.tsx
scopes/ui-foundation/use-box/dropdown/dropdown.composition.tsx
scopes/ui-foundation/use-box/dropdown/dropdown.module.scss

- preview fires onload fires event when iframe loads
- use box z-index fix

usebox z-index fix and preview onload event

---

scopes/scope/scope/ui/scope-overview/scope-overview.tsx

override scope overview

---

scopes/harmony/cli/cli.aspect.ts

add export default to CLIAspect

add export default to CLIAspect

---

src/logger/pino-logger.ts

utilize pino transport (Worker Thread)

---

workspace.jsonc

updated component highlighter not to use z-indexes component

---

scopes/dependencies/dependency-resolver/policy/variant-policy/variant-policy.ts

support variant config policy as array of object with name, version, hidden, force

---

scopes/component/component/component-factory.ts
scopes/envs/envs/environments.main.runtime.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/workspace/workspace/workspace.ts

correctly resolve aspect def for plugins envs

---

scopes/lanes/lanes/lanes.ui.runtime.tsx
scopes/lanes/ui/models/lanes-model/lanes-model.ts

- Handle resolving component id from url for components from a different scope than the lane scope

Lanes: Fix: Resolve Comp ID from Url

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

make @teambit/legacy always a peer dependency with ^

---

scopes/component/graph/graph-builder.ts

fix converting graph to toComponentGraph - handle runtime edges correctly

---

scopes/dependencies/yarn/yarn.package-manager.ts

pass pnpUnpluggedFolder to fix error on yarn install as a result of change in @yarnpkg/plugin-pnp (3.2.5 or 3.2.6)

---

e2e/harmony/snap-from-scope.e2e.ts
scopes/component/snapping/snap-from-scope.cmd.ts
scopes/component/snapping/snapping.main.runtime.ts
scopes/lanes/lanes/lanes.main.runtime.ts
scopes/scope/importer/importer.main.runtime.ts
src/e2e-helper/e2e-command-helper.ts

- support snapping from scope on a lane
- introduce `--json` to output as json format

feat(snap-from-scope): support lanes and support json

---

scopes/react/react-native/react-native.env.ts

add react-native-web as host dependency

---

src/scope/objects/repository.ts
src/scope/scope.ts

-  support reload scope's index.json if current `scopeIndex` difference with <scope_folder>/index.json content

feat: support reload scope's index.json if need

---

scopes/component/status/status-cmd.ts
src/scope/lanes/remote-lanes.ts

also, add some logs around writing refs files to debug corruption issues with these files.

improvement(status): suggest adding --lanes flag when on a lane

---

scopes/dependencies/dependency-resolver/index.ts
scopes/dependencies/yarn/yarn.package-manager.ts

feat: setting packageImportMethod for Yarn

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

do not resolve component dep version from model if it's in its policy

---

scopes/envs/envs/index.ts
scopes/envs/envs/services/index.ts
scopes/envs/envs/services/service-handler.ts
scopes/preview/preview/preview-env.ts

- add new AsyncEnvHandler<T> type
- Make getDevServer and getBundler return EnvHandler or AsyncEnvHandler

async env handler

---

scopes/dependencies/dependencies/dependencies-cmd.ts
scopes/dependencies/dependencies/dependencies.main.runtime.ts
scopes/scope/scope/scope.main.runtime.ts

To help understanding when a dependency was changed/added/removed.

feat(deps-blame): introduce a new command "bit deps blame"

---

package.json
workspace.jsonc

upgrade bvm list and bvm config deps

---

scopes/preview/preview/index.ts

- export component preview type

export component preview type

---

scopes/dependencies/pnpm/lynx.ts

perf: do not build core-js

---

scopes/generator/generator/component-generator.ts
scopes/generator/generator/component-template.ts
scopes/react/react/templates/react-hook/files/index-file.spec.ts

add aspectId and envId to component template context

---

e2e/bitsrc-tester.ts
scopes/cloud/cloud/cloud.main.runtime.ts
scopes/component/snapping/tag-model-component.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/dependency-resolver/index.ts
src/cli/commands/public-cmds/login-cmd.ts
src/cli/templates/eject-template.ts
src/constants.ts
src/e2e-helper/e2e-config-helper.ts
src/remotes/remote-resolver/remote-resolver.ts

Allow configuring via bit config cloud_domain and symphony_url

---

scopes/semantics/schema/schema.main.runtime.ts
scopes/semantics/schema/schema.service.ts

register schema service

---

scopes/envs/envs/envs.cmd.tsx

add services flag to bit envs get <component> command to filter output results

---

scopes/dependencies/dependency-resolver/dependencies/dependency-list-factory.ts
src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

- make sure to not add components set with bit deps set as packages
- use `getIssueByName` instead of `getIssue` to prevent bit from bvm and from repo compatibility

make sure to not add components set with bit deps set as packages

---

scopes/harmony/bit/bin/bit

bit CLI is executed with the --experimental-vm-modules option

---

scopes/harmony/application/application.main.runtime.ts

improve application metadata type

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts

fix: update should skip packages that are not yet in the registry

---

scopes/typescript/typescript/schema-extractor-context.ts
scopes/typescript/typescript/transformers/export-declaration.ts

fix(Schema): Find file in component + Export * from node modules

---

scopes/component/forking/fork.cmd.ts
scopes/component/forking/forking.main.runtime.ts

feat(fork): introduce --rename flag to rename files and variables/classes

---

scopes/scope/scope/scope.main.runtime.ts

This change was done by @ranm8 .

only apps should load themselves as aspects, not all aspects

---

scripts/docker-teambit-bit/Dockerfile-symphony

Revert "Update Dockerfile-symphony"

---

scopes/pipelines/builder/pipeline.ts

fix pipeline remove and replace APIs

---

scopes/compilation/compiler/compiler.main.runtime.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/generator/generator/generator.main.runtime.ts
scopes/generator/generator/templates/component-generator/files/main-runtime.ts
scopes/harmony/aspect/aspect.main.runtime.ts
scopes/harmony/node/node.main.runtime.ts
scopes/html/html/html.main.runtime.ts
scopes/mdx/mdx/mdx.main.runtime.ts
scopes/pipelines/builder/builder.main.runtime.ts
scopes/react/react-native/react-native.main.runtime.ts
scopes/react/react/react.main.runtime.ts

ensure generator is loaded before register slot

ensure generator is loaded before register slot

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

set peers deps correctly if they were set with force false and removed from runtime/dev

---

src/consumer/component/dependencies/files-dependency-builder/detectives/detective-typescript/index.ts

See https://github.com/teambit/bit/pull/6980#issuecomment-1409462546 for more context.

fix, add importSpecifiers only when the dependency was added

---

scopes/webpack/webpack/webpack.dev-server.ts

support getting an instance of webpack dev server instead of path to it (for backward compatibility)

---

.circleci/config.yml

- generate Linux-arm64 version on circleci
- related to #6967

linux arm64

---

scopes/preview/preview/env-preview-template.task.ts
scopes/preview/preview/preview.service.tsx
scopes/webpack/webpack/webpack.main.runtime.ts

- support getTemplateBundler for new envs
- add isEnvTemplate to GlobalWebpackConfigTransformContext

env template bundler transform

---

scripts/docker-teambit-bit/Dockerfile-symphony

Update Node.js in Dockerfile-symphony

---

scopes/compilation/bundler/bundler-context.ts
scopes/preview/preview/env-preview-template.task.ts
scopes/webpack/webpack/webpack.main.runtime.ts

- add isEnvTemplate to bundler context metadata
- pass isEnvTemplate to transform context in create bundler

env template bundler fixes

---

scopes/harmony/bit/bin/bit
scripts/docker-teambit-bit/Dockerfile-symphony

fix: use -S to pass options in shebang lines

---

components/ui/component-compare/compare-aspects/compare-aspect-view/compare-aspect-view.module.scss
components/ui/component-compare/compare-aspects/compare-aspects/compare-aspects.module.scss
components/ui/component-compare/compare-aspects/compare-aspects/compare-aspects.tsx
scopes/code/ui/code-compare/code-compare-view/code-compare-view.module.scss
scopes/code/ui/code-compare/code-compare.module.scss
scopes/component/component-compare/component-compare.ui.runtime.tsx
scopes/lanes/lanes/lanes.ui.runtime.tsx
scopes/lanes/ui/compare/lane-compare-drawer/lane-compare-drawer-name.module.scss
scopes/lanes/ui/compare/lane-compare-drawer/lane-compare-drawer-name.tsx
scopes/lanes/ui/compare/lane-compare-drawer/lane-compare-drawer.tsx
scopes/lanes/ui/compare/lane-compare-page/lane-compare-page.module.scss
scopes/lanes/ui/compare/lane-compare-page/lane-compare-page.tsx
scopes/lanes/ui/compare/lane-compare/lane-compare.module.scss
scopes/lanes/ui/compare/lane-compare/lane-compare.tsx
scopes/ui-foundation/tree/drawer/drawer.tsx

https://user-images.githubusercontent.com/8999604/216722040-6e69d939-45f8-419d-bef6-d38bbd9933f9.mov

feat(Lane): Compare: full screen + fixes

---

src/logger/pino-logger.ts

fix printing logs as json

---

e2e/harmony/imported-component-deps.e2e.ts
e2e/harmony/root-components.e2e.ts
scopes/dependencies/aspect-docs/dependency-resolver/dependency-resolver.mdx
scopes/workspace/install/install.cmd.tsx

bit install should always update existing policies

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts

feat: add packageName to dependency resolver component data

---

scopes/lanes/lanes/create-lane.ts

limit lane-lane length

---

e2e/harmony/install.e2e.ts
e2e/npm-ci-registry.ts
scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
scopes/workspace/install/install.cmd.tsx
scopes/workspace/install/install.main.runtime.ts

feat: install should support the --no-optional option

---

.bitmap
scopes/dependencies/modules/packages-excluder/generate-node-modules-pattern.spec.ts
scopes/dependencies/modules/packages-excluder/generate-node-modules-pattern.ts
scopes/dependencies/modules/packages-excluder/packages-excluder.composition.tsx
scopes/dependencies/modules/packages-excluder/packages-excluder.docs.md

bump teambit.dependencies/modules/packages-excluder to version 0.0.68

---

scopes/pipelines/builder/builder.service.tsx

It was switched. Tag was running the snap-pipeline and Snap was running the tag pipeline.

fix, run the proper the pipeline for snap/tag in the new env

---

.circleci/config.yml
scopes/compilation/bundler/bundler.main.runtime.ts
scopes/compilation/bundler/dev-server.service.tsx
scopes/compilation/bundler/dev-server.ts

- Add new slot for dev server transformer
- Call slot function to transform dev server from aspect

Add & use dev server transformer aspect slot

---

scopes/pkg/pkg/publisher.ts

fix(tag): it should be possible to publish packages when 2FA is required

---

.circleci/config.yml

drop docker with node 12 in circle as bvm requires node 14 now

---

e2e/harmony/install.e2e.ts
pnpm-lock.yaml
workspace.jsonc

test: update the registry mock

---

scopes/lanes/lanes/lane.cmd.ts

feat(Lane): CLI: create cmd: add note to lane create output if branched off non default lane

---

.bitmap
scopes/html/modules/render-template/index.ts
scopes/html/modules/render-template/render-template.ts
workspace.jsonc

-  teambit.html/modules/render-template
- set version to be 0.0.104 - before lit refactor to support html properly
-

chore - eject teambit.html/modules/render-template

---

e2e/harmony/lanes/lanes.e2e.ts
scopes/component/snapping/tag-model-component.ts
scopes/scope/importer/importer.main.runtime.ts
src/consumer/component/sources/artifact-files.ts
src/scope/scope.ts

otherwise, in some scenarios it is not able to find them in the lane-scope.

fix, fetch artifacts from main if possible

---

scopes/preview/ui/component-preview/urls.ts

- fix including envId in preview url

fix(Preview): EnvId in preview url

---

scopes/component/forking/fork.cmd.ts
scopes/component/forking/forking.main.runtime.ts

and introduce a new flag `--preserve` to opt out.

improvement(fork): change "--rename" flag to be the default

---

scopes/component/component/component.ui.runtime.tsx

fix(Component UI): consume plugin: display version for bit import, snap

---

e2e/harmony/lanes/lanes.e2e.ts
scopes/component/checkout/checkout-cmd.ts
scopes/component/checkout/checkout.main.runtime.ts

introduce a new flag `--workspace-only` to opt out.

improvement(checkout): make the --entire-lane flag the default

---

scopes/typescript/ts-server/ts-server-client.ts

- fix resolving tsserver client

fix(semantics): resolving tsserver client

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

fix: install missing type dependencies on the first iteration of install

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

fix: don't install second time because a peer has been removed

---

workspace.jsonc

- update loader-utils to fix audit issue
- update webpack-dev-server for audit issue

security(deps) - update dependencies to fix security issues

---

src/consumer/component/consumer-component.ts

- update the homepage field added to a component's package.json so it reflects the current remote domain (not hard-coded to the old bit.dev domain)
-
-

Fix homepage in packagejson

---

scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
scopes/workspace/workspace/workspace-aspects-loader.ts

- This also fixes issues with pnpm lock file getting changed on the second bit install when you have custom envs in your workspace

fix(aspects) - load non loaded aspects from components

---

e2e/harmony/lanes/lanes.e2e.ts

When checked out to a lane, only main components can be imported. This test verifies that when you explicitly import a snap from another lane, it doesn't change the lane object to that snap.

test(import), make sure that importing from one lane to another is not possible

---

.bitmap
components/ui/navigation/lane-switcher/index.ts
components/ui/navigation/lane-switcher/lane-switcher.module.scss
components/ui/navigation/lane-switcher/lane-switcher.tsx
scopes/code/ui/code-compare/code-compare-view/code-compare-view.tsx
scopes/lanes/lanes/lanes.ui.runtime.tsx
workspace.jsonc

- fix calculating height for diffEditor
- allow passing useLanes to LaneSwitcher

fix(ui): lane selector and code compare

---

.circleci/config.yml

upgrade node to v16.16 on windows for circle ci

---

scopes/dependencies/yarn/yarn.package-manager.ts

fix: yarn global cache creation failure on Windows

---

scopes/envs/envs/environments.main.runtime.ts

resolve env version when returning env descriptor from component graphql

---

src/api/scope/lib/fetch.ts
src/scope/objects/objects-readable-generator.ts

Log the duration, memory consumption and open connections.

log, improve logging of fetch process

---

.circleci/config.yml

make export running before bundling on depoly/nightly

---

scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts

fix: add missing deps that are present in root policies to component manifests

---

package.json

remove sqlite packages

---

src/scope/objects-fetcher/objects-writable-stream.ts

Currently, when importing 10 components, it writes each one of them individually and every time it updates the index.json and the refs. 
With this PR, it keeps these objects in-memory and then write them at once and updates index.json at once

write index.json once all model-components arrived

---

scopes/compilation/bundler/dev-server.graphql.ts
scopes/component/component/ui/component-model/component-model.ts
scopes/preview/ui/component-preview/urls.ts

- calculate preview url based on host and basePath if provided
- add host: String basePath: String to ComponentServer GraphqlSchema
- add host: String basePath: String to the component model

improvements(urls) - calculate preview url based on server host and basePath

---

src/consumer/bit-map/bit-map.ts

Tested on a workspace where this method got called 214,846 times. Before this fix it took 16 seconds. With this fix it's 351ms.

perf, improve "getExistingBitId" performance by caching ids as string

---

scopes/component/component/ui/use-component-query.ts

improvement(component gql) - update use component query to fetch host and base path

---

package.json
scopes/dependencies/yarn/yarn.package-manager.ts
scripts/install.js
src/constants.ts
src/registry/registry.ts
src/scope/scope-loader.ts
src/utils/os-resolve-home-path.ts

refactor, remove the deprecated user-home package

---

scopes/defender/eslint/eslint-config-writer.ts

fix(ws-config) - write path to tsconfig in generated eslint project prop with abs path

---

scopes/typescript/typescript/cmds/write-tsconfig.cmd.ts

remove(write-tsconfig-cmd) - hide write-tsconfig cmd in favor of ws-config write command

---

scopes/preview/preview/preview.main.runtime.tsx

fix(preview) - fix calculation of does scaling for components that are envs themselves

---

src/scope/component-ops/scope-components-importer.ts

Otherwise, quick fetch are locked due to some slow ones unnecessarily.

fix(fetch), avoid locking the fetch when preferDepsGraph is on

---

scopes/component/isolator/capsule-list.ts

The existing capsule list toposort only takes into account packages marked as "components", but unfortunately that doesn't include component peer dependencies (which will always marked as packages instead of components).
This PR will check package names against components of the current capsule list to include peer deps as well.

fix capsule list toposort to include peer dependencies

---

scopes/react/react/apps/web/react-app-options.ts
scopes/react/react/apps/web/react.app-type.ts
scopes/react/react/apps/web/react.application.ts

feature(react-apps) - support passing paths to webpack and webpack-dev-server modules for react apps

---

scopes/preview/preview/env-preview-template.task.ts

fix(env-template-task) - correctly resolve peer deps for new envs for preview-template-task

---

e2e/harmony/install-missing-dependencies.e2e.ts
scopes/dependencies/dependency-resolver/index.ts
scopes/workspace/install/install.cmd.tsx
scopes/workspace/install/install.main.runtime.ts

feat: installing missing dependencies

---

e2e/harmony/dependencies/never-built-dependencies.e2e.ts
scopes/dependencies/aspect-docs/dependency-resolver/dependency-resolver.mdx
scopes/dependencies/dependency-resolver/dependency-installer.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
scopes/dependencies/yarn/yarn.package-manager.ts
scopes/workspace/install/install.main.runtime.ts

feat: neverBuiltDependencies

---

scopes/webpack/config-mutator/config-mutator.ts

fix(webpack types) - make webpack config mutators types more releaxed

---

scopes/dependencies/pnpm/pnpm.package-manager.ts

perf(install) - do not reload components in case pnpm didn't install anything on first iteration

---

scopes/dependencies/pnpm/lynx.ts

internal(pnpm errors) - write original pnpm error to debug.log

---

scopes/lanes/lanes/lane.cmd.ts
scopes/lanes/lanes/lanes.main.runtime.ts
scopes/workspace/workspace/workspace.ui.drawer.tsx
src/scope/network/http/http.ts

- fix `lane show [lane-name] --remote` cmd to correctly show the lane data of the remote lane

fix(lanes): show remote lane cmd

---

scopes/preview/preview/bundler/html-template.ts

- override `body` styles in preview html template

fix(preview): override body browser defaults in html template

---

scopes/ui-foundation/uis/top-bar/top-bar.module.scss

Change scope top bar zIndex to be one under the main topbar

---

scopes/ui-foundation/uis/top-bar/top-bar.module.scss

Rollback #7443 
No need to change it. I'll use `createPortal` to inject the base modal where I need it.

Change topbar zindex

---

components/ui/gallery/lane-gallery.tsx
scopes/scope/ui/empty-scope/empty-scope.tsx
scopes/ui-foundation/empty-component-gallery/empty-component-gallery.composition.tsx
scopes/ui-foundation/empty-component-gallery/empty-component-gallery.tsx
scopes/workspace/ui/empty-workspace/empty-workspace.tsx

fix(ws): empty comps gallery

---

scopes/compositions/compositions/compositions.tsx
scopes/compositions/compositions/ui/composition-preview.tsx
scopes/compositions/compositions/ui/compositions-panel/compositions-panel.tsx

fix(preview) - fix preview url for old components

---

scopes/defender/formatter/format.cmd.ts

fix(format) - exit with code 1 when bit format --check found errors

---

scopes/component/isolator/isolator.main.runtime.ts

refactor: remove useNesting check that is always false

---

e2e/harmony/sign.e2e.ts
scopes/envs/envs/environment.ts
scopes/harmony/node/node.env.ts
scopes/react/react/react.env.ts
scopes/semantics/schema/schema.main.runtime.ts
scopes/semantics/schema/schema.task.ts
scopes/typescript/ts-server/process-based-tsserver.ts
scopes/typescript/ts-server/ts-server-client.ts
scopes/typescript/typescript/schema-extractor-context.ts
scopes/typescript/typescript/typescript.extractor.ts
scopes/typescript/typescript/typescript.main.runtime.ts

- Fix extracting schema on bare scope as part of the build process during bit sign

fix(semantics): running schema extractor on bare scope

---

README.md

Update README.md with new logo and updated slack link

---

.circleci/config.yml

fix circle ci (install zstd)

---

.circleci/config.yml

chore(circle-ci) - remove installing zstd from circleci

---

scopes/component/checkout/checkout.main.runtime.ts
scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
scopes/scope/importer/import-components.ts
scopes/workspace/workspace/workspace.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/models/model-component.ts

replace occurrences with importWithoutDeps.

refactor, remove the deprecated method importManyDeltaWithoutDeps

---

scopes/webpack/config-mutator/config-mutator.ts

fix addRuleToOneOf - not passing oneOf array to sub-function (addToArray)

---

src/api/consumer/lib/global-config.ts

improvements(global-config) - be more tolerant in case of trying to read a config without a name

---

scopes/dependencies/dependency-resolver/dependency-linker.ts

refactor: no need to link on link calculation phase

---

.circleci/config.yml

chore(circle-bvm) - clear bvm's index.json cache after publishing new bit version

---

scopes/scope/sign/sign.cmd.ts
scopes/scope/sign/sign.main.runtime.ts

improvement(sign) - print bit version during bit sign command

---

scopes/workspace/install/install.main.runtime.ts

fix(install) - correctly calculate the env version to install in the root, in case the env version is a snap

---

scopes/semantics/schema/schema.task.ts
scopes/typescript/ts-server/process-based-tsserver.ts
scopes/typescript/typescript/schema-extractor-context.ts
scopes/typescript/typescript/transformers/export-declaration.ts
scopes/typescript/typescript/typescript.extractor.ts

fix resolving identifiers when trying to parse the schema of a component

fix(schema): resolving identifiers

---

scopes/harmony/application/app-context.ts
scopes/harmony/application/application.main.runtime.ts
scopes/harmony/application/run.cmd.tsx
scopes/harmony/node/node.application.ts
scopes/react/react/apps/web/react.application.ts

- Add `port` option to `bit run` command
- Pass port to app context
- Use passed port in react-app 
- Use passed port in node-app

feature(apps) - passing port from bit run cmd to app context

---

pnpm-lock.yaml
scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/index.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.main.runtime.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
workspace.jsonc

feat: make some pnpm tools public in the pnpm aspect

---

src/api/consumer/lib/feature-toggle.ts
src/api/scope/lib/fetch.ts
src/constants.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/network/http/http.ts

currently enabled by a feature-flag `cloud-importer`.

support importing through bit-cloud

---

.circleci/config.yml
scripts/update-bit-gcp-index.js

- store the index.json during the publish to gcloud circle task

chore(ci) - change bvm index.json fetching url in circle ci

---

e2e/harmony/deps-in-capsules.e2e.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
scopes/dependencies/yarn/yarn.package-manager.ts

- fixes a regression introduced by #7246

fix: components in capsules should be able to require themselves

---

.bitmap
components/ui/command-bar/autocomplete-input/autocomplete-input.module.scss
components/ui/command-bar/autocomplete-input/autocomplete-input.tsx
components/ui/command-bar/autocomplete-input/index.ts
components/ui/command-bar/command-bar-item/command-bar-item.module.scss
components/ui/command-bar/command-bar-item/command-bar-item.tsx
components/ui/command-bar/command-bar-item/index.ts
components/ui/command-bar/command-bar.compositions.tsx
components/ui/command-bar/command-bar.docs.mdx
components/ui/command-bar/command-bar.spec.tsx
components/ui/command-bar/command-bar/command-bar.module.scss
components/ui/command-bar/command-bar/command-bar.tsx
components/ui/command-bar/command-bar/index.ts
components/ui/command-bar/command-bar/use-searcher.tsx
components/ui/command-bar/index.ts
components/ui/command-bar/search-result.ts
components/ui/command-bar/searcher.ts
scopes/explorer/command-bar/command-bar.ui.runtime.tsx
workspace.jsonc

update CommandBar to accept onEnter prop
update CommandBarUIRuntime to forward onEnter to CommandBar

feat(command-bar): onEnter prop

---

scopes/generator/generator/create.cmd.ts
scopes/generator/generator/generator.main.runtime.ts
scopes/generator/generator/new.cmd.ts

- add alias `--template` for `bit new/create` commands.

feat(craete/new cmds): add `--template` option alias

---

scopes/generator/generator/component-generator.ts
scopes/generator/generator/component-template.ts

feat: support async `generateFiles` method for template generators

---

scopes/component/isolator/isolator.main.runtime.ts
scopes/pipelines/builder/builder.main.runtime.ts
scopes/pipelines/builder/builder.service.tsx
scopes/workspace/workspace/capsule.cmd.ts
scopes/workspace/workspace/workspace-aspects-loader.ts
scopes/workspace/workspace/workspace.ts
src/constants.ts

feat(capsules-config) - new capsules_build_components_base_dir global config

---

scopes/typescript/typescript/schema-extractor-context.ts
scopes/typescript/typescript/transformers/index.ts
scopes/typescript/typescript/transformers/module-declaration.ts
scopes/typescript/typescript/typescript.main.runtime.ts

fix resolving file from component for fileNames with "." (dot)

fix(semantics): handle non extension dots in file name

---

src/scope/actions/export-validate.ts
src/scope/component-ops/traverse-versions.ts
src/scope/repositories/sources.ts

to debug some slowness on export.

limit merge-lane-component concurrency to 50 and add some profile around this area

---

scopes/component/status/mini-status-cmd.ts
scopes/component/status/status.main.runtime.ts
scopes/harmony/bit/load-bit.ts
scopes/workspace/workspace/workspace-component/comp-files.ts
scopes/workspace/workspace/workspace.provider.ts
scopes/workspace/workspace/workspace.ts

To make it fast, this "modified" doesn't check for config changes, only files changes.

feat(mini-status), introduce a new command mini-status for quick info about modified/new

---

scopes/harmony/application/app.cmd.ts

improvement(app cmd) - make apps an alias for app command

---

scopes/ui-foundation/ui/ui-server.ts

https://github.com/vitejs/vite/discussions/13625
- Changed the way of proxy in `bit start`

Fix bit start proxy issue

---

scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
scopes/harmony/bit/load-bit.ts
scopes/scope/scope/scope-aspects-loader.ts
scopes/workspace/install/install.cmd.tsx
scopes/workspace/workspace/workspace-aspects-loader.ts
scopes/workspace/workspace/workspace.ts
src/consumer/config/extension-data.ts

feat (workspace aspects): support file:// aspects in workspace.jsonc

---

scopes/dependencies/dependency-resolver/dependency-linker.ts

fix: always link core aspects

---

components/ui/compare/lane-compare-page/lane-compare-page.tsx

Update Lane Compare to aggregate lane components by status

feat(lane compare): aggregate by status

---

scopes/component/forking/fork.cmd.ts
scopes/component/forking/forking.main.runtime.ts
scopes/component/new-component-helper/new-component-helper.main.runtime.ts
scopes/component/tracker/tracker.main.runtime.ts
scopes/generator/generator/workspace-generator.ts
scopes/generator/generator/workspace-template.ts

- set env for fork cmd
- set env & config for starters > fork method

feat: add option to set env & config to forked components

---

scopes/react/react/component.json

chore(deps) - set esbuild to v0.14.29 for react env

---

scopes/component/remove/remove.main.runtime.ts
scopes/scope/scope/scope.main.runtime.ts
src/cli/templates/component-issues-template.ts
src/consumer/component-ops/component-status-loader.ts
src/consumer/component/components-list.ts
src/scope/component-ops/get-diverge-data.ts

Instead, show it in the `invalid components` section with a suggestion to merge from main.

fix, avoid throwing NoCommonSnap on bit-status

---

scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts

feat: pass options to pnpm rebuild function

---

scopes/component/isolator/isolator.main.runtime.ts
scopes/scope/scope/scope-aspects-loader.ts

internal(capsules) - when using dated capsules for the same scope in same process reuse the same hash

---

scopes/dependencies/pnpm/lynx.ts

feat: turn on reporting while running rebuild by pnpm

---

scopes/harmony/api-server/api-for-vscode.ts
scopes/harmony/api-server/api-server.main.runtime.ts
scopes/harmony/api-server/sse-events.route.ts
scopes/workspace/watcher/watcher.ts
scopes/workspace/workspace/index.ts
scopes/workspace/workspace/on-component-events.ts
scopes/workspace/workspace/workspace-component/comp-files.ts
scopes/workspace/workspace/workspace.main.runtime.ts
scopes/workspace/workspace/workspace.provider.ts
scopes/workspace/workspace/workspace.ts

- support Server-Sent Events to push events to vscode extensions.
- add a new event to notify about .bitmap changes.
- update workspace.bitmap instance upon consumer reloading.

improvement(vscode-api), support SSE 

---

e2e/harmony/custom-env.e2e.ts
e2e/harmony/multiple-envs.e2e.ts

To not depend on mdx-community

test, change the e2e-test of using core-env and then community-mdx to use a local one

---

scopes/lanes/lanes/lanes.main.runtime.ts

This regression caused by a PR merged yesterday #7620

fix(lane-create), respect "--scope" flag when forked

---

scopes/dependencies/pnpm/pnpm.package-manager.ts

chore(deps) - make component self ref a dev dep instead of runtime dep

---

e2e/harmony/install-missing-dependencies.e2e.ts
scopes/workspace/install/install.main.runtime.ts

fix: install --add-missing-deps should not add already linked core aspects

---

scopes/component/refactoring/refactoring.main.runtime.ts
scopes/typescript/typescript/sourceFileTransformers/expression-statement.ts
scopes/typescript/typescript/sourceFileTransformers/index.ts

- change identifier transformer to expression statement

fix(refactoring): expression statement transformer

---

scopes/mdx/mdx/mdx.main.runtime.ts

chore(mdx-deps) - update '@teambit/mdx.ui.mdx-scope-context' to '0.0.498' in mdx env

---

scopes/dependencies/pnpm/lynx.ts

fix: always should rebuild output, when rebuild is executed separately from install

---

scopes/typescript/typescript/sourceFileTransformers/empty-line-encoder.ts

fix decoding empty lines to remove the marker even if it's not the only thing on the line

fix(refactoring): empty line encoder

---

pnpm-lock.yaml

update (re-generate) lock file to point to another registry

---

scripts/docker-teambit-bit/README-zh.md

feat: 添加docker-teambit-bit中文翻译

---

components/ui/component-compare/component-compare/component-compare.tsx
components/ui/component-compare/hooks/use-component-compare/use-component-compare.ts
components/ui/component-compare/models/component-compare-change-type/component-compare-change-type.ts
components/ui/component-compare/models/component-compare-model/component-compare-model.ts
scopes/component/component-compare/component-compare.graphql.ts
scopes/component/component-compare/component-compare.main.runtime.ts
scopes/component/graph/graph.compare.section.tsx
scopes/defender/ui/test-compare-section/test.compare.section.tsx

This PR updates the `ComponentCompareMain` runtime to provide diffStatus specifically for test files. 
Shows the diff status for tests tab if the test files have changed

enhancement(compare): show diff status for test files

---

scopes/component/isolator/isolator.main.runtime.ts
src/constants.ts

improvement(isolator) - allow configure / customize the dated capsule dir via bit config

---

scopes/pipelines/builder/pipeline.ts

task to replace
- when replacing a task in the build pipeline, if the task to be replaced doesnt exist, just add the provided task
-
-

build replace - add task to pipeline if no existing

---

.circleci/config.yml

chore(circle) - change circle to use node-registry.bit.cloud instead of node-registry.v2.bit.cloud

---

scopes/component/isolator/isolator.main.runtime.ts
scopes/workspace/workspace/capsule.cmd.ts
scopes/workspace/workspace/workspace.provider.ts

improvement(isolator) - allow capsule commands to run from a bare scope

---

scopes/scope/scope/scope-aspects-loader.ts
scopes/scope/scope/scope.main.runtime.ts

API(scope) - expose new getIsolateAspectsOpts API from scope main runtime

---

scopes/harmony/application/build-application.task.ts
scopes/harmony/application/deploy.task.ts

- fix(apps) - pass deploy context correctly from build app to deploy app
- load apps during deploy task explicitly

fix(apps) - pass deploy context correctly from build app to deploy app

---

scopes/webpack/webpack/config/webpack.dev.config.ts

add(webpack): watch options polling

---

scopes/envs/envs/index.ts

types(envs) - expose more envs types

---

scopes/component/dev-files/dev-files.main.runtime.ts
scopes/compositions/compositions/compositions.main.runtime.ts
scopes/defender/tester/tester.main.runtime.ts
scopes/docs/docs/docs.main.runtime.ts
scopes/envs/envs/environments.main.runtime.ts
scopes/generator/generator/workspace-generator.ts
scopes/pkg/pkg/pkg.main.runtime.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts

fix(generator) - cleanup envs / aspect loading errors during bit new command

---

scopes/dependencies/dependency-resolver/manifest/deduping/dedupe-dependencies.ts
scopes/dependencies/dependency-resolver/manifest/deduping/hoist-dependencies.ts
scopes/dependencies/dependency-resolver/manifest/deduping/index-by-dep-id.ts
scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts

fix: peer dependencies should be deduped when root components are used

---

scripts/find-unused-packages.js
workspace.jsonc

chore(deps) - remove browserslist

---

scopes/component/isolator/isolator.main.runtime.ts

chore(isolator) - replace fs.remove with rimraf when clean capsules on process exit

---

scopes/component/isolator/isolator.main.runtime.ts

Aspect cache config

---

pnpm-lock.yaml
scopes/react/eslint-config-bit-react/bit-react-eslint.js
scopes/react/react/component.json

fix(linting) - fix linting mdx files with react components inside

---

.bitmap
scopes/react/eslint-config-bit-react/bit-react-eslint.js

chore(react-eslint) - checkout bit react eslint to v1.0.0

---

e2e/harmony/update-cmd.e2e.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts

fix: don't update components present in the workspace

---

e2e/fixtures/workspace-with-tsconfig-issue/workspace.jsonc
e2e/harmony/custom-env.e2e.ts
e2e/harmony/install-and-compile.e2e.ts

chore(e2e) - update react-env in e2e and re-enable disabled test

---

.bitmap
e2e/fixtures/workspace-with-tsconfig-issue/my-scope/envs/my-react-env/env.jsonc
e2e/fixtures/workspace-with-tsconfig-issue/workspace.jsonc
package.json
pnpm-lock.yaml
scopes/mdx/mdx/mdx.main.runtime.ts

chore(deps) - checkout latest versions (v1) of various components

---

e2e/harmony/lanes/lanes-with-issues.e2e.ts
scopes/lanes/diff/lane-diff-generator.ts
scopes/lanes/diff/lane-diff.cmd.ts

Also, fix the output of the "failure" section to show each failure in one line.

fix(lane-diff), import components needed for the diff if they are missing

---

scopes/component/isolator/isolator.main.runtime.ts

fix(capsule cache) - do not re-link core aspects if CACHE_CAPSULES is disabled

---

scopes/component/merging/merging.main.runtime.ts

In case the modification is a config change, suggest using `--ignore-config-changes`. Otherwise, keep the message suggesting to snap/tag.

improvement(lane-merge), suggest using --ignore-config-changes when applicable

---

e2e/harmony/update-cmd.e2e.ts
scopes/dependencies/dependencies/dependencies.main.runtime.ts
scopes/dependencies/dependency-resolver/apply-updates.spec.ts
scopes/dependencies/dependency-resolver/apply-updates.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.spec.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/dependency-resolver/get-all-policy-pkgs.spec.ts
scopes/dependencies/dependency-resolver/get-all-policy-pkgs.ts
scopes/dependencies/dependency-resolver/index.ts
scopes/harmony/aspect/aspect.main.runtime.ts
scopes/workspace/install/install.main.runtime.ts
scopes/workspace/install/pick-outdated-pkgs.spec.ts
scopes/workspace/install/pick-outdated-pkgs.ts
scopes/workspace/workspace/workspace.ts

fix: update dependencies in bitmap

---

scopes/component/isolator/isolator.main.runtime.ts

internal-feature(isolator) - add a slot to register a capsule transfer fn (to move from the dated capsules dir)

---

scopes/workspace/bit-roots/bit-roots.ts

fix: don't try to link root components to files in `.bit_roots`

---

scopes/component/isolator/index.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/pkg/pkg/packer.ts
scopes/pkg/pkg/write-npm-ignore.ts

fix(npm ignore) - always add internal bit files/folders to npm ignore file

---

pnpm-lock.yaml
scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
workspace.jsonc

Related PRs:
- https://github.com/pnpm/pnpm/pull/6979
- https://github.com/pnpm/pnpm/pull/6969
-
-
-

feat: add options to squeeze pnpm's installation output

---

components/ui/surfaces/menu/section/section.module.scss

Set overflow: hidden to only menuSection

styles(sidebar): fix section overflow

---

README.md
components/ui/menus/use-lanes-menu/use-lanes-menu.tsx
scopes/compositions/compositions/compositions.tsx
scopes/defender/ui/test-compare/compare-tests-page.tsx
scopes/defender/ui/test-page/tests-page.tsx
scopes/dependencies/aspect-docs/dependency-resolver/dependency-resolver.mdx
scopes/explorer/ui/component-card/component-card.composition.tsx
scopes/harmony/aspect-docs/node/node.mdx
scopes/harmony/aspect/aspect.ui.runtime.tsx
scopes/harmony/cli-reference/cli-reference.mdx
scopes/harmony/node/node.ui.runtime.tsx
scopes/html/html/templates/html-component/files/docs.ts
scopes/mdx/modules/loader/mdx-loader.docs.md
scopes/react/aspect-docs/react-native/react-native.mdx
scopes/react/aspect-docs/react/react.mdx
scopes/react/react/react.main.runtime.ts

Fix docs and cloud links across scopes.

fix links across scopes

---

scopes/component/checkout/checkout.main.runtime.ts
scopes/component/merging/merge-status-provider.ts
scopes/component/merging/merging.main.runtime.ts
scopes/component/snapping/snapping.main.runtime.ts
scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
scopes/lanes/diff/lane-diff-generator.ts
scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
scopes/scope/importer/import-components.ts
scopes/scope/importer/import.cmd.ts
scopes/scope/importer/importer.main.runtime.ts
scopes/scope/scope/scope-aspects-loader.ts
scopes/scope/scope/scope-component-loader.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/scope/sign/sign.main.runtime.ts
scopes/scope/update-dependencies/update-dependencies.main.runtime.ts
scopes/workspace/workspace/build-graph-from-fs.ts
scopes/workspace/workspace/build-graph-ids-from-fs.ts
scopes/workspace/workspace/workspace-aspects-loader.ts
scopes/workspace/workspace/workspace.ts
src/bit-id/bit-ids.ts
src/consumer/component/components-list.ts
src/consumer/consumer.ts
src/scope/actions/fetch-missing-deps.ts
src/scope/component-ops/get-flattened-dependencies.ts
src/scope/component-ops/scope-components-importer.ts
src/scope/graph/components-graph.ts
src/scope/models/model-component.ts
src/scope/objects-fetcher/objects-fetcher.ts

It's a better dx and also helps debugging import issues.

when importing from a remote, show the reason and number of comps/versions

---

scopes/component/merging/config-merger.ts

During config-merge we check whether the dependencies exist on the workspace or part of the other-lane, and then ignore it (we don't try to merge/find conflicts).
However, in case a component was deleted from the lane, and now other components on this lane are using different versions of this dependency (from main), we do want to try merging this dependency.

fix(lane-merge), do not ignore dependencies that exist on other-lane if their version is different

---

scopes/component/new-component-helper/new-component-helper.main.runtime.ts

- ignore renamin aspect's config for forked component
-
-

also ignore rename aspect in forked component config

---

src/constants.ts

fix bitmap docs references

---

.bitmap
scopes/react/eslint-config-bit-react/bit-react-eslint.js

chore - checkout latest version of bit-react-eslint

---

scopes/harmony/config/workspace-template.jsonc
src/e2e-helper/e2e-bit-jsonc-helper.ts

change(workspace.jsonc) - remove "teambit.workspace/variants" from the template of workspace.jsonc

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts

fix(node-linker) - fix calculation of node linker method for isolator in bare scope

---

scopes/generator/generator/generator.main.runtime.ts

improve error when template not found

Improve error message when a component template was not found

---

scopes/harmony/api-server/api-for-ide.ts
scopes/harmony/api-server/cli.route.ts
scopes/harmony/api-server/ide.route.ts

also, add an API for getting the current lane object.

add a new IDE-API for clearing cache, support running command with "report" method, not only json

---

scopes/react/react/react.main.runtime.ts

internal(react aspect) - validate ts and schema aspects exists before using them from react aspect

---

scopes/component/graph/ui/dependencies-compare/dependencies-compare.tsx
scopes/component/graph/ui/dependencies-graph/dependencies-graph.tsx

This PR fixes the auto sizing of the dependencies graph, by taking in consideration the number of nodes and adjusting accordingly

fix(dependencies): auto sizing deps graph 

---

scopes/component/snapping/snap-cmd.ts
scopes/defender/tester/test.cmd.tsx

- add unmodified flag for `bit test`
- also added the 'u' alias for the unmodified flag for `bit snap`
-

Unmodified for bit test

---

scopes/component/snapping/tag-cmd.ts

update tag's build flag description after making rippleCI the default

---

scopes/scope/scope/scope.main.runtime.ts
src/scope/network/http/http.ts

Also, fix the `bit list <scope-id>` to use the graphql instead of the legacy list API.

fix(list), change scope.list API to not return deleted components by default

---

scopes/component/remove/delete-cmd.ts
scopes/component/remove/remove-cmd.ts
scopes/component/remove/remove-components.ts
scopes/component/remove/remove.main.runtime.ts
scopes/component/remove/removed-local-objects.ts
scopes/harmony/api-server/api-for-ide.ts
scopes/harmony/api-server/api-server.main.runtime.ts
src/remotes/remote.ts
src/scope/network/fs/fs.ts
src/scope/network/network.ts
src/scope/network/ssh/ssh.ts
src/scope/removed-components.ts

Also, fix the `deleteMany` API to return consistent type.

api-ide, introduce a new API-IDE to remove components from the workspace

---

scopes/dependencies/dependency-resolver/dependency-linker.ts

fix: when searching for the locations of core/non-core aspects, use the latest main aspect location

---

scopes/api-reference/renderers/function/function.renderer.module.scss
scopes/api-reference/renderers/function/function.renderer.tsx
scopes/api-reference/renderers/grouped-schema-nodes-summary/grouped-schema-nodes-summary.module.scss
scopes/api-reference/renderers/grouped-schema-nodes-summary/grouped-schema-nodes-summary.tsx
scopes/api-reference/renderers/parameter/parameter.renderer.module.scss
scopes/api-reference/renderers/parameter/parameter.renderer.tsx
scopes/api-reference/renderers/schema-node-member-summary/function-node-summary.module.scss
scopes/api-reference/renderers/schema-node-member-summary/function-node-summary.tsx
scopes/api-reference/renderers/schema-node-member-summary/variable-node-summary.module.scss
scopes/api-reference/renderers/type-ref/type-ref.renderer.tsx
scopes/api-reference/utils/custom-prism-syntax-highlighter-theme/custom-theme.js
scopes/typescript/typescript/typescript.extractor.ts

This PR is part (3) of the style fixes in API Reference

fix(schema): node table style fixes

---

scopes/typescript/typescript/typescript.extractor.ts

This PR changes the log type for TransformerNotFound errors from warning to debug in logs

fix(schema): change transformer not found warning to debug in logs

---

scopes/typescript/typescript/exceptions/transformer-not-found.ts

update(transformer): log full node text on transformer not found error

---

scopes/component/component-log/component-log.main.runtime.ts
scopes/harmony/api-server/api-server.main.runtime.ts
scopes/harmony/express/express.main.runtime.ts

before sending a success message to the client.

fix(server-ide), wait for the listening event of express server 

---

pnpm-lock.yaml
workspace.jsonc

Related PR:
- https://github.com/pnpm/pnpm/pull/7149

fix: out-of-memory error during peers resolution

---

scopes/react/react/typescript/tsconfig.json

improvement(tsconfig) - add outdir to tsconfig to better handle it for ws-config write

---

scopes/scope/export/export-cmd.ts
scopes/scope/export/export.main.runtime.ts
src/cli/commands/public-cmds/login-cmd.ts
src/scope/network/http/http.ts

Also, open the browser to that link, unless `--no-browser` was used.

improvement(export), show the link to the Ripple job

---

.circleci/config.yml

fix(circle) - fix yarn 3 issues on circleci

---

scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts

- A new option added to install that allows to skip calling pnpm installation

feat: add dryRun option to package manager install function

---

CONTRIBUTING.md

- added `npm run link-bit-legacy` as its second step

Update installation guide

---

scopes/dependencies/dependency-resolver/policy/workspace-policy/workspace-policy.ts
scopes/workspace/install/install.main.runtime.ts

fix(install) - fix a case when aspect exist in both root workspace.jsonc and root policy

---

pnpm-lock.yaml
workspace.jsonc

Related PR: https://github.com/pnpm/pnpm/pull/7270

fix: update pnpm to fix regression with dependencies build

---

e2e/harmony/dependency-resolver.e2e.ts
scopes/harmony/node/node.env.ts

chroe(node-env) - update @types/node and remove @babel/runtime

---

scopes/generator/generator/component-template.ts
scopes/generator/generator/generator.main.runtime.ts
scopes/generator/generator/index.ts

feat(component-templates) - support setting component's env by env prop on the template instance

---

scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts

When merging partial lane, we check whether the dependencies exist in the current lane and if not we throw an error or add them to the lane (depend on the entered flag).
This check is done not only on the head but for all history of the components because we can't have previous versions including dependencies from other lanes. 
This PR imports the missing history in such cases.

fix(lane-merge), import missing history when merging partial lane

---

scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts

fix: never install core aspects as dependencies

---

.bitmap
pnpm-lock.yaml

chore(deps) - revert setting @babel/runtime via bitmap

---

e2e/harmony/babel.e2e.ts
e2e/harmony/new.e2e.ts
scopes/compilation/aspect-docs/babel/babel.mdx
scopes/component/component-descriptor/component-descriptor.mocks.ts
scopes/harmony/aspect/aspect.env.ts
scopes/react/react-native/react-native.env.ts
scopes/react/react/component.json
scopes/react/react/react.env.ts
src/e2e-helper/e2e-env-helper.ts

revert removing @babel/runtime and core-js from envs, update of @babel/preset-env

---

scopes/compositions/panels/composition-gallery/composition-gallery-skeleton/composition-gallery-skeleton.module.scss
scopes/compositions/panels/composition-gallery/composition-gallery-skeleton/composition-gallery-skeleton.tsx
scopes/compositions/panels/composition-gallery/composition-gallery-skeleton/index.ts
scopes/compositions/panels/composition-gallery/index.ts
scopes/docs/docs/overview/overview.tsx
scopes/docs/docs/overview/readme-skeleton.tsx

This PR adds a loading skeleton to the Component Overview Page while the iframe loads. 
https://github.com/teambit/bit/assets/8999604/b9fe45cf-67b0-449f-9734-919776f976cf

feat(Overview): Loading Skeleton

---

.circleci/config.yml

ci: update Yarn to v4

---

scopes/compilation/compiler/workspace-compiler.ts

fix(compile) - link components to node_modules and create package.json on bit compile

---

e2e/harmony/extensions-config-diff.e2e.ts
src/consumer/component-ops/components-diff.ts
src/consumer/component-ops/components-object-diff.ts
src/utils/fs/save-into-os-tmp.ts

improvement(diff), show extension diff nicely as if it was a json-file diff

---

scopes/workspace/workspace-config-files/workspace-config-files.main.runtime.ts

fix(ws-config) - show proper error if running ws-config command outside a workspace

---

scopes/workspace/install/install.main.runtime.ts

fix(install) - do not install envs configured in generator if they are in the workspace

---

src/api/scope/lib/fetch.ts

Queues are needed because some fetch-requests are very slow, for example, when includeParents is true, which loads all versions of the given components. We don't want multiple of slow requests to block other requests. 
This PR introduces 3 queues with different concurrency and different timeout.
1. depsQueue (when asking for all deps),  default to 10 concurrent tasks. timeout after 3 minutes.
2. parentsQueue (when asking to include parents), default to 10 concurrent tasks. timeout after 3 minutes.
3. fastQueue (for all other fetch), default to 10 concurrent tasks. timeout after 3 minutes.
The timeout is also new to this PR, it helps clearing tasks that got stuck for no good reason.
In case the fetch is asking for only one component, it always goes to the fastQueue. It happens for example …

introduce fetch queues to avoid slow fetch queries blocking the scope

---

scopes/workspace/modules/node-modules-linker/package-json-transformer.ts

feat(package-json) - support placeholder replaces for package.json exports field

---

pnpm-lock.yaml
scopes/react/react-elements/webpack/webpack.config.base.ts
scopes/react/react/component.json
scopes/react/react/webpack/webpack.config.base.ts
scopes/ui-foundation/ui/component.json
scopes/ui-foundation/ui/webpack/webpack.base.config.ts
scopes/ui-foundation/ui/webpack/webpack.dev.config.ts
scopes/webpack/webpack/config/webpack.dev.config.ts
workspace.jsonc

Remove `babel-preset-react-app`
- from `react-elements` webpack config
- from `react` webpack config
- from `ui-foundation` webpack config

chore: remove babel-preset-react-app

---

scopes/component/merging/merging.main.runtime.ts
scopes/lanes/merge-lanes/last-merged.ts
scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
scopes/scope/scope/staged-config.ts
src/scope/staged-snaps.ts

Also refactor merge-lanes file, extract the backup/restore of the last-merge data into a new file "last-merged".

fix(lane-merge-abort), restore staged-config and staged-snaps data

---

scopes/component/forking/forking.main.runtime.ts
scopes/component/forking/scope-fork.cmd.ts
src/constants.ts

Also, added a flag `--skip-dependency-installation` to be consistent with other commands that run installation.

feat(scope-fork), introduce a new arg "pattern" to filter the components to fork

---

scopes/envs/env/env.env.ts
scopes/envs/env/env.main.runtime.ts
scopes/harmony/aspect/aspect.env.ts
scopes/workspace/modules/node-modules-linker/node-modules-linker.ts
scopes/workspace/modules/node-modules-linker/package-json-transformer.ts

change(aspects) - add exports field to package.json of aspects

---

CHANGELOG.md

Update CHANGELOG.md skip-ci

---

scopes/component/isolator/isolator.main.runtime.ts

fix(capsules) - ignore errors when copying lock file from capsule cache to local capsule

---

src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts

overrides (`bit deps set`) takes priority over version in the .bitmap.
(as per @ranm8  request).

change deps version-resolution priority: overrides before .bitmap

---

scopes/component/checkout/checkout.main.runtime.ts

fix merge conflict advice for bit checkout

---

workspace.jsonc

templates(react) - update react templates

---

scopes/harmony/cli/cli-parser.ts
src/consumer/consumer.ts
src/logger/logger.ts

Also, include the PID to help crossing this with the debug.log file.

improve command-history to log commands that were aborted

---

src/scope/objects/object.ts
src/scope/objects/repository.ts

When running `bit cc`, the index.json is deleted, so any command afterwards needs to rebuild this file. To build it, it needs to read all local objects to check whether they're ModelComponent or Lane objects and if so, add them to the index.
For large workspaces, this takes very long because it not only reads every single file in the local scope but it also parses it. 
This PR improves it by extracting the header after reading the file and checking the type before parsing it. So then only for the given types the parsing take place.
The improvement is huge. For a scope with 168,266 files, it was 107 seconds, and with this PR it's 24 seconds.

perf, improve performance of scope.list() by parsing only the given types

---

e2e/harmony/sign.e2e.ts
scopes/pipelines/builder/artifact/artifact-extractor.ts

It's possible that locally the component wasn't built and so it has no artifacts.

fix(artifacts), re-import components in case they are build pending locally

---

scopes/component/status/status-cmd.ts

Also, avoid showing component-issues in the staged section. (they're shown in the component-issues section).

improvement(status), show the number of ids per category

---

scopes/component/isolator/isolator.main.runtime.ts

fix: only link core aspects to the root capsules directory once

---

.circleci/config.yml
src/constants.ts

internal(cloud api) - change symphony url from symphony.bit.cloud to api.v2.bit.cloud by default

---

scopes/component/checkout/checkout-cmd.ts
scopes/component/merging/merge-cmd.ts

because install already runs the compile

change the output when suggesting to run install and compile to be only install

---

scopes/harmony/node/node.templates.ts

templates(node) - set bitdev.node/node-env as the env of core node templates

---

scopes/harmony/api-server/api-for-ide.ts

It was sorted incorrectly before.

fix workspace history order

---

scopes/ui-foundation/ui/ui-server.ts

fix: type error for req.url with some node versions

---

e2e/harmony/dependencies/optional-dependencies.e2e.ts

fix: optional dependencies test

---

pnpm-lock.yaml
workspace.jsonc

update harmony templates

---

scopes/generator/generator/index.ts

improvements(generator) - expose ForkComponentInfo and ImportComponentInfo types from generator

---

scopes/generator/generator/generator.main.runtime.ts
scopes/generator/generator/new.cmd.ts
scopes/generator/generator/workspace-generator.ts

to create the new workspace in the current dir
- 
-
-

add --current-dir option to `bit new`

---

.circleci/config.yml
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts

fix(component-loading) - fix regressions from the new component loading algorithm

---

e2e/harmony/lanes/merge-lanes.e2e.ts
src/consumer/versions-ops/merge-version/three-way-merge.ts

Currently in such a case, it was marking it as "overridden" and was leaving the file in the FS as is.

fix(merge), in case a file was changed in fs and others but not exists in base, resolve as conflicted

---

workspace.jsonc

fix(bit) - re-add removed package.json props for the bit aspect (bvm/bin/engines/repo)

---

.bitmap
scopes/defender/eslint/component.json
scopes/react/react-native/component.json
scopes/ui-foundation/ui/component.json

chore(core-aspects) - update core aspect env (fix npmignore)

---

.bitmap
scopes/defender/eslint/component.json
scopes/react/react-native/component.json
scopes/ui-foundation/ui/component.json

chore(core-aspects) - update core aspect env (improve package.json exports)

---

scopes/harmony/aspect-loader/is-esm-module.ts

fix(aspects) - improve isEsmModule function (support .mjs file paths)

---

scopes/component/checkout/checkout-cmd.ts
scopes/component/checkout/checkout-version.ts
scopes/component/merging/index.ts
scopes/component/merging/merge-cmd.ts
scopes/component/merging/merging.main.runtime.ts
scopes/scope/importer/import-components.ts
src/consumer/versions-ops/merge-version/index.ts
src/consumer/versions-ops/merge-version/merge-version.ts

In case of a failure it would have thrown before reaching the output.

remove "Total Failed" in checkout/merge summary

---

scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
scopes/workspace/workspace/workspace.ts

fix(component-loading) - when running ws.list load seeders as aspects

---

src/prompts/schemas/analytics-reporting.ts

Fix broken analytics link

---

scopes/component/dev-files/dev-files.main.runtime.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts

perf(component loading) - optimization and perf for component loading

---

e2e/harmony/update-cmd.e2e.ts

test: updating auto detected dependencies in the model

---

pnpm-lock.yaml
scopes/compilation/bundler/dev-server.service.tsx
scopes/preview/preview/webpack/webpack.config.ts
workspace.jsonc

fix preview issues by temporary not run preview servers on parallel

---

.circleci/config.yml

ci: split bundling of Bit between several machines

---

.bitmap
scopes/defender/eslint/component.json
scopes/react/react-native/component.json
scopes/ui-foundation/ui/component.json

chore(core-aspects) - update version of core-aspect-env

---

e2e/harmony/deps-in-capsules.e2e.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/dependencies/dependency-resolver/dependency-resolver-workspace-config.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/dependency-resolver/index.ts

feat: an option to enable self references in capsules

---

scopes/component/checkout/checkout.main.runtime.ts
scopes/component/merging/merge-status-provider.ts
scopes/scope/export/export.main.runtime.ts
scopes/scope/importer/import-components.ts
scopes/workspace/eject/components-ejector.ts
src/consumer/component/component-loader.ts

fix(snap) - fix regression of deps calculation during bit snap

---

scopes/workspace/install/install.cmd.tsx

add alias 'a' for add-missing-deps

---

scopes/lanes/lanes/lanes.main.runtime.ts
scopes/lanes/lanes/lanes.spec.ts
scopes/scope/importer/importer.main.runtime.ts
scopes/workspace/testing/mock-workspace/mock-workspace.ts
src/api/consumer/lib/feature-toggle.ts

This feature has been implemented in this PR: https://github.com/teambit/bit/pull/8370

test, add tests for lane history feature

---

scopes/harmony/cli/bin/bit

chore(cleaning) - remove old unused bin (bit) file

---

scopes/component/status/status.main.runtime.ts

no need for this now that we deal only with ComponentID.

refactor(status), remove convertBitIdToComponentIdsAndSort

---

scopes/preview/preview/pre-bundle.ts

fix(preview): use windows-compatible paths for the prebundled preview entry file

---

scopes/component/component-compare/component-compare.main.runtime.ts
scopes/component/forking/forking.main.runtime.ts
scopes/component/isolator/isolator.main.runtime.ts
scopes/component/snapping/snapping.main.runtime.ts
scopes/dependencies/dependencies/dependencies.main.runtime.ts
scopes/dependencies/dependency-resolver/dependencies/component-dependency/component-dependency-factory.ts
scopes/dependencies/dependency-resolver/dependencies/dependency-factory.ts
scopes/dependencies/dependency-resolver/dependencies/dependency-list-factory.ts
scopes/dependencies/dependency-resolver/dependency-linker.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts
scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts
scopes/dependencies/dependency-resolver/show-fragments/dependencies.fragment.ts
scopes/dependencies/dependency-resolver/show-fragments/dev-dependencies.fragment.ts
scopes/dependencies/dependency-resolver/show-fragments/peer-dependencies.fragment.ts
scopes/pkg/pkg/package-dependency/package-dependency-factory.ts
scopes/preview/preview/strategies/component-strategy.ts
scopes/typescript/typescript/typescript.extractor.ts

It's not really an async call.

refactor, remove async from depResolver.getDependencies

---

components/modules/harmony-root-generator/harmony-root-generator.ts

improvement(harmony root) - support webpack hot reloading for generated harmony app root

---

e2e/harmony/pkg-manager-errors.e2e.ts
scopes/component/merging/merge-cmd.ts
scopes/scope/importer/import.cmd.ts

and suggest options what to do next

improvement(import), when the installation failed during import, make it clearer that the import succeeded

---

scopes/cloud/cloud/cloud.ui.runtime.tsx
scopes/docs/docs/overview/overview.tsx
scopes/workspace/workspace/ui/workspace/workspace.module.scss
scopes/workspace/workspace/ui/workspace/workspace.tsx
workspace.jsonc

- added the sidebar and top bar colors only on dark mode for now
-
-

Enable dark mode

---

scopes/component/checkout/checkout-cmd.ts

improve the description of --force-ours and --force-theirs flags

---

scopes/harmony/application/app-instance.ts

improvement(app-instance) - add stop fn to ApplicationInstance interface

---

scopes/component/forking/forking.main.runtime.ts

improvement(fork) - when forking components save the dependencies with the savePrefix in the root policy

---

scopes/cloud/cloud/cloud.ui.runtime.tsx

commented out theme toggle option

---

scopes/workspace/config-merger/esm.mjs

internal(config-merger-aspect) - add config merger esm.mjs file

---

scopes/compilation/compiler/esm.mjs
scopes/component/merging/esm.mjs
scopes/harmony/bit/esm.mjs
scopes/harmony/cli/esm.mjs
scopes/harmony/config/esm.mjs
scopes/typescript/typescript/esm.mjs
scopes/workspace/workspace/esm.mjs

refactor(core-aspects) - add missing exports in esm.mjs files

---

scopes/workspace/workspace/envs-subcommands/envs-replace.cmd.ts
scopes/workspace/workspace/envs-subcommands/envs-set.cmd.ts

fix - recommend running install after bit env set, replace and updated

---

.bitmap
.circleci/config.yml
scopes/defender/eslint/component.json
scopes/react/react-native/component.json
scopes/ui-foundation/ui/component.json

chore(core-aspects) - update core aspect env to update @types/react version

---

.bitmap
.circleci/config.yml
scopes/defender/eslint/component.json
scopes/react/react-native/component.json
scopes/ui-foundation/ui/component.json

chore(core-aspects) - update core aspect env - added new tsconfig options

---

.circleci/config.yml

circle ci - refresh core aspects env cache

---

scopes/component/forking/forking.main.runtime.ts

- As part of #8430 we added a version prefix (like `^`) when forking components. this causes issues in 2 cases:
- when the version is hash we got `^hash` which is invalid
- when the version already had a prefix we added another like `^^1.0.0` which is invalid
- This PR fixes both issues

improve(forking) - improve version prefix calculation when forking components

---

.circleci/config.yml

ci: don't build cpu-features and ssh2 for Windows

---

src/remotes/remote-resolver/remote-resolver.ts

add 3 retries to avoid dns issue when feach scope

add retry to avoid client dns issue

---

pnpm-lock.yaml
scopes/compositions/compositions/compositions.preview.runtime.ts
scopes/docs/docs/docs.preview.runtime.tsx
scopes/preview/preview/pre-bundle.ts
scopes/preview/preview/preview.preview.runtime.tsx
scopes/preview/preview/webpack/webpack.config.ts
workspace.jsonc

fix(preview) - fix preview when there is a package.json with type:module in the workspace root

---

workspace.jsonc

chore: mute warnings about some peer dependencies

---

e2e/harmony/import-harmony.e2e.ts
scopes/component/graph/component-id-graph.ts
scopes/scope/importer/import-components.ts
scopes/scope/importer/import.cmd.ts
src/e2e-helper/e2e-general-helper.ts

to traverse the dependents through the given ids.

feat(import-dependents-through), introduce a new flag --dependents-through

---

e2e/harmony/lanes/lanes.e2e.ts
scopes/lanes/merge-lanes/merge-lane-from-scope.cmd.ts
scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
scopes/scope/importer/importer.main.runtime.ts
src/consumer/component/sources/artifact-files.ts
src/scope/exceptions/missing-objects.ts

Also, change the algorithm of importing artifacts locally to search first in the lane scope and if not found, search in the original scopes.

improvement(merge-from-scope), introduce a new flag --re-merge

---

scopes/workspace/workspace/workspace.ts

`bit test` searches for all dependents and include them in the list ids to test. This PR limit this list to only the dependents that exist in the workspace to avoid ComponentNotFound errors.

fix(test), avoid running tests on non-workspace components

---

.bitmap
scopes/defender/eslint/component.json
scopes/react/react-native/component.json
scopes/ui-foundation/ui/component.json

chore(core-aspects) - update core-aspect-env to support schema extraction

---

package.json
pnpm-lock.yaml
workspace.jsonc

fix: update teambit.bvm/list

---

.circleci/config.yml

Revert "change circle to 2xlarge"

---

src/consumer/component/sources/artifact-files.ts

fix, fix the message when importing artifacts from a lane

---

scopes/component/merging/esm.mjs

fix(core-aspects) - add missing export in merging esm.mjs

---

scopes/harmony/config/workspace-config.ts

internal(workspace-config) - fixes for workspace config proto when casting/parsing

---

components/entities/semantic-schema/api-schema.ts

This PR fixes duplicated tagged exports being extracted from an API schema

fix(Schema): tagged exports - fix duplicates

---

scopes/generator/generator/templates/basic/template/files/workspace-config.ts

fix(basic-starter) - remove eslint plugins from basic starter workspace policy

---

pnpm-lock.yaml
scopes/harmony/aspect/aspect.templates.ts
workspace.jsonc

change(templates) - replace harmony templates with symphony templates

---

components/ui/code-view/code-view.tsx

This PR fixes the issue with Code Review throwing an error when the core aspects data requested from the API is unavailable

fix(Code): handle missing core aspects data

---

.circleci/config.yml

internal(circle ci) - remove old unused jobs 

---

src/consumer/component-ops/components-object-diff.ts

fix: show peer diffs

---

components/ui/code-tab-page/code-tab-page.tsx

This PR updates the rendering order of the component dependencies in the Code page alphabetically based on their package name

feat(Code): sort deps in code drawer

---

e2e/harmony/imported-component-deps.e2e.ts

test: make import component test stable

---

e2e/harmony/build-cmd.e2e.ts
scopes/pipelines/builder/build-pipe.ts

Show them with `[dependency]` prefix and dimmed.

indicate when a build-task is running on non-seeders

---

scopes/component/component/component-factory.ts
scopes/component/forking/forking.main.runtime.ts
scopes/component/merging/merge-status-provider.ts
scopes/component/remove/remove.main.runtime.ts
scopes/component/renaming/renaming.main.runtime.ts
scopes/component/stash/stash.main.runtime.ts
scopes/component/status/status.main.runtime.ts
scopes/harmony/api-server/api-for-ide.ts
scopes/harmony/aspect/aspect.main.runtime.ts
scopes/lanes/merge-lanes/merge-lanes.main.runtime.ts
scopes/scope/export/export.main.runtime.ts
scopes/scope/importer/dependents-getter.ts
scopes/workspace/install/install.main.runtime.ts
scopes/workspace/watcher/watcher.ts
scopes/workspace/workspace/aspects-merger.ts
scopes/workspace/workspace/build-graph-from-fs.ts
scopes/workspace/workspace/build-graph-ids-from-fs.ts
scopes/workspace/workspace/workspace-component/workspace-component-loader.ts
scopes/workspace/workspace/workspace.ts

It's not really a promise. Fix it to remove the Promise from the return type.

refactor, change workspace.listIds() to not be a promise

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts

refactor(deps-resolve) - make getDependenciesFromSerializedDependencies public method

---

scopes/workspace/workspace-config-files/config-writer-entry.ts
scopes/workspace/workspace-config-files/workspace-config-files.main.runtime.ts
scopes/workspace/workspace-config-files/writers/real-config-files.ts

improvement(ws-config) - pass workspace dir path to calcConfigFiles function of config writers

---

pnpm-lock.yaml
workspace.jsonc

improvements(ts-config-writer) - bump ts compiler version to add root dir to generated tsconfig files

---

scopes/dependencies/pnpm/lynx.ts

fix: auto install peers

---

package.json
pnpm-lock.yaml

deps(@types/prettier) - update prettier types package

---

workspace.jsonc

deps(eslint-linter) - bump @teambit/defender.eslint-linter version

---

.bitmap
.circleci/config.yml
scopes/defender/eslint/component.json
scopes/react/react-native/component.json
scopes/ui-foundation/ui/component.json

chore(core-aspects) - bump core aspects envs

---

pnpm-lock.yaml
workspace.jsonc

This PR fixes the tooltip width on the component sizer widget.

fix(Component Sizer): tooltip width

---

workspace.jsonc

deps(react-webpack) - bump react-webpack + css-minimizer-webpack-plugin + add optional peers of css-minimizer

---

scopes/scope/sign/sign.main.runtime.ts

fix(sign) - make sure to run env template tasks when signing envs on bare scope

---

scopes/component/component/component.ts

It was requested a while ago by Ran/Guy.

introduce a new API "getCurrentSnap()" for the Component object

---

e2e/harmony/checkout-harmony.e2e.ts
e2e/harmony/import-harmony.e2e.ts
scopes/component/checkout/checkout-cmd.ts
scopes/component/checkout/checkout.main.runtime.ts
scopes/scope/importer/import-components.ts
scopes/scope/importer/import.cmd.ts
src/api/consumer/lib/feature-toggle.ts

currently,  this is enabled only by a feature-flag. 
For more info about this feature, see this PR https://github.com/teambit/bit/pull/8405

make the update-deps-on-import the default

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts

fix(dependencies) - fix a case where a component was set as optional peer

---

scopes/dependencies/pnpm/pnpm.package-manager.ts

change(deps) - change the auto install peers to be false by default

---

scopes/defender/eslint/eslint.linter.ts
scopes/defender/linter/lint.task.ts

improvement(lint) - only run eslint on original seeders during build

---

workspace.jsonc

chore(deps) - bump @teambit/compilation.babel-compiler component version

---

scopes/compilation/compiler/workspace-compiler.ts

The performance of `bit compile` is improved dramatically with this change. The "transpile" part for 285 components is down from 29 seconds to 11 seconds.

perf, improve bit-compile performance by calculating distDirs only once per component

---

pnpm-lock.yaml
workspace.jsonc

chore(deps) - bump babel compiler component version

---

scopes/dependencies/pnpm/pnpm.package-manager.ts

perf: cache modules manifest

---

e2e/harmony/dependency-resolver.e2e.ts
scopes/dependencies/dependency-resolver/dependency-resolver-workspace-config.ts
scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
scopes/workspace/install/install.main.runtime.ts
workspace.jsonc

fix: don't hoist packages that are in the workspace

---

e2e/harmony/deduplication.e2e.ts
e2e/harmony/import-harmony.e2e.ts
e2e/harmony/install.e2e.ts
e2e/harmony/merge-config.e2e.ts
scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts

fix: install the exact version of a dependency

---

scopes/dependencies/pnpm/lynx.ts

fix: it should be possible to turn hoisting off

---

scopes/workspace/workspace/workspace.main.runtime.ts

Otherwise, when the aspect missing it can't import them until the user is logged in.

fix(login), avoid loading workspace aspects

---

scopes/scope/importer/import.cmd.ts

improvement(import), show the number of new versions instead of specifying them if > 5

---

src/consumer/bit-map/component-map.ts
src/consumer/component/component-fs-cache.ts
src/consumer/component/consumer-component.ts

It has a modest performance gain of 322ms for 285 components.

perf, remove the unused lastTrack check

---

scopes/harmony/aspect/typescript/tsconfig.json
scopes/react/react/typescript/tsconfig.build.json
scopes/react/react/typescript/tsconfig.cjs.json
scopes/react/react/typescript/tsconfig.json

fix(typescript) - exclude cjs files, node_modules, package.json from ts compile of core envs

---

scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.main.runtime.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
src/scope/network/http/http.ts

feat: add user's name to user agent sent to the registry

---

scopes/workspace/config-merger/config-merger.main.runtime.ts

This is related to the feature implemented in this PR: https://github.com/teambit/bit/pull/8405
It was working for packages only, this PR supports also components.

support updating components in workspace.jsonc during import along with packages

---

scopes/dependencies/dependency-resolver/manifest/workspace-manifest-factory.ts

fix: getting package name for component dependencies in manifests factory

---

.bitmap
.circleci/config.yml
scopes/defender/eslint/component.json
scopes/react/react-native/component.json
scopes/ui-foundation/ui/component.json

chore(core-aspects) - bump env of the core aspects

---

scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts

fix: pass network settings to pnpm

---

scopes/preview/preview/preview.main.runtime.ts
scopes/preview/preview/strategies/component-strategy.ts

fix(preview) - improve collecting webpack assets metadata

---

scopes/generator/generator/component-generator.ts

fix(templates) - resolve env id set by template to add env version to generated component

---

scopes/pipelines/builder/build.cmd.ts

It helps in cases we want to quickly debug without recreating the capsules but still copy the component files from the workspace.

improvement(build), introduce --rewrite and --reinstall to use in conjunction with --reuse-capsules

---

scopes/cloud/cloud/cloud.main.runtime.ts
scopes/workspace/workspace/workspace.ts
src/scope/network/http/http.ts
src/utils/bit/get-cloud-user.ts

fix: fetch with agent settings

---

scopes/component/component-compare/component-compare.main.runtime.ts

(currently, it shows them all as new).

fix(diff), show component files as deleted when a component was deleted

---

scopes/preview/preview/preview.start-plugin.tsx

fix(start) - fix a case when spinner with same name already exists

---

scopes/scope/sign/sign.cmd.ts
scopes/scope/sign/sign.main.runtime.ts

With this flag, no need to push to the remote in order to investigate the `Version` object changes.

improvement(sign), introduce a new flag --save-locally to make debugging easier

---

src/scope/exceptions/merge-conflict-on-remote.ts

improve merge-error message

---

scopes/component/status/status-cmd.ts
src/cli/chalk-box.ts

Also, when a component has issues, replace the " ... ok" with "... issues found".

improvement(status), show all soft-tagged in a dedicated category

---

e2e/functionalities/peer-dependencies.e2e.3.ts

test: skip tests at tagging in the peer dependencies e2e test

---

.circleci/config.yml

chore(circle) - temporary lock version of bit used to bit install

---

scopes/component/component-writer/esm.mjs
scopes/harmony/bit/esm.mjs
scopes/scope/importer/esm.mjs

internal(esm) - add missing exports from esm.mjs of core aspects

---

.circleci/config.yml

circle ci - rollback bit install to use latest nightly

---

scopes/component/status/status-cmd.ts

Also, show the `warnings found` in yellow, not red.

improvement(status), hide full warnings by default, show them with --warnings flag

---

.circleci/config.yml
scopes/dependencies/pnpm/lynx.ts

fix: remove store controller from cache to allow more effective garbage collecting

---

.circleci/config.yml

chore: update lockfile to v9

---

workspace.jsonc

chore: auto install peers in the Bit CLI repo itself

---

scopes/component/component/component-factory.ts
scopes/component/component/component.main.runtime.ts
scopes/component/component/component.ts
scopes/component/component/show/show.cmd.ts

feature(show) - add --browser to bit show to open component page on the browser

---

scopes/preview/preview/generate-link.ts
scopes/preview/preview/mk-temp-dir.ts

- fix the preview paths for Windows after @Jinjiang changes

fix(preview): make paths compatible with windows

---

scopes/dependencies/dependency-resolver/package-manager.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts

feat: pass enableModulesDir to pnpm

---

package.json

See the actual changes of the ClearGraph component here: https://bit.cloud/teambit/graph/~change-requests/edges-set/~changes
In some cases, the performance improvement is dramatic, from 288 seconds to 7 seconds. (building subgraphs during "bit tag" on 639 components).

perf, improve graph performance by eliminating duplicated edges

---

pnpm-lock.yaml
workspace.jsonc

- https://github.com/pnpm/pnpm/pull/8144

perf: fix installation performance with auto install peers on

---

scopes/workspace/install/install.main.runtime.ts

- This fix was done as part of #8562, but accidentally pushed as commented out. This PR uncomment it.

fix(bit create) - fix tsconfig not found on bit create

---

scopes/dependencies/pnpm/get-virtual-store-dir-max-length.ts
scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm-prune-modules.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
workspace.jsonc

refactor: use @teambit/dependencies.pnpm.dep-path

---

scopes/workspace/watcher/watch.cmd.ts

This flag was used for a while now and it works fine, it's time to make it the default.

improvement(watch), make "--import" flag the default

---

scopes/dependencies/pnpm/get-registries.ts
scopes/dependencies/pnpm/lynx.ts

fix: passing username/password auth settings to pnpm

---

workspace.jsonc

deps(ts-compiler) - update ts compiler to get new performance fixes

---

src/consumer/config/component-config.ts

internal(logs) - fix typo in debug logs

---

scopes/harmony/bit/load-bit.ts

improvements(outputs) - improve message for non satisfies bit version

---

scopes/dependencies/pnpm/pnpm.package-manager.ts

feat: enable auto install peers by default

---

scopes/compilation/compiler/compiler.main.runtime.ts
scopes/compilation/compiler/workspace-compiler.ts
scopes/workspace/install/install.main.runtime.ts
scopes/workspace/workspace/index.ts
scopes/workspace/workspace/workspace-component/index.ts

internal(compile API) - receive component load options for compile components API

---

scopes/api-reference/renderers/grouped-schema-nodes-summary/grouped-schema-nodes-summary.tsx

This PR fixes the rendering of method schema that return a JSX element.

fix(api-ref): handle rendering method schema for functions that return jsx

---

scopes/generator/generator/generator.main.runtime.ts
scopes/generator/generator/workspace-generator.ts

- fix creating components from custom envs defined by the workspace starters
- during bit new - fork components before creating components

fix(bit new) - fix creating components from custom envs defined by the workspace starters

---

scopes/scope/scope/scope-aspects-loader.ts
scopes/scope/scope/scope.main.runtime.ts
scopes/scope/sign/sign.main.runtime.ts

fix(sign) - fix signing components (aspects) with custom envs

---

scopes/generator/generator/component-generator.ts

This is not needed anymore due to a previous PR https://github.com/teambit/bit/pull/8965.

avoid adding apps into workspace.jsonc during bit-create

---

scopes/envs/envs/env.plugin.ts

feature(envs) - support define the env type by a type member (instead of name)

---

scopes/envs/envs/environments.main.runtime.ts
scopes/generator/generator/component-template.ts
scopes/generator/generator/generator.service.tsx
scopes/generator/generator/workspace-template.ts

feature(generator) - store generator service data for envs in their model

---

workspace.jsonc

(this is a preparation to get the pnpm output to another process).

chore, upgrade @pnpm/default-reporter to the latest

---

scopes/react/react/jest/jest.config.js

fix(jest) - restore deleted jest.config file for backward compatibility

---

scopes/react/eslint-config-bit-react/bit-react-eslint.js

- This is to prevent eslint errors as described in https://github.com/orgs/mdx-js/discussions/2454

fix(lint) - change mdx/code-blocks to false by default

---

.bitmap
.circleci/config.yml
scopes/defender/eslint/component.json
scopes/react/react-native/component.json
scopes/ui-foundation/ui/component.json

chore(core-aspects) - update core aspects envs

---

scopes/harmony/aspect-loader/aspect-loader.main.runtime.ts
scopes/workspace/install/install.main.runtime.ts

fix(install) - reload non loaded envs during install before compile

---

workspace.jsonc

fix(jest) - update jest tester to fix babel issue

---

scopes/defender/eslint/eslint.main.runtime.ts
scopes/defender/linter/linter-context.ts
scopes/react/react/react.env.ts

improvement(linter) - improve linter's context fix type type

---

scopes/workspace/workspace/workspace-component/workspace-component-loader.ts

fix(getMany) - return uniq items from workspace list / get many

---

scopes/cloud/cloud/cloud.main.runtime.ts
scopes/cloud/cloud/login.cmd.ts
src/constants.ts

feature(bit-login) - auto set cloud domain config when bit login to a custom domain

---

.circleci/config.yml

circle ci - install latest version of bit

---

workspace.jsonc

fix(jest) - update react-jest to fix issue with babel version

---

scopes/webpack/config-mutator/config-mutator.ts

fix(webpack config mutator) - fix addElementToHtmlTemplate

---

components/modules/harmony-root-generator/harmony-root-generator.ts

improvement(harmony-root) - add option to disable webpack hot when creating harmony root

---

.circleci/config.yml

This reverts commit f8c130370c16d9d5d4cf2e0224b6111a062b4d0f.
-
-
-

Revert "circle ci - temporary install specific bit version to make ci work"

---

scopes/defender/tester/test.cmd.ts

or any reason other than tests-failure.

improvement(test), exit with non-zero code when tester fails due to coverage

---

scopes/dependencies/dependency-resolver/dependency-installer.ts

fix: don't crash if node_modules cannot be removed

---

scopes/dependencies/dependencies/dependencies-loader/apply-overrides.ts

fix(deps) - remove component deps from package deps to prevent duplications

---

workspace.jsonc

- @teambit/component.ui.component-meta: update to v0.0.359
see:
- https://bit.cloud/teambit/vue/~change-requests/sass-deprecation-warning-20241010
- https://bit.cloud/teambit/vue/~change-requests/sass-deprecation-warning-deps-chain-20241011

Bump @teambit/component.ui.component-meta for teambit.docs/docs

---

workspace.jsonc

bump version of compare aspects

---

scopes/component/snapping/snapping.main.runtime.ts

Otherwise, the installation install incorrect deps.

fix(_snap), clear cache before starting installation

---

scopes/compilation/bundler/bundler-context.ts
scopes/compilation/bundler/dev-server.service.ts
scopes/preview/preview/strategies/component-strategy.ts
scopes/preview/preview/strategies/env-strategy.ts

improvement(bundler context) - add new componentDirectoryMap for targets on bundler context

---

scopes/pipelines/builder/builder.service.ts

By colorizing it using `chalk.cyan`.

improvement(build), make the env-id more prominent

---

scopes/lanes/diff/index.ts
scopes/lanes/diff/lane-diff-generator.ts
scopes/lanes/diff/lane-diff.cmd.ts
scopes/lanes/diff/lane-history-diff.cmd.ts
scopes/lanes/lanes/lanes.main.runtime.ts

To show diff between two history-ids.

feat(lane-history-diff), introduce a new command "bit lane history-diff"

---

scopes/preview/preview/preview.start-plugin.tsx

fix(bit-start) - fix an issue with spinners errors on bit start

---

components/ui/component-filters/env-filter/envs-filter.tsx

This PR fixes the issue with the envs filter where it would incorrectly filter out results when other filter (like deprecation filter) state changes. 
Previously, the envs filter would get populated initially with all non deprecated components, which results in it missing the env of the deprecated component, if no other non deprecated component has the same env. 
Since the deprecation filter runs first (order in which the filter gets registered to the slot) - it only shows what already has been filtered out by the envs filter in this case it is the deprecated component since its env wasnt populated yet.
There are two fixes to address this issue,
1. Now in the env's filter match function if all the envs are set to be true (checked) we dont run the filter and instead match everything. This …

fix(component drawer/filters): correctly derive env filter state when other filter state changes

---

src/constants.ts

Also, remove some old records from this list that are not relevant anymore. (.bit.map.json, bit.json and bitBindings.js)

add .DS_Store to the global ignore list

---

scopes/compilation/compiler/compiler.cmd.ts
scopes/compilation/compiler/workspace-compiler.ts
scopes/workspace/watcher/watch.cmd.ts
scopes/workspace/watcher/watcher.ts

The heavy lifting was done in #9308 . This PR is about adding the same functionality for `bit watch`.

add --generate-types to the watch command

---

components/legacy/loader/loader.ts
package.json

- **fix loader spinner type**
- **add @types/pretty-time to fix ts issues**

fix(types) - fix ts errors for legacy loader

---

.bitmap
.circleci/config.yml

chore(core-aspects) - bump core aspects env version

---

.bitmap
.circleci/config.yml
package.json
workspace.jsonc

internal(types) - update @types/node to v22.10.1

---

.circleci/config.yml
scopes/dependencies/pnpm/pnpm-prune-modules.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts
workspace.jsonc

fix: remove lockfile-file from dependencies and use lockfile.fs instead

---

components/legacy/analytics/analytics.ts
scopes/harmony/cli/command-runner.ts
scopes/scope/network/http/http.ts

- do not fail command if analytics init fails
- do not fail HTTP request if can't get bit version
- do not initialize analytics if it's disabled by the user

fix(analytics) - do not fail command if analytics init fails

---

components/legacy/analytics/analytics.ts
components/legacy/scope/scope.ts
scopes/scope/network/http/http.ts

internal(scope) - ignore bit version not found when creating new scope

---

.bitmap

internal(core-aspects) - change env for core aspects (doctor, host-initializer) to the correct env

---

scopes/component/lister/esm.mjs
scopes/component/merging/esm.mjs
scopes/component/remove/esm.mjs
scopes/component/snapping/esm.mjs
scopes/dependencies/dependencies/esm.mjs
scopes/harmony/cli/esm.mjs
scopes/harmony/config/esm.mjs
scopes/harmony/host-initializer/esm.mjs
scopes/scope/export/esm.mjs

internal(cli) - add missing exports to cli esm.mjs

---

scopes/dependencies/pnpm/pnpm.package-manager.ts

feat: log a debug message when a lockfile is created from dependencies graph

---

scopes/docs/docs/overview/overview.tsx

https://github.com/user-attachments/assets/02bd17e7-dce0-423f-b0fb-c1add9abef73

feat(minimal mode/overview): show preview first in minimal mode

---

.bitmap

internal(envs) - update teambit.node/envs/node-babel-mocha version

---

scopes/scope/objects/objects/repository.ts

fix(scope) - reload scope index in memory when index is corrupted

---

scopes/workspace/workspace/workspace.ts

internal(comps loading) - fix loading components <> envs by user input

---

components/legacy/consumer-config/component-overrides.ts
components/scope/remotes/remote.ts
scopes/harmony/testing/load-aspect/load-aspect.ts
scopes/workspace/modules/fs-cache/fs-cache.ts

Also, change some vars from `private` to `protected` to fix some TS errors outside bit-repo.

fix(testing-load-aspect), add the main-runtime when missing, on a best-effort basis

---

scopes/preview/preview/preview.main.runtime.ts

fix(serve preview) - better handle different files for serve preview

---

scopes/dependencies/pnpm/lockfile-deps-graph-converter.spec.ts
scopes/dependencies/pnpm/lockfile-deps-graph-converter.ts

fix: generating lockfile from dependencies graph

---

.circleci/config.yml

ci: upload @teambit/bit lockfile to bvm during release

---

.circleci/config.yml

ci: use pnpm v10 to install @teambit/bit

---

workspace.jsonc

deps(eslint-linter) - upgarde eslint linter to v1.0.47

---

package.json

deps(oxlint) - upgarde oxlint to v0.15.5

---

workspace.jsonc

deps(code-snippet) - upgrade @teambit/documenter.ui.code-snippet

---

scopes/harmony/config/workspace-template.jsonc

improvement(workspace template) - add commented bitdev.symphony/envs/symphony-env to workspace.jsonc generator envs

---

.circleci/config.yml

circleci - use latest bit version again

---

workspace.jsonc

bump @teambit/mdx.modules.mdx-loader

---

workspace.jsonc

bump @teambit/component.ui.component-compare.compare-aspects.compare-aspects version

---

workspace.jsonc

bump  "@teambit/scope.ui.hooks.use-scope"

---

workspace.jsonc

bump @teambit/react.webpack.react-webpack

---

workspace.jsonc

bump @teambit/code.ui.code-tab-tree

---

scopes/harmony/ipc-events/ipc-events.main.runtime.ts
scopes/workspace/watcher/watcher.ts

This is helpful when all we want is to notify the watchers that a new event has been written to the filesystem. 
It doesn't require the watchers to register to GotEventSlot. The watchers always listen to this onNotifySSE event, and once they get it, they simply send a server-send-event to the clients.

improvement(ipc-events), support publishing events directly for SSE

---

scopes/component/snapping/tag-model-component.ts

In some cases, when tagging or snapping with `--build` flag, the buildStatus remain `pending`, instead of `succeed`.
This is a regression caused by https://github.com/teambit/bit/pull/9437. It happens for example when tagging/snapping aspects. 
It's happening because the `ConsumerComponent instance inside the harmony component is different than the one originally created. Although the harmony component is created by the legacy, but in case the `Workspace` aspect already had this component in the cache, it won't use the provided legacy, but create a new one.
As a result, the buildStatus was set to one instance of ConsumerComponent and another instance was saved into the filesystem.
This PR fixes it by making sure it's using the same instance of `ConsumerComponent`.

fix(tag), fix buildStatus when tagging with --build aspects

---

.bitmap
scopes/react/bit-react-transformer/helpers.ts

internal(bit-react-transformer) - move @babel/core and @babel/types to be dev dependencies

---

workspace-jsonc-schema.json
workspace.jsonc

- **internal(workspace schema) - add workspace jsonc schema json**
- **update workspace aspect schema, add yarn example, remove packageManager from required, remove react aspect**
- **dep resolver schema updates**
- **add preview aspect**
- **add generator aspect**
- **add teambit.component/issues**
- **add more fields to deps resolver shcema**
- **add more missing props**
- **point workspace config to local schema**
-
-
-

workspace json schema

---

components/ui/code-view/code-view.tsx

fix(code viewer) - cjs/mjs code highlighting

---

scopes/dependencies/pnpm/pnpm.package-manager.ts

fix(isolation) - support deps graph to lock in capsules

---

package.json

chore(deps) - upgrade oxlint to v0.15.8

---

scopes/workspace/modules/fs-cache/fs-cache.ts

by re-trying deleting the deps cache in the filesystem after a second.

fix, fix ENOTEMPTY error when multiple processes writing and loading components at the same time

---

components/legacy/e2e-helper/e2e-command-helper.ts
e2e/harmony/custom-env.e2e.ts
scopes/compilation/compiler/compiler.main.runtime.ts
scopes/compilation/compiler/compiler.service.ts
scopes/defender/formatter/format.task.ts
scopes/defender/formatter/formatter.main.runtime.ts
scopes/defender/formatter/formatter.service.ts
scopes/defender/linter/lint.task.ts
scopes/defender/linter/linter.main.runtime.ts
scopes/defender/linter/linter.service.ts
scopes/defender/linter/linter.ts
scopes/defender/tester/tester.service.ts
scopes/defender/tester/tester.task.ts
scopes/docs/docs/docs.service.ts
scopes/envs/envs/env.plugin.ts
scopes/preview/preview/preview.service.tsx
scopes/preview/preview/preview.task.ts
scopes/preview/preview/strategies/component-strategy.ts
scopes/preview/preview/strategies/env-strategy.ts

It doesn't have any service, not a tester, not a compiler, absolutely nothing.

feat, support an empty env which does not implement anything

---

scopes/dependencies/pnpm/lockfile-deps-graph-converter.spec.ts
scopes/dependencies/pnpm/lockfile-deps-graph-converter.ts

fix: ignore peer dependencies when matching direct dependencies from the dependency graph

---

.circleci/config.yml
workspace.jsonc

fix: update cross-spawn to fix a vulnerability

---

package.json

deps(oxlint) - bump version of oxlint

---

scopes/webpack/webpack/transformers/resolve-peer.ts

Revert "fix: webpack peer resolver"

---

scopes/dependencies/pnpm/pnpm.package-manager.ts

fix: install should ignore directories that are not components

---

scopes/workspace/install/install.main.runtime.ts

fix(install) - do not fail install if prune node_modules failed

---

scopes/compilation/compiler/workspace-compiler.ts
scopes/typescript/typescript/schema-transformer.plugin.ts
scopes/typescript/typescript/typescript.extractor.ts
scopes/typescript/typescript/typescript.main.runtime.ts

This change reduces the number of files loaded during bootstrap by 44.

perf, lazy-load typescript-transformers

---

package.json

deps(oxlint) - upgrade oxlint version

---

components/entities/semantic-schema/schema-registry.ts
scopes/api-reference/api-reference/api-reference.ui.runtime.tsx
scopes/react/react/react.main.runtime.ts
scopes/react/react/react.ui.runtime.tsx
scopes/semantics/schema/schema.main.runtime.ts

It helps reduce the number of files loaded during each bit command by 53.

perf, lazy load schemas

---

scopes/scope/objects/models/version.ts

You can find all the details in this PR: [#8690](https://github.com/teambit/bit/pull/8690), which set up all the necessary preparations to support this string array syntax. This PR simply finalizes the process and makes it happen.

compact the flattened-edges data in the objects

---

e2e/functionalities/workspace-config.e2e.3.ts
e2e/harmony/deps-graph.e2e.ts
e2e/harmony/root-components.e2e.ts
scopes/harmony/node/node.env.ts

fix(node-env) - make react and react-dom peer deps if used by component that uses the core node env

---

scopes/preview/preview/strategies/component-strategy.ts

fix(preview) - fix conflicting preview chunk names

---

scopes/workspace/workspace/workspace-component/workspace-component-loader.ts

fix(env loading) - fixes for envs loading in bit repo itself

---

scopes/harmony/node/node.env.ts

change(node-env) - make node env setting react 17 instead of 18 to be aligned with other core envs

---

scopes/dependencies/pnpm/lynx.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts

refactor: change the options of dependenciesGraphToLockfile

---

scopes/dependencies/pnpm/pnpm.package-manager.ts

- Make proxyConfig, networkConfig, and registries optional in dependenciesGraphToLockfile

refactor: dependenciesGraphToLockfile

---

package.json

chore(oxlint) - update oxlint to v0.16.0

---

e2e/performance/filesystem-read.e2e.ts

Also, print the number of files read during the tests. (it's helpful to go back in time and see when it was increased).

test, improve filesystem-read e2e-test to print the diff files in case they reach the max-limit

---

scopes/preview/preview/strategies/component-strategy.ts

- This bug is a regression caused by #9622 
-
-

fix(preview) - fix a bug that prevent component size calculation

---

components/entities/semantic-schema/schemas/parameter.ts
package.json

chore(deps) - upgrade oxlint version

---

e2e/harmony/install-missing-dependencies.e2e.ts
scopes/workspace/install/install.cmd.tsx
scopes/workspace/install/install.main.runtime.ts

feat: skip unavailable packages when installing missing dependencies

---

scopes/preview/preview/preview.preview.runtime.tsx

This PR fixes the reportSize function in Preview to correctly calculate the rendered content height.

fix(preview): correctly calculate preview content height

---

scopes/workspace/watcher/watcher.ts

The previous suggestion was placed incorrectly. It’s now working and also recommends closing other watchers.

improvement(watcher), add suggestions when "Error starting FSEvents stream" is thrown

---

scopes/defender/linter/linter.ts

types(linter) - add some optional props to the linter interface

---

scopes/dependencies/pnpm/lockfile-deps-graph-converter.ts
scopes/dependencies/pnpm/pnpm.package-manager.ts

fix: lockfile generation when component from the workspace is in the dependency graph as a dependency

---

scopes/compilation/bundler/dedup-envs.ts

fix(start) - fix bit start when some envs not implementing preview API

---

scopes/toolbox/fs/link-or-symlink/create-link-or-symlink.ts

fix: use symlink-dir for creating symlinks to avoid any race conditions

---

scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts
scopes/scope/network/http/http.ts

This PR adds a remote-search tool to the MCP server, enabling remote component search functionality via the MCP protocol.

feat(mcp): add remote-search tool to MCP server

---

scopes/generator/generator/generator.main.runtime.ts

The Generator aspect's configuration wasn't automatically updating when `workspace.jsonc` changed, causing `getConfiguredEnvs()` to return stale `this.config.envs` values in long-running processes like "bit server". 
This PR fixes it by reloading the generator config upon workspace.jsonc changes.

feat: add config reload mechanism to Generator aspect for workspace config changes

---

scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts

This PR improves the MCP workspace info tool by making JSON output optional and cleaning up the formatting for better LLM consumption.

feat: improve MCP workspace info output with optional JSON and clean formatting

---

package.json

chore(oxlint) - upgrade oxlint version

---

scopes/component/snapping/version-maker.ts

fix: populate dependencies graph for autosnapped components

---

scopes/component/graph/graph-cmd.ts

This PR deprecates the `--include-local-only` flag in the `bit graph` command and makes local-only behavior the default, while adding a new `--include-dependencies` flag to preserve the previous recursive behavior.
- **Deprecated `--include-local-only` flag**: Added "DEPRECATED" prefix to the flag description
- **Made local-only the default behavior**: By default, `bit graph` now shows only workspace components and their local relationships
- **Added `--include-dependencies` flag**: New flag to include all dependencies recursively (preserves the original default behavior)
- **Updated both visual and JSON output**: Both `report()` and `json()` methods now consistently apply the new logic
- The deprecated `--include-local-only` flag still works but shows a deprecation message
- Users can …

feat(graph): deprecate include-local-only flag and add include-dependencies flag

---

scopes/mcp/cli-mcp-server/cli-mcp-server.main.runtime.ts

Replaces vulnerable `execSync` calls with secure `spawnSync` to prevent command injection attacks.

fix(mcp): replace execSync with spawnSync to prevent command injection

---

.bitmap
.circleci/config.yml
workspace.jsonc

chore(deps) - update internal deps (#9785)

---

components/legacy/constants/constants.ts
components/scope/remotes/remote-resolver/remote-resolver.ts
scopes/cloud/cloud/cloud.main.runtime.ts
scopes/harmony/api-server/api-server.main.runtime.ts

feature(config) - allow specify protocol for symphony url

---

scopes/git/ci/ci.main.runtime.ts

Fixes the git rebase error that occurs during `bit ci merge --build` when there are unstaged changes after the commit operation.
The issue was that after committing `.bitmap` and `pnpm-lock.yaml` files, other files might still be modified but unstaged, causing the subsequent `git pull --rebase` to fail with "You have unstaged changes" error.
**Changes:**
- Added git status logging before and after commit operations for better debugging
- Implemented stash/unstash pattern before the final git pull rebase operation
- Applied the same approach used in the initial pull operation to handle unstaged changes safely

fix(ci): handle unstaged changes during merge git rebase operation

---

.circleci/config.yml

ci: update pnpm to v10

---

.circleci/config.yml
scripts/circular-deps-check/ANALYSIS.md
scripts/circular-deps-check/README.md
scripts/circular-deps-check/baseline-cycles-full.json
scripts/circular-deps-check/baseline-cycles.json
scripts/circular-deps-check/check-circular-deps.js
scripts/circular-deps-check/ci-check.sh
scripts/circular-deps-check/create-baseline.js
scripts/circular-deps-check/diff-cycles.js

Add comprehensive circular dependencies measurement system with CI integration.
Establishes baseline of 2,066 cycles and prevents regressions in future PRs.

feat: add circular dependencies monitoring and CI integration

---

e2e/harmony/lanes/lane-import-git-branch.e2e.ts

Adds a comprehensive E2E test for the `bit lane import --branch` feature that ensures proper integration with git branch switching.
The test validates that when importing a lane with `--branch`, making changes, and then switching back to the main git branch, Bit correctly switches the current lane back to 'main' and maintains a clean status.

feat: add e2e test for lane import --branch with git switch main

---

scopes/git/ci/ci.main.runtime.ts
scopes/git/ci/source-branch-detector.ts

When `bit ci merge` runs on CI after a PR is merged, it was unable to detect the source branch because:
- The SourceBranchDetector was querying the current HEAD commit
- But HEAD is the NEW commit created by `bit ci merge` itself (always on main)
- This commit has no PR information associated with it
Capture the initial commit SHA at the start of `mergePr()` before any git operations, then pass it to SourceBranchDetector to query the correct commit that contains the PR merge information.
The GitHub API now correctly queries the merge commit that brought the PR into main, not the subsequent commit created by bit ci merge. This allows successful detection and deletion of lanes even when running on main branch.
This is a critical fix for the enhanced lane deletion feature in PR #9958

fix: use initial commit SHA for source branch detection in ci merge

---

scopes/dependencies/dependency-resolver/dependency-resolver.main.runtime.ts

Related previous PR: https://github.com/teambit/bit/pull/9955
-
-
-

fix: allow aliases to be used in dependencies

---

workspace.jsonc

fix: workspace.jsonc conflict
